SonarSource/sonar-dotnet

- README.md
This pull request includes a new README document with minimal project information and a link to the plugin's SonarQube documentation.
> Added a README document with link to the SonarQube wiki

- sonaranalyzer-dotnet/rspec/cs/S3236_c#.html
- sonaranalyzer-dotnet/rspec/cs/S3236_c#.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.resx
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/ArgumentSpecifiedForCallerInfoParameter.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S3236.html
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/ArgumentSpecifiedForCallerInfoParameter.cs
> Fix S3236: Rule should not report on CallerMemberName

- sonaranalyzer-dotnet/its/expected/Nancy/Nancy-{34576216-0DCA-4B0F-A0DC-9075E75A676F}-S2070.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Cluster-{6AB00F61-269A-4501-B06A-026707F000A7}-S2070.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/DoNotCallInsecureSecurityAlgorithm.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/InsecureEncryptionAlgorithm.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/InsecureHashAlgorithm.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/InsecureEncryptionAlgorithm.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/InsecureHashAlgorithm.cs
> Update rules S2278 and S2070 to handle more obsolete security algorithms

- sonaranalyzer-dotnet/rspec/cs/S1451_c#.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/CheckFileLicense.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/CheckFileLicenseCodeFixProvider.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S1451.html
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/Rules/CheckFileLicenseTest.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/CheckFileLicense_DefaultValues.Fixed.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/CheckFileLicense_DefaultValues.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/CheckFileLicense_MultiLineLicenseStartWithNamespace.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/CheckFileLicense_MultiSingleLineLicenseStartWithNamespace.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/CheckFileLicense_NoLicenseStartWithNamespace.Fixed.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/CheckFileLicense_NoLicenseStartWithNamespace.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/CheckFileLicense_NoLicenseStartWithUsing.Fixed.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/CheckFileLicense_NoLicenseStartWithUsing.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/CheckFileLicense_OutdatedLicenseStartWithNamespace.Fixed.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/CheckFileLicense_OutdatedLicenseStartWithNamespace.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/CheckFileLicense_OutdatedLicenseStartWithUsing.Fixed.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/CheckFileLicense_OutdatedLicenseStartWithUsing.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/CheckFileLicense_SingleLineLicenseStartWithNamespace.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/CheckFileLicense_SingleLineLicenseStartWithUsing.cs
> Fix S1451: Rule should handle multiple single-line comments

- sonaranalyzer-dotnet/its/expected/Nancy/Nancy-{34576216-0DCA-4B0F-A0DC-9075E75A676F}-S2372.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka-{5DEDDF90-37F0-48D3-A0B0-A5CBD8A7E377}-S2372.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/PropertyGetterWithThrow.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/ThrowReservedExceptions.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Rules/PropertyGetterWithThrowBase.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Rules/PropertyGetterWithThrow.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/Rules/PropertyGetterWithThrowTest.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/PropertyGetterWithThrow.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/PropertyGetterWithThrow.vb
> Rule S2372: it's fine to throw some types of exception from a getter

- sonar-csharp-plugin/src/main/java/org/sonar/plugins/csharp/CSharpMsBuildIntegrationProvider.java
> Deprecate sonar.cs.msbuild.testProjectPattern

- sonaranalyzer-dotnet/its/expected/Nancy/Nancy-{34576216-0DCA-4B0F-A0DC-9075E75A676F}-S3925.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/PrivateFieldUsedAsLocalVariable.cs
> Fix 1450: False positive in VS2017 but not VS2015

- sonaranalyzer-dotnet/its/expected/akka.net/Akka-{5DEDDF90-37F0-48D3-A0B0-A5CBD8A7E377}-S3962.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Cluster-{6AB00F61-269A-4501-B06A-026707F000A7}-S3962.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Cluster.Tests-{C8D6A95C-50BF-4416-A212-86B18B87220D}-S3962.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.MultiNodeTestRunner.Shared-{964F0EC5-FBE6-47C5-8AE6-145114D5DB8C}-S3962.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Persistence.TestKit-{AD9418B6-C452-4169-94FB-D43DE0BFA966}-S3962.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Persistence.Tests-{4492004A-A8D0-45B0-BACC-05BA2F38EC55}-S3962.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Remote-{EA4FF8FD-7C53-49C8-B9AA-02E458B3E6A7}-S3962.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Remote.AkkaIOTransport-{45AAAF15-C5D7-4107-94F0-766A32ECB9AE}-S3962.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Remote.Tests-{95E921AB-1F5A-4AF9-B7FE-284E317A97F4}-S3962.json
- sonaranalyzer-dotnet/its/expected/akka.net/SymbolLookup-{3007A692-A050-4F12-9187-4AE6C6106A66}-S3962.json
- sonaranalyzer-dotnet/rspec/cs/S3962_c#.html
- sonaranalyzer-dotnet/rspec/cs/S3962_c#.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.resx
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/UseConstantsWhereAppropriate.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S3962.html
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/Rules/UseConstantsWhereAppropriateTest.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/UseConstantsWhereAppropriate.cs
> Rule S3962: 'static readonly' constants should be 'const' instead

- sonaranalyzer-dotnet/its/expected/Nancy/Nancy-{34576216-0DCA-4B0F-A0DC-9075E75A676F}-S3963.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Demo.Authentication.Forms-{98940A30-1B48-4F71-A6BA-85F0AAF31A2F}-S3963.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Demo.Authentication.Stateless-{BAE74CD5-57C2-40E3-8F7A-EDE5721C2ACC}-S3963.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Demo.Hosting.Aspnet-{E127FED3-01C0-41BA-BF83-D8DCDD827D6A}-S3963.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Demo.ModelBinding-{1258BFCD-3BAD-4373-B786-4D698EC3C157}-S3963.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Demo.Validation-{F417B81C-B914-4BFD-8299-6BBD11072B01}-S3963.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Embedded-{D8EBA39B-63AE-4A66-BD0E-F7F95E572135}-S3963.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Hosting.Aspnet-{15B7F794-0BB2-4B66-AD78-4A951F1209B2}-S3963.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Testing-{D79203C0-B672-4751-9C95-C3AB7D3FEFBE}-S3963.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka-{5DEDDF90-37F0-48D3-A0B0-A5CBD8A7E377}-S3963.json
- sonaranalyzer-dotnet/rspec/cs/S3963_c#.html
- sonaranalyzer-dotnet/rspec/cs/S3963_c#.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.resx
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/InitializeStaticFieldsInline.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S3963.html
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/Rules/InitializeStaticFieldsInlineTest.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/InitializeStaticFieldsInline.cs
> Rule S3963: 'static fields' should be initialized inline

- sonaranalyzer-dotnet/its/expected/Nancy/Nancy-{34576216-0DCA-4B0F-A0DC-9075E75A676F}-S3967.json
- sonaranalyzer-dotnet/rspec/cs/S3967_c#.html
- sonaranalyzer-dotnet/rspec/cs/S3967_c#.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.resx
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/PreferJaggedArraysOverMultidimensional.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S3967.html
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/Rules/PreferJaggedArraysOverMultidimensionalTest.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/PreferJaggedArraysOverMultidimensional.cs
> Rule S3967: Multidimensional arrays should not be used

- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/tools-cs/install.ps1
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/tools-cs/uninstall.ps1
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/tools-vbnet/install.ps1
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/tools-vbnet/uninstall.ps1
> Rewrite powershell to use only powershell 2.0 syntax

- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Cluster.Sharding.Tests-{B369F314-4D37-4AC1-B4FB-64FF671AF0BC}-S1144.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Persistence.Tests-{4492004A-A8D0-45B0-BACC-05BA2F38EC55}-S1144.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Tests-{3F786C7D-70E3-4836-8B33-EC9A5AF72330}-S1144.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/UnusedPrivateMember.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/UnusedPrivateMember.cs
> Update S1144 to handle unused internal types

- sonar-csharp-plugin/src/main/java/org/sonar/plugins/csharp/RoslynProfileExporter.java
- sonar-csharp-plugin/src/test/java/org/sonar/plugins/csharp/RoslynProfileExporterTest.java
- sonar-csharp-plugin/src/test/resources/RoslynProfileExporterTest/empty_string_value.xml
> Update the C# plugin to properly handle null values and default values.

- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Authentication.Forms-{E8B18958-7C8A-4FBA-AF00-3041C34A20CE}-S3996.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka-{5DEDDF90-37F0-48D3-A0B0-A5CBD8A7E377}-S3990.json
- sonaranalyzer-dotnet/rspec/cs/S3996_c#.html
- sonaranalyzer-dotnet/rspec/cs/S3996_c#.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/StringUtils.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.resx
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/UriPropertiesShouldNotBeStrings.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SonarAnalyzer.CSharp.csproj
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S3996.html
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/Helpers/StringUtilsTest.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/Rules/UriPropertiesShouldNotBeStringsTest.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/SonarAnalyzer.UnitTest.csproj
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/UriPropertiesShouldNotBeStrings.cs
> Rule S3996: URI properties should not be strings

- sonaranalyzer-dotnet/build/rspec.ps1
- sonaranalyzer-dotnet/rspec/cs/S3449_c#.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.resx
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/RspecStrings.resx
> Update S3449: replace XML-encoded characters in description

- sonaranalyzer-dotnet/rspec/cs/S4000_c#.html
- sonaranalyzer-dotnet/rspec/cs/S4000_c#.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.resx
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/PointersShouldBePrivate.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S4000.html
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/Rules/PointersShouldBePrivateTest.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/PointersShouldBePrivate.cs
> Rule S4000: Pointers to unmanaged memory should not be visible

- sonaranalyzer-dotnet/its/expected/Nancy/Nancy-{34576216-0DCA-4B0F-A0DC-9075E75A676F}-S3881.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Hosting.Self-{AA7F66EB-EC2C-47DE-855F-30B3E6EF2134}-S3881.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Hosting.Self.Tests-{CA24ED85-DD68-4C10-B80A-D81C6745FCB8}-S3881.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Testing-{D79203C0-B672-4751-9C95-C3AB7D3FEFBE}-S3881.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Testing.Tests-{8EB9E15A-4B65-4C80-B834-9A7773750666}-S3881.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Tests-{776D244D-BC4D-4BBB-A478-CAF2D04520E1}-S3881.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.ViewEngines.Razor-{2C6F51DF-015C-4DB6-B44C-0E5E4F25E2A9}-S3881.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.ViewEngines.Spark.Tests-{06F89662-C2F0-4C1D-8581-E0C4A615B7E2}-S3881.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka-{5DEDDF90-37F0-48D3-A0B0-A5CBD8A7E377}-S3881.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Cluster-{6AB00F61-269A-4501-B06A-026707F000A7}-S3881.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Cluster.Tests-{C8D6A95C-50BF-4416-A212-86B18B87220D}-S3881.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.DI.TestKit-{D8DB14A5-6147-4512-BF5C-683FDCA6190C}-S3881.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.MultiNodeTestRunner-{C1113300-74F1-446A-9914-3020C842EDF1}-S3881.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.NodeTestRunner-{28520F30-2868-4BD3-9CAE-AC27226C24E3}-S3881.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Persistence.Sql.Common-{3B9E6211-9488-4DB5-B714-24248693B38F}-S3881.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Persistence.TestKit-{AD9418B6-C452-4169-94FB-D43DE0BFA966}-S3881.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Persistence.Tests-{4492004A-A8D0-45B0-BACC-05BA2F38EC55}-S3881.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Remote-{EA4FF8FD-7C53-49C8-B9AA-02E458B3E6A7}-S3881.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.TestKit-{0D3CBAD0-BBDB-43E5-AFC4-ED1D3ECDC224}-S3881.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.TestKit.NUnit-{BEF84A6F-32C4-4ACF-AFC3-7B5FCA6F209E}-S3881.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.TestKit.Xunit-{11F4D4B8-7E07-4457-ABF2-609B3E7B2649}-S3881.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.TestKit.Xunit2-{7DBD5C17-5E9D-40C4-9201-D092751532A7}-S3881.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/KnownMethods.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/ImplementIDisposableCorrectly.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Common/SecondaryLocation.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/SymbolHelper.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/ImplementIDisposableCorrectly.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/Verifier.cs
You should open the code in VS. I refactored the original implementation to get rid of many of the method arguments in the analyzer. Also fixed a bug in the Verifier class.
If you have ideas how to simplify the Checker class, I am open for suggestions :)
Fix #277
> Update S3881: should require a call to base.Dispose(bool)

- sonaranalyzer-dotnet/its/expected/Nancy/Nancy-{34576216-0DCA-4B0F-A0DC-9075E75A676F}-S4004.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Validation.DataAnnotations-{701765DC-F4F2-4943-A37F-6ED253198158}-S4004.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.ViewEngines.Razor-{2C6F51DF-015C-4DB6-B44C-0E5E4F25E2A9}-S4004.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.ViewEngines.Spark-{4B7E35DF-1569-4346-B180-A09615723095}-S4004.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka-{5DEDDF90-37F0-48D3-A0B0-A5CBD8A7E377}-S4004.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Remote-{EA4FF8FD-7C53-49C8-B9AA-02E458B3E6A7}-S4004.json
- sonaranalyzer-dotnet/its/expected/akka.net/SymbolLookup-{3007A692-A050-4F12-9187-4AE6C6106A66}-S4004.json
- sonaranalyzer-dotnet/rspec/cs/S4004_c#.html
- sonaranalyzer-dotnet/rspec/cs/S4004_c#.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.resx
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/CollectionPropertiesShouldBeReadOnly.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/ProjectTypeHelper.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S4004.html
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/Rules/CollectionPropertiesShouldBeReadOnlyTest.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/CollectionPropertiesShouldBeReadOnly.cs
> Rule S4004: Collection properties should be readonly

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/CognitiveComplexity.cs
> Update S3776: Disable by default because it is a parametrized rule

- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Tests-{3F786C7D-70E3-4836-8B33-EC9A5AF72330}-S2589.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/ConditionEvaluatesToConstant.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/ConditionEvaluatesToConstant.cs
> Update S2589 and S2583: raise issues for "true" and "false" literals

- sonaranalyzer-dotnet/build/rspec.ps1
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.resx
- sonaranalyzer-dotnet/src/SonarAnalyzer.RuleDescriptorGenerator/Descriptors/RuleDetail.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/RuleDescriptors/RuleDetail.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/RuleDetailBuilder.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/RspecStrings.resx
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/Common/RuleDescriptorTest.cs
> Use the Category property from RSPEC to determine the rule type

- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/PackagingTests/RuleTypeTests.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/SonarAnalyzer.UnitTest.csproj
Hah, I used region as well. Shame on me!
> Add test for rule type changes

- its/projects/EmptyModuleWithTestResults/mod1/Test.cs
- its/projects/EmptyModuleWithTestResults/reports/nunit.xml
- its/projects/EmptyModuleWithTestResults/reports/vstest.trx
- its/src/test/java/com/sonar/it/csharp/UnitTestResultsTest.java
- sonar-csharp-plugin/src/main/java/org/sonar/plugins/csharp/CSharpCodeCoverageProvider.java
- sonar-csharp-plugin/src/main/java/org/sonar/plugins/csharp/CSharpUnitTestResultsProvider.java
- sonar-dotnet-tests-library/src/main/java/org/sonar/plugins/dotnet/tests/CoverageReportImportSensor.java
- sonar-dotnet-tests-library/src/main/java/org/sonar/plugins/dotnet/tests/UnitTestResultsImportSensor.java
- sonar-dotnet-tests-library/src/test/java/org/sonar/plugins/dotnet/tests/CoverageReportImportSensorTest.java
- sonar-dotnet-tests-library/src/test/java/org/sonar/plugins/dotnet/tests/UnitTestResultsImportSensorTest.java
> Fix Sensors: Unit/Integration test results are skipped when module doesn't contain cs file 

- sonaranalyzer-dotnet/its/expected/Nancy/Nancy-{34576216-0DCA-4B0F-A0DC-9075E75A676F}-S4017.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Hosting.Aspnet-{15B7F794-0BB2-4B66-AD78-4A951F1209B2}-S4017.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Hosting.Self-{AA7F66EB-EC2C-47DE-855F-30B3E6EF2134}-S4017.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Testing-{D79203C0-B672-4751-9C95-C3AB7D3FEFBE}-S4017.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Tests-{776D244D-BC4D-4BBB-A478-CAF2D04520E1}-S4017.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka-{5DEDDF90-37F0-48D3-A0B0-A5CBD8A7E377}-S4017.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Cluster-{6AB00F61-269A-4501-B06A-026707F000A7}-S4017.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Cluster.Sharding-{A05C31E8-0246-46A1-B3BC-4D6FE7A9AA49}-S4017.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Persistence-{FCA84DEA-C118-424B-9EB8-34375DFEF18A}-S4017.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Remote-{EA4FF8FD-7C53-49C8-B9AA-02E458B3E6A7}-S4017.json
- sonaranalyzer-dotnet/rspec/cs/S4017_c#.html
- sonaranalyzer-dotnet/rspec/cs/S4017_c#.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.resx
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/DoNotNestTypesInArguments.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S4017.html
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/PackagingTests/RuleTypeTests.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/Rules/DoNotNestTypesInArgumentsTest.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/DoNotNestTypesInArguments.cs
> Rule S4017: Method signatures should not contain nested generic types

- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Tests-{776D244D-BC4D-4BBB-A478-CAF2D04520E1}-S4022.json
- sonaranalyzer-dotnet/rspec/cs/S4022_c#.html
- sonaranalyzer-dotnet/rspec/cs/S4022_c#.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.resx
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/EnumStorageNeedsToBeInt32.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S4022.html
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/PackagingTests/RuleTypeTests.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/Rules/EnumStorageNeedsToBeInt32Test.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/EnumStorageNeedsToBeInt32.cs
> Rule S4022: Enums storage should be Int32

- sonaranalyzer-dotnet/its/expected/Ember-MM/Ember.Plugins-{9496C697-5AFD-4813-AEDC-AF33FACEADF0}-S4027.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy-{34576216-0DCA-4B0F-A0DC-9075E75A676F}-S4027.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Hosting.Self-{AA7F66EB-EC2C-47DE-855F-30B3E6EF2134}-S4027.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Hosting.Self.Tests-{CA24ED85-DD68-4C10-B80A-D81C6745FCB8}-S4027.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Tests-{776D244D-BC4D-4BBB-A478-CAF2D04520E1}-S4027.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka-{5DEDDF90-37F0-48D3-A0B0-A5CBD8A7E377}-S4027.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Cluster.Tools-{5CF8A8BE-B634-473F-BB01-EBA878746BD4}-S4027.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Persistence-{FCA84DEA-C118-424B-9EB8-34375DFEF18A}-S4027.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Persistence.Tests-{4492004A-A8D0-45B0-BACC-05BA2F38EC55}-S4027.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Remote-{EA4FF8FD-7C53-49C8-B9AA-02E458B3E6A7}-S4027.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Remote.TestKit-{E5957C3E-2B1E-469F-A680-7953B4DEA31B}-S4027.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.TestKit.Xunit-{11F4D4B8-7E07-4457-ABF2-609B3E7B2649}-S4027.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.TestKit.Xunit2-{7DBD5C17-5E9D-40C4-9201-D092751532A7}-S4027.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Tests-{3F786C7D-70E3-4836-8B33-EC9A5AF72330}-S4027.json
- sonaranalyzer-dotnet/its/expected/akka.net/FaultTolerance-{FBEBD803-AEFC-44B1-A429-6143C3288CA4}-S4027.json
- sonaranalyzer-dotnet/rspec/cs/S4027_c#.html
- sonaranalyzer-dotnet/rspec/cs/S4027_c#.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/CollectionUtils.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.resx
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/ExceptionsNeedStandardConstructors.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S4027.html
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/Helpers/CollectionUtilsTest.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/PackagingTests/RuleTypeTests.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/Rules/ExceptionsNeedStandardConstructorsTest.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/SonarAnalyzer.UnitTest.csproj
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/ExceptionsNeedStandardConstructors.cs
> Rule S4027: Exceptions should provide standard constructors

- sonaranalyzer-dotnet/its/expected/Ember-MM/Ember.Plugins-{9496C697-5AFD-4813-AEDC-AF33FACEADF0}-S3906.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Remote-{EA4FF8FD-7C53-49C8-B9AA-02E458B3E6A7}-S3906.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.TestKit-{0D3CBAD0-BBDB-43E5-AFC4-ED1D3ECDC224}-S3906.json
- sonaranalyzer-dotnet/its/expected/akka.net/SymbolLookup-{3007A692-A050-4F12-9187-4AE6C6106A66}-S3906.json
- sonaranalyzer-dotnet/rspec/cs/S3906_c#.html
- sonaranalyzer-dotnet/rspec/cs/S3906_c#.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.resx
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/DeclareEventHandlersCorrectly.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S3906.html
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/PackagingTests/RuleTypeTests.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/Rules/DeclareEventHandlersCorrectlyTest.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/DeclareEventHandlersCorrectly.cs
> Rule S3906: Declare event handlers correctly

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/MultilineBlocksWithoutBrace.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/MultilineBlocksWithoutBrace.cs
> Fix S2681: Rule should not read parent block as next block

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/CollectionUtils.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/MethodParameterLookup.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/ParametersCorrectOrder.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/ParametersCorrectOrder.cs
> Update S2234: Add support for constructors

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/SymbolicExecution/InvocationVisitor.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/NullPointerDereference.cs
@tvsonar Thx for the catch it allowed me to handle more wrong possible calls.
> Refactor handling of nameof in SE to catch more cases

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/SymbolicExecution/ExplodedGraph.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/ConditionEvaluatesToConstant.cs
Fix #422 
@tvsonar if you want to have a look too.
> Improve Symbolic Execution to learn constraints implied by default()

- build.ps1
- sonaranalyzer-dotnet/build.cmd
- sonaranalyzer-dotnet/build/Version.props
- sonaranalyzer-dotnet/build/build-utils.ps1
- sonaranalyzer-dotnet/build/build.ps1
- sonaranalyzer-dotnet/src/AssemblyInfo.Shared.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.RuleDescriptorGenerator/Descriptor.cs.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.RuleDescriptorGenerator/Descriptor.vbnet.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/SonarAnalyzer.CSharp.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/SonarAnalyzer.VisualBasic.nuspec
> Improve build script and nuspec files

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/RemovableDeclarationCollector.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/CheckFileLicense.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/MemberShouldBeStatic.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/MethodName.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/MethodOverloadOptionalParameter.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/MethodOverrideChangedDefaultValue.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/MethodOverrideChangedDefaultValueCodeFixProvider.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/TooManyParameters.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/UseValueParameter.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/SymbolHelper.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Rules/OptionalParameterBase.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Rules/PublicMethodWithMultidimensionalArrayBase.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/Helpers/SymbolHelperTest.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/UseValueParameter.cs
> Update S3237: Add exception for empty properties from interfaces

- its/src/test/java/com/sonar/it/csharp/MetricsTest.java
> Refactor MetricsTest.java to fail fast when not on Windows

- sonar-dotnet-tests-library/src/main/java/org/sonar/plugins/dotnet/tests/CoverageReportImportSensor.java
- sonar-dotnet-tests-library/src/test/java/org/sonar/plugins/dotnet/tests/CoverageReportImportSensorTest.java
> Support many coverage reports

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/DoNotDecreaseMemberVisibility.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/DoNotDecreaseMemberVisibility.cs
> Fix S4015: Rule should not raise on 'new' or 'override' members

- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Persistence-{FCA84DEA-C118-424B-9EB8-34375DFEF18A}-S1764.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Tests-{3F786C7D-70E3-4836-8B33-EC9A5AF72330}-S1764.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/KnownMethods.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/BinaryOperationWithIdenticalExpressions.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Rules/BinaryOperationWithIdenticalExpressionsBase.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Rules/BinaryOperationWithIdenticalExpressions.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/BinaryOperationWithIdenticalExpressions.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/BinaryOperationWithIdenticalExpressions.vb
> Update S1764: Comparing the same object with Object.Equals() method

- sonaranalyzer-dotnet/rspec/cs/S4061_c#.html
- sonaranalyzer-dotnet/rspec/cs/S4061_c#.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.resx
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/UseParamsForVariableArguments.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S4061.html
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/PackagingTests/RuleTypeTests.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/Rules/UseParamsForVariableArgumentsTest.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/UseParamsForVariableArguments.cs
> Rule S4061: 'params' should be use instead of 'varargs'

- sonaranalyzer-dotnet/its/expected/Nancy/Nancy-{34576216-0DCA-4B0F-A0DC-9075E75A676F}-S4059.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka-{5DEDDF90-37F0-48D3-A0B0-A5CBD8A7E377}-S4059.json
- sonaranalyzer-dotnet/rspec/cs/S4059_c#.html
- sonaranalyzer-dotnet/rspec/cs/S4059_c#.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.resx
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/PropertyNamesShouldNotMatchGetMethods.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S4059.html
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/PackagingTests/RuleTypeTests.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/Rules/PropertyNamesShouldNotMatchGetMethodsTest.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/PropertyNamesShouldNotMatchGetMethods.cs
> Rule S4059: Property names should not match get methods

- sonaranalyzer-dotnet/rspec/cs/S4070_c#.html
- sonaranalyzer-dotnet/rspec/cs/S4070_c#.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.resx
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/DoNotMarkEnumsWithFlags.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S4070.html
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/PackagingTests/RuleTypeTests.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/Rules/DoNotMarkEnumsWithFlagsTest.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/DoNotMarkEnumsWithFlags.cs
> Rule S4070: Non-flags enums should not be marked with "FlagsAttribute"

- sonaranalyzer-dotnet/rspec/cs/S4047_c#.html
- sonaranalyzer-dotnet/rspec/cs/S4047_c#.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.Designer.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.resx
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/UseGenericWithRefParameters.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S4047.html
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/PackagingTests/RuleTypeTests.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/Rules/UseGenericWithRefParametersTest.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/UseGenericWithRefParameters.cs
> Rule S4047: Generics should be used when appropriate

- sonaranalyzer-dotnet/its/expected/Nancy/Nancy-{34576216-0DCA-4B0F-A0DC-9075E75A676F}-S4069.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka-{5DEDDF90-37F0-48D3-A0B0-A5CBD8A7E377}-S4069.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Cluster-{6AB00F61-269A-4501-B06A-026707F000A7}-S4069.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Remote-{EA4FF8FD-7C53-49C8-B9AA-02E458B3E6A7}-S4069.json
- sonaranalyzer-dotnet/rspec/cs/S4069_c#.html
- sonaranalyzer-dotnet/rspec/cs/S4069_c#.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.resx
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/OperatorOverloadsShouldHaveNamedAlternatives.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S4069.html
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/PackagingTests/RuleTypeTests.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/Rules/OperatorOverloadsShouldHaveNamedAlternativesTest.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/OperatorOverloadsShouldHaveNamedAlternatives.cs
> Rule S4069: Operator overloads should have named alternatives

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/AvoidExcessiveInheritance.cs
> Update description for S110

- sonaranalyzer-dotnet/src/SonarAnalyzer.RuleDocGenerator.Web/Program.cs
> Tweak web rule generator to accept target path as a parameter.

- pom.xml
- sonar-csharp-plugin/pom.xml
- sonar-dotnet-shared-library/pom.xml
- sonar-dotnet-tests-library/pom.xml
- sonaranalyzer-dotnet/build/Version.props
- sonaranalyzer-dotnet/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/SonarAnalyzer.CSharp/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/SonarAnalyzer.RuleDocGenerator.CSharp/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/SonarAnalyzer.RuleDocGenerator.VisualBasic/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/SonarAnalyzer.VisualBasic/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/pom.xml
- sonaranalyzer-dotnet/src/AssemblyInfo.Shared.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.RuleDescriptorGenerator/Descriptor.cs.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.RuleDescriptorGenerator/Descriptor.vbnet.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/SonarAnalyzer.CSharp.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/SonarAnalyzer.VisualBasic.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/source.extension.vsixmanifest
> [NO MERGE] Bump version to 6.3

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/ControlFlowGraph/ControlFlowGraphBuilder.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/ControlFlowGraph/SyntaxNodeBased/ControlFlowGraphBuilder.cs
A cfg refactoring I've been playing with. Started as a learning exercise, but I think it's worth merging. It makes some bits simpler and makes code shorter.
The change includes try-catch-finally, all the test (incl. its) pass.
> [NO MERGE] CFG builder refactoring

- sonaranalyzer-dotnet/rspec/cs/S2225_c#.html
- sonaranalyzer-dotnet/rspec/cs/S2225_c#.json
- sonaranalyzer-dotnet/rspec/cs/S4050_c#.html
- sonaranalyzer-dotnet/rspec/cs/S4069_c#.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.Designer.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.resx
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S2225.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S4050.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S4069.html
Haven't updated S1751 because of the thread going on.
> Update RSPEC metadata

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/ObjectsShouldNotBeDisposedMoreThanOnce.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/ObjectsShouldNotBeDisposedMoreThanOnce.cs
> Fix and Update S3966: Rule should not throw cast exception + detect Dispose on this

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/StringFormatValidator.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/StringFormatRuntimeExceptionFreeValidator.cs
> Fix S2275: Rule should not trigger on space before alignment

- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.ViewEngines.Razor-{2C6F51DF-015C-4DB6-B44C-0E5E4F25E2A9}-S1696.json
- sonaranalyzer-dotnet/rspec/cs/S1696_c#.html
- sonaranalyzer-dotnet/rspec/cs/S1696_c#.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.resx
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/DoNotCatchNullReferenceException.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S1696.html
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/PackagingTests/RuleTypeTests.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/Rules/DoNotCatchNullReferenceExceptionTest.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/DoNotCatchNullReferenceException.cs
> Rule S1696: 'NullReferenceException' should not be caught

- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Tests-{3F786C7D-70E3-4836-8B33-EC9A5AF72330}-S2325.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/MemberShouldBeStatic.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/MemberShouldBeStatic.cs
> Fix S2325: Should raise issues for methods and properties with SuppressMessage attribute 

- scripts/rspec/cs_strings.restext
- sonaranalyzer-dotnet/rspec/cs/S3431_c#.html
- sonaranalyzer-dotnet/rspec/cs/S3431_c#.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.resx
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/ExpectedExceptionAttributeShouldNotBeUsed.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S3431.html
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/PackagingTests/RuleTypeTests.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/Rules/ExpectedExceptionAttributeShouldNotBeUsedTest.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/SonarAnalyzer.UnitTest.csproj
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/ExpectedExceptionAttributeShouldNotBeUsed.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/packages.SonarAnalyzer.UnitTest.config
> Rule S3431: 'ExpectedExceptionAttribute' should not be used

- sonar-dotnet-tests-library/src/main/java/org/sonar/plugins/dotnet/tests/NUnitTestResultsFileParser.java
- sonar-dotnet-tests-library/src/test/java/org/sonar/plugins/dotnet/tests/NUnitTestResultsFileParserTest.java
- sonar-dotnet-tests-library/src/test/resources/nunit/nunit3_sample.xml
> Update plugin to support NUnit 3 test results

- sonaranalyzer-dotnet/rspec/cs/S3881_c#.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S3881.html
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/ImplementIDisposableCorrectly.cs
> Update S3881: Correct documentation and add more unit tests

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/ExceptionShouldNotBeThrownFromUnexpectedMethods.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/ExceptionShouldNotBeThrownFromUnexpectedMethods.cs
> Fix S3877: do not throw ArgumentNullException on ravendb

- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Rules/PropertyGetterWithThrowBase.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/PropertyGetterWithThrow.cs
> Fix S2372: do not throw ArgumentNullException on nlog

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/ReturnEmptyCollectionInsteadOfNull.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/ReturnEmptyCollectionInsteadOfNull.cs
> Fix S1168: Rule should not report when returning null within a lambda

- sonaranalyzer-dotnet/its/expected/Nancy/Nancy-{34576216-0DCA-4B0F-A0DC-9075E75A676F}-S4225.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Authentication.Basic.Tests-{2026DD2D-E041-4A14-8A04-D5B39B8B7C40}-S4225.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Authentication.Forms.Tests-{4E974051-38C2-4B5D-A6B1-F265A428A673}-S4225.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Demo.Authentication.Forms.TestingDemo-{948A8EF6-D50C-45EA-9AFD-7A4723ADAB0B}-S4225.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Embedded.Tests-{6EED2486-39BF-491D-B033-720DFCFD1211}-S4225.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Encryption.MachineKey.Tests-{429873F5-1E53-4ECC-A9EC-7950C789C6DF}-S4225.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Hosting.Aspnet.Tests-{D0F1D7F4-0D48-49AE-9E33-005926B58B1D}-S4225.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Hosting.Self.Tests-{CA24ED85-DD68-4C10-B80A-D81C6745FCB8}-S4225.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Metadata.Modules.Tests-{508A3A68-2012-4E62-925F-2F3083A013FC}-S4225.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Owin.Tests-{34DDDA42-4041-4F92-87A6-F0E8CE12C7E3}-S4225.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Testing.Tests-{8EB9E15A-4B65-4C80-B834-9A7773750666}-S4225.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Tests-{776D244D-BC4D-4BBB-A478-CAF2D04520E1}-S4225.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Validation.DataAnnotations.Tests-{8F9F910D-416E-4B28-BE59-D76670405F56}-S4225.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Validation.FluentValidation.Tests-{FBC35268-377B-4DBE-87E3-B22D1314BEC6}-S4225.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.ViewEngines.DotLiquid.Tests-{A3BF6450-DE9A-4C11-8E3C-66D9A8EC93F5}-S4225.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.ViewEngines.Markdown.Tests-{8EE6F976-F11F-44B3-B065-F5AAA598B30D}-S4225.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.ViewEngines.Razor.Tests-{FE32460D-547C-4EB9-A768-541255CCAA83}-S4225.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.ViewEngines.Spark.Tests-{06F89662-C2F0-4C1D-8581-E0C4A615B7E2}-S4225.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka-{5DEDDF90-37F0-48D3-A0B0-A5CBD8A7E377}-S4225.json
- sonaranalyzer-dotnet/rspec/cs/S4225_c#.html
- sonaranalyzer-dotnet/rspec/cs/S4225_c#.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.resx
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/ExtensionMethodShouldNotExtendObject.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S4225.html
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/PackagingTests/CsRuleTypeMapping.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/Rules/ExtensionMethodShouldNotExtendObjectTest.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/ExtensionMethodShouldNotExtendObject.cs
> Rule S4225: Extension methods should not extend "object"

- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/AnalysisContextExtensions.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/SonarAnalysisContext.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/Helpers/SonarAnalysisContextTest.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/Verifier.cs
Fixing a couple of issues discovered during end-to-end testing
> Fixed suppression function logic

- scripts/rspec/rspec.ps1
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.resx
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/DiagnosticDescriptorBuilder.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/DiagnosticReportHelper.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/RspecStrings.resx
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/Helpers/DiagnosticDescriptorBuilderTest.cs
Fix sonarsource/sonarlint-visualstudio#294
> [DO NOT MERGE] Changing help link to point to the new rules web site

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/CheckArgumentException.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/CheckArgumentException.cs
> Fix S3928: Rule throws NullReferenceException

- its/src/test/java/com/sonar/it/csharp/CoverageTest.java
- its/src/test/java/com/sonar/it/csharp/UnitTestResultsTest.java
- sonar-dotnet-tests-library/pom.xml
- sonar-dotnet-tests-library/src/main/java/org/sonar/plugins/dotnet/tests/CoverageAggregator.java
- sonar-dotnet-tests-library/src/main/java/org/sonar/plugins/dotnet/tests/CoverageReportImportSensor.java
- sonar-dotnet-tests-library/src/main/java/org/sonar/plugins/dotnet/tests/UnitTestResultsAggregator.java
- sonar-dotnet-tests-library/src/main/java/org/sonar/plugins/dotnet/tests/UnitTestResultsImportSensor.java
- sonar-dotnet-tests-library/src/test/java/org/sonar/plugins/dotnet/tests/CoverageAggregatorTest.java
- sonar-dotnet-tests-library/src/test/java/org/sonar/plugins/dotnet/tests/CoverageReportImportSensorTest.java
- sonar-dotnet-tests-library/src/test/java/org/sonar/plugins/dotnet/tests/UnitTestResultsAggregatorTest.java
- sonar-dotnet-tests-library/src/test/java/org/sonar/plugins/dotnet/tests/UnitTestResultsImportSensorTest.java
> Improve test sensors to execute them only when the related property is defined

- sonar-csharp-plugin/src/main/java/org/sonar/plugins/csharp/CSharpSensor.java
- sonar-csharp-plugin/src/test/java/org/sonar/plugins/csharp/CSharpSensorTest.java
> Fail analysis when OS is not Windows

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/CognitiveComplexityWalker.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/CognitiveComplexity.cs
> Cognitive Complexity Metric does not detect recursion correctly

- scripts/version/ChangeVersion.proj
- scripts/version/Version.props
- scripts/version/set-version.ps1
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/SonarAnalyzer.CSharp.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/SonarAnalyzer.VisualBasic.nuspec
- sonaranalyzer-dotnet/src/VsixManifests/Classic/source.extension.vsixmanifest
- sonaranalyzer-dotnet/src/VsixManifests/VS2015/source.extension.vsixmanifest
- sonaranalyzer-dotnet/src/VsixManifests/VS2017/source.extension.vsixmanifest
> Update release notes links and generating script

- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Demo.Authentication.Forms.TestingDemo-{948A8EF6-D50C-45EA-9AFD-7A4723ADAB0B}-S1075.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Demo.Authentication.Forms.TestingDemo-{948A8EF6-D50C-45EA-9AFD-7A4723ADAB0B}-S1200.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Demo.Authentication.Forms.TestingDemo-{948A8EF6-D50C-45EA-9AFD-7A4723ADAB0B}-S2221.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Demo.Authentication.Forms.TestingDemo-{948A8EF6-D50C-45EA-9AFD-7A4723ADAB0B}-S3216.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Demo.Authentication.Forms.TestingDemo-{948A8EF6-D50C-45EA-9AFD-7A4723ADAB0B}-S3900.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Demo.Authentication.Forms.TestingDemo-{948A8EF6-D50C-45EA-9AFD-7A4723ADAB0B}-S3990.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Demo.Authentication.Forms.TestingDemo-{948A8EF6-D50C-45EA-9AFD-7A4723ADAB0B}-S3992.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Testing-{D79203C0-B672-4751-9C95-C3AB7D3FEFBE}-S1200.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Testing-{D79203C0-B672-4751-9C95-C3AB7D3FEFBE}-S3900.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Testing-{D79203C0-B672-4751-9C95-C3AB7D3FEFBE}-S3925.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Testing-{D79203C0-B672-4751-9C95-C3AB7D3FEFBE}-S3990.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Testing-{D79203C0-B672-4751-9C95-C3AB7D3FEFBE}-S3992.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Testing-{D79203C0-B672-4751-9C95-C3AB7D3FEFBE}-S4004.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Testing-{D79203C0-B672-4751-9C95-C3AB7D3FEFBE}-S4026.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Testing-{D79203C0-B672-4751-9C95-C3AB7D3FEFBE}-S4039.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/ProjectTypeHelper.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/Helpers/ProjectTypeHelperTests.cs
> Update test assembly detection

- sonaranalyzer-dotnet/its/regression-test.ps1
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Metrics/ExecutableLinesWalker.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Metrics/Metrics.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/Utilities/MetricsAnalyzer.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Metrics/MetricsBase.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Metrics/Metrics.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/Common/MetricsTest.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/Metrics/ExecutableLinesWalkerTest.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/SonarAnalyzer.UnitTest.VS2015.csproj
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/SonarAnalyzer.UnitTest.VS2017.csproj
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/SonarAnalyzer.UnitTest.csproj
> Create an analyzer that computes executable lines metrics

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Metrics/Metrics.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Metrics/MetricsBase.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Protobuf/AnalyzerReport.proto
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Rules/Utilities/MetricsAnalyzerBase.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Metrics/Metrics.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/Common/MetricsTest.cs
> Populate protobuff with executable line metrics

- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/SonarAnalyzer.UnitTest.csproj
The unit tests for IssueLocationCollector were gone for some reason... Perhaps someone (me?) broke the inclusion patterns.
> Adding missing unit tests

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.resx
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S2386.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S2757.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S3257.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S3898.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S3903.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S3928.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S3972.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S4047.html
I only did a `java rule-api.jar update` previously which doesn't update everything....
> Update more RSPEC data

- sonaranalyzer-dotnet/rspec/cs/S2187_c#.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.resx
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/TestClassShouldHaveTestMethod.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S2187.html
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/TestClassShouldHaveTestMethod.cs
> Update S2187: Rule should handle "TheoryAttribute"

- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Testing.Tests-{8EB9E15A-4B65-4C80-B834-9A7773750666}-S3415.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Tests-{776D244D-BC4D-4BBB-A478-CAF2D04520E1}-S3415.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Tests.Functional-{BDA5E175-07D7-4E6F-B46F-C2CF7D63E231}-S3415.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.ViewEngines.DotLiquid.Tests-{A3BF6450-DE9A-4C11-8E3C-66D9A8EC93F5}-S3415.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Cluster.Sharding.Tests-{B369F314-4D37-4AC1-B4FB-64FF671AF0BC}-S3415.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Remote.Tests-{95E921AB-1F5A-4AF9-B7FE-284E317A97F4}-S3415.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Remote.Tests.MultiNode-{C9105C76-B084-4DA1-9348-1C74A8F22F6B}-S3415.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.TestKit.Tests-{D2BED2D5-B152-48C1-9818-1097BECDDF98}-S3415.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Tests-{3F786C7D-70E3-4836-8B33-EC9A5AF72330}-S3415.json
- sonaranalyzer-dotnet/rspec/cs/S3415_c#.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.resx
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/AssertionArgsShouldBePassedInCorrectOrder.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S3415.html
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/Rules/AssertionArgsShouldBePassedInCorrectOrderTest.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/AssertionArgsShouldBePassedInCorrectOrder.cs
> Update S3415: Support other test frameworks (XUnit and NUnit)

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/AsyncVoidMethod.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/AsyncVoidMethod.cs
> Fix S3168: Rule should not raise FP with UWP event args

- sonar-csharp-plugin/src/main/java/org/sonar/plugins/csharp/CSharpSensor.java
- sonar-csharp-plugin/src/test/java/org/sonar/plugins/csharp/CSharpSensorTest.java
> Enable analysis on non-Windows OSes

- scripts/rspec/rspec.ps1
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.resx
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/RspecStrings.resx
Fix SonarSource/sonarlint-visualstudio#434
> Category text

- sonaranalyzer-dotnet/rspec/cs/S2583_c#.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S2583.html
> Synchronize S2583 description with RSPEC

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/TestMethodShouldNotBeIgnored.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/TestMethodShouldNotBeIgnored.cs
> Update S1607: Rule should handle 'TestCaseSourceAttribute'

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/TestClassShouldHaveTestMethod.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/TestClassShouldHaveTestMethod.cs
> Update S2187: Rule should handle TestCaseSourceAttribute

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/TestMethodShouldContainAssertion.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/TestMethodShouldContainAssertion_NUnit.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/TestMethodShouldContainAssertion_Xunit.cs
> Update S2699: Rule should handle more test method attributes

- sonar-dotnet-tests-library/src/main/java/org/sonar/plugins/dotnet/tests/CoverageReportImportSensor.java
- sonar-dotnet-tests-library/src/test/java/org/sonar/plugins/dotnet/tests/CoverageReportImportSensorTest.java
Fix #989 and fix [SONARVB-258](https://jira.sonarsource.com/browse/SONARVB-258)
> SONARVB-258: Add warn log if code coverage doesn't cover any MAIN file

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/FieldShouldBeReadonlyCodeFixProvider.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/FieldShouldBeReadonly.Fixed.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/FieldShouldBeReadonly.cs
> Fix S2933: Code Fix should handle regions

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/ClassAndMethodName.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/Rules/ClassNameTest.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/SonarAnalyzer.UnitTest.csproj
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/MethodName.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/packages.SonarAnalyzer.UnitTest.config
> Fix S101: Rule should not throw IndexOutOfRangeException

- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/KnownMethods.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/MethodParameterUnused.Fixed.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/MethodParameterUnused.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/UnusedPrivateMember.Fixed.Batch.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/UnusedPrivateMember.Fixed.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/UnusedPrivateMember.cs
> Fix S1144 and S1172: handle new main syntax

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/SwitchDefaultClauseEmpty.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/SwitchDefaultClauseEmpty.Fixed.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/SwitchDefaultClauseEmpty.cs
> Fix S3532: default clauses with comments should not be reported

- its/pom.xml
> Update scanner version in ITs

- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/VariableUnused.cs
> S1481: Add tests for lambdas

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/UnusedPrivateMember.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/Rules/UnusedPrivateMemberTest.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/UnusedPrivateMember.part1.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/UnusedPrivateMember.part2.cs
> Fix S1144: False positive for partial methods/classes

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/CSharpSyntaxHelper.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/ImplementIDisposableCorrectlyPartial1.cs
> Fix S3881: 'Implement IDisposable correctly' has inconsistent behaviour in partial classes

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/CSharpSyntaxHelper.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/RedundantArgument.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/RedundantArgument.Named.Fixed.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/RedundantArgument.NoNamed.Fixed.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/RedundantArgument.cs
Fixed #789 : False positive in S3254 when used in Expression
> Fixed #789 : False positive in S3254 when used in Expression

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/ConditionalsShouldStartOnNewLine.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/SyntaxHelper.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Rules/FileLinesBase.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/FileLines20.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/FileLines20.vb
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/FileLines9.cs
Fix #1104 
Also fixes https://jira.sonarsource.com/browse/SONARVB-265
> Update S104: Multiline tokens should count as multiple lines

- sonar-csharp-plugin/src/main/java/org/sonar/plugins/csharp/CSharpCodeCoverageProvider.java
- sonar-csharp-plugin/src/main/java/org/sonar/plugins/csharp/CSharpUnitTestResultsProvider.java
> Update the plugin to convert comma separated properties as multi-values

- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/AnalysisContextExtensions.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/AnalysisRunContext.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/DiagnosticAnalyzerContextHelper.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/ReportingContext.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/SonarAnalysisContext.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/SonarCodeFixProvider.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/VbcHelper.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Helpers/AssertIgnoreScope.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Helpers/SonarAnalysisContextTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Verifier.cs
>  Refactor delegates to enable/disable and report a diagnostic

- sonaranalyzer-dotnet/rspec/cs/S3776_c#.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.resx
> Refresh RSPEC metadata to update S3776's remediation function and cost

- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Authentication.Forms.Tests-{4E974051-38C2-4B5D-A6B1-F265A428A673}-S3353.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Testing.Tests-{8EB9E15A-4B65-4C80-B834-9A7773750666}-S3353.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Tests-{776D244D-BC4D-4BBB-A478-CAF2D04520E1}-S3353.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Tests.Functional-{BDA5E175-07D7-4E6F-B46F-C2CF7D63E231}-S3353.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.ViewEngines.Markdown.Tests-{8EE6F976-F11F-44B3-B065-F5AAA598B30D}-S3353.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka-{5DEDDF90-37F0-48D3-A0B0-A5CBD8A7E377}-S3353.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Cluster-{6AB00F61-269A-4501-B06A-026707F000A7}-S3353.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Cluster.Sharding-{A05C31E8-0246-46A1-B3BC-4D6FE7A9AA49}-S3353.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Cluster.Tests-{C8D6A95C-50BF-4416-A212-86B18B87220D}-S3353.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Cluster.Tools.Tests-{9D8D62C7-7B4B-4CDF-8FE8-675DB71F6B21}-S3353.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.MultiNodeTestRunner.Shared.Tests-{91746A3F-21C6-4614-B0AB-A59310D75C51}-S3353.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Persistence.TestKit.Tests-{E6CDDAC1-BD68-4C7B-9E6D-569AC6D50793}-S3353.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Persistence.Tests-{4492004A-A8D0-45B0-BACC-05BA2F38EC55}-S3353.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Remote-{EA4FF8FD-7C53-49C8-B9AA-02E458B3E6A7}-S3353.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Remote.Tests-{95E921AB-1F5A-4AF9-B7FE-284E317A97F4}-S3353.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Remote.Tests.MultiNode-{C9105C76-B084-4DA1-9348-1C74A8F22F6B}-S3353.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Serialization.TestKit-{CAA97041-CFC0-4081-9BD2-8B139E62A611}-S3353.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Tests-{3F786C7D-70E3-4836-8B33-EC9A5AF72330}-S3353.json
- sonaranalyzer-dotnet/its/expected/akka.net/TcpEchoService.Server-{825196A4-4B08-401F-8994-E2DB7C77A8B7}-S3353.json
- sonaranalyzer-dotnet/its/expected/akka.net/TimeServer-{EB9BEE97-7B2C-44B7-8636-237A8E4171C7}-S3353.json
- sonaranalyzer-dotnet/rspec/cs/S3353_c#.html
- sonaranalyzer-dotnet/rspec/cs/S3353_c#.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.resx
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/UnchangedLocalVariablesShouldBeConst.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S3353.html
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/PackagingTests/CsRuleTypeMapping.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/UnchangedLocalVariablesShouldBeConstTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UnchangedLocalVariablesShouldBeConst.cs
> Rule S3353: Unchanged local variables should be 'const'

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/StringConcatenationInLoop.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Rules/StringConcatenationInLoopBase.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Rules/StringConcatenationInLoop.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/StringConcatenationInLoop.cs
> Fix S1643: check if expression is concatenation

- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/AnalysisContextExtensions.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/DiagnosticDescriptorBuilder.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/SonarAnalysisContext.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/SonarCodeFixProvider.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Helpers/SonarAnalysisContextTest.cs
> Allows to prevent the registration of a diagnostic on the context

- its/projects/CasingApp/CasingApp.sln
- its/projects/CasingApp/CasingApp/CasingApp.csproj
- its/projects/CasingApp/CasingApp/Properties/AssemblyInfo.cs
- its/projects/CasingApp/CasingApp/SRC/Class1.cs
- its/src/test/java/com/sonar/it/csharp/CasingAppTest.java
- sonar-csharp-plugin/src/main/java/org/sonar/plugins/csharp/CSharpSensor.java
- sonar-csharp-plugin/src/test/java/org/sonar/plugins/csharp/CSharpSensorTest.java
- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/ProtobufDataImporter.java
- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/RealPathProvider.java
- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/RoslynDataImporter.java
- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/protobuf/CPDTokensImporter.java
- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/protobuf/HighlightImporter.java
- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/protobuf/MetricsImporter.java
- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/protobuf/ProtobufImporter.java
- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/protobuf/ProtobufImporters.java
- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/protobuf/SymbolRefsImporter.java
- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/sarif/SarifParser01And04.java
- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/sarif/SarifParser10.java
- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/sarif/SarifParserFactory.java
- sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/ProtobufDataImporterTest.java
- sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/RealPathProviderTest.java
- sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/RoslynDataImporterTest.java
- sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/protobuf/CPDTokensImporterTest.java
- sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/protobuf/HighlightImporterTest.java
- sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/protobuf/MetricsImporterTest.java
- sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/protobuf/SymbolRefsImporterTest.java
- sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/sarif/SarifParser01And04Test.java
- sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/sarif/SarifParser10Test.java
- sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/sarif/SarifParserFactoryTest.java
> SonarC# should compare paths using the OS case-sensitivity

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/RemovableDeclarationCollector.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/AsyncVoidMethod.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/MethodParameterUnused.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/MethodsShouldUseBaseTypes.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/KnownMethods.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/SymbolHelper.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Rules/Naming/EventHandlerName.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Helpers/SymbolHelperTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/AsyncVoidMethod.cs
> Improve event handler detection

- sonaranalyzer-dotnet/its/expected/Nancy/Nancy-{34576216-0DCA-4B0F-A0DC-9075E75A676F}-S1821.json
- sonaranalyzer-dotnet/rspec/cs/S1821_c#.html
- sonaranalyzer-dotnet/rspec/cs/S1821_c#.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.resx
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/SwitchShouldNotBeNested.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S1821.html
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/PackagingTests/CsRuleTypeMapping.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/SwitchShouldNotBeNestedTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/SwitchShouldNotBeNested.cs
>  Rule S1821: "switch" statements should not be nested

- sonaranalyzer-dotnet/its/expected/Nancy/Nancy-{34576216-0DCA-4B0F-A0DC-9075E75A676F}-S1151.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka-{5DEDDF90-37F0-48D3-A0B0-A5CBD8A7E377}-S1151.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Cluster.Tests-{C8D6A95C-50BF-4416-A212-86B18B87220D}-S1151.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Cluster.Tools-{5CF8A8BE-B634-473F-BB01-EBA878746BD4}-S1151.json
- sonaranalyzer-dotnet/rspec/cs/S1151_c#.html
- sonaranalyzer-dotnet/rspec/cs/S1151_c#.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.resx
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/SwitchSectionShouldNotHaveTooManyStatements.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S1151.html
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/PackagingTests/CsRuleTypeMapping.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/SwitchSectionShouldNotHaveTooManyStatementsTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/SwitchSectionShouldNotHaveTooManyStatements_CustomValue.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/SwitchSectionShouldNotHaveTooManyStatements_DefaultValue.cs
> Rule S1151: "switch case" clauses should not have too many lines of code

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/RedundantCast.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/RedundantCast.Fixed.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/RedundantCast.cs
> Fix S1905: Rule should not report on Cast<T> over multi-dimensional arrays

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/CollectionQuerySimplification.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/CollectionQuerySimplification.cs
> Fix S2971: Do not trigger on ToList().AsEnumerable()

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/DoNotPassSameValueAsMultipleArguments.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Rules/DoNotPassSameValueAsMultipleArguments.cs
> Deprecate rule S4142

- sonaranalyzer-dotnet/rspec/cs/S3433_c#.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/TestMethodShouldHaveCorrectSignature.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S3433.html
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/TestMethodShouldHaveCorrectSignature.cs
> Fix S3433: Rule should not report on non-public test methods for xUnit

- sonaranalyzer-dotnet/its/expected/Nancy/Nancy-{34576216-0DCA-4B0F-A0DC-9075E75A676F}-S1192.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Hosting.Self-{AA7F66EB-EC2C-47DE-855F-30B3E6EF2134}-S1192.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Testing-{D79203C0-B672-4751-9C95-C3AB7D3FEFBE}-S1192.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.ViewEngines.Spark-{4B7E35DF-1569-4346-B180-A09615723095}-S1192.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka-{5DEDDF90-37F0-48D3-A0B0-A5CBD8A7E377}-S1192.json
- sonaranalyzer-dotnet/its/expected/akka.net/ClusterSharding.Node-{30A0B17D-B913-49AB-8CBB-8DF383AB7A52}-S1192.json
- sonaranalyzer-dotnet/its/expected/akka.net/FaultTolerance-{FBEBD803-AEFC-44B1-A429-6143C3288CA4}-S1192.json
- sonaranalyzer-dotnet/its/expected/akka.net/PersistenceExample-{4022147A-4F95-4A04-BE09-01B7952BBDD9}-S1192.json
- sonaranalyzer-dotnet/rspec/cs/S4524_c#.html
- sonaranalyzer-dotnet/rspec/cs/S4524_c#.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/CSharpSyntaxHelper.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.resx
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/DefaultSectionShouldBeFirstOrLast.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S4524.html
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/PackagingTests/CsRuleTypeMapping.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/DefaultSectionShouldBeFirstOrLastTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DefaultSectionShouldBeFirstOrLast.cs
> Rule S4524: switch 'default' case should be first or last

- sonaranalyzer-dotnet/its/expected/Nancy/Nancy-{34576216-0DCA-4B0F-A0DC-9075E75A676F}-S4462.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Testing-{D79203C0-B672-4751-9C95-C3AB7D3FEFBE}-S4462.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka-{5DEDDF90-37F0-48D3-A0B0-A5CBD8A7E377}-S4462.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Cluster-{6AB00F61-269A-4501-B06A-026707F000A7}-S4462.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Cluster.Sharding-{A05C31E8-0246-46A1-B3BC-4D6FE7A9AA49}-S4462.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Persistence-{FCA84DEA-C118-424B-9EB8-34375DFEF18A}-S4462.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Remote-{EA4FF8FD-7C53-49C8-B9AA-02E458B3E6A7}-S4462.json
- sonaranalyzer-dotnet/its/expected/akka.net/FaultTolerance-{FBEBD803-AEFC-44B1-A429-6143C3288CA4}-S4462.json
- sonaranalyzer-dotnet/its/expected/akka.net/PersistenceBenchmark-{39E6F51F-FA1E-4C62-B8F8-19065DE6D55D}-S4462.json
- sonaranalyzer-dotnet/its/expected/akka.net/Samples.Cluster.Transformation-{E5EB3DF5-D017-4B50-B5AA-2B0440DB773D}-S4462.json
- sonaranalyzer-dotnet/its/expected/akka.net/SymbolLookup-{3007A692-A050-4F12-9187-4AE6C6106A66}-S4462.json
- sonaranalyzer-dotnet/rspec/cs/S4462_c#.html
- sonaranalyzer-dotnet/rspec/cs/S4462_c#.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.resx
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/CallToAsyncMethodShouldNotBeBlocking.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S4462.html
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/PackagingTests/CsRuleTypeMapping.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/CallToAsyncMethodShouldNotBeBlockingTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/CallToAsyncMethodShouldNotBeBlocking.cs
> Rule S4462: Calls to 'async' methods should not be blocking

- sonaranalyzer-dotnet/rspec/cs/S1751_c#.html
- sonaranalyzer-dotnet/rspec/cs/S1751_c#.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.resx
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S1751_cs.html
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/PackagingTests/CsRuleTypeMapping.cs
> Update S1751: Rule should be a BUG

- sonaranalyzer-dotnet/rspec/cs/S2486_c#.html
- sonaranalyzer-dotnet/rspec/cs/S2486_c#.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.resx
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S2486.html
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/PackagingTests/CsRuleTypeMapping.cs
> Update S2486: Rule should be a VULNERABILITY

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/ShouldImplementExportedInterfaces.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/SymbolHelper.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ShouldImplementExportedInterfaces.cs
> Fix S4159: Rule should handle generic interfaces correctly

- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/AbstractPropertyDefinitions.java
> Fix SonarC# category under SonarQube/SonarCloud general settings

- sonar-csharp-plugin/src/main/java/org/sonar/plugins/csharp/RoslynProfileExporter.java
- sonar-csharp-plugin/src/test/java/org/sonar/plugins/csharp/RoslynProfileExporterTest.java
- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/protobuf/EncodingImporter.java
- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/protobuf/ProtobufImporter.java
- sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/protobuf/CPDTokensImporterTest.java
- sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/protobuf/EncodingImporterTest.java
- sonar-dotnet-shared-library/src/test/resources/ProtobufImporterTest/invalid-encoding.pb
> Fix string formats in the csharp plugin

- sonar-csharp-plugin/src/main/java/org/sonar/plugins/csharp/CSharpSonarWayProfile.java
The catch block was duplicated with SonarJava and in the same time not covered by tests. I replaced the various caught exceptions with Exception and I am planning to mark the SQ issue that will appear as Won't Fix.
> Fixing coverage and duplication

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/ParametersCorrectOrder.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ParametersCorrectOrder.cs
> Fix S2234: Check for parameter types before reporting it as bug

- its/src/test/java/com/sonar/it/csharp/UCFGDeserializationTest.java
Quick test to see if this makes the QA build pass
> [IGNORE] Temporarily disable UCFG tests

- its/projects/UcfgNoProtobuf/Class1.cs
- its/projects/UcfgNoProtobuf/UcfgNoProtobuf.csproj
- its/projects/UcfgNoProtobuf/UcfgNoProtobuf.sln
- its/src/test/java/com/sonar/it/csharp/UCFGDeserializationTest.java
Attempting to fix file locking issue in UCFG tests (#1478)
Fix #1478
> Change ucfg test to use a separate test project

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/ConditionEvaluatesToConstant.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ConditionEvaluatesToConstant.cs
> Fix S2583: Rule should not report false positives in finally block

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/ControlFlowGraph/UcfgInstructionFactory.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/ControlFlowGraph/UcfgBuilder_Instructions.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/ControlFlowGraph/UcfgBuilder_Instructions_Suspect.cs
> SONARSEC-145: Translate call to operator overload to uCFG method call

- sonar-dotnet-tests-library/src/main/java/org/sonar/plugins/dotnet/tests/XUnitTestResultsFileParser.java
- sonar-dotnet-tests-library/src/main/java/org/sonar/plugins/dotnet/tests/XmlParserHelper.java
- sonar-dotnet-tests-library/src/test/java/org/sonar/plugins/dotnet/tests/XUnitTestResultsFileParserTest.java
- sonar-dotnet-tests-library/src/test/resources/xunit/valid_no_total.xml
> Fix failure when parsing xUnit test result with no total

- its/src/test/java/com/sonar/it/csharp/MetricsTest.java
Same fix as https://github.com/SonarSource/sonar-cobol/pull/298
> ITs: stop testing comment_lines_data

- pom.xml
- scripts/version/Version.props
- sonar-csharp-plugin/pom.xml
- sonar-dotnet-shared-library/pom.xml
- sonar-dotnet-tests-library/pom.xml
- sonaranalyzer-dotnet/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/SonarAnalyzer.CSharp/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/SonarAnalyzer.RuleDocGenerator.CSharp/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/SonarAnalyzer.RuleDocGenerator.VisualBasic/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/SonarAnalyzer.VisualBasic/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/pom.xml
- sonaranalyzer-dotnet/src/AssemblyInfo.Shared.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.RuleDescriptorGenerator/Descriptor.cs.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.RuleDescriptorGenerator/Descriptor.vbnet.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/SonarAnalyzer.CSharp.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/SonarAnalyzer.VisualBasic.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/source.extension.vsixmanifest
not much user value, hence downgrading to a bugfix version number
> Update version to 7.3.1

- sonaranalyzer-dotnet/rspec/cs/S1075_c#.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/MethodSignature.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Rules/UriShouldNotBeHardcodedBase.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/AssemblyReferenceService.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/UriShouldNotBeHardcodedTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UriShouldNotBeHardcoded.AspNet.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UriShouldNotBeHardcoded.AspNetCore.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UriShouldNotBeHardcoded.cs
> Fix S1075: Rule should not report on virtual path for asp.net

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/MethodShouldBeNameAccordingToSynchronicity.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/MethodShouldBeNameAccordingToSynchronicity.cs
> Fix S4261: Do not report on async Main

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/PropertiesShouldBePreferred.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/PropertiesShouldBePreferred.cs
> Fix S4049: GetEnumerator should be white-listed

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Metrics/ExecutableLinesWalker.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Metrics/ExecutableLinesWalkerTest.cs
> Fix the executable lines of code count to ignore attributes

- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/protobuf/MetricsImporter.java
- sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/protobuf/MetricsImporterTest.java
> Stop feeding the comment_lines_data metric

- sonaranalyzer-dotnet/rspec/cs/S4524_c#.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S4524.html
> Update S4524: metadata needs to be updated

- sonaranalyzer-dotnet/rspec/cs/S2758_c#.html
- sonaranalyzer-dotnet/rspec/cs/S2758_c#.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/AllBranchesShouldNotHaveSameImplementation.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/TernaryOperatorPointless.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S2758.html
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/PackagingTests/DocGeneratorTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/AllBranchesShouldNotHaveSameImplementation.cs
> Deprecate S2758 in favor of S3923

- sonaranalyzer-dotnet/rspec/cs/S1764_c#.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S1764_cs.html
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/BinaryOperationWithIdenticalExpressions.cs
> Update S1764: update rule metadata

- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Authentication.Forms.Tests-{4E974051-38C2-4B5D-A6B1-F265A428A673}-S4143.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Tests-{776D244D-BC4D-4BBB-A478-CAF2D04520E1}-S4143.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/DoNotOverwriteCollectionElements.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DoNotOverwriteCollectionElements.cs
> Fix S4143: False Positive when variable is reassigned

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/TestMethodShouldContainAssertion.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/UnitTestHelper.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/TestMethodShouldContainAssertion.MsTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/TestMethodShouldContainAssertion.Xunit.Legacy.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/TestMethodShouldContainAssertion.Xunit.cs
Added common unit test helper class
Fixed #1687 
Fixed #1688
> Fixed #1687 and #1688

- sonaranalyzer-dotnet/its/expected/akka.net/Akka-{5DEDDF90-37F0-48D3-A0B0-A5CBD8A7E377}-S2245.json
- sonaranalyzer-dotnet/its/expected/akka.net/ClusterSharding.Node-{30A0B17D-B913-49AB-8CBB-8DF383AB7A52}-S2245.json
- sonaranalyzer-dotnet/its/expected/akka.net/ClusterToolsExample.Shared-{88D7D845-2F50-4D37-9026-B0A8353D0E8D}-S2245.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/CookieShouldBeSecure.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/CookieShouldNotContainSensitiveData.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/DoNotUseRandom.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/HardcodedIpAddress.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/CookieShouldBeSecure.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/CookieShouldNotContainSensitiveData.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DoNotUseRandom.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/HardcodedIpAddress.cs
> Change "Message" of Security Hotspot issues

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/CSharpSyntaxHelper.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/UseUriInsteadOfString.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UseUriInsteadOfString.cs
Fix #1723 
Fix #1724 
Fix #1725 
Fix #1726 
Fix #1727
> Update URI relates rules to handle ExpressionBody

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/UseValueParameter.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/UseValueParameterTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UseValueParameter.cs
> Update S3237: Rule should handle expression body accessors

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/FinalizerShouldNotBeEmpty.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/FinalizerShouldNotBeEmptyTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/FinalizerShouldNotBeEmpty.cs
> Update S3880: Rule should handle ExpressionBody

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/MemberShouldBeStatic.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/MemberShouldBeStaticTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/MemberShouldBeStatic.cs
> Update S2325: Rule should handle ExpressionBody

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/ReturnEmptyCollectionInsteadOfNull.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ReturnEmptyCollectionInsteadOfNull.cs
> Update S1168: Rule should handle ExpressionBody

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/ControlFlowGraph/CSharpControlFlowGraphBuilder.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/FlowAnalysisExtensions.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/ConditionEvaluatesToConstantTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/NullPointerDereferenceTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ConditionEvaluatesToConstant.CSharp7.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/NullPointerDereferenceCSharp7.cs
> Update Symbolic Execution Engine: Run rules on ExpressionBody

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/ImplementIDisposableCorrectly.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ImplementIDisposableCorrectly.cs
> Update S3881: Rule should handle ExpressionBody

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Metrics/Metrics.cs
> Update metrics to handle ExpressionBody

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/GenericTypeParameterUnused.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/GenericTypeParameterUnusedTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/GenericTypeParameterUnused.cs
> Update S2326: Rule should handle ExpressionBody

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/CSharpSyntaxHelper.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/RemovableSymbolCollector.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/UnusedPrivateMember.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/UnusedPrivateMemberTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UnusedPrivateMember.CSharp7.cs
> Update S1144: Rule should handle ExpressionBody

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/InitializeStaticFieldsInline.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/InitializeStaticFieldsInline.cs
> Update S3963: Rule should handle ExpressionBody

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/MemberInitializerRedundant.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/MemberInitializerRedundant.Fixed.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/MemberInitializerRedundant.cs
> Update S3604: Rule should handle ExpressionBody

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/MemberInitializedToDefault.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/MemberInitializedToDefault.Fixed.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/MemberInitializedToDefault.cs
> Update S3052: Rule should handle ExpressionBody

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/MethodParameterUnused.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/MethodParameterUnused.Fixed.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/MethodParameterUnused.cs
> Update S1172: Rule should handle ExpressionBody

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/PropertyToAutoProperty.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/PropertyToAutoPropertyTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/PropertyToAutoProperty.CSharp7.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/PropertyToAutoProperty.cs
> Update S2292: Rule should handle ExpressionBody

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/InfiniteRecursion.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/InfiniteRecursionTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/InfiniteRecursion.cs
> Update S2190: Rule should handle ExpressionBody

- sonaranalyzer-dotnet/rspec/cs/S3937_c#.html
- sonaranalyzer-dotnet/rspec/cs/S3937_c#.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.resx
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/NumberPatternShouldBeRegular.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S3937.html
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/PackagingTests/CsRuleTypeMapping.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/NumberPatternShouldBeRegularTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/NumberPatternShouldBeRegular.cs
> Rule S3937: Number patterns should be regular

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/ControlFlowGraph/CSharpControlFlowGraphBuilder.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SymbolicExecution/CSharpExplodedGraph.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/ControlFlowGraph/ControlFlowGraphTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ConditionEvaluatesToConstant.CSharp7.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/NullPointerDereferenceCSharp7.cs
> Pattern matching support for conditions and switch statements [NO SQUASH]

- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/SarifParserCallbackImpl.java
- sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/sarif/SarifParserCallbackImplTest.java
(based upon PR #1790)
Fix #1791
> Fix de-duplication mechanism for module and file level issues

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/GenericTypeParameterInOut.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/GenericTypeParameterInOutTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/GenericTypeParameterInOut.CSharp7.cs
> Fix S3246: False positive on tuples

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/DeadStores.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/DeadStoresTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DeadStores.cs
> Update S1854: Dead stores should allow initialization with default()

- sonar-dotnet-tests-library/src/main/java/org/sonar/plugins/dotnet/tests/CoverageReportImportSensor.java
- sonar-dotnet-tests-library/src/main/java/org/sonar/plugins/dotnet/tests/NUnitTestResultsFileParser.java
- sonar-dotnet-tests-library/src/main/java/org/sonar/plugins/dotnet/tests/UnitTestResults.java
- sonar-dotnet-tests-library/src/main/java/org/sonar/plugins/dotnet/tests/VisualStudioTestResultsFileParser.java
- sonar-dotnet-tests-library/src/main/java/org/sonar/plugins/dotnet/tests/XUnitTestResultsFileParser.java
- sonar-dotnet-tests-library/src/test/java/org/sonar/plugins/dotnet/tests/NUnitTestResultsFileParserTest.java
- sonar-dotnet-tests-library/src/test/java/org/sonar/plugins/dotnet/tests/UnitTestResultsImportSensorTest.java
- sonar-dotnet-tests-library/src/test/java/org/sonar/plugins/dotnet/tests/VisualStudioTestResultsFileParserTest.java
- sonar-dotnet-tests-library/src/test/java/org/sonar/plugins/dotnet/tests/XUnitTestResultsFileParserTest.java
> Improve debug logging when importing code coverage and test coverage

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/DeadStores.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DeadStores.cs
> Fix S1854: False Positive when variable initialized with -1 or +1

- sonaranalyzer-dotnet/its/expected/Nancy/Nancy-{34576216-0DCA-4B0F-A0DC-9075E75A676F}-S106.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka-{5DEDDF90-37F0-48D3-A0B0-A5CBD8A7E377}-S106.json
- sonaranalyzer-dotnet/its/expected/akka.net/ClusterToolsExample.Shared-{88D7D845-2F50-4D37-9026-B0A8353D0E8D}-S106.json
- sonaranalyzer-dotnet/its/expected/akka.net/Shared-{93EDACD8-F6BA-43A7-9FD7-D3D4156ADBC0}-S106.json
- sonaranalyzer-dotnet/rspec/cs/S106_c#.html
- sonaranalyzer-dotnet/rspec/cs/S106_c#.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/DebugOnlyCodeHelper.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.resx
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/ConsoleLogging.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/DoNotWriteToStandardOutput.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S106.html
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/PackagingTests/CsRuleTypeMapping.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/DoNotWriteToStandardOutputTest.cs
>  Rule S106: Standard outputs should not be used directly to log anything

- sonar-csharp-plugin/src/main/java/org/sonar/plugins/csharp/SonarLintProfileExporter.java
- sonar-csharp-plugin/src/test/java/org/sonar/plugins/csharp/CSharpSonarRulesDefinitionTest.java
- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/AbstractRulesDefinition.java
- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/AbstractSonarLintProfileExporter.java
- sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/AbstractSonarLintProfileExporterTest.java
Fix #1824 
We need to make test to ensure I didn't break anything for SonarLint + let's do one quick test to check Scanner for MSBuild (it seems to be using a different class but let's be sure).
> Update the plugin to not fail for SonarLint on SonarCloud

- docs/contributing-analyzer.md
- Document that they don't build the code
- Document issue with antivirus
> Document improvements for integration tests

- sonar-csharp-plugin/src/main/java/org/sonar/plugins/csharp/CSharpPlugin.java
- sonar-csharp-plugin/src/main/java/org/sonar/plugins/csharp/CSharpPropertyDefinitions.java
- sonar-csharp-plugin/src/test/java/org/sonar/plugins/csharp/CSharpPluginTest.java
- sonar-csharp-plugin/src/test/java/org/sonar/plugins/csharp/CSharpTest.java
- sonar-dotnet-shared-library/pom.xml
- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/AbstractConfiguration.java
- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/AbstractPropertyDefinitions.java
- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/RoslynDataImporter.java
- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/SarifParserCallbackImpl.java
- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/sarif/SarifParser01And04.java
- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/sarif/SarifParser10.java
- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/sarif/SarifParserCallback.java
- sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/AbstractConfigurationTest.java
- sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/RoslynDataImporterTest.java
- sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/protobuf/CPDTokensImporterTest.java
- sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/sarif/SarifParser01And04Test.java
- sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/sarif/SarifParser10Test.java
- sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/sarif/SarifParserCallbackImplTest.java
- sonar-dotnet-shared-library/src/test/resources/SarifParserTest/v1_0_file_level_issue.json
This is still work in progress. I still have to add more UT and do a manual test. But still you can maybe start having a look.
> Import third party Roslyn issues (fix #1825)

- sonar-dotnet-shared-library/pom.xml
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/SonarAnalyzer.Common.csproj
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/SonarAnalyzer.Vsix.csproj
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/packages.SonarAnalyzer.Vsix.config
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/SonarAnalyzer.UnitTest.csproj
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/packages.SonarAnalyzer.UnitTest.config
> Update the version of Google Protobuf we rely onto

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/NonAsyncTaskShouldNotReturnNull.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/NonAsyncTaskShouldNotReturnNull.cs
> Fix S4586: false positive with local function

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/DoNotOverwriteCollectionElements.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DoNotOverwriteCollectionElements.cs
> Fix S4143: False positive when using pre/post increment/decrement

- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/SonarAnalyzer.Vsix.csproj
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/packages.SonarAnalyzer.Vsix.config
> Upgrading Microsoft.VSSDK.BuildTools to be compatible with latest VS updates

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/ControlFlowGraph/CSharpControlFlowGraphBuilder.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SymbolicExecution/CSharpExplodedGraph.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ConditionEvaluatesToConstant.CSharp7.cs
> Fix NotSupportedException(s) when building CFG and executing symbolic execution

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/MemberShouldBeStatic.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/MemberShouldBeStatic.cs
> Update S2325: should not report methods in classes that inherit from System.Web.HttpApplication

- sonaranalyzer-dotnet/rspec/cs/S2931_c#.html
- sonaranalyzer-dotnet/rspec/cs/S2931_c#.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/DisposableMemberInNonDisposableClass.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S2931.html
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DisposableMemberInNonDisposableClass.cs
Fixes #1854 
Note that I significantly updated the rule description. It should be part of the review.
> S2931: Simpler implementation, one callback only, to avoid "timer issue"

- sonaranalyzer-dotnet/rspec/cs/S100_c#.html
- sonaranalyzer-dotnet/rspec/cs/S100_c#.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S100.html
> Update S100: Update RSPEC metadata

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/DoNotUseLiteralBoolInAssertions.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DoNotUseLiteralBoolInAssertions.MsTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DoNotUseLiteralBoolInAssertions.NUnit.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DoNotUseLiteralBoolInAssertions.Xunit.cs
> Fix S2701: rule should ignore bool? assertions

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/CSharpHotspotHelper.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/CSharpSyntaxHelper.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/MethodSignatureHelper.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/HotspotHelper.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Helpers/MethodSignatureHelper.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Helpers/VisualBasicHotspotHelper.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Helpers/VisualBasicSyntaxHelper.cs
Separate PR for the base classes, because the rule has quite a few FPs that have to be handled
> Adding base classes for hotspot rules

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/CSharpInvocationTracker.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/CSharpPropertyAccessTracker.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/CSharpSyntaxHelper.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/MethodSignatureHelper.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/InvocationTracker.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/MethodSignature.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Helpers/MethodSignatureHelper.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Helpers/VisualBasicInvocationTracker.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Helpers/VisualBasicPropertyAccessTracker.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Helpers/VisualBasicSyntaxHelper.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Helpers/MethodSignatureHelperTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Helpers/SymbolHelperTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestFramework/ProjectBuilder.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestFramework/SnippetCompiler.cs
Modified _MethodSignatureHelper_ to handle method overrides
Added unit tests for _MethodSignatureHelper_
Test infrastructure:
* added _SnippetCompiler_ class
* refactored _SymbolHelperTests_ to use the new class
> Added param-not-constant check to invocation tracker

- sonar-csharp-plugin/src/main/java/org/sonar/plugins/csharp/CSharpSonarWayProfile.java
- sonar-dotnet-shared-library/pom.xml
- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/AbstractSonarWayProfile.java
- sonar-vbnet-plugin/src/main/java/org/sonar/plugins/vbnet/VbNetPlugin.java
- sonar-vbnet-plugin/src/main/java/org/sonar/plugins/vbnet/VbNetSonarWayProfile.java
- sonar-vbnet-plugin/src/test/java/org/sonar/plugins/vbnet/VbNetPluginTest.java
- sonar-vbnet-plugin/src/test/java/org/sonar/plugins/vbnet/VbNetSonarWayProfileTest.java
> Visual Basic Security Hotspots rules should only be displayed on SonarQube/SonarCloud

- sonaranalyzer-dotnet/rspec/cs/S1523_c#.html
- sonaranalyzer-dotnet/rspec/vbnet/S1523_vb.net.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S1523_cs.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S1523_vb.html
> Update S1523 RSPEC metadata

- its/projects/MetricsTest/bar/Class1.cs
- its/projects/MetricsTest/foo/Class1.cs
- its/projects/MetricsTest/foo/Class1_copy.cs
- its/projects/VbMetricsTest/bar/Module1.vb
- its/projects/VbMetricsTest/foo/Module1.vb
- its/projects/VbMetricsTest/foo/Module1_copy.vb
- its/src/test/java/com/sonar/it/csharp/MetricsTest.java
- its/src/test/java/com/sonar/it/vbnet/MetricsTest.java
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Metrics/Metrics.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Common/MetricsTest.cs
>  Adding Cognitive Complexity metric to SonarVB

- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Rules/ArrayCreationLongSyntaxCodeFixProvider.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/ArrayCreationLongSyntaxTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ArrayCreationLongSyntax.Fixed.vb
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ArrayCreationLongSyntax.vb
> Fix S2355: Code fix should not crash when fixing an argument

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/UnusedPrivateMember.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UnusedPrivateMember.Fixed.Batch.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UnusedPrivateMember.Fixed.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UnusedPrivateMember.cs
> Fix S1144: AD0001 - System.InvalidCastException

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/ReturnEmptyCollectionInsteadOfNull.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ReturnEmptyCollectionInsteadOfNull.cs
> Fix S1168: FP with local function

- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/AbstractConfiguration.java
- sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/AbstractConfigurationTest.java
> Do not warn for missing "projectOutPaths" in test projects

- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Remote-{EA4FF8FD-7C53-49C8-B9AA-02E458B3E6A7}-S4069.json
- sonaranalyzer-dotnet/rspec/cs/S4069_c#.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/OperatorOverloadsShouldHaveNamedAlternatives.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S4069.html
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/OperatorOverloadsShouldHaveNamedAlternatives.cs
> Fix S4069: Add more alternative names for operators

- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Metrics/VisualBasicExecutableLinesMetric.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Metrics/CSharpExecutableLinesMetricTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Metrics/VisualBasicExecutableLinesMetricTest.cs
> Update executable lines metric

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Metrics/CSharpCognitiveComplexityMetric.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Metrics/VisualBasicCognitiveComplexityMetric.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Common/MetricsTest.cs
> Fix Cognitive Complexity Metric for recursions

- sonaranalyzer-dotnet/its/expected/Ember-MM/Ember Media Manager-{9B57D3AB-AF12-4012-B945-284C2448DC81}-S3776.json
- sonaranalyzer-dotnet/its/expected/Ember-MM/EmberAPI-{208AA35E-C6AE-4D2D-A9DD-B6EFD19A4279}-S3776.json
- sonaranalyzer-dotnet/its/expected/Ember-MM/generic.EmberCore.BulkRename-{EAAB0601-6478-44D2-A39C-89B0850D7833}-S3776.json
- sonaranalyzer-dotnet/its/expected/Ember-MM/generic.EmberCore.Extractor-{B413DEAF-4FDC-416A-B3E0-968C1C8F3F83}-S3776.json
- sonaranalyzer-dotnet/its/expected/Ember-MM/generic.EmberCore.MediaFileManager-{F6CACA89-E8E4-45D9-B942-97FBD4ADD106}-S3776.json
- sonaranalyzer-dotnet/its/expected/Ember-MM/generic.EmberCore.MovieExporter-{B0BDF9C2-EB9C-4090-B9A9-B703DF00CCEF}-S3776.json
- sonaranalyzer-dotnet/its/expected/Ember-MM/generic.EmberCore.NMT-{84B2143A-D04F-4262-923D-21AEDF86E2B7}-S3776.json
- sonaranalyzer-dotnet/its/expected/Ember-MM/generic.EmberCore.OfflineHolder-{E7FDD1C9-BCF7-4624-B033-D3888E422A8B}-S3776.json
- sonaranalyzer-dotnet/its/expected/Ember-MM/generic.EmberCore.WebServer-{64D6F035-F186-4193-AF35-D20126B8DA64}-S3776.json
- sonaranalyzer-dotnet/its/expected/Ember-MM/generic.EmberCore.XBMC-{6FE33C61-E2C2-4982-9536-63AEF0A98AAA}-S3776.json
- sonaranalyzer-dotnet/its/expected/Ember-MM/multi.EmberExtras-{62356BCF-D15A-4BF1-B980-395CEC0004A9}-S3776.json
- sonaranalyzer-dotnet/its/expected/Ember-MM/scraper.EmberCore-{EF6A550E-DD76-4F4D-8250-8598140F828B}-S3776.json
- sonaranalyzer-dotnet/its/expected/Ember-MM/scraper.EmberCore.XML-{E567C031-1F7B-4637-9B3A-806988DE50CF}-S3776.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Metrics/VisualBasicCognitiveComplexityMetric.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/CognitiveComplexity.vb
> Cognitive complexity increment is not increasing for nested loops in VB

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/UnusedPrivateMember.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/UnusedPrivateMemberTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UnusedPrivateMember.Fixed.Batch.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UnusedPrivateMember.Fixed.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UnusedPrivateMember.cs
I would like to see how this will affect peach
Fix #2168
> Fix S1144: Should create issues for unused event handlers

- sonar-csharp-plugin/pom.xml
- sonar-vbnet-plugin/pom.xml
- sonar-vbnet-plugin/src/main/java/org/sonar/plugins/vbnet/VbNetPlugin.java
> Fix VB.NET category names

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/StringLiteralShouldNotBeDuplicated.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/StringLiteralShouldNotBeDuplicatedTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/StringLiteralShouldNotBeDuplicated.cs
> Fix S1192: Rule should display string as defined in the source code

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/NumberPatternShouldBeRegular.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/NumberPatternShouldBeRegular.cs
> Fix S3937: FP for numbers with type suffixes

- sonaranalyzer-dotnet/its/expected/Automapper/AutoMapper.IntegrationTests-1EE3612B-FCA4-4DA5-BA9E-741A9D8DC59E-S2699.json
- sonaranalyzer-dotnet/its/expected/Automapper/AutoMapper.UnitTests-F0CC7EF4-B035-4FE1-A476-0676F7251200-S2699.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Testing.Tests-{8EB9E15A-4B65-4C80-B834-9A7773750666}-S2699.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Tests-{776D244D-BC4D-4BBB-A478-CAF2D04520E1}-S2699.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Remote.Tests-{95E921AB-1F5A-4AF9-B7FE-284E317A97F4}-S2699.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.TestKit.NUnit.Tests-{D63223FA-03F5-4B32-A6EC-668F718C0826}-S2699.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.TestKit.Tests-{D2BED2D5-B152-48C1-9818-1097BECDDF98}-S2699.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Tests-{3F786C7D-70E3-4836-8B33-EC9A5AF72330}-S2699.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/TestMethodShouldContainAssertion.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/UnitTestHelper.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/TestMethodShouldContainAssertion.MsTest.cs
> Fix S2699: Rule doesn't raise when the code contains any invocation

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/UnusedPrivateMember.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/DiagnosticDescriptorBuilder.cs
> Update S1144: Fade out / Dim code insteadof highlighting the full member

- sonaranalyzer-dotnet/its/expected/Automapper/AutoMapper-025B9F93-7953-454B-AF29-E6A55B2AA58F-S2436.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/TooManyGenericParameters.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/TooManyGenericParametersTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/TooManyGenericParameters_DefaultValues.cs
> Update S2436: Rule should be syntax based and not symbol based

- sonaranalyzer-dotnet/rspec/cs/S1144_c#.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S1144.html
> Update S1144: Add exceptions from RSPEC description

- sonaranalyzer-dotnet/rspec/cs/S4039_c#.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/InterfaceMethodsShouldBeCallableByChildTypes.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S4039.html
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/InterfaceMethodsShouldBeCallableByChildTypes.cs
> Update S4039: protected members should not generate issues

- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/SarifParserCallbackImpl.java
- sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/sarif/SarifParserCallbackImplTest.java
> Fix plugin: Roslyn external issues can contain invalid locations

- sonaranalyzer-dotnet/rspec/cs/S2183_c#.html
- sonaranalyzer-dotnet/rspec/cs/S2183_c#.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/DoNotShiftByZeroOrIntSize.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S2183.html
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DoNotShiftByZeroOrIntSize.cs
> Fix S2183: False positive for 8-bit and 16-bit integers

- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Demo.Hosting.Aspnet-{E127FED3-01C0-41BA-BF83-D8DCDD827D6A}-S2930.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/DisposableNotDisposed.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DisposableNotDisposed.cs
> Update S2930: update message to correspond the RSPEC declaration

- sonaranalyzer-dotnet/its/expected/Ember-MM/generic.EmberCore.NMT-{84B2143A-D04F-4262-923D-21AEDF86E2B7}-S1751.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Tests-{3F786C7D-70E3-4836-8B33-EC9A5AF72330}-S1751.json
- sonaranalyzer-dotnet/rspec/cs/S1751_c#.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/UnconditionalJumpStatement.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Rules/UnconditionalJumpStatementBase.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S1751_cs.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Rules/UnconditionalJumpStatement.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/UnconditionalJumpStatementTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UnconditionalJumpStatement.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UnconditionalJumpStatement.vb
> Update S1751: Update message and RSPEC metadata

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/UnusedPrivateMember.cs
> Update S1144: Exclude generated syntax trees from analysis

- sonaranalyzer-dotnet/its/expected/Ember-MM/Ember Media Manager-{9B57D3AB-AF12-4012-B945-284C2448DC81}-S126.json
- sonaranalyzer-dotnet/its/expected/Ember-MM/EmberAPI-{208AA35E-C6AE-4D2D-A9DD-B6EFD19A4279}-S126.json
- sonaranalyzer-dotnet/its/expected/Ember-MM/generic.EmberCore.BulkRename-{EAAB0601-6478-44D2-A39C-89B0850D7833}-S126.json
- sonaranalyzer-dotnet/its/expected/Ember-MM/scraper.EmberCore-{EF6A550E-DD76-4F4D-8250-8598140F828B}-S126.json
- sonaranalyzer-dotnet/its/expected/Ember-MM/scraper.EmberCore.XML-{E567C031-1F7B-4637-9B3A-806988DE50CF}-S126.json
- sonaranalyzer-dotnet/rspec/vbnet/S126_vb.net.html
- sonaranalyzer-dotnet/rspec/vbnet/S126_vb.net.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/IfChainWithoutElse.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Rules/IfChainWithoutElseBase.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S126_cs.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S126_vb.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Rules/IfChainWithoutElse.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/PackagingTests/VbRuleTypeMapping.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/IfChainWithoutElseTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/IfChainWithoutElse.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/IfChainWithoutElse.vb
> Rule S126 "If ... ElseIf" constructs should end with "Else" clauses

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/SillyBitwiseOperation.cs
> Update S2437: Rule highlight should be faded out

- sonar-csharp-plugin/pom.xml
- sonar-dotnet-shared-library/pom.xml
- sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/XmlParserHelper.java
- sonar-vbnet-plugin/pom.xml
Fix #2283 
The change was done with @m-g-sonar so there is no need for a special review.w
> Migrate to common XML parser provided by sonar-analyzer-commons

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/InvocationResolvesToOverrideWithParams.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/InvocationResolvesToOverrideWithParamsTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/InvocationResolvesToOverrideWithParams.cs
Fix #2234 
You should focus on the 2nd commit.
> Fix S3220: FP with overloads having Action and Func as parameter

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/UnusedPrivateMember.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/UnusedPrivateMemberTest.Types.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UnusedPrivateMember.Fixed.cs
Fix #2306 
You should focus the review on the 2nd commit.
> Update S1144: Rule should handle more unused types

- sonaranalyzer-dotnet/rspec/cs/S2325_c#.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/MemberShouldBeStatic.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S2325.html
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/MemberShouldBeStatic.cs
> Update S2325: Rule should handle a whitelist of method names

- sonaranalyzer-dotnet/rspec/cs/S3440_c#.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/RedundantConditionalAroundAssignment.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S3440.html
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/RedundantConditionalAroundAssignmentTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/RedundantConditionalAroundAssignment.Fixed.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/RedundantConditionalAroundAssignment.cs
> Update S3440: Allow property check before assignment

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/EqualityOnFloatingPoint.cs
> Add more tests for S1244

- sonaranalyzer-dotnet/rspec/cs/S3874_c#.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/DoNotUseOutRefParameters.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S3874.html
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/DoNotUseOutRefParametersTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DoNotUseOutRefParameters.cs
> Update S3874: FP with interface implementations

- sonaranalyzer-dotnet/rspec/cs/S3900_c#.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S3900.html
> S3900: Update rule documentation to mention protected members

- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/source.extension.vsixmanifest
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/tools-cs/install.ps1
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/tools-cs/uninstall.ps1
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/tools-vbnet/install.ps1
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/tools-vbnet/uninstall.ps1
Overrides #2329 and fixes #2328
> Add install/uninstall support for VS2019

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/MethodShouldBeNamedAccordingToSynchronicity.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/KnownType.cs
> Update S4261: Rule should handle 'ValueTask'

- docs/contributing-analyzer.md
- docs/contributing-plugin.md
`metadata` was removed from script in PR #2360
> Update readme files

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ParameterAssignedTo.cs
Cannot reproduce the issue reported in #2249
> Add tests to test reported FP

- sonaranalyzer-dotnet/its/expected/akka.net/Akka-{5DEDDF90-37F0-48D3-A0B0-A5CBD8A7E377}-S4275.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/PropertiesAccessCorrectField.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Rules/PropertiesAccessCorrectFieldBase.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Rules/PropertiesAccessCorrectField.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/NuGetMetadataReference.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/PropertiesAccessCorrectFieldTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/PropertiesAccessCorrectField.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/PropertiesAccessCorrectField.vb
Fix #2140
Fix #2195
I've put the alphabetical order refactor in a separate commit for an easy review of the actual changes. **Please squash commits** when merging.
> Fix S4275: FP with multiple assigments and ref parameters

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/GetHashCodeEqualsOverride.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/GetHashCodeEqualsOverride.cs
> Fix S3249 FP: ignore when has attribute

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/NotAssignedPrivateMember.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/NotAssignedPrivateMember.cs
> Fix S3459: FP with interop on private class members

- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/SymbolHelper.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Rules/PartCreationPolicyShouldBeUsedWithExportAttributeBase.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/PartCreationPolicyShouldBeUsedWithExportAttribute.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/PartCreationPolicyShouldBeUsedWithExportAttribute.vb
> Fix S4428 FP: should not raise for derived attributes

- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Rules/MarkWindowsFormsMainWithStaThreadBase.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/MarkWindowsFormsMainWithStaThread.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/MarkWindowsFormsMainWithStaThread.vb
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/MarkWindowsFormsMainWithStaThread_NoWindowsForms.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/MarkWindowsFormsMainWithStaThread_NoWindowsForms.vb
because async main is always MTA
Fixes #2352
> Fix S4210: not suggest STA for async main

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ClassWithEqualityShouldImplementIEquatable.cs
> Add FP test for S3897

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ConditionEvaluatesToConstant.cs
Reproducer for #1837 and #2164
> Add UT for S2583 and S2589 FP

- sonar-csharp-plugin/src/test/java/org/sonar/plugins/csharp/CSharpSonarRulesDefinitionTest.java
- sonar-vbnet-plugin/src/test/java/org/sonar/plugins/vbnet/VbNetSonarRulesDefinitionTest.java
- sonaranalyzer-dotnet/rspec/cs/S2255_c#.html
- sonaranalyzer-dotnet/rspec/cs/S2255_c#.json
- sonaranalyzer-dotnet/rspec/vbnet/S2255_vb.net.html
- sonaranalyzer-dotnet/rspec/vbnet/S2255_vb.net.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/Hotspots/DeliveringDebugFeaturesInProduction.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SyntaxTrackers/CSharpElementAccessTracker.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SyntaxTrackers/CSharpInvocationTracker.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/MemberDescriptor.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Rules/Hotspots/UsingCookiesBase.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/SyntaxTrackers/ElementAccessTracker.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/SyntaxTrackers/FieldAccessTracker.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/SyntaxTrackers/InvocationTracker.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/SyntaxTrackers/PropertyAccessTracker.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S2255_cs.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S2255_vb.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Rules/Hotspots/DeliveringDebugFeaturesInProduction.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/SyntaxTrackers/VisualBasicElementAccessTracker.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/SyntaxTrackers/VisualBasicFieldAccessTracker.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/SyntaxTrackers/VisualBasicInvocationTracker.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/SyntaxTrackers/VisualBasicPropertyAccessTracker.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Helpers/MethodSignatureHelperTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UsingCookies_Net46.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UsingCookies_Net46.vb
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UsingCookies_NetCore.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UsingCookies_NetCore.vb
> Fix #2384: Update Rule S2255 (remove cookie reading)

- sonaranalyzer-dotnet/rspec/cs/S2077_c#.html
- sonaranalyzer-dotnet/rspec/cs/S2077_c#.json
- sonaranalyzer-dotnet/rspec/vbnet/S2077_vb.net.html
- sonaranalyzer-dotnet/rspec/vbnet/S2077_vb.net.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/CSharpSyntaxHelper.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/Hotspots/ExecutingSqlQueries.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/Conditions.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Rules/Hotspots/ExecutingSqlQueriesBase.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S2077_cs.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S2077_vb.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Helpers/VisualBasicSyntaxHelper.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Rules/Hotspots/ExecutingSqlQueries.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/ExecutingSqlQueriesTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ExecutingSqlQueries_Net46.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ExecutingSqlQueries_Net46.vb
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ExecutingSqlQueries_NetCore.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ExecutingSqlQueries_NetCore.vb
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestFramework/ParseOptionsHelper.cs
> Rule S2077: Detect only formatted or concatenated strings

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/DoNotHardcodeCredentials.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Rules/DoNotHardcodeCredentialsBase.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Rules/DoNotHardcodeCredentials.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DoNotHardcodeCredentials_CustomValues.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DoNotHardcodeCredentials_CustomValues.vb
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DoNotHardcodeCredentials_DefaultValues.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DoNotHardcodeCredentials_DefaultValues.vb
> S2068: Update message and fix FP for empty strings

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DeclareEventHandlersCorrectly.cs
> Add UT for S3906 FP

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/PropertiesAccessCorrectField.cs
as reported internally https://discuss.sonarsource.com/t/fp-on-s4275-on-sonarc/2633
UT for FP mentioned in #2435
> S4275: Add UT for cross-procedural FP

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/DeclareEventHandlersCorrectly.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DeclareEventHandlersCorrectly.cs
> S3906: False positive when using generic type constraint

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/Hotspots/ExecutingSqlQueries.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Rules/Hotspots/ExecutingSqlQueries.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ExecutingSqlQueries_Net46.vb
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ExecutingSqlQueries_NetCore.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ExecutingSqlQueries_NetCore.vb
> S2077: Fix False Negative for + operator

- sonaranalyzer-dotnet/rspec/cs/S2219_c#.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/GetTypeWithIsAssignableFrom.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S2219.html
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/GetTypeWithIsAssignableFrom.Fixed.Batch.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/GetTypeWithIsAssignableFrom.Fixed.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/GetTypeWithIsAssignableFrom.cs
> S2219 FP on 'is object' used as null-check

- sonaranalyzer-dotnet/rspec/cs/S2201_c#.html
- sonaranalyzer-dotnet/rspec/cs/S2201_c#.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/ReturnValueIgnored.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S2201.html
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ReturnValueIgnored.cs
> S2201: Update message and description for string.Intern

- sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/CoverageAggregator.java
- sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/UnitTestResultsAggregator.java
- sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/XmlParserHelper.java
- sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/CoverageAggregatorTest.java
- sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/UnitTestResultsAggregatorTest.java
- sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/VisualStudioTestResultsFileParserTest.java
- sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/XmlParserHelperTest.java
- sonar-dotnet-shared-library/src/test/resources/visualstudio_test_results/invalid_character.trx
- sonar-dotnet-shared-library/src/test/resources/visualstudio_test_results/invalid_entities.trx
> Avoid failing analysis when XML imports fails

- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/RoslynProfileExporter.java
Hardcoded boolean values passed around are useless and make the QG fail due to lack of coverage.
> Remove dead code

- pom.xml
- scripts/build/ci-build.ps1
- add the same mvn profiles to PR and Feature Branch (to avoid having them just on master)
- replace missing mvn profile with 'coverage' profile
> Update pom again to fix master

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/ControlFlowGraph/CSharpControlFlowGraphBuilder.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/ConditionEvaluatesToConstant.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/ControlFlowGraph/ControlFlowGraphTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ConditionEvaluatesToConstant.cs
> S2583: Fix reported FP

- sonaranalyzer-dotnet/its/expected/Automapper/AutoMapper-025B9F93-7953-454B-AF29-E6A55B2AA58F-S3900.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/ControlFlowGraph/CSharpControlFlowGraphBuilder.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SymbolicExecution/CSharpExplodedGraph.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/ControlFlowGraph/ControlFlowGraphTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ConditionEvaluatesToConstant.CSharp7.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ConditionEvaluatesToConstant.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/InfiniteRecursion.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/NullPointerDereferenceCSharp6.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/NullPointerDereferenceCSharp7.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/PublicMethodArgumentsShouldBeCheckedForNull.cs
fix #2361 #1837 #2164 #1183 #1301 #2134 #2337
> fix FP S2589/S2583/S2259 due to conditional access

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/ControlFlowGraph/CSharpControlFlowGraphBuilder.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/CSharpSyntaxHelper.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/LiveVariableAnalysis/AbstractLiveVariableAnalysis.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/ControlFlowGraph/ControlFlowGraphTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DeadStores.cs
> Fix S1854 FP due to wrong CFG shape when `throw` is inside `try`

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/MLIRExporter.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/MlirExportTest.cs
Only operations related to i1 or i32 will remain generated, everything else is replaced by dummy (but hopefully valid) MLIR
> Detect type and generate unknown operations

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/MLIRExporter.cs
See reference SonarSource/SonarCBDE#37
>  Adapt to simplification of cbde.alloca

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/MLIRExporter.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/MlirExportTest.cs
They are useful, but they make the code harder to read...
> Make locations optional

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/ControlFlowGraph/CSharpControlFlowGraphBuilder.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/InfiniteRecursion.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SymbolicExecution/CSharpExplodedGraph.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/SymbolicExecution/SymbolicValues/SymbolicValue.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/ControlFlowGraph/CfgSerializerTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/ControlFlowGraph/ControlFlowGraphTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Helpers/FlowAnalysis/ExplodedGraphTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/SymbolicExecution/SymbolicValues/SymbolicValue_TrySetConstraint.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ConditionEvaluatesToConstant.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/NullPointerDereferenceCSharp6.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/NullPointerDereferenceCSharp7.cs
> Fix switch case cfg

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/MLIRExporter.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/MlirExportTest.cs
Maybe this PR would better not be squashed, since each commit is independant
> Handle (ignore) try/catch and handles throw

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/ControlFlowGraph/CSharpControlFlowGraphBuilder.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SymbolicExecution/CSharpExplodedGraph.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/SymbolicExecution/ProgramState.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/ControlFlowGraph/ControlFlowGraphTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ConditionEvaluatesToConstant.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/PublicMethodArgumentsShouldBeCheckedForNull.cs
> Fix the cfg of ref arg

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SymbolicExecution/CSharpExplodedGraph.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/SymbolicExecution/AbstractExplodedGraph.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ConditionEvaluatesToConstant.cs
fixes #1160
fixes #1187 
fixes #2348
> Fix S2583/S2589 FP due to foreach loops executed only once (#1160, #1187, #2348)

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/ConditionEvaluatesToConstant.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ConditionEvaluatesToConstant.cs
> Fix S2589 FP: ignore generator methods

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/ControlFlowGraph/CSharpControlFlowGraph.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/FlowAnalysisExtensions.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/SymbolicExecution/SymbolicExecutionException.cs
> Log exception details during symbolic execution

- sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/CoverageAggregator.java
- sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/CoverageAggregatorTest.java
> Log exception message when parse fails

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/CheckArgumentException.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/CheckArgumentException.cs
> Fix S3928 FP on indexers parameters

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/ControlFlowGraph/CSharpControlFlowGraphBuilder.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/DeadStores.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/RedundantJumpStatement.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/ControlFlowGraph/ControlFlowGraphTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/RedundantJumpStatement.cs
> Improve CFG for `try` statement: replace the 2 finally blocks with one finally block

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/ObjectsShouldNotBeDisposedMoreThanOnce.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ObjectsShouldNotBeDisposedMoreThanOnce.cs
> Fix FP S3966: Rule should consider the `leaveOpen` parameter

- sonaranalyzer-dotnet/rspec/cs/S4035_c#.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/EquatableClassShouldBeSealed.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S4035.html
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/EquatableClassShouldBeSealed.cs
> Fix S4035 FP on abstract declarations

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SymbolicExecution/CSharpExplodedGraph.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SymbolicExecution/InvocationVisitor.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/SymbolicExecution/Constraints/StringConstraint.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/SymbolicExecution/SymbolicValues/MemberAccessSymbolicValue.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/SymbolicExecution/SymbolicValues/SymbolicValue.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/SymbolicExecution/SymbolicValues/SymbolicValue_TrySetConstraint.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ConditionEvaluatesToConstant.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/NullPointerDereference.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/PublicMethodArgumentsShouldBeCheckedForNull.cs
> Add string constraints to support functions like IsNullOrEmpty

- sonaranalyzer-dotnet/its/expected/Nancy/Nancy-{34576216-0DCA-4B0F-A0DC-9075E75A676F}-S109.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka-{5DEDDF90-37F0-48D3-A0B0-A5CBD8A7E377}-S109.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Cluster-{6AB00F61-269A-4501-B06A-026707F000A7}-S109.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Persistence-{FCA84DEA-C118-424B-9EB8-34375DFEF18A}-S109.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Remote-{EA4FF8FD-7C53-49C8-B9AA-02E458B3E6A7}-S109.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Remote.AkkaIOTransport-{45AAAF15-C5D7-4107-94F0-766A32ECB9AE}-S109.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/MagicNumberShouldNotBeUsed.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/MagicNumberShouldNotBeUsed.cs
> S109: FP with auto-property assignment

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SymbolicExecution/CSharpExplodedGraph.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SymbolicExecution/InvocationVisitor.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/SymbolicExecution/Constraints/StringConstraint.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/SymbolicExecution/SymbolicValues/SymbolicValue.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/SymbolicExecution/SymbolicValues/SymbolicValue_TrySetConstraint.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ConditionEvaluatesToConstant.cs
> Add SE string constraint to handle `IsNullOrWhiteSpace`

- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/SymbolicExecution/SymbolicExecutionException.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/SymbolicExecution/SymbolicValues/MemberAccessSymbolicValueTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/SymbolicExecution/SymbolicValues/SymbolicValuesTest.cs
The QG is failing because I didn't add coverage for the exception class which I have modified to adhere to the serialization guideline (and I also opened  #2580). I didn't add coverage for that class because it's adding tests for boilerplate code to please the tool
> Add code cov

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ConditionEvaluatesToConstant.CSharp7.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ConditionEvaluatesToConstant.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DeadStores.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/NullPointerDereferenceCSharp6.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/PublicMethodArgumentsShouldBeCheckedForNull.cs
repro test cases for FPs #2592, #2590, #2596, #2598 , #2591 , #2600
> Add repro test cases for FPs from community

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/CBDE/CbdeHandler.cs
un peu plus que 2 lignes au final :-/
> report cbde build failures

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/ImplementIDisposableCorrectly.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/SonarAnalyzer.UnitTest.csproj
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ImplementIDisposableCorrectly.AbstractClass.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ImplementIDisposableCorrectly.cs
> Rule S3881: Makes message clearer on what is missing

- scripts/build/build-utils.ps1
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/CBDE/CbdeHandler.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/CBDE/MLIRExporter.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/SonarAnalyzer.CSharp.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/SonarAnalyzer.Vsix.csproj
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/CBDE/MlirExportTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/CbdeHandler.cs
disabled stderr stdout
ignore more syntax
change the layout of the temp directories for execution of cbde
> Branch to make CBDE integration tests work

- sonaranalyzer-dotnet/its/expected/Automapper/Benchmark-2A30FFB1-E25E-4BCB-9117-8BA11E2249BB-S2583.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy-{34576216-0DCA-4B0F-A0DC-9075E75A676F}-S2583.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka-{5DEDDF90-37F0-48D3-A0B0-A5CBD8A7E377}-S2583.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Remote-{EA4FF8FD-7C53-49C8-B9AA-02E458B3E6A7}-S2583.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Remote.Tests-{95E921AB-1F5A-4AF9-B7FE-284E317A97F4}-S2583.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.TestKit.Tests-{D2BED2D5-B152-48C1-9818-1097BECDDF98}-S2583.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Tests-{3F786C7D-70E3-4836-8B33-EC9A5AF72330}-S2583.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Tests.Performance-{B17DEDCB-D2AA-472D-82A0-D242B711F488}-S2583.json
- sonaranalyzer-dotnet/its/expected/akka.net/PersistenceBenchmark-{39E6F51F-FA1E-4C62-B8F8-19065DE6D55D}-S2583.json
Loïc: "We are finding new violations for the rule, unfortunately, they are known false positive. We have to discuss on how to make this rule work better, if at all possible..."
> Update integration tests

- sonaranalyzer-dotnet/its/expected/Automapper/AutoMapper.UnitTests-F0CC7EF4-B035-4FE1-A476-0676F7251200-S1128.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka-{5DEDDF90-37F0-48D3-A0B0-A5CBD8A7E377}-S1128.json
- sonaranalyzer-dotnet/rspec/cs/S1128_c#.html
- sonaranalyzer-dotnet/rspec/cs/S1128_c#.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/UnnecessaryUsings.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S1128.html
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UnnecessaryUsings.Fixed.Batch.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UnnecessaryUsings.Fixed.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UnnecessaryUsings.cs
> Update S1128 to not raise on duplicates due to CS0105

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DoNotOverwriteCollectionElements.cs
add repro attempt for https://community.sonarsource.com/t/sonarqube-incorrectly-indicating-bug-which-is-not-actually/14108/2
> Add more tests for S4143

- docs/contributing-analyzer.md
* Path environment variable should contain the Visual Studio Installer and NuGet folders
* In order be be able to run the integration tests on Nancy, the **ASP.Net and web development** workload is required
> Update the contributing-analyzer.md prerequisites

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/PublicMethodArgumentsShouldBeCheckedForNull.cs
> Repro for S3900 FP with boolean comparison

- docs/contributing-analyzer.md
the minus sign before the argument was missing
> Correct the command for running tests

- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Metrics/VisualBasicCognitiveComplexityMetric.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Rules/ConstructorArgumentValueShouldExist.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Rules/NameOfShouldBeUsed.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Common/MetricsTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/CognitiveComplexity.vb
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ConstructorArgumentValueShouldExist.vb
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DoNotThrowFromDestructors.vb
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/MethodParameterUnused.vb
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/NameOfShouldBeUsed.vb
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/OptionalParameter.vb
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/TooManyParameters_CustomValues.vb
> Fix VbNet NRE bugs due to null ParameterList

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/CSharpSymbolUsageCollector.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/ForLoopIncrementSign.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UnusedPrivateMember.Fixed.Batch.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UnusedPrivateMember.Fixed.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UnusedPrivateMember.cs
> Remove unused code, add ccov

- sonaranalyzer-dotnet/rspec/cs/S2092_c#.html
- sonaranalyzer-dotnet/rspec/cs/S2092_c#.json
- sonaranalyzer-dotnet/rspec/cs/S2699_c#.html
- sonaranalyzer-dotnet/rspec/cs/S3330_c#.html
- sonaranalyzer-dotnet/rspec/cs/S3330_c#.json
- sonaranalyzer-dotnet/rspec/cs/S5042_c#.html
- sonaranalyzer-dotnet/rspec/cs/S5042_c#.json
- sonaranalyzer-dotnet/rspec/vbnet/S5042_vb.net.html
- sonaranalyzer-dotnet/rspec/vbnet/S5042_vb.net.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/CookieShouldBeHttpOnly.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/sonarpedia.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S2092.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S2699.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S3330.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S5042_cs.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S5042_vb.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/sonarpedia.json
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/PackagingTests/CsRuleTypeMapping.cs
- S3330 becomes a Security Hotspot (fix #2743)
> Update rules descriptions

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/CommentedOutCode.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/MethodOverloadsShouldBeGrouped.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/MethodOverloadsShouldBeGrouped.vb
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/PropertiesAccessCorrectField.vb
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/PublicMethodArgumentsShouldBeCheckedForNull.cs
> Add reproducers for FP

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/AesManagedShouldBeWithSecureMode.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/CookieShouldBeHttpOnly.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/CookieShouldBeSecure.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/LdapConnectionShouldBeSecure.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/ObjectShouldBeInitializedCorrectlyBase.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/CookieShouldBeHttpOnlyTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/CookieShouldBeSecureTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/CookieShouldBeHttpOnly_NetCore.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/CookieShouldBeSecure_NetCore.cs
> Support CookieOptions object for rules S3330 and S2092

- scripts/build/build-utils.ps1
- sonaranalyzer-dotnet/its/regression-test.ps1
> Fix integration tests to run with VS2019 / MSBuild 16 (#2489)

- sonaranalyzer-dotnet/its/expected/Nancy/Nancy-{34576216-0DCA-4B0F-A0DC-9075E75A676F}-S2092.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Authentication.Forms-{E8B18958-7C8A-4FBA-AF00-3041C34A20CE}-S2092.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/CookieShouldBeHttpOnly.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/CookieShouldBeSecure.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SyntaxTrackers/CSharpObjectCreationTracker.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/AbstractMethodParameterLookup.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/SyntaxTrackers/ObjectCreationTracker.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/SyntaxTrackers/VisualBasicObjectCreationTracker.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/NuGetMetadataReference.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/CookieShouldBeHttpOnlyTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/CookieShouldBeSecureTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/SyntaxTrackers/ObjectCreationTrackerTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/CookieShouldBeHttpOnly_Nancy.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/CookiesShouldBeSecure_Nancy.cs
> Add support for NancyCookie in S3330 and S2092

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/UnnecessaryUsings.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UnnecessaryUsings.Fixed.Batch.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UnnecessaryUsings.Fixed.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UnnecessaryUsings.cs
> Fix S1128 FP: when using GetAwaiter() extension method

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/CBDE/MLIRExporter.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/CBDE/MlirExportTest.cs
- Unary - used a new cbde operation: cbde.neg
- Unary + just forwards its argument
> Add support for unary + and unary -

- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/SonarAnalyzer.CSharp.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/SonarAnalyzer.VisualBasic.nuspec
> Fix broken icon URL in nuspec files

- sonaranalyzer-dotnet/its/expected/Automapper/AutoMapper-025B9F93-7953-454B-AF29-E6A55B2AA58F-S1128.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/UnnecessaryUsings.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UnnecessaryUsings.Fixed.Batch.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UnnecessaryUsings.Fixed.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UnnecessaryUsings.cs
> Fix S1128 FP: when using System.Linq query syntax

- sonaranalyzer-dotnet/its/expected/ManuallyAddedNoncompliantIssues/IntentionalFindings--S5547.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/DoNotCallInsecureSecurityAlgorithm.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/InsecureEncryptionAlgorithm.cs
> Fix S5542: rule was not triggered

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/CookieShouldBeHttpOnly.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/CookieShouldBeHttpOnly.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/CookieShouldBeHttpOnly_NetCore.cs
Feedback from Appsec: update rule message to comply with new [RSPEC](https://jira.sonarsource.com/browse/RSPEC-3330)
> S3330: Update rule message

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/ReturnEmptyCollectionInsteadOfNull.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ReturnEmptyCollectionInsteadOfNull.cs
> Fix S1168 FP: when returning null in nested lambda

- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/EnumerableExtensions.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Helpers/EnumerableExtensionsTest.cs
> Implement .JoinStr extension

- docs/contributing-analyzer.md
- sonaranalyzer-dotnet/its/expected/AnalyzeGeneratedVb/AnalyzeGeneratedVb-{C4F122A1-A51D-4194-998F-686A6EF31E44}-S1451.json
- sonaranalyzer-dotnet/its/regression-test.ps1
> Add -project parameter to regression-test.ps1

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/CertificateValidationCheck.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Rules/CertificateValidationCheckBase.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Rules/CertificateValidationCheck.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/CertificateValidationCheck.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/CertificateValidationCheck.vb
> S4830: throw statements should be considered as validation

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/DoNotOverwriteCollectionElements.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Rules/DoNotOverwriteCollectionElements.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DoNotOverwriteCollectionElements.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DoNotOverwriteCollectionElements.vb
> S4143 False positives with `List<T>.Add` method calls

- sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/CoverageAggregator.java
- sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/CoverageReportImportSensor.java
- sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/DotCoverReportParser.java
- sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/DotCoverReportsAggregator.java
- sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/NCover3ReportParser.java
- sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/NUnitTestResultsFileParser.java
- sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/OpenCoverReportParser.java
- sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/VisualStudioCoverageXmlReportParser.java
- sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/VisualStudioTestResultsFileParser.java
- sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/WildcardPatternFileProvider.java
- sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/XUnitTestResultsFileParser.java
- sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/CoverageReportImportSensorTest.java
- sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/DotCoverReportParserTest.java
- sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/DotCoverReportsAggregatorTest.java
- sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/NCover3ReportParserTest.java
- sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/NUnitTestResultsFileParserTest.java
- sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/OpenCoverReportParserTest.java
- sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/VisualStudioCoverageXmlReportParserTest.java
- sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/VisualStudioTestResultsFileParserTest.java
- sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/WildcardPatternFileProviderTest.java
- sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/XUnitTestResultsFileParserTest.java
- sonar-dotnet-shared-library/src/test/resources/ncover3/one_file.nccov
- sonar-dotnet-shared-library/src/test/resources/opencover/one_class.xml
- sonar-dotnet-shared-library/src/test/resources/visualstudio_test_results/invalid_date.trx
Fixes #2860
This is Java code, so the QG does not appear on the PR.
Check the QG here > https://sonarcloud.io/dashboard?id=org.sonarsource.dotnet%3Asonar-csharp&pullRequest=0
> Add more logs for ccov and UT results import

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/DeclareTypesInNamespacesTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DeclareTypesInNamespaces.AfterCSharp8.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DeclareTypesInNamespaces.BeforeCSharp8.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DeclareTypesInNamespaces.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestFramework/ParseOptionsHelper.cs
> Add C# 8 and VB 16 to the supported versions in tests

- scripts/version/Version.props
- sonaranalyzer-dotnet/src/AssemblyInfo.Shared.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.RuleDescriptorGenerator/Descriptor.cs.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.RuleDescriptorGenerator/Descriptor.vbnet.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/SonarAnalyzer.CSharp.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/SonarAnalyzer.VisualBasic.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/source.extension.vsixmanifest
- the version should not end with a dot, otherwise the project build can fail and the tag URL will not be resolved correctly
> Fix vsixmanifest versions

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/ControlFlowGraph/CfgSerializerTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/ControlFlowGraph/ControlFlowGraphTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Helpers/FlowAnalysis/ExplodedGraphTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Helpers/TestHelper.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/Helpers/Microsoft_AspNetCore_Mvc_ControllerAttribute.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/Helpers/Microsoft_AspNetCore_Mvc_ControllerAttribute.vb
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/Helpers/Microsoft_AspNetCore_Mvc_ControllerBase.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/Helpers/Microsoft_AspNetCore_Mvc_ControllerBase.vb
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/Helpers/Microsoft_AspNetCore_Mvc_NonControllerAttribute.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/Helpers/Microsoft_AspNetCore_Mvc_NonControllerAttribute.vb
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/Helpers/System_Web_MVC_Controller.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/Helpers/System_Web_MVC_Controller.vb
> CFG Tests import from Sonar-Security

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/AllBranchesShouldNotHaveSameImplementationTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/SwitchCasesMinimumThreeTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/SwitchSectionShouldNotHaveTooManyStatementsTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/SwitchShouldNotBeNestedTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/TooManyLabelsInSwitchTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/AllBranchesShouldNotHaveSameImplementation.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/SwitchCasesMinimumThree.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/SwitchSectionShouldNotHaveTooManyStatements_CustomValue.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/SwitchShouldNotBeNested.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/TooManyLabelsInSwitch.cs
> Add tests with switch expressions

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/RedundantJumpStatement.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/RedundantJumpStatementTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/RedundantJumpStatement.cs
> Rule S3626: Add C# 8 unit tests for Non-SE CFG rule RedundantJumpStatement

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/InfiniteRecursion.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/InfiniteRecursionTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/InfiniteRecursion.cs
> Rule S2190: Add C# 8 unit tests for Non-SE CFG rule InfiniteRecursion

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/DeadStores.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/DeadStoresTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DeadStores.cs
> Rule S1854: Add C# 8 unit tests for Non-SE CFG rule DeadStores

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/MemberInitializerRedundantTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/MemberInitializerRedundant.Fixed.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/MemberInitializerRedundant.cs
> Rule S3604: Add C# 8 unit tests for Non-SE CFG rule MemberInitializerRedundant

- azure-pipelines.yml
> Fix Java analysis project version

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/CBDE/MlirExporter.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/CBDE/MlirExportTest.cs
> add UnsafeStatement to CBDE unsupported syntax

- azure-pipelines.yml
> Fix MVN properties

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/CBDE/MlirExporter.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/CBDE/MlirExportTest.cs
> fix bool assignent in if condition

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SymbolicExecution/CSharp/CSharpExplodedGraph.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/PublicMethodArgumentsShouldBeCheckedForNull.cs
- by using the program state with correct constrains
> Fix switch statement FP

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/PropertiesAccessCorrectField.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/PropertiesAccessCorrectField.vb
> S4275: Add repro for #2867

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UnconditionalJumpStatement.cs
> S1751: Add repro for #2864

- sonaranalyzer-dotnet/src/SonarAnalyzer.CFG/ControlFlowGraph/CSharpControlFlowGraphBuilder.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/ControlFlowGraph/ControlFlowGraphTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/SymbolicExecution/ExplodedGraphTests.cs
- last arm should have only one node instead of two
Fixes #2938
> Update CFG for switch expressions

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/SymbolicExecution/ExplodedGraphTests.cs
Related to #2891 and all other SE issues from #2849
> ExplodedGraphTests refactoring

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/EmptyCollectionsShouldNotBeEnumerated.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/EmptyCollectionsShouldNotBeEnumeratedTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/EmptyCollectionsShouldNotBeEnumerated.cs
> Add C# 8 unit tests for EmptyCollectionsShouldNotBeEnumerated

- sonaranalyzer-dotnet/its/expected/Ember-MM/Ember.Plugins-{9496C697-5AFD-4813-AEDC-AF33FACEADF0}-S1944.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/InvalidCastToInterface.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/InvalidCastToInterfaceTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/InvalidCastToInterface.cs
> Rule S1944: Enable and add C# 8 unit tests

- sonaranalyzer-dotnet/its/expected/Automapper/AutoMapper-025B9F93-7953-454B-AF29-E6A55B2AA58F-S2583.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy-{34576216-0DCA-4B0F-A0DC-9075E75A676F}-S2583.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka-{5DEDDF90-37F0-48D3-A0B0-A5CBD8A7E377}-S2589.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Persistence-{FCA84DEA-C118-424B-9EB8-34375DFEF18A}-S2589.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Remote.TestKit-{E5957C3E-2B1E-469F-A680-7953B4DEA31B}-S2583.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Tests-{3F786C7D-70E3-4836-8B33-EC9A5AF72330}-S2589.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/ConditionEvaluatesToConstant.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/ConditionEvaluatesToConstantTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ConditionEvaluatesToConstant.CSharp7.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ConditionEvaluatesToConstant.CSharp8.cs
> Rule S2583, S2589: add C# 8 unit tests

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DisposableMemberInNonDisposableClass.cs
> Add repro for issue 2957

- sonaranalyzer-dotnet/src/SonarAnalyzer.CFG/SonarAnalyzer.CFG.csproj
> Use C# 8 for SonarAnalyzer.CFG

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DeadStores.cs
> Add issue 2607 verification

- sonaranalyzer-dotnet/rspec/cs/S2068_c#.html
- sonaranalyzer-dotnet/rspec/cs/S2092_c#.html
- sonaranalyzer-dotnet/rspec/cs/S2092_c#.json
- sonaranalyzer-dotnet/rspec/cs/S3330_c#.html
- sonaranalyzer-dotnet/rspec/cs/S3330_c#.json
- sonaranalyzer-dotnet/rspec/cs/S3949_c#.html
- sonaranalyzer-dotnet/rspec/cs/S4507_c#.html
- sonaranalyzer-dotnet/rspec/cs/S4507_c#.json
- sonaranalyzer-dotnet/rspec/cs/S4830_c#.json
- sonaranalyzer-dotnet/rspec/cs/S5542_c#.json
- sonaranalyzer-dotnet/rspec/cs/S5547_c#.json
- sonaranalyzer-dotnet/rspec/vbnet/S2068_vb.net.html
- sonaranalyzer-dotnet/rspec/vbnet/S4507_vb.net.html
- sonaranalyzer-dotnet/rspec/vbnet/S4507_vb.net.json
- sonaranalyzer-dotnet/rspec/vbnet/S4830_vb.net.json
- sonaranalyzer-dotnet/rspec/vbnet/S5542_vb.net.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/sonarpedia.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S2068_cs.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S2068_vb.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S2092.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S3330.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S3949.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S4507_cs.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S4507_vb.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/sonarpedia.json
All updates seem legit, no behavior change, just rewords.
I excluded the update on S4426 because it seems it has some behavior change and I need to talk w/ appsec team about it
> update rspec before 8.2 release

- NOTICE.txt
- README.md
- sonar-csharp-plugin/pom.xml
- sonaranalyzer-dotnet/LICENSE
- sonaranalyzer-dotnet/src/AssemblyInfo.Shared.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.RuleDescriptorGenerator/Descriptor.cs.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.RuleDescriptorGenerator/Descriptor.vbnet.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/SonarAnalyzer.CSharp.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/SonarAnalyzer.VisualBasic.nuspec
> update copyright metadata to year 2020

- pom.xml
- scripts/version/Version.props
- sonar-csharp-plugin/pom.xml
- sonar-dotnet-shared-library/pom.xml
- sonar-vbnet-plugin/pom.xml
- sonaranalyzer-dotnet/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/SonarAnalyzer.CSharp/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/SonarAnalyzer.RuleDocGenerator.CSharp/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/SonarAnalyzer.RuleDocGenerator.VisualBasic/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/SonarAnalyzer.VisualBasic/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/pom.xml
- sonaranalyzer-dotnet/src/AssemblyInfo.Shared.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.RuleDescriptorGenerator/Descriptor.cs.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.RuleDescriptorGenerator/Descriptor.vbnet.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/SonarAnalyzer.CSharp.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/SonarAnalyzer.VisualBasic.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/source.extension.vsixmanifest
> Bump version to 8.3

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/NonAsyncTaskShouldNotReturnNull.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/NonAsyncTaskShouldNotReturnNull.cs
> Rule S4586 - update to support static local functions

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/DoNotNestTypesInArguments.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DoNotNestTypesInArguments.cs
> Rule S4017 - update to support static local functions

- azure-pipelines.yml
- pom.xml
- sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/CoverageAggregator.java
SQUASH!
you can see below that with d04a876 , the ccov works
> Fix code coverage for the java codebase on SonarCloud

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/EmptyCollectionsShouldNotBeEnumerated.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SymbolicExecution/CSharp/CSharpExplodedGraph.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/SymbolicExecution/ExplodedGraphTests.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/EmptyCollectionsShouldNotBeEnumerated.cs
- this is a temporary fix until #2936 is done
> Push SymbolicValue for DeclarationExpression

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/EnumStorageNeedsToBeInt32.cs
> S4022 FP reproduction of issue 3026

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SymbolicExecution/CSharp/CSharpExplodedGraph.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/SymbolicExecution/ExplodedGraphTests.cs
ticket to properly support RefExpression: #3024
I tested locally building dnSpy and it reduced errors from 659 to 332
> do not fail for RefExpression

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/SelfAssignment.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Rules/SelfAssignmentBase.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Rules/SelfAssignment.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/SelfAssignment.cs
> Rule S1656 - support the `??=` null coalescing assignment

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/ExpressionComplexity.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Rules/ExpressionComplexityBase.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Rules/ExpressionComplexity.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ExpressionComplexity.cs
> Rule S1067 - support the `??=` null coalescing assignment

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SymbolicExecution/CSharp/CSharpExplodedGraph.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/SymbolicExecution/ExplodedGraphTests.cs
> Add support for tuple assignment

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/VariableShadowsField.cs
> S1117 - Add test w/ properties shadowed in local functions

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/TooManyParameters.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/TooManyParametersTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/TooManyParameters_CustomValues.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/TooManyParameters_DefaultValues.cs
> Rule S107 - update to support static local functions

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/AssignmentInsideSubExpression.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/AssignmentInsideSubExpression.cs
> Rule S1121 - support the `??=` null coalescing assignment

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/ClassAndMethodName.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/MethodName.cs
> Rule S100 - update to support static local functions

- sonaranalyzer-dotnet/src/SonarAnalyzer.CFG/ControlFlowGraph/CSharpControlFlowGraphBuilder.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SymbolicExecution/CSharp/CSharpExplodedGraph.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/SymbolicExecution/ExplodedGraphTests.cs
- in order to be able to correctly handle the method invocations which
have as argument a DiscardDesignation
- update CFG to generate instructions for Dictionary
- add test
> Create SymbolicValue for DiscardDesignation

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/ParameterNamesShouldNotDuplicateMethodNames.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ParameterNamesShouldNotDuplicateMethodNames.cs
> Rule S3872 - update to support static local functions

- sonaranalyzer-dotnet/rspec/cs/S1301_c#.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/SwitchCasesMinimumThree.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S1301_cs.html
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/SwitchCasesMinimumThree.cs
> Update S1301 with support for `switch` expressions

- docs/contributing-analyzer.md
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/CheckFileLicense.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/ParameterLoader.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Rules/CheckFileLicense.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/SonarAnalyzer.Vsix.csproj
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/source.extension.vsixmanifest
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/CheckFileLicenseTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/CheckFileLicense_YearDifference.Fixed.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/CheckFileLicense_YearDifference.cs
Fixes #2711 
Please don't squash commits
> Make S1451 SQ param text area

- sonaranalyzer-dotnet/src/SonarAnalyzer.CFG/ShimLayer/ITypeSymbolExtensions.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/DisposableNotDisposed.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/DisposableNotDisposedTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DisposableNotDisposed.cs
> Rule S2930 - Support Disposable ref structs and using declaration

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/GenericTypeParameterUnused.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/GenericTypeParameterUnused.cs
> Rule S2326 - update to support static local functions

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/StaticFieldInitializerOrder.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/StaticFieldInitializerOrder.cs
> Rule S3263 - update to support default interface members

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/InheritedCollidingInterfaceMembers.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/InheritedCollidingInterfaceMembers.AfterCSharp8.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/InheritedCollidingInterfaceMembers.cs
> Fix S3444 FP for default interface static and private methods 

- sonaranalyzer-dotnet/its/expected/Ember-MM/generic.EmberCore.WebServer-{64D6F035-F186-4193-AF35-D20126B8DA64}-S3923.json
- sonaranalyzer-dotnet/its/expected/Ember-MM/multi.Compatibility-{859C1085-518B-49D2-9C84-D91C4094097F}-S3923.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/SwitchExpressionSyntaxWrapperExtensions.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/AllBranchesShouldNotHaveSameImplementation.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/SwitchCasesMinimumThree.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Rules/AllBranchesShouldNotHaveSameImplementationBase.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Rules/AllBranchesShouldNotHaveSameImplementation.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/AllBranchesShouldNotHaveSameImplementation.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/AllBranchesShouldNotHaveSameImplementation.vb
> S3923 - add support for switch expressions

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/SymbolicExecution/ExplodedGraphTests.cs
> Remove unused code

- sonaranalyzer-dotnet/its/expected/Automapper/AutoMapper-025B9F93-7953-454B-AF29-E6A55B2AA58F-S3240.json
- sonaranalyzer-dotnet/its/expected/Automapper/AutoMapper.UnitTests-F0CC7EF4-B035-4FE1-A476-0676F7251200-S3240.json
- sonaranalyzer-dotnet/its/expected/Ember-MM/Ember.Plugins-{9496C697-5AFD-4813-AEDC-AF33FACEADF0}-S3240.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy-{34576216-0DCA-4B0F-A0DC-9075E75A676F}-S3240.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Hosting.Self.Tests-{CA24ED85-DD68-4C10-B80A-D81C6745FCB8}-S3240.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Testing-{D79203C0-B672-4751-9C95-C3AB7D3FEFBE}-S3240.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Tests-{776D244D-BC4D-4BBB-A478-CAF2D04520E1}-S3240.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.ViewEngines.Spark.Tests-{06F89662-C2F0-4C1D-8581-E0C4A615B7E2}-S3240.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka-{5DEDDF90-37F0-48D3-A0B0-A5CBD8A7E377}-S3240.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Cluster.Tests.MultiNode-{F0781BEA-5BA0-4AF0-BB15-E3F209B681F5}-S3240.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Persistence-{FCA84DEA-C118-424B-9EB8-34375DFEF18A}-S3240.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Remote-{EA4FF8FD-7C53-49C8-B9AA-02E458B3E6A7}-S3240.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Remote.TestKit-{E5957C3E-2B1E-469F-A680-7953B4DEA31B}-S3240.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.TestKit-{0D3CBAD0-BBDB-43E5-AFC4-ED1D3ECDC224}-S3240.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Tests-{3F786C7D-70E3-4836-8B33-EC9A5AF72330}-S3240.json
- sonaranalyzer-dotnet/rspec/cs/S3240_c#.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/ConditionalSimplification.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/ConditionalSimplificationCodeFixProvider.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/SonarAnalysisContext.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S3240.html
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/ConditionalSimplificationTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ConditionalSimplification.BeforeCSharp8.Fixed.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ConditionalSimplification.BeforeCSharp8.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ConditionalSimplification.FromCSharp8.Fixed.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ConditionalSimplification.FromCSharp8.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestFramework/CodeFixVerifier.cs
Fixes #2989
Please review the update of RSPEC itself as well.
> Rule S3240 - support the `??=` null coalescing assignment

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/CSharpSyntaxHelper.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/UnusedReturnValue.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/UnusedReturnValueTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UnusedReturnValue.cs
> Rule S3241 - update to support static local functions

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SymbolicExecution/CSharp/CSharpExplodedGraph.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/SymbolicExecution/ExplodedGraphTests.cs
- created for VariableDesignation
Fixes #3071
> Add not null constraint for symbolic values

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/SqlKeywordsDelimitedBySpace.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/SqlKeywordsDelimitedBySpace.cs
> Rule S2857 - update to support interpolated string syntax

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/DisposeNotImplementingDispose.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DisposeNotImplementingDispose.cs
> Fix S2953 FP with disposable ref structs

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SymbolicExecution/CSharp/CSharpExplodedGraph.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/SymbolicExecution/ExplodedGraphTests.cs
> Add constraints for values added by DeclarationExpression

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/UnconditionalJumpStatement.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Rules/UnconditionalJumpStatementBase.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Rules/UnconditionalJumpStatement.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/UnconditionalJumpStatementTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UnconditionalJumpStatement.cs
> S1751: FP when exception is thrown inside a local function

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/SymbolicExecution/ExplodedGraphTests.cs
> Add unit test with DiscardDesignation inside IsPattern

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/CSharpCompilationHelper.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/IFieldSymbolExtensions.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/IMethodSymbolExtensions.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/ITypeSymbolExtensions.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/LanguageVersionExtensions.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/DisposableMemberInNonDisposableClass.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/DisposeFromDispose.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/DisposeNotImplementingDispose.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/CompilationExtensions.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/DisposeFromDisposeTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DisposeFromDispose.BeforeCsharp8.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DisposeFromDispose.cs
> Rule S2952 - support Disposable ref structs

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SymbolicExecution/CSharp/CSharpExplodedGraph.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/SymbolicExecution/ExplodedGraphTests.cs
- during symbolic execution
- proper handling will be done by #2937
Fixes #3077
> Ignore RecursivePatterns inside IsPattern

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/ConsumeValueTaskCorrectly.cs
Follow up of https://github.com/SonarSource/sonar-dotnet/pull/3079#discussion_r372360828
> S5034 Remove duplicate DiagnosticId

- CODE_OF_CONDUCT.md
- README.md
- docs/contributing-analyzer.md
- docs/issues.md
- scripts/rspec/README.md
> Update documentation files

- sonaranalyzer-dotnet/rspec/cs/S2583_c#.html
- sonaranalyzer-dotnet/rspec/cs/S2583_c#.json
- sonaranalyzer-dotnet/rspec/cs/S2589_c#.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/LiveVariableAnalysis/CSharp/CSharpLiveVariableAnalysis.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/ConditionEvaluatesToConstant.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S2583.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S2589.html
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/ConditionEvaluatesToConstantTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ConditionEvaluatesToConstant.CSharp6.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ConditionEvaluatesToConstant.CSharp8.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ConditionEvaluatesToConstant.cs
Fixes #3066
Please review RSPEC text update as well.
I've closed the spin-off LVA #3076 because it's not relevant anymore.
> S2583: NullCoalesceOperator ??= for ConditionEvaluatesToConstant

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SonarAnalyzer.CSharp.csproj
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/packages.lock.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.RuleDescriptorGenerator/packages.lock.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/packages.lock.json
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/packages.lock.json
> Uninstall System.Runtime.InteropServices.RuntimeInformation

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/UnusedReturnValueTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UnusedReturnValue.External.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UnusedReturnValue.part1.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UnusedReturnValue.part2.cs
> Add reproducer for S3241 'AD0001' error

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UnnecessaryUsings.Fixed.Batch.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UnnecessaryUsings.Fixed.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UnnecessaryUsings.cs
> Add repro for #3065

- sonaranalyzer-dotnet/rspec/cs/S1301_c#.html
- sonaranalyzer-dotnet/rspec/cs/S2092_c#.html
- sonaranalyzer-dotnet/rspec/cs/S2589_c#.html
- sonaranalyzer-dotnet/rspec/cs/S2952_c#.html
- sonaranalyzer-dotnet/rspec/cs/S3949_c#.html
- sonaranalyzer-dotnet/rspec/cs/S4426_c#.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/sonarpedia.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S1301_cs.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S2092.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S2589.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S2952.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S3949.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/sonarpedia.json
Rule S4426 was not updated, I've create issue #3089 to track this.
> Update RSPEC for release 8.3

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DeadStores.cs
> Add repro for S1854 FP

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/CheckFileLicenseTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/MethodsShouldNotHaveTooManyLinesTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestFramework/DiagnosticVerifierTest.cs
@lg2de opened a fix for #3055 on #3098 (Thanks!)
this PR is needed to run the CI tests
> Make tests pass on non-english culture

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/DownloadCBDE.targets
details here https://github.com/SonarSource/SonarCBDE/pull/113
This will have to be fixed until our next release (to rely on a properly released version)
> Unlock master by updating to new dev CBDE

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/Hotspots/ExecutingSqlQueries.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SyntaxTrackers/CSharpObjectCreationTracker.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/SemanticModelExtensions.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Rules/Hotspots/ExecutingSqlQueriesBase.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/SyntaxTrackers/InvocationTracker.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/SyntaxTrackers/ObjectCreationTracker.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/SyntaxTrackers/PropertyAccessTracker.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Rules/Hotspots/ExecutingSqlQueries.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ExecutingSqlQueries_Net46.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ExecutingSqlQueries_Net46.vb
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ExecutingSqlQueries_NetCore.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ExecutingSqlQueries_NetCore.vb
> Extend RSPEC-2077 to consider also variable declarators

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ConditionEvaluatesToConstant.CSharp7.cs
> Add repro for S2583 FP #3110

- sonaranalyzer-dotnet/its/sources/ManuallyAddedNoncompliantIssues/IntentionalFindings/AssemblyInfo.cs
- sonaranalyzer-dotnet/its/sources/ManuallyAddedNoncompliantIssues/IntentionalFindings/S2251.cs
- sonaranalyzer-dotnet/its/sources/ManuallyAddedNoncompliantIssues/IntentionalFindings/S2479.cs
- sonaranalyzer-dotnet/its/sources/ManuallyAddedNoncompliantIssues/IntentionalFindings/S4487.cs
- sonaranalyzer-dotnet/its/sources/ManuallyAddedNoncompliantIssues/IntentionalFindings/S4635.cs
for files from ManuallyAddedNoncompliantIssues
> Convert eol to linux format

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/ControlFlowGraph/ControlFlowGraphTest.cs
Fixes #2680
Issue is not reproducible anymore after recent CFG update.
> Add tests for handling exceptions inside null coalesce operator

- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Rules/Hotspots/DoNotHardcodeCredentialsBase.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/DoNotHardcodeCredentialsTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DoNotHardcodeCredentials_CustomValues.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DoNotHardcodeCredentials_CustomValues.vb
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DoNotHardcodeCredentials_DefaultValues.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DoNotHardcodeCredentials_DefaultValues.vb
> Rule S2068: add exceptions for query parameters

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/IFieldSymbolExtensions.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DisposableMemberInNonDisposableClass.cs
Fixes #2957
Fix S2931 FN: fields of type IDisposable will be considered
> Fix S2931 FN: fields of type IDisposable will be considered 

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DeadStores.cs
> Add repro for S1854 #3126

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/MethodParameterUnused.Fixed.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/MethodParameterUnused.cs
Reproducer for #3132 and #3134
> Add repro for S1172 FP

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/CollectionPropertiesShouldBeReadOnly.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/CollectionPropertiesShouldBeReadOnly.cs
> Fix S4004 FP: Should not raise on [Serializable] objects

- sonaranalyzer-dotnet/its/expected/Automapper/AutoMapper.IntegrationTests-1EE3612B-FCA4-4DA5-BA9E-741A9D8DC59E-S4004.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy-{34576216-0DCA-4B0F-A0DC-9075E75A676F}-S4004.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Validation.DataAnnotations-{701765DC-F4F2-4943-A37F-6ED253198158}-S4004.json
- sonaranalyzer-dotnet/rspec/cs/S4004_c#.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/CollectionPropertiesShouldBeReadOnly.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S4004.html
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/CollectionPropertiesShouldBeReadOnly.cs
> Fix S4004 FP: Should not raise when enforced by interface or base class

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SyntaxTrackers/CSharpObjectInitializationTracker.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/XmlExternalEntityShouldNotBeParsed_XmlDocument_Net35.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/XmlExternalEntityShouldNotBeParsed_XmlTextReader_Net35.cs
> Fix FPs regarding XXE rule inside using

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/PropertiesAccessCorrectField.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Rules/PropertiesAccessCorrectField.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/PropertiesAccessCorrectField.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/PropertiesAccessCorrectField.vb
> Fix S4275: FP when the value is encapsulated in another class

- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Rules/PropertiesAccessCorrectField.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/PropertiesAccessCorrectField.vb
Fixes #2774
Branch name contains wrong rule ID
> Fix S4275 VB .NET : FP when `WithEvents` is present

- pom.xml
- scripts/version/Version.props
- sonar-csharp-plugin/pom.xml
- sonar-dotnet-shared-library/pom.xml
- sonar-vbnet-plugin/pom.xml
- sonaranalyzer-dotnet/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/SonarAnalyzer.CSharp/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/SonarAnalyzer.RuleDocGenerator.CSharp/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/SonarAnalyzer.RuleDocGenerator.VisualBasic/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/SonarAnalyzer.VisualBasic/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/pom.xml
- sonaranalyzer-dotnet/src/AssemblyInfo.Shared.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CFG/SonarAnalyzer.CFG.cs.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.RuleDescriptorGenerator/Descriptor.cs.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.RuleDescriptorGenerator/Descriptor.vbnet.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/SonarAnalyzer.CSharp.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/SonarAnalyzer.VisualBasic.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/source.extension.vsixmanifest
Prepare the next development iteration
> Bump version to 8.5

- docs/contributing-analyzer.md
> Mention .NET 3.5 SDK (SP1) dependency

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/StaticFieldInitializerOrder.cs
- use structs where possible (IdentifierFieldMapping, IdentifierTypeDeclarationMapping)
- check exit conditions as early as possible
- use the syntax tree instead of semantic model where possible
This commit reduces the StaticFieldInitializerOrder rule execution time using the AnalyzerTool on noda-time from ~7134ms to ~2009ms. An improvement of 71%.
> Improve performance for StaticFieldInitializerOrder

- README.md
(we don't support MSTest UT results - see #2529)
> Remove mstest from docs

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/PropertiesShouldBePreferred.cs
> Add repro for S4049 #3140

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/NullPointerDereference.cs
> Add repro for S2259

- sonaranalyzer-dotnet/rspec/cs/S2068_c#.html
- sonaranalyzer-dotnet/rspec/vbnet/S2068_vb.net.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/Hotspots/DoNotHardcodeCredentials.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Rules/Hotspots/DoNotHardcodeCredentialsBase.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S2068_cs.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S2068_vb.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Rules/Hotspots/DoNotHardcodeCredentials.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DoNotHardcodeCredentials_CustomValues.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DoNotHardcodeCredentials_CustomValues.vb
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DoNotHardcodeCredentials_DefaultValues.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DoNotHardcodeCredentials_DefaultValues.vb
Fixes #2865
Reported messages were update according to current RSPEC.
> Rule S2068: support url userinfo component

- sonaranalyzer-dotnet/rspec/cs/S4275_c#.html
- sonaranalyzer-dotnet/rspec/vbnet/S4275_vb.net.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/CSharpSyntaxHelper.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/PropertiesAccessCorrectField.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Rules/PropertiesAccessCorrectFieldBase.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S4275_cs.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S4275_vb.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Rules/PropertiesAccessCorrectField.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/PropertiesAccessCorrectField.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/PropertiesAccessCorrectField.vb
> Fix S4275 FP when method is used inside getter or setter

- sonaranalyzer-dotnet/src/SonarAnalyzer.CFG/ControlFlowGraph/CSharpControlFlowGraphBuilder.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SymbolicExecution/CSharp/CSharpExplodedGraph.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/ControlFlowGraph/CfgSerializerTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/ControlFlowGraph/ControlFlowGraphTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/SymbolicExecution/ExplodedGraphTests.cs
> Fix SymbolicExecution error AD0001 for indices and ranges

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/ValueTypeShouldImplementIEquatable.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/ValueTypeShouldImplementIEquatableTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ValueTypeShouldImplementIEquatable.cs
> Fix S3898 FP: ref structs can not implement interfaces

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/RedundantJumpStatement.cs
> Add repro for S3626 FP

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/PropertiesAccessCorrectField.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/PropertiesAccessCorrectField.cs
> Fix S4275 Bug: C# auto-implemented property with AggressiveInlining throws NRE

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/PropertyToAutoProperty.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/PropertyToAutoProperty.CSharp7.cs
> Fix S2292: FP on volatile fields

- sonaranalyzer-dotnet/rspec/cs/S2068_c#.html
- sonaranalyzer-dotnet/rspec/vbnet/S2068_vb.net.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Rules/Hotspots/DoNotHardcodeCredentialsBase.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S2068_cs.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S2068_vb.html
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DoNotHardcodeCredentials_DefaultValues.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DoNotHardcodeCredentials_DefaultValues.vb
> Rule S2068: filter string literal that contains the wordlist item

- sonaranalyzer-dotnet/rspec/cs/S4426_c#.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/CryptographicKeyShouldNotBeTooShort.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S4426.html
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/FrameworkMetadataReference.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/NuGetMetadataReference.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/CryptographicKeyShouldNotBeTooShortTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/CryptographicKeyShouldNotBeTooShort.cs
> Rule S4426: support more cryptographic algorithms

- sonaranalyzer-dotnet/.sonarlint/SonarAnalyzer.slconfig
- sonaranalyzer-dotnet/.sonarlint/sonaranalyzer-dotnetCSharp.ruleset
> Update SonarLint profiles after activating more rules

- sonaranalyzer-dotnet/its/sources/ManuallyAddedNoncompliantIssues/NetFramework35/NetFramework35.csproj
- sonaranalyzer-dotnet/its/sources/ManuallyAddedNoncompliantIssues/NetFramework35/XPathDocumentTest.cs
- sonaranalyzer-dotnet/its/sources/ManuallyAddedNoncompliantIssues/NetFramework4/NetFramework4.csproj
- sonaranalyzer-dotnet/its/sources/ManuallyAddedNoncompliantIssues/NetFramework4/XPathDocumentTest.cs
- sonaranalyzer-dotnet/its/sources/ManuallyAddedNoncompliantIssues/NetFramework45/NetFramework45.csproj
- sonaranalyzer-dotnet/its/sources/ManuallyAddedNoncompliantIssues/NetFramework45/XPathDocumentTest.cs
- sonaranalyzer-dotnet/its/sources/ManuallyAddedNoncompliantIssues/NetFramework452/NetFramework452.csproj
- sonaranalyzer-dotnet/its/sources/ManuallyAddedNoncompliantIssues/NetFramework452/XPathDocumentTest.cs
- sonaranalyzer-dotnet/its/sources/ManuallyAddedNoncompliantIssues/NetFramework48/NetFramework48.csproj
- sonaranalyzer-dotnet/its/sources/ManuallyAddedNoncompliantIssues/NetFramework48/XPathDocumentTest.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/ArgumentSyntaxExtensions.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/InvocationExpressionSyntaxExtensions.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/ObjectCreationExpressionSyntaxExtensions.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/XmlExternalEntityShouldNotBeParsed.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/XmlExternalEntityShouldNotBeParsedTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/XmlExternalEntityShouldNotBeParsed_XPathDocument_Net35.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/XmlExternalEntityShouldNotBeParsed_XPathDocument_Net4.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/XmlExternalEntityShouldNotBeParsed_XPathDocument_Net452.cs
> Implement S2755 for XPathNavigator

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ParameterValidationInAsyncShouldBeWrapped.cs
> Add FP repro for S4457

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/LdapConnectionShouldBeSecure.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/XmlExternalEntityShouldNotBeParsed.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SyntaxTrackers/CSharpObjectInitializationTracker.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/LdapConnectionShouldBeSecureTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/LdapConnectionShouldBeSecure.cs
> Fix S4433 FP

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/MemberShouldBeStatic.cs
> Add FP repro for S2325

- sonaranalyzer-dotnet/src/SonarAnalyzer.CFG/Helpers/CSharpSyntaxHelper.cs
> Remove unused method (IsOn)

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/StaticFieldInitializerOrder.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/StaticFieldInitializerOrder.cs
> Fix S3263 FP: Static initialization is not detected in struct

- sonaranalyzer-dotnet/rspec/cs/S2755_c#.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S2755.html
> Update RSPEC for XXE rule

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/Hotspots/DoNotHardcodeCredentials.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Rules/Hotspots/DoNotHardcodeCredentialsBase.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/SyntaxTrackers/ObjectCreationTracker.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/SyntaxTrackers/PropertyAccessTracker.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DoNotHardcodeCredentials_DefaultValues.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DoNotHardcodeCredentials_DefaultValues.vb
> Display correct message when hardcoded password is detected

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/Hotspots/DoNotHardcodeCredentials.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Rules/Hotspots/DoNotHardcodeCredentialsBase.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Helpers/VisualBasicSyntaxHelper.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Rules/Hotspots/DoNotHardcodeCredentials.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DoNotHardcodeCredentials_DefaultValues.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DoNotHardcodeCredentials_DefaultValues.vb
> Fix S2068 FN: Raise issue for literals passed as arguments

- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Rules/Hotspots/DoNotHardcodeCredentialsBase.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DoNotHardcodeCredentials_DefaultValues.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DoNotHardcodeCredentials_DefaultValues.vb
Issue was raised for HTML fragments containing expected URI parts.
> Fix S2068 FP: Precise UserInfo match for URI

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/CSharpSymbolUsageCollector.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/CSharpSyntaxHelper.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/LiveVariableAnalysis/CSharp/CSharpLiveVariableAnalysis.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/CallToAsyncMethodShouldNotBeBlocking.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/DeadStores.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/InfiniteRecursion.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/MemberInitializerRedundant.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/MemberShouldBeStatic.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/CallToAsyncMethodShouldNotBeBlocking.cs
> Fix S4462 FP when using nameof()

- sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/BranchCoverage.java
- sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/Coverage.java
- sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/CoverageReportImportSensor.java
- sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/LineBranchCoverage.java
- sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/OpenCoverReportParser.java
- sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/BranchCoverageTest.java
- sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/CoverageReportImportSensorTest.java
- sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/CoverageTest.java
- sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/OpenCoverReportParserTest.java
- sonar-dotnet-shared-library/src/test/resources/opencover/coverage_branches.xml
> Add branch coverage support for OpenCover

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/InheritedCollidingInterfaceMembers.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/InheritedCollidingInterfaceMembers.AfterCSharp8.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/InheritedCollidingInterfaceMembers.cs
> S3444 Add missing name in the message for indexers

- azure-pipelines.yml
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/SonarAnalyzer.UnitTest.csproj
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/packages.lock.json
> Compute branch coverage with OpenCover

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/VariableUnused.cs
> Add FP repro for S1481

- azure-pipelines-external.yml
> Simple pipeline for external checks

- README.md
> Update README - how to trigger CI on external PRs

- azure-pipelines-external.yml
- these steps need Azure secrets and are not safe for external PRs
> Remove SonarCloud check

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/MethodParameterUnused.CSharp8.cs
> Add FP repro for S1172

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/XXE/XmlReaderSettingsValidator.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/XmlExternalEntityShouldNotBeParsedTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/XmlExternalEntityShouldNotBeParsed_XmlReader_ExternalParameter.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/XmlExternalEntityShouldNotBeParsed_XmlReader_ParameterProvider.cs
> Fix S2755 Bug: Rule throws ArgumentException

- sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/BranchCoverage.java
- sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/VisualStudioCoverageXmlReportParser.java
- sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/BranchCoverageTest.java
- sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/VisualStudioCoverageXmlReportParserTest.java
- sonar-dotnet-shared-library/src/test/resources/visualstudio_coverage_xml/getter_setter.coveragexml
- sonar-dotnet-shared-library/src/test/resources/visualstudio_coverage_xml/getter_setter_multiple_per_line.coveragexml
- sonar-dotnet-shared-library/src/test/resources/visualstudio_coverage_xml/no_ranges.coveragexml
- sonar-dotnet-shared-library/src/test/resources/visualstudio_coverage_xml/valid_complex_case.coveragexml
> VS coverage - treat multiple coverage per line as branch coverage

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UnusedReturnValue.cs
> Add S3241 FN reproducer

- sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/UnitTestResultsImportSensor.java
- sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/UnitTestResultsImportSensorTest.java
> Do not fail the build when importing unit test reports for solutions with VB and C# projects

- README.md
> Add Coverlet to the list of supported coverage tools

- .github/ISSUE_TEMPLATE/false-positive---false-negative.md
- .github/ISSUE_TEMPLATE/the-analyzer-is-crashing.md
- README.md
- THIRD-PARTY-NOTICES.txt
- docs/contributing-analyzer.md
- docs/contributing-plugin.md
- docs/issues.md
- sonar-csharp-plugin/README.md
- sonar-csharp-plugin/pom.xml
- sonar-dotnet-shared-library/README.md
- sonar-vbnet-plugin/README.md
- sonar-vbnet-plugin/pom.xml
> Remove terms 'SonarC#' and 'SonarVB' from docs

- sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/DotCoverReportParser.java
- sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/DotCoverReportParserTest.java
- sonar-dotnet-shared-library/src/test/resources/dotcover/valid_multiple_sequence_points_per_line.html
> Improve dotCover get\set coverage report

- sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/DotCoverReportParser.java
- sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/OpenCoverReportParser.java
- sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/SequencePoint.java
- sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/SequencePointCollector.java
- sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/DotCoverReportParserTest.java
- sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/OpenCoverReportParserTest.java
- sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/SequencePointCollectorTest.java
> Refactor DotCover and OpenCover coverage parsers to reuse code

- sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/CoverageAggregator.java
- sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/NCover3ReportParser.java
- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/CodeCoverageProvider.java
- sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/CoverageAggregatorTest.java
- sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/NCover3ReportParserTest.java
- sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/CodeCoverageProviderTest.java
> Deprecate NCover3 support

- azure-pipelines.yml
- in order to have the burgr notifications working
Fixes #3280
> Add GITHUB_BRANCH and GIT_SHA1 env var

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/ClassAndMethodName.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ClassName.cs
> Fix S101 FP: IEnumerableExtensionsTests should not be reported

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ConditionEvaluatesToConstant.CSharp7.cs
Reproduces #3239
Should be merged after 8.6 release.
> Add FP repro for S2589

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UnchangedLocalVariablesShouldBeConst.cs
Reproduces #3271
Should be merged after 8.6 release.
> Add FP repro for S3353

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ConditionEvaluatesToConstant.CSharp7.cs
> Add FP repro for S2583

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/NullPointerDereference.cs
> Add FN repro for S2259

- sonar-csharp-plugin/src/test/java/org/sonar/plugins/csharp/CSharpSonarRulesDefinitionTest.java
- sonaranalyzer-dotnet/rspec/cs/S1104_c#.json
- sonaranalyzer-dotnet/rspec/cs/S2486_c#.json
- sonaranalyzer-dotnet/rspec/cs/S3415_c#.html
- sonaranalyzer-dotnet/rspec/cs/S3984_c#.json
- sonaranalyzer-dotnet/rspec/cs/S4212_c#.json
- sonaranalyzer-dotnet/rspec/cs/S4433_c#.html
- sonaranalyzer-dotnet/rspec/cs/S4507_c#.json
- sonaranalyzer-dotnet/rspec/cs/S4564_c#.json
- sonaranalyzer-dotnet/rspec/vbnet/S4507_vb.net.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S3415.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S4433.html
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/PackagingTests/CsRuleTypeMapping.cs
Update RSPEC files before 8.6.1 bugfix release.
> update RSPECs for 8.6.1 release

- pom.xml
- scripts/version/Version.props
- sonar-csharp-plugin/pom.xml
- sonar-dotnet-shared-library/pom.xml
- sonar-vbnet-plugin/pom.xml
- sonaranalyzer-dotnet/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/SonarAnalyzer.CSharp/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/SonarAnalyzer.RuleDocGenerator.CSharp/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/SonarAnalyzer.RuleDocGenerator.VisualBasic/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/SonarAnalyzer.VisualBasic/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/pom.xml
- sonaranalyzer-dotnet/src/AssemblyInfo.Shared.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CFG/SonarAnalyzer.CFG.cs.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.RuleDescriptorGenerator/Descriptor.cs.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.RuleDescriptorGenerator/Descriptor.vbnet.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/SonarAnalyzer.CSharp.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/SonarAnalyzer.VisualBasic.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/source.extension.vsixmanifest
> Bump version to 8.7

- azure-pipelines.yml
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/XmlExternalEntityShouldNotBeParsedTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/MethodParameterUnused.CSharp8.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestFramework/Verifier.cs
> Ensure that OpenCover returns the exit code from test runner

- sonaranalyzer-dotnet/rspec/cs/S3011_c#.html
- sonaranalyzer-dotnet/rspec/cs/S3011_c#.json
- sonaranalyzer-dotnet/rspec/vbnet/S3011_vb.net.html
- sonaranalyzer-dotnet/rspec/vbnet/S3011_vb.net.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S3011_cs.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S3011_vb.html
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/PackagingTests/CsRuleTypeMapping.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/PackagingTests/VbRuleTypeMapping.cs
This will update the rule type to Code Smell and severity to Major.
Fixes #3285
> Update rspec for S3011

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/UnnecessaryUsings.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UnnecessaryUsings.Fixed.Batch.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UnnecessaryUsings.Fixed.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UnnecessaryUsings.cs
> S1128 FP: Fix for collection initializer extension methods

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UsingRegularExpressions.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UsingRegularExpressions.vb
> Add FN repro for S4784

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DeadStores.cs
> Add FP repro for S1854

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/XmlExternalEntityShouldNotBeParsed.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SonarAnalyzer.CSharp.csproj
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/packages.lock.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.RuleDescriptorGenerator/packages.lock.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/packages.lock.json
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/packages.lock.json
> Remove 'System.ValueTuple' use from C# analyzer

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/EnumStorageNeedsToBeInt32.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/EnumStorageNeedsToBeInt32.cs
> Allow also uint, long and ULong

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/UnchangedLocalVariablesShouldBeConst.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UnchangedLocalVariablesShouldBeConst.cs
> Consider lambda functions as parent method

- pom.xml
- scripts/version/Version.props
- sonar-csharp-plugin/pom.xml
- sonar-dotnet-shared-library/pom.xml
- sonar-vbnet-plugin/pom.xml
- sonaranalyzer-dotnet/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/SonarAnalyzer.CSharp/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/SonarAnalyzer.RuleDocGenerator.CSharp/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/SonarAnalyzer.RuleDocGenerator.VisualBasic/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/SonarAnalyzer.VisualBasic/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/pom.xml
- sonaranalyzer-dotnet/src/AssemblyInfo.Shared.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CFG/SonarAnalyzer.CFG.cs.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.RuleDescriptorGenerator/Descriptor.cs.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.RuleDescriptorGenerator/Descriptor.vbnet.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/SonarAnalyzer.CSharp.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/SonarAnalyzer.VisualBasic.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/source.extension.vsixmanifest
> Bump version to 8.8

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ClassNotInstantiatable.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ClassNotInstantiatable.vb
> Add FP repro for S3453

- .editorconfig
> Update .editorconfig: avoid "this." and "Me." if not necessary

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/EmptyCollectionsShouldNotBeEnumerated.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/SymbolicExecutionAnalyzerFactory.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/SymbolicExecutionRunner.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/EmptyCollectionsShouldNotBeEnumeratedTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/EmptyNullableValueAccessTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/ObjectsShouldNotBeDisposedMoreThanOnceTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/PublicMethodArgumentsShouldBeCheckedForNullTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/SymbolicExecutionAnalyzerFactoryTest.cs
> Refactor S4158 to reuse symbolic execution

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ConditionEvaluatesToConstant.CSharp8.cs
> Add FP for S2589

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/DeadStores.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/FieldShouldBeReadonly.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/GenericReadonlyFieldPropertyAssignment.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/StaticFieldWrittenFrom.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/FieldShouldBeReadonlyTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/GenericReadonlyFieldPropertyAssignmentTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/StaticFieldWrittenFromInstanceConstructorTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DeadStores.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/FieldShouldBeReadonly.Fixed.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/FieldShouldBeReadonly.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/GenericReadonlyFieldPropertyAssignment.AddConstraint.Fixed.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/GenericReadonlyFieldPropertyAssignment.Remove.Fixed.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/GenericReadonlyFieldPropertyAssignment.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/StaticFieldWrittenFromInstanceConstructor.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/StaticFieldWrittenFromInstanceMember.cs
> Fix S2933 FP and related S1854, S3010, S2696, S2934 FN: Null-coalescing assignment is not recognized

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/ConditionEvaluatesToConstant.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/EmptyCollectionsShouldNotBeEnumerated.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/EmptyNullableValueAccess.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/ISymbolicExecutionAnalysisContext.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/ObjectsShouldNotBeDisposedMoreThanOnce.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/PublicMethodArgumentsShouldBeCheckedForNull.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/SymbolicExecutionAnalyzerFactory.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/SymbolicExecutionRunner.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/ConditionEvaluatesToConstantTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/SymbolicExecutionAnalyzerFactoryTest.cs
> Refactor S2583 and S2589 to reuse symbolic execution

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/InvalidCastToInterfaceSymbolicExecution.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/SymbolicExecutionAnalyzerFactory.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/InvalidCastToInterfaceTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/SymbolicExecutionAnalyzerFactoryTest.cs
> Refactor InvalidCastToInterface to reuse SE

- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/ParameterLoader.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Helpers/ParameterLoaderTests.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Helpers/PropertiesHelperTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/ResourceTests/RuleWithBooleanParameter/SonarLint.xml
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/ResourceTests/RuleWithStringParameter/SonarLint.xml
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/ResourceTests/StringInsteadOfBoolean/SonarLint.xml
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/ResourceTests/StringInsteadOfInt/SonarLint.xml
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/ResourceTests/ToChange/SonarLint.xml
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/SonarAnalyzer.UnitTest.csproj
> Stop caching rule parameters; hardening for reading the config file

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SymbolicExecution/Common/Constraints/SymbolicValueConstraints.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SymbolicExecution/Common/SymbolicValues/SymbolicValue.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/SymbolicExecutionRulesTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecutionRules.cs
> S2583: Fix FP when using the new "using statement" from C# 8

- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Tests-{776D244D-BC4D-4BBB-A478-CAF2D04520E1}-S4586.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/NonAsyncTaskShouldNotReturnNull.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Rules/NonAsyncTaskShouldNotReturnNullBase.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/NonAsyncTaskShouldNotReturnNull.cs
> S4586: Fix FP and FN with simple lambda expressions

- sonaranalyzer-dotnet/its/sources/ManuallyAddedNoncompliantIssues/NetFramework48/JavaScriptSerializerTest.cs
- sonaranalyzer-dotnet/its/sources/ManuallyAddedNoncompliantIssues/NetFramework48/NetFramework48.csproj
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/RestrictDeserializedTypes.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SymbolicExecution/Common/Constraints/SerializationConstraint.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SymbolicExecution/Common/SymbolicValues/SymbolicValue.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/FrameworkMetadataReference.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/RestrictDeserializedTypesTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/SonarAnalyzer.UnitTest.csproj
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Constraints/SerializationConstraintTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/RestrictDeserializedTypes.Binders.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/RestrictDeserializedTypes.JavaScriptSerializer.cs
> S5773: Add checks for JavaScriptSerializer

- sonaranalyzer-dotnet/its/sources/ManuallyAddedNoncompliantIssues/NetFramework48/LosFormatterTest.cs
- sonaranalyzer-dotnet/its/sources/ManuallyAddedNoncompliantIssues/NetFramework48/NetFramework48.csproj
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/BaseArgumentListSyntaxExtensions.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/RestrictDeserializedTypes.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Helpers/BaseArgumentListSyntaxExtensionsTests.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/RestrictDeserializedTypesTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/RestrictDeserializedTypes.LosFormatter.cs
> S5773: Add checks for LosFormatter

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/RestrictDeserializedTypes.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/RestrictDeserializedTypes.JavaScriptSerializer.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/RestrictDeserializedTypes.LosFormatter.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/RestrictDeserializedTypes.cs
> S5773: Fix bug when processing object initializer

- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- remove unused fields
- remove redundant "this."
- use expression body where possible
> Cleanup around KnownType

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/MethodShouldBeNamedAccordingToSynchronicity.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/AspNetMvcHelper.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/NuGetMetadataReference.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/MethodShouldBeNamedAccordingToSynchronicityTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/MethodShouldBeNamedAccordingToSynchronicity.cs
> S4261: should not report for SignalR hub methods

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/SyntaxNodeExtensions.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/InsecureDeserialization.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/InsecureDeserialization.cs
> S5766: Fix handling of IDeserializationCallback indirect implementation

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/MethodsShouldUseBaseTypes.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/MethodsShouldUseBaseTypes.cs
> Fix S3242 FP and FN: Consider double conditional access

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/NullPointerDereferenceCSharp6.cs
> Add repro for 3416

- sonar-csharp-plugin/pom.xml
- sonar-vbnet-plugin/pom.xml
- sonaranalyzer-dotnet/src/SonarAnalyzer.RuleDescriptorGenerator/Descriptor.cs.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.RuleDescriptorGenerator/Descriptor.vbnet.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.RuleDescriptorGenerator/SonarAnalyzer.RuleDescriptorGenerator.csproj
- sonaranalyzer-dotnet/src/SonarAnalyzer.RuleDescriptorGenerator/packages.lock.json
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/packages.lock.json
> Migrate RuleDescriptorGenerator to .NetCore 3.1

- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Demo.MarkdownViewEngine-{B6929D0B-5104-4C7E-979D-F4914E813FA6}-S5766.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Hosting.Self-{AA7F66EB-EC2C-47DE-855F-30B3E6EF2134}-S5766.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Cluster.Sharding-{A05C31E8-0246-46A1-B3BC-4D6FE7A9AA49}-S5766.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Cluster.Tools-{5CF8A8BE-B634-473F-BB01-EBA878746BD4}-S5766.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Persistence-{FCA84DEA-C118-424B-9EB8-34375DFEF18A}-S5766.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Persistence.Sql.Common-{3B9E6211-9488-4DB5-B714-24248693B38F}-S5766.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/InsecureDeserialization.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Common/RuleTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/InsecureDeserializationTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/InsecureDeserialization.cs
- change location to contain only the method name
Issue #3421
> Run InsecureDeserialization only when using scanner

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/MethodShouldBeNamedAccordingToSynchronicity.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/MethodShouldBeNamedAccordingToSynchronicityTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/MethodShouldBeNamedAccordingToSynchronicity.CSharp8.cs
> S4261: FP on methods which return IAsyncEnumerable<T>

- sonaranalyzer-dotnet/its/regression-test.ps1
> Disable S3949 for Net5 and make the script fail when dotnet build fails

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/MetadataReferences/FrameworkMetadataReference.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/MetadataReferences/MetadataReferenceFacade.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/MetadataReferences/MetadataReferenceFactory.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/PropertiesAccessCorrectFieldTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/PropertiesAccessCorrectField.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/PropertiesAccessCorrectField.vb
note that the second ticket is on hold as I cannot repro
related to #3441 and #3442
> Add two repro cases for S4275

- sonaranalyzer-dotnet/SonarAnalyzer.UnitTest.CSharp9.sln
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest.CSharp9/EmptyMethodTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest.CSharp9/ReadMe.md
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest.CSharp9/SonarAnalyzer.UnitTest.CSharp9.csproj
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Properties/AssemblyInfo.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestFramework/Verifier.cs
> Add unit test with C#9 syntax

- pom.xml
- scripts/version/Version.props
- sonar-csharp-plugin/pom.xml
- sonar-dotnet-shared-library/pom.xml
- sonar-vbnet-plugin/pom.xml
- sonaranalyzer-dotnet/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/SonarAnalyzer.CSharp/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/SonarAnalyzer.RuleDocGenerator.CSharp/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/SonarAnalyzer.RuleDocGenerator.VisualBasic/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/SonarAnalyzer.VisualBasic/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/pom.xml
- sonaranalyzer-dotnet/src/AssemblyInfo.Shared.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CFG/SonarAnalyzer.CFG.cs.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.RuleDescriptorGenerator/Descriptor.cs.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.RuleDescriptorGenerator/Descriptor.vbnet.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/SonarAnalyzer.CSharp.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/SonarAnalyzer.VisualBasic.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/source.extension.vsixmanifest
> Bump version to 8.11

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DeclareEventHandlersCorrectly.cs
> S3906: Add repro for #3453

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/CallToAsyncMethodShouldNotBeBlockingTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/CallToAsyncMethodShouldNotBeBlocking.cs
> S4462: Add repro for #3452

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/PublicMethodArgumentsShouldBeCheckedForNull.cs
> S3900: Add FP repro for #3400

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ConditionalSimplification.FromCSharp8.Fixed.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ConditionalSimplification.FromCSharp8.cs
> S3240: Add FP repro for #3468

- docs/contributing-analyzer.md
> Remove NuGet lock files section

- pom.xml
- scripts/version/Version.props
- sonar-csharp-plugin/pom.xml
- sonar-dotnet-shared-library/pom.xml
- sonar-vbnet-plugin/pom.xml
- sonaranalyzer-dotnet/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/SonarAnalyzer.CSharp/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/SonarAnalyzer.RuleDocGenerator.CSharp/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/SonarAnalyzer.RuleDocGenerator.VisualBasic/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/SonarAnalyzer.VisualBasic/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/pom.xml
- sonaranalyzer-dotnet/src/AssemblyInfo.Shared.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CFG/SonarAnalyzer.CFG.cs.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.RuleDescriptorGenerator/Descriptor.cs.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.RuleDescriptorGenerator/Descriptor.vbnet.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/SonarAnalyzer.CSharp.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/SonarAnalyzer.VisualBasic.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/source.extension.vsixmanifest
> Bump version to 8.12

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DoNotNestTypesInArguments.cs
> S4017: Add FP repro for #3277

- sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/sarif/SarifParser01And04Test.java
- sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/sarif/SarifParser10Test.java
anyCollectionOf is deprecated and the only thing is doing is calling anyCollection
Partial fix for: #3480
> Replace Mockito.anyCollectionOf with Mockito.anyCollection

- sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/PropertiesSensorTest.java
- sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/protobuf/MetricsImporterTest.java
> Use ArgumentMatchers.any instead of Matchers.any

- scripts/rspec/rspec2resx.ps1
> Add logging to help with troubleshooting

- sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/AbstractProjectConfigurationTest.java
> Remove usage of deprecated MapSettings

- its/src/test/java/com/sonar/it/csharp/CasingAppTest.java
- its/src/test/java/com/sonar/it/csharp/CoverageTest.java
- its/src/test/java/com/sonar/it/csharp/DoNotAnalyzeTestFilesTest.java
- its/src/test/java/com/sonar/it/csharp/MetricsIncludeHeaderCommentTest.java
- its/src/test/java/com/sonar/it/csharp/MetricsTest.java
- its/src/test/java/com/sonar/it/csharp/MultiTargetAppTest.java
- its/src/test/java/com/sonar/it/csharp/SharedFilesTest.java
- its/src/test/java/com/sonar/it/shared/TestUtils.java
- its/src/test/java/com/sonar/it/vbnet/CoverageTest.java
- its/src/test/java/com/sonar/it/vbnet/DoNotAnalyzeTestFilesTest.java
- its/src/test/java/com/sonar/it/vbnet/MetricsTest.java
- modules are no longer supported
> Remove usages of TestUtils.hasModules

- sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/AbstractProjectConfigurationTest.java
after merging #3477 I realized this small improvement would make tests easier to read
> Refactor the two tests calling mockProtobufOutPaths to be together

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Common/MetricsTest.cs
> Add repro for #3513

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Common/MetricsTest.cs
- currently enums are not counted towards the total number of classes
> Document class metric behavior for enums

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/CognitiveComplexity.cs
> Add repro for #3516

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Common/MetricsTest.cs
> Add repro for #3518

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Metrics/CSharpCyclomaticComplexityMetric.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Common/MetricsTest.cs
> Count switch expression arms when computing cyclomatic complexity

- its/src/test/java/com/sonar/it/csharp/MultipleProjectsTest.java
I merged #3509 after #3521  which changed the way complexity was computed.
> Fix build break

- its/src/test/java/com/sonar/it/csharp/MultipleProjectsTest.java
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Metrics/CSharpCognitiveComplexityMetric.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Common/MetricsTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/CognitiveComplexity.cs
> Count switch expression arms when computing cognitive complexity

- its/projects/MultipleProjects/opencover.xml
- its/src/test/java/com/sonar/it/csharp/CoverageTest.java
Related to  #3506
With this, we'll have more comprehensive tests for coverage import.
> Add opencover integration test for MultipleProjects

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Metrics/CSharpCyclomaticComplexityMetric.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/FunctionComplexity.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Common/MetricsTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/FunctionComplexity.cs
> Count null-coalescing assignment when computing cyclomatic complexity

- its/projects/MultipleProjects/README.md
- its/projects/MultipleProjects/VisualStudio.coveragexml
- its/src/test/java/com/sonar/it/csharp/CoverageTest.java
> Add visual studio coverage test for MultipleProjects

- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/AbstractGlobalProtobufFileProcessor.java
- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/AbstractModuleConfiguration.java
- sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/AbstractGlobalProtobufFileProcessorTest.java
- sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/AbstractModuleConfigurationTest.java
> Drop support of Scanner for MSBuild <= 3.0

- its/pom.xml
- sonar-csharp-plugin/pom.xml
- sonar-vbnet-plugin/pom.xml
> Fix maven project structure

- azure-pipelines.yml
> Use the `release` mvn profile

- pom.xml
- scripts/version/Version.props
- sonar-csharp-plugin/pom.xml
- sonar-dotnet-shared-library/pom.xml
- sonar-vbnet-plugin/pom.xml
- sonaranalyzer-dotnet/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/SonarAnalyzer.CSharp/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/SonarAnalyzer.RuleDocGenerator.CSharp/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/SonarAnalyzer.RuleDocGenerator.VisualBasic/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/SonarAnalyzer.VisualBasic/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/pom.xml
- sonaranalyzer-dotnet/src/AssemblyInfo.Shared.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CFG/SonarAnalyzer.CFG.cs.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/SonarAnalyzer.CSharp.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/SonarAnalyzer.VisualBasic.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/source.extension.vsixmanifest
Note that there are less files to update after #3542
> Bump version to 8.13

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/FieldShadowsParentFieldTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/FieldShadowsParentField.cs
> S2387: Add FP repro for #3393

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.resx
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/RspecStrings.resx
my bad - it seems I missed them (there were other changes which I ignored and due to the noise I missed these)
> Fix RSPEC update leftover

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/RedundantArgumentTest.cs
> S3254: Fix RedundantArgumentTest references

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/UnusedPrivateMember.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/UnusedPrivateMemberTest.cs
> S1144, S4487: Ignore entity framework migration files

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SymbolicExecution/Common/Constraints/StringConstraint.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SymbolicExecution/Common/SymbolicValues/SymbolicValue.cs
Please review it per commit. The mess in `UpdateStringConstraint` would be hard to follow otherwise.
> SymbolicValue refactoring

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/CSharpSymbolUsageCollector.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UnusedPrivateMember.Fixed.Batch.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UnusedPrivateMember.Fixed.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UnusedPrivateMember.cs
> S1144, S4487: Check known types for ElementAccessExpression

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/PropertiesAccessCorrectField.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/PropertiesAccessCorrectFieldTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/PropertiesAccessCorrectField.CSharp8.cs
> Fix S4275 FP: Consider ??= as assignment

- sonaranalyzer-dotnet/its/expected/Automapper/AutoMapper-025B9F93-7953-454B-AF29-E6A55B2AA58F-S4017.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy-{34576216-0DCA-4B0F-A0DC-9075E75A676F}-S4017.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/DoNotNestTypesInArguments.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/DoNotNestTypesInArgumentsTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DoNotNestTypesInArguments.cs
> S4017: Don't count Nullable<T> shorthand

- sonaranalyzer-dotnet/its/expected/Nancy/Nancy-{34576216-0DCA-4B0F-A0DC-9075E75A676F}-S3240.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/ConditionalSimplification.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/ConditionalSimplificationTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ConditionalSimplification.FromCSharp8.Fixed.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ConditionalSimplification.FromCSharp8.cs
> Fix S3240 FP: Nested conditional operators

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/VariableUnused.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Rules/VariableUnused.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/VariableUnused.cs
> Fix S1481 FP: "var using" declarations should not raise issue

- .github/workflows/release.yml
> Add slack notification on central sync error

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/ConditionEvaluatesToConstantTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ConditionEvaluatesToConstant.cs
> S2583: Add repro for #3565

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/BaseMethodDeclarationSyntaxExtensions.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/IFieldSymbolExtensions.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/DisposableMemberInNonDisposableClass.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Helpers/BaseMethodDeclarationSyntaxExtensionsTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/DisposableMemberInNonDisposableClassTest.cs
> Fix S2931 FP: Handle IAsyncDisposable as disposing interface

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/CSharpSyntaxHelper.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/UnnecessaryUsings.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/UnnecessaryUsingsTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UnnecessaryUsings.TupleDeconstruct.cs
> Fix S1128 FP: System namespace is needed for tuple deconstruction

- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/DotNetSensor.java
- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/PropertiesSensor.java
- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/ReportPathCollector.java
- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/RoslynDataImporter.java
- sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/DotNetSensorTest.java
- sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/PropertiesSensorTest.java
- sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/ReportPathCollectorTest.java
> Fail fast for SonarScanner for MSBuild <= 3.0

- sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/RoslynProfileExporterTest.java
https://sonarcloud.io/project/issues?id=org.sonarsource.dotnet%3Asonar-csharp&open=AXLgpoDS5Aia9KydA8Xr&resolved=false&severities=MAJOR&types=CODE_SMELL
> Fix last Java CodeSmell: bug

- pom.xml
- scripts/version/Version.props
- sonar-csharp-plugin/pom.xml
- sonar-dotnet-shared-library/pom.xml
- sonar-vbnet-plugin/pom.xml
- sonaranalyzer-dotnet/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/SonarAnalyzer.CSharp/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/SonarAnalyzer.RuleDocGenerator.CSharp/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/SonarAnalyzer.RuleDocGenerator.VisualBasic/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/SonarAnalyzer.VisualBasic/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/pom.xml
- sonaranalyzer-dotnet/src/AssemblyInfo.Shared.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CFG/SonarAnalyzer.CFG.cs.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/SonarAnalyzer.CSharp.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/SonarAnalyzer.VisualBasic.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/source.extension.vsixmanifest
> bump version for 8.14

- pom.xml
- scripts/version/Version.props
- sonar-csharp-plugin/pom.xml
- sonar-dotnet-shared-library/pom.xml
- sonar-vbnet-plugin/pom.xml
- sonaranalyzer-dotnet/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/SonarAnalyzer.CSharp/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/SonarAnalyzer.RuleDocGenerator.CSharp/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/SonarAnalyzer.RuleDocGenerator.VisualBasic/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/SonarAnalyzer.VisualBasic/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/pom.xml
- sonaranalyzer-dotnet/src/AssemblyInfo.Shared.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CFG/SonarAnalyzer.CFG.cs.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/SonarAnalyzer.CSharp.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/SonarAnalyzer.VisualBasic.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/source.extension.vsixmanifest
> Set 8.13.1 version

- sonaranalyzer-dotnet/rspec/cs/S3358_c#.html
- sonaranalyzer-dotnet/rspec/vbnet/S3358_vb.net.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/sonarpedia.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S3358_cs.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S3358_vb.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/sonarpedia.json
because the other updates need implementation updates as well
> Update RSPEC S3358

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/InfiniteRecursion.cs
> S2190: Add FN repro for #3624

- pom.xml
- scripts/version/Version.props
- sonar-csharp-plugin/pom.xml
- sonar-dotnet-shared-library/pom.xml
- sonar-vbnet-plugin/pom.xml
- sonaranalyzer-dotnet/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/SonarAnalyzer.CSharp/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/SonarAnalyzer.RuleDocGenerator.CSharp/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/SonarAnalyzer.RuleDocGenerator.VisualBasic/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/SonarAnalyzer.VisualBasic/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/pom.xml
- sonaranalyzer-dotnet/src/AssemblyInfo.Shared.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CFG/SonarAnalyzer.CFG.cs.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/SonarAnalyzer.CSharp.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/SonarAnalyzer.VisualBasic.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/source.extension.vsixmanifest
> Bump version to 8.14

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/ControlFlowGraph/ControlFlowGraphTest.cs
> Add repro for #3611

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/GetTypeWithIsAssignableFrom.Fixed.Batch.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/GetTypeWithIsAssignableFrom.Fixed.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/GetTypeWithIsAssignableFrom.cs
> S2219: Add FP repro for #3605

- sonaranalyzer-dotnet/its/expected/Automapper/AutoMapper.UnitTests-F0CC7EF4-B035-4FE1-A476-0676F7251200-S2699.json
- sonaranalyzer-dotnet/its/sources/NetCore31/global.json
- sonaranalyzer-dotnet/rspec/cs/S2699_c#.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/TestMethodShouldContainAssertion.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S2699.html
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/TestMethodShouldContainAssertionTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/TestMethodShouldContainAssertion.Custom.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/TestMethodShouldContainAssertion.MsTest.cs
Fixes #3634
Approach similar to S2259 / C#: [RSPEC-3634](https://jira.sonarsource.com/browse/RSPEC-3634)
> S2699: Detect custom method with specific attribute as assertion

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/DoNotCallGCSuppressFinalizeMethod.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/DoNotCallGCSuppressFinalizeTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DoNotCallGCSuppressFinalize.NetCore.cs
> Add repro for #3639

- README.md
related to #3648
I manually checked the links are correct
> Update sonarcloud badges after project rename

- its/projects/ExternalIssues/ExternalIssues.csproj
- its/projects/ExternalIssues/ExternalIssues.sln
- its/projects/ExternalIssues/Program.cs
- its/src/test/java/com/sonar/it/csharp/ExternalIssuesTest.java
- its/src/test/java/com/sonar/it/csharp/Tests.java
To test [Importing Third-Party Issues](https://docs.sonarqube.org/latest/analysis/external-issues/)
> Add integration test with the import of external issues

- pom.xml
- scripts/version/Version.props
- sonar-csharp-plugin/pom.xml
- sonar-dotnet-shared-library/pom.xml
- sonar-vbnet-plugin/pom.xml
- sonaranalyzer-dotnet/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/SonarAnalyzer.CSharp/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/SonarAnalyzer.RuleDocGenerator.CSharp/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/SonarAnalyzer.RuleDocGenerator.VisualBasic/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/SonarAnalyzer.VisualBasic/pom.xml
- sonaranalyzer-dotnet/sonaranalyzer-maven-artifacts/pom.xml
- sonaranalyzer-dotnet/src/AssemblyInfo.Shared.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CFG/SonarAnalyzer.CFG.cs.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/SonarAnalyzer.CSharp.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/SonarAnalyzer.VisualBasic.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/source.extension.vsixmanifest
> Bump version to 8.15

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UnchangedLocalVariablesShouldBeConst.cs
Reproduces #3271 as reported in #3661
> S3353: Add 2nd FP repro for #3271

- .github/workflows/RequestReview.yml
Add GitHub workflow when review is requested:
- Find all linked issues `Fixes #xxxx` or process the PR itself
- Remove assignees
- Assign to the reviewer
- Move card to "Review in progress" column or
- Add card to "Review in progress" column if the PR/Issue is not on Kanban yet
For now, it's based on https://github.com/actions/github-script for simplicity (only single all-in-one YML file). Once it's ready for distribution to LT/SonarSource, we can extract it as a reusable action into a separate repo.
- https://github.com/pavel-mikula-sonarsource/GitHubActionPlayground
- Status and log of an action is visible here: https://github.com/pavel-mikula-sonarsource/GitHubActionPlayground/actions
- It takes around 20 sec to queue the action.
> GitHub workflow: Request review

- scripts/build/dev-build.ps1
to be able to check everything passes before opening a PR
> Run all unit tests from the dev-build script

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/UseUriInsteadOfStringTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/UseValueParameterTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/ValuesUselesslyIncrementedTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/VariableShadowsFieldTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/VariableUnusedTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/VirtualEventFieldTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/XmlExternalEntityShouldNotBeParsedTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UseUriInsteadOfString.CSharp9.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UseValueParameter.CSharp9.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UseValueParameter.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ValuesUselesslyIncremented.CSharp9.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/VariableShadowsField.CSharp9.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/VariableUnused.CSharp9.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/VirtualEventField.CSharp9.Fixed.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/VirtualEventField.CSharp9.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/XmlExternalEntityShouldNotBeParsed_XPathDocument_CSharp9.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/XmlExternalEntityShouldNotBeParsed_XmlDocument_CSharp9.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/XmlExternalEntityShouldNotBeParsed_XmlReader_CSharp9.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/XmlExternalEntityShouldNotBeParsed_XmlTextReader_CSharp9.cs
> Add C# 9 test cases for rules starting with X, V and U

- its/pom.xml
> Bump sonar-orchestrator to 3.31.0.2646
