SonarSource/sonar-dotnet

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/StringFormatValidator.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/StringFormatRuntimeExceptionFreeValidator.cs
> Fix S2275: Rule should not report on multiple ':' in formatting methods

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/InvalidCastToInterface.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/InvalidCastToInterface.cs
This is a port of https://github.com/SonarSource/sonaranalyzer-dotnet/pull/1164
> InvalidCastToInterface: do not raise S1944 when casting to Nullable<T>

- sonaranalyzer-dotnet/its/expected/Nancy/Nancy-{34576216-0DCA-4B0F-A0DC-9075E75A676F}-S3994.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Authentication.Forms-{E8B18958-7C8A-4FBA-AF00-3041C34A20CE}-S3994.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Hosting.Self-{AA7F66EB-EC2C-47DE-855F-30B3E6EF2134}-S3994.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Tests-{776D244D-BC4D-4BBB-A478-CAF2D04520E1}-S3994.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.ViewEngines.Razor-{2C6F51DF-015C-4DB6-B44C-0E5E4F25E2A9}-S3994.json
- sonaranalyzer-dotnet/rspec/cs/S3994_c#.html
- sonaranalyzer-dotnet/rspec/cs/S3994_c#.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.resx
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/UseUriInsteadOfString.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S3994.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S4005.html
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/UseUriInsteadOfString.cs
> Rule S3994: URI Parameters should not be strings

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/StringFormatValidator.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/StringFormatRuntimeExceptionFreeValidator.cs
> Fix S2275: InvalidCastExteption when analyzing single argument method

- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Hosting.Self.Tests-{CA24ED85-DD68-4C10-B80A-D81C6745FCB8}-S4005.json
- sonaranalyzer-dotnet/rspec/cs/S4005_c#.html
- sonaranalyzer-dotnet/rspec/cs/S4005_c#.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.resx
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/UseUriInsteadOfString.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/Rules/UseUriInsteadOfStringTest.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/UseUriInsteadOfStringMethodOverloads.cs
> Rule S4005: "System.Uri" argument should be passed instead of string

- sonaranalyzer-dotnet/rspec/cs/S4002_c#.html
- sonaranalyzer-dotnet/rspec/cs/S4002_c#.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.resx
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/DisposableTypesNeedFinalizers.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S4002.html
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/Rules/DisposableTypesNeedFinalizersTest.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/DisposableTypesNeedFinalizers.cs
> Rule S4002: Disposable types should declare finalizer

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/RedundantInheritanceList.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCasesForRuleFailure/InvalidSyntax.cs
> Fix S1939: Extends and implements list entries should not be redundant

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/BooleanCheckInverted.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/BooleanCheckInverted.Fixed.Batch.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/BooleanCheckInverted.Fixed.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/BooleanCheckInverted.cs
> Fix S1940: "Inverted boolean checks" should not suggest inversion for Nullable<T>

- sonaranalyzer-dotnet/rspec/cs/S3909_c#.html
- sonaranalyzer-dotnet/rspec/cs/S3909_c#.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/CollectionUtils.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.resx
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/CollectionsShouldImplementGenericInterface.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SonarAnalyzer.CSharp.csproj
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S3909.html
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/PackagingTests/RuleTypeTests.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/Rules/CollectionsShouldImplementGenericInterfaceTest.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/CollectionsShouldImplementGenericInterface.cs
> Rule S3909: Collections should implement the generic interface

- sonar-csharp-plugin/src/main/java/org/sonar/plugins/csharp/CSharpCodeCoverageProvider.java
- sonar-csharp-plugin/src/main/java/org/sonar/plugins/csharp/CSharpUnitTestResultsProvider.java
- sonar-csharp-plugin/src/test/java/org/sonar/plugins/csharp/CSharpCodeCoverageProviderTest.java
- sonar-csharp-plugin/src/test/java/org/sonar/plugins/csharp/CSharpUnitTestResultsProviderTest.java
- sonar-dotnet-tests-library/pom.xml
- sonar-dotnet-tests-library/src/main/java/org/sonar/plugins/dotnet/tests/CoverageReportImportSensor.java
- sonar-dotnet-tests-library/src/main/java/org/sonar/plugins/dotnet/tests/UnitTestResultsImportSensor.java
- sonar-dotnet-tests-library/src/test/java/org/sonar/plugins/dotnet/tests/CoverageAggregatorTest.java
- sonar-dotnet-tests-library/src/test/java/org/sonar/plugins/dotnet/tests/CoverageReportImportSensorTest.java
- sonar-dotnet-tests-library/src/test/java/org/sonar/plugins/dotnet/tests/UnitTestResultsAggregatorTest.java
- sonar-dotnet-tests-library/src/test/java/org/sonar/plugins/dotnet/tests/UnitTestResultsImportSensorTest.java
> When working with SQ >= 6.4 sensors are now global

- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/EncodingPerFile.java
- sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/EncodingPerFileTest.java
> Treat Roslyn's UTF-16 equal to SonarQube's UTF-16LE

- sonaranalyzer-dotnet/its/expected/Nancy/Nancy-{34576216-0DCA-4B0F-A0DC-9075E75A676F}-S2328.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Tests-{776D244D-BC4D-4BBB-A478-CAF2D04520E1}-S2328.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka-{5DEDDF90-37F0-48D3-A0B0-A5CBD8A7E377}-S2328.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/KnownMethods.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/GetHashCodeMutable.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/GetHashCodeMutableCodeFixProvider.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/GetHashCodeMutable.Fixed.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/GetHashCodeMutable.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestFramework/IssueLocationCollector.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/Verifier.cs
> Update S2328: "GetHashCode should not reference mutable fields" should report once per method

- sonaranalyzer-dotnet/its/expected/Ember-MM/Ember.Plugins-{9496C697-5AFD-4813-AEDC-AF33FACEADF0}-S3908.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Remote-{EA4FF8FD-7C53-49C8-B9AA-02E458B3E6A7}-S3908.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.TestKit-{0D3CBAD0-BBDB-43E5-AFC4-ED1D3ECDC224}-S3908.json
- sonaranalyzer-dotnet/rspec/cs/S3908_c#.html
- sonaranalyzer-dotnet/rspec/cs/S3908_c#.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.resx
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/DeclareEventHandlersCorrectly.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/UseGenericEventHandlerInstances.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S3908.html
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/PackagingTests/RuleTypeTests.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/Rules/UseGenericEventHandlerInstancesTest.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/UseGenericEventHandlerInstances.cs
> Rule S3908: Generic event handlers should be used

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/SymbolicExecution/InvocationVisitor.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/NullPointerDereference.cs
> Fix Symbolic Execution: Invalid nameof() should be properly handled

- sonar-dotnet-tests-library/src/main/java/org/sonar/plugins/dotnet/tests/UnitTestResults.java
- sonar-dotnet-tests-library/src/main/java/org/sonar/plugins/dotnet/tests/XUnitTestResultsFileParser.java
- sonar-dotnet-tests-library/src/test/java/org/sonar/plugins/dotnet/tests/XUnitTestResultsFileParserTest.java
- sonar-dotnet-tests-library/src/test/resources/xunit/empty.xml
> SonarC# fails when parsing xUnit test results with empty <assembly> tags

- sonar-csharp-plugin/pom.xml
- sonar-dotnet-shared-library/pom.xml
How to:
1. `mvn clean install` <=> `mvn clean install -P local-analyzer -D analyzer.configuration=Release` used by CI but also to test release mode on a Windows machine
2. `mvn clean install -P local-analyzer -D analyzer.configuration=Debug` used to test on a Windows machine
3. `mvn clean install -P download-analyzer -D analyzer.version=6.1.0.2070` with configurable version used to build only the java part (useful on unix machines).
> Provide the ability to download the analyzer instead of compiling it

- sonaranalyzer-dotnet/its/expected/Ember-MM/Ember.Plugins-{9496C697-5AFD-4813-AEDC-AF33FACEADF0}-S2221.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy-{34576216-0DCA-4B0F-A0DC-9075E75A676F}-S2221.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Authentication.Stateless-{211560C3-FDDF-46D6-AB0C-F3BC04B173B5}-S2221.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Demo.CustomModule-{F56F3983-0C34-4AEC-B418-A8AFFA63F1C4}-S2221.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Demo.Hosting.Self-{0B3EA40E-F7D8-4E14-A30F-1536F41B62D1}-S2221.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Encryption.MachineKey-{14A66047-5F67-4774-B0E3-195D1D25B6A5}-S2221.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Hosting.Self-{AA7F66EB-EC2C-47DE-855F-30B3E6EF2134}-S2221.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Metadata.Modules-{DC8AAA8B-7FD0-47C4-9413-3CC94088BCC4}-S2221.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.ViewEngines.DotLiquid-{B795886D-9D70-45B1-BFB5-AD54CBC9A447}-S2221.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.ViewEngines.Spark-{4B7E35DF-1569-4346-B180-A09615723095}-S2221.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka-{5DEDDF90-37F0-48D3-A0B0-A5CBD8A7E377}-S2221.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Cluster-{6AB00F61-269A-4501-B06A-026707F000A7}-S2221.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Persistence-{FCA84DEA-C118-424B-9EB8-34375DFEF18A}-S2221.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Remote-{EA4FF8FD-7C53-49C8-B9AA-02E458B3E6A7}-S2221.json
- sonaranalyzer-dotnet/rspec/cs/S2221_c#.html
- sonaranalyzer-dotnet/rspec/cs/S2221_c#.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.resx
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/DoNotCatchSystemException.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S2221.html
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/PackagingTests/RuleTypeTests.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/Rules/DoNotCatchSystemExceptionTest.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/DoNotCatchSystemException.cs
> Rule S2221: "Exception" should not be caught when not required by called methods

- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Remote.TestKit-{E5957C3E-2B1E-469F-A680-7953B4DEA31B}-S4041.json
- sonaranalyzer-dotnet/rspec/cs/S4041_c#.html
- sonaranalyzer-dotnet/rspec/cs/S4041_c#.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.resx
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/TypeNamesShouldNotMatchNamespaces.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S4041.html
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/PackagingTests/RuleTypeTests.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/Rules/TypeNamesShouldNotMatchNamespacesTest.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/TypeNamesShouldNotMatchNamespaces.cs
> Rule S4041: Type names should not match namespaces

- sonaranalyzer-dotnet/rspec/cs/S2386_c#.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/MutableFieldsShouldNotBe.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/MutableFieldsShouldNotBePublicReadonly.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/MutableFieldsShouldNotBePublicStatic.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S2386.html
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/MutableFieldsShouldNotBePublicReadonly.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/MutableFieldsShouldNotBePublicStatic.cs
> Fix S2386: Do not raise if the readonly field is initialized with a known immutable collection

- sonaranalyzer-dotnet/its/expected/Nancy/Nancy-{34576216-0DCA-4B0F-A0DC-9075E75A676F}-S4060.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Demo.CustomModule-{F56F3983-0C34-4AEC-B418-A8AFFA63F1C4}-S4060.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Demo.Validation-{F417B81C-B914-4BFD-8299-6BBD11072B01}-S4060.json
- sonaranalyzer-dotnet/rspec/cs/S4060_c#.html
- sonaranalyzer-dotnet/rspec/cs/S4060_c#.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.Designer.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.resx
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/AvoidUnsealedAttributes.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/SymbolHelper.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S4060.html
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/PackagingTests/RuleTypeTests.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/Rules/AvoidUnsealedAttributesTest.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/AvoidUnsealedAttributes.cs
> Rule S4060: Non-abstract attributes should be sealed

- sonaranalyzer-dotnet/its/expected/Nancy/Nancy-{34576216-0DCA-4B0F-A0DC-9075E75A676F}-S927.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Authentication.Forms.Tests-{4E974051-38C2-4B5D-A6B1-F265A428A673}-S927.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Demo.Authentication.Forms-{98940A30-1B48-4F71-A6BA-85F0AAF31A2F}-S927.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Demo.Authentication.Stateless-{BAE74CD5-57C2-40E3-8F7A-EDE5721C2ACC}-S927.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Demo.Hosting.Aspnet-{E127FED3-01C0-41BA-BF83-D8DCDD827D6A}-S927.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Hosting.Aspnet-{15B7F794-0BB2-4B66-AD78-4A951F1209B2}-S927.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Testing-{D79203C0-B672-4751-9C95-C3AB7D3FEFBE}-S927.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Testing.Tests-{8EB9E15A-4B65-4C80-B834-9A7773750666}-S927.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Tests-{776D244D-BC4D-4BBB-A478-CAF2D04520E1}-S927.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Validation.DataAnnotations-{701765DC-F4F2-4943-A37F-6ED253198158}-S927.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.ViewEngines.DotLiquid-{B795886D-9D70-45B1-BFB5-AD54CBC9A447}-S927.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka-{5DEDDF90-37F0-48D3-A0B0-A5CBD8A7E377}-S927.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Cluster-{6AB00F61-269A-4501-B06A-026707F000A7}-S927.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Cluster.Tools-{5CF8A8BE-B634-473F-BB01-EBA878746BD4}-S927.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.MultiNodeTestRunner.Shared-{964F0EC5-FBE6-47C5-8AE6-145114D5DB8C}-S927.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.NodeTestRunner-{28520F30-2868-4BD3-9CAE-AC27226C24E3}-S927.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Remote-{EA4FF8FD-7C53-49C8-B9AA-02E458B3E6A7}-S927.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.TestKit-{0D3CBAD0-BBDB-43E5-AFC4-ED1D3ECDC224}-S927.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.TestKit.Tests-{D2BED2D5-B152-48C1-9818-1097BECDDF98}-S927.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Tests-{3F786C7D-70E3-4836-8B33-EC9A5AF72330}-S927.json
- sonaranalyzer-dotnet/its/expected/akka.net/SymbolLookup-{3007A692-A050-4F12-9187-4AE6C6106A66}-S927.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/ParameterNamesInPartialMethod.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/ParameterNamesInPartialMethod.cs
> Update S927: C#: parameter names should match base declaration and other partial definitions

- sonaranalyzer-dotnet/its/expected/Ember-MM/Ember.Plugins-{9496C697-5AFD-4813-AEDC-AF33FACEADF0}-S3956.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy-{34576216-0DCA-4B0F-A0DC-9075E75A676F}-S3956.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Demo.ModelBinding-{1258BFCD-3BAD-4373-B786-4D698EC3C157}-S3956.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Demo.Validation-{F417B81C-B914-4BFD-8299-6BBD11072B01}-S3956.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.ViewEngines.Spark-{4B7E35DF-1569-4346-B180-A09615723095}-S3956.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka-{5DEDDF90-37F0-48D3-A0B0-A5CBD8A7E377}-S3956.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Persistence-{FCA84DEA-C118-424B-9EB8-34375DFEF18A}-S3956.json
- sonaranalyzer-dotnet/its/expected/akka.net/PersistenceExample-{4022147A-4F95-4A04-BE09-01B7952BBDD9}-S3956.json
- sonaranalyzer-dotnet/its/expected/akka.net/Samples.Cluster.Transformation-{E5EB3DF5-D017-4B50-B5AA-2B0440DB773D}-S3956.json
- sonaranalyzer-dotnet/rspec/cs/S3956_c#.html
- sonaranalyzer-dotnet/rspec/cs/S3956_c#.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.Designer.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.resx
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/DoNotExposeListT.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/SymbolHelper.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S3956.html
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/Helpers/SymbolHelperTest.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/PackagingTests/RuleTypeTests.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/Rules/DoNotExposeListTTest.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/DoNotExposeListT.cs
Fix #506 
I'm surprised by how few violations this rule reports. Expected way more.
> Rule S3956: "Generic.List" instances should not be part of public APIs

- sonaranalyzer-dotnet/its/expected/Nancy/Nancy-{34576216-0DCA-4B0F-A0DC-9075E75A676F}-S1200.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Demo.CustomModule-{F56F3983-0C34-4AEC-B418-A8AFFA63F1C4}-S1200.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Hosting.Aspnet-{15B7F794-0BB2-4B66-AD78-4A951F1209B2}-S1200.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Hosting.Self-{AA7F66EB-EC2C-47DE-855F-30B3E6EF2134}-S1200.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.ViewEngines.DotLiquid-{B795886D-9D70-45B1-BFB5-AD54CBC9A447}-S1200.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.ViewEngines.Razor-{2C6F51DF-015C-4DB6-B44C-0E5E4F25E2A9}-S1200.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.ViewEngines.Spark-{4B7E35DF-1569-4346-B180-A09615723095}-S1200.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka-{5DEDDF90-37F0-48D3-A0B0-A5CBD8A7E377}-S1200.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Cluster-{6AB00F61-269A-4501-B06A-026707F000A7}-S1200.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Cluster.Sharding-{A05C31E8-0246-46A1-B3BC-4D6FE7A9AA49}-S1200.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Cluster.Tools-{5CF8A8BE-B634-473F-BB01-EBA878746BD4}-S1200.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Persistence-{FCA84DEA-C118-424B-9EB8-34375DFEF18A}-S1200.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Persistence.Sql.Common-{3B9E6211-9488-4DB5-B714-24248693B38F}-S1200.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Remote-{EA4FF8FD-7C53-49C8-B9AA-02E458B3E6A7}-S1200.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Remote.AkkaIOTransport-{45AAAF15-C5D7-4107-94F0-766A32ECB9AE}-S1200.json
- sonaranalyzer-dotnet/its/expected/akka.net/PingPong-{956F7D26-4505-4A26-86D0-73135BD35A93}-S1200.json
- sonaranalyzer-dotnet/rspec/cs/S1200_c#.html
- sonaranalyzer-dotnet/rspec/cs/S1200_c#.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.resx
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/AvoidExcessiveClassCoupling.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S1200.html
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/PackagingTests/RuleTypeTests.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/Rules/AvoidExcessiveClassCouplingTest.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/AvoidExcessiveClassCoupling.cs
> Rule S1200: Classes should not be coupled to too many other classes

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/ImplementISerializableCorrectly.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/Rules/ImplementISerializableCorrectlyTest.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/ImplementISerializableCorrectly.cs
> Fix S3925: Call to 'base.GetObjectData' is not properly detected

- sonaranalyzer-dotnet/its/expected/Nancy/Nancy-{34576216-0DCA-4B0F-A0DC-9075E75A676F}-S3717.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Authentication.Forms.Tests-{4E974051-38C2-4B5D-A6B1-F265A428A673}-S3717.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Testing.Tests-{8EB9E15A-4B65-4C80-B834-9A7773750666}-S3717.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Tests-{776D244D-BC4D-4BBB-A478-CAF2D04520E1}-S3717.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka-{5DEDDF90-37F0-48D3-A0B0-A5CBD8A7E377}-S3717.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Cluster-{6AB00F61-269A-4501-B06A-026707F000A7}-S3717.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Remote-{EA4FF8FD-7C53-49C8-B9AA-02E458B3E6A7}-S3717.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.TestKit-{0D3CBAD0-BBDB-43E5-AFC4-ED1D3ECDC224}-S3717.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.TestKit.Xunit-{11F4D4B8-7E07-4457-ABF2-609B3E7B2649}-S3717.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.TestKit.Xunit2-{7DBD5C17-5E9D-40C4-9201-D092751532A7}-S3717.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Tests-{3F786C7D-70E3-4836-8B33-EC9A5AF72330}-S3717.json
- sonaranalyzer-dotnet/rspec/cs/S3717_c#.html
- sonaranalyzer-dotnet/rspec/cs/S3717_c#.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.Designer.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.resx
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/TrackNotImplementedException.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S3717.html
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/PackagingTests/RuleTypeTests.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/Rules/TrackNotImplementedExceptionTest.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/TrackNotImplementedException.cs
> Rule S3717: Track use of 'NotImplementedException'

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/StaticFieldInitializerOrder.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/Rules/StaticFieldInitializerOrderTest.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/StaticFieldInitializerOrder.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/StaticFieldInitializerOrder_PartialClass.cs
> Fix S3263: Rule should not raise when constant field is used in initialization

- scripts/utils.ps1
If the executable couldn't be found then the script would fail with an unhelpful error about _where.exe_.
Added a try-catch with a more useful output message.
> Improved error reporting in powershell script

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/DoNotMarkEnumsWithFlags.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/DoNotMarkEnumsWithFlags.cs
A rewrite of the rule to fix #809
> Rule S4070: Use xor operator to verify flags

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/MemberShouldBeStatic.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/MemberShouldBeStatic.cs
> Fix S2325: 'Member should be static' throws NullReferenceException

- sonaranalyzer-dotnet/rspec/cs/S1226_c#.html
- sonaranalyzer-dotnet/rspec/cs/S1226_c#.json
- sonaranalyzer-dotnet/rspec/cs/S1751_c#.json
- sonaranalyzer-dotnet/rspec/cs/S2234_c#.json
- sonaranalyzer-dotnet/rspec/cs/S2681_c#.json
- sonaranalyzer-dotnet/rspec/cs/S3010_c#.json
- sonaranalyzer-dotnet/rspec/cs/S4158_c#.json
- sonaranalyzer-dotnet/rspec/vbnet/S1226_vb.net.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.resx
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S1226_cs.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/RspecStrings.resx
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/PackagingTests/CsRuleTypeMapping.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/PackagingTests/VbRuleTypeMapping.cs
Fix #839, Fix #840, Fix #841, Fix #842, Fix #843, Fix #844
> Update rule types

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Metrics/ExecutableLinesWalker.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/Metrics/ExecutableLinesWalkerTest.cs
Reporting the metric on code marked as not to be tested causes the lines to be marked as not covered, which is not desirable.
> Do not calculate executable line metrics for code excluded from coverage

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SymbolicExecution/ControlFlowGraph/CSharpControlFlowGraphBuilder.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SymbolicExecution/InvocationVisitor.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/NullPointerDereference.cs
> Fix S2259: Rule should not fire on nameof(a.P) when a is null

- its/projects/UnitTestResultsTest/reports/vstest.trx
- its/src/test/java/com/sonar/it/csharp/UnitTestResultsTest.java
- sonar-dotnet-tests-library/src/main/java/org/sonar/plugins/dotnet/tests/NUnitTestResultsFileParser.java
- sonar-dotnet-tests-library/src/main/java/org/sonar/plugins/dotnet/tests/VisualStudioTestResultsFileParser.java
- sonar-dotnet-tests-library/src/main/java/org/sonar/plugins/dotnet/tests/XUnitTestResultsFileParser.java
- sonar-dotnet-tests-library/src/test/java/org/sonar/plugins/dotnet/tests/NUnitTestResultsFileParserTest.java
- sonar-dotnet-tests-library/src/test/java/org/sonar/plugins/dotnet/tests/VisualStudioTestResultsFileParserTest.java
- sonar-dotnet-tests-library/src/test/java/org/sonar/plugins/dotnet/tests/XUnitTestResultsFileParserTest.java
- sonar-dotnet-tests-library/src/test/resources/visualstudio_test_results/valid.trx
> Update SonarC#: Unit Tests total and skipped numbers are not consistent

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/TestClassShouldHaveTestMethod.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/TestClassShouldHaveTestMethod.cs
#1010 
add DataTestMethod to recognized test method attributes
> SONAR-1010 TestClassShouldHaveTestMethod recognizes [DataTestMethod]

- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/Rules/CheckFileLicenseTest.cs
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/SonarAnalyzer.UnitTest.csproj
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/app.classic.config
- sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/packages.SonarAnalyzer.UnitTest.config
Starting with 2.3.0 all code fixes rules are now failing with a `NullReferenceException`. We will still need to find a way to fix that so we can have tests running with latest. But in the meantime we can already start using 2.2 and some C# 7 features (like tuples).
> Update unit tests to use roslyn 2.2

- sonaranalyzer-dotnet/rspec/cs/S4212_c#.html
- sonaranalyzer-dotnet/rspec/cs/S4212_c#.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.resx
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/SerializationConstructorsShouldBeSecured.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S4212.html
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/PackagingTests/CsRuleTypeMapping.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/SerializationConstructorsShouldBeSecuredTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/SerializationConstructorsShouldBeSecured.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/SerializationConstructorsShouldBeSecured_NoAssemblyAttribute.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/SerializationConstructorsShouldBeSecured_Part1.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/SerializationConstructorsShouldBeSecured_Part2.cs
> Rule S4212: Serialization constructors should be secured

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/EventHandlerDelegateShouldHaveProperArguments.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/EventHandlerDelegateShouldHaveProperArguments.cs
Hi,
We encountered a StackOverflow in one of our projects during the build when using the sonar c# analyser.
After a divide and conquer strategy, I was able to isolate the code and deduce the faulty rule.
It's a very specific combination of criteria :
- An encapsuled EventHandler without event keyword
- A nested conditionnal access and invoke of the handler
In this case the method GetEventSymbol get called in infinite loop.
Here, the reproduction case and the fix.
There may be better way to handle this case, I don't know well the roselyn api.
> Fix S4220 : Rule should not throw StackOverflowException

- sonaranalyzer-dotnet/its/SingleRule.ruleset.template
This speeds up its for a single rule by 10s
> Allow metadata computing metrics to be ignored during its

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/RedundantConditionalAroundAssignment.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/RedundantConditionalAroundAssignment.Fixed.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/RedundantConditionalAroundAssignment.cs
> Update S3440: 'Variables should not be checked before assignment' should not raise on properties

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/ImplementISerializableCorrectly.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ImplementISerializableCorrectly.cs
Fix #1076 
Not perfect solution, but to make it right I have to rewrite half of the rule. Basically disabled the check for public/virtual GetObjectData on explicitly implemented interfaces. There is no check if the explicit implementation calls the virtual method, or if there is a virtual method at all.
> Fix S3925: Should not raise on explicit implementation of ISerializable

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/DoNotDecreaseMemberVisibility.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DoNotDecreaseMemberVisibility.cs
> Fix S4015: Incorrectly Identifies Descendent Overload as Member Hiding

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/UninvokedEventDeclaration.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UninvokedEventDeclaration.cs
Removed the check for EventDeclarationSyntax as it cannot be invoked. One can only invoke EventFieldDeclarationSyntax but checking whether the event declaration is using the _correct_ field is a different rule IMO. S3237 will report if the value of the accessor is not used (e.g. if you don't assign an event field).
Refactored the implementation a bit to make it more functional and somewhat easier to understand.
Fix #1219 
Fix #1123
> Fix S3264: FP when using add/remove syntax

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/RedundantJumpStatement.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SymbolicExecution/CSharpExplodedGraph.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SymbolicExecution/ControlFlowGraph/CSharpControlFlowGraphBuilder.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Helpers/FlowAnalysis/ControlFlowGraphTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/RedundantJumpStatement.cs
Related to #1295 but does not fully implement it.
The `yield return` statements used to generate s `SimpleBlock` in CFG. Now a `JumpBlock` is generated, which "jumps" to the next statement. The `JumpBlock` allows us to do additional processing for `yield return` statements, such as to delete the constraints from class fields.
> Adding support for 'yield return' in CFG

- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/DiagnosticDescriptorBuilder.cs
> SonarWayTag, MainSourcesScopeTag and TestSourcesScopeTag are now public

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/ParameterValidationInMethodShouldBeWrapped.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ParameterValidationInAsyncShouldBeWrapped.cs
> Fix a NRE with parameter validation in async methods

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/NonAsyncTaskShouldNotReturnNull.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/NonAsyncTaskShouldNotReturnNull.cs
Fix #1436 
I decided to ignore all return null from within a lambda but we could have looked for some specific invocations instead. This choice is motivated by having a fast fix which would only result in some FN but should cover more FPs.
> Fix S4586: False positive when returning null from inside Task.Run

- its/pom.xml
- its/src/test/java/com/sonar/it/csharp/UCFGDeserializationTest.java
Fix compatibility of integration tests with SQ 7.2
(same changes as https://github.com/SonarSource/sonar-csharp/pull/1471, but rebased)
> Upgrade Orchestrator to 3.19

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/BlockIdMap.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/CfgSerializer.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/DotWriter.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/UcfgSerializer.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/UcfgGenerator.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Security/Ucfg/UniversalControlFlowGraphBuilder.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Helpers/BlockIdMapTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Helpers/CfgSerializerTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Helpers/DotWriterTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Helpers/FluentTestHelper.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Helpers/UcfgSerializerTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/UcfgGeneratorTest.cs
To enable set the following env var `SONARANALYZER_GENERATE_DOT` to `TRUE` (should be case insensitive).
Both `Visitor` classes are not exactly following the visitor pattern; I did not wanted to modify many existing classes and did simpler implementation. If we do a proper `Visitor` implementation it would be of help for the UCFG generation too.
> Adding conditional UCFG to DOT serialization

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SymbolicExecution/CSharpExplodedGraph.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SymbolicExecution/ControlFlowGraph/CSharpControlFlowGraphBuilder.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Helpers/FlowAnalysis/ControlFlowGraphTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/NullPointerDereference.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/NullPointerDereferenceCSharp6.cs
Fix #1324 
We were not adding the exception filters to the CFG, hence the code was evaluated as unconditional and some false positives were generated. I added `BinaryBranchBlock` to the CFG for each exception filter, connecting the catch block and the finally/after-try block. I had to add support for `CatchFilterSyntax` in the `CSharpExplodedGraph` too.
> Rule S2259: False positive on 'try/catch' with exception filter

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/HardcodedIpAddress.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/HardcodedIpAddress.cs
Fix #1540 
- Adds exception for 127.0.0.1
- Changes compliant IP address example since the original test was actually for the address the exception is being added for!
> Rule S1313: do not report issue for loopback address (#1540)

- its/src/test/java/com/sonar/it/csharp/UCFGDeserializationTest.java
This PR should make the QA test fail in the future if any UCFG generation error occurs on the C# side.
> QA: UCFG test should fail if is any Roslyn analyzer error

- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Remote-{EA4FF8FD-7C53-49C8-B9AA-02E458B3E6A7}-S3242.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/MethodsShouldUseBaseTypes.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/MethodsShouldUseBaseTypes.cs
> Fix S3242: Rule should not suggest base type for virtual methods

- its/src/test/java/com/sonar/it/csharp/Tests.java
Environment vars should not have whitespace in name.
> Remove whitespace from MSBUILD_PATH string

- scripts/rspec/rspec.ps1
- sonar-csharp-plugin/pom.xml
- sonar-csharp-plugin/src/test/java/org/sonar/plugins/csharp/CSharpSonarRulesDefinitionTest.java
- sonar-csharp-plugin/src/test/java/org/sonar/plugins/csharp/SonarVersion.java
- sonar-dotnet-shared-library/pom.xml
- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/AbstractRulesDefinition.java
- sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/AbstractRulesDefinitionTest.java
- sonaranalyzer-dotnet/rspec/cs/S1313_c#.json
- sonaranalyzer-dotnet/rspec/cs/S2092_c#.json
- sonaranalyzer-dotnet/rspec/cs/S2245_c#.json
- sonaranalyzer-dotnet/rspec/cs/S2255_c#.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.resx
Fix #1562 and fix #1588 
- to ensure backwards compatibility, the rules.xml is kept the same
- after deserializing the rules.xml at runtime, the json files are used to set the rule type and the security-specific metadata
>  Support SECURITY_HOTSPOT rules and populate Security Standards data for Security Hotspots and Vulnerabilities rules

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/TestClassShouldHaveTestMethod.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/TestClassShouldHaveTestMethod.MsTest.cs
> Fixed #1486 - exception for classes that contain assembly-level setup/cleanup methods

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/NuGetMetadataReference.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestFramework/TestResultHelper.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestFramework/TestResultHelperTests/TestResultHelper_Tests.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestResultHelper.cs
There are a few limitations of this approach:
- if a new nuget is added to the helper everyone will have to delete his TestResults folder. This should not happen very often though.
- not sure about the period, perhaps 7 days is a bit long, but in general should be ok because our release cycle is longer and we should be able to include a quick fix in the current release.
> Attempt to improve performance of locally run tests

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/MethodsShouldUseBaseTypes.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Common/AnalyzerLanguage.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Helpers/DiagnosticAnalyzerContextHelperTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Helpers/SonarAnalysisContextTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Helpers/SymbolHelperTest.IsExtensionOn.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Helpers/SymbolHelperTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Helpers/TestHelper.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/MethodsShouldUseBaseTypesTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestFramework/CodeFixVerifier.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestFramework/DiagnosticVerifier.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestFramework/NewVerifier.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestFramework/ParseOptionsHelper.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestFramework/ProjectBuilder.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestFramework/SolutionBuilder.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Verifier.cs
+ Creating NewVerifier in an attempt to replace the existing Verifier with more modular framework. NOTE: this is work in progress and some of the code in Verifier will be replaced with calls to the new classes.
Fix #1610
> [DO NOT SQUASH] Fix S3242: Rule should not suggest base type resulting in inconsistent accessibility

- its/pom.xml
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/TestMethodShouldNotBeIgnored.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/TestMethodShouldNotBeIgnoredTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/TestMethodShouldNotBeIgnored.MsTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/TestMethodShouldNotBeIgnored.NUnit.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/TestMethodShouldNotBeIgnored.Xunit.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/TestMethodShouldNotBeIgnored.Xunit.v1.cs
Fixed #1705 
* add support for NUnit _Theory_ and MSTest _DataTestMethod_ tests
* exclude xUnit from rule to remove FPs
> Fix #1705: support recognized test attributes

- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Demo.Hosting.Aspnet-{E127FED3-01C0-41BA-BF83-D8DCDD827D6A}-S2148.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.Tests-{776D244D-BC4D-4BBB-A478-CAF2D04520E1}-S2148.json
- sonaranalyzer-dotnet/its/expected/Nancy/Nancy.ViewEngines.Spark.Tests-{06F89662-C2F0-4C1D-8581-E0C4A615B7E2}-S2148.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Remote-{EA4FF8FD-7C53-49C8-B9AA-02E458B3E6A7}-S2148.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Remote.Tests-{95E921AB-1F5A-4AF9-B7FE-284E317A97F4}-S2148.json
- sonaranalyzer-dotnet/its/expected/akka.net/Akka.Tests.Performance-{B17DEDCB-D2AA-472D-82A0-D242B711F488}-S2148.json
- sonaranalyzer-dotnet/rspec/cs/S2148_c#.html
- sonaranalyzer-dotnet/rspec/cs/S2148_c#.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.resx
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/UseNumericLiteralSeparator.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S2148.html
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/PackagingTests/CsRuleTypeMapping.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/UseNumericLiteralSeparatorTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UseNumericLiteralSeparator.cs
> Rule S2148: Underscores should be used to make large numbers readable

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/ControlFlowGraph/CSharpControlFlowGraphBuilder.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/ForeachLoopExplicitConversionCodeFixProvider.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/ResourceTests/GeneratedResourcesTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/CommentedOutCodeTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/ConditionEvaluatesToConstantTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/DoNotMarkEnumsWithFlagsTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/ForeachLoopExplicitConversionTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/MethodParameterUnusedTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/NameOfShouldBeUsedTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/NullPointerDereferenceTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/NumberPatternShouldBeRegularTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/PropertyToAutoPropertyTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/StringFormatValidatorTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/UnusedPrivateMemberTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/UseCurlyBracesTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/UseNumericLiteralSeparatorTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/SonarAnalyzer.UnitTest.csproj
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DoNotMarkEnumsWithFlags.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ForeachLoopExplicitConversion.Fixed.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/InitializeStaticFieldsInline.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/MethodParameterUnused.CSharp7.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/MethodParameterUnused.Fixed.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestFramework/CodeFixVerifier.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestFramework/ParseOptionsHelper.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Verifier.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/app.config
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/packages.SonarAnalyzer.UnitTest.config
`ForeachLoopExplicitConversion_CodeFix` doesn't work but even when forcing the C# version to an older version it doesn't work.
Could you test on your machine if the code fix passes?
> Update the version of Roslyn the tests depends upon

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/CheckFileLicenseTest.cs
Use wildcards to check only the part of the message that remains in English even on a French Visual Studio.
>  Correct a unit test that was failing on a French Visual studio

- sonaranalyzer-dotnet/src/Directory.Build.props
Recent commit added a lower-level Directory-Build.props file that prevented the existing Directory.Build.props file from being imported -> $(DebugSymbols) property not set -> no code coverage -> QG failed
> Fix QG build issue

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/CSharpSyntaxHelper.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/StringOperationWithoutCulture.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/RedundantArgument.Named.Fixed.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/RedundantArgument.NoNamed.Fixed.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/RedundantArgument.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/StringOperationWithoutCulture.cs
~~No change in behaviour, the unit test was already working :)~~
Sorry, I was wrong about that... Here is a proper correction.
Related to community thread:
https://community.sonarsource.com/t/c-rule-culture-should-be-specified-for-string-operations/2364
closes #1841 
closes #1994
> Fix S1449: Do not raise issues inside of an Expression

- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/AbstractConfiguration.java
> Remove double negative in log warning for missing Roslyn issues report

- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/SarifParserCallbackImpl.java
- sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/sarif/SarifParserCallbackImplTest.java
> Do not report Security Hotspots as external rules when analyzing PRs and short-living branches

- its/projects/MetricsTest/bar/Class1.cs
- its/projects/MetricsTest/foo/Class1.cs
- its/projects/MetricsTest/foo/Class1_copy.cs
- its/projects/VbMetricsTest/bar/Module1.vb
- its/projects/VbMetricsTest/foo/Module1.vb
- its/projects/VbMetricsTest/foo/Module1_copy.vb
- its/src/test/java/com/sonar/it/csharp/MetricsTest.java
- its/src/test/java/com/sonar/it/vbnet/MetricsTest.java
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Metrics/CSharpPublicApiMetric.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Metrics/Metrics.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Metrics/MetricsBase.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Metrics/Metrics.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Metrics/VisualBasicPublicApiMetric.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Common/MetricsTest.cs
> Undocumented public API metric should count only documentation comments

- sonaranalyzer-dotnet/its/expected/Automapper/AutoMapper-025B9F93-7953-454B-AF29-E6A55B2AA58F-S1200.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/AvoidExcessiveClassCoupling.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/AvoidExcessiveClassCouplingTest.cs
> Update S1200: Rule should ignore 'nameof()' references

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/UnusedPrivateMember.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/UnusedPrivateMemberTest.cs
Fix #2203, Fix #2154  
I did not go with the additional optimizations because reporting for property accessors would become much more difficult.
> Fix S1144: Do not keep references to all type symbols

- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/SonarAnalyzer.CSharp.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/SonarAnalyzer.VisualBasic.nuspec
When trying to publish the NuGet package to nuget.org there was a warning to tell us we are using a deprecated element.
> NuGet packages should stop using deprecated licenseUrl tag

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/UnusedPrivateMemberTest.Constructors.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/UnusedPrivateMemberTest.Fields.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/UnusedPrivateMemberTest.Methods.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/UnusedPrivateMemberTest.Properties.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/UnusedPrivateMemberTest.Types.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/UnusedPrivateMemberTest.cs
Also prepend all test methods with `UnusedPrivateMember_` to be easy to filter the 25 tests inside the IDE
> Refactor: Split UnusedPrivateMemberTest in multiple files

- sonaranalyzer-dotnet/src/Rspec2Resx.targets
I don't understand why this is necessary.
It's also breaking my local env
> Remove PS Unrestricted requirement from Rspec2Resx.targets

- scripts/build/build-utils.ps1
The scripts are currently hard-coded in a couple of places to use MSBuild15. However, the vswhere was configured to search for "latest", causing a failure on a machine that also has VS2019 installed.
> Fix IT build scripts to run on a machine with VS2017 and VS2019

- sonaranalyzer-dotnet/rspec/cs/S1905_c#.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/RedundantCast.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S1905.html
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/RedundantCastTest.cs
> Update S1905: False Positive with 'default'

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/EmptyCollectionsShouldNotBeEnumerated.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/EmptyCollectionsShouldNotBeEnumeratedTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/EmptyCollectionsShouldNotBeEnumerated.cs
> Fix S4158: Rule should consider .NetCore 2.0+ 'Dictionary.TryAdd' method

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/StringFormatValidator.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/StringFormatValidatorTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/StringFormatEdgeCasesValidator.cs
> Fix StringFormatValidator NRE due to array instantiation w/o initializer

- its/projects/MetricsTest/foo/Class1.cs
- its/src/test/java/com/sonar/it/csharp/MetricsIncludeHeaderCommentTest.java
- its/src/test/java/com/sonar/it/csharp/MetricsTest.java
- its/src/test/java/com/sonar/it/shared/TestUtils.java
This is quite hard to test inside the C# analyzer, as the `SonarLint.xml` file is passed as _Additional file_ to roslyn by S4MSB, which is quite hard to mock.
> Add integration test for counting header comments

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/BooleanCheckInverted.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Rules/BooleanCheckInverted.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/BooleanCheckInverted.Fixed.Batch.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/BooleanCheckInverted.Fixed.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/BooleanCheckInverted.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/BooleanCheckInverted.vb
Fixes #2427.
Note that failure on SonarCloud is due to duplicated code. However, it is not possible to easily simplify that part, as both CSharp and VisualBasic analyzers use different objects for `SyntaxKind`
> S1940: FP with null-conditional operator

- scripts/build/ci-build.ps1
In other projects that use the Jenkinsfile, the following are common args
```
def commonArgs = "-Dsonar.host.url=$SONAR_HOST_URL \
-Dsonar.login=$SONAR_TOKEN \
-Dsonar.analysis.buildNumber=$BUILD_NUMBER \
-Dsonar.analysis.pipeline=$BUILD_NUMBER \
-Dsonar.analysis.sha1=$GIT_SHA1  \
-Dsonar.analysis.repository=$GITHUB_REPO \
-B -e -V "
```
> Add missing MVN arguments to PR and main build

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/MLIRExporter.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/MlirExportTest.cs
Poisonous construct are constructs that have an impact on the CFG and make it invalid until we write specific code to handle them.
> Ignore functions that contain a poisonous construct

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/MLIRExporter.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/MlirExportTest.cs
The function call is modeled as `unknown`. Doing anything more elaborate is useless until we are cross functions.
> Make the MLIR valid when a function call is present

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/MLIRExporter.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/MlirExportTest.cs
Create dummy unique SSA name for unnamed parameters in entry block params
Ignore unnamed parameters in the entry block body
> Handle functions with unnamed parameters

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/ControlFlowGraph/CSharpControlFlowGraphBuilder.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SymbolicExecution/CSharpExplodedGraph.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/ControlFlowGraph/ControlFlowGraphTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/EmptyNullableValueAccess.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/NullPointerDereference.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ObjectsShouldNotBeDisposedMoreThanOnce.cs
Note: this was making many rules fail: NullPointerDereference, ObjectsShouldNotBeDisposedMoreThanOnce, EmptyNullableValueAccess, ConditionEvaluatesToConstant, InvalidCastToInterface, EmptyCollectionsShouldNotBeEnumerated
I have added just some partial UTs that go over the exploded graph
> Fix regression (Symbolic Execution exception which breaks cirrus QA) introduced in #2511

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/MLIRExporter.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/PreservingEncodingFallback.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/MlirExportTest.cs
MLIR is pretty restrictive in term of names it accepts. So converting non-compatible character into compatible ones with a bijection that preserves name readability in case of simple names
> Handle names not encodable in ASCII

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/MLIRExporter.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/MlirExportTest.cs
The basic mangling is provided by Roslyn, then cleaned-up from characters not acceptable for a MLIR function name.
> Use a mangling instead of a name to support overloaded functions

- scripts/rspec/rspec2resx.ps1
This change is not enough to run ITs on such a machine.
> Allow building on a machine where only VS2019 has been installed

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/DownloadCBDE.targets
Make sure that even when a very light build is done (for instance, from the IDE), the executable files from CBDE are registered as "content" in the SonarAnalyzer.CSharp.csproj project. In order to do that, we add them twice:
- Once statically, when they are already here, this addition is always executed
- Once dynamically, when they are just downloaded, this addition may be skipped if the solution is pretty much up-to-date
Then add those file with a more classical path relative to the project.
> Make cbde binaries available in unit tests

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/TestMethodShouldContainAssertion.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/UnitTestHelper.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/TestMethodShouldContainAssertionTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/TestMethodShouldContainAssertion.NUnit.cs
Also upgrade UT to run with NUnit 3.11 as baseline
Fix  #2451
> Fix S2699 FP: NUnit 3.0 TestCase + ExpectedResult

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/TestMethodShouldContainAssertion.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/NuGetMetadataReference.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/TestMethodShouldContainAssertionTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/TestMethodShouldContainAssertion.MsTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/TestMethodShouldContainAssertion.NUnit.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/TestMethodShouldContainAssertion.Xunit.cs
The checks for the NSubstitute assertions are done using the actual method symbol instead of searching for keywords like it's done for the other assertions. This allows for more granular and precise matching.
Fixes #2709
> Update S2699: to support NSubstitute 4.2.1

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/TestMethodShouldContainAssertionTest.cs
not only with the latest version.
Issue: #2714
> Run tests with FluentAssertions 5

- sonar-csharp-plugin/pom.xml
- sonar-csharp-plugin/src/test/java/org/sonar/plugins/csharp/CSharpPluginTest.java
- sonar-csharp-plugin/src/test/java/org/sonar/plugins/csharp/CSharpTest.java
- sonar-csharp-plugin/src/test/java/org/sonar/plugins/csharp/SonarVersion.java
- sonar-dotnet-shared-library/pom.xml
- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/CodeCoverageProvider.java
- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/PropertiesSensor.java
- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/RoslynReport.java
- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/SarifParserCallbackImpl.java
- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/UnitTestResultsProvider.java
- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/sarif/SarifParser01And04.java
- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/sarif/SarifParser10.java
- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/sarif/SarifParserCallback.java
- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/sarif/SarifParserFactory.java
- sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/AbstractProjectConfigurationTest.java
- sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/AbstractSolutionConfigurationTest.java
- sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/GeneratedFileFilterTest.java
- sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/RoslynDataImporterTest.java
- sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/sarif/SarifParser01And04Test.java
- sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/sarif/SarifParserCallbackImplTest.java
- sonar-vbnet-plugin/pom.xml
- sonar-vbnet-plugin/src/test/java/org/sonar/plugins/vbnet/SonarVersion.java
- sonar-vbnet-plugin/src/test/java/org/sonar/plugins/vbnet/VbNetPluginTest.java
- sonar-vbnet-plugin/src/test/java/org/sonar/plugins/vbnet/VbNetTest.java
- update vbnet, csharp and shared plugins to sonar-plugin-api to 7.9
- use InputProject instead of InputModule
- replace Qualifiers.MODULE with PROJECT
The following warnings for deprecated APIs are remaining:
```
java: org.sonar.api.batch.ScannerSide in org.sonar.api.batch has been deprecated
java: global() in org.sonar.api.batch.sensor.SensorDescriptor has been deprecated
java: module() in org.sonar.api.batch.sensor.SensorContext has been deprecated
java: org.sonar.api.batch.bootstrap.ProjectBuilder in org.sonar.api.batch.bootstrap has been deprecated
java: org.sonar.api.batch.bootstrap.ProjectDefinition in org.sonar.api.batch.bootstrap has been deprecated
java: org.sonar.api.batch.bootstrap.ProjectBuilder.Context in org.sonar.api.batch.bootstrap.ProjectBuilder has been deprecated
java: …
```
> Update sonar-plugin-api to 7.9

- docs/contributing-analyzer.md
to include possibility to install only the VS 2017 Build Tools
This won't be relevant anymore after #2489 gets fixed...
> Update analyzer README

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/UnnecessaryUsings.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UnnecessaryUsings.Fixed.Batch.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UnnecessaryUsings.Fixed.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UnnecessaryUsings.cs
> Fix S1128 FP: using System.Linq query syntax missing cases

- .gitignore
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/DownloadCBDE.targets
Refactor the code of DownloadCBDE.targets because I could not see how to make CallTarget work with batched targets, and having a batched target to download CBDE for each OS seemed a nice thing.
> Add linux executable of CBDE to the DotNet plugin

- its/pom.xml
Fixes #2617
Use of deprecated methods was already removed in PR #2486
This version update is just a formality, as the removed API were already not used anymore by our codebase
> Update orchestrator to 3.27.0.2172

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/CSharpSyntaxHelper.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/ArrayCovariance.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/EncryptionAlgorithmsShouldBeSecure.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/InvocationResolvesToOverrideWithParams.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/LossOfFractionInDivision.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/RedundantToStringCall.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SyntaxTrackers/CSharpInvocationTracker.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SyntaxTrackers/CSharpObjectCreationTracker.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/AbstractMethodParameterLookup.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Rules/CertificateValidationCheckBase.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Helpers/VisualBasicSyntaxHelper.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Rules/EncryptionAlgorithmsShouldBeSecure.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/SyntaxTrackers/VisualBasicInvocationTracker.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/SyntaxTrackers/VisualBasicObjectCreationTracker.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Helpers/MethodParameterLookupTest.cs
> Fix AbstractMethodParameterLookup.TryGetArgumentSyntax to handle param/ParamArray properly

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/CBDE/MLIRExporter.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/CBDE/MlirExportTest.cs
This is a special case in C# language specification, the number is an uint32, and minus this number is an int32 (and not a int64, like for -10u). But the patch handle all cases where the output of neg is known while the input is unknown.
> Correct code generation for -2147483648

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/UsingCookiesTest.cs
Set version to 2.2.0 instead of 3.0 as the "Microsoft.AspNetCore.Http.Abstractions" package only exists up to 2.2.0 version of netcore
> Set version of netcore packages for UsingCookiesTest to 2.2.0

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/EmptyNullableValueAccess.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/EmptyNullableValueAccessTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/EmptyNullableValueAccess.cs
> Rule S3655: Update SE to the new CFG and add C# 8 unit tests EmptyNullableValueAccess

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/CBDE/CbdeHandler.cs
- Add the stack trace in the message
- Workaround Roslyn cutting message at first newline
Related to #2922 
Please note that due to #2773, this PR introduced new issues (false positives) in the code base.
> Better exception messages for CBDE

- scripts/build/build-utils.ps1
Upgrading UnitTest project to net48 target changed the output direcotry of the build.
Script `.\scripts\build\dev-build.ps1 -restore -build -test` expected `net46` directory that didn't exists in clean solution.
> Update build-utils.ps1 for net48 for UnitTests

- sonaranalyzer-dotnet/.sonarlint/SonarAnalyzer.slconfig
- sonaranalyzer-dotnet/.sonarlint/sonaranalyzer-dotnetCSharp.ruleset
- sonaranalyzer-dotnet/src/SonarAnalyzer.CFG/SonarAnalyzer.CFG.csproj
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SonarAnalyzer.CSharp.csproj
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/SonarAnalyzer.Common.csproj
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/SonarAnalyzer.Utilities.csproj
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/SonarAnalyzer.VisualBasic.csproj
- sonaranalyzer-dotnet/tests/CBDE/CBDEArguments/CBDEArguments.csproj
- sonaranalyzer-dotnet/tests/CBDE/CBDEFails/CBDEFails.csproj
- sonaranalyzer-dotnet/tests/CBDE/CBDESucceedsWithIncorrectResults/CBDESucceedsWithIncorrectResults.csproj
- sonaranalyzer-dotnet/tests/CBDE/CBDEWaitAndSucceeds/CBDEWaitAndSucceeds.csproj
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/SonarAnalyzer.UnitTest.csproj
Related to #3007 
This contains changes:
- autogenerated files from binding SonarLint to SonarCloud (we have new rules in SonarWay since the last update in May 2019)
- fixing the path to the local SonarLint.xml
I tested the usage of SonarLint.xml in projects with a local SQ instance with S1451 enables in the QP. It works 😄
> Update sonarlint metafiles; fix path to SonarLint.xml in csproj files

- scripts/rspec/rspec2resx.ps1
Address first two points of #3008
AzureDevOps build image environment changed and original version is not working anymore.
> Update rspec2resx for .NET 4.8 SDK

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SymbolicExecution/CSharp/CSharpExplodedGraph.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/SymbolicExecution/ExplodedGraphTests.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ConditionEvaluatesToConstant.CSharp8.cs
Previously, handling of coalesce assignments on object properties 
was resulting in an error.
e.g. `obj.Property ??= 1`
> Improve handling for CoalesceAssignments

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/CbdeHandlerRule.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SonarAnalyzer.CSharp.csproj
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/packages.lock.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.RuleDescriptorGenerator/packages.lock.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/packages.lock.json
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/packages.lock.json
- RuntimeInformation.IsOSPlatform is only supported starting with
.NET Framework 4.7.1 and failed on Visual Studio 2015
- Environment.OSVersion is supported starting with .Net Framework 1.1
and .Net Core 2.0
Fixes #3048
> Use Environment.OSVersion to verify the OS type

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/DeadStores.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DeadStores.cs
Since the tuples are not yet fully supported by both CFG and symbolic
execution (#2933), **S1854** will ignore the methods which are containing them.
Fixes #3094
> Avoid false positives while handling tuples

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/DownloadCBDE.targets
This is to allow the next sonar-dotnet release. More change will come when
the cbde release becomes automatized.
>   Download the cbde artifacts from release instead of from builds.

- sonaranalyzer-dotnet/rspec/cs/S5042_c#.html
- sonaranalyzer-dotnet/rspec/cs/S5542_c#.html
- sonaranalyzer-dotnet/rspec/vbnet/S5042_vb.net.html
- sonaranalyzer-dotnet/rspec/vbnet/S5542_vb.net.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/sonarpedia.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S5042_cs.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S5042_vb.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S5542_cs.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S5542_vb.html
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/sonarpedia.json
Intentionally ignore the update to S4426 (must be done in #3097, together with the update of the implementation)
Fixes #3091
> Update RSPECs before the release of 8.4

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/CSharpSymbolUsageCollector.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/UnusedPrivateMemberTest.Constructors.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/UnusedPrivateMemberTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UnusedPrivateMember.CSharp8.cs
> UnusedPrivateMember throws 'NullReferenceException' in SonarLint

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/GenericTypeParameterUnused.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/GenericTypeParameterUnusedTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/GenericTypeParameterUnused.Partial.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/GenericTypeParameterUnused.cs
- use structs
- filter the identifiers by name before asking for SymbolInfo
This reduces GenericTypeParameterUnused rule execution time
(using AnalyzerTool) for Entity Framework Core project from
~1315636ms to ~4531ms.
> Performance improvement for GenericTypeParameterUnused

- scripts/rspec/rspec-templates/CSharpTestTemplate.cs
- scripts/rspec/rspec-templates/VbNetTestTemplate.cs
Update templates for `rspec.ps1` after #3127 refactored `Verifier.cs` into `TestFramework` namespace.
> Update RSPEC test class templates

- sonaranalyzer-dotnet/its/expected/Ember-MM/Ember Media Manager-{9B57D3AB-AF12-4012-B945-284C2448DC81}-S1075.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CFG/Helpers/StringExtensions.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/StringExtensions.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Helpers/StringExtensionsTest.cs
Strings like `HTML`  or `PEHeader` were handled per upper case letter and splitted into `h, t, m, l` or `p, e, header`.
This causes some problems with upper-case only names like `PASSWORD` or `URL`.
New implementation is aware of upper case sequences and can handle situations like `ThisIsSMTPName` to `this, is, smtp, name`
> SplitCamelCaseToWords handles UPPERCASE sequences

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/PropertiesAccessCorrectField.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/PropertiesAccessCorrectField.cs
C# auto-implemented readonly property with [DebuggerStepThrought] attribute was throwing NRE in SingleReturn function.
> Fix S4275 Bug: C# auto-implemented readonly property with attr..

- docs/contributing-analyzer.md
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/SonarAnalyzer.Common.csproj
Fixes #3032
cherry-pick #3217 to run CI
> The short version is that you can not rely on $(NUGET_PACKAGES) to be configured, but you can on $(NugetPackageRoot) . By changing this (for building with ProtoBuf) i could compile (again) locally.
> 
> See: NuGet/Home#6301 (comment)
> Use $(NugetPackageRoot) instead of $(NUGET_PACKAGES)

- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Rules/CheckFileLicenseBase.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/CheckFileLicenseTest.cs
The configuration for S1451 supports regular expression.
I tried to configure the rule using a [popular example](https://stackoverflow.com/questions/31462870/sonarqube-rules-squids1451-copyright-and-license-headers-should-be-defined).
I was wondering why it does not work, at least not in the local analysis using roslyn analzers (SonarAnalyzer.CSharp 8.4.0.15306).
I think, it should be a compatible change to use the option `RegexOptions.Singleline`.
Then the newline character is matched by "dot".
There no separate issue so far. Is it required?
Fixes #3224
> fix S1451 FP if regex expression tries to match newline using "."

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/TrackNotImplementedException.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/TrackNotImplementedException.cs
Fixes #2503 
Due to the use of an old version of Microsoft.CodeAnalysis.Charp 1.3.2 (backwards compatebility I asume), it was a bit less straight forward.
> Fix FP on S3717 with throw expressions

- sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/BranchPoint.java
- sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/Coverage.java
- sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/CoverageReportImportSensor.java
- sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/OpenCoverReportParser.java
- sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/BranchPointTest.java
- sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/CoverageReportImportSensorTest.java
- sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/CoverageTest.java
- sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/DotCoverReportParserTest.java
- sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/OpenCoverReportParserTest.java
- sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/VisualStudioCoverageXmlReportParserTest.java
- sonar-dotnet-shared-library/src/test/resources/opencover/code_tested_by_multiple_projects.xml
- sonar-dotnet-shared-library/src/test/resources/opencover/coverage_branches.xml
- sonar-dotnet-shared-library/src/test/resources/opencover/invalid_file_id.xml
- sonar-dotnet-shared-library/src/test/resources/opencover/switch_expression_multiple_test_projects_1.xml
- sonar-dotnet-shared-library/src/test/resources/opencover/switch_expression_multiple_test_projects_2.xml
When a code file is touched by unit tests from different test projects,
it will appear multiple times in the open cover reports. Since different
tests can cover different branches we need to correctly identify the
covered branches and count them only once.
SequencePoint does not have enough information to allow this
and because of that we have to rely on BranchPoints.
Fixes branch coverage import for #3296
> Fix OpenCover branch coverage import by using BranchPoints

- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/SarifParserCallbackImpl.java
- sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/RoslynDataImporterTest.java
- sonar-dotnet-shared-library/src/test/resources/RoslynDataImporterTest/roslyn-report-invalid-location.json
Issues from third-party Roslyn analyzers (including Roslyn analyzers provided by Microsoft) are included in the MSBuild output and imported by default into SonarQube.
In this case they are considered external issues and the Roslyn importer is very forgiving regarding the location:
- if the column is invalid it will use only the line
- if both column and line are invalid, it will report the issue on the file.
On the other hand, if the [SDK for SonarQube Roslyn Analyzer Plugins](https://github.com/SonarSource/sonarqube-roslyn-sdk) is used to create a plugin for the analyzers, then the issues are treated as internal and the importer will not fallback to line or file level.
This commit is changing that and allows the import of internal issues (excepting the ones from `csharpsquid` and `vbnet` …
> Allow import of internal issues with invalid location

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/ClassNotInstantiatable.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Rules/ClassNotInstantiatableBase.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Rules/ClassNotInstantiatable.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ClassNotInstantiatable.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ClassNotInstantiatable.vb
Fixes #3329
Added check for classes derived from SafeHandle to not flag S3453.
Note: I based this PR on the Repro cases to be added with #3336. Let me know if that's not desirable and I will remove the test cases from this PR again.
> S3453: Fix FP with SafeHandle

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/EmptyNullableValueAccess.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/ISymbolicExecutionAnalysisContext.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/ISymbolicExecutionAnalyzer.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/ObjectsShouldNotBeDisposedMoreThanOnce.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/SymbolicExecutionAnalyzerFactory.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/SymbolicExecutionRunner.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Common/IRuleFactory.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/RuleDetailBuilder.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/RuleFinder.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Common/RuleFinderTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Common/RuleTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Constants.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/ResourceTests/GeneratedResourcesTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/EmptyNullableValueAccessTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/ObjectsShouldNotBeDisposedMoreThanOnceTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/SymbolicExecutionAnalyzerFactoryTest.cs
This commit introduces `SymbolicExecutionRunner` which allows the reuse of the generated exploded graph and walking it one single time for all the symbolic execution rules.
As a proof of concept, `SymbolicExecutionRunner` is now executing the `EmptyNullableValueAccess` and `ObjectsShouldNotBeDisposedMoreThanOnce` analyzers which are refactored to implement `ISymbolicExecutionAnalyzer` instead of `SonarDiagnosticAnalyzer`.
With this refactoring the overall analysis time drops ~6%.
Fixes: #3341
> Reuse symbolic execution logic in EmptyNullableValueAccess and ObjectsShouldNotBeDisposedMoreThanOnce

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/InvalidCastToInterface.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/InvalidCastToInterfaceRuleConstants.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/InvalidCastToInterfaceRuleDetails.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/InvalidCastToInterfaceSymbolicExecution.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SymbolicExecution/CSharp/CSharpExplodedGraph.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestFramework/DiagnosticVerifier.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestFramework/Verifier.cs
Since this rule combines two (distinct and complementary) implementations I've split it in two analyzers:
- one is doing semantic analysis
- the other symbolic execution
This split will ease #3346 implementation.
> Split InvalidCastToInterface

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/NumberPatternShouldBeRegular.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/NumberPatternShouldBeRegularTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/NumberPatternShouldBeRegular.cs
Fixes #3165
Take binary and hexadecimal prefixes into account.
All groups should have the same size with these exceptions:
* first group before the dot is allowed to be shorter.
* last group after the dot is allowed to be shorter.
* It is allowed to only have groups before the dot.
* the first group after the dot (if multiple) should be one shorter than the group size
Specially the last one was missing.
``` C#
var amout = 1_123_123.23_123_12m; 
```
> Fix S3937 FP and other improvements on number pattern checks

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/ConditionEvaluatesToConstant.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/EmptyNullableValueAccess.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/ObjectsShouldNotBeDisposedMoreThanOnce.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/SymbolicExecutionRunner.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SymbolicExecution/Common/AbstractExplodedGraph.cs
Additional changes:
- ensure that analyzer contexts are disposed right after diagnostics are reported
- increase max step count for symbolic execution. Some of the rules are adding additional steps and due to this we had some FNs which were correctly reported in 8.7. With this increase we can avoid those FNs and find even more TP.
> Update S3966 and S3655 to support partial results

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/RestrictDeserializedTypes.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/RestrictDeserializedTypes.JavaScriptSerializer.cs
- additionally a null resolver is considered safe
> S5773: JavaScriptSerializer default constructor is safe

- scripts/build/build-utils.ps1
- sonar-csharp-plugin/pom.xml
- sonar-vbnet-plugin/pom.xml
- sonaranalyzer-dotnet/src/SonarAnalyzer.CFG/SonarAnalyzer.CFG.cs.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.CFG/SonarAnalyzer.CFG.csproj
- sonaranalyzer-dotnet/src/SonarAnalyzer.CFG/packages.lock.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SonarAnalyzer.CSharp.csproj
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/packages.lock.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/SonarAnalyzer.Common.csproj
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/packages.lock.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.RuleDescriptorGenerator/Descriptor.cs.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.RuleDescriptorGenerator/Descriptor.vbnet.nuspec
- sonaranalyzer-dotnet/src/SonarAnalyzer.RuleDescriptorGenerator/SonarAnalyzer.RuleDescriptorGenerator.csproj
- sonaranalyzer-dotnet/src/SonarAnalyzer.RuleDescriptorGenerator/packages.lock.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/SonarAnalyzer.Utilities.csproj
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/packages.lock.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/SonarAnalyzer.VisualBasic.csproj
- sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/packages.lock.json
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/SonarAnalyzer.CSharp.nuspec
- sonaranalyzer-dotnet/tests/CBDE/CBDEArguments/CBDEArguments.csproj
- sonaranalyzer-dotnet/tests/CBDE/CBDEFails/CBDEFails.csproj
- sonaranalyzer-dotnet/tests/CBDE/CBDESucceedsWithIncorrectResults/CBDESucceedsWithIncorrectResults.csproj
- sonaranalyzer-dotnet/tests/CBDE/CBDEWaitAndSucceeds/CBDEWaitAndSucceeds.csproj
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/SonarAnalyzer.UnitTest.csproj
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/packages.lock.json
This commit will update to .Net Standard 2.0 the following projects:
- SonarAnalyzer.CFG
- SonarAnalyzer.Common
- SonarAnalyzer.CSharp
- SonarAnalyzer.Utilities
- SonarAnalyzer.VisualBasic
and to .Net 4.6.1 the following:
- SonarAnalyzer.RuleDescriptorGenerator
- CBDEArguments
- CBDEFails
- CBDESucceedsWithIncorrectResults
- CBDEWaitAndSucceeds
> Update analyzers target to .Net Standard 2.0

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Helpers/AspNetMvcHelper_IsControllerMethod.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Helpers/NetFrameworkVersionProviderTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Helpers/TypeDeclarationSyntaxExtensionsTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/MetadataReferences/FrameworkMetadataReference.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/MetadataReferences/NetStandardMetadataReference.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Performance/PerformanceTests.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/AssertionArgsShouldBePassedInCorrectOrderTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/CertificateValidationCheckTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/ConfiguringLoggersTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/CookieShouldBeHttpOnlyTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/CookieShouldBeSecureTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/DeliveringDebugFeaturesInProductionTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/ExecutingSqlQueriesTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/MethodShouldBeNamedAccordingToSynchronicityTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/UsingCookiesTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestFramework/SolutionBuilder.cs
- it is common for both `.Net Framework` and `.Net Core`
> Move NetStandard reference into it's own file

- sonaranalyzer-dotnet/src/SonarAnalyzer.CFG/SonarAnalyzer.CFG.csproj
- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/SonarAnalyzer.Common.csproj
- sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/SonarAnalyzer.Utilities.csproj
- sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/SonarAnalyzer.Vsix.csproj
Visual Studio 2015 does not support .Net Standard out of the box.
In order to keep compatibility we will target both .Net 4.6.1 and .Net Standard 2.0 but use only .Net 4.6.1 in plugin.
> Fix build errors when using VS2015

- azure-pipelines.yml
We have intermittent failures in our CI/CD when trying to run the unit tests for netcoreapp3.1
Sample logs:
```
2020-07-24T00:26:32.6416433Z Run tests on .Net Core 3.1
2020-07-24T00:26:33.9112051Z Test run for D:\a\1\s\sonaranalyzer-dotnet\tests\SonarAnalyzer.UnitTest\bin\Release\netcoreapp3.1\SonarAnalyzer.UnitTest.dll(.NETCoreApp,Version=v3.1)
2020-07-24T00:26:34.5767254Z dotnet : The test source file 
2020-07-24T00:26:34.5770085Z "D:\a\1\s\sonaranalyzer-dotnet\tests\SonarAnalyzer.UnitTest\bin\Release\netcoreapp3.1\SonarAnalyzer.UnitTest.dll" 
2020-07-24T00:26:34.5771517Z provided was not found.
2020-07-24T00:26:34.5772760Z At D:\a\_temp\1e91bf39-455b-463e-97b0-7e1849ffbc76.ps1:17 char:1
2020-07-24T00:26:34.5774664Z + dotnet test $testProjFileName -c Release --no-build --no-restore --no …
```
> Debug logging to debug intermittent failures

- azure-pipelines.yml
- scripts/rspec/rspec2resx.ps1
Noticed during build that there are multiple points of failure:
```
D:\a\1\s\scripts\rspec\\_strings.restext : error RG0000: The process cannot access the file 'D:\a\1\s\scripts\rspec\_strings.restext' because it is being used by another process. [D:\a\1\s\sonaranalyzer-dotnet\src\SonarAnalyzer.CSharp\SonarAnalyzer.CSharp.csproj]
```
This happens because `_strings.restext` file is generated twice during build. Once for .Net 4.6.1 and once for .Net Standard. There is also an additional issue since it was supposed to be named `cs_strings.restext` and `vbnet_strings.restext` but the language prefix is missing.
```
ResGen : error RG0000: Output file is possibly corrupt.  Deleting "D:\a\1\s\sonaranalyzer-dotnet\src\SonarAnalyzer.CSharp\RspecStrings.resx" …
```
> Fix concurrency issue on rspec generation

- docs/contributing-plugin.md
**SonarAnalyzer.RuleDescriptorGenerator** is executed for both **cs** and **vbnet** during build.
> Remove redundant step from doc

- sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/CoverageReportImportSensor.java
- sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/CoverageReportImportSensorTest.java
https://docs.sonarqube.org/x/CoBh is broken.
See community threads [one](https://community.sonarsource.com/t/receiving-the-code-coverage-report-doesnt-contain-any-coverage-data-for-the-included-files-for-net-coverage/29737) and [two](https://community.sonarsource.com/t/scanner-for-msbuild-url-https-docs-sonarqube-org-x-cob-is-broken/21589).
> Fix broken link in user warning

- sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/UnitTestResultsAggregator.java
- sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/UnitTestResultsImportSensor.java
- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/UnitTestResultsProvider.java
- sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/UnitTestResultsAggregatorTest.java
- sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/UnitTestResultsImportSensorTest.java
> Remove deprecated APIs: SensorDescriptor.global() from UnitTestResultsImportSensor

- sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/CoverageAggregator.java
- sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/CoverageReportImportSensor.java
- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/CodeCoverageProvider.java
- sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/CoverageReportImportSensorTest.java
> Remove deprecated APIs: SensorDescriptor.global() from CoverageReportImportSensor

- sonaranalyzer-dotnet/src/SonarAnalyzer.CFG/SonarAnalyzer.CFG.cs.nuspec
A complete list of TFM can be found here: https://docs.microsoft.com/en-us/dotnet/standard/frameworks
Fixes #3543
> NuGet packaging: Place SonarAnalyzer.CFG.dll in a framework specific folder

- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/EncodingPerFile.java
- sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/EncodingPerFileTest.java
> SQ plugin: Fall back to default when Roslyn encoding is not present

- azure-pipelines-external.yml
- azure-pipelines.yml
- sonaranalyzer-dotnet/its/sources/Net5/global.json
This reverts commit 45b65f5035b5cc4f7c452a1a7f5579d829692f6b.
On the new version the build becomes unstable due to:
```
C:\hostedtoolcache\windows\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error : Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt. [D:\a\1\s\sonaranalyzer-dotnet\src\SonarAnalyzer.CSharp\SonarAnalyzer.CSharp.csproj]
C:\hostedtoolcache\windows\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PEMethodSymbol.get_ExplicitInterfaceImplementations() [D:\a\1\s\sonaranalyzer-dotnet\src\SonarAnalyzer.CSharp\SonarAnalyzer.CSharp.csproj] …
```
> Revert "Use the latest version of .Net 5 (#3564)"

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/UnusedPrivateMember.cs
- make method static where possible
- use the most generic type where possible
> Cleanup around UnusedPrivateMember

- sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/AnalysisContextExtensions.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Helpers/AssertIgnoreScope.cs
`DefaultTraceListener.AssertUiEnabled` was not set for .NET core. That was causing `SonarAnalysis_WhenReportDiagnosticActionNotNull_AllowToContolWhetherOrNotToReport` to silently fail with error message logged in Tests output:
```
The active test run was aborted. Reason: Test host process crashed : Process terminated. Assertion Failed
Not expecting SonarLint to set both the old and the new delegates.
at SonarAnalyzer.Helpers.AnalysisContextExtensions.ReportDiagnostic(ReportingContext reportingContext) in C:\Projects\sonar-dotnet\sonaranalyzer-dotnet\src\SonarAnalyzer.Common\Helpers\AnalysisContextExtensions.cs:line 69
at SonarAnalyzer.Helpers.AnalysisContextExtensions.ReportDiagnosticWhenActive(SyntaxTreeAnalysisContext context, Diagnostic diagnostic) in …
```
> Fix AssertIgnoreScope for .NET Core

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/CSharpSymbolUsageCollector.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/CSharpSyntaxHelper.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/UnusedPrivateMember.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/UnusedPrivateMemberTest.Constructors.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/UnusedPrivateMemberTest.Types.cs
By retrieving symbols only for known names, when analyzing efcore, we reduce the analysis time from ~854678ms to 
~210854ms
Partial fix for #2474
> S1144, S4487: Read symbols only for known names

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SymbolicExecution/Common/Constraints/DisposableConstraint.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SymbolicExecution/Common/Constraints/SymbolicValueConstraints.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SymbolicExecution/Common/SymbolicValues/SymbolicValue.cs
This should help with future diagnostics of #3403 
All SE constraints except DisposableConstraint were sealed.
> Improve SymbolicValue error message and seal DisposableConstraint

- pom.xml
- sonar-csharp-plugin/pom.xml
- sonar-dotnet-shared-library/pom.xml
- sonar-vbnet-plugin/pom.xml
- sonaranalyzer-dotnet/pom.xml
For historical reasons, the parent project for both .NET analyzers was still called `sonar-csharp`. With some leftovers on other places. Same confusion is in SonarCloud and [SonarC# parent
](https://sonarcloud.io/dashboard?id=org.sonarsource.dotnet%3Asonar-csharp) project name and project key.
This PR should fix that.
I've stopped CI to prevent creating new duplicate project on SC. My plan is:
> Rename Java parent project

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/UnchangedLocalVariablesShouldBeConstTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/UninvokedEventDeclarationTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/UnnecessaryUsingsTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/UnusedPrivateMemberTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/UnusedReturnValueTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/UseGenericEventHandlerInstancesTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/UseNumericLiteralSeparatorTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/UseShortCircuitingOperatorTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UnchangedLocalVariablesShouldBeConst.CSharp9.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UninvokedEventDeclaration.CSharp9.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UnnecessaryUsings.CSharp9.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UnusedPrivateMember.CSharp9.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UnusedReturnValue.CSharp9.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UseGenericEventHandlerInstances.CSharp9.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UseNumericLiteralSeparator.CSharp9.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UseShortCircuitingOperator.CSharp9.Fixed.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UseShortCircuitingOperator.CSharp9.cs
> Add C# 9 test cases (8 rules)

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/CollectionPropertiesShouldBeReadOnlyTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/CollectionQuerySimplificationTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/ConditionalSimplificationTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/ConditionalStructureSameConditionTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/ConditionalsWithSameConditionTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/CollectionPropertiesShouldBeReadOnly.CSharp9.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/CollectionQuerySimplification.CSharp9.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ConditionalSimplification.FromCSharp9.Fixed.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ConditionalSimplification.FromCSharp9.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ConditionalStructureSameCondition.CSharp9.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ConditionalsWithSameCondition.CSharp9.TopLevelStatements.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ConditionalsWithSameCondition.CSharp9.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestFramework/CodeFixVerifier.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestFramework/Verifier.cs
> Add C# 9 tests for S4004, S2971, S3240, S1862 and S2760

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestFramework/NugetMetadataFactory.cs
`Microsoft.EntityFrameworkCore.SqlServer` NuGet package changed containted target framework to `netstandard2.1` in it's LATEST version.
> Add .NET Standard 2.1 to allowed NuGet directories

- sonaranalyzer-dotnet/its/regression-test.ps1
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/CBDE/MlirExporter.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/CBDE/CbdeHandlerTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/CBDE/MlirExportTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/ControlFlowGraph/ControlFlowGraphTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/CbdeHandler.CSharp9.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/CbdeHandler.cs
Fixes #3439
Fixes #3697
I did not add tests for top level statement, because test infrastructure and implementation works on `MethodDeclarationSyntax` level.
> S3949: Add C# 9 tests and do not fail for unsupported language version

- azure-pipelines.yml
- scripts/build/build-utils.ps1
- scripts/build/dev-build.ps1
This should have been done in #3700 ... better late than never.
In #3700 I forced the same behavior as on AZP.
By running `.\scripts\build\dev-build.ps1 -build -test -release` before opening a PR we'll make sure we won't have surprises.
> Run tests for all platforms in dev build

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/EmptyMethodTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/EmptyStatementTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/EnumerableSumInUncheckedTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/EqualityOnModulusTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/EquatableClassShouldBeSealedTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/EventHandlerDelegateShouldHaveProperArgumentsTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/EmptyMethod.CSharp9.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/EmptyMethod.Comment.Fixed.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/EmptyMethod.Throw.Fixed.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/EmptyMethod.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/EmptyStatement.CSharp9.Fixed.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/EmptyStatement.CSharp9.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/EnumerableSumInUnchecked.CSharp9.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/EqualityOnModulus.CSharp9.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/EquatableClassShouldBeSealed.CSharp9.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/EventHandlerDelegateShouldHaveProperArguments.CSharp9.cs
> Add C#9 tests for S1186, S1116, S2291 , S2197, S4035, S4220

- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/ExceptionShouldNotBeThrownFromUnexpectedMethodsTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/ExpressionComplexityTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/ExtensionMethodShouldBeInSeparateNamespaceTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ExceptionShouldNotBeThrownFromUnexpectedMethods.CSharp9.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ExceptionShouldNotBeThrownFromUnexpectedMethods.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ExpressionComplexity.CSharp9.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ExtensionMethodShouldBeInSeparateNamespace.CSharp9.cs
> Add C# 9 tests for S3877 , S1067 , S4226 

- azure-pipelines.yml
- scripts/build/build-utils.ps1
- sonaranalyzer-dotnet/its/ReviewDiffs/ReviewDiffs.csproj
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/MetadataReferences/AspNetCoreMetadataReference.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/DeliveringDebugFeaturesInProductionTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/DisposableMemberInNonDisposableClassTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/DoNotCallGCSuppressFinalizeTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/DoNotDecreaseMemberVisibilityTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/EmptyMethodTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/ExceptionShouldNotBeThrownFromUnexpectedMethodsTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/PointersShouldBePrivateTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/UnnecessaryUsingsTest.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/SonarAnalyzer.UnitTest.csproj
As far as I can tell opencover is considering only the first run
> Compute coverage for both .Net 4.8 and .Net 5

- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/BeginInvokePairedWithEndInvoke.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/CollectionQuerySimplification.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/DebugAssertHasNoSideEffects.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/EnumerableSumInUnchecked.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/GetTypeWithIsAssignableFrom.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/RedundantToCharArrayCall.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/TypeExaminationOnSystemType.cs
- sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/UseStringIsNullOrEmpty.cs
- sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/EnumerableSumInUnchecked.cs
Related to #3731 (but a full fix)
Fixes #3768
(leftovers after #3771)
all these rules take several seconds and there wasn't a visible improvement in #3771 because we don't check the method name before getting the symbol
> Improve perf for S2291, S2971, S3346 and S3256

- .github/workflows/SubmitReview.yml
Second baby step in Kanban automation. Most of the content is copy/paste from https://github.com/SonarSource/sonar-dotnet/blob/master/.github/workflows/RequestReview.yml This is intentional to keep the orchestration as simple as possible. I'll extract it to standalone reusable action into another repo after dogfooding.
Desired functionality when review is submitted:
* Find all cards with "Fixed #xxxx" and process referenced issue XOR
* Process PR itself, if no referenced issue is found
* Do not process closed issues/PRs
Submitted review is COMMENT:
* Do nothing
Submitted review is APPROVE:
* Move card to "Review approved" (GitHub does this for PRs, but doesn't do it for referenced issues)
* Assign card to PR author, remove others
Submitted review is REQUEST CHANGES:
* Move card to "In …
> GitHub workflow: Submit review

- analyzers/src/SonarAnalyzer.CFG/ControlFlowGraph/CSharpControlFlowGraphBuilder.cs
- analyzers/tests/SonarAnalyzer.UnitTest/ControlFlowGraph/ControlFlowGraphTest.cs
> CFG generation throws StackOverlowException when syntax tree is too deep

- analyzers/src/SonarAnalyzer.Common/Helpers/UnitTestHelper.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/TestMethodShouldContainAssertion.NUnit.cs
TestMethodShouldContainAssertion (S2699) rule takes into account a return value and the TestCaseSourceAttribute of NUnit test methods
Fixes #3751
> TestMethodShouldContainAssertion (S2699) NUnit return value

- its/src/test/java/com/sonar/it/shared/TestUtils.java
We're having too much of [these failures](https://sonarsource.visualstudio.com/DotNetTeam%20Project/_build/results?buildId=25314&view=logs&jobId=5a0b2a7a-818d-5a4c-a639-e2568d087f6b&j=5a0b2a7a-818d-5a4c-a639-e2568d087f6b&t=407cbd3b-4ba1-5b9c-259b-e19d650c77d2) in CI
```
[ERROR] Tests run: 102, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 551.258 s <<< FAILURE! - in com.sonar.it.csharp.Tests
[ERROR] visual_studio_on_MultipleProjects(com.sonar.it.csharp.CoverageTest)  Time elapsed: 73.875 s  <<< ERROR!
com.sonar.orchestrator.util.CommandException: Timeout exceeded: 60000 ms [command: cmd /c ""C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe" "/t:Restore,Rebuild""]
at com.sonar.it.csharp.CoverageTest.analyzeMultipleProjectsTestProject(Coverag …
```
> Update Java ITs MSBuild timeout

- analyzers/its/sources/ManuallyAddedNoncompliantIssues/NetFramework48/AesCngTest.cs
- analyzers/its/sources/ManuallyAddedNoncompliantIssues/NetFramework48/AesCryptoServiceProviderTest.cs
- analyzers/its/sources/ManuallyAddedNoncompliantIssues/NetFramework48/AesTest.cs
- analyzers/its/sources/ManuallyAddedNoncompliantIssues/NetFramework48/SymmetricAlgorithmTest.cs
- analyzers/rspec/cs/S3329_c#.html
- analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/InitializationVectorShouldBeRandom.cs
- analyzers/src/SonarAnalyzer.Utilities/Rules.Description/S3329.html
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/InitializationVectorShouldBeRandom.CSharp9.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/InitializationVectorShouldBeRandom.cs
Related to #3724
This updates the current implementation to consider the IV safe by default.
According to the [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.symmetricalgorithm.createencryptor?view=net-5.0#System_Security_Cryptography_SymmetricAlgorithm_CreateEncryptor):
> If the current Key property is null, the GenerateKey method is called to create a new random Key. If the current IV property is null, the GenerateIV method is called to create a new random IV.
> Rule S3329: IV is safe by default

- analyzers/src/SonarAnalyzer.CSharp/Rules/PropertiesShouldBePreferred.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/PropertiesShouldBePreferred.cs
Fix for FP on Consider making method '{0}' a property; when there is any attribute on the method not supported on properties.
Fixes #3140
> Fix S4049 FP: Do not raise on methods with attributes that are not allowed on properties

- scripts/build/dev-build.ps1
When running 
- `git clean -dfx`
- `.\scripts\build\dev-build.ps1 -buildJava -build -test -release` 
The build fails for the VSIX project (at least on my machine). This should fix it.
> Restore VSIX nuget packages

- analyzers/src/SonarAnalyzer.CSharp/Helpers/CSharpSymbolUsageCollector.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/MemberShouldBeStatic.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/AccessibilityExtensions.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/MemberShouldBeStatic.CSharp8.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnusedPrivateMember.CSharp7.cs
Related to #2478
Spin off from https://github.com/SonarSource/sonar-dotnet/pull/3843#discussion_r545271559
Having only public facing member, the rule didn't trigger.
Having only one Deconstruct, the code with access checking didn't run.
> Improve S1144 for protected internal members

- analyzers/src/SonarAnalyzer.CSharp/Rules/CollectionEmptinessChecking.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/CollectionEmptinessCheckingTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CollectionEmptinessChecking.cs
Will working on #2334 , I noticed that both `enumerable.Count() != 0` and `enumerable.Count(condition) ?? 0|1` where not covered by tests. The second already worked, but the first one didn't, so hence a simple fix.
> Fix S1155 FN: Count() != 0

- analyzers/.sonarlint/SonarAnalyzer.slconfig
- analyzers/.sonarlint/sonaranalyzer-dotnetCSharp.ruleset
- analyzers/tests/SonarAnalyzer.UnitTest/SonarAnalyzer.UnitTest.csproj
Our UT project didn't have correct link to `sonarlint.xml` configuration file so it was locally complaining about nonexistent issues (like license headers).
> Update SonarLint.xml and fix it's link in UTs

- azure-pipelines.yml
Currently, GitHub shows this full check name in CI check list:
`Sonar.Net (Promote NuGet on repox Promote SonarAnalyzer.CFG.CSharp NuGet on repox)`
this will fix it to
`Sonar.Net (Promote NuGet on repox SonarAnalyzer.CFG.CSharp)`
while still keeping the tree structure in AZP understandable.
This check is not marked as required. Renaming doesn't require to update GitHub settings.
Another PR is [on it's way](https://sonarsource.visualstudio.com/DotNetTeam%20Project/_git/pipelines-yaml-templates/pullrequest/14) in AZP to deal with 
`Sonar.Net (Promote artifacts on repox and notify Burgr Promote artifact on repox and notify Burgr)`
`Sonar.Net (Promote artifacts on repox and notify Burgr promoteBurgr)`
to
`Sonar.Net (Artifacts: Promote on repox)`
`Sonar.Net (Artifacts: Notify Burgr)`
> Rename "Promote Nuget on repox" pipeline step

- scripts/rspec/rspec.ps1
Revert of this https://github.com/SonarSource/sonar-dotnet/pull/3859#discussion_r545825263
`utf8BOM` produces this error (contrary [docs](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/set-content?view=powershell-7.1)):
>C:\Projects\sonar-dotnet\scripts\rspec\rspec.ps1 : Cannot bind parameter 'Encoding'. Cannot convert value "utf8BOM" to
type "Microsoft.PowerShell.Commands.FileSystemCmdletProviderEncoding". Error: "Unable to match the identifier name
utf8BOM to a valid enumerator name. Specify one of the following enumerator names and try again:
Unknown, String, Unicode, Byte, BigEndianUnicode, UTF8, UTF7, UTF32, Ascii, Default, Oem, BigEndianUTF32"
>At line:1 char:1
>+ .\scripts\rspec\rspec.ps1 cs S4036 CommandPath
>+ …
> Update rspec.ps1 encoding

- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/DiagnosticVerifier.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/IssueLocationCollector.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/IssueLocationCollectorTests/IssueLocationCollector_GetExpectedBuildErrors.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/IssueLocationCollectorTests/IssueLocationCollector_GetExpectedIssueLocations.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/IssueLocationCollectorTests/IssueLocationCollector_GetIssueLocations.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/IssueLocationCollectorTests/IssueLocationCollector_GetPreciseIssueLocations.cs
Related to #3185 
Intended usage for S5753:
```C#
var compilation = SolutionBuilder.Create().AddProject(AnalyzerLanguage.CSharp).GetCompilation();
var root = @"TestCases\WebConfigReader\S5753Values\";
var content = File.ReadAllText(root + "web.config");
DiagnosticVerifier.VerifyAdditionalDocument(compilation, new DisablingRequestValidation(AnalyzerConfiguration.AlwaysEnabled, root), content);
```
Intended in-file annotations for `S5753Values\web.config`:
```xml
<system.web>
<compilation debug="true" targetFramework="4.8" />
<httpRuntime targetFramework="4.8" />
<pages validateRequest="false" /> 
<httpRuntime requestValidationMode="0.0" />    
</system.web>
```
> Collect issue locations in XML files

- .editorconfig
Deactivate StyleCop rules:
* SA1305 FieldNamesMustNotUseHungarianNotation - too noisy vbWalker, csSourceFile, opCounter, ivSymbolicValue
* SA1401 FieldsMustBePrivate, we have better rules for that S2357 and S1104
* SA1204 StaticElementsMustAppearBeforeInstanceElements - doesn't match our style for methods
> Update StyleCop rules

- .github/workflows/SubmitReview.yml
If the issue is closed, we still need to change the assignee for Peach validation stage.
> GitHub workflow: Submit review update

- .github/ISSUE_TEMPLATE/false-positive---false-negative.md
Clarify the requirement for a reproducer to be minimal.
As #3996 contained report that's too hard to find, orchestrate and reproduce.
> Update GitHub FP/FN issue template

- analyzers/tests/SonarAnalyzer.UnitTest/MetadataReferences/NuGetMetadataReference.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/NugetMetadataFactory.cs
- this is needed in order to support dependencies like [Mono.Posix](https://www.nuget.org/packages/Mono.Posix.NETStandard)
> Extend NugetMetadataFactory to support specifying a runtime

- azure-pipelines.yml
Update to the latest [v1.0.11 commit](https://sonarsource.visualstudio.com/DotNetTeam%20Project/_git/pipelines-yaml-templates/commit/0b8ce2a631db4d551d8194bc472d2887069ba0a9?refName=refs%2Fheads%2Fmaster) 
* `stageName` is now configurable
* All titles related to `Compute variables needed in the Burgr payload` will be shorter
Due to changes in underlaying names from JulienH, we will have to replace required check from `Sonar.Net (Artifacts: Promote on repox)` to `Sonar.Net (Artifacts: Call repox)`
> Update commonTemplates to v1.0.11

- analyzers/src/SonarAnalyzer.CSharp/Helpers/CSharpDiagnosticAnalyzerContextHelper.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/ClassShouldNotBeAbstract.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/ClassWithOnlyStaticMember.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/DisposableNotDisposed.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/UnusedPrivateMember.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/DiagnosticAnalyzerContextHelper.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Helpers/VisualBasicDiagnosticAnalyzerContextHelper.cs
Remove redundant `Compilation` argument from `ReportDiagnosticIfNonGenerated` extensions
Rebase will be needed after #4060 is merged. The `Squash #4048` commit doesn't need a review.
> Remove redundant parameters from ReportDiagnosticIfNonGenerated

- analyzers/src/SonarAnalyzer.CSharp/Rules/StaticFieldInGenericClass.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/StaticFieldInGenericClass.cs
> Add FP repro for #4081

- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/FileTypeSensor.java
- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/ProjectTypeCollector.java
- sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/FileTypeSensorTest.java
- sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/ProjectTypeCollectorTest.java
Fixes  #4054 
TL;DR;:
- we now count the MSBuild projects and show statistics - how many are MAIN, how many are TEST etc. Each MSBuild project has an equivalent scanner module.
- the global module is an artificial scanner module which has no files and no MSBuild equivalent.
- the global module has `projectName` and `projectKey` properties like all other module; to filter it out, this PR uses `projectOutPath` which is a property just for "real project" modules.
The IT,  `MultipleProjectsTest#projectTypesInfoIsLogged`, hasn't changed.
> Fix project count logic - filter out global module

- .github/workflows/MilestoneIssue.yml
To work on a sprint, we need to add issues to ToDo column and set Milesones on all of them.
New intended process will be just adding milestones, as we have to do it anyway and choose the correct one. This action will automatically add the card to ToDo column for us.
Sprint issues without milestone needs to be added manually, as before.
> GitHub workflow: Milestone issue

- .github/workflows/CreatePullRequest.yml
- .github/workflows/RequestReview.yml
- .github/workflows/SubmitReview.yml
- .github/workflows/release.yml
We should provide early visibility to PRs & draft PRs as they are a WIP and consume time.
If PR contains "Fixes #xxx", this action does nothing as there should already exist a card on Kanban with the original issue.
For standalone PRs, it creates the card in "In progress" column and assigns PR to sender.
> GitHub workflow: Create PR

- its/src/test/java/com/sonar/it/csharp/DoNotAnalyzeTestFilesTest.java
- its/src/test/java/com/sonar/it/vbnet/DoNotAnalyzeTestFilesTest.java
- additional warnings can be logged on the build machine
> Use contains instead of containsExactly

- analyzers/rspec/cs/S3216_c#.html
- analyzers/src/SonarAnalyzer.Utilities/Rules.Description/S3216.html
As it can be seen in the following [blog post](https://devblogs.microsoft.com/dotnet/configureawait-faq/), ConfigureAwait(false) is not necessary in most cases in .Net Core as  there is no SynchronizationContext in most cases.
The rule was already raising only for .Net Framework but that was not mentioned in the rule description.
> S3216 RSPEC update

- azure-pipelines.yml
if the workspace is not clean, the plugin is not generated correctly and the size is bigger than the threshold.
> Clean workspace for java steps

- analyzers/tests/SonarAnalyzer.UnitTest/MetadataReferences/NuGetMetadataFactory.Package.cs
- analyzers/tests/SonarAnalyzer.UnitTest/MetadataReferences/NuGetMetadataFactory.cs
- remove separator at the end of the path
- add comments
- Path.GetFullPath() to always provide full path (useful when debugging)
> Cleanup around NuGetMetadataFactory

- analyzers/its/SonarAnalyzer.Testing.ImportBefore.targets
- analyzers/its/expected/WebConfig/Framework48-{6AC7E627-A21A-459C-8831-C45B6058E24D}-S5753.json
Generate artificial `FilesToAnalyze.txt` for .NET ITs and link it from `SonarProjectConfig.xml` file, because S4MSB is not used.
`dir /s /b` produces output like this. `findstr` is used to remove
* \bin\
* \obj\
* \packages\
* all directories (and also files) without an extension, becase `dir /a -d` to exclude directories throws an error `File not found`
```
c:\Projects\sonar-dotnet\analyzers\its\sources\WebConfig\App_Start
c:\Projects\sonar-dotnet\analyzers\its\sources\WebConfig\bin
c:\Projects\sonar-dotnet\analyzers\its\sources\WebConfig\Controllers
c:\Projects\sonar-dotnet\analyzers\its\sources\WebConfig\Global.asax
c:\Projects\sonar-dotnet\analyzers\its\sources\WebConfig\Global.asax.cs
c:\Projects\sonar-dotnet\analyzers\its\sources\WebConfig\Web.config …
```
> Generate FilesToAnalyze.txt in .NET ITs

- analyzers/rspec/cs/S2053_c#.json
- analyzers/src/SonarAnalyzer.CSharp/RspecStrings.resx
- analyzers/src/SonarAnalyzer.CSharp/Rules/FieldShadowsParentField.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/AnalysisContextExtensions.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/ReportingContext.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/SonarAnalysisContext.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Rules/FieldShadowsParentField.cs
- analyzers/tests/SonarAnalyzer.UnitTest/CBDE/CbdeHandlerTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/ClassAndMethodNameTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/CommentKeywordTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/EmptyMethodTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/FieldShadowsParentFieldTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/InsecureEncryptionAlgorithmTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/StringFormatValidatorTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/ConditionEvaluatesToConstantTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/EmptyCollectionsShouldNotBeEnumeratedTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/EmptyNullableValueAccessTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/HashesShouldHaveUnpredictableSaltTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/InitializationVectorShouldBeRandomTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/InvalidCastToInterfaceTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/NullPointerDereferenceTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/ObjectsShouldNotBeDisposedMoreThanOnceTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/PublicMethodArgumentsShouldBeCheckedForNullTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/RestrictDeserializedTypesTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/UnusedPrivateMemberTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/UseUriInsteadOfStringTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/ProjectBuilder.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SolutionBuilder.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/TestHelper.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Verifier.cs
> Refactor ReportDiagnosticWhenActive methods to not check diagnostic scope by default

- analyzers/its/ReviewDiffs/ReviewDiffs.csproj
- analyzers/src/SonarAnalyzer.CFG/SonarAnalyzer.CFG.csproj
- analyzers/src/SonarAnalyzer.CSharp/SonarAnalyzer.CSharp.csproj
- analyzers/src/SonarAnalyzer.Common/SonarAnalyzer.Common.csproj
- analyzers/src/SonarAnalyzer.Utilities/SonarAnalyzer.Utilities.csproj
- analyzers/src/SonarAnalyzer.VisualBasic/SonarAnalyzer.VisualBasic.csproj
- analyzers/tests/SonarAnalyzer.UnitTest/SonarAnalyzer.UnitTest.csproj
- azure-pipelines-external.yml
- azure-pipelines.yml
- scripts/build/dev-build.ps1
- currently StyleCop warnings pollute the logs, better no warnings at all
- maven batch mode avoids some unnecessary logs when downloading (see https://stackoverflow.com/a/48929096)
> Disable analysis during dev build (keep only live source analysis in the IDE)

- azure-pipelines-external.yml
- azure-pipelines.yml
This should not be needed anymore. https://github.com/SonarSource/sonar-scanner-msbuild/issues/829 was fixed and we have S4NET 5.2 on AZP already. 
Functionality is verified in #4238 that's based on this branch - new artificial issue failed the QG
> Remove /p:RunAnalyzers=true

- analyzers/tests/SonarAnalyzer.UnitTest/Common/SecurityHotspotTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/Hotspots/CookieShouldBeHttpOnlyTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/Hotspots/CookieShouldBeSecureTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/Hotspots/ExecutingSqlQueriesTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/Hotspots/RequestsWithExcessiveLengthTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/Hotspots/UsingRegularExpressionsTest.cs
When running the hotspots, link only the required references instead of doing a union of all the references needed by all hotspots
> SecurityHotspotTest: link only required references

- .github/GitHub.shproj
- .github/dependabot.yml
- analyzers/SonarAnalyzer.sln
GitHub Dependabot is adding PRs to our repo once upon a time, like #4317
By default, it creates `dependency` label and adds it to the PR. This should prevent the label from appearing.
Changes are based on [docs for dependabot](https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates) and [labels section](https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates#labels)
> Configure dependabot.yml

- analyzers/src/SonarAnalyzer.Common/Helpers/SymbolHelper.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Helpers/SymbolHelperTest.cs
- moved methods to respect our convention
- use arrow methods where possible
- fix alignment
- use switch expressions
- re-arrange operators where needed
> Cleanup SymbolHelper

- analyzers/src/SonarAnalyzer.CSharp/Rules/UninvokedEventDeclaration.cs
Fixes  #4498
- doing the same method call inside a loop is not optimal.
- this wouldn't have lead to a huge perf increase, but `GetInvokedEventSymbols()` does a `tuple.SemanticModel.GetSymbolInfo(tuple.SyntaxNode).Symbol` inside, so it can explode if there's lots of events inside a codebase
> Fix S3264 perf regression

- analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/LooseFilePermissions.cs
- analyzers/src/SonarAnalyzer.CSharp/Wrappers/ObjectCreationFactory.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/Hotspots/LooseFilePermissionsTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/LooseFilePermissions.Windows.CSharp9.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Wrappers/ObjectCreationFactoryTest.cs
First commit is a WIP from other rules to have `IObjectCreation.IsKnownType` and doesn't need a review.
Unrelated UTs are expected to fail before rebase.
> Rule S2612: Add support for target typed new expressions

- .github/workflows/RequestReview.yml
- .github/workflows/SubmitReview.yml
Old state: When card was already assigned to the desired user, `removeAssignees` and `addAssignee` happend asynchronously. So user was often added and them all users were removed.
New state: Wait for removal before adding the desired user.
> GitHub workflow: await removeAssignees

- analyzers/src/SonarAnalyzer.CSharp/Rules/ExceptionsShouldBeUsed.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ExceptionsShouldBeUsed.cs
In our [April perf evaluation](https://docs.google.com/spreadsheets/d/1uo7kSDPkbRFyoXtzBp7Piftcpda29i9mUoj-ZTluCtQ/edit#gid=1598900315) , on `nodatime`, S3984 behaved pretty badly:
<google-sheets-html-origin>
ExceptionsShouldBeUsed |  6324 ms (4%)
-- | -- |
</google-sheets-html-origin>
Also, see [internal report.](https://discuss.sonarsource.com/t/performance-problem-reported-for-csharp-post-8-9-upgrade-rules-impacted-s1128-s3984-and-s1450/7867/3). 
It's pretty obvious it will behave bad because it's querying the symbol as the first operation in the rule.
> Improve S3984 performance

- .github/workflows/CreatePullRequest.yml
Dependabot is creating PRs directly from our repository, so it passes the original `if` condition.
It doesn't have enough permissions and creates errors like this https://github.com/SonarSource/sonar-dotnet/pull/4543/checks?check_run_id=2817846021
We don't need a card for bot PRs. It will be created later, when needed by other actions (request (self) review, approve review)
> GitHub workflow: Don't run CreatePullRequest for bots

- .github/workflows/LabelIssue.yml
When Label `Type: xxx` is added to an open issue:
* create card in `Backlog` project and associated column 
* move card to the new column if exists
Column selection is based on the column name. Column-related API is available in preview mode (special header tag is needed to gain access).
If two or more `Type: xxx` labels are added (invalid state as per process), last queued action wins.
Isn't easy: 
https://docs.github.com/en/rest/reference/projects#list-repository-projects
This script can be used (after fitting with github token instead of `FIXME`):
https://github.com/pavel-mikula-sonarsource/GitHubActionPlayground/blob/8a932277c20ffdfc97c66e6b8468bc65989621fe/index.js#L15-L26
https://github.com/pavel-mikula-sonarsource/GitHubActionPlayground/projects/2 …
> GitHub workflow: Label issue to Backlog

- analyzers/src/Directory.Build.props
- analyzers/src/SonarAnalyzer.CFG/SonarAnalyzer.CFG.csproj
- analyzers/src/SonarAnalyzer.CSharp/SonarAnalyzer.CSharp.csproj
- analyzers/src/SonarAnalyzer.Common/SonarAnalyzer.Common.csproj
- analyzers/src/SonarAnalyzer.RuleDescriptorGenerator/packages.lock.json
- analyzers/src/SonarAnalyzer.ShimLayer.CodeGeneration/packages.lock.json
- analyzers/src/SonarAnalyzer.Utilities/SonarAnalyzer.Utilities.csproj
- analyzers/src/SonarAnalyzer.VisualBasic/SonarAnalyzer.VisualBasic.csproj
- analyzers/src/SonarAnalyzer.Vsix/SonarAnalyzer.Vsix.csproj
- analyzers/src/SonarAnalyzer.Vsix/packages.SonarAnalyzer.Vsix.config
- analyzers/src/SonarAnalyzer.Vsix/packages.lock.json
- analyzers/tests/CBDE/CBDEArguments/packages.lock.json
- analyzers/tests/CBDE/CBDEFails/packages.lock.json
- analyzers/tests/CBDE/CBDESucceedsWithIncorrectResults/packages.lock.json
- analyzers/tests/CBDE/CBDEWaitAndSucceeds/packages.lock.json
- analyzers/tests/Directory.Build.props
- analyzers/tests/SonarAnalyzer.UnitTest/SonarAnalyzer.UnitTest.csproj
- analyzers/tests/SonarAnalyzer.UnitTest/packages.lock.json
If we add the reference in `Directory.Build.props` it will be automatically available for all the projects.
Changes done:
- We introduced a problem with lock files (appeared only on a clean build): we need to reference parent `Directory.Build.props` in tests, otherwise it is not considered
- Fix the assembly name of the Vsix project (previously it was the same with SonarAnalyzer.Common which caused a conflict on NuGet restore)
- Used PackageReference instead of packages file in the VSIX project (we cannot use mixed and in `StyleCopAnalyzers.targets` package reference was used)
- Remove duplication where referencing `StyleCopAnalyzers.targets`
> Remove duplication when referencing StyleCopAnalyzers

- analyzers/src/SonarAnalyzer.CFG/SonarAnalyzer.CFG.csproj
- analyzers/src/SonarAnalyzer.CSharp/SonarAnalyzer.CSharp.csproj
- analyzers/src/SonarAnalyzer.Common/SonarAnalyzer.Common.csproj
- analyzers/src/SonarAnalyzer.RuleDescriptorGenerator/SonarAnalyzer.RuleDescriptorGenerator.csproj
- analyzers/src/SonarAnalyzer.Utilities/SonarAnalyzer.Utilities.csproj
- analyzers/src/SonarAnalyzer.VisualBasic/SonarAnalyzer.VisualBasic.csproj
`DisableImplicitNuGetFallbackFolder` it is already defined in Directory.Build.props
> Remove duplicate property and reduce the scope for the warning suppression

- analyzers/src/SonarAnalyzer.CSharp/Rules/UnchangedLocalVariablesShouldBeConst.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnchangedLocalVariablesShouldBeConst.cs
> Fix S3353 FP: Variable is used within an Expression

- analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Common/SymbolicValues/Binary/AndSymbolicValue.cs
- analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Common/SymbolicValues/Binary/BinarySymbolicValue.cs
- analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Common/SymbolicValues/Binary/BoolBinarySymbolicValue.cs
- analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Common/SymbolicValues/Binary/ComparisonSymbolicValue.cs
- analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Common/SymbolicValues/Binary/OrSymbolicValue.cs
- analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Common/SymbolicValues/Binary/RelationalSymbolicValue.cs
- analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Common/SymbolicValues/Binary/XorSymbolicValue.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/SymbolicValues/SymbolicValue_TrySetConstraint.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/SymbolicValues/SymbolicValuesTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/NullPointerDereference.cs
Fixes #3395
`OrSymbolicValue.TrySetConstraint` triggered too deep exponential tree evaluation. Same happens for other binary constraints as well.
Changes:
* Introduced `BoolBinarySymbolicValue` to extract common logic for all `BinarySymbolicValue` types that work with `BoolContraint`
* Measure nested size of operands
* Limit size of explored operands based on measurements
SE flow:
* All instructions are processed
* `VisitBinaryBranch` is called at the end of the block
* Constraint is set in `TrySetConstraint` here https://github.com/SonarSource/sonar-dotnet/blob/954aaee95a640e6de52480e5bdacdf67e7b0a687/analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/CSharp/CSharpExplodedGraph.cs#L870
> Improve SE performance for a long OR chain condition

- analyzers/src/SonarAnalyzer.CSharp/Helpers/CSharpEquivalenceChecker.cs
- analyzers/src/SonarAnalyzer.CSharp/Helpers/CSharpNavigationHelper.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/ConditionalStructureSameCondition.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/ConditionalsWithSameCondition.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/EquivalenceChecker.cs
- analyzers/src/SonarAnalyzer.Common/Rules/ConditionalStructureSameConditionBase.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Rules/ConditionalStructureSameCondition.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Helpers/EquivalenceCheckerTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ConditionalStructureSameCondition.CSharp9.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ConditionalsWithSameCondition.CSharp9.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ConditionalsWithSameCondition.cs
I don't want to fix this. PR contains only some cleanup and more UTs.
`CSharpEquivalenceChecker` can be updated to replace nodes in the tree to normalize null checks, but it's not worth the trouble and performance impact on all usages.
From syntax point of view, the check is not the same. Even when the semantic meaning is.
> Rule S1862 and S2760: add support for C# 9 pattern matching

- azure-pipelines.yml
This confuses me every time I read the YML file.
> AZP: Rename pipelines-yaml-templates from commonTemplates to pipelines-yaml-templates

- analyzers/its/AllSonarAnalyzerRules.ruleset
- analyzers/its/sources/ManuallyAddedNoncompliantIssues.CS/IntentionalFindings/S3949.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/CbdeHandlerRule.cs
Currently this rule is disabled by default and we plan to rewrite it.
Fixes #4619
> Skip S3949 when running ITs

- analyzers/src/SonarAnalyzer.CSharp/Trackers/CSharpMethodDeclarationTracker.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Trackers/VisualBasicMethodDeclarationTracker.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Trackers/MethodDeclarationTrackerTest.cs
There's no UT for this.
It could be reachable with `ControllingPermissions`, but it's obsolete and targets .NET Framework-only. 
It's too complicated to scaffold with artificial AnalyzerContext.
> Support C# 9 init-only setters in CSharpMethodDeclarationTracker

- azure-pipelines.yml
This is necessary to dogfood our own analyzer as well as SonarCloud's metrics visualization. When we migrated the CI to AZP we missed to upload test results.
I tested this locally with SQ - the below screenshot is from the measures tab http://localhost:9000/component_measures?id=local-sonar-dotnet&metric=tests
The number of tests is 4.9K because it's the sum of the `net48` and `net5.0` tests (however... they don't add up... it should be 4691 tests... - however data-driver UTs may be counted twice - to be investigated):
```
Passed!  - Failed:     0, Passed:  2230, Skipped:     0, Total:  2230, Duration: 2 m 33 s - SonarAnalyzer.UnitTest.dll (net48)
Passed!  - Failed:     0, Passed:  2461, Skipped:     0, Total:  2461, Duration: 44 s - SonarAnalyzer.UnitTest.dll (net5.0)
```
> [AZP] provide `sonar.cs.vstest.reportsPaths` to SC begin step

- azure-pipelines.yml
This reverts commit 8268375f9fef627b412d0ac5516e55efccc98c20.
Related to #4676
This actually didn't work because the SC project needs to be bound to the Github repo. And this currently isn't possible via the SC UI - they plan it for Q3 [(details)](https://discuss.sonarsource.com/t/gh-integration-main-branch-commit-is-green-even-if-qg-failed/7941/12?u=andrei_epure).
> Revert "Fix main branch SC decoration (#4676)"

- analyzers/src/SonarAnalyzer.Common/Helpers/ProjectTypeHelper.cs
Fixes #4470
Measurements on a VM for `protoactor-dotnet`, using 
* an average from 6 runs 
* independent on other commits - I did code changes manually to isolate the change
* measured with `/p:ReportAnalyzer`
* collected with `ParseBuildOutput` tool
* commit b08def1e
Detection | Time | Compared to Optimum | Absolute Regression | Relative Improvement
--- | --- | --- | --- | ---
Precomputed from Scanner | 137s | - | - | -
Before regression | 167s | +22% | - | -
Original regression | 171s | +24.4% | +2% | -
ToUpper-free | 168s | +22.2% | +0.2% | -1.8%
This PR | 145s | +5.5% | -13.5% | -15.2%
Measurements on a VM for `efcore`, using
* same as before except commit f8a6198da (same as in #4642)
Detection | Time | Compared to Optimum | Absolute Regression | Relative Improvement
--- | --- | --- | …
> Improve the detection time for project type (is test or main code)

- analyzers/its/expected/Net5/Net5--net5.0-S101.json
- analyzers/its/expected/Net5/Net5--net5.0-S1118.json
- analyzers/its/expected/Net5/Net5--net5.0-S1451.json
- analyzers/its/expected/Net5/Net5--net5.0-S2933.json
- analyzers/its/expected/Net5/Net5--net5.0-S3604.json
- analyzers/its/expected/Net5/Net5--net5.0-S3963.json
- analyzers/its/expected/Net5/Net5--net5.0-S4487.json
- analyzers/its/sources/Net5/Net5/S3604.cs
- analyzers/src/SonarAnalyzer.CSharp/Extensions/IMethodSymbolExtensions.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/MemberInitializerRedundant.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/MemberInitializerRedundantTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/MemberInitializerRedundant.CSharp9.Fixed.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/MemberInitializerRedundant.CSharp9.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/MemberInitializerRedundant.Fixed.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/MemberInitializerRedundant.cs
related to the module initializers support in https://jira.sonarsource.com/browse/MMF-2227
RE: records = it seems that we missed this rule from the https://jira.sonarsource.com/browse/MMF-2223 , however the compiler is already handling this case for records. More exactly, for
```
public record Bar
{
private string foo = "foo";    
public Bar(string foo)
{
foo = "foo";
}
}
```
The generated constructor (for which `IsImplicitlyDeclared` is `false` from a Roslyn API point of view...) is, according to sharplab.io 2 Aug 2021:
```
[System.Runtime.CompilerServices.NullableContext(0)]
public Bar(string foo)
{
this.foo = "foo";
base..ctor();
foo = "foo";
}
```
In sharplab.io there is an issue being raised that the assignment to `foo` is not necessary (as tested in sharplab.io).
Even more, for 
``` …
```
> Rule S3604: add support for static constructors and module initializers

- azure-pipelines.yml
Currently if the signing task fails it will let the build in an inconsistent state and any retry will lead to errors like: 
> ##[error]Artifact Binaries already exists for build 35465.
See: https://dev.azure.com/sonarsource/DotNetTeam%20Project/_build/results?buildId=35465&view=logs&jobId=f44a741f-9110-553a-520b-28a1a7416edf&j=f44a741f-9110-553a-520b-28a1a7416edf&t=af00f6af-222b-5187-006a-702a33759858
By pushing the artifacts after the signing occurs we avoid this.
> Change build tasks order

- analyzers/src/SonarAnalyzer.CSharp/Rules/ReferenceEqualityCheckWhenEqualsExists.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ReferenceEqualityCheckWhenEqualsExists.cs
When updating to  version `8.26.0.34506` I got the following error:
`AD0001: Analyzer 'SonarAnalyzer.Rules.CSharp.ReferenceEqualityCheckWhenEqualsExists' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.`
I got this twice (as, I got for two different projects in my solution). Unfortunately, after reloading the solution, I could not longer reproduce it.
Nevertheless, I checked the code, and made some small adjustments that should fix potential null de-references.
> ReferenceEqualityCheckWhenEqualsExists cleanup

- analyzers/src/SonarAnalyzer.CSharp/LiveVariableAnalysis/CSharp/CSharpLiveVariableAnalysis.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/MethodParameterUnused.CSharp8.cs
Fixes #4704
The key idea is to handle `GenericNameSyntax` (that has `.Identifier`) the same way as `ProcessIdentifier` was updated in #3818
> Fix S1172 FP: Parameter captured in a referenced generic local function

- analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/EmptyNullableValueAccess.cs
- analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Common/SymbolicValues/SymbolicValue.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/ConditionEvaluatesToConstantTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/EmptyNullableValueAccess.cs
Fixes #4573
The `NestedCombined` demonstrates, that there's something wrong with general condition processing in the engine itself. Relationships are probably not taken into considerations properly for consequent `if` statements - that's just documented for now.
> Fix AD0001 with Symbolic Execution engine

- azure-pipelines.yml
From original doc: https://github.com/OpenCover/opencover/wiki/Usage
```
-safemode:[on|off|yes|no] - enable or disable safemode - default is on/yes. When safemode is on OpenCover will use a common buffer for all threads in an instrumented process and this may have performance impacts depending on your code and its tests. Turning safemode off uses individual buffers for each thread but this may lead to data loss (uncovered code reported) if the runtime shuts down the instrumented process before the profiler has had time to retrieve the data and shunt it to the host for processing.
```
> Disable opencover safe mode to reduce building time

- analyzers/src/SonarAnalyzer.ShimLayer.CodeGeneration/OperationLightupGenerator.cs
Most of the wrapped `IOperation`s are in `Microsoft.CodeAnalysis.Operations` namespace and there are 6 more of them in `FlowAnalysis` namespace:
```
Microsoft.CodeAnalysis.FlowAnalysis.ICaughtExceptionOperation
Microsoft.CodeAnalysis.FlowAnalysis.IFlowAnonymousFunctionOperation
Microsoft.CodeAnalysis.FlowAnalysis.IFlowCaptureOperation
Microsoft.CodeAnalysis.FlowAnalysis.IFlowCaptureReferenceOperation
Microsoft.CodeAnalysis.FlowAnalysis.IIsNullOperation
Microsoft.CodeAnalysis.FlowAnalysis.IStaticLocalInitializationSemaphoreOperation
```
This change is configured in `analyzers\src\SonarAnalyzer.CFG\ShimLayer\OperationInterfaces.xml` file, but the `Namespace` attribute was ignored in the code.
> Fix ignored namespace in OperationLightupGenerator

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CertificateValidationCheck.CSharp8.cs
(there is already support for C# 9 static lambdas, see [line 21](https://github.com/SonarSource/sonar-dotnet/blob/8.27.0.35380/analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CertificateValidationCheck.CSharp9.cs#L21)
> S4830 - add C#8 static local function test

- analyzers/src/SonarAnalyzer.CFG/ShimLayer/IOperationWrapperSonar.cs
- analyzers/tests/SonarAnalyzer.UnitTest/CFG/Roslyn/BasicBlockTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/CFG/Roslyn/CaptureIdTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/CFG/Roslyn/ControlFlowBranchTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/CFG/Roslyn/ControlFlowRegionTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/CFG/Roslyn/RoslynControlFlowGraphTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/TestHelper.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Wrappers/IOperationWrapperSonarTest.cs
There already exist `IOperationWrapper` interface in the ShimLayer as a base type for all wrapped interfaces.
This class has the same prefix to be easily found.
> Introduce IOperation wrapper

- analyzers/its/expected/Net5/Net5Test--net5.0-S2187.json
- analyzers/its/expected/Net5/Net5Test--net5.0-S2701.json
- analyzers/its/expected/Net5/Net5Test--net5.0-S3433.json
- analyzers/its/sources/Net5/Net5Test/Net5Test.csproj
- analyzers/its/sources/Net5/Net5Test/S3433_Mstest.cs
- analyzers/its/sources/Net5/Net5Test/S3433_Xunit.cs
- analyzers/its/sources/Net5/Net5Test/packages.lock.json
- analyzers/src/SonarAnalyzer.CSharp/Rules/TestMethodShouldHaveCorrectSignature.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/TestMethodShouldHaveCorrectSignature.CSharp9.cs
If a local function has a test method attribute, it should be flagged for NUnit and VSTest, but not for xUnit (which allows this behavior).
For adding ITs, I need to rebase on master after #4834 gets merged (it's adding a new test project to the Net5 solution; avoid polluting this PR until rebase).
> S3433 - support C# 9 attributes on local functions

- analyzers/src/SonarAnalyzer.CSharp/Rules/TestMethodShouldContainAssertion.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/TestMethodShouldContainAssertionTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/TestMethodShouldContainAssertion.MsTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/TestMethodShouldContainAssertion.NUnit.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/TestMethodShouldContainAssertion.Xunit.cs
Shouldly is already supported by the UnitTestHelper KnownAssertionMethodParts - https://github.com/SonarSource/sonar-dotnet/blob/8.27.0.35380/analyzers/src/SonarAnalyzer.Common/Helpers/UnitTestHelper.cs#L60 - all methods contain "Should" .
I don't want to add explicit support because it would be additional logic with no functional gain.
Related to #1353
Might have conflicts with #4862 (rebase will be needed)
> S2699: add tests with Shouldly

- analyzers/tests/SonarAnalyzer.UnitTest/LiveVariableAnalysis/RoslynLiveVariableAnalysisTest.TryCatchFinally.cs
- analyzers/tests/SonarAnalyzer.UnitTest/LiveVariableAnalysis/RoslynLiveVariableAnalysisTest.cs
This changes Roslyn LVA assertion error messages from
>  Expected Lva.LiveOut(block).Select(x => x.Name) to be a collection with 3 item(s) because Block #2081 , but {"boolParameter", "intParameter"}"
to
>  Expected Lva.LiveOut(block).Select(x => x.Name) to be a collection with 3 item(s) because Block #2 Method(0);, but {"boolParameter", "intParameter"}"
to make it easier to find affected block
> Show block instruction in Roslyn LVA UTs

- analyzers/src/SonarAnalyzer.CFG/Helpers/UniqueQueue.cs
- analyzers/src/SonarAnalyzer.CFG/LiveVariableAnalysis/LiveVariableAnalysisBase.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Helpers/UniqueQueueTest.cs
Enqueuing predecessors after each LiveIn change tends to enqueue a single block multiple times when it is already in the queue. `Analyze()` then has to do some collection and HashSet manipulations to figure out that nothing has changed => no operation.
This PR should prevent that and improve the performance a little.
> Use UniqueQueue in LVA

- analyzers/its/AllSonarAnalyzerRules.ruleset
- analyzers/its/SingleRule.ruleset.template
- analyzers/its/SonarAnalyzer.Testing.ImportBefore.targets
- its/src/test/java/com/sonar/it/shared/TestUtils.java
.NET ITs silently produced this
>Warning CS8032: An instance of analyzer SonarAnalyzer.Rules.CSharp.TokenTypeAnalyzer cannot be created from C:\Projects\sonar-dotnet\analyzers\its\binaries\SonarAnalyzer.CSharp.dll : Could not load file or assembly 'Google.Protobuf, Version=3.6.1.0, Culture=neutral, PublicKeyToken=a7d26565bac4d604' or one of its dependencies. The system cannot find the file specified.
because `Google.Protobuf.dll` was not part of `Analyzers` property in targets file.
> Configure CS8032 as Error in ITs

- .github/workflows/CreatePullRequest.yml
- .github/workflows/LabelIssue.yml
- .github/workflows/MilestoneIssue.yml
- .github/workflows/RequestReview.yml
- .github/workflows/StartProgress.yml
- .github/workflows/SubmitReview.yml
This reverts commit b7bf044e20ca8ee74a4b70de4b2d45c3c04f509e.
We're having some GitHub action failures since then.
> Revert "Bump actions/github-script from 4.0.2 to 5 (#4923)"

- analyzers/src/SonarAnalyzer.CFG/CfgSerializer/CfgSerializer.RoslynCfgWalker.cs
- analyzers/src/SonarAnalyzer.CFG/Roslyn/ControlFlowRegion.cs
- analyzers/src/SonarAnalyzer.CFG/ShimLayer/CaptureId.cs
- analyzers/src/SonarAnalyzer.CFG/ShimLayer/LightupHelpers.cs
- analyzers/src/SonarAnalyzer.ShimLayer.CodeGeneration/OperationLightupGenerator.cs
- analyzers/tests/SonarAnalyzer.UnitTest/CFG/Roslyn/CaptureIdTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/CFG/Roslyn/RoslynCfgSerializerTest.cs
We need to return shimmed `CaptureId` instead of `InvalidOpertationException` when invoking `IFlowCaptureOperationWrapper.Id` and `IFlowCaptureReferenceOperationWrapper.Id`
> Return CaptureId from ShimLayer operations

- analyzers/src/SonarAnalyzer.Common/Json/Parsing/SyntaxAnalyzer.cs
`FIXME` comments should not be on `master`
These should have been removed in #5047 before the feature branch was merged to master as #5047 ensures the correct issue reporting.
This is a draft to prevent merging before release.
> Remove comments related to Json feature branch

- analyzers/src/SonarAnalyzer.Vsix/SonarAnalyzer.Vsix.csproj
- analyzers/src/SonarAnalyzer.Vsix/packages.lock.json
The old version of `Microsoft.VSSDK.BuildTools` could not be used in VS 2022 to compile the project.
>The target "CreateClientEnabledPkgFiles" does not exist
> Update Vsix NuGet references

- sonar-dotnet-shared-library/pom.xml
- sonar-vbnet-plugin/pom.xml
WhiteSource flags this as vulnerable.
> Update gson to 2.8.9

- analyzers/src/SonarAnalyzer.CFG/ShimLayer/INamedTypeSymbolExtensions.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/UnusedPrivateMember.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/UnusedPrivateMemberTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnusedPrivateMember.CSharp7.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnusedPrivateMember.CSharp9.Second.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnusedPrivateMember.CSharp9.TopLevelStatements.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnusedPrivateMember.CSharp9.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Verifier.cs
The symbols were processed twice, once for the Program symbol and the second time for the types defined in the top-level statement file.
> Rule S1144: remove duplicate issues in top level statements

- analyzers/src/SonarAnalyzer.VisualBasic/Metrics/VisualBasicExecutableLinesMetric.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Metrics/CSharpExecutableLinesMetricTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Metrics/VisualBasicExecutableLinesMetricTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SnippetCompilerTest.cs
> Count ElseIf as executable line metric for VB.NET

- analyzers/src/SonarAnalyzer.CFG/Sonar/CSharpControlFlowGraphBuilder.cs
- analyzers/src/SonarAnalyzer.CSharp/Extensions/SonarAnalysisContextExtensions.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/ConditionEvaluatesToConstant.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/EmptyCollectionsShouldNotBeEnumerated.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/EmptyNullableValueAccess.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/HashesShouldHaveUnpredictableSalt.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/ISymbolicExecutionAnalyzer.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/InitializationVectorShouldBeRandom.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/InvalidCastToInterfaceSymbolicExecution.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/NullPointerDereference.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/ObjectsShouldNotBeDisposedMoreThanOnce.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/PublicMethodArgumentsShouldBeCheckedForNull.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/RestrictDeserializedTypes.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/SymbolicExecutionRunner.cs
- analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Sonar/SonarExplodedGraph.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Sonar/SonarExplodedGraphTest.cs
Only `Rename CSharpExplodedGraph to SonarExplodedGraph` commit needs a review.
> Rename CSharpExplodedGraph to SonarExplodedGraph

- analyzers/SonarAnalyzer.sln
- analyzers/its/expected/Expected.shproj
It obstructs search results when searching for `reference`, `serial`, `engine`, ... in solution explorer file filter
> Remove ITs/Expected from Solution Explorer

- analyzers/StyleCopAnalyzers.targets
- analyzers/src/SonarAnalyzer.CFG/packages.lock.json
- analyzers/src/SonarAnalyzer.CSharp/packages.lock.json
- analyzers/src/SonarAnalyzer.Common/packages.lock.json
- analyzers/src/SonarAnalyzer.RuleDescriptorGenerator/packages.lock.json
- analyzers/src/SonarAnalyzer.ShimLayer.CodeGeneration/packages.lock.json
- analyzers/src/SonarAnalyzer.Utilities/packages.lock.json
- analyzers/src/SonarAnalyzer.VisualBasic/packages.lock.json
- analyzers/tests/CBDE/CBDEArguments/packages.lock.json
- analyzers/tests/CBDE/CBDEFails/packages.lock.json
- analyzers/tests/CBDE/CBDESucceedsWithIncorrectResults/packages.lock.json
- analyzers/tests/CBDE/CBDEWaitAndSucceeds/packages.lock.json
- analyzers/tests/SonarAnalyzer.UnitTest/packages.lock.json
Using beta version to fix SA1000 FP on C# 9 target-typed new keyword `new()`
> Bump StyleCop.Analyzers to 1.2.0-beta.354

- analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/SymbolicExecutionAnalyzerFactory.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/SymbolicExecutionRunner.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Sonar/SymbolicExecutionAnalyzerFactoryTest.cs
It does not change the behavior for now, because all rules run only on the main code. 
But having at least one rule running on Test&Main or Test causes `SymbolicExecutionRunner` to contain at least one diagnostic descriptor that should execute so all rules are executed, causing FPs in terms of their scope.
> Filter rule scope in SymbolicExecutionFactory

- analyzers/tests/SonarAnalyzer.UnitTest/CBDE/CbdeHandlerTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/CheckFileLicenseTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/Hotspots/DisablingRequestValidationTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/MethodsShouldNotHaveTooManyLinesTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/CodeFixVerifier.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/DiagnosticVerifier.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Verifier.cs
This is a prerequisite for #5159
`DiagnosticVerifier.GetAllDiagnostics` does also some verification that should not be its responsibility. Making the API hard to user (and long to write)
> Simplify DiagnosticVerifier

- analyzers/tests/SonarAnalyzer.UnitTest/Rules/CheckFileLicenseTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/MethodsShouldNotHaveTooManyLinesTest.cs
`OnlyCSharp7` actually contains `CSharp7`, `CSharp7_1`, `CSharp7_2` and `CSharp7_3` on `master` build.
> Fix failing UTs

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/ProgramState.cs
Use the underlaying operation as a key, instead of the wrapper
Squash commit doesn't need a review
> Improve SE ProgramState operation storage

- analyzers/its/expected/akka.net/Akka--netstandard2.0-S3442.json
- analyzers/rspec/cs/S3442_c#.html
- analyzers/src/SonarAnalyzer.CSharp/RspecStrings.resx
- analyzers/src/SonarAnalyzer.CSharp/Rules/AbstractTypesShouldNotHaveConstructors.cs
- analyzers/src/SonarAnalyzer.Utilities/Rules.Description/S3442.html
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/AbstractTypesShouldNotHaveConstructors.TopLevelStatements.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/AbstractTypesShouldNotHaveConstructors.cs
> S3442 suggests `private protected` instead of `protected` for internal ctors

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnusedPrivateMember.CSharp10.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnusedPrivateMember.CSharp7.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnusedPrivateMember.CSharp9.cs
add repro for #2752
I've motivated in https://github.com/SonarSource/sonar-dotnet/issues/2752#issuecomment-1005668009 why we should close as won't fix, but if after https://jira.sonarsource.com/browse/MMF-2417 the rule will be re-written, we could fix the FP if very easy and not impacting perf for such an edge case
> add repro for S4487 FP

- analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/DeliveringDebugFeaturesInProduction.cs
- analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/DeliveringDebugFeaturesInProductionBase.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Rules/Hotspots/DeliveringDebugFeaturesInProduction.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/DeliveringDebugFeaturesInProduction.NetCore2.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/DeliveringDebugFeaturesInProduction.NetCore3.cs
S4507 
Fixes #5032 - only for C#
(opening draft to discuss first with AppSec if this really makes sense)
> S4507: relax `env.IsDevelopment()` validator check

- analyzers/its/expected/Nancy/Nancy--net452-S927.json
- analyzers/its/expected/Nancy/Nancy--netstandard2.0-S927.json
- analyzers/src/SonarAnalyzer.Common/Rules/ParameterNameMatchesOriginalBase.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ParameterNameMatchesOriginal.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ParameterNameMatchesOriginal.vb
> S927 FP fix: Fix cases when generic type arguments are changed

- analyzers/tests/SonarAnalyzer.UnitTest/Rules/CommentedOutCodeTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/Hotspots/UsingCommandLineArgumentsTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/MarkAssemblyWithAssemblyVersionAttributeTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/NotAssignedPrivateMemberTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/RedundantCastTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/TestFramework/Verifier.BasePath.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/OldVerifier.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/ProjectBuilder.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SolutionBuilder.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Tests/IssueLocationCollectorTest.GetPreciseIssueLocations.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Tests/VerifierBuilderTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Tests/VerifierTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Verifier.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/VerifierBuilder.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Trackers/ConstantValueFinderTest.cs
Contributes to #5186
Add more options:
* `.AddSnippet`
* `.AddTestReference`
* `.WithBasePath`
* `.WithConcurrentAnalysis`
This is a draft, rebase will be needed after #5231 is merged. The squash commits doesn't need a review for the same reason.
> Add concurrency to VerifierBuilder

- analyzers/rspec/cs/S109_c#.html
- analyzers/src/SonarAnalyzer.Utilities/Rules.Description/S109.html
S109 rule got updated in #5247 together with the RSPEC changes (I should have merged the rspec PR after #5247 got merged, my bad), which got reverted in #5273.
I did this via `git checkout  4b55e5119 ...` , not via the RSPEC script because the rspec PR is still not merged. I rebased and pushed https://github.com/SonarSource/rspec/pull/694 to rerun the SQ check and set it to merge, however there seems to be some test failures.
> Bring back S109 RSPEC changes

- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/OldVerifier.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Verifier.cs
Leftover from #5270 where I forgot to make the fixed path relative to the `TestCases` directory.
> UT Verifier: Read codefix paths from TestCases directory

- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Tests/VerifierTest.cs
FluentAssertions behaves inconsistently when showing the error message. Sometimes it will find the actual variable name as `ActualCodeWithReplacedComments().ToUnixLineEndings()` and sometimes as `string`.
In order to update the library to the latest effort additional effort is needed since there are breaking changes.
> Fix UTs after FluentAssertions change on net6.0

- analyzers/src/SonarAnalyzer.CSharp/Rules/ClassNotInstantiatable.cs
- analyzers/src/SonarAnalyzer.Common/Rules/BeginInvokePairedWithEndInvokeBase.cs
- analyzers/src/SonarAnalyzer.Common/Rules/BooleanLiteralUnnecessaryBase.cs
- analyzers/src/SonarAnalyzer.Common/Rules/CertificateValidationCheckBase.cs
- analyzers/src/SonarAnalyzer.Common/Rules/ClassNotInstantiatableBase.cs
- analyzers/src/SonarAnalyzer.Common/Rules/DeclareTypesInNamespacesBase.cs
- analyzers/src/SonarAnalyzer.Common/Rules/DoNotCheckZeroSizeCollectionBase.cs
- analyzers/src/SonarAnalyzer.Common/Rules/DoNotLockWeakIdentityObjectsBase.cs
- analyzers/src/SonarAnalyzer.Common/Rules/DoNotOverwriteCollectionElementsBase.cs
- analyzers/src/SonarAnalyzer.Common/Rules/EmptyNestedBlockBase.cs
- analyzers/src/SonarAnalyzer.Common/Rules/EnumNameHasEnumSuffixBase.cs
- analyzers/src/SonarAnalyzer.Common/Rules/ExpectedExceptionAttributeShouldNotBeUsedBase.cs
- analyzers/src/SonarAnalyzer.Common/Rules/FlagsEnumWithoutInitializerBase.cs
- analyzers/src/SonarAnalyzer.Common/Rules/FlagsEnumZeroMemberBase.cs
- analyzers/src/SonarAnalyzer.Common/Rules/GenericInheritanceShouldNotBeRecursiveBase.cs
- analyzers/src/SonarAnalyzer.Common/Rules/IfChainWithoutElseBase.cs
- analyzers/src/SonarAnalyzer.Common/Rules/IndexOfCheckAgainstZeroBase.cs
- analyzers/src/SonarAnalyzer.Common/Rules/InsecureTemporaryFilesCreationBase.cs
- analyzers/src/SonarAnalyzer.Common/Rules/MarkWindowsFormsMainWithStaThreadBase.cs
- analyzers/src/SonarAnalyzer.Common/Rules/MethodOverloadsShouldBeGroupedBase.cs
- analyzers/src/SonarAnalyzer.Common/Rules/NameOfShouldBeUsedBase.cs
- analyzers/src/SonarAnalyzer.Common/Rules/ParameterNameMatchesOriginalBase.cs
- analyzers/src/SonarAnalyzer.Common/Rules/PropertyWriteOnlyBase.cs
- analyzers/src/SonarAnalyzer.Common/Rules/PureAttributeOnVoidMethodBase.cs
- analyzers/src/SonarAnalyzer.Common/Rules/SecurityPInvokeMethodShouldNotBeCalledBase.cs
- analyzers/src/SonarAnalyzer.Common/Rules/ShouldImplementExportedInterfacesBase.cs
- analyzers/src/SonarAnalyzer.Common/Rules/UnconditionalJumpStatementBase.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Rules/ClassNotInstantiatable.cs
Refactored all SonarDiagnosticAnalyzer base classes contained
``` C#
protected abstract ILanguageFacade<TSyntaxKind> Language { get; }
```
To inhertit from `SonarDiagnosticAnalyzer <TSyntaxKind>` instead (introduced in PR #5106 )
> Use SonarDiagnosticAnalyzer<TSyntaxKind> base type

- .github/workflows/release.yml
According to the release engineering team, we should not run `rules-cov` anymore as it's handled differently now.
> Remove run_rules_cov from release.yml

- analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Sonar/AbstractExplodedGraph.cs
We can help GC to collect unused nodes sooner
> Improve old Symbolic Execution memory consumption

- analyzers/src/SonarAnalyzer.Common/Helpers/IsExternalInit.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/ProgramState.cs
This approach will help to reduce duplications when more items are tracked.
It should prevent duplications like this:
https://github.com/SonarSource/sonar-dotnet/blob/c0d92c7faa43e0e0e112d3f667a78fc64e51bddd/analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Sonar/ProgramState.cs#L268-L341
> Refactor ProgramState to init-only setters

- .github/workflows/release.yml
I've used tags in the task reference.
All the versions can be found here:
- https://github.com/SonarSource/gh-action_release/releases
- https://github.com/jfrog/setup-jfrog-cli/releases
- https://github.com/8398a7/action-slack/releases
> Update the task versions from the release pipeline

- analyzers/its/sources/Ember-MM/Ember.Plugins/Ember.Plugins.csproj
- analyzers/its/sources/Ember-MM/Ember.Plugins/packages.config
- analyzers/its/sources/Ember-MM/Ember.Plugins/packages.lock.json
Update Integration Test dependency to avoid CVE-2018-1285 being raised. 
Our analyzer is not at risk.
> Update Ember-MM log4net dependency

- analyzers/tests/SonarAnalyzer.UnitTest/Rules/BeginInvokePairedWithEndInvokeTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/CertificateValidationCheckTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/ClassAndMethodNameTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/CollectionsShouldImplementGenericInterfaceTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/DisposeNotImplementingDisposeTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/EmptyNamespaceTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/ImplementISerializableCorrectlyTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/MutableFieldsShouldNotBePublicReadonlyTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/MutableFieldsShouldNotBePublicStaticTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/PartialMethodNoImplementationTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/InvalidCastToInterfaceTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/UnnecessaryUsingsTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/OldVerifier.cs
Squash commits doesn't need a review
> UTs: Remove OldVerifier overloads for C# 9 and 10

- analyzers/src/SonarAnalyzer.Common/Helpers/DictionaryExtensions.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/HashCode.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/ProgramState.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Helpers/BlockIdMapTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Helpers/DictionaryExtensionsTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Helpers/DotWriterTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Helpers/HashCodeTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ProgramStateTest.cs
Related to #5306 
It's a prerequisite for implementing `IEquatable` in `ExplodedNode`
> Implement IEquatable for ProgramState

- analyzers/tests/SonarAnalyzer.UnitTest/Rules/DoNotDecreaseMemberVisibilityTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/GenericTypeParameterEmptinessCheckingTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/MarkAssemblyWithAssemblyVersionAttributeTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/MarkAssemblyWithNeutralResourcesLanguageAttributeTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/NativeMethodsShouldBeWrappedTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/SerializationConstructorsShouldBeSecuredTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/ShouldImplementExportedInterfacesTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/TestMethodShouldNotBeIgnoredTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/XmlExternalEntityShouldNotBeParsedTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/OldVerifier.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Tests/DiagnosticVerifierTest.cs
This is draft for now. Rebase will be needed after the merge of #5294 (current target branch of this PR) and #5293 (see comment below)
> UTs: Remove OldVerifier.VerifyNonConcurrentAnalyzer

- analyzers/tests/SonarAnalyzer.UnitTest/Rules/ConditionalSimplificationTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/EmptyNamespaceTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/RedundantCastTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/UnnecessaryUsingsTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/UnusedPrivateMemberTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/OldVerifier.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Tests/VerifierBuilderTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Tests/VerifierTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/VerifierBuilder.cs
Batch version is never used without a fixed version. So we can unify the methods.
> UTs: Unify VerifierBuilder.CodeFixPaths

- analyzers/its/sources/Ember-MM/Addons/generic.EmberCore.NMT/generic.EmberCore.NMT.vbproj
- analyzers/its/sources/Ember-MM/Addons/generic.EmberCore.NMT/packages.config
- analyzers/its/sources/Ember-MM/Addons/generic.EmberCore.NMT/packages.lock.json
- analyzers/its/sources/Ember-MM/Addons/scraper.EmberCore.XML/packages.config
- analyzers/its/sources/Ember-MM/Addons/scraper.EmberCore.XML/packages.lock.json
- analyzers/its/sources/Ember-MM/Addons/scraper.EmberCore.XML/scraper.EmberCore.XML.vbproj
- analyzers/its/sources/Ember-MM/Addons/scraper.EmberCore/packages.config
- analyzers/its/sources/Ember-MM/Addons/scraper.EmberCore/packages.lock.json
- analyzers/its/sources/Ember-MM/Addons/scraper.EmberCore/scraper.EmberCore.vbproj
- analyzers/its/sources/Ember-MM/Ember Media Manager/Ember Media Manager.vbproj
- analyzers/its/sources/Ember-MM/Ember Media Manager/packages.config
- analyzers/its/sources/Ember-MM/Ember Media Manager/packages.lock.json
Updating dependency in ITs to avoid CVE warnings.
The CVE doesn't affect our analyzer.
> ITs: Update SharpZipLib to 1.3.3 in Ember-MM

- pom.xml
This also updates to xerces:xercesImpl:2.12.2 which addresses security warnings.
> Update sonar.analyzer.commons to 1.23

- LICENSE.txt
A valid license is required for [compliance reasons](https://jira.sonarsource.com/browse/BUILD-1273).
Contact Release Engineering Team for more information.
> BUILD-1337: fix license

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Checks/LocksReleasedAllPathsBase.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SymbolicContext.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SymbolicValue.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ProgramStateTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/SymbolicContextTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/SymbolicValueTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Monitor.Conditions.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Monitor.Loops.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SymbolicExecution/SETestContext.cs
Fixes #5370
First commit explains what is wrong.
Key change is in `SymbolicValue`
`SymbolicContext.SetSymbolConstraint` is additional value.
> Make SymbolicValue constraints immutable

- analyzers/src/SonarAnalyzer.CFG/Roslyn/ControlFlowGraphCache.cs
- analyzers/src/SonarAnalyzer.CSharp/Extensions/SyntaxNodeExtensions.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Extensions/SyntaxNodeExtensions.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Extensions/SyntaxNodeExtensionsTest.cs
Fixes #5384
When analyzing user project with only S1854 active, I get 20 sec build&analysis time after this change.
For 16000 invocations on that project, we have 11086 cache hits and 4914 cache misses.
> Cache CreateCfg

- analyzers/src/SonarAnalyzer.CFG/Extensions/PropertyInfoExtensions.cs
- analyzers/src/SonarAnalyzer.CFG/Helpers/RoslynHelper.cs
- analyzers/src/SonarAnalyzer.CFG/Roslyn/BasicBlock.cs
- analyzers/src/SonarAnalyzer.CFG/Roslyn/ControlFlowBranch.cs
- analyzers/src/SonarAnalyzer.CFG/Roslyn/ControlFlowGraph.cs
- analyzers/src/SonarAnalyzer.CFG/Roslyn/ControlFlowRegion.cs
- analyzers/src/SonarAnalyzer.CFG/ShimLayer/IOperationWrapperSonar.cs
> Reduce CFG memory allocations

- its/projects/ProjectLevelDuplication/ClassLibrary1/Class1.cs
- its/projects/ProjectLevelDuplication/ClassLibrary1/ClassLibrary1.csproj
- its/projects/ProjectLevelDuplication/ClassLibrary1/Properties/AssemblyInfo.cs
- its/projects/ProjectLevelDuplication/ClassLibrary2/Class1.cs
- its/projects/ProjectLevelDuplication/ClassLibrary2/ClassLibrary2.csproj
- its/projects/ProjectLevelDuplication/ClassLibrary2/Properties/AssemblyInfo.cs
- its/projects/ProjectLevelDuplication/ProjectLevelDuplication.sln
- its/src/test/java/com/sonar/it/csharp/ProjectLevelDuplicationTest.java
- its/src/test/java/com/sonar/it/csharp/Tests.java
> Java IT that documents the current de-duplication logic

- analyzers/packaging/SonarAnalyzer.CSharp.nuspec
- analyzers/packaging/SonarAnalyzer.VisualBasic.nuspec
- analyzers/packaging/tools-cs/install.ps1
- analyzers/packaging/tools-cs/uninstall.ps1
- analyzers/packaging/tools-vbnet/install.ps1
- analyzers/packaging/tools-vbnet/uninstall.ps1
- analyzers/src/SonarAnalyzer.CSharp/SonarAnalyzer.CSharp.csproj
- analyzers/src/SonarAnalyzer.Common/SonarAnalyzer.Common.csproj
- analyzers/src/SonarAnalyzer.RuleDescriptorGenerator/packages.lock.json
- analyzers/src/SonarAnalyzer.Utilities/packages.lock.json
- analyzers/src/SonarAnalyzer.VisualBasic/SonarAnalyzer.VisualBasic.csproj
- analyzers/tests/SonarAnalyzer.UnitTest/packages.lock.json
- its/src/test/java/com/sonar/it/csharp/Tests.java
- its/src/test/java/com/sonar/it/shared/TestUtils.java
- its/src/test/java/com/sonar/it/vbnet/Tests.java
- sonar-csharp-plugin/pom.xml
- sonar-vbnet-plugin/pom.xml
> Fix VB.NET BC42376: An instance of analyzer SymbolicExecutionRunner cannot be created

- azure-pipelines.yml
- scripts/whitesource/WhiteSource-Scan.ps1
Same changes as here:
https://github.com/SonarSource/sonar-dotnet-autoscan/commit/d0ad37196d71a292472b4a530b707e1c7a0fe131
This PR uses a release branch name to force WhiteSource to run on PR as well. It is meant to be merged to master - that is unusual.
> Fix WhiteSource releaseability check

- analyzers/its/expected/Nancy/Nancy--net452-S6354.json
- analyzers/its/expected/Nancy/Nancy--netstandard2.0-S6354.json
- analyzers/its/expected/akka.net/Akka--netstandard2.0-S6354.json
- analyzers/its/expected/akka.net/Akka.TestKit--netstandard2.0-S6354.json
- analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- analyzers/src/SonarAnalyzer.Common/Rules/UseTestableTimeProviderBase.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UseTestableTimeProvider.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UseTestableTimeProvider.vb
> S6354 FN: Add support for tracking usage of DateTimeOffset

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Invocation.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
Prerequisite for #5308
We need to remove constraints from symbols that are subject to `out`, `ref` and `ByRef` calls because their value is unknown from that point.
> Support out, ref and ByRef in SE

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Constants.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Loops.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.PatternMatching.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Mutex.NetFx.cs
> Support conditional branching in SE

- analyzers/rspec/cs/S3459_c#.html
- analyzers/src/SonarAnalyzer.CSharp/Rules/NotAssignedPrivateMember.cs
- analyzers/src/SonarAnalyzer.Utilities/Rules.Description/S3459.html
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/NotAssignedPrivateMember.cs
> Rule S3459: Add exception for types decorated with `Serializable` attribute.

- azure-pipelines.yml
Fixes master broken build, because we run sonar analysis twice
`mvn sonar:sonar` and  `sonarQubeRunAnalysis: true`
Attention for the reviewer: git blame shows that I introduced the 2nd analysis in #3018 to fix a code coverage issue. We must ensure there's no regression regarding code coverage before merging.
> Run mvn sonar just once

- analyzers/src/SonarAnalyzer.CSharp/Rules/ForLoopConditionAlwaysFalse.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/ExpressionNumericConverterBase.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/ForLoopConditionAlwaysFalseTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ForLoopConditionAlwaysFalse.CSharp9.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ForLoopConditionAlwaysFalse.cs
> FIX S2252 FP: Rule raises issue in case of non integer value in for loop.

- analyzers/src/SonarAnalyzer.CFG/Extensions/BasicBlockExtensions.cs
- analyzers/src/SonarAnalyzer.CFG/Extensions/ControlFlowRegionExtensions.cs
- analyzers/src/SonarAnalyzer.CFG/LiveVariableAnalysis/RoslynLiveVariableAnalysis.cs
- analyzers/tests/SonarAnalyzer.UnitTest/LiveVariableAnalysis/RoslynLiveVariableAnalysisTest.TryCatchFinally.cs
- analyzers/tests/SonarAnalyzer.UnitTest/LiveVariableAnalysis/RoslynLiveVariableAnalysisTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DeadStores.RoslynCfg.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.SpinLock.cs
Fixes #5522
The `Successors` and `Predecessors` method pair became too complex and need bigger refactoring that I'll try to do in another PR. This change is just a focused update to fix the problem.
The key idea is that we need to join nested `finally` blocks directly in both directions (predecessors and successors), in case there are not other blocks and instructions between them.
```
try
{
try
{
}
finally
{
// Successors(of this block) needs to be connected directly to the next finally
}
// Nothing here
}
finally
{
// Prececessors(of this block) needs to be connected directly to the previous finally
}
```
> Fix S2222 FP: SpinLock.TryEnter followed by nested finally regions

- analyzers/src/SonarAnalyzer.CSharp/Facade/CSharpFacade.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/Utilities/SymbolReferenceAnalyzer.cs
- analyzers/src/SonarAnalyzer.Common/Facade/ILanguageFacade.cs
- analyzers/src/SonarAnalyzer.Common/Rules/Utilities/SymbolReferenceAnalyzerBase.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Facade/VisualBasicFacade.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Rules/Utilities/SymbolReferenceAnalyzer.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/SymbolReferenceAnalyzerTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Utilities/SymbolReferenceAnalyzer/Method.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Utilities/SymbolReferenceAnalyzer/Method.vb
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Utilities/SymbolReferenceAnalyzer/MissingDeclaration.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Utilities/SymbolReferenceAnalyzer/Property.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Utilities/SymbolReferenceAnalyzer/Property.vb
Rewrite the analyzer to work as much as possible at the syntax level by retrieving symbols only when strictly necessary.
Tested this rule on:
- akka.net - before: 0:02:49, after: 0:01:32, improvement: 45.94%
- efcore - before: 0:01:39, after: 0:01:04, improvement: 35.19%
- nodatime - before: 0:00:06, after:	0:00:04, improvement: 26.02%
Part of #4220
> Improve performance for SymbolReferenceAnalyzer

- analyzers/src/SonarAnalyzer.CSharp/Rules/DangerousGetHandleShouldNotBeCalled.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/DoNotCallExitMethods.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/DoNotCallGCSuppressFinalize.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/DoNotCallMethodsCsharpBase.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/NormalizeStringsToUppercase.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/ThreadResumeOrSuspendShouldNotBeCalled.cs
- analyzers/src/SonarAnalyzer.Common/Rules/DoNotCallMethodsBase.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Rules/DangerousGetHandleShouldNotBeCalled.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Rules/ThreadResumeOrSuspendShouldNotBeCalled.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DoNotCallExitMethods.CSharp9.cs
Fixes #3854
Fixes #4349
The testing of the performance included 4 runs each on 3 different projects. The sum of the times are the following:
akka 75.353 -> 21.673
efcore 116.028 -> 19.791
noda 18.35 -> 1.837
> Improve the performance of rules inheriting from DoNotCallMethodsBase

- analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/SymbolHelper.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/UnitTestHelper.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/TestClassShouldHaveTestMethodTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/TestClassShouldHaveTestMethod.NUnit3.cs
> Fix S2187 FP: Support test attributes deriving from `ITestBuilder` in NUnit

- analyzers/src/SonarAnalyzer.CSharp/Rules/RedundantDeclaration.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/SetLocaleForDataTypes.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/UnusedPrivateMember.cs
- analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/RequestsWithExcessiveLengthBase.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/SetLocaleForDataTypesTest.cs
As for the other performance tests I did 4 runs on Akka, EfCore and Noda projects.  The sum of the execution time of the 3 rules changed, RequestsWithExcessiveLength, SetLocaleForDataTypes and UnusedPrivateMember with and without the changes are the following:
akka:  28.47 -> 32.893
efcore: 36.698 -> 37.362
noda: 15.455 -> 13.409
> Remove usage of concurrent collections from rules

- analyzers/src/SonarAnalyzer.CSharp/Rules/ValueTypeShouldImplementIEquatable.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/ValueTypeShouldImplementIEquatableTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ValueTypeShouldImplementIEquatable.CSharp10.cs
[S3898](https://sonarsource.github.io/rspec/#/rspec/S3898) Implement 'IEquatable<T>' in value type '{0}'.
Record struct was marked as a false negative, but because records automatically implement IEquatable this was actually wrong. I marked it as compliant.
> S3898: Add support for record struct

- sonar-csharp-plugin/src/main/java/org/sonar/plugins/csharp/CSharpPlugin.java
- sonar-csharp-plugin/src/test/java/org/sonar/plugins/csharp/CSharpPluginTest.java
- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/AnalysisWarningsSensor.java
- sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/AnalysisWarningsSensorTest.java
- sonar-dotnet-shared-library/src/test/resources/analysisWarnings/AnalysisWarnings.AutoScan.json
- sonar-dotnet-shared-library/src/test/resources/analysisWarnings/AnalysisWarnings.Scanner.json
- sonar-vbnet-plugin/src/main/java/org/sonar/plugins/vbnet/VbNetPlugin.java
- sonar-vbnet-plugin/src/test/java/org/sonar/plugins/vbnet/VbNetPluginTest.java
This sensor is responsible for importing all the warnings raised by the auto-scan analysis or S4NET and pushing them to SonarCloud/SonarQube.
We expect the files to have the following format: `.sonarqube\out\AnalysisWarnings.<product>.json`.
e.g.
```
.sonarqube\out\AnalysisWarnings.AutoScan.json
.sonarqube\out\AnalysisWarnings.Scanner.json
```
> Implement the AnalysisWarningsSensor

- analyzers/src/SonarAnalyzer.CSharp/Rules/RedundantInheritanceList.cs
- analyzers/src/SonarAnalyzer.Common/Common/MultiValueDictionary.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/RedundantInheritanceListTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundantInheritanceList.CSharp10.Fixed.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundantInheritanceList.CSharp10.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundantInheritanceList.Fixed.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundantInheritanceList.cs
This PR includes a custom `ILookup` [implementation ](https://github.com/SonarSource/sonar-dotnet/pull/5606/files#diff-9837ebf1cf25978507ec848d843b6111fcdd1bd439a16db052842099a6cd055cR102-R157). It replaces the MultiValueDictionary used here. There is nothing wrong with MultiValueDictionary and it is used in multiple other places too. `ILookup` is just better suited for the intent here. I implemented my own `ILookup` because the `ToLookup` extension method would have introduced a big overhead.
I don't think it is worth to keep my custom `Lookup` implementation, as it basically does the same as the existing MultiValueDictionary. I left it for the moment in case you see value in keeping it.
> S1939: Add support for record struct

- analyzers/src/SonarAnalyzer.CSharp/Rules/TypeNamesShouldNotMatchNamespaces.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/TypeNamesShouldNotMatchNamespacesTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/TypeNamesShouldNotMatchNamespaces.CSharp10.cs
~Blocked by ##5577 `CSharpFacade.Instance.Syntax.NodeIdentifier` should be replaced by a call to the C# syntax extension method.~
> S4041: Add support for record structs

- analyzers/src/SonarAnalyzer.Utilities/RuleDescriptors/RuleDetail.cs
- analyzers/src/SonarAnalyzer.Utilities/RuleDetailBuilder.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Common/RuleTest.cs
Property `RuleDetail.CodeFixTitles` is very difficult to generate. And it was not used at all.
This is part of bigger cleanup around RSPEC handling.
> Remove RuleDetail.CodeFixTitles

- analyzers/src/SonarAnalyzer.Utilities/RuleDetailBuilder.cs
- analyzers/src/SonarAnalyzer.Utilities/RuleFinder.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Common/RuleFinderTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Common/RuleTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Common/SecurityHotspotTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/PackagingTests/GeneratedResourcesTest.cs
Mechanical refactoring of RuleFinder class. This is a prerequisite for further structure cleanups.
It's internal state was always recomputed from something static, so I made the whole class static to avoid this. And did some cleanup about its weird usage and method structure.
> Refactor RuleFinder

- scripts/rspec/rspec.ps1
This was used to clear .vs cache after creating new files and updating resources. 
It is not needed in VS2022.
It often fails because of locked files.
> Do not delete .vs from rspec.ps1

- analyzers/src/SonarAnalyzer.CSharp/Extensions/AttributeSyntaxExtensions.cs
- analyzers/src/SonarAnalyzer.CSharp/Extensions/ObjectCreationExpressionSyntaxExtensions.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/CertificateValidationCheck.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/CollectionsShouldImplementGenericInterface.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/CompareNaN.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/MethodParameterMissingOptionalCodeFix.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/NonFlagsEnumInBitwiseOperationCodeFix.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/OptionalParameterWithDefaultValueCodeFix.cs
- analyzers/src/SonarAnalyzer.CSharp/Wrappers/ObjectCreationFactory.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/KnownMethods.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.Implementation.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/MemberDescriptor.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/TypeHelper.cs
- analyzers/src/SonarAnalyzer.Common/Rules/CertificateValidationCheckBase.cs
- analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/UsingCookiesBase.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Metrics/VisualBasicExecutableLinesMetric.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Rules/CertificateValidationCheck.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Helpers/KnownTypeTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Helpers/TypeHelperTest.cs
> Reimplement KnownType matching to avoid string generation and calling `ToDisplayString`

- analyzers/src/SonarAnalyzer.Common/Helpers/UnitTestHelper.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/TestMethodShouldContainAssertion.NUnit.cs
Named argument `ExpectedResult` was only taken into account for `[TestCase]`, not `[Test]`. Has been changed.
See: #5702
> Fix false positive S2699: NUnit test method does not regonize named argument ExpectedResult

- analyzers/src/SonarAnalyzer.Common/Helpers/HashCode.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/ExceptionState.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/ProgramState.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ExceptionStateTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ProgramStateTest.cs
Related to #5710, prerequisite for #5718
We need to track what kind of exception are we dealing with.
We will need this to know that we're on an exception-thrown path for nested scenario.
```C#
try{
try{
throw new Exception(); // Persist state, that we're in an exception
} finally {
// After this, we need to skip DoSomething()
}
DoSomething();
} finally {
// And continue with this
}
```
> Add ExceptionState to ProgramState

- analyzers/src/SonarAnalyzer.CFG/Extensions/ControlFlowRegionExtensions.cs
- analyzers/src/SonarAnalyzer.CFG/LiveVariableAnalysis/RoslynLiveVariableAnalysis.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Loops.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.TryCatchFinally.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Monitor.TryCatch.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.SpinLock.cs
Related to #5710 
```C#
try
{
try
{
CanThrow()
}
finally
{
// This is processed in happy-path and exception-path
// Happy-path continues to DoSomething
// Exception-path continues to outer finally
}
DoSomething() // This is process only in happy-path
}
finally
{
// This is processed in happy-path and exception-path
// Happy-path continues to DoSomethingElse
// Exception-path reaches exit
}
DoSomethingElse() // This is process only in happy-path
```
> Support exception handling for finally regions in SE

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/ProgramState.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ExplodedNodeTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ProgramStateTest.cs
This helps a lot when debugging the SE flow:
```
Console.WriteLine(current);
```
Previously, empty program state did not have EOL at the end, while all non-empty states had. That made tracking of exploded nodes irregular and harder to follow.
This PR ensures that all results of `ToString()` of a `ProgramState` always ends with EOL. This change is not important for `ProgramState` itself, but for usages, mainly in `ExplodedNode.ToString()`
> ProgramState.ToString always ends with EOL

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/ProgramState.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ProgramStateTest.Exception.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.TryCatchFinally.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Mutex.NetFx.cs
Related to #5710 
`ProgramState.Exception` needs to be cleared at the end of `catch` block because it is handled. Whatever follows the `catch` block is happy path again.
> Clear exception after catch block in SE

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/ProgramState.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.TryCatchFinally.cs
Related to #5710, follow up of #5745
This PR fixes problem with clearing exception when transitioning between blocks inside try.
```
try
{
}
catch
{
try  // Exception was cleared on entry to this block and it shouldn't.
{
}
catch  
{
}
}
```
It also fixes an issue when branch out of `catch` is starting inside `LocalLifeTime` region.
The problem with exiting nested catch will be fixed in another PR.
> Preserve exception on entry into nested try in SE

- analyzers/src/SonarAnalyzer.CSharp/Extensions/AssignmentExpressionSyntaxExtensions.cs
- analyzers/src/SonarAnalyzer.CSharp/Extensions/TupleExpressionSyntaxExtensions.cs
- analyzers/src/SonarAnalyzer.CSharp/Extensions/VariableDesignationSyntaxWrapperExtensions.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Extensions/AssignmentExpressionSyntaxExtensionsTests.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Extensions/TupleExpressionSyntaxExtensionsTests.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Extensions/VariableDesignationSyntaxWrapperTests.cs
This PR will conflict with #5756 as both add the same file(s).
> Add extension methods for tuple flattening and assignment target handling

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/ProgramState.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ProgramStateTest.Exception.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ProgramStateTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.TryCatchFinally.cs
Related to #5710, follow up of #5745
```
try
{
CanThrow_First(); // Do not preserve previous exception, like in Finally for example
}
catch
{
try
{
CanThrow_Second(); // Do not clear information about CanThrow_First(), add info about CanThrow_Second
}
catch
{
}   // Here, only CanThrow_Second is cleared. Returning CanThrow_First to the throne
} // Here, CanThrow_First is cleared as before
```
> Preserve exception in nested catch in SE

- analyzers/src/SonarAnalyzer.CFG/CfgSerializer/CfgSerializer.RoslynCfgWalker.cs
- analyzers/src/SonarAnalyzer.CFG/CfgSerializer/DotWriter.cs
- analyzers/tests/SonarAnalyzer.UnitTest/CFG/Roslyn/RoslynCfgSerializerTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Helpers/DotWriterTest.cs
Previously, scenario like this
```
try { }
catch { }
try { }
catch { }
```
used a common `TryRegion` and  `CatchRegion` - that was wrong. We need to serialize them to separate regions like this, see http://viz-js.com/
```
digraph "RoslynCfg" {
subgraph "cluster_1" {
label = "TryAndCatch region"
subgraph "cluster_2" {
label = "Try region"
cfg0_block1 [shape=record label="{BLOCK #1}"]
}
subgraph "cluster_3" {
label = "Catch region: object"
cfg0_block2 [shape=record label="{BLOCK #2}"]
}
}
subgraph "cluster_4" {
label = "TryAndCatch region"
subgraph "cluster_5" {
label = "Try region"
cfg0_block3 [shape=record label="{BLOCK #3}"]
}
subgraph "cluster_6" {
label = "Catch region: object"
cfg0_block4 [shape=record label="{BLOCK #4}"]
}
}
cfg0_block0 [shape=record label="{ENTRY #0}"]
cfg0_block5 …
```
> Make subgraphs unique in RoslynCfgSerializer

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Extensions/IOperationExtensions.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.ExceptionCandidate.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.TryCatchFinally.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SymbolicExecution/SETestContext.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SymbolicExecution/ValidatorTestCheck.cs
Related to #5710
Remaining tasks after this PR:
- [IEndOperation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.operations.iendoperation?view=roslyn-dotnet-4.2.0) (`'End' statement cannot be used in class library projects.`)
- use specific exceptions instead of the unknown where possible (e.g. NullReferenceException for member reference)
- update testing infrastructure to run tests on C# 8 and add handling for indexes and ranges
- exception constructors should not throw
> Implement ExceptionCandidate

- analyzers/src/SonarAnalyzer.RuleDescriptorGenerator/Descriptors/Rule.cs
- analyzers/src/SonarAnalyzer.RuleDescriptorGenerator/Descriptors/RuleParameter.cs
- analyzers/src/SonarAnalyzer.RuleDescriptorGenerator/Program.cs
Prerequisite for #5590 
The project state is rather ugly, as most of it will be eventually removed and target framework will be updated to `net6`. For this stage, we need to preserve both functionalities.
Reflection is used intentionally so we can get rid of the dependency on the analyzer DLLs.
> Serialize rule metadata to Json

- sonar-csharp-plugin/pom.xml
- sonar-vbnet-plugin/pom.xml
Prerequisite for #5590
We need to generate the `Parameters.json` during the Java build. 
We also need to add HTML files as resources.
All JSON files are already part of the resources.
Products of this change can be found in 
```
sonar-csharp-plugin\target\analyzer\org\sonar\plugins\csharp\
sonar-vbnet-plugin\target\analyzer\org\sonar\plugins\vbnet\
```
> Add all rspec resources to Java build

- analyzers/src/SonarAnalyzer.CSharp/Rules/TestMethodShouldContainAssertion.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/TestMethodShouldContainAssertion.NUnit.cs
Fixes #5826 
KnownAssertions changed to dictionary of <string, KnownTypes[]> in favor "Received" and "ReceivedWithAnyArgs" is used by multiple types
> Fix S2699 FP: When using NSubstitute Received with quantity

- its/pom.xml
- its/src/test/java/com/sonar/it/shared/TestUtils.java
as part of our release process: https://xtranet-sonarsource.atlassian.net/wiki/spaces/SSG/pages/1181769/Scanner+for+.NET+Release+Process
we want to be using the latest S4NET version in all our ITs
> bump s4net version to 5.7.2

- analyzers/src/SonarAnalyzer.Common/Common/PropertyType.cs
- analyzers/src/SonarAnalyzer.RuleDescriptorGenerator/Descriptors/RuleParameter.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Common/RuleDetailTest.cs
Related to #5590 
Unused enum values serialized from .NET side are not supported by sonar-plugin-api on the server side.
> Remove unsupported members from PropertyType

- sonar-csharp-plugin/pom.xml
- sonar-vbnet-plugin/pom.xml
These profiles are leftover form days, where there used to exist two profiles. `download-analyzer` profile was removed in #4681
Since there's a single profile that is used every time on all dev machines and CI, there's no reason to have those steps extracted into a profile. That plugin can be moved to other plugins.
> Remove maven profile 'local-analyzer'

- analyzers/src/SonarAnalyzer.Common/Common/RuleDescriptor.cs
- analyzers/src/SonarAnalyzer.SourceGenerators/RuleCatalogGenerator.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Common/RuleTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Helpers/DiagnosticDescriptorBuilderTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Helpers/RuleCatalogTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/PackagingTests/RuleTypeTest.cs
Cleanup after #5590
This is a prerequisite for removing resx files. We need to move remaining assertions from ResourceManager to RuleCatalog.
> Move RSPEC related UTs to RuleCatalog

- scripts/rspec/rspec-templates/Rule.Base.cs
- scripts/rspec/rspec-templates/Rule.CS.cs
- scripts/rspec/rspec-templates/Rule.VB.cs
- scripts/rspec/rspec-templates/Test.CS.cs
- scripts/rspec/rspec-templates/Test.VB.cs
- scripts/rspec/rspec-templates/TestMethod.VB.cs
- scripts/rspec/rspec.ps1
Cleanup after #5590 
Changes:
* Removed `DiagnosticDescriptorBuilder.GetDescriptor` - will be deleted
* Using file scope namespaces
* `SonarDiagnosticAnalyzer<TSyntaxKind>` base class to lower boiler plate noise
> Use file scoped namespaces in rspec template

- analyzers/src/SonarAnalyzer.CSharp/Helpers/DescriptorFactory.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/ClearTextProtocolsAreSensitive.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/DisablingCsrfProtection.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/DoNotUseRandom.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/InsecureDeserialization.cs
- analyzers/src/SonarAnalyzer.Common/Common/RuleDescriptor.cs
- analyzers/src/SonarAnalyzer.Common/DiagnosticAnalyzer/DiagnosticDescriptorFactory.cs
- analyzers/src/SonarAnalyzer.Common/DiagnosticAnalyzer/TrackerHotspotDiagnosticAnalyzer.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/SonarAnalysisContext.cs
- analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/DisablingRequestValidationBase.cs
- analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/DoNotHardcodeCredentialsBase.cs
- analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/HardcodedIpAddressBase.cs
- analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/LooseFilePermissionsBase.cs
- analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/PubliclyWritableDirectoriesBase.cs
- analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/RequestsWithExcessiveLengthBase.cs
- analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/UsingNonstandardCryptographyBase.cs
- analyzers/src/SonarAnalyzer.Common/Rules/Utilities/UtilityAnalyzerBase.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Helpers/DescriptorFactory.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Common/RuleTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Helpers/DiagnosticDescriptorFactoryTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Helpers/SonarAnalysisContextTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/SymbolicExecutionRunnerTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SymbolicExecution/AssignmentRuleCheck.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SymbolicExecution/BinaryRuleCheck.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Tests/OldVerifierTest.cs
Cleanup after #5590 
Explicit `WithNotConfugrable` declaration was redundant in the code base. Rule type can be read from rspec.
> Remove need for explicit WithNotConfigurable call

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.CSharp10.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.CSharp6.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.CSharp7.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.CSharp8.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.CSharp9.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.cs
The first part of #5862
This only copies the test files and prepares these for the new CFG by replacing "Noncompliant" with "FIXME". The new test files are not integrated in the test infrastructure. This follows the approach taken by the "LocksReleasedAllPaths" analyzer.
To see the replacement of "Noncompliant" with "FIXME", a commit by commit review should be done.
> S2259 Copy test files for Roslyn CFG

- pom.xml
- sonar-csharp-plugin/pom.xml
- sonar-dotnet-shared-library/pom.xml
- sonar-vbnet-plugin/pom.xml
Related to https://discuss.sonarsource.com/t/sonar-plugin-api-relocated-in-maven-central/11143
> Use the latest released version of sonar-plugin-api

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
Avoiding repetitive syntax, the list will grow. Typecasts didn't work, unfortunatelly.
> Simplify RoslynSymbolicExecution.ProcessOperation

- analyzers/src/SonarAnalyzer.Common/Rules/CognitiveComplexityBase.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Common/RuleTest.cs
> Fix S3776 configuration: Cognitive complexity threshold for property is not registered properly

- analyzers/rspec/vbnet/S4225_vb.net.html
- analyzers/rspec/vbnet/S4225_vb.net.json
- analyzers/src/SonarAnalyzer.CSharp/Rules/ExtensionMethodShouldNotExtendObject.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- analyzers/src/SonarAnalyzer.Common/Rules/ExtensionMethodShouldNotExtendObjectBase.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Extensions/AttributeSyntaxExtensions.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Helpers/VisualBasicSyntaxHelper.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Rules/ExtensionMethodShouldNotExtendObject.cs
- analyzers/tests/SonarAnalyzer.UnitTest/PackagingTests/RuleTypeMappingVB.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/ExtensionMethodShouldNotExtendObjectTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ExtensionMethodShouldNotExtendObject.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ExtensionMethodShouldNotExtendObject.vb
Fixes #5823
Originally implemented via #763. [Documentation update](https://github.com/SonarSource/rspec/pull/1063) pending.
> Rule S4225: Extension method should not extend on object - for VB.NET

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DeadStores.RoslynCfg.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/VariableUnused.cs
Add the same test case for an unused variable to the S1854 (DeadStores) and S1481(VariableUnsused) for the sake of showing that it's handled by one of the two rules.
> Add UT test case to S1854 and S1481 for unused variable.

- analyzers/rspec/vbnet/S4060_vb.net.html
- analyzers/rspec/vbnet/S4060_vb.net.json
- analyzers/src/SonarAnalyzer.CSharp/Facade/CSharpSyntaxKindFacade.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/AvoidUnsealedAttributes.cs
- analyzers/src/SonarAnalyzer.Common/Facade/ISyntaxKindFacade.cs
- analyzers/src/SonarAnalyzer.Common/Rules/AvoidUnsealedAttributesBase.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Facade/VisualBasicSyntaxKindFacade.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Helpers/VisualBasicSyntaxHelper.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Rules/AvoidUnsealedAttributes.cs
- analyzers/tests/SonarAnalyzer.UnitTest/PackagingTests/RuleTypeMappingVB.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/AvoidUnsealedAttributesTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/AvoidUnsealedAttributes.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/AvoidUnsealedAttributes.vb
See #501
The .NET framework class library provides methods for retrieving custom attributes. Sealing the attribute eliminates the search through the inheritance hierarchy, and can improve performance.
This rule raises an issue when a public type inherits from System.Attribute, is not abstract, and is not sealed.
``` VB
Namespace MyLibrary 
<AttributeUsage(AttributeTargets.Class)>
Public Class MyAttribute ' Noncompliant
Inherits Attribute 
Public Sub New(name as String) 
Value = val
End Sub
Public Readonly Property Value as String
End Class
End Namespace
```
``` VB
Namespace MyLibrary 
<AttributeUsage(AttributeTargets.Class)>
Public MustInherit Class MyAttribute ' Noncompliant
Inherits Attribute 
Public Sub New(val as String) 
Value = val 
End Sub
Public Readonly Property Value as String …
```
> Implement S4060 - Avoid unsealed attributes - for VB.NET

- sonar-csharp-plugin/src/test/java/org/sonar/plugins/csharp/CSharpSonarRulesDefinitionTest.java
- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/AbstractRulesDefinition.java
- sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/AbstractRulesDefinitionTest.java
- sonar-dotnet-shared-library/src/test/resources/AbstractRulesDefinitionTest/Rules.json
- sonar-dotnet-shared-library/src/test/resources/AbstractRulesDefinitionTest/S1115.html
- sonar-dotnet-shared-library/src/test/resources/AbstractRulesDefinitionTest/S1115.json
- sonar-dotnet-shared-library/src/test/resources/AbstractRulesDefinitionTest/S1116.html
- sonar-dotnet-shared-library/src/test/resources/AbstractRulesDefinitionTest/S1116.json
> Add support for PCI DSS 3.2 and 4.0, and ASVS 4.0

- analyzers/tests/SonarAnalyzer.UnitTest/Metrics/CSharpExecutableLinesMetricTest.cs
Declarations do not count as executable lines and with `const string` we cannot have any kind of operation that counts as an executable line.
> Delete test for CSharpExecutableLinesMetric that is not useful.

- analyzers/src/SonarAnalyzer.CSharp/Rules/ImplementIDisposableCorrectly.cs
CallsSuppressFinalize and CallsVirtualDispose had some flaws in it:
* The name of the invoked method was not checked syntactically before semantic
* Both called `HasArgumentValues` which was not using `Language.MethodParameterLookup` and therefore was not working properly with named arguments.
* Both were relying on "ToString()" on syntax nodes much too often.
> S3881: Improve invocation detection

- azure-pipelines.yml
Use `strategy` and `matrix` as in the runJavaIntegrationTests job.
This PR changes the name of the checks:
*  .NET 4.8 UTs -> .NET UTs Net48
*  .NET 6 UTs -> .NET UTs Net60
Therefore the *required checks* for PRs need to be updated too.
> AZP: Combine runUnitTestsJobNet48 and runUnitTestsJobNet6

- docs/contributing-analyzer.md
Improve the pre-requirements section the documentation with respect to
* VS 2022
* Locations of artifacts required (e.g. `orchestrator.properties` or `rule-api.jar`)
> Improve contributing-analyzer.md

- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SnippetCompiler.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Tests/SnippetCompilerTest.cs
> Add support for filescoped namespaces to SnippetCompiler.GetNamespaceSymbol

- analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/ClearTextProtocolsAreSensitive.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/ClearTextProtocolsAreSensitive.CSharp10.cs
> Fix FN S5332: No issue is raised if an insecure protocol is used as part of a constant interpolated string

- azure-pipelines.yml
.gitignored directories like `/bin/net46/` are randomly laying around on VMs from previous builds and survive `git checkout`.
> CI: Clean workspace for each job

- analyzers/src/SonarAnalyzer.CSharp/Rules/ForeachLoopExplicitConversionCodeFix.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/ForeachLoopExplicitConversionTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ForeachLoopExplicitConversion.CSharp10.Fixed.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ForeachLoopExplicitConversion.CSharp10.cs
> Fix CodeFix S3217: Using directives are not moved to the closest namespace when this is file scoped

- pom.xml
Burgr is failing releasability with:
```
FAILED
ParentPOM
update your parent from to 62.0.180 to 63.0.187
```
This PR is updating the version.
> Update parent POM from 62.0.180 to 63.0.187

- analyzers/src/SonarAnalyzer.CSharp/Extensions/BaseMethodDeclarationSyntaxExtensions.cs
- analyzers/src/SonarAnalyzer.CSharp/Helpers/CSharpSyntaxHelper.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/CloudNative/AzureFunctionsCatchExceptions.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/PartialMethodNoImplementation.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Helpers/BaseMethodDeclarationSyntaxExtensionsTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CloudNative/AzureFunctionsCatchExceptions.cs
Fixes #5995
Based on #6016
Root cause was
* method attributes were visited by the walker -> only body is visited now
* `nameof()` was treated as an invocation -> check for `IsNameOf` added
> Fix FP S6421: Don't raise issue for Azure Functions with already wrapped body in try/catch block.

- analyzers/src/SonarAnalyzer.CFG/SonarAnalyzer.CFG.csproj
- analyzers/src/SonarAnalyzer.CSharp/SonarAnalyzer.CSharp.csproj
- analyzers/src/SonarAnalyzer.Common/SonarAnalyzer.Common.csproj
- analyzers/src/SonarAnalyzer.VisualBasic/SonarAnalyzer.VisualBasic.csproj
- analyzers/tests/SonarAnalyzer.UnitTest/Extensions/ITupleOperationWrapperExtensionsTests.cs
- azure-pipelines.yml
We do not use `netstandard2.0` builds and we do not ship them. So we don't need to wait for them to be built and analyzed.
With this change, we also unit test the build that we ship.
`Build and package` is 41% faster. Making every build 0:47 shorter in average.
`.NET Analysis / Run .Net code analysis - before` is 28% faster (0:40), but it doesn't help with total CI run too much yet, because Java ITs take longer anyway. And we already know how to speed them up.
**Build and package - before**
Min: 1:07
Max: 3:30
Average: 1:52
_Side note:_ Why the hell do we have such volatile differences on the same VMs anyway?
**Build and package - before**
Min: 0:52
Max: 1:47
Average: 1:05
**.NET Analysis / Run .Net code analysis - before**
Min: 2:11
Max: 2:58
Average: 2:25
**.NET Analysis / Run .Net code …
> Do not build netstandard2.0

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.cs
This adds the reproducer for this [community post](https://community.sonarsource.com/t/s2259-false-positive-null-pointers-should-not-be-dereferenced/69959/3).
The new engine is handling this case gracefully. The issue is solved once we ship the new implementation.
> FP S2259: Reproducer: Null check with two variables

- analyzers/src/SonarAnalyzer.CFG/ShimLayer/UnaryOperatorKind.cs
- analyzers/src/SonarAnalyzer.ShimLayer.CodeGeneration/OperationLightupGenerator.cs
Prerequisite for #6030
To validate that this works:
- pull
- rebuild
- restart VS
- place this somewhere in `RoslynSymbolicExecution.cs`:
```
public void Something(IUnaryOperationWrapper unary)
{
UnaryOperatorKind kind = unary.OperatorKind;
}
```
It should compile. Before, it would complaint that `object` cannot be converted to `UnaryOperatorKind`
> Add UnaryOperatorKind to ShimLayer

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/LocksReleasedAllPathsBase.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/NullPointerDereferenceBase.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SymbolicContext.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Monitor.Conditions.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Monitor.Conditions.vb
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Monitor.Linear.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Monitor.Linear.vb
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Monitor.TryEnter.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Monitor.TryEnter.vb
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Mutex.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Mutex.vb
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.ReaderWriterLock.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.ReaderWriterLock.vb
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.ReaderWriterLockSlim.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.ReaderWriterLockSlim.vb
Fixes #6048
Bunch of cases from `.Linear.` was moved to `.Condition.` as they were meant to demonstrate that we support the signature of the method.
Same idea is for those `if lock then nothing else unlock end if` - they demonstrate the method signature and not the flow
> Fix S2222 FP: Consider symbols released only if they were previously held

- analyzers/its/expected/Ember-MM/Ember.Plugins-{9496C697-5AFD-4813-AEDC-AF33FACEADF0}-S1210.json
- analyzers/its/expected/Nancy/Nancy--net452-S1210.json
- analyzers/its/expected/Nancy/Nancy--netstandard2.0-S1210.json
- analyzers/its/expected/akka.net/Akka--netstandard2.0-S1210.json
- analyzers/its/expected/akka.net/Akka.Cluster--netstandard2.0-S1210.json
- analyzers/its/expected/akka.net/Akka.DistributedData--netstandard2.0-S1210.json
- analyzers/its/expected/akka.net/Akka.MultiNodeTestRunner.Shared--netstandard2.0-S1210.json
- analyzers/its/expected/akka.net/Akka.Persistence.Query--netstandard2.0-S1210.json
- analyzers/its/expected/akka.net/Akka.Tests.Performance--netcoreapp3.1-S2931.json
- analyzers/src/SonarAnalyzer.CSharp/Rules/ComparableInterfaceImplementation.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/DisposableMemberInNonDisposableClass.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/DisposableReturnedFromUsing.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/ForLoopCounterCondition.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/ImplementISerializableCorrectly.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/VirtualEventField.cs
- analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/DoNotHardcodeCredentialsBase.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ComparableInterfaceImplementation.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DisposableMemberInNonDisposableClass.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DisposableReturnedFromUsing.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/DoNotHardcodeCredentials_DefaultValues.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/DoNotHardcodeCredentials_DefaultValues.vb
> Use serial comma in error messages

- analyzers/its/expected/Ember-MM/Ember Media Manager-{9B57D3AB-AF12-4012-B945-284C2448DC81}-S2259.json
- analyzers/its/expected/Ember-MM/EmberAPI-{208AA35E-C6AE-4D2D-A9DD-B6EFD19A4279}-S2259.json
- analyzers/its/expected/Ember-MM/generic.EmberCore.NMT-{84B2143A-D04F-4262-923D-21AEDF86E2B7}-S2259.json
- analyzers/its/expected/Nancy/Nancy--net452-S2259.json
- analyzers/its/expected/Nancy/Nancy--netstandard2.0-S2259.json
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Constraints/ObjectConstraint.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Checks/InvocationCheck.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Extensions/IOperationExtensions.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/ProgramState.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ProgramStateTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Invocation.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.cs
Part of #5973
This seems similar to supporting [`[NotNullWhen]`](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/nullable-analysis#conditional-post-conditions-notnullwhen-maybenullwhen-and-notnullifnotnull), but there is a twist to this one. While NotNullWhen just sets constraints on branching, this one actually explodes the graph to find NREs in the "true" path.
> SE: Support string.IsNullOrEmpty

- analyzers/tests/SonarAnalyzer.UnitTest/Rules/UnchangedLocalVariablesShouldBeConstTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnchangedLocalVariablesShouldBeConst.CSharp7.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnchangedLocalVariablesShouldBeConst.cs
master CI was failing, because it was executing a test with C#10, which was assumed to be executed only with lang versions 7 to 9. I moved the test to a new test file.
Test failure:
https://dev.azure.com/sonarsource/DotNetTeam%20Project/_build/results?buildId=53655&view=ms.vss-test-web.build-test-results-tab&runId=1201082&resultId=101432&paneView=debug
> S3353: Move test case

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.CSharp8.cs
Related to #6070
Accepts it as TP. The `??` is visited because of the type mismatch, or because the original value was null.
>as check with null-coalescing sets misleading null constraint in the Null case => graph as Flow<TIn, TOut, TMat> ?? new Flow<TIn, TOut, TMat>(graph.Module); sources\akka.net\src\core\Akka.Streams\Dsl\Flow.cs
> SE: Add repro from ITs

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Checks/ConstantCheck.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.CSharp8.cs
Fixes
```
CSC : error AD0001: Analyzer 'SonarAnalyzer.Rules.CSharp.SymbolicExecutionRunner' threw an exception of type 'SonarAnalyzer.SymbolicExecution.SymbolicExecutionException' with message 'Error processing method: get_Use 
Method file: C:\Project\src\System.ServiceModel.Primitives\ref\System.ServiceModel.Primitives.cs 
Method line: 845,43 
Inner exception: System.NullReferenceException: Object reference not set to an instance of an object. 
at SonarAnalyzer.SymbolicExecution.Roslyn.Checks.ConstantCheck.ConvertedType(IOperation operation) 
at SonarAnalyzer.SymbolicExecution.Roslyn.Checks.ConstantCheck.ConstraintFromConstantValue(IOperationWrapperSonar operation) 
at SonarAnalyzer.SymbolicExecution.Roslyn.Checks.ConstantCheck.PreProcessSimple(SymbolicContext context) 
at …
```
> SE: Fix S2259 AD0001 on ConstantCheck

- analyzers/tests/SonarAnalyzer.UnitTest/MetadataReferences/NuGetMetadataReference.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/Hotspots/ConfiguringLoggersTest.cs
Tries to fix a CI error
```
Test method SonarAnalyzer.UnitTest.Rules.ConfiguringLoggersTest.ConfiguringLoggers_Serilog_CS threw exception:
SonarAnalyzer.UnitTest.TestFramework.UnexpectedDiagnosticException: CSharp7: Unexpected build error [CS1705]: Assembly 'Serilog' with identity 'Serilog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10' uses 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' which has a higher version than referenced assembly 'netstandard' with identity 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' on line 1
```
https://dev.azure.com/sonarsource/DotNetTeam%20Project/_build/results?buildId=53933&view=ms.vss-test-web.build-test-results-tab&runId=1202772&resultId=102266&paneView=debug
> Fix serilog build error in CI

- analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/LocksReleasedAllPaths.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/LocksReleasedAllPathsBase.cs
- analyzers/src/SonarAnalyzer.VisualBasic/SymbolicExecution/Roslyn/LocksReleasedAllPaths.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Monitor.TryCatch.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Monitor.TryCatch.vb
S2222 did not support methods containing `throw`. These are now supported as SE understands different flows containing `try/catch` scenarios
> Fix S2222 FN: Support methods with throw

- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Invocation.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SymbolicExecution/SETestContext.cs
Re-producer for an issue found during [peach validation](https://peach.sonarsource.com/project/issues?issues=AYMfpuzBBnZofnLJMrx3&open=AYMfpuzBBnZofnLJMrx3&id=dnn)
If the invocation which resets the state has an argument expression that branches, some states escape.
Reproducer for #6103
see also #6065
> S2259: Add FP repro for #6103

- analyzers/its/expected/Net5/Net5--net5.0-S1067.json
- analyzers/its/expected/Net5/Net5--net5.0-S1301.json
- analyzers/its/expected/Net5/Net5--net5.0-S1541.json
- analyzers/its/expected/Net5/Net5--net5.0-S3532.json
- analyzers/its/sources/Net5/Net5/S4201.cs
The Net5.sln in the analyzer/ITs folder contains code that no longer compiles with a new version of the .Net SDK. This prevents an upgrade of the SDKs on peach. The error is:
Error CS8510: The pattern is unreachable. It has already been handled by a previous arm of the switch expression or it is impossible to match. in C:\Projects\sonar-dotnet\analyzers\its\sources\Net5\Net5\S4201.cs:31
The test case was removed.
See also https://github.com/SonarSource/peachee-languages/pull/287
> ITs: Net5 sln contains a compiler error for newer versions of the compiler

- analyzers/its/expected/Nancy/Nancy--net452-S2259.json
- analyzers/its/expected/Nancy/Nancy--netstandard2.0-S2259.json
- analyzers/its/expected/akka.net/Akka.Persistence.TCK--netstandard2.0-S2259.json
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Binary.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Unary.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Binary.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.cs
Prerequisite for #349
Learn Unary and Binary constraints directly from the operation. Until now, they were learned only when branching.
> SE: Learn Unary and Binary constraints directly from operation

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Pattern.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.PatternMatching.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.CSharp9.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SymbolicExecution/ValidatorTestCheck.cs
Prerequisite for #349
Learn IsPattern constraints directly from the operation. Until now, they were learned only when branching.
> SE: Learn IsPattern directly from operation

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IsNull.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.PatternMatching.cs
Prerequisite for #349
Learn IsNull constraints directly from the operation. Until now, they were learned only when branching.
This is a draft now, `Squash IsPattern` doesn't need a review.
> SE: Learn IsNull constraints directly from operation

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IsType.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
Prerequisite for #349
Learn IsType constraints directly from the operation. Until now, they were learned only when branching.
> SE: Learn IsType constraints directly from operation

- analyzers/src/SonarAnalyzer.Common/Helpers/TypeHelper.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Checks/ConstantCheck.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationDispatcher.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/DefaultValue.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Unary.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.PatternMatching.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.CSharp6.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.cs
Fixes #4537 
Fixes #4989 
Adds support for unary `Not` and `!` for nullable types with `null` value.
> SE: Set Null constraint to nullable types

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Invocation.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Invocation.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.CSharp6.cs
> Fix S2259 FP: object.Equals method recognizes null arguments

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationDispatcher.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/CaughtException.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Loops.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.TryCatchFinally.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.cs
Partially fixes #890
Note: To really fix #890, we need to be able to detect, that the loop is always entered. We can fix it for a `do/while` loop now, for all other loops it is assumed that there is one bypass flow.
> Improve S2259: Variables of caught exceptions are known to be NotNull

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IsPattern.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.PatternMatching.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.CSharp8.cs
> Fix S2259 FP: Should not report in switch expression after a null check

- analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/ExecutingSqlQueriesBase.cs
- analyzers/src/SonarAnalyzer.Common/Trackers/PropertyAccessTracker.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/ExecutingSqlQueries_Net46.cs
Part of #3905
[S3649.json](https://github.com/SonarSource/sonar-security/blob/master/config/src/main/resources/config/roslyn.sonaranalyzer.security.cs/sinks/S3649.json) lists any IDbCommand.CommandText assignments. We only support some specialized commands, like `OracleCommand` but not abstractions like `DbCommand` or `IDbCommand`. We can unify all existing `CommandText` assignments by checking if any `CommandText` implements `IDbCommand.CommandText`.
> Rule S2077: support for additional database libraries: IDbCommand.CommandText

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/ExecutingSqlQueries_EntityFrameworkCoreLatest.cs
Part of #3905
All EF core methods defined in [S3649.json](https://github.com/SonarSource/sonar-security/blob/master/config/src/main/resources/config/roslyn.sonaranalyzer.security.cs/sinks/S3649.json) for `Microsoft.EntityFrameworkCore` are supported already. A false FN was fixed.
> Fix S2077: Update false FN in unit tests for EF core

- azure-pipelines-external.yml
The production group is named `sonar-dotnet-variables-tmp`, we need to change that. 
To make the room for the rename, we need to first rename the external pipeline to something specific.
The external pipeline doesn't work anyway right now (too behind latest changes). I've raised the point on How we work already about it.
I've already renamed it on the [AZP side](https://dev.azure.com/sonarsource/DotNetTeam%20Project/_library?itemType=VariableGroups&view=VariableGroupView&variableGroupId=4&path=sonar-dotnet-variables-external).
Next steps will be to rename the production one.
> Rename external pipeline variable group

- analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/DoNotHardcodeCredentialsBase.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/DoNotHardcodeCredentials.DefaultValues.cs
https://www.rfc-editor.org/rfc/rfc3986#section-3.2.1 defines userInfo as
```
userinfo    = *( unreserved / pct-encoded / sub-delims / ":" )
```
therefore `:` is valid part of the password
```
var uri = "scheme://user:Pa$$word:With:Colons@domain.com";            // Noncompliant
```
> S2068: Support colon in uri password

- docs/contributing-plugin.md
Added the `-release` flag on the `dev-build.ps1` run instruction, since if the `-buildJava` flag is supplied, it needs the release DLLs.
> Added the -release flag in order to run dev-build.ps1

- analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/ExecutingSqlQueriesBase.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/Hotspots/ExecutingSqlQueriesTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/ExecutingSqlQueries.NHibernate.cs
> Rule S2077: support for additional database libraries: NHibernate

- analyzers/src/SonarAnalyzer.Common/Json/JsonWalker.cs
- analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/DoNotHardcodeCredentialsBase.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Json/JsonWalkerTest.cs
Follow up of #6187 and https://github.com/SonarSource/sonar-dotnet/pull/6187#discussion_r992050938
`Squash S206-appsettings` doesn't need a review
@pavel-mikula-sonarsource 
>Extract as reusable walker?
@martin-strecker-sonarsource 
>Sounds like a good idea to me. You could provide `IEnumerable<JsonNode> Descendants()` and `IEnumerable<KeyValuePair<string?, object>> DescendantValues()` extension methods for `JsonNode` on top of it.
>
>It's also easier to test the visitor for things like nested lists and the like.
@pavel-mikula-sonarsource 
>The walker is not as easy at it seemed. I'll leave it like this for now and we can discuss it here and do it in another PR.
The key problem is, that I need to visit `"value"`, but I do not want to visit `"value"` inside object `"key": "value"`. And …
> Extract JsonWalker

- analyzers/src/SonarAnalyzer.CSharp/Extensions/SyntaxNodeAnalysisContextExtensions.cs
- analyzers/src/SonarAnalyzer.CSharp/Extensions/SyntaxNodeExtensions.cs
- analyzers/src/SonarAnalyzer.CSharp/Helpers/CSharpSyntaxHelper.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/RedundantArgument.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/StringOperationWithoutCulture.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/SymbolicExecutionRunner.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- analyzers/src/SonarAnalyzer.Common/Rules/SymbolicExecutionRunnerBase.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Checks/ConstantCheck.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/ExceptionCandidate.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Extensions/IOperationExtensions.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Conversion.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Extensions/SyntaxNodeAnalysisContextExtensions.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Extensions/SyntaxNodeExtensions.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Rules/SymbolicExecution/SymbolicExecutionRunner.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Extensions/SyntaxNodeExtensionsTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/SymbolicExecutionRunnerTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/StringOperationWithoutCulture.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.cs
> Fix S2259 FP: SingleOrDefault() and FirstOrDefault() used within EF LINQ queries

- analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/RestrictDeserializedTypesTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/AssertIgnoreScope.cs
`WhenReportDiagnosticActionNotNull_AllowToControlWhetherOrNotToReport` UT is failing in Debug mode since updating to .NET 7. Root cause is the impression mechanism for Debug.Assert exception is no longer working on .Net 7 as before. A more radical approach (removing the default listener) fixes the problem,
> Fix AssertIgnoreScope for .NET 7

- pom.xml
C# Jar size went from 5 532 287 bytes -> 5 508 320 bytes
We're still within boundaries
https://github.com/SonarSource/sonar-dotnet/blob/d2590e5c855787cfcd9b351f546023485a953294/sonar-csharp-plugin/pom.xml#L217-L220
> Bump sonar-analyzer-commons to 2.0.0.1075

- azure-pipelines.yml
Follow up of #6197 
`sonar-dotnet-variables-tmp` was duplicated as `sonar-dotnet-variables`
`sonar-dotnet-variables-tmp` will be deleted once this is merged
> Rename pipeline variable group

- azure-pipelines.yml
The new behavior can be observed here: https://dev.azure.com/sonarsource/DotNetTeam%20Project/_build/results?buildId=55839&view=results
There are 2 different changes:
- `.Net Analysis` job is not executed if .Net unit tests fail.
- Coverage and test results artifacts are not published if running the unit tests fails. The reason is that the uploaded artifacts cannot be overwritten and all the subsequent build retries will fail.
> Run .Net code analysis only if the UTs pass

- .github/workflows/CreateMilestone.yml
Automatically create `Update RSPEC before x.y release` and milestone it, once a milestone is created.
Tested here: [CreateMilestone.yml](https://github.com/pavel-mikula-sonarsource/GitHubActionPlayground/blob/master/.github/workflows/CreateMilestone.yml), `@master` and `@v1` are identical now.
Source milestone: [6.2.4](https://github.com/pavel-mikula-sonarsource/GitHubActionPlayground/milestone/31)
Action log: [Job run log](https://github.com/pavel-mikula-sonarsource/GitHubActionPlayground/actions/runs/3393178582/jobs/5640215197)
Produced issue: https://github.com/pavel-mikula-sonarsource/GitHubActionPlayground/issues/35
---
How it really works:
[Source of the action](https://github.com/SonarSource/gh-action-lt-backlog/blob/master/CreateRspecIssue/index.ts)
[Boring intermediate base …
> GitHub workflow: Create Milestone

- analyzers/tests/SonarAnalyzer.UnitTest/Extensions/ITupleOperationWrapperExtensionsTests.cs
I've recently seen this UT failing randomly on the CI. Last few times with messages:
>Execution of the action should be less than 0.005s, but it required more than 0.009s and 947.9µs.
>Execution of the action should be less than 0.005s, but it required more than 0.012s and 363.9µs.
> Fix flaky UT AllElements_Performance_DeepNesting

- .github/workflows/StartProgress.yml
Action: https://github.com/SonarSource/gh-action-lt-backlog/tree/master/AssignCardToSender
Source: https://github.com/SonarSource/gh-action-lt-backlog/blob/master/AssignCardToSender/AssignCardToSender.ts
This PR removes filter for "Target" column. It's just a noise. If I move card from `To do` to `In review`, I should get my face on it too.
> GitHub workflow: Migrate StartProgress to shared action

- analyzers/its/sources/ManuallyAddedNoncompliantIssues.CS/IntentionalFindings/IntentionalFindings.csproj
There was a security alert for versions <= 4.8.4
We're not affected as we don't execute this code. This will just remove the FP
ITs are failing due to some issue with master. The change itself worked and projects are built. Rebase will be needed.
> ITs: Bump System.Data.SqlClient to 4.8.5

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/InitializeStaticFieldsInline.cs
> S3963: Add FP repro for #6343

- .github/workflows/CreateMilestone.yml
One action doesn't trigger another. So we also need to crate cards on Kanban from this action.
Action was already modified here: 
https://github.com/SonarSource/gh-action-lt-backlog/pull/5
All we need to do is to provide a value for the new parameter with target column-id of our `To Do` column. Column ID can be found as part of the column URL.
> GitHub workflow: Create Milestone creates card on Kanban

- analyzers/src/SonarAnalyzer.CSharp/Rules/DeadStores.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DeadStores.CSharp11.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DeadStores.RoslynCfg.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DeadStores.SonarCfg.cs
This rule also documents that the behaviour reported in the following two issues is not a false positive as we intentionally not evaluate string interpolations.
- https://github.com/SonarSource/sonar-dotnet/issues/6301
- https://github.com/SonarSource/sonar-dotnet/issues/6302 
Fixes #6301 
Fixes #6302
> Fix S1854 FP: Rule should not raise if empty interpolated string is assigned to the variable

- analyzers/src/SonarAnalyzer.CSharp/Rules/DatabasePasswordsShouldBeSecure.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DatabasePasswordsShouldBeSecure.CSharp11.cs
> Fix S2115 FN: Support multi-line string interpolation inside a raw string literal

- analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/DisablingCsrfProtection.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/DisablingCSRFProtection.CSharp11.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/DisablingCSRFProtection.cs
This reverts #6314 in favor of performance.
Also fixed some comments to document this decision.
> Revert S4502 C#11 changes to opt for performance

- analyzers/src/SonarAnalyzer.CFG/ShimLayer/Syntax.xml
Copy from the VS 17.4 release (C#11 release)
https://github.com/dotnet/roslyn/blob/Visual-Studio-2022-Version-17.4/src/Compilers/CSharp/Portable/Syntax/Syntax.xml
Hint: Use *Hide whitespace* for review:
> Update Syntax.xml for C# 11

- .github/workflows/LabelIssue.yml
Last one to migrate.
Uses: https://github.com/SonarSource/gh-action-lt-backlog/tree/master/CreateCardForIssueFromLabel
> GitHub workflow: Migrate LabelIssue to shared action

- analyzers/src/SonarAnalyzer.CSharp/Rules/VariableShadowsField.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/VariableShadowsField.CSharp11.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/VariableShadowsField.CSharp9.cs
Fixes #6378
Also adds support for the other [pattern types with a designation](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/patterns#patterns)
* property pattern (aka recursive pattern)
* positional pattern (aka recursive pattern)
* var pattern
> Fix S1117 FN: Support list patterns

- azure-pipelines.yml
We will exclude from coverage the `SonarAnalyzer.ShimLayer.CodeGeneration` project and all the files from `src/SonarAnalyzer.CFG/ShimLayer` folder.
I've tested the PT with one file inside the folder and one file outside. The file outside had the coverage computed and the on inside was skipped.
> Exclude Shim layer code from coverage

- analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/UnitTestHelper.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/TestMethodShouldContainAssertion.Custom.cs
> Fix S2699 FP: Support derivations of ExpectedExceptionBaseAttribute for MsTest

- its/pom.xml
- pom.xml
- sonar-csharp-plugin/pom.xml
- sonar-dotnet-shared-library/pom.xml
- sonar-vbnet-plugin/pom.xml
`org.slf4j` dependency is added by `logback-classic` and we don't need to explicitly set it.
If we change the version by hand we can get to errors like:
```
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J: Ignoring binding found at [jar:file:/C:/Users/../.m2/repository/ch/qos/logback/logback-classic/1.2.0/logback-classic-1.2.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.
```
> Remove explicit org.slf4j dependency and update java dependencies

- analyzers/src/SonarAnalyzer.CSharp/Rules/NameOfShouldBeUsed.cs
- analyzers/src/SonarAnalyzer.Common/Rules/NameOfShouldBeUsedBase.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/NameOfShouldBeUsed.CSharp11.cs
> Fix S2302 FN: Issue is not raised when the name of one of the method parameters is a raw string literal

- analyzers/src/SonarAnalyzer.CFG/ShimLayer/SyntaxKindEx.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/ExpressionComplexity.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/ExpressionComplexityTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ExpressionComplexity.cs
Follow up to #6500
Other binary expressions should be considered as part of the tree and be visited also.
> Fix S1067 FN: binary expressions should be treated as transparent

- analyzers/src/SonarAnalyzer.CSharp/Rules/NativeMethodsShouldBeWrapped.cs
- analyzers/src/SonarAnalyzer.Common/AnalysisContext/DiagnosticAnalyzerContextHelper.cs
- analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarAnalysisContext.ScrapYard.cs
- analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarAnalysisContext.cs
- analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarAnalysisContextBase.cs
- analyzers/src/SonarAnalyzer.Common/Rules/EmptyMethodBase.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Tests/CodeFixProviderTest.cs
Part of #6540
* Migrate `RegisterSyntaxNodeAction` to the new Sonar-signature
* Migrate `RegisterCodeBlockStartAction` to the new Sonar-signature
> Refactor SonarAnalysisContext - Migrate RegisterSyntaxNodeAction

- analyzers/src/SonarAnalyzer.CSharp/Helpers/CSharpDiagnosticAnalyzerContextHelper.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/ClassShouldNotBeAbstract.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/ClassWithOnlyStaticMember.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/DisposableMemberInNonDisposableClass.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/DisposableNotDisposed.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/DisposeNotImplementingDispose.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/MemberShadowsOuterStaticMember.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/NativeMethodsShouldBeWrapped.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/UninvokedEventDeclaration.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/UnusedPrivateMember.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/UnusedReturnValue.cs
- analyzers/src/SonarAnalyzer.Common/AnalysisContext/DiagnosticAnalyzerContextHelper.cs
- analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarAnalysisContext.ScrapYard.cs
- analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarAnalysisContext.cs
- analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarSymbolAnalysisContext.cs
- analyzers/src/SonarAnalyzer.Common/Rules/ClassNotInstantiatableBase.cs
- analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/DisablingRequestValidationBase.cs
- analyzers/src/SonarAnalyzer.Common/Rules/PropertiesAccessCorrectFieldBase.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Helpers/VisualBasicDiagnosticAnalyzerContextHelper.cs
- analyzers/tests/SonarAnalyzer.UnitTest/AnalysisContext/DiagnosticAnalyzerContextHelperTest.cs
Part of #6540
* Migrate `RegisterSymbolAction` to the new Sonar-signature
> Refactor SonarAnalysisContext - Migrate RegisterSymbolAction

- analyzers/src/SonarAnalyzer.Common/AnalysisContext/ParameterLoadingAnalysisContext.cs
- analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarAnalysisContext.ScrapYard.cs
- analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarAnalysisContext.cs
- analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarAnalysisContextBase.cs
- analyzers/src/SonarAnalyzer.Common/DiagnosticAnalyzer/ParameterLoadingDiagnosticAnalyzer.cs
- analyzers/src/SonarAnalyzer.Common/Extensions/DiagnosticDescriptorExtensions.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/AnalysisContextExtensions.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/SonarCodeFix.cs
- analyzers/src/SonarAnalyzer.Common/Rules/EmptyMethodBase.cs
- analyzers/src/SonarAnalyzer.Common/Rules/SymbolicExecutionRunnerBase.cs
- analyzers/tests/SonarAnalyzer.UnitTest/AnalysisContext/SonarAnalysisContextTest.ShouldAnalyze.cs
- analyzers/tests/SonarAnalyzer.UnitTest/AnalysisContext/SonarAnalysisContextTest.ShouldAnalyzeGenerated.cs
- analyzers/tests/SonarAnalyzer.UnitTest/AnalysisContext/SonarAnalysisContextTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Extensions/DiagnosticDescriptorExtensionsTest.cs
Part of #6540
Review per commit should show how individual steps were made:
* Move `IsAnalysisScopeMatching` into an extension
* Move `IsRegisteredActionEnabled` - renamed to `LegacyIsRegisteredActionEnabled`
* Remove `ShouldAnalyzeGenerated` - rewrote UTs to match the new state and test all scenarios properly
> Refactor SonarAnalysisContext - Migrate helper methods

- analyzers/src/SonarAnalyzer.CSharp/Helpers/CSharpDiagnosticAnalyzerContextHelper.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/CommentedOutCode.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/GetHashCodeEqualsOverride.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/GuardConditionOnEqualsOverride.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/IssueSuppression.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/VariableUnused.cs
- analyzers/src/SonarAnalyzer.Common/AnalysisContext/DiagnosticAnalyzerContextHelper.cs
- analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarAnalysisContext.cs
- analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarAnalysisContextBase.cs
- analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarCodeBlockAnalysisContext.cs
- analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarCodeBlockStartAnalysisContext.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/AnalysisContextExtensions.cs
- analyzers/src/SonarAnalyzer.Common/Rules/VariableUnusedBase.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Helpers/VisualBasicDiagnosticAnalyzerContextHelper.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Rules/CommentLineEnd.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Rules/VariableUnused.cs
Part of #6540
* Migrate `ReportIssue` for `SyntaxTreeAnalysisContext`
* Migrate `ReportIssue` for `CodeBlockAnalysisContext`
> Refactor SonarAnalysisContext - Migrate ReportIssue for Tree and CodeBlock

- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/IssueLocationCollector.cs
- docs/contributing-analyzer.md
- docs/verifier-syntax.md
[Preview](https://github.com/SonarSource/sonar-dotnet/blob/Martin/docs_VerifierSyntax/docs/verifier-syntax.md)
based on https://github.com/gregory-paidis-sonarsource/random/blob/main/issue_location_collector.md and on the comment from here:
https://github.com/SonarSource/sonar-dotnet/blob/d795ff77dc05911a1ae06ab151568dd229b08e74/analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/IssueLocationCollector.cs#L29-L86
> Documentation: Add markdown file with description of the verifier doc comment syntax

- sonar-csharp-plugin/src/main/java/org/sonar/plugins/csharp/CSharpFileCacheSensor.java
- sonar-csharp-plugin/src/test/java/org/sonar/plugins/csharp/CSharpFileCacheSensorTest.java
- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/AbstractFileCacheSensor.java
- sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/AbstractFileCacheSensorTest.java
- sonar-vbnet-plugin/src/main/java/org/sonar/plugins/vbnet/VbNetFileCacheSensor.java
- sonar-vbnet-plugin/src/test/java/org/sonar/plugins/vbnet/VbNetFileCacheSensorTest.java
Fixes #6598
I've validated this locally by updating the integration tests to run with 8.9. The problem is reproducible before the change and is fixed after it.
> Check API version before calling `isCacheEnabled`

- analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarAnalysisContext.cs
- analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarAnalysisContextBase.cs
- analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarParametrizedAnalysisContext.cs
- analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarReportingContextBase.cs
- analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarSyntaxNodeAnalysisContext.cs
- analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarSyntaxTreeAnalysisContext.cs
- analyzers/src/SonarAnalyzer.Common/Extensions/DiagnosticDescriptorExtensions.cs
- analyzers/src/SonarAnalyzer.Common/Rules/SymbolicExecutionRunnerBase.cs
- analyzers/tests/SonarAnalyzer.UnitTest/AnalysisContext/SonarAnalysisContextBaseTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/AnalysisContext/SonarAnalysisContextTest.ShouldAnalyze.cs
Part of #6532
Previous changes showed that `HasMatchingScope` always depends on data from `SonarAnalysisContextBase`. 
It is now also clear, that `Compilation` is never null after this redesign.
> Refactor SonarAnalysisContext - Move HasMatchingScope

- analyzers/src/SonarAnalyzer.CSharp/Rules/EmptyMethod.cs
- analyzers/src/SonarAnalyzer.Common/Rules/EmptyMethodBase.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Rules/EmptyMethod.cs
Part of #6540
This rule duplicates it's registration. We have a better method for that.
> Refactor SonarAnalysisContext - Refactor EmptyMethod rule

- analyzers/tests/SonarAnalyzer.UnitTest/Extensions/EnumerableExtensionsTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SonarAnalyzer.UnitTest.csproj
- analyzers/tests/SonarAnalyzer.UnitTest/packages.lock.json
The UT projects references can be updated, except for FluentValidations which has API changes that need to be resolved. Regarding the MSTest update see also https://sonarsource.slack.com/archives/C012KBFFYD6/p1671013908445919.
> Packages: Update package references for UnitTests

- analyzers/src/SonarAnalyzer.CSharp/Rules/UnchangedLocalVariablesShouldBeConst.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnchangedLocalVariablesShouldBeConst.CSharp9.cs
The rule was missing some constructs that form a method boundary. I added support for these and added some tests. I was expecting this to cause problems with shadowed locals/fields but it turned out that there was an additional symbol checked which prevented this. The fix is therefore only a small performance optimization but the added tests are useful anyhow.
> Fix S3353: Add support for different function types

- its/src/test/java/com/sonar/it/csharp/IncrementalAnalysisTest.java
Cache API used by incremental analysis has changed on SQ side and ITs are failing.
This will temporary disable them to unblock other work.
`@Disable` annotation is available from JUnit 5, we use version 4 so I've just commented the annotations with `ToDo`
> Disable Incremental analysis ITs

- analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/DoNotHardcodeCredentials.cs
- analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarAnalysisContext.cs
- analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarParametrizedAnalysisContext.cs
- analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/DoNotHardcodeCredentialsBase.cs
- analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/RequestsWithExcessiveLengthBase.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Rules/Hotspots/DoNotHardcodeCredentials.cs
- analyzers/tests/SonarAnalyzer.UnitTest/AnalysisContext/SonarAnalysisContextTest.Register.cs
Part of #6532
`SonarParametrizedAnalysisContext` should inherit `SonarAnalysisContext` because it is meant to be it's in-place alternation. And override that single method that has different behavior instead of trying to duplicate everything from it.
> Refactor SonarAnalysisContext - SonarParametrizedAnalysisContext inherits SonarAnalysisContext

- analyzers/tests/SonarAnalyzer.UnitTest/AnalysisContext/SonarCompilationStartAnalysisContextTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/AnalysisContext/SonarSymbolReportingContextTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/AnalysisContext/SonarSyntaxTreeReportingContextTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/CBDE/MlirTestUtilities.cs
- analyzers/tests/SonarAnalyzer.UnitTest/CFG/Sonar/SonarCfgSerializerTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/CFG/Sonar/SonarControlFlowGraphTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Extensions/AttributeSyntaxExtensionsTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Extensions/ControlFlowGraphExtensionsTests.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Extensions/ExpressionSyntaxExtensionsTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Extensions/InterpolatedStringExpressionSyntaxExtensionsTests.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Extensions/ObjectCreationExpressionSyntaxExtensionsTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Extensions/SyntaxNodeExtensionsTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Extensions/VisualBasic/ISymbolExtensionsTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Extensions/VisualBasic/InterpolatedStringExpressionSyntaxExtensionsTests.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Helpers/AspNetMvcHelperTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Helpers/BuilderPatternDescriptorTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Helpers/CSharpSymbolUsageCollectorTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Helpers/KnownTypeTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Helpers/OperationExecutionOrderTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Helpers/TypeDeclarationSyntaxExtensionsTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/LiveVariableAnalysis/SonarLiveVariableAnalysisTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Sonar/SonarExplodedGraphTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Sonar/SonarProgramStateTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SyntaxTreeExtensions.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/TestHelper.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Trackers/ConstantValueFinderTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Wrappers/IOperationWrapperSonarTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Wrappers/MethodDeclarationFactoryTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Wrappers/ObjectCreationFactoryTest.cs
Follow up of #6532 
Remove `Get*` methods from TestHelper. They where mostly not needed or used by classes that are about to be deleted.
Extract `tree.First<T>` and `tree.Single<T>` where `T:SyntaxNode` in UTs instead.
> Refactor SonarAnalysisContext - Cleanup TestHelper

- analyzers/tests/SonarAnalyzer.UnitTest/Extensions/SyntaxTreeExtensionsTest.cs
Part of #6532
File `SyntaxTreeContextExtensionsTest.cs` should not have `Context` in the name and should be in `Extensions` directory.
> Refactor SonarAnalysisContext - Rename SyntaxTreeExtensionsTest

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/InfiniteRecursion.RoslynCfg.cs
Reproduces #6642 
Reproduces #6643
Reproduces #6644
> FN S2190: Add reproducers for issues 6642, 6643 and 6644

- analyzers/src/SonarAnalyzer.CSharp/Helpers/ParameterValidationInMethodWalker.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/ParameterValidationInAsyncShouldBeWrapped.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/ParameterValidationInMethodWalker.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/ParameterValidationInYieldShouldBeWrapped.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ParameterValidationInAsyncShouldBeWrapped.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ParameterValidationInYieldShouldBeWrapped.CSharp10.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ParameterValidationInYieldShouldBeWrapped.cs
> Fix S4457 FP: Argument check after async code

- analyzers/src/SonarAnalyzer.CSharp/Rules/DisposableNotDisposed.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DisposableNotDisposed.CSharp8.cs
Fixes https://github.com/SonarSource/sonar-dotnet/issues/5879
> Fix S2930 FN

- .github/workflows/release.yml
Revert release.yml to automatically use the latest minor version (v5).
> Revert release.yml 

- analyzers/src/SonarAnalyzer.CSharp/Rules/EqualityOnFloatingPoint.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/OperatorsShouldBeOverloadedConsistently.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/KnownMethods.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/EqualityOnFloatingPointTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/EqualityOnFloatingPoint.CSharp11.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/EqualityOnFloatingPoint.cs
Part of #6521
~~Made into a draft because it should be merged after the release.~~
> Improve S1244: Add message to use "IsNaN" instead of "== double.NaN"

- analyzers/src/SonarAnalyzer.CSharp/Rules/EqualityOnFloatingPoint.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/EqualityOnFloatingPoint.CSharp11.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/EqualityOnFloatingPoint.cs
Follows #6664
Fixes #6521 
~~Made into a draft because it should be merged after the release.~~
RSPEC update to be merged with this:
https://github.com/SonarSource/rspec/pull/1509
> Improve S1244: Add message to use "IsXInfinity()" instead of "== double.XInfinity"

- analyzers/tests/SonarAnalyzer.UnitTest/SonarAnalyzer.UnitTest.csproj
- analyzers/tests/SonarAnalyzer.UnitTest/packages.lock.json
Revert part of #6626 due to VS regression https://github.com/microsoft/vstest/issues/4208
Being able to run UTs in VS is a must-have.
> Downgrade MSTest references to 2.2.10

- sonar-csharp-plugin/pom.xml
- sonar-vbnet-plugin/pom.xml
Without this, the "exec" task of `maven-antrun-lugin` reports `[ERROR]` and happily continues. The build succeeds and the SQ startup fails due to runtime error because of some missing resources.
We need to fail the Java build when this `exec` task fails.
Remark:
`failonerror` defaults to `true` when used at maven-antrun-plugin level (c.p. https://maven.apache.org/plugins/maven-antrun-plugin/run-mojo.html), but defaults to `false` when used in a `exec` task under `target` (c.p. https://ant.apache.org/manual/Tasks/exec.html).
> Fail Java build when RuleDescriptorGeneratorFails

- analyzers/src/SonarAnalyzer.CSharp/Rules/InvocationResolvesToOverrideWithParams.cs
- analyzers/src/SonarAnalyzer.Common/Extensions/ISymbolExtensions.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/InvocationResolvesToOverrideWithParamsTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/InvocationResolvesToOverrideWithParams.CSharp11.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/InvocationResolvesToOverrideWithParams.TopLevelStatements.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/InvocationResolvesToOverrideWithParams.cs
Fixes #5430
~~Made into a draft because it should be merged after the release.~~
Remarks:
An API has been introduced in Roslyin API to check whether a symbol is accessible from within another symbol: https://github.com/dotnet/roslyn/issues/23842
The API is not yet available for the .NET Analyzer, and quite heavy (as it also for any type of symbol).
For those reasons, a tailored way of checking visibility of a method overload `M` of a type `T` from a (potentially different) type `U` has been implemented, exploiting the fact that, for rule 3220 to be triggered, `T`, as well as at least one of the overloads of `M `(with `params`) are visible from `U`.
A false negative would be produced in the case: 
- `InternalsVisibleToAttribute("A2")` is used on an assembly `A1`
- assembly `A2` contains a …
> Fix S3220 FP: Rule does not take into account access modifier of the members

- analyzers/src/SonarAnalyzer.Common/Rules/CommentsShouldNotBeEmptyBase.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CommentsShouldNotBeEmpty.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CommentsShouldNotBeEmpty.vb
This PR aims to fix squiggly lines under whitespace between `SingleLineCommentTrivia` entries.
> S4663: Fix highlighting to remove underlying whitespaces
