sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/CallToAsyncMethodShouldNotBeBlockingTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/CallerInformationParametersShouldBeLastTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/CastShouldNotBeDuplicatedTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/CertificateValidationCheckTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/CheckArgumentExceptionTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/CheckFileLicenseTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/ClassAndMethodNameTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/CallToAsyncMethodShouldNotBeBlocking.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/CallerInformationParametersShouldBeLast.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/CastShouldNotBeDuplicated.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/CertificateValidationCheck.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/CertificateValidationCheck.TopLevelStatements.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/CertificateValidationCheck.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/CheckArgumentException.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/CheckArgumentException.TopLevelStatements.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/CheckArgumentException.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/CheckFileLicense_CSharp9.Fixed.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/CheckFileLicense_CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ClassName.TopLevelStatement.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/MethodName.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/RecordName.cs

Related to #3668
S3343 CallerInformationParametersShouldBeLast.cs
S4462 CallToAsyncMethodShouldNotBeBlocking.cs
S3247 CastShouldNotBeDuplicated.cs
S4830 CertificateValidationCheck.cs
S3928 CheckArgumentException.cs
S1451 CheckFileLicense.cs
S100, S101 ClassAndMethodName.cs

Add C# 9 tests for 8 rules

---

sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/ThisShouldNotBeExposedFromConstructors.cs
sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/ThreadStaticNonStaticField.cs
sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/TooManyGenericParameters.cs
sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/TypeNamesShouldNotMatchNamespaces.cs
sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/TypesShouldNotExtendOutdatedBaseTypes.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/TestMethodShouldNotBeIgnoredTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/ThisShouldNotBeExposedFromConstructorsTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/ThreadStaticNonStaticFieldTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/ThreadStaticWithInitializerTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/ToStringNoNullTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/TooManyGenericParametersTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/TypeNamesShouldNotMatchNamespacesTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/TypesShouldNotExtendOutdatedBaseTypesTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/UnaryPrefixOperatorRepeatedTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/TestMethodShouldNotBeIgnored.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ThisShouldNotBeExposedFromConstructors.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ThreadStaticNonStaticField.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ThreadStaticNonStaticField.Fixed.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ThreadStaticNonStaticField.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ThreadStaticWithInitializer.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ThreadStaticWithInitializer.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ToStringNoNull.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/TooManyGenericParameters.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/TypeNamesShouldNotMatchNamespaces.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UnaryPrefixOperatorRepeated.CSharp9.cs

Add C# 9 test cases (8 rules)

---

sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/StringOrIntegralTypesForIndexersTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/SuppressFinalizeUselessTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/SwitchCaseFallsThroughToDefaultTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/TestClassShouldHaveTestMethodTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/TestMethodShouldContainAssertionTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/TestMethodShouldHaveCorrectSignature.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/StringOrIntegralTypesForIndexers.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/StringOrIntegralTypesForIndexers.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/SuppressFinalizeUseless.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/SuppressFinalizeUseless.Fixed.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/SuppressFinalizeUseless.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/SwitchCaseFallsThroughToDefault.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/SwitchCaseFallsThroughToDefault.Fixed.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/SwitchCaseFallsThroughToDefault.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/TestClassShouldHaveTestMethod.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/TestMethodShouldContainAssertion.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/TestMethodShouldHaveCorrectSignature.CSharp9.cs

Add C# 9 test cases

---

README.md
sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/SonarAnalyzer.CSharp.nuspec
sonaranalyzer-dotnet/src/SonarAnalyzer.Vsix/SonarAnalyzer.VisualBasic.nuspec

(see [this comment](http://disq.us/p/2cx9cnn) )

Raise awareness that our analyzers are Roslyn-based

---

sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/ClassNotInstantiatableTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/ClassShouldNotBeAbstractTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/ClassWithEqualityShouldImplementIEquatableTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/ClassWithOnlyStaticMemberTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/CognitiveComplexityTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ClassNotInstantiatable.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ClassShouldNotBeAbstract.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ClassWithEqualityShouldImplementIEquatable.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ClassWithOnlyStaticMember.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/CognitiveComplexity.CSharp9.cs

Add C# 9 test cases (5 rules)

---

sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/SillyBitwiseOperationTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/SingleStatementPerLineTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/StaticFieldInGenericClassTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/StaticFieldInitializerOrderTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/StaticFieldVisibleTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/StaticFieldWrittenFromInstanceConstructorTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/StaticFieldWrittenFromInstanceMemberTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/StaticSealedClassProtectedMembersTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/StringLiteralShouldNotBeDuplicatedTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/SillyBitwiseOperation.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/SillyBitwiseOperation.Fixed.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/SillyBitwiseOperation.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/SingleStatementPerLine.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/StaticFieldInGenericClass.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/StaticFieldInGenericClass.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/StaticFieldInitializerOrder.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/StaticFieldInitializerOrder.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/StaticFieldVisible.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/StaticFieldVisible.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/StaticFieldWrittenFromInstanceConstructor.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/StaticFieldWrittenFromInstanceMember.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/StaticFieldWrittenFromInstanceMember.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/StaticSealedClassProtectedMembers.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/StaticSealedClassProtectedMembers.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/StringLiteralShouldNotBeDuplicated.CSharp9.cs

Add C# 9 test cases (9 rules)

---

sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/RedundantToStringCallTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/ReturnEmptyCollectionInsteadOfNullTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/ReturnValueIgnoredTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/ReversedOperatorsTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/SerializationConstructorsShouldBeSecuredTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/SetLocaleForDataTypesTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/ShiftDynamicNotIntegerTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/ShouldImplementExportedInterfacesTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/RedundantToStringCall.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/RedundantToStringCall.Fixed.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/RedundantToStringCall.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ReturnEmptyCollectionInsteadOfNull.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ReturnValueIgnored.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ReversedOperators.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ReversedOperators.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/SerializationConstructorsShouldBeSecured.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/SetLocaleForDataTypes.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ShiftDynamicNotInteger.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ShouldImplementExportedInterfaces.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/StringOrIntegralTypesForIndexers.CSharp9.cs

Add C# 9 test cases for S4159, S3449, S4057, S4212, S2757, S2201, S1168 and S1858

---

sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/AbstractTypesShouldNotHaveConstructors.Records.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/CheckArgumentException.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ClassNotInstantiatable.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ClassShouldNotBeAbstract.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ClassWithEqualityShouldImplementIEquatable.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/CognitiveComplexity.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/MethodName.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UnusedPrivateMember.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/UseValueParameter.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/VariableUnused.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestFramework/SolutionBuilder.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestFramework/Verifier.cs

Avoid duplication for workaround to support C#9 init

---

sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/RedundantConditionalAroundAssignmentTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/RedundantDeclarationTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/RedundantInheritanceListTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/RedundantJumpStatementTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/RedundantModifierTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/RedundantNullCheckTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/RedundantParenthesesObjectCreationTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/RedundantConditionalAroundAssignment.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/RedundantConditionalAroundAssignment.Fixed.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/RedundantConditionalAroundAssignment.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/RedundantDeclaration.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/RedundantInheritanceList.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/RedundantInheritanceList.Fixed.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/RedundantInheritanceList.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/RedundantJumpStatement.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/RedundantModifier.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/RedundantNullCheck.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/RedundantNullCheck.Fixed.Batch.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/RedundantNullCheck.Fixed.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/RedundantNullCheck.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/RedundantParenthesesObjectCreation.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestFramework/SolutionBuilder.cs

Add C# 9 tests for S3235, S4201, S2333, S3626, S1939, S3257 and S3440

---

sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ConditionEvaluatesToConstant.cs

Reproduces #3161 
Reproduces #3701

S2583 and S2589: Add FP repro for #3161 and #3701

---

sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/PropertyWriteOnlyTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/ProvideDeserializationMethodsForOptionalFieldsTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/PublicConstantFieldTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/PureAttributeOnVoidMethodTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/ReadingStandardInputTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/RedundancyInConstructorDestructorDeclarationTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/RedundantArgumentTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/PropertyWriteOnly.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ProvideDeserializationMethodsForOptionalFields.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/PublicConstantField.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/PureAttributeOnVoidMethod.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ReadingStandardInput.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/RedundancyInConstructorDestructorDeclaration.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/RedundantArgument.CSharp9.cs

Add C# 9 tests for S3254, S4829, S3603, S3253, S2339, S3926 and S2376

---

sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/RedundantToStringCall.Fixed.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/RedundantToStringCall.cs

S1858: Add FP repro for #3665

---

sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/DangerousGetHandleShouldNotBeCalledTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/DeadStoresTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/DebugAssertHasNoSideEffectsTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/DeclareTypesInNamespacesTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/DefaultSectionShouldBeFirstOrLastTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/DelegateSubtractionTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DangerousGetHandleShouldNotBeCalled.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DeadStores.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DebugAssertHasNoSideEffects.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DeclareTypesInNamespaces.AfterCSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DefaultSectionShouldBeFirstOrLast.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DelegateSubtraction.CSharp9.cs

Add C# 9 test cases for S3869, S1854, S3346, S3903, S4524, S3172

---

sonaranalyzer-dotnet/its/expected/Net5/Net5--S108.json
sonaranalyzer-dotnet/its/expected/Net5/Net5--S109.json
sonaranalyzer-dotnet/its/expected/Net5/Net5--S1104.json
sonaranalyzer-dotnet/its/expected/Net5/Net5--S1481.json
sonaranalyzer-dotnet/its/expected/Net5/Net5--S2201.json
sonaranalyzer-dotnet/its/expected/Net5/Net5--S2325.json
sonaranalyzer-dotnet/its/expected/Net5/Net5--S2357.json
sonaranalyzer-dotnet/its/expected/Net5/Net5--S3241.json
sonaranalyzer-dotnet/its/expected/Net5/Net5--S3257.json
sonaranalyzer-dotnet/its/sources/Net5/Net5/LambdaDiscardParameters.cs

Update .Net5 IT for Lambda Discard

---

sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/PInvokesShouldNotBeVisibleTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/ParameterNamesInPartialMethodTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/PartCreationPolicyShouldBeUsedWithExportAttributeTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/PartialMethodNoImplementationTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/PointersShouldBePrivateTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/PrivateFieldUsedAsLocalVariableTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/PropertiesAccessCorrectFieldTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/PropertiesShouldBePreferredTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/PropertyToAutoPropertyTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/PInvokesShouldNotBeVisible.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ParameterNamesInPartialMethod.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/PartCreationPolicyShouldBeUsedWithExportAttribute.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/PartialMethodNoImplementation.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/PointersShouldBePrivate.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/PrivateFieldUsedAsLocalVariable.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/PropertiesAccessCorrectField.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/PropertiesShouldBePreferred.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/PropertyToAutoProperty.CSharp9.cs

Add C# 9 test cases for S2292, S4049, S4275, S1450, S4000, S4214, S3251, S4428 and S927

---

sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/ImplementIDisposableCorrectlyTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/ImplementISerializableCorrectlyTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/ImplementSerializationMethodsCorrectlyTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ImplementIDisposableCorrectly.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ImplementISerializableCorrectly.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ImplementISerializableCorrectly.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ImplementSerializationMethodsCorrectly.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ImplementSerializationMethodsCorrectly.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ImplementSerializationMethodsCorrectly.vb

Related to #3668
Reproduces #3734
New tests are mostly copy/paste from regular test file.

Add C# 9 tests for Implement* rules

---

sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/IssueSuppressionTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/JwtSignedTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/LdapConnectionShouldBeSecureTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/LossOfFractionInDivisionTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/IssueSuppression.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/JwtSigned.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/LdapConnectionShouldBeSecure.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/LossOfFractionInDivision.CSharp9.cs

Add C# 9 tests fro S1309, S5659, S4433, S2184

---

sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/NotAssignedPrivateMemberTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/NumberPatternShouldBeRegularTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/ObsoleteAttributesNeedExplanationTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/OperatorOverloadsShouldHaveNamedAlternativesTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/OperatorsShouldBeOverloadedConsistentlyTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/OptionalParameterNotPassedToBaseCallTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/OptionalRefOutParameterTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/OverrideGetHashCodeOnOverridingEqualsTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/ParameterAssignedToTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/NotAssignedPrivateMember.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/NotAssignedPrivateMember.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/NumberPatternShouldBeRegular.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ObsoleteAttributesNeedExplanation.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/OperatorOverloadsShouldHaveNamedAlternatives.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/OperatorsShouldBeOverloadedConsistently.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/OptionalParameterNotPassedToBaseCall.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/OptionalParameterNotPassedToBaseCall.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/OptionalRefOutParameter.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/OverrideGetHashCodeOnOverridingEquals.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ParameterAssignedTo.CSharp9.cs

Add C# 9 test cases for S1226,  S1206, S3447, S3466, S4050, S4069, S1123, S3937 and S3459

---

sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/EqualsOverrideTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/GenericInheritanceShouldNotBeRecursiveTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/GenericReadonlyFieldPropertyAssignmentTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/GenericTypeParameterEmptinessCheckingTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/GenericTypeParameterUnusedTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/GetHashCodeEqualsOverrideTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/GetHashCodeMutableTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/GetTypeWithIsAssignableFromTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/MethodsShouldUseBaseTypesTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/NativeMethodsShouldBeWrappedTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/NestedCodeBlockTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/GenericInheritanceShouldNotBeRecursive.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/GenericReadonlyFieldPropertyAssignment.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/GenericTypeParameterEmptinessChecking.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/GenericTypeParameterUnused.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/GetHashCodeEqualsOverride.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/GetHashCodeMutable.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/GetTypeWithIsAssignableFrom.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/MethodsShouldUseBaseTypes.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/NativeMethodsShouldBeWrapped.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/NestedCodeBlock.CSharp9.cs

Add C#9 test cases for S1199, S4200, S3242, S2219, S2328, S3249, S2326, S2955 and S2934

---

sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/LiteralsShouldNotBePassedAsLocalizedParametersTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/LiteralsShouldNotBePassedAsLocalizedParameters.CSharp9.cs

Add C# 9 unit tests for S4055

---

sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/TestMethodShouldContainAssertion.NUnit.cs

Rule S2699: Document false positive

---

docs/contributing-analyzer.md
docs/contributing-plugin.md

`-restore` was not necessary in was removed in a previous commit

Update docs: fix run command

---

sonaranalyzer-dotnet/rspec/cs/S4784_c#.html
sonaranalyzer-dotnet/rspec/cs/S4784_c#.json
sonaranalyzer-dotnet/rspec/cs/S4787_c#.html
sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S4784_cs.html
sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S4787_cs.html

Deprecate S4787 and S4784

---

sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/AssignmentInsideSubExpressionTest.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/AssignmentInsideSubExpression.CSharp9.cs

Add C# 9 UT for S1121

---

sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Helpers/SyntaxNodeExtensions.cs
sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/AssertionArgsShouldBePassedInCorrectOrder.cs
sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/BeginInvokePairedWithEndInvoke.cs
sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/CollectionQuerySimplification.cs
sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/DebugAssertHasNoSideEffects.cs
sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/EnumerableSumInUnchecked.cs
sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/FieldsShouldBeEncapsulatedInProperties.cs
sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/GetTypeWithIsAssignableFrom.cs
sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/InvocationResolvesToOverrideWithParams.cs
sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/LiteralSuffixUpperCase.cs
sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/OrderByRepeated.cs
sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/RedundantCast.cs
sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/RedundantToCharArrayCall.cs
sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/ReturnEmptyCollectionInsteadOfNull.cs
sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/TypeExaminationOnSystemType.cs
sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/UseStringIsNullOrEmpty.cs
sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Rules/HardcodedIpAddressBase.cs
sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Rules/UriShouldNotBeHardcodedBase.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/GetTypeWithIsAssignableFrom.CSharp9.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/GetTypeWithIsAssignableFrom.Fixed.Batch.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/GetTypeWithIsAssignableFrom.Fixed.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/GetTypeWithIsAssignableFrom.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/LiteralSuffixUpperCase.Fixed.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/LiteralSuffixUpperCase.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/OrderByRepeated.Fixed.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/OrderByRepeated.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/RedundantToCharArrayCall.Fixed.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/RedundantToCharArrayCall.cs
sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ReturnEmptyCollectionInsteadOfNull.cs

Related to #3768 (another small change will be made tomorrow)
Fixes #3767
Fixes #3766 !!
Fixes #3764
Fixes #3762
Fixes #3760
Partial fix for #3731 (another small change tomorrow)

Improve performance for 17 rules

---

scripts/build/dev-build.ps1
scripts/rspec/rspec2resx.ps1
sonar-csharp-plugin/src/test/java/org/sonar/plugins/csharp/CSharpSonarRulesDefinitionTest.java
sonar-vbnet-plugin/src/test/java/org/sonar/plugins/vbnet/VbNetSonarRulesDefinitionTest.java
sonaranalyzer-dotnet/rspec/cs/S2228_c#.html
sonaranalyzer-dotnet/rspec/cs/S2228_c#.json
sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/RspecStrings.resx
sonaranalyzer-dotnet/src/SonarAnalyzer.RuleDescriptorGenerator/Descriptors/RuleDetail.cs
sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/RuleDescriptors/RuleDetail.cs
sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/RuleDetailBuilder.cs
sonaranalyzer-dotnet/src/SonarAnalyzer.Utilities/Rules.Description/S2228.html
sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/RspecStrings.resx

Update rules.xml generation to include status

---

its/pom.xml

Update orchestrator to version 3.34.0.2692

---

.github/workflows/RequestReview.yml

This fixes issue that appeared when the action was triggered for PR from external fork.

GitHub workflow: Don't run Request review for external PRs

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/MethodParameterUnused.CSharp8.cs

Adds test case to document the FP from #3803

Document FP from #3803

---

.github/workflows/StartProgress.yml

Assign to sender when card is moved from `To do` to `In progress` column on the Best Kanban

GitHub workflow: Start progress

---

analyzers/src/SonarAnalyzer.CFG/ControlFlowGraph/CSharpControlFlowGraphBuilder.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/MethodParameterUnused.cs
analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/CSharp/CSharpExplodedGraph.cs
analyzers/tests/SonarAnalyzer.UnitTest/ControlFlowGraph/ControlFlowGraphTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/ExplodedGraphTests.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ConditionEvaluatesToConstant.CSharp7.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ConditionEvaluatesToConstant.CSharp8.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/MethodParameterUnused.CSharp8.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/MethodParameterUnused.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/MethodParameterUnused.cs

Fix S1172 FP: Issue is raised when parameter is used in tuple creation

---

analyzers/src/SonarAnalyzer.CSharp/Rules/UnchangedLocalVariablesShouldBeConst.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnchangedLocalVariablesShouldBeConst.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnchangedLocalVariablesShouldBeConst.cs

Fix S3353 FP: With Tuple Assignment

---

analyzers/src/SonarAnalyzer.CSharp/Helpers/CSharpSymbolUsageCollector.cs
analyzers/src/SonarAnalyzer.CSharp/Helpers/CSharpSyntaxHelper.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/UnchangedLocalVariablesShouldBeConst.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/UnusedPrivateMember.cs
analyzers/tests/SonarAnalyzer.UnitTest/Helpers/SyntaxHelperTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnchangedLocalVariablesShouldBeConst.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnusedPrivateMember.CSharp7.cs

S1144 FP: tuple construction should be considered for member usage

---

analyzers/src/SonarAnalyzer.CSharp/Rules/DoNotExposeListT.cs
analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/DoNotExposeListTTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DoNotExposeListT.CSharp8.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DoNotExposeListT.cs

Fix S3956 FP: Don't raise on properties marked with XmlElement attribute

---

analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Common/SymbolicValues/SymbolicValue.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/SymbolicValues/SymbolicValue_TrySetConstraint.cs

Add handling for updating ByteArray and CryptographyIV constraints

---

analyzers/src/SonarAnalyzer.CSharp/Rules/ConditionEvaluatesToConstant.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/InvalidCastToInterfaceSymbolicExecution.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/EmptyCollectionsShouldNotBeEnumerated.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/EmptyNullableValueAccess.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/NullPointerDereference.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/ObjectsShouldNotBeDisposedMoreThanOnce.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/RestrictDeserializedTypes.cs
analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/CSharp/CSharpExplodedGraph.cs

Use ProgramPoint.CurrentInstruction to simplify code

---

analyzers/rspec/cs/S3168_c#.html
analyzers/src/SonarAnalyzer.CSharp/Rules/AsyncVoidMethod.cs
analyzers/src/SonarAnalyzer.Common/Helpers/KnownMethods.cs
analyzers/src/SonarAnalyzer.Utilities/Rules.Description/S3168.html
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/AsyncVoidMethod.cs

S3168: Broaden detection of event handlers

---

analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/CSharp/CSharpExplodedGraph.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ConditionEvaluatesToConstant.CSharp7.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ConditionEvaluatesToConstant.CSharp8.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/ParseOptionsHelper.cs

S2583 and S2589 FP: Pattern matching generates wrong bool constraint

---

analyzers/its/expected/akka.net/Akka-{5DEDDF90-37F0-48D3-A0B0-A5CBD8A7E377}-S2325.json
analyzers/its/expected/akka.net/Akka.Persistence-{FCA84DEA-C118-424B-9EB8-34375DFEF18A}-S2325.json
analyzers/src/SonarAnalyzer.CSharp/Rules/MemberShouldBeStatic.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/MemberShouldBeStatic.cs

Fix S2325 FP: Do not raise for methods inside generic class

---

analyzers/tests/SonarAnalyzer.UnitTest/Rules/HashesShouldHaveUnpredictableSaltTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/HashesShouldHaveUnpredictableSalt.cs

Rule S2053: Add more test cases

---

analyzers/src/SonarAnalyzer.CSharp/Rules/DoNotCallGCSuppressFinalize.cs
analyzers/src/SonarAnalyzer.Common/Helpers/KnownMethods.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DoNotCallGCSuppressFinalize.Net5.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DoNotCallGCSuppressFinalize.NetCore.cs

Fix S3971 FP: Support IAsyncDisposable

---

analyzers/rspec/cs/S3927_c#.html
analyzers/rspec/vbnet/S3927_vb.net.html
analyzers/src/SonarAnalyzer.CSharp/Rules/ImplementSerializationMethodsCorrectly.cs
analyzers/src/SonarAnalyzer.Common/Rules/ImplementSerializationMethodsCorrectlyBase.cs
analyzers/src/SonarAnalyzer.Utilities/Rules.Description/S3927_cs.html
analyzers/src/SonarAnalyzer.Utilities/Rules.Description/S3927_vb.html
analyzers/src/SonarAnalyzer.VisualBasic/Rules/ImplementSerializationMethodsCorrectly.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ImplementSerializationMethodsCorrectly.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ImplementSerializationMethodsCorrectly.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ImplementSerializationMethodsCorrectly.vb

Fix S3927 FP and FN: Internal, protected and static methods

---

analyzers/src/SonarAnalyzer.CSharp/Rules/WeakSslTlsProtocols.cs
analyzers/src/SonarAnalyzer.Common/Rules/WeakSslTlsProtocolsBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/WeakSslTlsProtocols.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/WeakSslTlsProtocols.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/WeakSslTlsProtocols.vb

Fix S4423 FPs: If statements, unary negations

---

analyzers/its/expected/akka.net/Akka-{5DEDDF90-37F0-48D3-A0B0-A5CBD8A7E377}-S107.json
analyzers/its/expected/akka.net/Akka.Remote-{EA4FF8FD-7C53-49C8-B9AA-02E458B3E6A7}-S107.json
analyzers/src/SonarAnalyzer.CSharp/Rules/TooManyParameters.cs
analyzers/src/SonarAnalyzer.Common/Rules/TooManyParametersBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/TooManyParameters.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/TooManyParametersTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/TooManyParameters_CustomValues.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/TooManyParameters_CustomValues.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/TooManyParameters_CustomValues.vb

Fix S107 FPs: Don't count base constructor parameter in the threshold

---

analyzers/src/SonarAnalyzer.CSharp/Rules/BinaryOperationWithIdenticalExpressions.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/CallerInformationParametersShouldBeLast.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/CheckFileLicenseCodeFixProvider.cs
analyzers/src/SonarAnalyzer.Common/Helpers/SemanticModelExtensions.cs
analyzers/src/SonarAnalyzer.Common/Rules/VariableUnusedBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Helpers/VisualBasicMethodParameterLookup.cs
analyzers/src/SonarAnalyzer.VisualBasic/Helpers/VisualBasicSyntaxWalkerHelper.cs

Should fix existing S1451
https://sonarcloud.io/project/issues?id=sonaranalyzer-dotnet&open=AXCtNZDhAFhjSEJCuYfS&resolved=false&rules=csharpsquid%3AS1451

Fix code smells: Update file headers

---

analyzers/src/SonarAnalyzer.CSharp/Helpers/CSharpSymbolUsageCollector.cs
analyzers/src/SonarAnalyzer.Common/Helpers/TypeHelper.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnusedPrivateMember.CSharp7.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnusedPrivateMember.CSharp8.cs

Fixes #2478
(I opened #3842 for the C# 8 found FPs)

Fix S1144 FP: Support tuple deconstruction for C# 7 syntax

---

analyzers/its/expected/Nancy/Nancy-{34576216-0DCA-4B0F-A0DC-9075E75A676F}-S2328.json
analyzers/its/expected/Nancy/Nancy.Tests-{776D244D-BC4D-4BBB-A478-CAF2D04520E1}-S2328.json
analyzers/its/expected/Net5/Net5--S2328.json
analyzers/its/expected/akka.net/Akka-{5DEDDF90-37F0-48D3-A0B0-A5CBD8A7E377}-S2328.json
analyzers/src/SonarAnalyzer.CSharp/Rules/GetHashCodeMutable.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/GetHashCodeMutable.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/GetHashCodeMutable.cs

Trim S2328 message

---

analyzers/its/expected/Ember-MM/EmberAPI-{208AA35E-C6AE-4D2D-A9DD-B6EFD19A4279}-S4790.json
analyzers/its/expected/Nancy/Nancy-{34576216-0DCA-4B0F-A0DC-9075E75A676F}-S4790.json
analyzers/its/expected/Nancy/Nancy-{34576216-0DCA-4B0F-A0DC-9075E75A676F}-S4834.json
analyzers/its/expected/Nancy/Nancy.Demo.Authentication-{5F2DD52D-471B-4946-8F7B-F050C88EFC52}-S4834.json
analyzers/its/expected/Nancy/Nancy.Demo.Authentication.Basic-{911196F4-B88F-4940-B1FD-D30F5290D06D}-S4834.json
analyzers/its/expected/Nancy/Nancy.Demo.Authentication.Forms-{98940A30-1B48-4F71-A6BA-85F0AAF31A2F}-S4834.json
analyzers/its/expected/Nancy/Nancy.Demo.Authentication.Stateless-{BAE74CD5-57C2-40E3-8F7A-EDE5721C2ACC}-S4834.json
analyzers/its/expected/Nancy/Nancy.Hosting.Self-{AA7F66EB-EC2C-47DE-855F-30B3E6EF2134}-S4834.json
analyzers/its/expected/akka.net/Akka.Cluster-{6AB00F61-269A-4501-B06A-026707F000A7}-S4790.json
analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/ControllingPermissionsBase.cs
analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/CreatingHashAlgorithmsBase.cs
analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/ExecutingSqlQueriesBase.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/CreatingHashAlgorithmsTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ControllingPermissions.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ControllingPermissions.vb
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CreatingHashAlgorithms.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CreatingHashAlgorithms.vb
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ExecutingSqlQueries_Net46.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ExecutingSqlQueries_Net46.vb

Fixes #3626 
Fixes #3628
Fixes #3627

Update messages for S2077, S4834 and S4790

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ConditionEvaluatesToConstant.CSharp7.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/NullPointerDereference.CSharp7.cs

Add FP and FN reproducers for issue 2528

---

analyzers/rspec/cs/S5042_c#.html
analyzers/rspec/cs/S5042_c#.json
analyzers/rspec/vbnet/S5042_vb.net.html
analyzers/rspec/vbnet/S5042_vb.net.json
analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/ExpandingArchives.cs
analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/ExpandingArchivesBase.cs
analyzers/src/SonarAnalyzer.Utilities/Rules.Description/S5042_cs.html
analyzers/src/SonarAnalyzer.Utilities/Rules.Description/S5042_vb.html
analyzers/src/SonarAnalyzer.VisualBasic/Rules/Hotspots/ExpandingArchives.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/ExpandingArchivesTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ExpandingArchives.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ExpandingArchives.vb

Rule S5042 focus on zipbomb attacks (#3621)

---

analyzers/rspec/cs/S1313_c#.html
analyzers/rspec/vbnet/S1313_vb.net.html
analyzers/src/SonarAnalyzer.CSharp/Rules/HardcodedIpAddress.cs
analyzers/src/SonarAnalyzer.Common/Rules/HardcodedIpAddressBase.cs
analyzers/src/SonarAnalyzer.Utilities/Rules.Description/S1313_cs.html
analyzers/src/SonarAnalyzer.Utilities/Rules.Description/S1313_vb.html
analyzers/src/SonarAnalyzer.VisualBasic/Rules/HardcodedIpAddress.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/HardcodedIpAddressTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/HardcodedIpAddress.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/HardcodedIpAddress.vb

Rule S1313 should not raise when loopback, broadcast addresses are used (#3450)

---

analyzers/its/expected/Ember-MM/scraper.EmberCore-{EF6A550E-DD76-4F4D-8250-8598140F828B}-S4784.json
analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/UsingRegularExpressions.cs
analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/UsingRegularExpressionsBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/Hotspots/UsingRegularExpressions.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/UsingRegularExpressionsTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UsingRegularExpressions.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UsingRegularExpressions.vb

Fix S4784 FN: Process const regex

---

analyzers/src/SonarAnalyzer.CSharp/Rules/CertificateValidationCheck.cs
analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
analyzers/src/SonarAnalyzer.Common/Rules/CertificateValidationCheckBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/CertificateValidationCheck.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/CertificateValidationCheckTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CertificateValidationCheck.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CertificateValidationCheck.vb

Fix S4830 FN: Match DangerousAcceptAnyServerCertificateValidator

---

analyzers/rspec/cs/S5547_c#.html
analyzers/src/SonarAnalyzer.CSharp/Rules/DoNotCallInsecureSecurityAlgorithm.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/InsecureEncryptionAlgorithm.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/InsecureHashAlgorithm.cs
analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
analyzers/src/SonarAnalyzer.Utilities/Rules.Description/S5547.html
analyzers/tests/SonarAnalyzer.UnitTest/Rules/InsecureEncryptionAlgorithmTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/InsecureEncryptionAlgorithm.cs

Fix 5547 FN AesFastEngine algorithm is vulnerable to side channel attack (#3330)

---

analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/DoNotHardcodeCredentials.cs
analyzers/src/SonarAnalyzer.CSharp/SyntaxTrackers/CSharpObjectCreationTracker.cs
analyzers/src/SonarAnalyzer.CSharp/SyntaxTrackers/CSharpPropertyAccessTracker.cs
analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/DoNotHardcodeCredentialsBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/Hotspots/DoNotHardcodeCredentials.cs
analyzers/src/SonarAnalyzer.VisualBasic/SyntaxTrackers/VisualBasicObjectCreationTracker.cs
analyzers/src/SonarAnalyzer.VisualBasic/SyntaxTrackers/VisualBasicPropertyAccessTracker.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/DoNotHardcodeCredentialsTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/SyntaxTrackers/PropertyAccessTrackerTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DoNotHardcodeCredentials_DefaultValues.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DoNotHardcodeCredentials_DefaultValues.vb

Improve S2068: Detect constant concatenation

---

analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/DoNotHardcodeCredentials.cs
analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/DoNotHardcodeCredentialsBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/Hotspots/DoNotHardcodeCredentials.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DoNotHardcodeCredentials_DefaultValues.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DoNotHardcodeCredentials_DefaultValues.vb

Fixes #3885
This is a draft PR, rebase will be needed. Only the last commit needs review.

Improve S2068: Detect interpolation with constant values

---

analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/DoNotHardcodeCredentials.cs
analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/DoNotHardcodeCredentialsBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/Hotspots/DoNotHardcodeCredentials.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DoNotHardcodeCredentials_DefaultValues.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DoNotHardcodeCredentials_DefaultValues.vb

Fixes #3884
This is a draft, rebase will be needed. Only commits from 69f85c2 needs review.

Improve S2068: Detect string.Format with constant values

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/NullPointerDereference.cs

S2259: Add FP repro for #3850

---

analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/ExecutingSqlQueries.cs
analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/ExecutingSqlQueriesBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/Hotspots/ExecutingSqlQueries.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/ExecutingSqlQueriesTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ExecutingSqlQueries_Net46.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ExecutingSqlQueries_Net46.vb

Rule S2077 concatenated value tracking (#3292)

---

analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/DoNotHardcodeCredentials.cs
analyzers/src/SonarAnalyzer.CSharp/SyntaxTrackers/CSharpAssignmentFinder.cs
analyzers/src/SonarAnalyzer.CSharp/SyntaxTrackers/CSharpBuilderPatternCondition.cs
analyzers/src/SonarAnalyzer.CSharp/SyntaxTrackers/CSharpStringConstantFinder.cs
analyzers/src/SonarAnalyzer.Common/SyntaxTrackers/AssignmentFinder.cs
analyzers/src/SonarAnalyzer.Common/SyntaxTrackers/BuilderPatternCondition.cs
analyzers/src/SonarAnalyzer.Common/SyntaxTrackers/StringConstantFinder.cs
analyzers/src/SonarAnalyzer.VisualBasic/Helpers/SyntaxNodeExtensions.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/Hotspots/DoNotHardcodeCredentials.cs
analyzers/src/SonarAnalyzer.VisualBasic/SyntaxTrackers/VisualBasicAssignmentFinder.cs
analyzers/src/SonarAnalyzer.VisualBasic/SyntaxTrackers/VisualBasicBuilderPatternCondition.cs
analyzers/src/SonarAnalyzer.VisualBasic/SyntaxTrackers/VisualBasicStringConstantFinder.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DoNotHardcodeCredentials_DefaultValues.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DoNotHardcodeCredentials_DefaultValues.vb

Fixes #3883
Review per commit should show you how it was done and what piece solves what task.

Improve S2068: Detect fields and variable initialized to constant

---

analyzers/its/expected/Ember-MM/scraper.EmberCore-{EF6A550E-DD76-4F4D-8250-8598140F828B}-S4784.json
analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/UsingRegularExpressions.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/Hotspots/UsingRegularExpressions.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UsingRegularExpressions.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UsingRegularExpressions.vb

Improve S4784: Detect constant value propagation

---

analyzers/its/expected/akka.net/Akka.Persistence.TestKit-{AD9418B6-C452-4169-94FB-D43DE0BFA966}-S2275.json
analyzers/src/SonarAnalyzer.CSharp/Rules/StringFormatValidator.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/StringFormatRuntimeExceptionFreeValidator.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/StringFormatTypoFreeValidator.cs

Improve S2275 S3457: Detect constant value propagation

---

analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/UsingCookies.cs
analyzers/src/SonarAnalyzer.CSharp/SyntaxTrackers/CSharpElementAccessTracker.cs
analyzers/src/SonarAnalyzer.CSharp/SyntaxTrackers/CSharpInvocationTracker.cs
analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/UsingCookiesBase.cs
analyzers/src/SonarAnalyzer.Common/SyntaxTrackers/ElementAccessTracker.cs
analyzers/src/SonarAnalyzer.Common/SyntaxTrackers/InvocationTracker.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/Hotspots/UsingCookies.cs
analyzers/src/SonarAnalyzer.VisualBasic/SyntaxTrackers/VisualBasicElementAccessTracker.cs
analyzers/src/SonarAnalyzer.VisualBasic/SyntaxTrackers/VisualBasicInvocationTracker.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/UsingCookiesTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/SyntaxTrackers/ElementAccessTrackerTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/SyntaxTrackers/InvocationTrackerTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UsingCookies_NetCore.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UsingCookies_NetCore.vb

Improve S2255: Detect constant value propagation

---

analyzers/src/SonarAnalyzer.CSharp/Helpers/CSharpSymbolUsageCollector.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/GenericTypeParameterUnused.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/MemberInitializerRedundant.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/MethodParameterUnused.cs
analyzers/src/SonarAnalyzer.Common/Helpers/SyntaxNodeExtensions.cs
analyzers/src/SonarAnalyzer.Common/SyntaxTrackers/ConstantValueFinder.cs
analyzers/tests/SonarAnalyzer.UnitTest/SyntaxTrackers/ConstantValueFinderTest.cs

Fix S2068 and constant lookup for partial classes

---

analyzers/its/expected/Ember-MM/Ember Media Manager-{9B57D3AB-AF12-4012-B945-284C2448DC81}-S2077.json
analyzers/its/expected/Ember-MM/EmberAPI-{208AA35E-C6AE-4D2D-A9DD-B6EFD19A4279}-S2077.json
analyzers/its/expected/Ember-MM/generic.EmberCore.NMT-{84B2143A-D04F-4262-923D-21AEDF86E2B7}-S2077.json
analyzers/its/expected/Ember-MM/generic.EmberCore.OfflineHolder-{E7FDD1C9-BCF7-4624-B033-D3888E422A8B}-S2077.json
analyzers/its/expected/Ember-MM/generic.EmberCore.WebServer-{64D6F035-F186-4193-AF35-D20126B8DA64}-S2077.json
analyzers/its/expected/Ember-MM/scraper.EmberCore-{EF6A550E-DD76-4F4D-8250-8598140F828B}-S2077.json
analyzers/its/expected/akka.net/Akka.Persistence.Sqlite-{453EFD22-7C53-4887-9DBF-FCFC9172E909}-S2077.json
analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/ExecutingSqlQueries.cs
analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/ExecutingSqlQueriesBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/Hotspots/ExecutingSqlQueries.cs
analyzers/tests/SonarAnalyzer.UnitTest/MetadataReferences/NuGetMetadataReference.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/ExecutingSqlQueriesTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ExecutingSqlQueries_Net46.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ExecutingSqlQueries_Net46.vb

Rule S2077: support of more database libraries (#3293)

---

analyzers/src/SonarAnalyzer.CSharp/Rules/EncryptionAlgorithmsShouldBeSecure.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/JwtSigned.cs
analyzers/src/SonarAnalyzer.CSharp/SyntaxTrackers/CSharpInvocationTracker.cs
analyzers/src/SonarAnalyzer.Common/Rules/EncryptionAlgorithmsShouldBeSecureBase.cs
analyzers/src/SonarAnalyzer.Common/Rules/JwtSignedBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/EncryptionAlgorithmsShouldBeSecure.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/JwtSigned.cs
analyzers/src/SonarAnalyzer.VisualBasic/SyntaxTrackers/VisualBasicInvocationTracker.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/EncryptionAlgorithmsShouldBeSecure.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/EncryptionAlgorithmsShouldBeSecure.vb
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/JwtSigned.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/JwtSigned.vb

Improve S5542, S5659: Detect constant value propagation

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ClassNotInstantiatable.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnusedPrivateMember.CSharp9.cs

Reproducers from [community post](https://community.sonarsource.com/t/c-9-fp-linked-to-private-constructors-and-the-new-terse-new-syntax/36469/2)

Add S3453 and S1144 FP repros for C# 9

---

analyzers/src/SonarAnalyzer.CSharp/Rules/ClearTextProtocolsAreSensitive.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/CryptographicKeyShouldNotBeTooShort.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/LdapConnectionShouldBeSecure.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/LdapConnectionShouldBeSecureTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ClearTextProtocolsAreSensitive.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CryptographicKeyShouldNotBeTooShort.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CryptographicKeyShouldNotBeTooShort.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/LdapConnectionShouldBeSecure.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/LdapConnectionShouldBeSecure.cs

Improve S5332, S4426, S4433: Detect constant value propagation

---

sonar-csharp-plugin/pom.xml
sonar-dotnet-shared-library/pom.xml
sonar-vbnet-plugin/pom.xml

update guava version

---

analyzers/src/SonarAnalyzer.CSharp/Rules/RedundantJumpStatement.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundantJumpStatement.cs

Fix S3626 FP: Redundant jump for "throw expressions"

---

analyzers/src/SonarAnalyzer.CSharp/Helpers/CSharpSyntaxHelper.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/ExecutingSqlQueries.cs
analyzers/src/SonarAnalyzer.CSharp/SyntaxTrackers/CSharpFieldAccessTracker.cs
analyzers/src/SonarAnalyzer.CSharp/SyntaxTrackers/CSharpInvocationTracker.cs
analyzers/src/SonarAnalyzer.CSharp/SyntaxTrackers/CSharpObjectCreationTracker.cs
analyzers/src/SonarAnalyzer.CSharp/SyntaxTrackers/CSharpPropertyAccessTracker.cs
analyzers/src/SonarAnalyzer.VisualBasic/Helpers/VisualBasicSyntaxHelper.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/Hotspots/ExecutingSqlQueries.cs
analyzers/src/SonarAnalyzer.VisualBasic/SyntaxTrackers/VisualBasicFieldAccessTracker.cs
analyzers/src/SonarAnalyzer.VisualBasic/SyntaxTrackers/VisualBasicInvocationTracker.cs
analyzers/src/SonarAnalyzer.VisualBasic/SyntaxTrackers/VisualBasicObjectCreationTracker.cs
analyzers/src/SonarAnalyzer.VisualBasic/SyntaxTrackers/VisualBasicPropertyAccessTracker.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DoNotHardcodeCredentials_DefaultValues.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DoNotHardcodeCredentials_DefaultValues.vb

Improve S2068 : Detect constant value propagation for properties and constructors

---

docs/contributing-analyzer.md

document manuallyAddedNonCompliantIssues IT

---

analyzers/src/SonarAnalyzer.CSharp/Rules/UninvokedEventDeclaration.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UninvokedEventDeclaration.cs

Rule S3264: add repro for #3931

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ConditionEvaluatesToConstant.CSharp7.cs

S2589: Add FP and FN repro for #3910

---

analyzers/src/SonarAnalyzer.CSharp/Rules/XXE/XmlReaderSettingsValidator.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/XmlExternalEntityShouldNotBeParsed.cs
analyzers/src/SonarAnalyzer.CSharp/SyntaxTrackers/CSharpObjectInitializationTracker.cs
analyzers/src/SonarAnalyzer.Common/Common/SecondaryLocation.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/XmlExternalEntityShouldNotBeParsedTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/XmlExternalEntityShouldNotBeParsed_AlwaysSafe.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/XmlExternalEntityShouldNotBeParsed_XPathDocument_Net35.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/XmlExternalEntityShouldNotBeParsed_XPathDocument_Net4.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/XmlExternalEntityShouldNotBeParsed_XPathDocument_Net452.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/XmlExternalEntityShouldNotBeParsed_XmlReader_CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/XmlExternalEntityShouldNotBeParsed_XmlReader_ExternalParameter.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/XmlExternalEntityShouldNotBeParsed_XmlReader_Net35.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/XmlExternalEntityShouldNotBeParsed_XmlReader_Net4.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/XmlExternalEntityShouldNotBeParsed_XmlReader_Net452.cs

Display secondary locations for S2755

---

analyzers/its/expected/Nancy/Nancy-{34576216-0DCA-4B0F-A0DC-9075E75A676F}-S4790.json
analyzers/src/SonarAnalyzer.CSharp/Rules/DoNotCallInsecureSecurityAlgorithm.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/CreatingHashAlgorithms.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/InsecureEncryptionAlgorithm.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/InsecureHashAlgorithm.cs
analyzers/src/SonarAnalyzer.CSharp/SyntaxTrackers/CSharpInvocationTracker.cs
analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/CreatingHashAlgorithmsBase.cs
analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/UsingCookiesBase.cs
analyzers/src/SonarAnalyzer.Common/SyntaxTrackers/InvocationTracker.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/Hotspots/CreatingHashAlgorithms.cs
analyzers/src/SonarAnalyzer.VisualBasic/SyntaxTrackers/VisualBasicInvocationTracker.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/CreatingHashAlgorithmsTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/SyntaxTrackers/InvocationTrackerTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CreatingHashAlgorithms.NetFramework.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CreatingHashAlgorithms.NetFramework.vb
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CreatingHashAlgorithms.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CreatingHashAlgorithms.vb

Deprecated S2070 and update S4790

---

analyzers/rspec/cs/S1206_c#.html
analyzers/rspec/cs/S2971_c#.html
analyzers/rspec/cs/S3875_c#.html
analyzers/rspec/cs/S3881_c#.html
analyzers/rspec/cs/S4635_c#.html
analyzers/src/SonarAnalyzer.CSharp/RspecStrings.resx
analyzers/src/SonarAnalyzer.CSharp/sonarpedia.json
analyzers/src/SonarAnalyzer.Utilities/Rules.Description/S1206.html
analyzers/src/SonarAnalyzer.Utilities/Rules.Description/S2971.html
analyzers/src/SonarAnalyzer.Utilities/Rules.Description/S3875.html
analyzers/src/SonarAnalyzer.Utilities/Rules.Description/S3881.html
analyzers/src/SonarAnalyzer.Utilities/Rules.Description/S4635.html
analyzers/src/SonarAnalyzer.VisualBasic/sonarpedia.json

Updates the RSPECs for CS and VBNET

RSPEC update

---

analyzers/src/SonarAnalyzer.CSharp/Rules/DoNotCallInsecureSecurityAlgorithm.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/InsecureEncryptionAlgorithm.cs

Rule S5547: Fix FN when ConvertedType is not same as Type

---

analyzers/rspec/cs/S4564_c#.html
analyzers/rspec/cs/S4564_c#.json
analyzers/src/SonarAnalyzer.CSharp/RspecStrings.resx
analyzers/src/SonarAnalyzer.Utilities/Rules.Description/S4564.html

Fixes #3211
Fixes #3160 (as we deprecated it, we won't fix the FP)

Deprecate S4564 in favor of S5753

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ConditionEvaluatesToConstant.CSharp8.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ConditionEvaluatesToConstant.cs

Rule S2583: Add repro for #3955

---

analyzers/src/SonarAnalyzer.Common/Rules/SillyBitwiseOperationBase.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SillyBitwiseOperation.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SillyBitwiseOperation.Fixed.vb
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SillyBitwiseOperation.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SillyBitwiseOperation.vb

Fix FP found on Peach, related to #3970

Fix S2437 FP: Tracked Enum variable initialized to zero

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/BooleanLiteralUnnecessary.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/BooleanLiteralUnnecessary.cs

See: https://community.sonarsource.com/t/s1905-false-positives-generated-within-c-ternary-operator-statement/36717

Rule S1125: Add code example from community

---

analyzers/src/SonarAnalyzer.CSharp/Rules/DoNotCheckZeroSizeCollection.cs
analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
analyzers/src/SonarAnalyzer.Common/Rules/DoNotCheckZeroSizeCollectionBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/DoNotCheckZeroSizeCollection.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/DoNotCheckZeroSizeCollectionTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DoNotCheckZeroSizeCollection.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DoNotCheckZeroSizeCollection.vb

S3981 FN fix: Not raised for IList and ICollection

---

analyzers/src/SonarAnalyzer.Common/Rules/BeginInvokePairedWithEndInvokeBase.cs
analyzers/src/SonarAnalyzer.Common/Rules/DoNotCallInsecureSecurityAlgorithmBase.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/BeginInvokePairedWithEndInvoke.vb
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/InsecureEncryptionAlgorithm.vb
analyzers/tests/SonarAnalyzer.UnitTest/TestCasesForRuleFailure/SpecialCases.vb

Fix NRE S4583 and S5547: Invocation expression is null for VB

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnchangedLocalVariablesShouldBeConst.cs

Add FP repro for #4015

---

analyzers/rspec/cs/S4261_c#.html
analyzers/rspec/cs/S4261_c#.json
analyzers/src/SonarAnalyzer.CSharp/RspecStrings.resx
analyzers/src/SonarAnalyzer.CSharp/Rules/MethodShouldBeNamedAccordingToSynchronicity.cs
analyzers/src/SonarAnalyzer.Utilities/Rules.Description/S4261.html

Fixes #3928
More details here: https://community.sonarsource.com/t/s4261-has-incorrect-examples/36324/7

Deprecate S4261

---

analyzers/rspec/cs/S4834_c#.html
analyzers/rspec/cs/S4834_c#.json
analyzers/rspec/vbnet/S4834_vb.net.html
analyzers/rspec/vbnet/S4834_vb.net.json
analyzers/src/SonarAnalyzer.CSharp/RspecStrings.resx
analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/ControllingPermissions.cs
analyzers/src/SonarAnalyzer.Utilities/Rules.Description/S4834_cs.html
analyzers/src/SonarAnalyzer.Utilities/Rules.Description/S4834_vb.html
analyzers/src/SonarAnalyzer.VisualBasic/RspecStrings.resx
analyzers/src/SonarAnalyzer.VisualBasic/Rules/Hotspots/ControllingPermissions.cs

Deprecate S4834

---

analyzers/src/SonarAnalyzer.VisualBasic/Rules/UseReturnStatement.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UseReturnStatement.vb

Related to #2159 
Attribute name issue was found on Peach.

Fix S5944 FP: Attribute and named argument

---

analyzers/pom.xml
analyzers/sonaranalyzer-maven-artifacts/SonarAnalyzer.CSharp/pom.xml
analyzers/sonaranalyzer-maven-artifacts/SonarAnalyzer.RuleDocGenerator.CSharp/pom.xml
analyzers/sonaranalyzer-maven-artifacts/SonarAnalyzer.RuleDocGenerator.VisualBasic/pom.xml
analyzers/sonaranalyzer-maven-artifacts/SonarAnalyzer.VisualBasic/pom.xml
analyzers/sonaranalyzer-maven-artifacts/pom.xml
analyzers/src/AssemblyInfo.Shared.cs
analyzers/src/SonarAnalyzer.CFG/SonarAnalyzer.CFG.cs.nuspec
analyzers/src/SonarAnalyzer.Vsix/SonarAnalyzer.CSharp.nuspec
analyzers/src/SonarAnalyzer.Vsix/SonarAnalyzer.VisualBasic.nuspec
analyzers/src/SonarAnalyzer.Vsix/source.extension.vsixmanifest
pom.xml
scripts/version/Version.props
sonar-csharp-plugin/pom.xml
sonar-dotnet-shared-library/pom.xml
sonar-vbnet-plugin/pom.xml

Bump version to 8.19

---

its/projects/CoverageWithDeterministicSourcePaths/CoverageWithDeterministicSourcePaths.Tests/FooTests.cs
its/projects/CoverageWithDeterministicSourcePaths/CoverageWithDeterministicSourcePaths/Foo.cs
its/projects/CoverageWithDeterministicSourcePaths/VisualStudio.coveragexml
its/projects/CoverageWithDeterministicSourcePaths/opencover.xml
its/src/test/java/com/sonar/it/csharp/CoverageTest.java
sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/FileService.java
sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/OpenCoverReportParser.java
sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/OpenCoverReportParserTest.java
sonar-dotnet-shared-library/src/test/resources/opencover/deterministic_source_paths.xml

Add OpenCover support for deterministic build

---

azure-pipelines.yml

Use new version of common templates:
https://sonarsource.visualstudio.com/DotNetTeam%20Project/_git/pipelines-yaml-templates/pullrequest/14
As this step renames steps, we need to:
* remove `Sonar.Net (Promote artifacts on repox and notify Burgr promoteBurgr)` required checks
* merge this
* add `Sonar.Net (Artifacts: Notify Burgr)` required checks

Update commonTemplates to v1.0.10

---

analyzers/src/SonarAnalyzer.CSharp/Rules/BypassingAccessibility.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/BypassingAccessibility.cs
analyzers/tests/SonarAnalyzer.UnitTest/Common/RuleTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/BypassingAccessibilityTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Hotspots/ClearTextProtocolsAreSensitiveTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Hotspots/CommandPathTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Hotspots/ConfiguringLoggersTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Hotspots/ControllingPermissionsTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Hotspots/CookieShouldBeHttpOnlyTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Hotspots/CookieShouldBeSecureTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Hotspots/CreatingHashAlgorithmsTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Hotspots/DeliveringDebugFeaturesInProductionTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Hotspots/DisablingRequestValidationTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Hotspots/DoNotHardcodeCredentialsTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Hotspots/DoNotUseRandomTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Hotspots/EncryptingDataTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Hotspots/ExecutingSqlQueriesTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Hotspots/ExpandingArchivesTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Hotspots/HardcodedIpAddressTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Hotspots/ReadingStandardInputTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Hotspots/SocketsCreationTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Hotspots/UsingCommandLineArgumentsTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Hotspots/UsingCookiesTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Hotspots/UsingNonstandardCryptographyTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Hotspots/UsingRegularExpressionsTest.cs

Clean hotpot rules

---

analyzers/src/SonarAnalyzer.CFG/ControlFlowGraph/CSharpControlFlowGraphBuilder.cs
analyzers/tests/SonarAnalyzer.UnitTest/ControlFlowGraph/ControlFlowGraphTest.cs

Don't count lambdas in too complex CFG expression count

---

analyzers/src/SonarAnalyzer.CSharp/Helpers/CSharpDiagnosticAnalyzerContextHelper.cs
analyzers/src/SonarAnalyzer.Common/Helpers/DiagnosticAnalyzerContextHelper.cs
analyzers/src/SonarAnalyzer.VisualBasic/Helpers/VisualBasicDiagnosticAnalyzerContextHelper.cs

Fixes #4048
Review per commit is suggested to see the action and the cleanup separately

Missing files on SonarCloud with wrong license headers

---

sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/DotNetSensor.java
sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/DotNetSensorTest.java

Log warning when there are only tests in the SQ/SC project

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DeadStores.cs

I tried to the fix the bug #3719.
But I was only able to create the repro. If you agree we can make it public available.
Unfortunately I was not able to fix the bug because the implementation of "DeadStore" is very complex and the documentation (comments) is "limited"...
Maybe someone else is able to fix the problem with my repro.

S1854: Add FP repro for #3719

---

its/src/test/java/com/sonar/it/csharp/MultipleProjectsTest.java
sonar-csharp-plugin/src/main/java/org/sonar/plugins/csharp/CSharpPlugin.java
sonar-csharp-plugin/src/test/java/org/sonar/plugins/csharp/CSharpPluginTest.java
sonar-dotnet-shared-library/pom.xml
sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/StringUtils.java
sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/AbstractModuleConfiguration.java
sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/DotNetSensor.java
sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/FileTypeSensor.java
sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/ProjectTypeCollector.java
sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/ProtobufDataImporter.java
sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/RoslynDataImporter.java
sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/SensorContextUtils.java
sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/DotNetSensorTest.java
sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/FileTypeSensorTest.java
sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/ProjectTypeCollectorTest.java
sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/PropertiesSensorTest.java
sonar-vbnet-plugin/src/main/java/org/sonar/plugins/vbnet/VbNetPlugin.java
sonar-vbnet-plugin/src/test/java/org/sonar/plugins/vbnet/VbNetPluginTest.java

Log MAIN and TEST projects summary as INFO level

---

analyzers/src/SonarAnalyzer.CFG/ControlFlowGraph/CSharpControlFlowGraph.cs
analyzers/src/SonarAnalyzer.CSharp/CBDE/MlirExporter.cs
analyzers/src/SonarAnalyzer.CSharp/Helpers/CSharpDiagnosticAnalyzerContextHelper.cs
analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/CSharp/CSharpExplodedGraph.cs
analyzers/src/SonarAnalyzer.Common/Rules/Utilities/UtilityAnalyzerBase.cs

Remove old ToDo comments

---

sonar-csharp-plugin/src/main/java/org/sonar/plugins/csharp/CSharpPlugin.java
sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/package-info.java
sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/FileTypeSensorTest.java
sonar-vbnet-plugin/src/main/java/org/sonar/plugins/vbnet/VbNetPlugin.java

[refactor] Sort scanner plugin dependencies; some leftovers

---

its/src/test/java/com/sonar/it/csharp/MetricsIncludeHeaderCommentTest.java
its/src/test/java/com/sonar/it/csharp/MetricsTest.java
its/src/test/java/com/sonar/it/csharp/MultipleProjectsTest.java
its/src/test/java/com/sonar/it/shared/TestUtils.java
its/src/test/java/com/sonar/it/vbnet/MetricsTest.java

[refactor] cleanup java ITs code

---

its/pom.xml
its/src/test/java/com/sonar/it/csharp/DoNotAnalyzeTestFilesTest.java
its/src/test/java/com/sonar/it/csharp/MultiTargetAppTest.java
its/src/test/java/com/sonar/it/csharp/NoSonarTest.java
its/src/test/java/com/sonar/it/csharp/NoSourcesTest.java
its/src/test/java/com/sonar/it/csharp/SharedFilesTest.java
its/src/test/java/com/sonar/it/csharp/TestProjectTest.java
its/src/test/java/com/sonar/it/csharp/UnitTestProjectTypeProbingTest.java
its/src/test/java/com/sonar/it/shared/ScannerCliTest.java
its/src/test/java/com/sonar/it/vbnet/DoNotAnalyzeTestFilesTest.java
its/src/test/java/com/sonar/it/vbnet/NoSonarTest.java
sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/AbstractModuleConfiguration.java
sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/AbstractPropertyDefinitions.java
sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/DotNetSensor.java
sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/FileTypeSensor.java
sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/DotNetSensorTest.java
sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/FileTypeSensorTest.java

Fixes #4063
Also some other minor improvements and fixing another found issue.

Display warnings in SQ/SC UI when only test projects are analyzed

---

analyzers/tests/SonarAnalyzer.UnitTest/MetadataReferences/NuGetMetadataFactory.Package.cs
analyzers/tests/SonarAnalyzer.UnitTest/MetadataReferences/NuGetMetadataFactory.cs
analyzers/tests/SonarAnalyzer.UnitTest/MetadataReferences/NuGetMetadataReference.cs

Deobfuscate complicated logic.
Procedural => OOP.
Simplify.
Cleanup

Refactor NuGetMetadataFactory

---

its/src/test/java/com/sonar/it/csharp/DoNotAnalyzeTestFilesTest.java
its/src/test/java/com/sonar/it/shared/TestUtils.java
its/src/test/java/com/sonar/it/vbnet/DoNotAnalyzeTestFilesTest.java
sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/FileTypeSensorTest.java

add IT and address leftover UT comment from #4091 review

add IT for querying AnalysisWarnings from SQ

---

sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/CoverageAggregator.java
sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/CoverageReportImportSensor.java
sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/DotNetSensor.java
sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/CoverageAggregatorTest.java
sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/CoverageReportImportSensorTest.java

Add .NET coverage troubleshooting guide link in logs

---

analyzers/pom.xml
analyzers/sonaranalyzer-maven-artifacts/SonarAnalyzer.CSharp/pom.xml
analyzers/sonaranalyzer-maven-artifacts/SonarAnalyzer.RuleDocGenerator.CSharp/pom.xml
analyzers/sonaranalyzer-maven-artifacts/SonarAnalyzer.RuleDocGenerator.VisualBasic/pom.xml
analyzers/sonaranalyzer-maven-artifacts/SonarAnalyzer.VisualBasic/pom.xml
analyzers/sonaranalyzer-maven-artifacts/pom.xml
analyzers/src/AssemblyInfo.Shared.cs
analyzers/src/SonarAnalyzer.CFG/SonarAnalyzer.CFG.cs.nuspec
analyzers/src/SonarAnalyzer.Vsix/SonarAnalyzer.CSharp.nuspec
analyzers/src/SonarAnalyzer.Vsix/SonarAnalyzer.VisualBasic.nuspec
analyzers/src/SonarAnalyzer.Vsix/source.extension.vsixmanifest
pom.xml
scripts/version/Version.props
sonar-csharp-plugin/pom.xml
sonar-dotnet-shared-library/pom.xml
sonar-vbnet-plugin/pom.xml

Bump version to 8.20

---

analyzers/tests/SonarAnalyzer.UnitTest/Common/RuleTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Common/SecurityHotspotTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/TestHelper.cs

Fixes #4034
S3011 was already fixed in previous refactoring PR

Add UTs for Hotspot and Deprecated rules

---

docs/contributing-plugin.md

Useful links to the orchestrator config added

---

analyzers/tests/SonarAnalyzer.UnitTest/SonarAnalyzer.UnitTest.csproj
azure-pipelines.yml
its/src/test/java/com/sonar/it/csharp/DoNotAnalyzeTestFilesTest.java
its/src/test/java/com/sonar/it/csharp/MetricsIncludeHeaderCommentTest.java
its/src/test/java/com/sonar/it/csharp/MultipleProjectsTest.java
its/src/test/java/com/sonar/it/shared/TestUtils.java
its/src/test/java/com/sonar/it/vbnet/DoNotAnalyzeTestFilesTest.java
scripts/build/build-utils.ps1

Update azure agent pool

---

analyzers/rspec/cs/S3431_c#.html
analyzers/src/SonarAnalyzer.CSharp/Rules/ExpectedExceptionAttributeShouldNotBeUsed.cs
analyzers/src/SonarAnalyzer.Utilities/Rules.Description/S3431.html
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ExpectedExceptionAttributeShouldNotBeUsed.MsTest.cs

Update message and example for S3431

---

its/projects/MultipleProjects/WildcardPatternTest/opencover.xml
its/src/test/java/com/sonar/it/csharp/CoverageTest.java
sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/CoverageReportImportSensor.java
sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/UnitTestResultsImportSensor.java
sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/WildcardPatternFileProvider.java
sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/WildcardPatternFileProviderTest.java

OutOfMemoryError possible using wildcard pattern with alternative path separators

---

its/src/test/java/com/sonar/it/csharp/WebConfigTest.java
its/src/test/java/com/sonar/it/vbnet/WebConfigTest.java

Unblock feature branch: ignore failing IT until E2E works

---

analyzers/src/SonarAnalyzer.Common/Common/AnalyzerConfiguration.cs
analyzers/src/SonarAnalyzer.Common/Common/IAnalyzerConfiguration.cs
analyzers/src/SonarAnalyzer.Common/Common/IRuleLoader.cs
analyzers/src/SonarAnalyzer.Common/Common/RuleLoader.cs
analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/DisablingRequestValidationBase.cs
analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/DoNotHardcodeCredentialsBase.cs
analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/RequestsWithExcessiveLengthBase.cs
analyzers/src/SonarAnalyzer.Common/Trackers/TrackerInput.cs
analyzers/tests/SonarAnalyzer.UnitTest/Common/AnalyzerConfigurationTests.cs
analyzers/tests/SonarAnalyzer.UnitTest/Common/Resources/SonarLint.xml
analyzers/tests/SonarAnalyzer.UnitTest/Common/RuleLoaderTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/SonarAnalyzer.UnitTest.csproj

This will fix also the intermittent ITs failures we have on the CI pipeline.

Avoid stale config when SonarLint.xml changes

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/MethodParameterUnused.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/MethodParameterUnused.cs

S1172 FP repro with try catch block

---

analyzers/rspec/cs/S3928_c#.html
analyzers/src/SonarAnalyzer.Utilities/Rules.Description/S3928.html

Updates compliant and non compliant examples for S3928

---

sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/sarif/SarifParser10.java
sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/sarif/SarifParser10Test.java
sonar-dotnet-shared-library/src/test/resources/SarifParserTest/v1_0_region_with_length.json
sonar-dotnet-shared-library/src/test/resources/SarifParserTest/v1_0_relative_paths.json

Fix the parsing of Sarif files when the path is relative

---

analyzers/src/SonarAnalyzer.Common/Common/AnalyzerConfiguration.cs
analyzers/src/SonarAnalyzer.Common/Common/IAnalyzerConfiguration.cs
analyzers/src/SonarAnalyzer.Common/Common/IRuleLoader.cs
analyzers/src/SonarAnalyzer.Common/Common/RuleLoader.cs
analyzers/src/SonarAnalyzer.Common/DiagnosticAnalyzer/HotspotDiagnosticAnalyzer.cs
analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/DisablingRequestValidationBase.cs
analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/DoNotHardcodeCredentialsBase.cs
analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/RequestsWithExcessiveLengthBase.cs
analyzers/src/SonarAnalyzer.Common/Trackers/TrackerInput.cs
analyzers/tests/SonarAnalyzer.UnitTest/Common/AnalyzerConfigurationTests.cs
analyzers/tests/SonarAnalyzer.UnitTest/Common/RuleLoaderTest.cs

Fix NRE caused by race condition in Hotspot Analyzer

---

analyzers/its/SonarAnalyzer.Testing.ImportBefore.targets
analyzers/src/SonarAnalyzer.CSharp/CBDE/CbdeHandler.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/CbdeHandlerRule.cs
analyzers/src/SonarAnalyzer.Common/Helpers/DiagnosticAnalyzerContextHelper.cs
analyzers/src/SonarAnalyzer.Common/Helpers/ParameterLoader.cs
analyzers/src/SonarAnalyzer.Common/Helpers/PropertiesHelper.cs
analyzers/src/SonarAnalyzer.Common/Helpers/SonarAnalysisContext.cs
analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/DisablingRequestValidationBase.cs
analyzers/src/SonarAnalyzer.Common/Rules/Utilities/CopyPasteTokenAnalyzerBase.cs
analyzers/src/SonarAnalyzer.Common/Rules/Utilities/FileMetadataAnalyzerBase.cs
analyzers/src/SonarAnalyzer.Common/Rules/Utilities/MetricsAnalyzerBase.cs
analyzers/src/SonarAnalyzer.Common/Rules/Utilities/SymbolReferenceAnalyzerBase.cs
analyzers/src/SonarAnalyzer.Common/Rules/Utilities/TokenTypeAnalyzerBase.cs
analyzers/src/SonarAnalyzer.Common/Rules/Utilities/UtilityAnalyzerBase.cs
analyzers/tests/SonarAnalyzer.UnitTest/Helpers/PropertiesHelperTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Helpers/SonarAnalysisContextTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Hotspots/DisablingRequestValidationTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/FileMetadataAnalyzerTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/UtilityAnalyzerBaseTests.cs

Fixes #4118
Review per commit is suggested. There's a bunch of refactoring on the way, as it was hard to understand the logic. I tried to keep individual commits as small as possible.

Use SonarProjectConfig.xml instead of ProjectOutFolderPath.txt

---

its/src/test/java/com/sonar/it/csharp/MetricsIncludeHeaderCommentTest.java
its/src/test/java/com/sonar/it/csharp/MetricsTest.java
its/src/test/java/com/sonar/it/csharp/MultipleProjectsTest.java
its/src/test/java/com/sonar/it/shared/ScannerCliTest.java
its/src/test/java/com/sonar/it/shared/TestUtils.java

Delete local cache at each Orchestrator reset

---

azure-pipelines.yml

- currently it is unstable and fails the build

Remove maven cache

---

analyzers/its/expected/WebConfig/Framework48-{6AC7E627-A21A-459C-8831-C45B6058E24D}-S5753.json
analyzers/its/sources/WebConfig/Web.Debug.config
analyzers/its/sources/WebConfig/Web.Release.config
analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/DisablingRequestValidationBase.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Hotspots/DisablingRequestValidationTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/WebConfig/TransformCustom/FilesToAnalyze.txt
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/WebConfig/TransformCustom/Web.Custom.config
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/WebConfig/TransformDebug/FilesToAnalyze.txt
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/WebConfig/TransformDebug/Web.Debug.config
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/WebConfig/TransformRelease/FilesToAnalyze.txt
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/WebConfig/TransformRelease/Web.Release.config

Extend S5753 to support Web.{Debug,Release}.config transformations

---

analyzers/pom.xml
analyzers/sonaranalyzer-maven-artifacts/SonarAnalyzer.CSharp/pom.xml
analyzers/sonaranalyzer-maven-artifacts/SonarAnalyzer.RuleDocGenerator.CSharp/pom.xml
analyzers/sonaranalyzer-maven-artifacts/SonarAnalyzer.RuleDocGenerator.VisualBasic/pom.xml
analyzers/sonaranalyzer-maven-artifacts/SonarAnalyzer.VisualBasic/pom.xml
analyzers/sonaranalyzer-maven-artifacts/pom.xml
analyzers/src/AssemblyInfo.Shared.cs
analyzers/src/SonarAnalyzer.CFG/SonarAnalyzer.CFG.cs.nuspec
analyzers/src/SonarAnalyzer.Vsix/SonarAnalyzer.CSharp.nuspec
analyzers/src/SonarAnalyzer.Vsix/SonarAnalyzer.VisualBasic.nuspec
analyzers/src/SonarAnalyzer.Vsix/source.extension.vsixmanifest
pom.xml
scripts/version/ChangeVersion.proj
scripts/version/Version.props
sonar-csharp-plugin/pom.xml
sonar-dotnet-shared-library/pom.xml
sonar-vbnet-plugin/pom.xml

Bump version to 8.21.0

---

analyzers/tests/SonarAnalyzer.UnitTest/Rules/Hotspots/CookieShouldBeHttpOnlyTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/WebConfig/CookieShouldBeHttpOnly/Formatting/Web.config

Related to the problem fixed by #4158
No behavior change, just a test

S3330 - Add spaced formatting web.config

---

.editorconfig

Update StyleCop rules

---

analyzers/src/SonarAnalyzer.CSharp/Rules/ClassAndMethodName.cs
analyzers/src/SonarAnalyzer.Common/Helpers/ProjectTypeHelper.cs
analyzers/tests/SonarAnalyzer.UnitTest/Helpers/ProjectTypeHelperTests.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/ClassAndMethodNameTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ClassName.Tests.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ClassName.TopLevelStatement.Test.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ClassName.TopLevelStatement.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ClassName.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ClassName.vb
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SolutionBuilder.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Verifier.cs

Update ClassAndMethodName to use cached `IsTest`

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CheckArgumentException.cs

S3928: Add FP repro for #4180

---

analyzers/src/SonarAnalyzer.Common/Helpers/ProjectTypeHelper.cs
analyzers/src/SonarAnalyzer.Common/Helpers/SonarAnalysisContext.cs
analyzers/tests/SonarAnalyzer.UnitTest/Helpers/SonarAnalysisContextTest.cs

Related to #4156
This is draft, rebase will be needed when #4179 is merged. First squash commit doesn't need a review.

Add more UTs for SonarAnalysisConfig

---

analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/CSharp/CSharpExplodedGraph.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ConditionEvaluatesToConstant.CSharp9.cs

Ensure we don't throw on TypePattern and RelationalPattern

---

azure-pipelines.yml

- check if the problem was fixed in the meantime

Add back maven cache

---

analyzers/src/SonarAnalyzer.VisualBasic/Rules/UseReturnStatement.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UseReturnStatement.vb

Fix S5944 FP: With NameOf

---

azure-pipelines.yml

Remove maven cache - it fails the build

---

analyzers/tests/SonarAnalyzer.UnitTest/Common/AnalyzerConfigurationTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Extensions/CSharpSyntaxWalkerExtensionsTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Helpers/BaseArgumentListSyntaxExtensionsTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Helpers/ParameterLoaderTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Helpers/ProjectConfigReaderTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Helpers/ProjectTypeHelperTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Helpers/VbcHelperTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/LiveVariableAnalysis/LiveVariableAnalysisTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/PackagingTests/RuleTypeTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/AbstractTypesShouldNotHaveConstructorsTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/UtilityAnalyzerBaseTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/ExplodedGraphTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/ProgramPointTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/ProgramStateTest.cs

Rename 14 files to align with the rest of the codebase

Rename "Tests" suffixes to "Test"

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ClassName.cs

Adds FP repro for rule S101

---

analyzers/rspec/cs/S3443_c#.html
analyzers/src/SonarAnalyzer.CSharp/Extensions/IMethodSymbolExtensions.cs
analyzers/src/SonarAnalyzer.CSharp/Extensions/InvocationExpressionSyntaxExtensions.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/GetTypeWithIsAssignableFrom.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/RedundantNullableTypeComparison.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/TypeExaminationOnSystemType.cs
analyzers/src/SonarAnalyzer.Utilities/Rules.Description/S3443.html
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/TypeExaminationOnSystemType.cs

S3443: Treat "typeof(Type).GetType()" as an exception

---

analyzers/tests/SonarAnalyzer.UnitTest/Rules/UnusedPrivateMemberTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnusedPrivateMember.CSharp8.cs

Add repro for #4102

---

analyzers/tests/SonarAnalyzer.UnitTest/Rules/MethodParameterUnusedTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/MethodParameterUnused.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/MethodParameterUnused.cs

Add repro for S1172 - local functions

---

analyzers/src/SonarAnalyzer.RuleDescriptorGenerator/SonarAnalyzer.RuleDescriptorGenerator.csproj

Disable analysis during dev build (RulesDescriptorGenerator)

---

sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/DotCoverReportParser.java
sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/DotCoverReportParserTest.java
sonar-dotnet-shared-library/src/test/resources/dotcover/no_title_end.html
sonar-dotnet-shared-library/src/test/resources/dotcover/title_nested_tag.html
sonar-dotnet-shared-library/src/test/resources/dotcover/title_swapped.html

Fix RegEx hotspots in DotCoverReportParser

---

its/projects/ExternalIssues.TestProject.CS/.editorconfig
its/projects/ExternalIssues.TestProject.CS/ExternalIssues.TestProject.CS.sln
its/projects/ExternalIssues.TestProject.CS/ExternalIssues.TestProject.CS/ExternalIssues.TestProject.CS.csproj
its/projects/ExternalIssues.TestProject.CS/ExternalIssues.TestProject.CS/NUnitTest.cs
its/projects/ExternalIssues.TestProject.CS/ExternalIssues.TestProject.CS/xUnitTest.cs
its/src/test/java/com/sonar/it/csharp/ExternalIssuesTest.java

Add IT with nunit and xunit analyzers as external issues

---

analyzers/src/SonarAnalyzer.CSharp/Rules/DoNotOverwriteCollectionElements.cs
analyzers/src/SonarAnalyzer.Common/Rules/DoNotOverwriteCollectionElementsBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/DoNotOverwriteCollectionElements.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DoNotOverwriteCollectionElements.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DoNotOverwriteCollectionElements.vb

Fix S4143 FP with Indexers

---

analyzers/src/SonarAnalyzer.CSharp/Rules/DoNotOverwriteCollectionElements.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/TestMethodShouldContainAssertion.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/TestMethodShouldNotBeIgnored.cs
analyzers/src/SonarAnalyzer.Common/Helpers/UnitTestHelper.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/TestMethodShouldContainAssertion.MsTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/TestMethodShouldContainAssertion.NUnit.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/TestMethodShouldContainAssertion.Xunit.cs

Fixes S2699 FP with using static directive

---

analyzers/src/SonarAnalyzer.CSharp/Rules/Utilities/CopyPasteTokenAnalyzer.cs
analyzers/src/SonarAnalyzer.VisualBasic/Helpers/VisualBasicSyntaxHelper.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/Utilities/CopyPasteTokenAnalyzer.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/CopyPasteTokenAnalyzerTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/SymbolReferenceAnalyzerTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Utilities/CopyPasteTokenAnalyzer/Unique.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Utilities/CopyPasteTokenAnalyzer/Unique.vb

Recognize interpolated strings in CopyPasteTokenAnalyzer

---

analyzers/its/expected/akka.net/Akka.Tests-{3F786C7D-70E3-4836-8B33-EC9A5AF72330}-S2699.json
analyzers/src/SonarAnalyzer.CSharp/Rules/TestMethodShouldContainAssertion.cs
analyzers/tests/SonarAnalyzer.UnitTest/Helpers/SonarAnalysisContextTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/TestMethodShouldContainAssertionTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/TestMethodShouldContainAssertion.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/TestMethodShouldContainAssertion.MsTest.AnotherFile.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/TestMethodShouldContainAssertion.MsTest.cs

Fix S2699 FP: Inspect invoked methods to search for assertions

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/BeginInvokePairedWithEndInvoke.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/BeginInvokePairedWithEndInvoke.vb

Add Repro for S4583 with action.EndInvoke as callback

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ConditionEvaluatesToConstant.cs

S2583: Add FP repro for #4257

---

analyzers/pom.xml
analyzers/sonaranalyzer-maven-artifacts/SonarAnalyzer.CSharp/pom.xml
analyzers/sonaranalyzer-maven-artifacts/SonarAnalyzer.RuleDocGenerator.CSharp/pom.xml
analyzers/sonaranalyzer-maven-artifacts/SonarAnalyzer.RuleDocGenerator.VisualBasic/pom.xml
analyzers/sonaranalyzer-maven-artifacts/SonarAnalyzer.VisualBasic/pom.xml
analyzers/sonaranalyzer-maven-artifacts/pom.xml
analyzers/src/AssemblyInfo.Shared.cs
analyzers/src/SonarAnalyzer.CFG/SonarAnalyzer.CFG.cs.nuspec
analyzers/src/SonarAnalyzer.Vsix/SonarAnalyzer.CSharp.nuspec
analyzers/src/SonarAnalyzer.Vsix/SonarAnalyzer.VisualBasic.nuspec
analyzers/src/SonarAnalyzer.Vsix/source.extension.vsixmanifest
pom.xml
scripts/version/Version.props
sonar-csharp-plugin/pom.xml
sonar-dotnet-shared-library/pom.xml
sonar-vbnet-plugin/pom.xml

Please also verify, that `branch-8.21` is correctly created from the correct tag.

Bump version to 8.21.1

---

analyzers/its/expected/WebConfig/Framework48-{6AC7E627-A21A-459C-8831-C45B6058E24D}-S2115.json
analyzers/its/sources/WebConfig/Views/Web.config
analyzers/its/sources/WebConfig/Web.config
analyzers/src/SonarAnalyzer.CSharp/Rules/DatabasePasswordsShouldBeSecure.cs
analyzers/src/SonarAnalyzer.Common/Helpers/SonarAnalysisContext.cs
analyzers/src/SonarAnalyzer.Common/Helpers/XmlHelper.cs
analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/DisablingRequestValidationBase.cs
analyzers/tests/SonarAnalyzer.UnitTest/Helpers/XmlHelperTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/DatabasePasswordsShouldBeSecureTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Hotspots/DisablingRequestValidationTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DatabasePasswordsShouldBeSecure.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/WebConfig/DatabasePasswordsShouldBeSecure/Corrupt/Web.config
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/WebConfig/DatabasePasswordsShouldBeSecure/ExternalConfig/Web.config
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/WebConfig/DatabasePasswordsShouldBeSecure/ExternalConfig/external.config
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/WebConfig/DatabasePasswordsShouldBeSecure/Formatting/Web.config
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/WebConfig/DatabasePasswordsShouldBeSecure/UnexpectedContent/Web.config
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/WebConfig/DatabasePasswordsShouldBeSecure/Values/Web.config
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/WebConfig/DisablingRequestValidation/Empty/README.md

 Rule S2115: Databases should be password-protected  - detect web.config issues

---

its/pom.xml
pom.xml

Parallel to #4291  for `branch-8.21`

Update parent pom version

---

sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/UnitTestResultsAggregator.java
sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/UnitTestResultsAggregatorTest.java

Improve unit test report error message

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/EmptyCollectionsShouldNotBeEnumerated.cs

Add repro for #4261

---

analyzers/src/SonarAnalyzer.CFG/ShimLayer/ILocalSymbolExtensions.cs
analyzers/src/SonarAnalyzer.CSharp/LiveVariableAnalysis/CSharp/CSharpLiveVariableAnalysis.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/DeadStores.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DeadStores.cs

Fix S1854 FP: ref keyword on a local variable

---

analyzers/src/SonarAnalyzer.CSharp/Rules/ConditionEvaluatesToConstant.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ConditionEvaluatesToConstant.CSharp7.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ConditionEvaluatesToConstant.cs

Fix S2589 FP: Tuple Assignment

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UninvokedEventDeclaration.cs

Add repro for #4276

---

analyzers/src/SonarAnalyzer.CSharp/Rules/DatabasePasswordsShouldBeSecure.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DatabasePasswordsShouldBeSecure.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/WebConfig/DatabasePasswordsShouldBeSecure/Values/Web.config

Fix S2115: FP when implicit authentication is used

---

analyzers/src/SonarAnalyzer.CSharp/Rules/AssignmentInsideSubExpression.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/AssignmentInsideSubExpression.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/AssignmentInsideSubExpression.cs

Add repro for #4264

---

analyzers/src/SonarAnalyzer.CSharp/Rules/ConditionEvaluatesToConstant.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ConditionEvaluatesToConstant.cs

S2583 and S2589 False positive when a variable is initialized inside local function

---

analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/ClearTextProtocolsAreSensitive.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/ClearTextProtocolsAreSensitive.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/ClearTextProtocolsAreSensitive.cs

Fix S5332 FP: Don't raise for known schema and example domains

---

analyzers/src/SonarAnalyzer.CSharp/Rules/BeginInvokePairedWithEndInvoke.cs
analyzers/src/SonarAnalyzer.Common/Rules/BeginInvokePairedWithEndInvokeBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/BeginInvokePairedWithEndInvoke.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/BeginInvokePairedWithEndInvoke.cs

S4583 FP fix with EndInvoke as MemberAccess

---

analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/ClearTextProtocolsAreSensitive.cs
analyzers/tests/SonarAnalyzer.UnitTest/Common/SecurityHotspotTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Hotspots/ClearTextProtocolsAreSensitiveTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/ClearTextProtocolsAreSensitive.cs

Fix S5332 FP: Don't raise http warning for xml namespace

---

analyzers/src/SonarAnalyzer.CSharp/Facade/CSharpSyntaxFacade.cs
analyzers/src/SonarAnalyzer.CSharp/Facade/CSharpSyntaxKindFacade.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/UnconditionalJumpStatement.cs
analyzers/src/SonarAnalyzer.Common/Facade/ISyntaxKindFacade.cs
analyzers/src/SonarAnalyzer.Common/Facade/SyntaxFacade.cs
analyzers/src/SonarAnalyzer.Common/Rules/UnconditionalJumpStatementBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Facade/VisualBasicSyntaxFacade.cs
analyzers/src/SonarAnalyzer.VisualBasic/Facade/VisualBasicSyntaxKindFacade.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/UnconditionalJumpStatement.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnconditionalJumpStatement.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnconditionalJumpStatement.vb

Fix S1751 FP: Triggered when returning a property inside try catch block

---

analyzers/src/SonarAnalyzer.CSharp/Helpers/MutedSyntaxWalker.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/ConditionEvaluatesToConstant.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/DeadStores.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DeadStores.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DeadStores.cs

Fix S1854 FP: When a variable is used inside local function

---

analyzers/src/SonarAnalyzer.CSharp/Helpers/MutedSyntaxWalker.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DeadStores.cs

Fixes #3348
First `Squash` commit doesn't need a review

Fix S1854 FP: Values used as Indices and Ranges

---

analyzers/its/expected/Ember-MM/Ember Media Manager-{9B57D3AB-AF12-4012-B945-284C2448DC81}-S1821.json
analyzers/its/expected/Ember-MM/generic.EmberCore.BulkRename-{EAAB0601-6478-44D2-A39C-89B0850D7833}-S1821.json
analyzers/its/expected/Ember-MM/generic.EmberCore.WebServer-{64D6F035-F186-4193-AF35-D20126B8DA64}-S1821.json
analyzers/its/expected/Ember-MM/multi.Compatibility-{859C1085-518B-49D2-9C84-D91C4094097F}-S1821.json
analyzers/src/SonarAnalyzer.VisualBasic/Rules/SwitchShouldNotBeNested.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SwitchShouldNotBeNested.vb

Update S1821 message for VB.NET

---

analyzers/src/SonarAnalyzer.CSharp/Helpers/MutedSyntaxWalker.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ConditionEvaluatesToConstant.CSharp7.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DeadStores.cs

Fixes #2590
Fixes #2596
Fixes #2598
Fixes #2600
Fixes #2761
Fixes #2766
First squash commit doesn't need a review

Fix S1854, S2583 and S2589 FPs related to Try/Catch

---

analyzers/src/SonarAnalyzer.CSharp/Rules/UnconditionalJumpStatement.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnconditionalJumpStatement.cs

S1751 FP fix with Anonymous Method Expression

---

analyzers/src/SonarAnalyzer.CSharp/Rules/PropertyWriteOnly.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/PropertyWriteOnly.cs

Fix S2376 FP with getter in base class

---

analyzers/src/SonarAnalyzer.Common/Rules/PublicMethodWithMultidimensionalArrayBase.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/PublicMethodWithMultidimensionalArrayTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/RedundantNullCheckTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/PublicMethodWithMultidimensionalArray.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/PublicMethodWithMultidimensionalArray.vb

Fix S2368 FP: Params keyword on jagged arrays

---

analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/CookieShouldBeHttpOnly.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/CookieShouldBeSecure.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/ObjectShouldBeInitializedCorrectlyBase.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Hotspots/CookieShouldBeHttpOnlyTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Hotspots/CookieShouldBeSecureTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/CookieShouldBeHttpOnly.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/CookieShouldBeSecure.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/CookieShouldBeSecure_WithWebConfig.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/WebConfig/CookieShouldBeHttpOnly/ConfigWithoutAttribute/Web.config
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/WebConfig/CookieShouldBeHttpOnly/Formatting/Web.config
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/WebConfig/CookieShouldBeHttpOnly/HttpOnlyCookiesConfig/Web.config
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/WebConfig/CookieShouldBeHttpOnly/NonHttpOnlyCookiesConfig/Web.config
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/WebConfig/CookieShouldBeHttpOnly/UnrelatedConfig/Web.config
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/WebConfig/CookieShouldBeSecure/ConfigWithoutAttribute/Web.config
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/WebConfig/CookieShouldBeSecure/Formatting/Web.config
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/WebConfig/CookieShouldBeSecure/NonSecureCookieConfig/Web.config
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/WebConfig/CookieShouldBeSecure/SecureCookieConfig/Web.config
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/WebConfig/CookieShouldBeSecure/UnrelatedConfig/Web.config

Fix S2092 FP: Setting requireSSL in web.config

---

analyzers/src/SonarAnalyzer.CSharp/Rules/ParameterValidationInAsyncShouldBeWrapped.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ParameterValidationInAsyncShouldBeWrapped.cs

Fix S4457 FP with async void methods

---

analyzers/rspec/cs/S2053_c#.html
analyzers/src/SonarAnalyzer.Utilities/Rules.Description/S2053.html

Update S2053 message to reflect impl

---

its/pom.xml
pom.xml
sonar-csharp-plugin/pom.xml
sonar-dotnet-shared-library/pom.xml
sonar-vbnet-plugin/pom.xml

Update parent pom and sonar-analyzer-commons

---

analyzers/CBDE/SonarSource.CBDE.nuspec
analyzers/NuGet.Config
analyzers/src/SonarAnalyzer.CSharp/SonarAnalyzer.CSharp.csproj

Update SonarSource.CBDE to 1.0.0.31145

---

.github/workflows/release.yml
azure-pipelines.yml
pom.xml

Update release workflow to v3

---

analyzers/pom.xml
analyzers/sonaranalyzer-maven-artifacts/SonarAnalyzer.CSharp/pom.xml
analyzers/sonaranalyzer-maven-artifacts/SonarAnalyzer.RuleDocGenerator.CSharp/pom.xml
analyzers/sonaranalyzer-maven-artifacts/SonarAnalyzer.RuleDocGenerator.VisualBasic/pom.xml
analyzers/sonaranalyzer-maven-artifacts/SonarAnalyzer.VisualBasic/pom.xml
analyzers/sonaranalyzer-maven-artifacts/pom.xml
analyzers/src/AssemblyInfo.Shared.cs
analyzers/src/SonarAnalyzer.CFG/SonarAnalyzer.CFG.cs.nuspec
analyzers/src/SonarAnalyzer.Vsix/SonarAnalyzer.CSharp.nuspec
analyzers/src/SonarAnalyzer.Vsix/SonarAnalyzer.VisualBasic.nuspec
analyzers/src/SonarAnalyzer.Vsix/source.extension.vsixmanifest
pom.xml
scripts/version/Version.props
sonar-csharp-plugin/pom.xml
sonar-dotnet-shared-library/pom.xml
sonar-vbnet-plugin/pom.xml

Bump version to 8.23.0

---

azure-pipelines.yml

Run nightly builds only during the week

---

analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/PublicMethodArgumentsShouldBeCheckedForNull.cs
analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/PublicMethodArgumentsShouldBeCheckedForNull.CSharp9.cs

Fix S3900 FP: should not raise when argument is annotated with [FromServices] attribute

---

analyzers/its/regression-test.ps1

Fixes #4330
There's [unintuitive PS behavior](https://stackoverflow.com/questions/18476634/powershell-doesnt-return-an-empty-array-as-an-array) for `return @()` that translates to `$null`.
Note: 
* Internal projects uses `// Noncompliant` annotations
* Normal projects uses `expected/projectname/*.json` files to mark expected issues
Issues for testing:
* S3904 is NOT raised on `ManuallyAddedNoncompliantIssues` (internal) nor `AnalyzeGenerated` (normal)
* S4487 is raised on `ManuallyAddedNoncompliantIssues` (internal)
* S1128 is raised on `AnalyzeGenerated` (normal)
Tested scenarios - default codebase:
```
.\regression-test.ps1
.\regression-test.ps1 -ruleId S3904
.\regression-test.ps1 -ruleId S4487 
.\regression-test.ps1 -ruleId S1128 
.\regression-test.ps1 -project …
```

Fix regression-test.ps1 when executed for single rule

---

analyzers/.sonarlint/SonarAnalyzer.slconfig
analyzers/.sonarlint/sonaranalyzer-dotnet/CSharp/SonarLint.xml
analyzers/.sonarlint/sonaranalyzer-dotnetCSharp.ruleset

The QP on SonarCloud updated, we need to change the auto-generated SLVS files to avoid conflicts.

Update SLVS config for connected mode

---

analyzers/its/sources/ManuallyAddedNoncompliantIssues/NetFramework48/HashesShouldHaveUnpredictableSaltTest.cs
analyzers/rspec/cs/S2053_c#.html
analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/HashesShouldHaveUnpredictableSalt.cs
analyzers/src/SonarAnalyzer.Utilities/Rules.Description/S2053.html
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/HashesShouldHaveUnpredictableSalt.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/HashesShouldHaveUnpredictableSalt.cs

S2053 FP fix and message improvement

---

analyzers/src/SonarAnalyzer.CSharp/Rules/StringOrIntegralTypesForIndexers.cs
analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/StringOrIntegralTypesForIndexersTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/StringOrIntegralTypesForIndexers.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/StringOrIntegralTypesForIndexers.cs

Fix S3876 FP System.Index and System.Range are valid indices

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/PropertiesAccessCorrectField.cs

Document false positives for S4275

---

analyzers/src/SonarAnalyzer.CSharp/Rules/AbstractTypesShouldNotHaveConstructors.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/AbstractTypesShouldNotHaveConstructors.Records.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/AbstractTypesShouldNotHaveConstructors.TopLevelStatements.cs

Rule S3442: add support for records

---

analyzers/its/expected/Nancy/Nancy-{34576216-0DCA-4B0F-A0DC-9075E75A676F}-S4462.json
analyzers/its/expected/akka.net/Akka.Remote-{EA4FF8FD-7C53-49C8-B9AA-02E458B3E6A7}-S4462.json
analyzers/its/expected/akka.net/SymbolLookup-{3007A692-A050-4F12-9187-4AE6C6106A66}-S4462.json
analyzers/src/SonarAnalyzer.CSharp/Rules/CallToAsyncMethodShouldNotBeBlocking.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/PrivateFieldUsedAsLocalVariable.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/TryStatementsWithIdenticalCatchShouldBeMerged.cs
analyzers/src/SonarAnalyzer.Shared/Extensions/StatementSyntaxExtensions.cs
analyzers/src/SonarAnalyzer.Shared/Extensions/SyntaxNodeExtensions.cs
analyzers/tests/SonarAnalyzer.UnitTest/Extensions/SyntaxNodeExtensionsTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CallToAsyncMethodShouldNotBeBlocking.cs

Fix S4462 FP when using Task.WhenAll

---

analyzers/src/SonarAnalyzer.CSharp/Helpers/CSharpSymbolUsageCollector.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/GenericTypeParameterUnused.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/MemberInitializerRedundant.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/MethodParameterUnused.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/TestMethodShouldContainAssertion.cs
analyzers/src/SonarAnalyzer.Common/Helpers/SyntaxNodeExtensions.cs
analyzers/src/SonarAnalyzer.Common/Trackers/ConstantValueFinder.cs
analyzers/tests/SonarAnalyzer.UnitTest/Helpers/CSharpSymbolUsageCollectorTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Trackers/ConstantValueFinderTest.cs

Fix S2699 throws AD0001 exception

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ParameterNameMatchesOriginal.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ParameterNameMatchesOriginal.vb

Documenting S927 FP found on Peach

---

scripts/build/dev-build.ps1

Fixes #3006
Low priority hardening
This is a draft to avoid merging before release

Clean output dir before dev-build

---

analyzers/src/SonarAnalyzer.CSharp/Rules/ClassAndMethodName.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/ClassAndMethodNameTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/MethodName.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/MethodName.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RecordName.cs

Rules S100, S101: Add support for records

---

analyzers/src/SonarAnalyzer.CSharp/Rules/AvoidExcessiveInheritance.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/AvoidExcessiveInheritanceTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/AvoidExcessiveInheritance_CustomValues.Records.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/AvoidExcessiveInheritance_DefaultValues.Records.cs

Rule S110: Add support for records

---

analyzers/its/expected/Automapper/AutoMapper-025B9F93-7953-454B-AF29-E6A55B2AA58F-S1694.json
analyzers/its/expected/Nancy/Nancy-{34576216-0DCA-4B0F-A0DC-9075E75A676F}-S1694.json
analyzers/its/expected/Nancy/Nancy.Demo.CustomModule-{F56F3983-0C34-4AEC-B418-A8AFFA63F1C4}-S1694.json
analyzers/its/expected/Nancy/Nancy.Hosting.Aspnet-{15B7F794-0BB2-4B66-AD78-4A951F1209B2}-S1694.json
analyzers/its/expected/Nancy/Nancy.Metadata.Modules-{DC8AAA8B-7FD0-47C4-9413-3CC94088BCC4}-S1694.json
analyzers/its/expected/Nancy/Nancy.ViewEngines.Razor-{2C6F51DF-015C-4DB6-B44C-0E5E4F25E2A9}-S1694.json
analyzers/its/expected/Net5/Net5--S1694.json
analyzers/its/expected/akka.net/Akka-{5DEDDF90-37F0-48D3-A0B0-A5CBD8A7E377}-S1694.json
analyzers/its/expected/akka.net/Akka.Cluster-{6AB00F61-269A-4501-B06A-026707F000A7}-S1694.json
analyzers/its/expected/akka.net/Akka.Cluster.Sharding-{A05C31E8-0246-46A1-B3BC-4D6FE7A9AA49}-S1694.json
analyzers/its/expected/akka.net/Akka.MultiNodeTestRunner.Shared-{964F0EC5-FBE6-47C5-8AE6-145114D5DB8C}-S1694.json
analyzers/its/expected/akka.net/Akka.Persistence-{FCA84DEA-C118-424B-9EB8-34375DFEF18A}-S1694.json
analyzers/its/expected/akka.net/Akka.Persistence.Sql.Common-{3B9E6211-9488-4DB5-B714-24248693B38F}-S1694.json
analyzers/its/expected/akka.net/Akka.Remote-{EA4FF8FD-7C53-49C8-B9AA-02E458B3E6A7}-S1694.json
analyzers/its/expected/akka.net/Akka.TestKit-{0D3CBAD0-BBDB-43E5-AFC4-ED1D3ECDC224}-S1694.json
analyzers/src/SonarAnalyzer.CSharp/Rules/ClassShouldNotBeAbstract.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ClassShouldNotBeAbstract.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ClassShouldNotBeAbstract.cs

Rule S1694: add support for records

---

analyzers/src/SonarAnalyzer.CSharp/Rules/AsyncVoidMethod.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/AsyncVoidMethod.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/AsyncVoidMethod.cs

Rule S3168: Add support for records

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/StaticFieldVisible.cs

Add repro for #4407

---

analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/InsecureDeserialization.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Hotspots/InsecureDeserializationTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/InsecureDeserialization.CSharp9.cs

Rule S5766: add support for records

---

analyzers/its/expected/Net5/Net5--S3881.json
analyzers/src/SonarAnalyzer.CSharp/Rules/ImplementIDisposableCorrectly.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ImplementIDisposableCorrectly.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ImplementIDisposableCorrectly.cs

Rule S3881: Add support for records

---

analyzers/src/SonarAnalyzer.CSharp/Facade/CSharpSyntaxFacade.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/PropertyWriteOnly.cs
analyzers/src/SonarAnalyzer.Common/Rules/PropertyWriteOnlyBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Facade/VisualBasicSyntaxFacade.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/PropertyWriteOnly.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/PropertyWriteOnly.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/PropertyWriteOnly.cs

S2376: PropertyWriteOnly  add test cases

---

analyzers/src/SonarAnalyzer.CSharp/Rules/ImplementISerializableCorrectly.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/ImplementISerializableCorrectlyTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ImplementISerializableCorrectly.CSharp9.cs

Rule S3925: Add support for records

---

analyzers/src/SonarAnalyzer.CSharp/Rules/CertificateValidationCheck.cs
analyzers/src/SonarAnalyzer.Common/Rules/CertificateValidationCheckBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/CertificateValidationCheck.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CertificateValidationCheck.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CertificateValidationCheck.TopLevelStatements.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CertificateValidationCheck.cs

Rule S4830: Add support for records

---

analyzers/src/SonarAnalyzer.CSharp/Rules/InterfaceMethodsShouldBeCallableByChildTypes.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/InterfaceMethodsShouldBeCallableByChildTypes.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/InterfaceMethodsShouldBeCallableByChildTypes.cs

Rule S4039: add support for records

---

analyzers/src/SonarAnalyzer.CSharp/Rules/RedundantInheritanceList.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/RedundantInheritanceListCodeFixProvider.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/RedundantInheritanceListTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundantInheritanceList.CSharp9.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundantInheritanceList.CSharp9.cs

S1939: RedundantInheritanceList - Records support

---

analyzers/src/SonarAnalyzer.CSharp/Rules/TypesShouldNotExtendOutdatedBaseTypes.cs

S4052: TypesShouldNotExtendOutdatedBaseTypes- code smell fix

---

analyzers/src/SonarAnalyzer.CSharp/Rules/PartCreationPolicyShouldBeUsedWithExportAttribute.cs
analyzers/src/SonarAnalyzer.Common/Rules/PartCreationPolicyShouldBeUsedWithExportAttributeBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/PartCreationPolicyShouldBeUsedWithExportAttribute.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/PartCreationPolicyShouldBeUsedWithExportAttributeTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/PartCreationPolicyShouldBeUsedWithExportAttribute.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/PartCreationPolicyShouldBeUsedWithExportAttribute.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/PartCreationPolicyShouldBeUsedWithExportAttribute.vb

Rule S4428: add support for records

---

analyzers/src/SonarAnalyzer.CSharp/Rules/StringLiteralShouldNotBeDuplicated.cs
analyzers/src/SonarAnalyzer.Common/Rules/StringLiteralShouldNotBeDuplicatedBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/StringLiteralShouldNotBeDuplicated.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/StringLiteralShouldNotBeDuplicated.CSharp9.cs

Rule S1192: add support for records

---

analyzers/src/SonarAnalyzer.CSharp/Rules/UnnecessaryUsings.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnnecessaryUsings.CSharp9.cs

Rule S1128: fix false positive with top level statements

---

analyzers/its/expected/Nancy/Nancy-{34576216-0DCA-4B0F-A0DC-9075E75A676F}-S4050.json
analyzers/its/expected/akka.net/Akka-{5DEDDF90-37F0-48D3-A0B0-A5CBD8A7E377}-S4050.json
analyzers/its/expected/akka.net/Akka.Cluster-{6AB00F61-269A-4501-B06A-026707F000A7}-S4050.json
analyzers/its/expected/akka.net/Akka.Remote-{EA4FF8FD-7C53-49C8-B9AA-02E458B3E6A7}-S4050.json
analyzers/rspec/cs/S4050_c#.html
analyzers/src/SonarAnalyzer.CSharp/Rules/OperatorsShouldBeOverloadedConsistently.cs
analyzers/src/SonarAnalyzer.Common/Helpers/KnownMethods.cs
analyzers/src/SonarAnalyzer.Utilities/Rules.Description/S4050.html
analyzers/tests/SonarAnalyzer.UnitTest/Helpers/KnownMethodsTests.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/OperatorsShouldBeOverloadedConsistently.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/OperatorsShouldBeOverloadedConsistently.cs

S4050 fix FPs and add test cases for records

---

analyzers/src/SonarAnalyzer.CSharp/Rules/RedundancyInConstructorDestructorDeclaration.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/RedundancyInConstructorDestructorDeclarationCodeFixProvider.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/RedundancyInConstructorDestructorDeclarationTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundancyInConstructorDestructorDeclaration.BaseCall.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundancyInConstructorDestructorDeclaration.CSharp9.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundancyInConstructorDestructorDeclaration.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundancyInConstructorDestructorDeclaration.Constructor.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundancyInConstructorDestructorDeclaration.Destructor.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundancyInConstructorDestructorDeclaration.cs

Rule S3253: add support for records

---

analyzers/src/SonarAnalyzer.CSharp/Rules/ProvideDeserializationMethodsForOptionalFields.cs
analyzers/src/SonarAnalyzer.Common/Facade/ILanguageFacade.cs
analyzers/src/SonarAnalyzer.Common/Rules/ProvideDeserializationMethodsForOptionalFieldsBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/ProvideDeserializationMethodsForOptionalFields.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ProvideDeserializationMethodsForOptionalFields.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ProvideDeserializationMethodsForOptionalFields.cs

Rule S3926: add support for records

---

analyzers/its/expected/Net5/Net5--S3459.json
analyzers/src/SonarAnalyzer.CSharp/Helpers/CSharpRemovableDeclarationCollector.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/NotAssignedPrivateMember.cs
analyzers/src/SonarAnalyzer.Common/Helpers/RemovableDeclarationCollectorBase.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/NotAssignedPrivateMember.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/NotAssignedPrivateMember.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UninvokedEventDeclaration.CSharp9.cs

Rule S3459: Add support for records

---

analyzers/src/SonarAnalyzer.CSharp/Facade/CSharpSyntaxFacade.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/ShouldImplementExportedInterfaces.cs
analyzers/src/SonarAnalyzer.Common/Rules/ShouldImplementExportedInterfacesBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Facade/VisualBasicSyntaxFacade.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/ShouldImplementExportedInterfaces.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ShouldImplementExportedInterfaces.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ShouldImplementExportedInterfaces.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ShouldImplementExportedInterfaces.vb

Rule S4159: Add support for records

---

analyzers/src/SonarAnalyzer.CSharp/Rules/UninvokedEventDeclaration.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UninvokedEventDeclaration.CSharp9.cs

Rule S3264: Add support for records

---

analyzers/src/SonarAnalyzer.CSharp/Rules/UnusedPrivateMember.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/UnusedPrivateMemberTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnusedPrivateMember.CSharp9.TopLevelStatements.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnusedPrivateMember.CSharp9.cs

Rule S1144: Add support for records

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/AssignmentInsideSubExpression.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/AssignmentInsideSubExpression.cs

Documenting S1121 FP

---

analyzers/pom.xml
analyzers/sonaranalyzer-maven-artifacts/SonarAnalyzer.CSharp/pom.xml
analyzers/sonaranalyzer-maven-artifacts/SonarAnalyzer.RuleDocGenerator.CSharp/pom.xml
analyzers/sonaranalyzer-maven-artifacts/SonarAnalyzer.RuleDocGenerator.VisualBasic/pom.xml
analyzers/sonaranalyzer-maven-artifacts/SonarAnalyzer.VisualBasic/pom.xml
analyzers/sonaranalyzer-maven-artifacts/pom.xml
analyzers/src/AssemblyInfo.Shared.cs
analyzers/src/SonarAnalyzer.CFG/SonarAnalyzer.CFG.cs.nuspec
analyzers/src/SonarAnalyzer.Vsix/SonarAnalyzer.CSharp.nuspec
analyzers/src/SonarAnalyzer.Vsix/SonarAnalyzer.VisualBasic.nuspec
analyzers/src/SonarAnalyzer.Vsix/source.extension.vsixmanifest
pom.xml
scripts/version/Version.props
sonar-csharp-plugin/pom.xml
sonar-dotnet-shared-library/pom.xml
sonar-vbnet-plugin/pom.xml

Bump version to 8.24

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/NameOfShouldBeUsed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/NameOfShouldBeUsed.vb

Add repro for S2302 FP

---

analyzers/tests/SonarAnalyzer.UnitTest/Rules/BooleanLiteralUnnecessaryTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/BooleanLiteralUnnecessary.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/BooleanLiteralUnnecessary.cs

Add repro for #4465

---

analyzers/src/SonarAnalyzer.CSharp/Trackers/CSharpBuilderPatternCondition.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/JwtSigned.CSharp9.cs

Rule S5659: Add support for target typed new expressions

---

analyzers/src/SonarAnalyzer.CSharp/Rules/RedundantArgument.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundantArgument.CSharp9.cs

Rule S3254: Add support for target typed new expressions

---

analyzers/src/SonarAnalyzer.CSharp/Rules/UseUriInsteadOfString.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UseUriInsteadOfString.CSharp9.cs

Rule S4005: Add support for target typed new expressions

---

analyzers/src/SonarAnalyzer.CSharp/Rules/DisposableNotDisposed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DisposableNotDisposed.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DisposableNotDisposed.cs

Rule S2930: Add support for target typed new expressions

---

analyzers/src/SonarAnalyzer.CSharp/Rules/CryptographicKeyShouldNotBeTooShort.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CryptographicKeyShouldNotBeTooShort.CSharp9.cs

Rule S4426: Add support for target typed new expressions

---

analyzers/src/SonarAnalyzer.CSharp/Facade/CSharpSyntaxKindFacade.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/InsecureEncryptionAlgorithm.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/InsecureHashAlgorithm.cs
analyzers/src/SonarAnalyzer.Common/Facade/ISyntaxKindFacade.cs
analyzers/src/SonarAnalyzer.Common/Rules/DoNotCallInsecureSecurityAlgorithmBase.cs
analyzers/src/SonarAnalyzer.Common/Rules/InsecureEncryptionAlgorithmBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Facade/VisualBasicSyntaxKindFacade.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/InsecureEncryptionAlgorithm.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/InsecureEncryptionAlgorithm.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/InsecureHashAlgorithm.CSharp9.cs

Rules S2278, S5547, S2070: Add support for target typed new expressions

---

.editorconfig
analyzers/SonarAnalyzer.sln
analyzers/StyleCopAnalyzers.targets
analyzers/stylecop.json

Add configuration for StyleCop rules

---

analyzers/src/SonarAnalyzer.CSharp/Helpers/CSharpSymbolUsageCollector.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnusedPrivateMember.CSharp9.TopLevelStatements.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnusedPrivateMember.CSharp9.cs

Rule S1144: Add support for target typed new expressions

---

analyzers/src/SonarAnalyzer.CSharp/Rules/CryptographicKeyShouldNotBeTooShort.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/RedundantDeclaration.cs
analyzers/src/SonarAnalyzer.CSharp/Wrappers/ObjectCreationFactory.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundantDeclaration.ArraySize.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundantDeclaration.ArrayType.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundantDeclaration.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundantDeclaration.DelegateParameterList.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundantDeclaration.ExplicitDelegate.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundantDeclaration.ExplicitNullable.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundantDeclaration.LambdaParameterType.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundantDeclaration.ObjectInitializer.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundantDeclaration.cs
analyzers/tests/SonarAnalyzer.UnitTest/Wrappers/ObjectCreationFactoryTest.cs

Rule S3257: Add support for target typed new expressions

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/EmptyCollectionsShouldNotBeEnumerated.cs

S4158: Add FP repro for #4478

---

sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/AbstractPropertyDefinitions.java

Update description of sonar.{cs,vbnet}.file.suffixes

---

analyzers/src/SonarAnalyzer.VisualBasic/Rules/UseReturnStatement.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UseReturnStatement.vb

Fix S5944 FP: When namespace or type is same as function name

---

analyzers/src/SonarAnalyzer.CSharp/Rules/MethodParameterUnused.cs
analyzers/src/SonarAnalyzer.Common/Rules/MethodParameterUnusedBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/MethodParameterUnused.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/MethodParameterUnused.vb

Fix S1172 FP: Should not raise for event handlers

---

.github/workflows/release.yml

Push notifs to team-lang-dotnet slack channel

---

analyzers/src/SonarAnalyzer.CSharp/Trackers/CSharpAssignmentFinder.cs
analyzers/src/SonarAnalyzer.Common/Rules/SillyBitwiseOperationBase.cs
analyzers/src/SonarAnalyzer.Common/Trackers/AssignmentFinder.cs
analyzers/src/SonarAnalyzer.VisualBasic/Trackers/VisualBasicAssignmentFinder.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SillyBitwiseOperation.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SillyBitwiseOperation.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SillyBitwiseOperation.Fixed.vb
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SillyBitwiseOperation.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SillyBitwiseOperation.vb

Fix S2437 FP: Silly bit operation with iterative aggregation

---

analyzers/src/SonarAnalyzer.VisualBasic/Rules/StringConcatenationWithPlus.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/StringConcatenationWithPlusTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/StringConcatenationWithPlus.Fixed.vb
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/StringConcatenationWithPlus.vb

Fix S1645 FP: Not applicable for XName/XNamespace

---

analyzers/src/SonarAnalyzer.CSharp/Trackers/CSharpAssignmentFinder.cs
analyzers/src/SonarAnalyzer.Common/Trackers/AssignmentFinder.cs
analyzers/src/SonarAnalyzer.VisualBasic/Trackers/VisualBasicAssignmentFinder.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Hotspots/DoNotHardcodeCredentialsTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/DoNotHardcodeCredentials_DefaultValues.CSharp8.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/DoNotHardcodeCredentials_DefaultValues.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/DoNotHardcodeCredentials_DefaultValues.vb

Fix S2068 FP: Don't propagate constants through self-modifying assignments

---

analyzers/src/SonarAnalyzer.CSharp/Rules/CheckArgumentException.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CheckArgumentException.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CheckArgumentException.TopLevelStatements.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CheckArgumentException.cs

Fix S3928 FP and FN: Parameters of local functions

---

analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/DeliveringDebugFeaturesInProduction.cs
analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/DeliveringDebugFeaturesInProductionBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/Hotspots/DeliveringDebugFeaturesInProduction.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Hotspots/DeliveringDebugFeaturesInProductionTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/DeliveringDebugFeaturesInProduction.NetCore3.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/DeliveringDebugFeaturesInProduction.NetCore3.vb

Rule S4507: Add exception for StartupDevelopment

---

analyzers/its/expected/akka.net/Akka-{5DEDDF90-37F0-48D3-A0B0-A5CBD8A7E377}-S2223.json
analyzers/src/SonarAnalyzer.CSharp/Rules/StaticFieldVisible.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/StaticFieldVisible.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/StaticFieldVisible.cs

Rule S2223: Fix FP when using ThreadStatic

---

analyzers/src/SonarAnalyzer.CSharp/Rules/LiteralsShouldNotBePassedAsLocalizedParameters.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/LiteralsShouldNotBePassedAsLocalizedParameters.cs

Fix FP when Localizable attribute has false argument in constructor

---

analyzers/src/SonarAnalyzer.CSharp/Rules/CallToAsyncMethodShouldNotBeBlocking.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CallToAsyncMethodShouldNotBeBlocking.cs

Fix NullReferenceException raised by S4462

---

.github/workflows/MilestoneIssue.yml

Do not create card when there already exist one to prevent Action error and email with an error log.
Do not add card for closed issue, it's already done.

GitHub workflow: Improve Milestone

---

analyzers/Directory.Build.props

Enable deterministic builds

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CheckArgumentException.cs

Add tests with empty/whitespace strings for S3928

---

analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Common/Checks/ByteArrayCheck.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/InitializationVectorShouldBeRandom.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/InitializationVectorShouldBeRandom.cs

S3329: fix FN with implicitly typed arrays

---

analyzers/src/SonarAnalyzer.CSharp/Rules/CertificateValidationCheck.cs
analyzers/src/SonarAnalyzer.Common/Rules/CertificateValidationCheckBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/CertificateValidationCheck.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CertificateValidationCheck.TopLevelStatements.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CertificateValidationCheck.cs

Rule S4830: Fix FN in presence of local function statements

---

analyzers/src/SonarAnalyzer.CSharp/Extensions/SyntaxNodeExtensions.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/ClassNotInstantiatable.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/ImplementIDisposableCorrectly.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/TooManyGenericParameters.cs
analyzers/tests/SonarAnalyzer.UnitTest/Extensions/SyntaxNodeExtensionsTest.cs

- to enable reuse and remove code duplication

Extract GetDeclarationTypeName

---

analyzers/its/sources/akka.net/global.json

no need to have a fixed version installed locally

RollForward for akka.net sdk version

---

analyzers/src/SonarAnalyzer.CSharp/Facade/CSharpSyntaxKindFacade.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/CertificateValidationCheck.cs
analyzers/src/SonarAnalyzer.Common/Facade/ISyntaxKindFacade.cs
analyzers/src/SonarAnalyzer.Common/Rules/CertificateValidationCheckBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Facade/VisualBasicSyntaxKindFacade.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/CertificateValidationCheck.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/CertificateValidationCheckTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CertificateValidationCheck.CSharp8.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CertificateValidationCheck.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CertificateValidationCheck.vb

Rule S4830: Fix FN with structs

---

analyzers/its/regression-test.ps1
analyzers/its/sources/AutoMapper/global.json

Switch Automapper build to dotnet from msbuild

---

analyzers/its/ReviewDiffs/ReviewDiffs.csproj
analyzers/src/Directory.Build.props
analyzers/src/SonarAnalyzer.CFG/SonarAnalyzer.CFG.csproj
analyzers/src/SonarAnalyzer.CSharp/SonarAnalyzer.CSharp.csproj
analyzers/src/SonarAnalyzer.Common/SonarAnalyzer.Common.csproj
analyzers/src/SonarAnalyzer.RuleDescriptorGenerator/SonarAnalyzer.RuleDescriptorGenerator.csproj
analyzers/src/SonarAnalyzer.Utilities/SonarAnalyzer.Utilities.csproj
analyzers/src/SonarAnalyzer.VisualBasic/SonarAnalyzer.VisualBasic.csproj
analyzers/tests/Directory.Build.props
analyzers/tests/SonarAnalyzer.UnitTest/SonarAnalyzer.UnitTest.csproj

Move RunAnalyzersDuringBuild to Directory.Build.props

---

analyzers/pom.xml
analyzers/sonaranalyzer-maven-artifacts/SonarAnalyzer.CSharp/pom.xml
analyzers/sonaranalyzer-maven-artifacts/SonarAnalyzer.RuleDocGenerator.CSharp/pom.xml
analyzers/sonaranalyzer-maven-artifacts/SonarAnalyzer.RuleDocGenerator.VisualBasic/pom.xml
analyzers/sonaranalyzer-maven-artifacts/SonarAnalyzer.VisualBasic/pom.xml
analyzers/sonaranalyzer-maven-artifacts/pom.xml
analyzers/src/AssemblyInfo.Shared.cs
analyzers/src/SonarAnalyzer.CFG/SonarAnalyzer.CFG.cs.nuspec
analyzers/src/SonarAnalyzer.Vsix/SonarAnalyzer.CSharp.nuspec
analyzers/src/SonarAnalyzer.Vsix/SonarAnalyzer.VisualBasic.nuspec
analyzers/src/SonarAnalyzer.Vsix/source.extension.vsixmanifest
pom.xml
scripts/version/Version.props
sonar-csharp-plugin/pom.xml
sonar-dotnet-shared-library/pom.xml
sonar-vbnet-plugin/pom.xml

Bump version to 8.26

---

scripts/rspec/rspec-templates/CSharpTestTemplate.cs
scripts/rspec/rspec-templates/VbNetTestTemplate.cs
scripts/rspec/rspec.ps1

Update RSPEC script to generate different code for UTs

---

analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/ConditionEvaluatesToConstantTest.cs

Add repro for AD0001 for SE

---

analyzers/tests/SonarAnalyzer.UnitTest/CBDE/PreservingEncodingTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/PropertiesAccessCorrectFieldTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/ExplodedGraphTest.cs

Remove unnecessary extern aliases

---

analyzers/src/SonarAnalyzer.CSharp/Rules/CastShouldNotBeDuplicated.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CastShouldNotBeDuplicated.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CastShouldNotBeDuplicated.cs

S3247: introduce C#9 patterns support

---

analyzers/src/SonarAnalyzer.CFG/ShimLayer/SyntaxKindEx.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/DoNotCatchSystemException.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DoNotCatchSystemException.CSharp9.cs

S2221 support C#9 patterns

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ConditionEvaluatesToConstant.CSharp8.cs

FN reproducer with local functions S2583

---

docs/contributing-analyzer.md

Mention Rider as alternative IDE

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/NullPointerDereference.cs

S2259: Add FP repro for #4537

---

analyzers/src/SonarAnalyzer.CSharp/Rules/ExpressionComplexity.cs
analyzers/src/SonarAnalyzer.Common/Rules/ExpressionComplexityBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/ExpressionComplexity.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ExpressionComplexity.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ExpressionComplexity.cs

Review per commit is suggested

Rule S1067: add support for C# 9 pattern matching

---

analyzers/src/SonarAnalyzer.CFG/Extensions/IsPatternExpressionSyntaxWrapperExtensions.cs
analyzers/src/SonarAnalyzer.CFG/Extensions/PatternSyntaxWrapperExtensions.cs
analyzers/src/SonarAnalyzer.CFG/Extensions/UnaryPatternSyntaxWrapperExtensions.cs
analyzers/src/SonarAnalyzer.CFG/Helpers/CSharpSyntaxHelper.cs
analyzers/src/SonarAnalyzer.CSharp/Extensions/CSharpCompilationExtensions.cs
analyzers/src/SonarAnalyzer.CSharp/Extensions/ExpressionSyntaxExtensions.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/ConditionalSimplification.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/ConditionalSimplificationCodeFixProvider.cs
analyzers/tests/SonarAnalyzer.UnitTest/Extensions/ExpressionSyntaxExtensionsTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Extensions/PatternSyntaxWrapperExtensionsTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/ConditionalSimplificationTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ConditionalSimplification.CSharp8.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ConditionalSimplification.CSharp8.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ConditionalSimplification.FromCSharp8.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ConditionalSimplification.FromCSharp8.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ConditionalSimplification.FromCSharp9.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ConditionalSimplification.FromCSharp9.cs

Rule S3240: add support for C# 9 pattern matching

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/EmptyNestedBlock.cs

Related to https://github.com/SonarSource/sonar-dotnet/issues/4540

Add test case with conditional compilation

---

analyzers/src/SonarAnalyzer.Common/Common/AnalyzerConfiguration.cs

(a bit of waste of resources to run CI/CD just for this, I know)

Fix AnalyzerConfiguration comment about SLVS/S4NET

---

analyzers/src/SonarAnalyzer.CSharp/Rules/GetTypeWithIsAssignableFrom.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/GetTypeWithIsAssignableFromCodeFixProvider.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/GetTypeWithIsAssignableFromTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/GetTypeWithIsAssignableFrom.CSharp9.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/GetTypeWithIsAssignableFrom.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/GetTypeWithIsAssignableFrom.Fixed.Batch.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/GetTypeWithIsAssignableFrom.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/GetTypeWithIsAssignableFrom.cs

Rule S2219: add support for C# 9 pattern matching

---

analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/ConditionEvaluatesToConstantTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ConditionEvaluatesToConstant.CSharp7.cs

Add repro for #4559

---

analyzers/its/expected/akka.net/Akka--netstandard2.0-S3060.json
analyzers/its/expected/akka.net/Akka.Persistence--netstandard2.0-S3060.json
analyzers/its/expected/akka.net/Akka.TestKit--netstandard2.0-S3060.json
analyzers/src/SonarAnalyzer.CSharp/Extensions/ExpressionSyntaxExtensions.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/DoNotTestThisWithIsOperator.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DoNotTestThisWithIsOperator.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DoNotTestThisWithIsOperator.cs

Rule S3060: add support for C# 9 pattern matching

---

analyzers/src/SonarAnalyzer.CSharp/Rules/RedundantConditionalAroundAssignment.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/RedundantConditionalAroundAssignmentCodeFixProvider.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/RedundantConditionalAroundAssignmentTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundantConditionalAroundAssignment.CSharp9.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundantConditionalAroundAssignment.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundantConditionalAroundAssignment.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundantConditionalAroundAssignment.cs

Rule S3440: add support for C# 9 pattern matching

---

analyzers/src/SonarAnalyzer.CSharp/Rules/DoNotCheckZeroSizeCollection.cs
analyzers/src/SonarAnalyzer.Common/Rules/DoNotCheckZeroSizeCollectionBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/DoNotCheckZeroSizeCollection.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DoNotCheckZeroSizeCollection.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DoNotCheckZeroSizeCollection.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DoNotCheckZeroSizeCollection.vb

S3981 FN fix, check <0

---

analyzers/src/SonarAnalyzer.CSharp/Rules/ClassWithOnlyStaticMember.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ClassWithOnlyStaticMember.cs

Fix S1118: Rule should not raise issue on abstract classes

---

analyzers/src/SonarAnalyzer.Common/Helpers/ProjectTypeHelper.cs
analyzers/tests/SonarAnalyzer.UnitTest/Helpers/ProjectTypeHelperTest.cs

This is expensive and executed in a loop it has a significant impact on performance.

Don't call ToUpperInvariant()

---

analyzers/its/expected/Net5/Net5--net5.0-S1067.json
analyzers/its/expected/Net5/Net5--net5.0-S1128.json
analyzers/its/expected/Net5/Net5--net5.0-S1301.json
analyzers/its/expected/Net5/Net5--net5.0-S1451.json
analyzers/its/expected/Net5/Net5--net5.0-S1541.json
analyzers/its/expected/Net5/Net5--net5.0-S3532.json
analyzers/its/expected/Net5/Net5--net5.0-S3874.json
analyzers/its/expected/Net5/Net5--net5.0-S4201.json
analyzers/its/sources/Net5/Net5/Apple.cs
analyzers/its/sources/Net5/Net5/S4201.cs
analyzers/src/SonarAnalyzer.CFG/Extensions/IsPatternExpressionSyntaxWrapperExtensions.cs
analyzers/src/SonarAnalyzer.CFG/Extensions/UnaryPatternSyntaxWrapperExtensions.cs
analyzers/src/SonarAnalyzer.CSharp/Extensions/ExpressionSyntaxExtensions.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/ConditionalSimplification.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/ConditionalSimplificationCodeFixProvider.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/RedundantNullCheck.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/RedundantNullCheckCodeFixProvider.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/RedundantNullCheckTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundantNullCheck.CSharp9.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundantNullCheck.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundantNullCheck.Fixed.Batch.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundantNullCheck.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundantNullCheck.cs

Rule S4201 - improve support for C# 9 pattern matching

---

analyzers/NuGet.Config
analyzers/its/ReviewDiffs/ReviewDiffs.csproj
analyzers/its/ReviewDiffs/packages.lock.json
analyzers/src/SonarAnalyzer.CSharp/SonarAnalyzer.CSharp.csproj
analyzers/src/SonarAnalyzer.CSharp/packages.lock.json
analyzers/src/SonarAnalyzer.RuleDescriptorGenerator/packages.lock.json
analyzers/src/SonarAnalyzer.Utilities/packages.lock.json
analyzers/src/SonarAnalyzer.Vsix/packages.lock.json
analyzers/tests/SonarAnalyzer.UnitTest/packages.lock.json

Update Newtonsoft.Json to 13.0.1

---

analyzers/pom.xml
analyzers/sonaranalyzer-maven-artifacts/SonarAnalyzer.CSharp/pom.xml
analyzers/sonaranalyzer-maven-artifacts/SonarAnalyzer.RuleDocGenerator.CSharp/pom.xml
analyzers/sonaranalyzer-maven-artifacts/SonarAnalyzer.RuleDocGenerator.VisualBasic/pom.xml
analyzers/sonaranalyzer-maven-artifacts/SonarAnalyzer.VisualBasic/pom.xml
analyzers/sonaranalyzer-maven-artifacts/pom.xml
analyzers/src/AssemblyInfo.Shared.cs
analyzers/src/SonarAnalyzer.CFG/SonarAnalyzer.CFG.cs.nuspec
analyzers/src/SonarAnalyzer.Vsix/SonarAnalyzer.CSharp.nuspec
analyzers/src/SonarAnalyzer.Vsix/SonarAnalyzer.VisualBasic.nuspec
analyzers/src/SonarAnalyzer.Vsix/source.extension.vsixmanifest
pom.xml
scripts/version/Version.props
sonar-csharp-plugin/pom.xml
sonar-dotnet-shared-library/pom.xml
sonar-vbnet-plugin/pom.xml

Bump version to 8.27 after release

---

analyzers/its/expected/Net5/Net5--net5.0-S126.json

Update message in expected issues to fix the build.

---

analyzers/src/SonarAnalyzer.CSharp/Rules/CheckArgumentException.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CheckArgumentException.CSharp9.cs

Rule S3928: introduce support for C# 9 init-only setters

---

analyzers/src/SonarAnalyzer.CSharp/Rules/EmptyNestedBlock.cs
analyzers/src/SonarAnalyzer.Common/Rules/EmptyNestedBlockBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/EmptyNestedBlock.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/EmptyNestedBlock.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/EmptyNestedBlock.vb

S108 FP fix-when conditional compilation

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/FieldShouldBeReadonly.CSharp9.cs

Rule S2933 - fix UT for C# 9

---

analyzers/src/SonarAnalyzer.CSharp/Rules/RedundantJumpStatement.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundantJumpStatement.CSharp9.cs

Rule S3626: introduce support for C# 9 init-only setters

---

analyzers/src/SonarAnalyzer.CSharp/Rules/RedundantConditionalAroundAssignment.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundantConditionalAroundAssignment.CSharp9.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundantConditionalAroundAssignment.CSharp9.cs

Rule S3440: introduce support for C# 9 init-only setters

---

analyzers/src/SonarAnalyzer.CSharp/Rules/FunctionComplexity.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/FunctionComplexity.CSharp9.cs

Rule S1541: introduce support for C# 9 init-only setters

---

THIRD-PARTY-NOTICES.txt
analyzers/src/SonarAnalyzer.Vsix/SonarAnalyzer.CSharp.nuspec
analyzers/src/SonarAnalyzer.Vsix/SonarAnalyzer.VisualBasic.nuspec
sonar-csharp-plugin/pom.xml
sonar-vbnet-plugin/pom.xml

Update 3rd party licenses and include in packages

---

azure-pipelines.yml

see https://discuss.sonarsource.com/t/gh-integration-main-branch-commit-is-green-even-if-qg-failed/7941/9

Fix main branch SC decoration

---

analyzers/its/expected/Net5/Net5--net5.0-S3928.json
analyzers/src/SonarAnalyzer.CSharp/Rules/CheckArgumentException.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CheckArgumentException.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CheckArgumentException.cs

Rule S3928 - don't raise the issue when property name is used in nameof() call.

---

analyzers/its/expected/Net5/Net5--net5.0-S3237.json
analyzers/src/SonarAnalyzer.CSharp/Rules/UseValueParameter.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UseValueParameter.CSharp9.cs

Rule S3237: introduce support for C# 9 init-only setters

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DoNotDecreaseMemberVisibility.CSharp9.cs

Add test with init accessor for the rule S4015

---

analyzers/src/SonarAnalyzer.CSharp/Rules/DisposableNotDisposed.cs
analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
analyzers/tests/SonarAnalyzer.UnitTest/Helpers/RemovableDeclarationCollectorTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/DisposableNotDisposedTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DisposableNotDisposed.cs

Fixes #3914
Rebase will be needed after merge of #4693, the squash commit doesn't need a review.

S2930 : Add AssertionScope to the list of tracked types

---

analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SolutionBuilder.cs
analyzers/tests/SonarAnalyzer.UnitTest/Trackers/MethodDeclarationTrackerTest.cs

Provide default imports for VB.NET UnitTest project

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ConditionalSimplification.CSharp8.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ConditionalSimplification.CSharp8.cs

FP reproducer for S3240

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/MethodParameterUnused.CSharp8.cs

FP reproducer when parameter is used in generic local function

---

analyzers/src/SonarAnalyzer.CSharp/Rules/InvalidCastToInterface.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/MemberShouldNotHaveConflictingTransparencyAttributes.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/StaticFieldWrittenFrom.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/StringFormatValidator.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/SymbolicExecutionRunner.cs
analyzers/src/SonarAnalyzer.Common/DiagnosticAnalyzer/SonarDiagnosticAnalyzer.cs
analyzers/tests/SonarAnalyzer.UnitTest/Common/RuleTest.cs

Enable concurrent analysis for .NET Analyzer rules

---

analyzers/src/SonarAnalyzer.CSharp/Rules/EqualityOnModulus.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/EqualityOnModulus.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/EqualityOnModulus.cs

Rule S2197: add support for native integers

---

azure-pipelines.yml

Enable concurrent execution for ITs

---

analyzers/its/expected/Net5/Net5--net5.0-S108.json
analyzers/its/expected/Net5/Net5--net5.0-S1451.json
analyzers/its/expected/Net5/Net5--net5.0-S1481.json
analyzers/its/expected/Net5/Net5--net5.0-S2325.json
analyzers/its/expected/Net5/Net5--net5.0-S3353.json
analyzers/its/sources/Net5/Net5/S3353.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/UnchangedLocalVariablesShouldBeConst.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnchangedLocalVariablesShouldBeConst.CSharp9.cs

Related to https://jira.sonarsource.com/browse/MMF-2222

Rule S3353: add support for top level methods

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/EqualityOnModulus.cs

Document S2197 false positives

---

analyzers/its/expected/Net5/Net5--net5.0-S1451.json
analyzers/its/expected/Net5/Net5--net5.0-S1854.json
analyzers/its/expected/Net5/Net5--net5.0-S2325.json
analyzers/its/expected/Net5/Net5--net5.0-S2437.json
analyzers/its/expected/Net5/Net5--net5.0-S3353.json
analyzers/its/sources/Net5/Net5/S2437.cs
analyzers/src/SonarAnalyzer.CFG/ShimLayer/SyntaxKindEx.cs
analyzers/src/SonarAnalyzer.CSharp/Extensions/MemberAccessExpressionSyntaxExtensions.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/SillyBitwiseOperation.cs
analyzers/src/SonarAnalyzer.CSharp/Trackers/CSharpAssignmentFinder.cs
analyzers/src/SonarAnalyzer.CSharp/Trackers/CSharpConstantValueFinder.cs
analyzers/src/SonarAnalyzer.Common/Rules/SillyBitwiseOperationBase.cs
analyzers/src/SonarAnalyzer.Common/Trackers/AssignmentFinder.cs
analyzers/src/SonarAnalyzer.Common/Trackers/ConstantValueFinder.cs
analyzers/src/SonarAnalyzer.Shared/Extensions/MemberAccessExpressionSyntaxExtensions.cs
analyzers/src/SonarAnalyzer.VisualBasic/Extensions/MemberAccessExpressionSyntaxExtensions.cs
analyzers/src/SonarAnalyzer.VisualBasic/Trackers/VisualBasicConstantValueFinder.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/LdapConnectionShouldBeSecureTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/JwtSigned.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/LdapConnectionShouldBeSecure.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SillyBitwiseOperation.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SillyBitwiseOperation.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SillyBitwiseOperation.cs

Rule S2437: add support for native integers

---

analyzers/its/expected/Net5/Net5--net5.0-S1118.json
analyzers/its/expected/Net5/Net5--net5.0-S112.json
analyzers/its/expected/Net5/Net5--net5.0-S1451.json
analyzers/its/expected/Net5/Net5--net5.0-S3877.json
analyzers/its/sources/Net5/Net5/S3877.cs
analyzers/src/SonarAnalyzer.CSharp/Extensions/SyntaxNodeExtensions.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/ExceptionShouldNotBeThrownFromUnexpectedMethods.cs
analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
analyzers/tests/SonarAnalyzer.UnitTest/Extensions/SyntaxNodeExtensionsTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ExceptionShouldNotBeThrownFromUnexpectedMethods.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ExceptionShouldNotBeThrownFromUnexpectedMethods.cs

RSPEC PR : https://github.com/SonarSource/rspec/pull/231

Rule S3877: add support for throw expressions and module initializers

---

analyzers/src/SonarAnalyzer.CSharp/Rules/Utilities/LogAnalyzer.cs
analyzers/src/SonarAnalyzer.Common/Rules/Utilities/LogAnalyzerBase.cs
analyzers/src/SonarAnalyzer.Common/Rules/Utilities/UtilityAnalyzerBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/Utilities/LogAnalyzer.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/LogAnalyzerTest.cs

Log language version

---

analyzers/src/SonarAnalyzer.CSharp/Rules/ParameterValidationInAsyncShouldBeWrapped.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ParameterValidationInAsyncShouldBeWrapped.cs

Fix S4457 FP: Should not raise on `async Task Main(string[] args)'

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ConditionEvaluatesToConstant.cs

S2583: Add FP repro for #4755

---

azure-pipelines.yml

`$(solution)` was wrong since it contains `analyzers` folder too.

Fix solution path

---

analyzers/its/expected/Net5/Net5--net5.0-S1118.json
analyzers/its/expected/Net5/Net5--net5.0-S1144.json
analyzers/its/expected/Net5/Net5--net5.0-S1186.json
analyzers/its/expected/Net5/Net5--net5.0-S1192.json
analyzers/its/expected/Net5/Net5--net5.0-S1451.json
analyzers/its/expected/Net5/Net5--net5.0-S4583.json
analyzers/its/sources/Net5/Net5/S4583.Part1.cs
analyzers/its/sources/Net5/Net5/S4583.Part2.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/BeginInvokePairedWithEndInvoke.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/BeginInvokePairedWithEndInvokeTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/BeginInvokePairedWithEndInvoke.CSharp9.Part1.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/BeginInvokePairedWithEndInvoke.CSharp9.Part2.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/BeginInvokePairedWithEndInvoke.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/BeginInvokePairedWithEndInvoke.cs

Rule S4583: Add support for C# 9 partial methods

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SillyBitwiseOperation.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SillyBitwiseOperation.cs

Related to https://github.com/SonarSource/sonar-dotnet/issues/4774

S2437: document FP with local fields

---

.github/workflows/CreatePullRequest.yml
.github/workflows/RequestReview.yml
.github/workflows/SubmitReview.yml

Verified here: https://github.com/pavel-mikula-sonarsource/GitHubActionPlayground/pull/27

GitHub workflow: Fix null PR body after API change

---

analyzers/src/SonarAnalyzer.Common/Extensions/ISymbolExtensions.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/PropertyWithArrayType.cs
analyzers/tests/SonarAnalyzer.UnitTest/Extensions/VisualBasic/ISymbolExtensionsTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/PropertyWithArrayType.vb

Fix S2365 FP: Should not raise for overriding methods and interface implementations

---

analyzers/its/expected/akka.net/Akka.Cluster.Tests--net471-S2699.json
analyzers/its/expected/akka.net/Akka.Cluster.Tests--net5.0-S2699.json
analyzers/its/expected/akka.net/Akka.Cluster.Tests--netcoreapp3.1-S2699.json
analyzers/its/expected/akka.net/Akka.Cluster.Tests.MultiNode--net471-S2699.json
analyzers/its/expected/akka.net/Akka.Cluster.Tests.MultiNode--net5.0-S2699.json
analyzers/its/expected/akka.net/Akka.Cluster.Tests.MultiNode--netcoreapp3.1-S2699.json
analyzers/its/expected/akka.net/Akka.MultiNodeTestRunner.Shared.Tests--net471-S2699.json
analyzers/its/expected/akka.net/Akka.MultiNodeTestRunner.Shared.Tests--net5.0-S2699.json
analyzers/its/expected/akka.net/Akka.MultiNodeTestRunner.Shared.Tests--netcoreapp3.1-S2699.json
analyzers/its/expected/akka.net/Akka.Tests--net471-S2699.json
analyzers/its/expected/akka.net/Akka.Tests--net5.0-S2699.json
analyzers/its/expected/akka.net/Akka.Tests--netcoreapp3.1-S2699.json
analyzers/src/SonarAnalyzer.CSharp/Rules/MethodShouldBeNamedAccordingToSynchronicity.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/TestClassShouldHaveTestMethod.cs
analyzers/src/SonarAnalyzer.Common/Helpers/SymbolHelper.cs
analyzers/src/SonarAnalyzer.Common/Helpers/UnitTestHelper.cs
analyzers/tests/SonarAnalyzer.UnitTest/Helpers/SymbolHelperTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/MethodShouldBeNamedAccordingToSynchronicity.MsTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/TestClassShouldHaveTestMethod.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/TestClassShouldHaveTestMethod.MsTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/TestClassShouldHaveTestMethod.NUnit.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/TestMethodShouldContainAssertion.MsTest.cs

S2187 FP: Derived test method attribute usage fix

---

analyzers/rspec/cs/S1764_c#.json
analyzers/rspec/vbnet/S1764_vb.net.json
analyzers/src/SonarAnalyzer.CSharp/RspecStrings.resx
analyzers/src/SonarAnalyzer.VisualBasic/RspecStrings.resx
analyzers/tests/SonarAnalyzer.UnitTest/Rules/BinaryOperationWithIdenticalExpressionsTest.cs

Fix S1764 FP: Don't run on Test code

---

analyzers/src/SonarAnalyzer.CSharp/Rules/ConditionalSimplification.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ConditionalSimplification.CSharp8.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ConditionalSimplification.CSharp8.cs

Fix S3240 FP: Property initializers that share a name

---

analyzers/its/expected/Net5/Net5--net5.0-S1541.json
analyzers/its/expected/Net5/variouspatternsofpatterns-3EFB6389-ED5B-4E14-809C-B43AF38748D9-net5.0-S1541.json
analyzers/src/SonarAnalyzer.CSharp/Metrics/CSharpCyclomaticComplexityMetric.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/FunctionComplexity.CSharp9.cs

Rule S1541: supports C#9 patterns

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/NullPointerDereference.cs

S2259: ToList() FP repro

---

analyzers/src/SonarAnalyzer.CSharp/Rules/NotAssignedPrivateMember.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/NotAssignedPrivateMember.cs

Fix S3459 FN: Support fields in generic classes

---

sonar-csharp-plugin/src/main/resources/documentation.md
sonar-vbnet-plugin/src/main/resources/documentation.md

Fixes #4783 by adding a section on Improving Performance with the new concurrent execution setting. Let me know who else  you think should review this @pavel-mikula-sonarsource and I can add them?

Add 'Improving Performance' embedded documentation (#4783)

---

analyzers/tests/SonarAnalyzer.UnitTest/Rules/MethodOverrideChangedDefaultValueTest.cs
azure-pipelines.yml
scripts/utils.ps1

Reduce CI running time by running .Net tests in parallel (by framework)

---

analyzers/src/SonarAnalyzer.CFG/Helpers/RoslynHelper.cs
analyzers/src/SonarAnalyzer.CFG/Roslyn/BasicBlock.cs
analyzers/src/SonarAnalyzer.CFG/Roslyn/ControlFlowGraph.cs
analyzers/src/SonarAnalyzer.CFG/Roslyn/ControlFlowRegion.cs
analyzers/src/SonarAnalyzer.CFG/SonarAnalyzer.CFG.csproj
analyzers/tests/SonarAnalyzer.UnitTest/CBDE/CheckMlirWithReference.cs
analyzers/tests/SonarAnalyzer.UnitTest/CFG/Sonar/Roslyn/RoslynControlFlowGraphTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/CFG/Sonar/Sonar/SonarCfgSerializerTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/CFG/Sonar/Sonar/SonarControlFlowGraphTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/LiveVariableAnalysis/LiveVariableAnalysisTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/ExplodedGraphTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/ProgramStateTest.cs

2nd attempt after the 1st PR was accidentally closed by renaming base branch #4821

Introduce Roslyn CFG wrapper

---

analyzers/src/SonarAnalyzer.CFG/Helpers/RoslynHelper.cs
analyzers/src/SonarAnalyzer.CFG/Roslyn/BasicBlock.cs
analyzers/src/SonarAnalyzer.CFG/Roslyn/BasicBlockKind.cs
analyzers/src/SonarAnalyzer.CFG/Roslyn/ControlFlowBranch.cs
analyzers/src/SonarAnalyzer.CFG/Roslyn/ControlFlowConditionKind.cs
analyzers/src/SonarAnalyzer.CFG/Roslyn/ControlFlowGraph.cs
analyzers/src/SonarAnalyzer.CFG/Roslyn/ControlFlowRegion.cs
analyzers/tests/SonarAnalyzer.UnitTest/CFG/Roslyn/BasicBlockTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/CFG/Roslyn/ControlFlowRegionTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/CFG/Roslyn/RoslynControlFlowGraphTest.cs

`Squash ControlFlowRegion` commit doesn't need a review, it's in #4828

Introduce BasicBlock wrapper

---

analyzers/rspec/cs/S4261_c#.html
analyzers/rspec/cs/S4261_c#.json
analyzers/src/SonarAnalyzer.CSharp/RspecStrings.resx
analyzers/src/SonarAnalyzer.CSharp/Rules/MethodShouldBeNamedAccordingToSynchronicity.cs
analyzers/src/SonarAnalyzer.Utilities/Rules.Description/S4261.html
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/MethodShouldBeNamedAccordingToSynchronicity.cs

Rule S4261: Undeprecate and add FP example

---

analyzers/src/SonarAnalyzer.CSharp/Rules/StaticFieldWrittenFromInstanceConstructor.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/StaticFieldWrittenFromInstanceMember.cs
analyzers/src/SonarAnalyzer.CSharp/SonarAnalyzer.CSharp.csproj
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/StaticFieldWrittenFromInstanceMember.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/StaticFieldWrittenFromInstanceMember.cs

IMO static lambdas should work as they currently work.

S2696 - update tests

---

analyzers/src/SonarAnalyzer.CFG/Helpers/SemanticModelHelper.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/DoNotUseLiteralBoolInAssertions.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DoNotUseLiteralBoolInAssertions.MsTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DoNotUseLiteralBoolInAssertions.NUnit.cs

Refactor, minor perf improvement.

Refactor DoNotUseLiteralBoolInAssertions S2701

---

analyzers/tests/SonarAnalyzer.UnitTest/Rules/UnnecessaryUsingsTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnnecessaryUsingsFNRepro.cs

 S1128 FN repro with built in types.

---

analyzers/src/SonarAnalyzer.Common/Rules/CertificateValidationCheckBase.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/CertificateValidationCheckTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CertificateValidationCheck.CSharp9.Partial.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CertificateValidationCheck.CSharp9.cs

Fix S4830 FN: Extended partial methods feature support is missing

---

analyzers/its/expected/Net5/Net5--net5.0-S3881.json
analyzers/src/SonarAnalyzer.CSharp/Rules/ImplementIDisposableCorrectly.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/ImplementIDisposableCorrectlyTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ImplementIDisposableCorrectly.CSharp9.cs

Fix S3881 FP: Extended partial methods feature support is missing

---

README.md

As requested in https://community.sonarsource.com/t/document-configurability-of-sonar-dotnet/47883/3

Update README: Document configurability 

---

analyzers/src/SonarAnalyzer.CSharp/Rules/TestMethodShouldContainAssertion.cs
analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
analyzers/tests/SonarAnalyzer.UnitTest/MetadataReferences/NuGetMetadataReference.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/TestMethodShouldContainAssertionTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/TestMethodShouldContainAssertion.MsTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/TestMethodShouldContainAssertion.NUnit.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/TestMethodShouldContainAssertion.Xunit.Legacy.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/TestMethodShouldContainAssertion.Xunit.cs

S2699 NFluent support

---

analyzers/tests/SonarAnalyzer.UnitTest/CFG/Sonar/SonarControlFlowGraphTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/LiveVariableAnalysis/LiveVariableAnalysisTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/LiveVariableAnalysis/SonarLiveVariableAnalysisTest.cs

We need to cover the existing LVA with isolated UTs.
This is a draft for now to simplify the review, more commits will arrive for:

Add LVA UTs

---

analyzers/src/SonarAnalyzer.CSharp/Rules/FieldShouldBeReadonly.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/FieldShouldBeReadonlyCodeFixProvider.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/FieldShouldBeReadonly.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/FieldShouldBeReadonly.cs

S2933 FP fix: Tuple deconstruction 

---

analyzers/tests/SonarAnalyzer.UnitTest/Helpers/RemovableDeclarationCollectorTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Helpers/SymbolHelperTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/MetadataReferences/MetadataReferenceFacade.cs
analyzers/tests/SonarAnalyzer.UnitTest/MetadataReferences/WindowsFormsMetadataReference.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/MarkWindowsFormsMainWithStaThreadTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/SonarAnalyzer.UnitTest.csproj
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/MarkWindowsFormsMainWithStaThread.vb
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/PropertiesAccessCorrectField.NetFramework.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/PropertiesAccessCorrectField.vb

WinForms support in unit tests when targeting .Net Core

---

analyzers/src/SonarAnalyzer.CSharp/Rules/MarkWindowsFormsMainWithStaThread.cs
analyzers/src/SonarAnalyzer.Common/Rules/MarkWindowsFormsMainWithStaThreadBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/MarkWindowsFormsMainWithStaThread.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/MarkWindowsFormsMainWithStaThreadTest.cs

S4210 FP: Issue raised in class libraries fix

---

analyzers/its/expected/akka.net/Akka--netstandard2.0-S2302.json
analyzers/its/expected/akka.net/Akka.Cluster--netstandard2.0-S2302.json
analyzers/its/expected/akka.net/Akka.Cluster.Tools--netstandard2.0-S2302.json
analyzers/its/expected/akka.net/Akka.Persistence--netstandard2.0-S2302.json
analyzers/its/expected/akka.net/Akka.Remote--netstandard2.0-S2302.json
analyzers/its/expected/akka.net/Akka.Streams--netstandard2.0-S2302.json
analyzers/its/expected/akka.net/Akka.TestKit--netstandard2.0-S2302.json
analyzers/src/SonarAnalyzer.CSharp/Facade/CSharpSyntaxKindFacade.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/NameOfShouldBeUsed.cs
analyzers/src/SonarAnalyzer.Common/Facade/ISyntaxKindFacade.cs
analyzers/src/SonarAnalyzer.Common/Rules/NameOfShouldBeUsedBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Facade/VisualBasicSyntaxKindFacade.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/NameOfShouldBeUsed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/NameOfShouldBeUsed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/NameOfShouldBeUsed.vb

Rule S2302: Get rid of noisy FP

---

analyzers/src/SonarAnalyzer.CFG/ShimLayer/SyntaxKindEx.cs
analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/CSharp/CSharpExplodedGraph.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ConditionEvaluatesToConstant.CSharp9.cs

Ensure we don't throw on AndPattern, OrPattern and NotPattern

---

analyzers/src/SonarAnalyzer.CFG/Extensions/ControlFlowGraphExtensions.cs
analyzers/src/SonarAnalyzer.CFG/LiveVariableAnalysis/RoslynLiveVariableAnalysis.cs
analyzers/src/SonarAnalyzer.CFG/Roslyn/ControlFlowGraph.cs
analyzers/tests/SonarAnalyzer.UnitTest/CFG/Roslyn/RoslynControlFlowGraphTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Extensions/ControlFlowGraphExtensionsTests.cs
analyzers/tests/SonarAnalyzer.UnitTest/LiveVariableAnalysis/RoslynLiveVariableAnalysisTest.LocalFunction.cs

This is a draft for now, first commit `Squash LocalFunction` doesn't need a review, it's in #4913

Reference to a local function support in Roslyn LVA

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/TypeMemberVisibility.cs

to document the analyzer behavior

Rule S3059: add test case with ctors

---

analyzers/src/SonarAnalyzer.CSharp/Rules/TestMethodShouldHaveCorrectSignature.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/TestMethodShouldHaveCorrectSignature.Xunit.Legacy.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/TestMethodShouldHaveCorrectSignature.Xunit.cs

Fix S3433: FP on xUnit async void methods

---

analyzers/src/SonarAnalyzer.CSharp/Rules/PureAttributeOnVoidMethod.cs
analyzers/src/SonarAnalyzer.Common/Helpers/RefKindEx.cs
analyzers/src/SonarAnalyzer.Common/Rules/PureAttributeOnVoidMethodBase.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/PureAttributeOnVoidMethodTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/PureAttributeOnVoidMethod.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/PureAttributeOnVoidMethod.vb

Extending the logic was straightforward.

FP S3603: A function that returns a Task, is not a pure function but an async void

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/StaticFieldInGenericClass.cs

Rule S2743: document false positives

---

analyzers/src/SonarAnalyzer.CSharp/Rules/DeadStores.cs
analyzers/tests/SonarAnalyzer.UnitTest/LiveVariableAnalysis/RoslynLiveVariableAnalysisTest.TryCatchFinally.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DeadStores.RoslynCfg.cs

Reproduces #4948
Reproduces #4949
This is a draft to prevent merging before release

S1854: Add FP repro for #4948 and #4949

---

analyzers/tests/SonarAnalyzer.UnitTest/Rules/MemberInitializerRedundantTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/MemberInitializerRedundant.RoslynCfg.FlowCaptureBug.cs

Document S3604 FN: ? : operation should be supported for Roslyn CFG

---

analyzers/src/SonarAnalyzer.CSharp/Extensions/SyntaxNodeExtensions.cs
analyzers/src/SonarAnalyzer.CSharp/Facade/CSharpSyntaxFacade.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/BooleanLiteralUnnecessary.cs
analyzers/src/SonarAnalyzer.CSharp/Trackers/CSharpBuilderPatternCondition.cs
analyzers/src/SonarAnalyzer.Common/Facade/SyntaxFacade.cs
analyzers/src/SonarAnalyzer.Common/Rules/BooleanLiteralUnnecessaryBase.cs
analyzers/src/SonarAnalyzer.Common/Trackers/BuilderPatternCondition.cs
analyzers/src/SonarAnalyzer.VisualBasic/Facade/VisualBasicSyntaxFacade.cs
analyzers/src/SonarAnalyzer.VisualBasic/Helpers/VisualBasicSyntaxHelper.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/BooleanLiteralUnnecessary.cs
analyzers/src/SonarAnalyzer.VisualBasic/Trackers/VisualBasicBuilderPatternCondition.cs

Add RemoveParentheses to SyntaxFacade

---

analyzers/src/SonarAnalyzer.CSharp/Rules/NonDerivedPrivateClassesShouldBeSealed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/NonDerivedPrivateClassesShouldBeSealed.cs

 Rule S3260: FP when private class has a virtual member

---

sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/sarif/SarifParser10.java
sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/sarif/SarifParserCallback.java
sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/sarif/SarifParser10Test.java
sonar-dotnet-shared-library/src/test/resources/SarifParserTest/v1_0_no_message.json

- add a warning for this case
Fixes #5034

Ensure we don't fail when the issue message is missing

---

analyzers/src/SonarAnalyzer.Common/Rules/CertificateValidationCheckBase.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CertificateValidationCheck.cs

InvalidOperationException thrown by CertificateValidationCheck

---

sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/sarif/Location.java
sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/sarif/SarifParser10.java
sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/sarif/SarifParserCallback.java
sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/sarif/SarifParser10Test.java
sonar-dotnet-shared-library/src/test/resources/SarifParserTest/v1_0_no_message.json

- SQ/SC will reject them
Related to #5034

Do not push issues without a message

---

analyzers/src/SonarAnalyzer.CSharp/Rules/NonDerivedPrivateClassesShouldBeSealed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/NonDerivedPrivateClassesShouldBeSealed.cs

Fixes #4983
Related PR for virtual members FP: #5027

Rule S3260: FP when nested private class inherits from outer private class.

---

analyzers/src/SonarAnalyzer.CSharp/Rules/AssignmentInsideSubExpression.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/AssignmentInsideSubExpression.CSharp9.cs

Rule S1121: FP in IsPattern context

---

.github/workflows/release.yml

Reverts SonarSource/sonar-dotnet#4891

Revert "Bump jfrog/setup-jfrog-cli from 1.2.0 to 2"

---

analyzers/its/expected/Nancy/Nancy--net452-S4581.json
analyzers/its/expected/Nancy/Nancy--netstandard2.0-S4581.json
analyzers/rspec/cs/S4581_c#.html
analyzers/rspec/cs/S4581_c#.json
analyzers/src/SonarAnalyzer.CSharp/RspecStrings.resx
analyzers/src/SonarAnalyzer.CSharp/Rules/NewGuidShouldNotBeUsed.cs
analyzers/src/SonarAnalyzer.Utilities/Rules.Description/S4581.html
analyzers/tests/SonarAnalyzer.UnitTest/Rules/NewGuidShouldNotBeUsedTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/NewGuidShouldNotBeUsed.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/NewGuidShouldNotBeUsed.cs

S4581: Issue is raised for implicit constructor and default expressions.

---

analyzers/tests/SonarAnalyzer.UnitTest/Json/LexicalAnalyzerTest.cs

Adds missing test from https://github.com/SonarSource/sonar-dotnet/pull/5049

Add missing test for the JSON parser

---

azure-pipelines.yml

AZP opencover: add excludebyattribute

---

analyzers/tests/SonarAnalyzer.UnitTest/Rules/BooleanLiteralUnnecessaryTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/BooleanLiteralUnnecessary.CSharp8.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/BooleanLiteralUnnecessary.CSharp8.cs

Reproduces: https://github.com/SonarSource/sonar-dotnet/issues/5013

Add repro for codefix provider issue S1125

---

azure-pipelines.yml
scripts/whitesource/WhiteSource-Scan.ps1
scripts/whitesource/wss-unified-agent.config

Implement WhiteSource scan

---

azure-pipelines.yml
scripts/whitesource/WhiteSource-Scan.ps1

Remove WhiteSource-Scan.ps1 parameter

---

analyzers/its/expected/Net5/Net5--net5.0-S3981.json
analyzers/src/SonarAnalyzer.CSharp/Facade/CSharpSyntaxFacade.cs
analyzers/src/SonarAnalyzer.CSharp/Facade/CSharpSyntaxKindFacade.cs
analyzers/src/SonarAnalyzer.CSharp/Helpers/CSharpExpressionNumericConverter.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/DoNotCheckZeroSizeCollection.cs
analyzers/src/SonarAnalyzer.Common/Extensions/CountComparisonResultExtensions.cs
analyzers/src/SonarAnalyzer.Common/Facade/ISyntaxKindFacade.cs
analyzers/src/SonarAnalyzer.Common/Facade/SyntaxFacade.cs
analyzers/src/SonarAnalyzer.Common/Helpers/ExpressionNumericConverterBase.cs
analyzers/src/SonarAnalyzer.Common/Helpers/IExpressionNumericConverter.cs
analyzers/src/SonarAnalyzer.Common/Rules/DoNotCheckZeroSizeCollectionBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Facade/VisualBasicSyntaxFacade.cs
analyzers/src/SonarAnalyzer.VisualBasic/Facade/VisualBasicSyntaxKindFacade.cs
analyzers/src/SonarAnalyzer.VisualBasic/Helpers/VisualBasicExpressionNumericConverter.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/DoNotCheckZeroSizeCollection.cs
analyzers/tests/SonarAnalyzer.UnitTest/Facade/SyntaxFacadeTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Helpers/CountComparisonResultExtensionsTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DoNotCheckZeroSizeCollection.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DoNotCheckZeroSizeCollection.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DoNotCheckZeroSizeCollection.vb

Simplify S3981 implementation DoNotCheckZeroSizeCollection

---

scripts/whitesource/WhiteSource-Scan.ps1

- it is already installed on the machine

Do not download WhiteSource tool

---

analyzers/src/SonarAnalyzer.CSharp/Rules/RedundantCast.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/RedundantCastTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundantCast.CSharp9.cs

Fix S1905: false positive with OfType

---

analyzers/src/SonarAnalyzer.CSharp/packages.lock.json
analyzers/src/SonarAnalyzer.Common/SonarAnalyzer.Common.csproj
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/ProgramState.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SymbolicExecutionCheck.cs
analyzers/src/SonarAnalyzer.Common/packages.lock.json
analyzers/src/SonarAnalyzer.RuleDescriptorGenerator/packages.lock.json
analyzers/src/SonarAnalyzer.Utilities/packages.lock.json
analyzers/src/SonarAnalyzer.VisualBasic/packages.lock.json
analyzers/src/SonarAnalyzer.Vsix/packages.lock.json
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ProgramStateTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/FluentTestHelper.cs
analyzers/tests/SonarAnalyzer.UnitTest/packages.lock.json

Only commits after `Squash SimplifyRunner` needs a review

Scaffold RoslynSymbolicExecution

---

analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/SymbolicExecutionRunner.cs

Improve analyzer performance when no SE rule is active

---

analyzers/src/SonarAnalyzer.CFG/ShimLayer/IOperationWrapperSonar.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/ProgramState.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SymbolicValue.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SymbolicValueCounter.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ProgramStateTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/SymbolicValueTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SymbolicExecution/TestChecks.cs
analyzers/tests/SonarAnalyzer.UnitTest/Wrappers/IOperationWrapperSonarTest.cs

`Squash ExplodedNode` commit doesn't need a review

Introduce SymbolicValue in SE

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Constraints/LockConstraint.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SymbolicValue.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/SymbolicValueTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/SymbolicConstraintTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SymbolicExecution/CollectorTestCheck.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SymbolicExecution/ProcessTestChecks.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SymbolicExecution/TestConstraints.cs

`Squash UseCSharp9` commit doesn't need a review

Introduce SymbolicConstraint in SE

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/ProgramState.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ProgramStateTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.cs

Squash* commits do not need a review

Track symbols in ProgramState

---

analyzers/its/SonarAnalyzer.Testing.ImportBefore.targets

Implements this suggestion https://github.com/SonarSource/sonar-dotnet/pull/5143#discussion_r763867980

Remove SonarAnalyzerRegressionTestRunning property

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/ExplodedNode.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SymbolicExecution/CollectorTestCheck.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SymbolicExecution/SETestContext.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SymbolicExecution/SetTestConstraintCheck.cs

`Squash ImproveChecks` commit doesn't need a review

Ordinal block processing in SE

---

analyzers/src/SonarAnalyzer.CSharp/SonarAnalyzer.CSharp.csproj
analyzers/src/SonarAnalyzer.VisualBasic/SonarAnalyzer.VisualBasic.csproj

Add url and description when signing

---

README.md
docs/contributing-analyzer.md

[DOCS] Rm vsix reference from docs; update Directory.Build.targets link

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/NonDerivedPrivateClassesShouldBeSealed.cs

S3260: Add FP repro for #5160

---

analyzers/src/SonarAnalyzer.CSharp/Helpers/CSharpSyntaxHelper.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/PureAttributeOnVoidMethod.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/ExpandingArchives.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/JwtSigned.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/PureAttributeOnVoidMethod.CSharp9.cs

Fix S3603 Bug and FN: NRE for local method with qualified attributes

---

analyzers/src/SonarAnalyzer.Common/Helpers/SonarAnalysisContext.cs
analyzers/tests/SonarAnalyzer.UnitTest/Helpers/SonarAnalysisContextTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/SymbolicExecutionRunnerTest.cs

Fixes #5173
The squash commit doesn't need a review

Support mixed scopes in a single analyzer class

---

analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/HashesShouldHaveUnpredictableSalt.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/InitializationVectorShouldBeRandom.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/RestrictDeserializedTypes.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/HashesShouldHaveUnpredictableSaltTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/InitializationVectorShouldBeRandomTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/RestrictDeserializedTypesTest.cs

Squash* commits doesn't need a review

Migrate security SE rules to the SE Verifier overloads

---

analyzers/src/SonarAnalyzer.VisualBasic/Helpers/VisualBasicEquivalenceChecker.cs

This PR was initially created to test if the external pipeline works, however after checking that the PR can be merged as it contains "useful" stuff.

Fix a couple of code smells

---

sonar-vbnet-plugin/pom.xml

This also aligns the size with C# range to avoid VB.NET maintenance too often
https://github.com/SonarSource/sonar-dotnet/blob/26115eaece6f30560c2fa1362eddd0c46ac8f43d/sonar-csharp-plugin/pom.xml#L209-L212

Update VB.NET expected plugin size

---

analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Sonar/SonarExplodedGraph.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Sonar/NullPointerDereference.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Sonar/PublicMethodArgumentsShouldBeCheckedForNull.cs

Fix Symbolic Execution FPs when `ValidatedNotNullAttribute` is used in extension method

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Sonar/ConditionEvaluatesToConstant.cs

S2589: Add reproducer for #5221

---

analyzers/src/SonarAnalyzer.CSharp/Rules/NonDerivedPrivateClassesShouldBeSealed.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/NonDerivedPrivateClassesShouldBeSealedTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/NonDerivedPrivateClassesShouldBeSealed.cs

Fix S3260 FP: Class inherited  by generic classes

---

analyzers/src/SonarAnalyzer.CSharp/Rules/MethodShouldBeNamedAccordingToSynchronicity.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/MethodShouldBeNamedAccordingToSynchronicity.cs

Fix S4261 FP: When using generic constraints

---

analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Sonar/SonarExplodedGraph.cs

follow-up of #5218 - see https://github.com/SonarSource/sonar-dotnet/pull/5218#discussion_r777904674

SE: Be defensive w/ extension method check

---

analyzers/src/SonarAnalyzer.CSharp/Rules/RedundancyInConstructorDestructorDeclarationCodeFixProvider.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundancyInConstructorDestructorDeclaration.BaseCall.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundancyInConstructorDestructorDeclaration.Constructor.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundancyInConstructorDestructorDeclaration.Destructor.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundancyInConstructorDestructorDeclaration.cs

Rule S3253: code fix provider trivia fix

---

analyzers/its/expected/Net6/Net6--net6.0-S3906.json
analyzers/src/SonarAnalyzer.CSharp/Rules/DeclareEventHandlersCorrectly.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DeclareEventHandlersCorrectly.cs

S3906 FP fix - do not raise when override or interface implementation

---

analyzers/src/SonarAnalyzer.CSharp/Rules/BooleanLiteralUnnecessary.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/BooleanLiteralUnnecessaryCodeFixProvider.cs
analyzers/src/SonarAnalyzer.Common/Rules/BooleanLiteralUnnecessaryBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/BooleanLiteralUnnecessary.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/BooleanLiteralUnnecessaryTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/BooleanLiteralUnnecessary.CSharp9.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/BooleanLiteralUnnecessary.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/BooleanLiteralUnnecessary.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/BooleanLiteralUnnecessary.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/BooleanLiteralUnnecessary.vb

Fixes #5219
Also solves the second case from #4465

S1125 FP with nullable booleans - Fix

---

analyzers/src/SonarAnalyzer.CSharp/Rules/CheckArgumentException.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CheckArgumentException.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CheckArgumentException.cs

S3928 FP fix: Handle named parameters

---

analyzers/src/SonarAnalyzer.CSharp/Rules/EquatableClassShouldBeSealed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/EquatableClassShouldBeSealed.cs

Fix S4035 FP

---

analyzers/src/SonarAnalyzer.CSharp/Rules/BooleanLiteralUnnecessary.cs
analyzers/src/SonarAnalyzer.Common/Rules/BooleanLiteralUnnecessaryBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/BooleanLiteralUnnecessary.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/BooleanLiteralUnnecessary.CSharp8.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/BooleanLiteralUnnecessary.CSharp8.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/BooleanLiteralUnnecessary.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/BooleanLiteralUnnecessary.cs

Fix S1125 FP: ternary operator and throw expressions

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ParameterNameMatchesOriginal.cs

Remove reproducer for S927 FP on discard - as we don't want to handle it

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundantConditionalAroundAssignment.CSharp9.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundantConditionalAroundAssignment.CSharp9.cs

Add repro for #5246

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/NewGuidShouldNotBeUsed.CSharp9.cs

Add repro for #5245

---

analyzers/tests/SonarAnalyzer.UnitTest/Rules/DeclareTypesInNamespacesTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/DoNotHideBaseClassMethodsTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/EmptyNestedBlockTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/FileLinesTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/FileShouldEndWithEmptyNewLineTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/IssueSuppressionTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/MarkAssemblyWithAssemblyVersionAttributeTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/MarkAssemblyWithNeutralResourcesLanguageAttributeTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/MethodsShouldUseBaseTypesTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/ReferenceEqualityCheckWhenEqualsExistsTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/ShiftDynamicNotIntegerTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/SingleStatementPerLineTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/UnnecessaryUsingsTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Tests/DummyAnalyzer.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Tests/VerifierBuilderTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Tests/VerifierTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Verifier.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/VerifierBuilder.cs

Add AutogenerateConcurrentFiles to VerifierBuilder

---

analyzers/tests/SonarAnalyzer.UnitTest/CBDE/CbdeHandlerTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Common/SecurityHotspotTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/CallerInformationParametersShouldBeLastTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/MarkWindowsFormsMainWithStaThreadTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/NameOfShouldBeUsedTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/NullPointerDereferenceTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/OldVerifier.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/ProjectBuilder.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Tests/VerifierTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Verifier.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/VerifierBuilder.cs

Add VerifyNoIssueReported to VerifierBuilder

---

analyzers/tests/SonarAnalyzer.UnitTest/Common/SecurityHotspotTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/CheckFileLicenseTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/MethodsShouldNotHaveTooManyLinesTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/MethodsShouldUseBaseTypesTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/SymbolicExecutionRunnerTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/CopyPasteTokenAnalyzerTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/MetricsAnalyzerTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/SymbolReferenceAnalyzerTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/TokenTypeAnalyzerTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/CodeFixVerifier.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/OldVerifier.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/ParseOptionsHelper.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/ProjectBuilder.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SolutionBuilder.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Verifier.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestSuiteInitialization.cs

Per commit review should explain individual steps (boring refactoring vs. structural changes)

Cleanup SolutionBuilder and ProjectBuilder

---

analyzers/src/SonarAnalyzer.CSharp/Rules/EqualityOnModulus.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/EqualityOnModulus.cs

Fix S2197 FP: False Positive when collection size methods or properties are used

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Sonar/NullPointerDereference.cs

S2259: Add FP repro for #5285

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SymbolicExecution/ValidatorTestCheck.cs

Limit Symbolic Execution MaxSteps

---

analyzers/packaging/tools-cs/install.ps1
analyzers/packaging/tools-cs/uninstall.ps1
analyzers/packaging/tools-vbnet/install.ps1
analyzers/packaging/tools-vbnet/uninstall.ps1

Fixes #5334
This is a hotfix, we should discuss the purpose and strategy around this piece.
I've tested the change manually by updating cached plugin.

Add VS2022 to NuGet install scripts

---

analyzers/src/SonarAnalyzer.Common/Rules/PropertiesAccessCorrectFieldBase.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/PropertiesAccessCorrectFieldTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/PropertiesAccessCorrectField.vb

Add repro for #5336

---

analyzers/tests/SonarAnalyzer.UnitTest/Rules/GenericTypeParameterEmptinessCheckingTest.cs
its/src/test/java/com/sonar/it/csharp/Tests.java
its/src/test/java/com/sonar/it/vbnet/Tests.java

Target latest release in java ITs

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/ExplodedNode.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/ProgramPoint.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ExplodedNodeTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ProgramPointTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.cs

Implement IEquatable for ExplodedNode

---

azure-pipelines.yml

- until we find the coverage problem which happens randomly

Enable verbose mode

---

analyzers/src/SonarAnalyzer.CFG/CfgSerializer/CfgSerializer.RoslynCfgWalker.cs
analyzers/src/SonarAnalyzer.CFG/Extensions/IOperationExtensions.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/ExplodedNode.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/ProgramState.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ExplodedNodeTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ProgramStateTest.cs

Add ExplodedNode.ToString() for debugging SE

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/ProgramState.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SymbolicValue.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ProgramStateTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/SymbolicValueTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Monitor.Conditions.CSharp8.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Monitor.Conditions.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Monitor.Loops.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Monitor.TryCatch.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Monitor.TryEnter.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SymbolicExecution/SETestContext.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SymbolicExecution/ValidatorTestCheck.cs

Support branching in Symbolic Execution

---

analyzers/src/SonarAnalyzer.Common/Extensions/MethodSymbolExtensions.cs
analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Checks/LocksReleasedAllPathsBase.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/Roslyn/LocksReleasedAllPathsTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.ReaderWriterLockSlim.cs

Improve S2222: Track ReaderWriterLockSlim

---

analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Checks/LocksReleasedAllPathsBase.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.ReaderWriterLock.cs

Improve S2222: Track ReaderWriterLock

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/MethodParameterUnused.RoslynCfg.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/MethodParameterUnused.RoslynCfg.cs

S1172: Add FP repro for #5338

---

analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/Roslyn/LocksReleasedAllPathsTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Monitor.Conditions.CSharp8.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Monitor.Conditions.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Monitor.GoTo.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Monitor.Linear.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Monitor.Loops.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Monitor.TryCatch.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Monitor.TryEnter.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Mutex.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.ReaderWriterLock.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.ReaderWriterLockSlim.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.SpinLock.cs

Shrink `LocksReleasedAllPathsTest`.
This is prerequisite for #5311

Refactor LocksReleasedAllPathsTest

---

analyzers/src/SonarAnalyzer.CSharp/Rules/CollectionEmptinessCheckingCodeFix.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/CollectionEmptinessCheckingFixProvider.cs
analyzers/src/SonarAnalyzer.Common/Rules/CollectionEmptinessCheckingBase.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/CollectionEmptinessCheckingTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CollectionEmptinessChecking.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CollectionEmptinessChecking.cs

As specified in #2334 .
Note to @pavel-mikula-sonarsource the `VerifyBuilder` (still) requires the 'TestCases' root directory to be specified, is that intentionally?

S1155: Implement a fix provider for C#

---

analyzers/tests/SonarAnalyzer.UnitTest/Rules/ExpectedExceptionAttributeShouldNotBeUsedTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/LoopsAndLinqTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/MemberInitializerRedundantTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/NonDerivedPrivateClassesShouldBeSealedTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/TypeMemberVisibilityTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/UseTestableTimeProviderTest.cs

Remove TestCategoryAttribute

---

its/pom.xml
its/src/test/java/com/sonar/it/shared/TestUtils.java

Update S4NET to latest (https://github.com/SonarSource/sonar-scanner-msbuild/releases/tag/5.5.3.43281)

Bump S4NET to 5.5.3.43281 in ITs

---

analyzers/src/SonarAnalyzer.CSharp/Extensions/SyntaxNodeExtensions.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/SymbolicExecutionRunner.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Checks/ConstantCheck.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/References.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/LocksReleasedAllPathsBase.cs
analyzers/tests/SonarAnalyzer.UnitTest/Extensions/SyntaxNodeExtensionsTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/Roslyn/LocksReleasedAllPathsTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Constants.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Loops.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SymbolicExecution/EmptyTestCheck.cs

SE: add symbolic engine support for Boolean constraints

---

analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/SymbolicExecutionRunner.cs
analyzers/src/SonarAnalyzer.Common/Rules/SymbolicExecutionRunnerBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/SymbolicExecution/SymbolicExecutionRunner.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/SymbolicExecutionRunnerTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/DiagnosticVerifier.cs

Fixes this comment https://github.com/SonarSource/sonar-dotnet/pull/5393#discussion_r806692819

Remove test logic from SymbolicExecutionRunnerBase

---

docs/coding-style.md

This extracts easy topics from #5295

Update coding style: empty lines and ternary

---

analyzers/rspec/cs/S107_c#.html
analyzers/rspec/cs/S1155_c#.json
analyzers/rspec/cs/S2092_c#.html
analyzers/rspec/cs/S2612_c#.html
analyzers/rspec/cs/S4834_c#.html
analyzers/rspec/vbnet/S107_vb.net.html
analyzers/rspec/vbnet/S2222_vb.net.html
analyzers/rspec/vbnet/S2612_vb.net.html
analyzers/rspec/vbnet/S4834_vb.net.html
analyzers/src/SonarAnalyzer.CSharp/sonarpedia.json
analyzers/src/SonarAnalyzer.Utilities/Rules.Description/S107_cs.html
analyzers/src/SonarAnalyzer.Utilities/Rules.Description/S107_vb.html
analyzers/src/SonarAnalyzer.Utilities/Rules.Description/S2092.html
analyzers/src/SonarAnalyzer.Utilities/Rules.Description/S2222_vb.html
analyzers/src/SonarAnalyzer.Utilities/Rules.Description/S2612_cs.html
analyzers/src/SonarAnalyzer.Utilities/Rules.Description/S2612_vb.html
analyzers/src/SonarAnalyzer.Utilities/Rules.Description/S4834_cs.html
analyzers/src/SonarAnalyzer.Utilities/Rules.Description/S4834_vb.html
analyzers/src/SonarAnalyzer.VisualBasic/sonarpedia.json

Update RSPEC before 8.36 release

---

analyzers/tests/SonarAnalyzer.UnitTest/Rules/UnusedPrivateMemberTest.Constructors.cs

Add repro S1144 FP

---

analyzers/src/SonarAnalyzer.CSharp/sonarpedia.json
analyzers/src/SonarAnalyzer.VisualBasic/sonarpedia.json

Update RSPEC before 8.36.1 release

---

analyzers/src/SonarAnalyzer.CSharp/Rules/AsyncVoidMethod.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/AsyncVoidMethod.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/AsyncVoidMethod.cs

S3168: Add FP repro for #5432

---

analyzers/src/SonarAnalyzer.CSharp/Rules/InvocationResolvesToOverrideWithParams.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/InvocationResolvesToOverrideWithParams.cs

Reproduces S3220 FP

---

sonar-csharp-plugin/src/main/java/org/sonar/plugins/csharp/CSharpSonarRulesDefinition.java
sonar-csharp-plugin/src/test/java/org/sonar/plugins/csharp/CSharpSonarRulesDefinitionTest.java
sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/AbstractRulesDefinition.java
sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/AbstractRulesDefinitionTest.java
sonar-dotnet-shared-library/src/test/resources/AbstractRulesDefinitionTest/S1111.json
sonar-dotnet-shared-library/src/test/resources/AbstractRulesDefinitionTest/rules.xml
sonar-vbnet-plugin/src/main/java/org/sonar/plugins/vbnet/VbNetSonarRulesDefinition.java
sonar-vbnet-plugin/src/test/java/org/sonar/plugins/vbnet/VbNetSonarRulesDefinitionTest.java

Provide OWASP Top 10 2021 security standards for rules metadata

---

analyzers/src/SonarAnalyzer.CSharp/Rules/TestClassShouldHaveTestMethod.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/TestClassShouldHaveTestMethod.MsTest.cs

S2187: Add test cases with other attributes

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Loops.cs

Support branching on operation constraints in SE

---

analyzers/rspec/cs/S4226_c#.html
analyzers/src/SonarAnalyzer.CSharp/Rules/ExtensionMethodShouldBeInSeparateNamespace.cs
analyzers/src/SonarAnalyzer.Utilities/Rules.Description/S4226.html
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ExtensionMethodShouldBeInSeparateNamespace.cs

Rule S4226: Add exception for types decorated with GeneratedCode attribute

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/ProgramState.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ProgramStateTest.OperationValue.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ProgramStateTest.SymbolValue.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ProgramStateTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.cs

Don't persist null state in ProgramState

---

analyzers/rspec/cs/S3459_c#.html
analyzers/rspec/cs/S4226_c#.html
analyzers/src/SonarAnalyzer.CFG/CfgSerializer/CfgSerializer.RoslynCfgWalker.cs
analyzers/src/SonarAnalyzer.CFG/ShimLayer/BinaryOperatorKind.cs
analyzers/src/SonarAnalyzer.CFG/ShimLayer/LightupHelpers.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/ExtensionMethodShouldBeInSeparateNamespace.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/NotAssignedPrivateMember.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Constraints/BoolConstraint.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Checks/ConstantCheck.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Binary.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/ProgramState.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
analyzers/src/SonarAnalyzer.ShimLayer.CodeGeneration/OperationLightupGenerator.cs
analyzers/src/SonarAnalyzer.Utilities/Rules.Description/S3459.html
analyzers/src/SonarAnalyzer.Utilities/Rules.Description/S4226.html
analyzers/tests/SonarAnalyzer.UnitTest/CFG/Roslyn/RoslynCfgSerializerTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ProgramStateTest.OperationValue.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ProgramStateTest.SymbolValue.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ProgramStateTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/SymbolicConstraintTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ExtensionMethodShouldBeInSeparateNamespace.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/NotAssignedPrivateMember.cs
azure-pipelines.yml

Support implicit VB.NET declaration value in SE

---

analyzers/src/SonarAnalyzer.CFG/CfgSerializer/CfgSerializer.RoslynCfgWalker.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Checks/ConstantCheck.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/FlowCapture.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Pattern.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/ProgramState.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
analyzers/tests/SonarAnalyzer.UnitTest/CFG/Roslyn/RoslynCfgSerializerTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ProgramStateTest.CaptureOperation.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ProgramStateTest.OperationValue.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ProgramStateTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.PatternMatching.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.cs

Support tracking of flow capturing operations in SE

---

analyzers/src/SonarAnalyzer.CFG/LiveVariableAnalysis/RoslynLiveVariableAnalysis.cs
analyzers/src/SonarAnalyzer.CFG/ShimLayer/SyntaxKindEx.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/DeadStores.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/MethodParameterUnused.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/SymbolicExecutionRunner.cs
analyzers/tests/SonarAnalyzer.UnitTest/LiveVariableAnalysis/RoslynLiveVariableAnalysisTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/SymbolicExecutionRunnerTest.cs

Remove originalDeclaration from RoslynLVA

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/References.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/ProgramState.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/LocksReleasedAllPathsBase.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SymbolicContext.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ProgramStateTest.OperationValue.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ProgramStateTest.SymbolValue.cs

Add SetSymbolConstraint and SetOperationConstraint to ProgramState

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SymbolicExecution/ProcessTestChecks.cs

Refactor branching in SE and ProcessTestChecks

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SymbolicCheckList.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SymbolicContext.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/SymbolicCheckListTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/SymbolicContextTest.cs

Extract SymbolicCheckList

---

analyzers/src/SonarAnalyzer.CSharp/Rules/MethodShouldNotOnlyReturnConstant.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/MethodShouldNotOnlyReturnConstantTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/MethodShouldNotOnlyReturnConstant.CSharp8.cs

Rule S3400: add repro

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Extensions/IOperationExtensions.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SymbolicCheck.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SymbolicCheckList.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Loops.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.TryCatchFinally.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Mutex.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Mutex.vb
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SymbolicExecution/ProcessTestChecks.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SymbolicExecution/SETestContext.cs

Learn constraints on branching in SE

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/LocksReleasedAllPathsBase.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.ReaderWriterLock.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.ReaderWriterLock.vb
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.ReaderWriterLockSlim.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.ReaderWriterLockSlim.vb

Improve S2222: add support for IsReadLockHeld and IsWriteLockHeld checks

---

analyzers/src/SonarAnalyzer.CSharp/Rules/UnusedReturnValue.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnusedReturnValue.CSharp10.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnusedReturnValue.cs

Fix: S3241-False positive if the method is async

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/LocksReleasedAllPathsBase.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Monitor.Conditions.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Monitor.Conditions.vb
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Monitor.TryEnter.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Monitor.TryEnter.vb
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Mutex.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.SpinLock.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.SpinLock.vb

S2222: add support for ref parameter lock status tracking

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/LocksReleasedAllPathsBase.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Monitor.Conditions.cs

Fix S2222 FP and FN: Support Monitor.IsEntered

---

analyzers/src/SonarAnalyzer.CSharp/Rules/MethodsShouldNotHaveIdenticalImplementations.cs
analyzers/src/SonarAnalyzer.Common/Rules/MethodsShouldNotHaveIdenticalImplementationsBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/MethodsShouldNotHaveIdenticalImplementations.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/MethodsShouldNotHaveIdenticalImplementationsTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/MethodsShouldNotHaveIdenticalImplementations.CSharp10.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/MethodsShouldNotHaveIdenticalImplementations.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/MethodsShouldNotHaveIdenticalImplementations.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/MethodsShouldNotHaveIdenticalImplementations.vb

Fix S4144 FN: Should raise for methods in interfaces and structs

---

analyzers/its/expected/akka.net/Akka.Cluster--netstandard2.0-S3963.json
analyzers/src/SonarAnalyzer.CSharp/Rules/InitializeStaticFieldsInline.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/InitializeStaticFieldsInlineTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/InitializeStaticFieldsInline.cs

Fix S3963 FP: Should not raise for conditional logic

---

analyzers/src/SonarAnalyzer.CSharp/Rules/MethodShouldNotOnlyReturnConstant.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/MethodShouldNotOnlyReturnConstant.CSharp8.cs

Rule S3400: Fix FP when using default interface implementation

---

analyzers/src/SonarAnalyzer.CSharp/Rules/StaticFieldInGenericClass.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/StaticFieldInGenericClassTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/StaticFieldInGenericClass.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/StaticFieldInGenericClass.cs

Fix S2743 FP: Don't report on static fields which use the type parameter

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Mutex.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.SpinLock.cs

Reproduces #5522 and issue from Peach: https://peach.sonarsource.com/issues?open=AX8cBcOC0TDn9J0Gyumu&resolved=false&rules=csharpsquid%3AS2222

S2222: Add FP repro for #5522

---

analyzers/tests/SonarAnalyzer.UnitTest/Rules/AsyncVoidMethodTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/AsyncVoidMethod.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/AsyncVoidMethod.cs

S3168: Document behavior for virtual members

---

.gitattributes

Fixes #2882
All our PS files already have LF EOLs

.gitattributes: Set *.ps1 as LF

---

analyzers/tests/SonarAnalyzer.UnitTest/LiveVariableAnalysis/RoslynLiveVariableAnalysisTest.LocalFunction.cs
analyzers/tests/SonarAnalyzer.UnitTest/LiveVariableAnalysis/RoslynLiveVariableAnalysisTest.TryCatchFinally.cs
analyzers/tests/SonarAnalyzer.UnitTest/LiveVariableAnalysis/RoslynLiveVariableAnalysisTest.cs

1st commit shows the refactoring
2nd commit is mechanical removal of the `new` keyword

Refactor RoslynLiveVariableAnalysisTest

---

analyzers/src/SonarAnalyzer.VisualBasic/Rules/ArrayCreationLongSyntax.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/ArrayCreationLongSyntaxTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ArrayCreationLongSyntax.Fixed.vb
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ArrayCreationLongSyntax.vb

One of the `ReportIssue` lines was not covered by UTs

Refactor ArrayCreationLongSyntax

---

analyzers/src/SonarAnalyzer.CFG/Roslyn/ControlFlowGraphCache.cs
analyzers/tests/SonarAnalyzer.UnitTest/Extensions/SyntaxNodeExtensionsTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/MethodParameterUnusedTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Verifier.cs

Fix S1172 FP: Raises randomly under VS context

---

analyzers/src/SonarAnalyzer.CSharp/Constants/SyntaxConstants.cs
analyzers/src/SonarAnalyzer.CSharp/Helpers/CSharpDiagnosticAnalyzerContextHelper.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/ClassWithOnlyStaticMember.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/ImplementISerializableCorrectly.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/UnusedPrivateMember.cs
analyzers/src/SonarAnalyzer.Common/Common/FixAllProviders/BidirectionalDictionary.cs
analyzers/tests/SonarAnalyzer.UnitTest/Common/BidirectionalDictionaryTests.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/UnusedPrivateMemberTest.Properties.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnusedPrivateMember.CSharp10.cs

Fixes #4351
The testing of the performance included 4 runs each on 3 different projects. The sum of the times are the following:
akka 33.998 -> 24.951
efcore 32.698 -> 29.39
noda 42.223 -> 14.218

Fix S1144 / S4487 perf regression: UnusedPrivateMember

---

analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/ClearTextProtocolsAreSensitive.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Hotspots/ClearTextProtocolsAreSensitiveTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/ClearTextProtocolsAreSensitive.cs

Fix S5332 FP: Add "schemas.microsoft.com" to commonly used known schema domain

---

analyzers/src/SonarAnalyzer.CSharp/Rules/MemberShadowsOuterStaticMember.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/MethodsShouldNotHaveIdenticalImplementations.cs
analyzers/src/SonarAnalyzer.Common/Rules/MethodsShouldNotHaveIdenticalImplementationsBase.cs

Record struct support was already added with #5512 
Some small improvements I could find are included.
I didn't milestone it and labeled the PR to distinguish it from the others.

S4144: Optimize duplication logic

---

NOTICE.txt
analyzers/src/SonarAnalyzer.Utilities/RuleDetailBuilder.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/RedundancyInConstructorDestructorDeclarationTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/RedundantArgumentTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/RedundantConditionalAroundAssignmentTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/RedundantDeclarationTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/RedundantInheritanceListTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/RedundantModifierTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/RedundantNullCheckTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/RedundantParenthesesObjectCreationTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/RedundantPropertyNamesInAnonymousClassTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/RedundantToCharArrayCallTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/RedundantToStringCallTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/SillyBitwiseOperationTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/StringConcatenationWithPlusTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/SuppressFinalizeUselessTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/SwitchCaseFallsThroughToDefaultTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/SwitchDefaultClauseEmptyTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/ThreadStaticNonStaticFieldTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Tests/DummyCodeFix.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestSuiteInitialization.cs
scripts/rspec/rspec-templates/CSharpRuleTemplate.cs
scripts/rspec/rspec-templates/CSharpTestTemplate.cs
scripts/rspec/rspec-templates/CommonBaseClassTemplate.cs
scripts/rspec/rspec-templates/VbNetRuleTemplate.cs
scripts/rspec/rspec-templates/VbNetTestTemplate.cs

Follow-up from https://github.com/SonarSource/sonar-dotnet/pull/5629#discussion_r865071714

Fix license headers 2022

---

analyzers/src/SonarAnalyzer.CSharp/Rules/BeginInvokePairedWithEndInvoke.cs
analyzers/src/SonarAnalyzer.Common/Rules/BeginInvokePairedWithEndInvokeBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/BeginInvokePairedWithEndInvoke.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/BeginInvokePairedWithEndInvoke.CSharp9.Part1.cs

~see https://github.com/SonarSource/sonar-dotnet/pull/5569#issuecomment-1102688699 why this is still a draft.~

S4583: Cleanup

---

analyzers/rspec/cs/S4581_c#.html
analyzers/src/SonarAnalyzer.CSharp/sonarpedia.json
analyzers/src/SonarAnalyzer.VisualBasic/sonarpedia.json

Update RSPEC before release 8.39

---

analyzers/tests/SonarAnalyzer.UnitTest/Common/MetricsTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/GenericReadonlyFieldPropertyAssignmentTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/ConditionEvaluatesToConstantTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/EmptyNullableValueAccessTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/InvalidCastToInterfaceTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/NullPointerDereferenceTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/ObjectsShouldNotBeDisposedMoreThanOnceTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/PublicMethodArgumentsShouldBeCheckedForNullTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/RestrictDeserializedTypesTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SolutionBuilder.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Tests/VerifierTest.cs

UTs: Remove unused usings

---

analyzers/tests/SonarAnalyzer.UnitTest/MetadataReferences/MetadataReferenceFacade.cs
analyzers/tests/SonarAnalyzer.UnitTest/MetadataReferences/NuGetMetadataReference.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/ShouldImplementExportedInterfacesTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ShouldImplementExportedInterfaces.System.Composition.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ShouldImplementExportedInterfaces.cs

Add repro for #5641

---

analyzers/src/SonarAnalyzer.CSharp/Rules/MethodsShouldUseBaseTypes.cs
analyzers/src/SonarAnalyzer.Common/Helpers/AspNetMvcHelper.cs
analyzers/tests/SonarAnalyzer.UnitTest/Helpers/AspNetMvcHelperTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/MethodsShouldUseBaseTypesTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/MethodsShouldUseBaseTypes.AspControllers.cs

S3242 FP: Don't raise on public methods in controllers

---

analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
analyzers/src/SonarAnalyzer.Common/Rules/ShouldImplementExportedInterfacesBase.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ShouldImplementExportedInterfaces.System.Composition.cs

Add support for System.Composition.ExportAttribute

---

analyzers/src/SonarAnalyzer.CSharp/Metrics/CSharpCognitiveComplexityMetric.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/CognitiveComplexityTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CognitiveComplexity.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CognitiveComplexity.LocalFunctions.cs

S3776: Exclude local functions from complexity computation

---

analyzers/rspec/cs/S6421_c#.html
analyzers/rspec/cs/S6421_c#.json
analyzers/src/SonarAnalyzer.CSharp/Helpers/CSharpSyntaxHelper.cs
analyzers/src/SonarAnalyzer.CSharp/RspecStrings.resx
analyzers/src/SonarAnalyzer.CSharp/Rules/CloudNative/AzureFunctionsCatchExceptions.cs
analyzers/src/SonarAnalyzer.VisualBasic/Helpers/VisualBasicSyntaxHelper.cs
analyzers/tests/SonarAnalyzer.UnitTest/Helpers/SyntaxHelperTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/PackagingTests/CsRuleTypeMapping.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/CloudNative/AzureFunctionsCatchExceptionsTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CloudNative/AzureFunctionsCatchExceptions.cs

Fixes #5597
~~This is draft for now. Rebase will be needed and some dummy stuff removed~~

Rule S6421: Azure Functions should use Structured Error Handling

---

analyzers/its/expected/Automapper/AutoMapper--net461-S1541.json
analyzers/its/expected/Automapper/AutoMapper--netstandard2.0-S1541.json
analyzers/src/SonarAnalyzer.CSharp/Metrics/CSharpCyclomaticComplexityMetric.cs
analyzers/src/SonarAnalyzer.Common/Rules/FunctionComplexityBase.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/FunctionComplexityTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/FunctionComplexity.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/FunctionComplexity.LocalFunctions.cs

S1541: Exclude static local functions from complexity computation.

---

analyzers/src/SonarAnalyzer.CSharp/Metrics/CSharpCognitiveComplexityMetric.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/CognitiveComplexity.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CognitiveComplexity.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CognitiveComplexity.LocalFunctions.cs

S3776: Static local functions have their own complexity score.

---

analyzers/src/SonarAnalyzer.Common/Rules/DeclareTypesInNamespacesBase.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DeclareTypesInNamespaces.AfterCSharp9.cs

Add repro for #5660

---

analyzers/tests/SonarAnalyzer.UnitTest/Rules/StringConcatenationInLoopTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/StringConcatenationInLoop.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/StringConcatenationInLoop.vb

Add repro for #5521

---

analyzers/tests/SonarAnalyzer.UnitTest/MetadataReferences/NuGetMetadataFactory.cs
analyzers/tests/SonarAnalyzer.UnitTest/MetadataReferences/NuGetMetadataReference.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Hotspots/ExecutingSqlQueriesTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/ExecutingSqlQueries_EntityFrameworkCore2.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/ExecutingSqlQueries_EntityFrameworkCoreLatest.cs

Add repro for #5636

---

analyzers/src/SonarAnalyzer.CSharp/Rules/ConditionalStructureSameImplementation.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/ConditionalStructureSameImplementationTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ConditionalStructureSameImplementation_Switch.cs

Add repro for #5587

---

analyzers/src/SonarAnalyzer.CSharp/Rules/MemberShouldBeStatic.cs
analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/MemberShouldBeStaticTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/MemberShouldBeStatic.WinForms.cs

Given the required scenario, I opted for a separate test case.
Fixes #5536

Fix FP S2325: Event Handlers should not be static

---

analyzers/src/SonarAnalyzer.CSharp/Rules/TestClassShouldHaveTestMethod.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/TestClassShouldHaveTestMethod.MsTest.cs

Rule S2187: Fix FP, check all upper class hierarchy for test attributes

---

analyzers/src/SonarAnalyzer.CSharp/Rules/MemberShouldBeStatic.cs

- do the syntax level check first

Reduce the number of conditional operators

---

analyzers/rspec/cs/S6354_c#.json
analyzers/rspec/cs/S6419_c#.json
analyzers/rspec/cs/S6420_c#.json
analyzers/rspec/cs/S6421_c#.json
analyzers/rspec/cs/S6423_c#.json
analyzers/rspec/cs/S6424_c#.json
analyzers/rspec/vbnet/S6354_vb.net.json
analyzers/src/SonarAnalyzer.CSharp/RspecStrings.resx
analyzers/src/SonarAnalyzer.CSharp/sonarpedia.json
analyzers/src/SonarAnalyzer.VisualBasic/RspecStrings.resx
analyzers/src/SonarAnalyzer.VisualBasic/sonarpedia.json
analyzers/tests/SonarAnalyzer.UnitTest/Common/RuleTest.cs

Normalize rule names

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/TestClassShouldHaveTestMethod.NUnit3.cs

S2187: Add FP repro for #5732

---

analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.TryCatchFinally.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SymbolicExecution/ValidatorTestCheck.cs

Related to #5710
Prerequisite for #5745

Add assignment tagging to ValidatorTestCheck

---

analyzers/src/SonarAnalyzer.CSharp/Rules/BinaryOperationWithIdenticalExpressions.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/CallToAsyncMethodShouldNotBeBlocking.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/CbdeHandlerRule.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/ClassAndMethodName.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/ConditionalSimplification.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/DoNotShiftByZeroOrIntSize.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/GetHashCodeMutable.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/GetHashCodeMutableCodeFix.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/ClearTextProtocolsAreSensitive.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/MemberInitializerRedundant.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/MethodsShouldNotHaveTooManyLines.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/MutableFieldsShouldNotBe.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/RedundantDeclaration.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/RedundantNullCheck.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/StringFormatValidator.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/SwitchCasesMinimumThree.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/ConditionEvaluatesToConstant.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/InvalidCastToInterfaceSymbolicExecution.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/UnusedPrivateMember.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/UseUriInsteadOfString.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/BinaryOperationWithIdenticalExpressions.cs

#5644 follow up
Irregular cases. I tried not to clean as we code as much as possible (and failed slightly few times)

Remove RspecResources references - batch 3

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Sonar/InvalidCastToInterface.CSharp10.cs

The test was missing a concrete implementation. I corrected it and the diagnostic turned up.

S1944: Add support for deconstruction

---

analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.ExceptionCandidate.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SnippetCompiler.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SymbolicExecution/SETestContext.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/TestHelper.cs

Document EndOperation handling

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.ExceptionCandidate.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.TryCatchFinally.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Monitor.TryCatch.cs

Related to #5710
Review per commit will illustrate the change.
The FP in rule will be in another PR

Support try/finally nested in try/catch in SE

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/ExceptionCandidate.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Extensions/IInvocationOperationExtensions.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/LocksReleasedAllPathsBase.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.ExceptionCandidate.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Monitor.TryCatch.cs

Lock releasing methods should not throw in SE

---

analyzers/rspec/cs/S5542_c#.html
analyzers/rspec/cs/S6354_c#.json
analyzers/rspec/cs/S6419_c#.json
analyzers/rspec/cs/S6420_c#.json
analyzers/rspec/cs/S6421_c#.json
analyzers/rspec/cs/S6423_c#.json
analyzers/rspec/cs/S6424_c#.json
analyzers/rspec/vbnet/S5542_vb.net.html
analyzers/rspec/vbnet/S6354_vb.net.json
analyzers/src/SonarAnalyzer.CSharp/RspecStrings.resx
analyzers/src/SonarAnalyzer.CSharp/sonarpedia.json
analyzers/src/SonarAnalyzer.VisualBasic/RspecStrings.resx
analyzers/src/SonarAnalyzer.VisualBasic/sonarpedia.json

Update RSPEC for 8.41

---

analyzers/src/SonarAnalyzer.CSharp/Rules/StaticFieldWrittenFrom.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/StaticFieldWrittenFromInstanceConstructor.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/StaticFieldWrittenFromInstanceMember.cs

Cleanup for merged PR #5793

---

analyzers/src/SonarAnalyzer.CSharp/Rules/SetLocaleForDataTypes.cs
analyzers/src/SonarAnalyzer.Common/Common/NodeAndSymbol.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SetLocaleForDataTypes.CSharp10.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SetLocaleForDataTypes.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SetLocaleForDataTypes.cs

Please do not review `MapAssignmentArguments` It will be replaced by the method from work on rule S4055.

S4057: Add support for tuples and assignment and declaration in the same deconstruction

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/VariableShadowsField.cs

Follow up for #5767
Peach showed some new true positives. This PR is to avoid regressions in this space.

S1117: Add test cases for True Positive for declarations in out arguments.

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/VariableShadowsField.CSharp10.cs

Clean-up PR based on https://github.com/SonarSource/sonar-dotnet/pull/5767#discussion_r920247348

S1117: Improve test by adding marker

---

analyzers/src/SonarAnalyzer.CSharp/Rules/ForLoopCounterChanged.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ForLoopCounterChanged.CSharp10.cs

This PR fixes some new FNs in for loop initializers. One existing FN was not addressed.

S127: Fix some FNs for tuple deconstruction in for loop initializer

---

sonar-csharp-plugin/src/main/resources/documentation.md
sonar-vbnet-plugin/src/main/resources/documentation.md

Replace documentation broken link to to coverage page

---

analyzers/src/SonarAnalyzer.Common/DiagnosticAnalyzer/DiagnosticDescriptorBuilder.cs
analyzers/tests/SonarAnalyzer.UnitTest/Helpers/DiagnosticDescriptorBuilderTest.cs

Remove obsolete methods from DiagnosticDescriptorBuilder

---

scripts/rspec/rspec.ps1

Cleanup after #5590 
Logic around `UpdateTestEntry` could be simplified a lot

rspec.ps1 cleanup around UpdateTestEntry

---

scripts/rspec/rspec-templates/Rule.VB.cs
scripts/rspec/rspec.ps1

Cleanup after #5590
Mechanical refactorings to make code more readable

rspec.ps1 cleanup around class generation

---

analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/NullPointerDereferenceTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Sonar/NullPointerDereference.cs

Part two of #5862
This PR is independent of part one #5864. #5864 and this PR can be reviewed and merged in any order.

S2259 Move UTs to VerifierBuilder

---

pom.xml

- the previous one was deleted

Link released version of sonar-plugin-api-impl

---

analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/ConditionEvaluatesToConstant.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/InvalidCastToInterfaceSymbolicExecution.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/NullPointerDereference.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/ObjectsShouldNotBeDisposedMoreThanOnce.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/PublicMethodArgumentsShouldBeCheckedForNull.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Constraints/ObjectConstraint.cs

Move ObjectConstraint to Common

---

analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Sonar/SonarExplodedGraph.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/SymbolicExecutionRunnerTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Sonar/ConditionEvaluatesToConstant.CSharp8.cs

Fixes #5829 
Fixes https://community.sonarsource.com/t/66958

SE: Fix ArgumentNullException for nested designations

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Creation.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SymbolicExecution/ValidatorTestCheck.cs

Set NotNull constraints for object creations in SE

---

analyzers/src/SonarAnalyzer.Common/Rules/ShouldImplementExportedInterfacesBase.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ShouldImplementExportedInterfaces.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ShouldImplementExportedInterfaces.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ShouldImplementExportedInterfaces.vb

Fix S4159 FP: add support for generic type exports

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/References.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SymbolicValue.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs

Set NotNull constraint for `this` in SE

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Invocation.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs

Set NotNull constraints for invocations in SE

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/References.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SymbolicExecution/SETestContext.cs

Contributes to https://github.com/SonarSource/sonar-dotnet/issues/5860

Set NotNull constraints for member references in SE

---

analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs

Failing master: Fix Invocation_SetsNotNullOnInstance_CS for extension methods

---

analyzers/src/SonarAnalyzer.CSharp/Extensions/InvocationExpressionSyntaxExtensions.cs
analyzers/src/SonarAnalyzer.CSharp/Helpers/CSharpEquivalenceChecker.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/ConditionalStructureSameImplementation.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ConditionalStructureSameImplementation_If.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ConditionalStructureSameImplementation_Switch.cs

Fix S1871 FP: When invocations are overloads.

---

analyzers/its/expected/akka.net/Akka.DistributedData--netstandard2.0-S3240.json
analyzers/src/SonarAnalyzer.CSharp/Rules/ConditionalSimplification.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/ConditionalSimplificationTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ConditionalSimplification.BeforeCSharp8.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ConditionalSimplification.BeforeCSharp8.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ConditionalSimplification.FromCSharp10.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ConditionalSimplification.FromCSharp10.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ConditionalSimplification.FromCSharp8.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ConditionalSimplification.FromCSharp8.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ConditionalSimplification.FromCSharp9.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ConditionalSimplification.FromCSharp9.cs

S3240: ConditionalSimplification FPs - fix

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Literal.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Constants.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SymbolicExecution/SETestContext.cs

Set Null constraint for `default` in SE

---

analyzers/src/SonarAnalyzer.Common/DiagnosticAnalyzer/DiagnosticDescriptorFactory.cs
analyzers/tests/SonarAnalyzer.UnitTest/Common/RuleTest.cs

All rules should be configurable

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/InfiniteRecursion.RoslynCfg.cs

S2190: Add FP repro for #5261

---

analyzers/src/SonarAnalyzer.CSharp/Rules/DeclareTypesInNamespaces.cs
analyzers/src/SonarAnalyzer.Common/Extensions/SyntaxNodeAnalysisContextExtensions.cs
analyzers/src/SonarAnalyzer.Common/Rules/DeclareTypesInNamespacesBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/DeclareTypesInNamespaces.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DeclareTypesInNamespaces.AfterCSharp9.cs

Fix S3903 FP:  When declaring a partial class Program in top-level statements.

---

analyzers/src/SonarAnalyzer.CFG/Extensions/ControlFlowRegionExtensions.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.TryCatchFinally.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Monitor.TryCatch.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SymbolicExecution/SETestContext.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/TestHelper.cs

Fix AD0001 on S2222: IndexOutOfRange for lambda in try/finally

---

analyzers/tests/SonarAnalyzer.UnitTest/Rules/DisposableNotDisposedTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DisposableNotDisposed.CSharp10.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DisposableNotDisposed.CSharp9.cs

Add reproducer for FP S2930: DisposeAsync is not recognized as Dispose.

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Assignment.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IsNull.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.IsNull.cs

Calculate BoolConstraint from IsNull operation in SE

---

analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/NullPointerDereference.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Extensions/IOperationExtensions.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/NullPointerDereferenceBase.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SymbolicContext.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.CSharp6.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.CSharp7.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.CSharp8.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.cs

~Sonar and Roslyn versions don't run completely independently at the moment. Should be solved with #5911.~
Update #5911 is merged and solved the problem.

S2259: Support member access

---

analyzers/src/SonarAnalyzer.CSharp/Rules/CheckArgumentException.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/CheckArgumentExceptionTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CheckArgumentException.CSharp9.cs

Fix S3928 FP: Does not raise issue when using record parameters 

---

analyzers/src/SonarAnalyzer.CSharp/Rules/ArgumentSpecifiedForCallerInfoParameter.cs
analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/ArgumentSpecifiedForCallerInfoParameterTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/MethodOverloadOptionalParameterTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/OptionalParameterNotPassedToBaseCallTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/OptionalParameterTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/OptionalParameterWithDefaultValueTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ArgumentSpecifiedForCallerInfoParameter.CSharp10.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/MethodOverloadOptionalParameter.CSharp10.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/OptionalParameter.CSharp10.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/OptionalParameter.cs

Fix S2360 FP: Extend CallerInfoAttributes with CallerArgumentExpressionAttribute

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Extensions/IOperationExtensions.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/NullPointerDereferenceBase.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.cs

S2259: Support array element access

---

analyzers/src/SonarAnalyzer.CSharp/Rules/SqlKeywordsDelimitedBySpace.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SqlKeywordsDelimitedBySpace.CSharp10.cs

FIX FN S2857: No issue is raised if the malformed SQL query is formatted with the help of constant interpolated strings

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Extensions/IOperationExtensions.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Pattern.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.PatternMatching.cs

Set NotNull constraint for recursive pattern in SE

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IsNull.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Pattern.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.PatternMatching.cs

Set NotNull constraint for declaration pattern in SE

---

analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/DoNotHardcodeCredentials.cs
analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/DoNotHardcodeCredentialsBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/Hotspots/DoNotHardcodeCredentials.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Hotspots/DoNotHardcodeCredentialsTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/DoNotHardcodeCredentials_DefaultValues.CSharp10.cs

S2068 document constant string interpolation support in UTs

---

analyzers/src/SonarAnalyzer.CSharp/Facade/CSharpSyntaxFacade.cs
analyzers/src/SonarAnalyzer.CSharp/Helpers/CSharpSyntaxHelper.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/DoNotHardcodeCredentials.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/PubliclyWritableDirectories.cs
analyzers/src/SonarAnalyzer.Common/Facade/SyntaxFacade.cs
analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/PubliclyWritableDirectoriesBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Facade/VisualBasicSyntaxFacade.cs
analyzers/tests/SonarAnalyzer.UnitTest/Facade/SyntaxFacadeTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Hotspots/PubliclyWritableDirectoriesTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/PubliclyWritableDirectories.CSharp10.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/PubliclyWritableDirectories.cs

Fix FN S5443: No issue is raised if the publicly writable directory path is assembled with the help of a constant interpolated string

---

analyzers/src/SonarAnalyzer.CSharp/Extensions/BlockSyntaxExtensions.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/EmptyMethod.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/EmptyNestedBlock.cs
analyzers/tests/SonarAnalyzer.UnitTest/Extensions/BlockSyntaxExtensionsTests.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/EmptyMethod.Comment.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/EmptyMethod.Throw.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/EmptyMethod.cs

Improvement: Merge IsEmpty(BlockSyntax) implementations

---

analyzers/src/SonarAnalyzer.CSharp/Rules/CallerInformationParametersShouldBeLast.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/CallerInformationParametersShouldBeLastTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CallerInformationParametersShouldBeLast.CSharp10.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CallerInformationParametersShouldBeLast.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CallerInformationParametersShouldBeLastInvalidSyntax.cs

S3343: Add tests for [CallerArgumentExpression] and support local functions

---

analyzers/src/SonarAnalyzer.CSharp/Facade/CSharpSyntaxFacade.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/HardcodedIpAddress.cs
analyzers/src/SonarAnalyzer.Common/Facade/SyntaxFacade.cs
analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/HardcodedIpAddressBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Facade/VisualBasicSyntaxFacade.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/Hotspots/HardcodedIpAddress.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/HardcodedIpAddress.vb

S1313 FN: VB.NET - No issue is raised if the IP address is assembled as an interpolated string

---

analyzers/src/SonarAnalyzer.CSharp/Helpers/CSharpSyntaxHelper.cs
analyzers/src/SonarAnalyzer.CSharp/Helpers/CsharpStringValueHelper.cs
analyzers/src/SonarAnalyzer.Common/Helpers/StringValueHelper.cs
analyzers/src/SonarAnalyzer.Common/Rules/SecurityPInvokeMethodShouldNotBeCalledBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Facade/VisualBasicSyntaxFacade.cs
analyzers/src/SonarAnalyzer.VisualBasic/Helpers/VisualBasicStringValueHelper.cs
analyzers/src/SonarAnalyzer.VisualBasic/Helpers/VisualBasicSyntaxHelper.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/Hotspots/DoNotHardcodeCredentials.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/Hotspots/PubliclyWritableDirectories.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/SecurityPInvokeMethodShouldNotBeCalled.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/SecurityPInvokeMethodShouldNotBeCalledTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/PubliclyWritableDirectories.vb
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SecurityPInvokeMethodShouldNotBeCalled.vb

Fix FN S5443 VB.NET: No issue is raised if the publicly writable directory path is assembled with the help of a constant interpolated string

---

analyzers/src/SonarAnalyzer.CFG/ShimLayer/Syntax.xml
analyzers/src/SonarAnalyzer.CSharp/Rules/DoNotCheckZeroSizeCollection.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/DoNotCheckZeroSizeCollectionTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DoNotCheckZeroSizeCollection.CSharp10.cs

Fix FN S3981: No issue is raised when property check is done through a pattern.

---

analyzers/src/SonarAnalyzer.CSharp/Rules/UnnecessaryUsings.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/UnnecessaryUsingsTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnnecessaryUsings.CSharp10.FileScopedNamespace.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnnecessaryUsings.CSharp10.FileScopedNamespace.cs

FN S1128: No issue is raised when the unnecessary using is inside a file scoped namespace

---

analyzers/src/SonarAnalyzer.CFG/ShimLayer/Syntax.xml
analyzers/src/SonarAnalyzer.CSharp/Rules/ImplementSerializationMethodsCorrectly.cs
analyzers/src/SonarAnalyzer.Common/Rules/ImplementSerializationMethodsCorrectlyBase.cs
analyzers/src/SonarAnalyzer.ShimLayer.CodeGeneration/SyntaxLightupGenerator.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/ImplementSerializationMethodsCorrectlyTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ImplementSerializationMethodsCorrectly.CSharp10.cs

Fix FN S3927: No issue is raised when attribute is placed on a lambda

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CloudNative/AzureFunctionsCatchExceptions.cs

Add repro for FP S6421
