SonarSource/sonar-dotnet

- analyzers/src/SonarAnalyzer.CSharp/Rules/ArgumentSpecifiedForCallerInfoParameter.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ArgumentSpecifiedForCallerInfoParameter.cs
> FP S3236: Passthrough parameters should be compliant

- analyzers/src/SonarAnalyzer.Common/Extensions/BinaryOperatorKindExtensions.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Constraints/ObjectConstraint.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Extensions/IOperationExtensions.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Binary.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SymbolicValue.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.LearnConstraint.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/SymbolicValueTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.CSharp6.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.CSharp7.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.CSharp8.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.CSharp9.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Sonar/NullPointerDereference.cs
Contributes to #5970
Rebase will be needed. Commits `Add UnaryOperatorKind to ShimLayer` and `Squash Conversion` do not need a review, but create a lot of noise on GitHub website
> SE: Learn ObjectConstraint and BoolConstraint on branching from equality operators

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Pattern.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.LearnConstraint.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.CSharp7.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.CSharp9.cs
Contributes to #5970
Rebase will be needed, commit `Squash Equals` doesn't need a review.
> SE: Learn ObjectConstraint on branching from constant pattern

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Pattern.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.LearnConstraint.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.CSharp9.cs
> SE: Learn ObjectConstraint on branching from negated pattern

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Pattern.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/SymbolicConstraint.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.LearnConstraint.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/SymbolicContextTest.cs
> SE: Learn ObjectConstraint on branching from type pattern

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IsType.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.LearnConstraint.cs
> SE: Learn ObjectConstraint on branching from IsType

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Pattern.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.LearnConstraint.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.CSharp7.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.CSharp8.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.CSharp9.cs
> SE: Support captured operations in branching

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Pattern.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.PatternMatching.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.CSharp9.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SymbolicExecution/SETestContext.cs
> SE: Learn bool constraint from object constraint in patterns

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Literal.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SymbolicValue.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.LearnConstraint.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.CSharp8.cs
> Improve S2259: Add support for string literal sets NotNull

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/References.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.CSharp6.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.cs
> SE: Do not mix instance fields

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IsNull.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.LearnConstraint.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.IsNull.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.CSharp6.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.CSharp7.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.CSharp8.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.cs
> SE: Learn ObjectConstraint from IsNull operation

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Pattern.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/ProgramState.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ProgramStateTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.LearnConstraint.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.PatternMatching.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.CSharp9.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SymbolicExecution/SETestContext.cs
> SE: Learn ObjectConstraint on branching from Recursive pattern

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Pattern.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.LearnConstraint.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.PatternMatching.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.CSharp7.cs
> SE: Learn ObjectConstraint on branching from DeclarationPattern

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Invocation.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.cs
Part of #5973
See https://github.com/SonarSource/sonar-dotnet/issues/5973#issuecomment-1222109090
> S2259: Support ValidatedNotNullAttribute

- analyzers/its/expected/Net5/jsonserializerfields-9AFDCE7D-6246-495E-B3CF-51715210B93A-net5.0-S3353.json
- analyzers/its/expected/Net5/jsonserializerimmutabletypes-723C2A23-18CA-421D-9458-F71B06A0553A-net5.0-S3353.json
- analyzers/its/expected/Net5/recordsvsclasses-{96F1111E-2713-4CDE-B2D8-BF973EB5A4DE}-net5.0-S3353.json
- analyzers/its/expected/Net5/recordswithstatichelper-541512C1-D79D-48B4-AE0B-D9A643E16D1F-net5.0-S3353.json
- analyzers/its/expected/NetCore31/NetCore31--netcoreapp3.1.Views-S3353.json
- analyzers/its/expected/akka.net/Akka.Cluster--netstandard2.0-S3353.json
- analyzers/its/expected/akka.net/Akka.MultiNodeTestRunner--net5.0-S3353.json
- analyzers/its/expected/akka.net/Akka.MultiNodeTestRunner--netcoreapp3.1-S3353.json
- analyzers/its/expected/akka.net/Akka.Remote--netstandard2.0-S3353.json
- analyzers/its/expected/akka.net/Akka.Serialization.TestKit--net471-S3353.json
- analyzers/its/expected/akka.net/Akka.Serialization.TestKit--net5.0-S3353.json
- analyzers/its/expected/akka.net/Akka.Serialization.TestKit--netcoreapp3.1-S3353.json
- analyzers/its/expected/akka.net/Akka.Streams.Tests.Performance--netcoreapp3.1-S3353.json
- analyzers/its/expected/akka.net/Akka.Tests.Performance--netcoreapp3.1-S3353.json
- analyzers/its/expected/akka.net/TcpEchoService.Server--netcoreapp3.1-S3353.json
- analyzers/src/SonarAnalyzer.CFG/ShimLayer/LanguageVersionEx.cs
- analyzers/src/SonarAnalyzer.CSharp/Extensions/ArgumentSyntaxExtensions.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/UnchangedLocalVariablesShouldBeConst.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Helpers/SyntaxHelperTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/UnchangedLocalVariablesShouldBeConstTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnchangedLocalVariablesShouldBeConst.CSharp10.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnchangedLocalVariablesShouldBeConst.cs
> S3353: Error message unprecise

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.CSharp6.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.cs
Related to #5973
Some FIXMEs are left over. Those should be fixed by other PRs
> S2259: Update FIXME in test cases

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Checks/ConstantCheck.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/ReDim.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.CSharp10.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.vb
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SymbolicExecution/SETestContext.cs
> SE: Implicit Null constraint for VB.NET declarations and ReDim support

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.cs
> SE: Forget field state on await

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Binary.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Binary.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.vb
> SE: Support binary OR

- analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/NullPointerDereference.cs
- analyzers/src/SonarAnalyzer.VisualBasic/SymbolicExecution/Roslyn/NullPointerDereference.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.vb
> Implement NullPointerDereference.ShouldExecute

- analyzers/NuGet.Config
Avoid inheriting the default configuration
> Add <clear /> to NuGet .config

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/NullPointerDereferenceBase.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SymbolicRuleCheck.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.CSharp8.Nullable.cs
> Improve S2259: Check nullability info before reporting

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
> SE: Remove RoslynSymbolicExecution.SetBranchingConstraints

- analyzers/its/expected/Ember-MM/Ember Media Manager-{9B57D3AB-AF12-4012-B945-284C2448DC81}-S2259.json
- analyzers/its/expected/Ember-MM/EmberAPI-{208AA35E-C6AE-4D2D-A9DD-B6EFD19A4279}-S2259.json
- analyzers/its/expected/Ember-MM/generic.EmberCore.MovieExporter-{B0BDF9C2-EB9C-4090-B9A9-B703DF00CCEF}-S2259.json
- analyzers/its/expected/Ember-MM/generic.EmberCore.NMT-{84B2143A-D04F-4262-923D-21AEDF86E2B7}-S2259.json
- analyzers/its/expected/Ember-MM/generic.EmberCore.WebServer-{64D6F035-F186-4193-AF35-D20126B8DA64}-S2259.json
- analyzers/its/expected/Ember-MM/scraper.EmberCore-{EF6A550E-DD76-4F4D-8250-8598140F828B}-S2259.json
- analyzers/its/expected/Ember-MM/scraper.EmberCore.XML-{E567C031-1F7B-4637-9B3A-806988DE50CF}-S2259.json
- analyzers/src/SonarAnalyzer.CSharp/Rules/SpecifyIFormatProviderOrCultureInfo.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Invocation.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Invocation.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.vb
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Sonar/ConditionEvaluatesToConstant.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SymbolicExecution/SETestContext.cs
> Improve S2259: Understand results of Enumerable and Queryable methods from System.Linq

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Argument.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Invocation.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
Part of #6083
~Blocked by #6120~ Unblocked
> Improve S2259: Add support for [NotNull] on parameters.

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Invocation.Enumerable.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Invocation.cs
Extract logic into partial class. The `Invocation` is getting big.
Bump coverage
> SE: Refactor OperationProcessor.Invocation

- analyzers/rspec/cs/S3236_c#.html
- analyzers/rspec/cs/S3343_c#.html
- analyzers/rspec/cs/S5332_c#.html
- analyzers/rspec/cs/S6419_c#.json
- analyzers/rspec/cs/S6420_c#.json
- analyzers/rspec/cs/S6421_c#.json
- analyzers/rspec/cs/S6422_c#.json
- analyzers/rspec/cs/S6423_c#.json
- analyzers/rspec/cs/S6424_c#.json
- analyzers/src/SonarAnalyzer.CSharp/sonarpedia.json
- analyzers/src/SonarAnalyzer.VisualBasic/sonarpedia.json
> Update RSPEC before 8.46 release

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Extensions/IOperationExtensions.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Invocation.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/ProgramState.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Invocation.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.IsNull.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.TryCatchFinally.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SymbolicExecution/SETestContext.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SymbolicExecution/ValidatorTestCheck.cs
> SE: Reset static fields on static method calls

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Extensions/IInvocationOperationExtensions.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Invocation.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/ProgramState.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ProgramStateTest.OperationValue.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Invocation.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.cs
> Fix S2259 FP: Reset fields on this invocation with flow captures

- analyzers/src/SonarAnalyzer.CSharp/Rules/NameOfShouldBeUsed.cs
- analyzers/src/SonarAnalyzer.Common/Rules/NameOfShouldBeUsedBase.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Rules/NameOfShouldBeUsed.cs
> S2302: Fix blocking code smell

- analyzers/src/SonarAnalyzer.Common/DiagnosticAnalyzer/ParameterLoadingDiagnosticAnalyzer.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/DiagnosticAnalyzerContextHelper.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/ParameterLoadingAnalysisContext.cs
- analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/DoNotHardcodeCredentialsBase.cs
- analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/RequestsWithExcessiveLengthBase.cs
There's everything wrong about this class (and parameter loading in general). This is just a small refactoring to make S2068 easier to implement
Prerequisite for #5427
> Refactor ParameterLoadingAnalysisContext

- analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/HardcodedIpAddressBase.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/HardcodedIpAddress.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/HardcodedIpAddress.vb
> Rule S1313: Exclude reserved documentation IP ranges

- analyzers/its/expected/Nancy/Nancy--net452-S3963.json
- analyzers/its/expected/Nancy/Nancy--netstandard2.0-S3963.json
- analyzers/its/expected/Nancy/Nancy.Embedded--net452-S3963.json
- analyzers/its/expected/Nancy/Nancy.Embedded--netstandard2.0-S3963.json
- analyzers/its/expected/Nancy/Nancy.Hosting.Aspnet--net452-S3963.json
- analyzers/its/expected/Net5/Net5--net5.0-S3963.json
- analyzers/its/expected/akka.net/Akka--netstandard2.0-S3963.json
- analyzers/its/expected/akka.net/Akka.Cluster--netstandard2.0-S3963.json
- analyzers/its/expected/akka.net/Akka.Remote.TestKit--netstandard2.0-S3963.json
- analyzers/src/SonarAnalyzer.CSharp/Rules/InitializeStaticFieldsInline.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/InitializeStaticFieldsInline.cs
> Improve S3963: Highlight only the identifier instead of the full constructor body

- analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/HardcodedIpAddressBase.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/HardcodedIpAddress.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/HardcodedIpAddress.vb
> Fix S1313: Exclude local IPv4-mapped IPv6 address

- analyzers/src/SonarAnalyzer.CSharp/Trackers/CSharpInvocationTracker.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/ExecutingSqlQueriesBase.cs
- analyzers/src/SonarAnalyzer.Common/Trackers/InvocationTracker.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Trackers/VisualBasicInvocationTracker.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/Hotspots/ExecutingSqlQueriesTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/ExecutingSqlQueries.EF6.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Trackers/InvocationTrackerTest.cs
> Rule S2077: support for additional database libraries: EF6

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.cs
Add test cases from code found on Peach
https://peach.sonarsource.com/project/issues?issues=AYPR_stwHigTOvkdJW4F&open=AYPR_stwHigTOvkdJW4F&id=sharex
https://peach.sonarsource.com/project/issues?issues=AWdBJLiXagf4vZj17Iq5&open=AWdBJLiXagf4vZj17Iq5&id=sharex
> Add S2259 test cases

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.cs
> S2259: Add FP repro for #6241

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SqlKeywordsDelimitedBySpace.CSharp10.cs
> S2857: Add FP and FN repro for #6126

- sonar-csharp-plugin/src/main/resources/documentation.md
- sonar-vbnet-plugin/src/main/resources/documentation.md
Related to https://github.com/SonarSource/sonar-dotnet/pull/6226
> Mention altcover in public link

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationDispatcher.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/StaticLocalInitializationSemaphore.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.vb
> Fix S2259 FP: Support VB.NET static local variables

- analyzers/Analyzers.targets
- analyzers/src/Directory.Build.targets
- analyzers/src/SonarAnalyzer.CFG/SonarAnalyzer.CFG.csproj
- analyzers/src/SonarAnalyzer.CSharp/SonarAnalyzer.CSharp.csproj
- analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Sonar/SymbolicValues/NullableSymbolicValue.cs
- analyzers/src/SonarAnalyzer.Common/Common/SecondaryLocation.cs
- analyzers/src/SonarAnalyzer.Common/SonarAnalyzer.Common.csproj
- analyzers/src/SonarAnalyzer.VisualBasic/SonarAnalyzer.VisualBasic.csproj
- analyzers/src/SonarAnalyzer.VisualBasic/packages.lock.json
- analyzers/tests/SonarAnalyzer.UnitTest/SonarAnalyzer.UnitTest.csproj
Cleanup will be a separate PR once this one is merged
> Src: Add global usings

- analyzers/src/SonarAnalyzer.Common/Rules/UriShouldNotBeHardcodedBase.cs
I wanted to add a repro and while checking the code I've noticed some small things to improve on the code.
While I've changed my mind regarding the reproducer, I would still keep the code changes.
> Clean UriShouldNotBeHardcodedBase

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SillyBitwiseOperation.Fixed.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SillyBitwiseOperation.cs
> S2437: Add FP repro for #6326

- .github/workflows/CreatePullRequest.yml
Action: https://github.com/SonarSource/gh-action-lt-backlog/tree/master/CreateCardForStandalonePR
Source: https://github.com/SonarSource/gh-action-lt-backlog/blob/master/CreateCardForStandalonePR/CreateCardForStandalonePR.ts
> GitHub workflow: Migrate CreatePullRequest to shared action

- analyzers/src/SonarAnalyzer.CFG/ShimLayer/SyntaxKindEx.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/CloudNative/AzureFunctionsStateless.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CloudNative/AzureFunctionsStateless.CSharp11.cs
> Fix S6419 FN: Support unsigned right-shift operator (>>>)

- analyzers/src/SonarAnalyzer.CFG/ShimLayer/SyntaxKindEx.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/StaticFieldWrittenFrom.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/StaticFieldWrittenFromInstanceConstructor.CSharp11.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/StaticFieldWrittenFromInstanceMember.CSharp11.cs
> Fix S2696 FN and S3010 FN: unsigned right shift operator (>>>)

- analyzers/src/SonarAnalyzer.CFG/ShimLayer/SyntaxKindEx.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/AssignmentInsideSubExpression.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/AssignmentInsideSubExpression.CSharp11.cs
> Fix S1121 FN: Support unsigned right-shift operator (>>>)

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/AsyncVoidMethod.CSharp11.cs
> S3168 FN: Mark virtual interface method test case as compliant.

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ClassWithOnlyStaticMember.CSharp11.cs
> S1118 FN: Marked the FNs as Compliant

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ImplementSerializationMethodsCorrectly.CSharp11.cs
Fixes [#6311](https://github.com/SonarSource/sonar-dotnet/issues/6311)
> S3927 FP: Add better documentation to some Noncompliant UT lines

- analyzers/src/SonarAnalyzer.CFG/ShimLayer/SyntaxKindEx.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/FieldShouldBeReadonly.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/FieldShouldBeReadonly.CSharp11.cs
> Fix S2933 FP: Support unsigned right-shift operator (>>>)

- analyzers/src/SonarAnalyzer.CFG/ShimLayer/SyntaxKindEx.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/GenericReadonlyFieldPropertyAssignment.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/GenericReadonlyFieldPropertyAssignment.CSharp11.cs
> Fix S2934 FN: Support unsigned right shift operator (>>>)

- .github/workflows/RequestReview.yml
- .github/workflows/SubmitReview.yml
Uses these actions, see sample yml:
https://github.com/SonarSource/gh-action-lt-backlog/tree/v1/MoveCardToReview
https://github.com/SonarSource/gh-action-lt-backlog/tree/v1/MoveCardAfterReview
> GitHub workflow: Migrate RequestReview and SubmitReview to shared action

- analyzers/src/SonarAnalyzer.CFG/ShimLayer/SyntaxKindEx.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/ClearTextProtocolsAreSensitive.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/ClearTextProtocolsAreSensitive.CSharp11.cs
> Fix S5332 FN: Support utf-8 string literals

- analyzers/src/SonarAnalyzer.CFG/ShimLayer/Syntax.xml
- analyzers/src/SonarAnalyzer.CSharp/Rules/CastShouldNotBeDuplicated.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CastShouldNotBeDuplicated.CSharp11.cs
> Fix S3247 FN: Support list patterns

- analyzers/src/SonarAnalyzer.CFG/ShimLayer/Syntax.xml
- analyzers/src/SonarAnalyzer.CFG/ShimLayer/SyntaxKindEx.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/DoNotTestThisWithIsOperator.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DoNotTestThisWithIsOperator.CSharp11.cs
> Fix S3060 FN: Support list patterns

- analyzers/src/SonarAnalyzer.CFG/ShimLayer/Syntax.xml
- analyzers/src/SonarAnalyzer.CSharp/Rules/CompareNaN.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CompareNaN.CSharp11.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CompareNaN.cs
> S2688 FN: Do not raise for IsExpression since it works as expected

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/CreatingHashAlgorithms.CSharp11.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/CreatingHashAlgorithms.cs
> S4790 FN: Edit test cases to const string, added interpolation test case

- analyzers/src/SonarAnalyzer.CFG/ShimLayer/SyntaxKindEx.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/DoNotShiftByZeroOrIntSize.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DoNotShiftByZeroOrIntSize.CSharp11.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DoNotShiftByZeroOrIntSize.cs
> Fix S2183 FN: Support unsigned right-shift operator (>>>)

- analyzers/src/SonarAnalyzer.CSharp/Facade/CSharpSyntaxFacade.cs
- analyzers/src/SonarAnalyzer.CSharp/Facade/CSharpSyntaxKindFacade.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/MultipleVariableDeclaration.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/MultipleVariableDeclarationCodeFix.cs
- analyzers/src/SonarAnalyzer.Common/Facade/ISyntaxKindFacade.cs
- analyzers/src/SonarAnalyzer.Common/Facade/SyntaxFacade.cs
- analyzers/src/SonarAnalyzer.Common/Rules/MultipleVariableDeclarationBase.cs
- analyzers/src/SonarAnalyzer.Common/Rules/MultipleVariableDeclarationCodeFixBase.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Facade/VisualBasicSyntaxFacade.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Facade/VisualBasicSyntaxKindFacade.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Rules/MultipleVariableDeclaration.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Rules/MultipleVariableDeclarationCodeFix.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/MultipleVariableDeclarationTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/MultipleVariableDeclaration.WrongIndentation.Fixed.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/MultipleVariableDeclaration.WrongIndentation.cs
> Rule S1659: Add test case with wrong indentation

- analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/DisablingCsrfProtection.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/DisablingCSRFProtection.CSharp11.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/DisablingCSRFProtection.cs
> Fix S4502 FN: Support generic attributes

- analyzers/src/SonarAnalyzer.CSharp/Rules/CryptographicKeyShouldNotBeTooShort.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CryptographicKeyShouldNotBeTooShort.cs
> Fix AD0001 for S4426: CryptographicKeyShouldNotBeTooShort

- analyzers/src/SonarAnalyzer.CSharp/Rules/ParameterValidationInMethodWalker.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/ParameterValidationInAsyncShouldBeWrappedTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/ParameterValidationInYieldShouldBeWrappedTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ParameterValidationInAsyncShouldBeWrapped.CSharp10.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ParameterValidationInAsyncShouldBeWrapped.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ParameterValidationInYieldShouldBeWrapped.CSharp10.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ParameterValidationInYieldShouldBeWrapped.cs
> Fix S4456/S4457 FN ArgumentNullException.ThrowIfNull()

- .github/workflows/MilestoneIssue.yml
Uses this action:
https://github.com/SonarSource/gh-action-lt-backlog/tree/v1/CreateCardForIssue
> GitHub workflow: Migrate MilestoneIssue to shared action

- its/pom.xml
- pom.xml
- scripts/version/set-version.ps1
> Target JDK 11 in Java plugins

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DoNotExposeListT.CSharp9.cs
> FN S3956: Reproducer for Properties declared via primary constructor not detected

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DoNotUseOutRefParameters.CSharp11.cs
Default interface declarations were missing from the tests
> S3874: Add test cases for Direct Interface Implementations

- analyzers/tests/SonarAnalyzer.UnitTest/Rules/ExpressionComplexityTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ExpressionComplexity.CSharp11.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ExpressionComplexity.CSharp9.cs
> S1067: Add FP repros for conditionals in pattern (#6429)

- analyzers/tests/SonarAnalyzer.UnitTest/Rules/EqualityOnFloatingPointTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/EqualityOnFloatingPoint.CSharp11.cs
> S1244: Add tests for Half, NFloat and IFloatingPointIeee754

- analyzers/tests/SonarAnalyzer.UnitTest/Rules/StringOperationWithoutCultureTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/StringOperationWithoutCulture.CSharp10.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/StringOperationWithoutCulture.cs
> S1449: Add repro (#6439) for missing DateTime types.

- analyzers/src/SonarAnalyzer.CSharp/Rules/RedundantConditionalAroundAssignment.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundantConditionalAroundAssignment.CSharp10.Fixed.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundantConditionalAroundAssignment.CSharp10.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundantConditionalAroundAssignment.CSharp11.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundantConditionalAroundAssignment.CSharp9.Fixed.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundantConditionalAroundAssignment.CSharp9.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundantConditionalAroundAssignment.Fixed.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundantConditionalAroundAssignment.cs
This PR is closing issue #6390 since it's not C#11 related, the test will remain marked as FN and another issue will be opened to address the 'is' and 'is not' expressions for this rule.
> S3440 FN: Add test cases for is expression

- analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/PermissiveCors.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/PermissiveCors.CSharp10.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/PermissiveCors.CSharp11.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/PermissiveCors.Net.cs
> Fix S5122 FN: Support raw string literals interpolation

- analyzers/src/SonarAnalyzer.CSharp/Rules/TestMethodShouldNotBeIgnored.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/TestMethodShouldNotBeIgnoredTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/TestMethodShouldNotBeIgnored.CSharp11.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/TestMethodShouldNotBeIgnored.MsTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/TestMethodShouldNotBeIgnored.NUnit.V2.cs
> Fix S1607 FN: Support derived attributes

- analyzers/src/SonarAnalyzer.CSharp/Rules/TestMethodShouldHaveCorrectSignature.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/UnitTestHelper.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/TestMethodShouldHaveCorrectSignature.CSharp11.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/TestMethodShouldHaveCorrectSignature.MsTest.cs
> Fix S3433 FN: Support derived attributes

- analyzers/src/SonarAnalyzer.CSharp/Rules/MethodOverrideNoParams.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/MethodOverrideNoParams.CSharp11.cs
> S3262 FN: Mark comments as compliant in UTs 

- analyzers/tests/SonarAnalyzer.UnitTest/Rules/MemberInitializedToDefaultTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/MemberInitializedToDefault.CSharp8.cs
Add UT with property initialization to default with suppression operator in nullable context.
> S3052: Add nullable test cases

- its/pom.xml
- its/src/test/java/com/sonar/it/shared/TestUtils.java
https://github.com/SonarSource/sonar-scanner-msbuild/releases/tag/5.9.0.57893
> Bump Scanner in ITs to 5.9.0.57893

- analyzers/src/SonarAnalyzer.CSharp/Rules/MemberShadowsOuterStaticMember.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/MemberShadowsOuterStaticMember.CSharp11.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/MemberShadowsOuterStaticMember.CSharp9.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/MemberShadowsOuterStaticMember.cs
> Fix S3218 FN: Support interfaces

- analyzers/its/expected/Automapper/AutoMapper--net461-S1481.json
- analyzers/its/expected/Automapper/AutoMapper--netstandard2.0-S1481.json
- analyzers/its/expected/Net5/Net5--net5.0-S1481.json
- analyzers/its/expected/akka.net/Akka--netstandard2.0-S1481.json
- analyzers/its/expected/akka.net/Akka.Cluster--netstandard2.0-S1481.json
- analyzers/its/expected/akka.net/Akka.Cluster.Metrics--netstandard2.0-S1481.json
- analyzers/its/expected/akka.net/Akka.Cluster.Sharding--netstandard2.0-S1481.json
- analyzers/its/expected/akka.net/Akka.DistributedData--netstandard2.0-S1481.json
- analyzers/its/expected/akka.net/Akka.MultiNodeTestRunner--net471-S1481.json
- analyzers/its/expected/akka.net/Akka.MultiNodeTestRunner--netcoreapp3.1-S1481.json
- analyzers/its/expected/akka.net/Akka.Persistence.Query--netstandard2.0-S1481.json
- analyzers/its/expected/akka.net/Akka.Persistence.TCK--netstandard2.0-S1481.json
- analyzers/its/expected/akka.net/Akka.Remote--netstandard2.0-S1481.json
- analyzers/its/expected/akka.net/Akka.Remote.TestKit--netstandard2.0-S1481.json
- analyzers/its/expected/akka.net/Akka.Remote.Tests.Performance--netcoreapp3.1-S1481.json
- analyzers/its/expected/akka.net/Akka.Streams--netstandard2.0-S1481.json
- analyzers/its/expected/akka.net/RemotePingPong--net471-S1481.json
- analyzers/its/expected/akka.net/RemotePingPong--net5.0-S1481.json
- analyzers/its/expected/akka.net/RemotePingPong--netcoreapp3.1-S1481.json
- analyzers/src/SonarAnalyzer.CSharp/Rules/VariableUnused.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/VariableUnused.CSharp11.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/VariableUnused.CSharp9.cs
Fixes #6377
Also adds support for the other [pattern types with a designation](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/patterns#patterns)
* property pattern (aka recursive pattern)
* positional pattern (aka recursive pattern)
* var pattern
> Fix S1481 FN: Support list patterns

- analyzers/src/SonarAnalyzer.CSharp/Facade/CSharpSyntaxFacade.cs
- analyzers/src/SonarAnalyzer.CSharp/Facade/CSharpSyntaxKindFacade.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/ShiftDynamicNotInteger.cs
- analyzers/src/SonarAnalyzer.Common/Facade/ISyntaxKindFacade.cs
- analyzers/src/SonarAnalyzer.Common/Facade/SyntaxFacade.cs
- analyzers/src/SonarAnalyzer.Common/Rules/ShiftDynamicNotIntegerBase.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Facade/VisualBasicSyntaxFacade.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Facade/VisualBasicSyntaxKindFacade.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Rules/ShiftDynamicNotInteger.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ShiftDynamicNotInteger.CSharp11.cs
> S3449 FN: Remove unsigned right-shift operator test cases (>>>)

- analyzers/rspec/cs/S1123_c#.html
- analyzers/rspec/cs/S3456_c#.html
- analyzers/rspec/cs/S3456_c#.json
- analyzers/rspec/cs/S5332_c#.html
- analyzers/rspec/vbnet/S1123_vb.net.html
- analyzers/src/SonarAnalyzer.CSharp/sonarpedia.json
- analyzers/src/SonarAnalyzer.VisualBasic/sonarpedia.json
> Update RSPEC before 8.50 release 

- analyzers/src/SonarAnalyzer.CSharp/Facade/CSharpSyntaxKindFacade.cs
- analyzers/src/SonarAnalyzer.Common/Facade/ISyntaxKindFacade.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/StringValueHelper.cs
- analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/HardcodedIpAddressBase.cs
- analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/PubliclyWritableDirectoriesBase.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Facade/VisualBasicSyntaxKindFacade.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/HardcodedIpAddress.CSharp11.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/PubliclyWritableDirectories.CSharp11.cs
Fixes #6376  (this was a byproduct of adding the utf8 string literals to the CSharp Facade)
> Fix S1313 FN: Support utf-8 literals and add support utf8 string literals in CSharpFacade

- analyzers/src/SonarAnalyzer.CSharp/Rules/InheritedCollidingInterfaceMembers.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/InheritedCollidingInterfaceMembers.CSharp11.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/InheritedCollidingInterfaceMembers.CSharp8.cs
Fixes [#6386](https://github.com/SonarSource/sonar-dotnet/issues/6386)
> Fix S3444 FN: Support static methods in interfaces

- analyzers/src/SonarAnalyzer.CSharp/Rules/CryptographicKeyShouldNotBeTooShort.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CryptographicKeyShouldNotBeTooShort.CSharp9.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CryptographicKeyShouldNotBeTooShort.cs
> S4426 FN: On .Net 7 when using ECDsaOpenSsl

- analyzers/src/SonarAnalyzer.Common/Helpers/AnalysisConfig.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/AnalysisConfigReader.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/ConfigSetting.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/ProjectConfigReader.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Helpers/AnalysisConfigReaderTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Helpers/ProjectConfigReaderTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/TestHelper.cs
> Incremental PR Analysis: Load unchanged changed files

- analyzers/src/SonarAnalyzer.CSharp/Helpers/CSharpDiagnosticAnalyzerContextHelper.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/WcfMissingContractAttribute.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/DiagnosticAnalyzerContextHelper.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/SonarAnalysisContext.cs
- analyzers/src/SonarAnalyzer.Common/Rules/EmptyMethodBase.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Helpers/SonarAnalysisContextTest.ShouldAnalyzeGenerated.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Helpers/SonarAnalysisContextTest.cs
> Refactor SonarAnalysisContext.ShouldAnalyze

- analyzers/src/SonarAnalyzer.Common/Helpers/AnalysisConfig.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/AnalysisConfigReader.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/DiagnosticAnalyzerContextHelper.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/ProjectConfigReader.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/SonarAnalysisContext.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Helpers/SonarAnalysisContextTest.cs
> Incremental PR Analysis: Cache the unchanged files

- analyzers/src/SonarAnalyzer.CSharp/Extensions/AwaitExpressionSyntaxExtensions.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/StreamReadStatement.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Extensions/AwaitExpressionSyntaxExtensionsTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/StreamReadStatement.cs
> Fix S2674 FN: Add support for ConfigureAwait

- analyzers/src/SonarAnalyzer.CSharp/Rules/EqualityOnFloatingPoint.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/EqualityOnFloatingPoint.CSharp11.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/EqualityOnFloatingPoint.cs
> Fix S1244 FN: Half, NFloat, and IFloatingPointIeee754 are not supported

- analyzers/its/SonarAnalyzer.Testing.ImportBefore.targets
- analyzers/its/SonarQubeAnalysisConfig.xml
- analyzers/src/SonarAnalyzer.CSharp/Helpers/CSharpDiagnosticAnalyzerContextHelper.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/AnalysisConfig.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/AnalysisConfigReader.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/DiagnosticAnalyzerContextHelper.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/ProjectConfigReader.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/SonarAnalysisContext.cs
- analyzers/src/SonarAnalyzer.Common/Rules/EmptyMethodBase.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Helpers/DiagnosticAnalyzerContextHelperTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Helpers/SonarAnalysisContextTest.ShouldAnalyze.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Helpers/SonarAnalysisContextTest.ShouldAnalyzeGenerated.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Helpers/SonarAnalysisContextTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/TestHelper.cs
Fixes #6485
Follow up PRs will be:
* Implement utility analyzers #6515
* add UT for various rules (one per registration kind)* #6518
* refactor the mess
> Incremental PR Analysis: Update rules to consider the unchanged files

- analyzers/src/SonarAnalyzer.CSharp/Rules/StreamReadStatement.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/StreamReadStatementTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/StreamReadStatement.CSharp11.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/StreamReadStatement.cs
> Fix S2674 FN: Add support for Stream.ReadAtLeast

- analyzers/tests/SonarAnalyzer.UnitTest/Common/RuleTest.cs
Follow up of #6508
~~First two commitds does not need a review:~~
* ~~Refactor TestHelper.CreateSonarProjectConfig~~
* ~~Squash ShouldAnalyzeAndThisTimeIMeanIt~~
> Incremental PR Analysis: Add rule UTs

- analyzers/src/SonarAnalyzer.Common/Rules/Utilities/CopyPasteTokenAnalyzerBase.cs
- analyzers/src/SonarAnalyzer.Common/Rules/Utilities/UtilityAnalyzerBase.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/CopyPasteTokenAnalyzerTest.cs
> Incremental PR Analysis: Run CopyPasteTokenAnalyzer for all files

- analyzers/tests/SonarAnalyzer.UnitTest/Rules/NativeMethodsShouldBeWrappedTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/NativeMethodsShouldBeWrapped.CSharp11.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/NativeMethodsShouldBeWrapped.CSharp9.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/NativeMethodsShouldBeWrapped.cs
> Tests for S4200: Add testcases from S4214

- docs/coding-style.md
The context is [on slack](https://sonarsource.slack.com/archives/C012KBFFYD6/p1670419941305159?thread_ts=1669286144.335599&cid=C012KBFFYD6)
This should be simple to review.
> Update coding-style for arrow position on method/property

- analyzers/src/SonarAnalyzer.CSharp/Rules/ExpressionComplexity.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ExpressionComplexity.cs
Follow up to #6500 after peach vailidation
> S1067 FN: Add condition of conditional ternary operator to list of visited childreen

- analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarAnalysisContextBase.cs
- analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarCodeBlockStartAnalysisContext.cs
- analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarCompilationAnalysisContext.cs
- analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarCompilationStartAnalysisContext.cs
- analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarSymbolAnalysisContext.cs
- analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarSyntaxNodeAnalysisContext.cs
- analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarSyntaxTreeAnalysisContext.cs
Part of #6532
I already know that I will need these from later refactoring phase. They serve as unified wrappers for their Roslyn counterparts
I promise the coverage will get better 😅
> Refactor SonarAnalysisContext - Add AnalysisContext classes

- its/src/test/java/com/sonar/it/csharp/CasingAppTest.java
- its/src/test/java/com/sonar/it/csharp/MultiTargetAppTest.java
- its/src/test/java/com/sonar/it/csharp/Tests.java
> Remove analyzeProjectWithSubProject

- README.md
> Update README.md: Fix link

- azure-pipelines.yml
> Use java 17 for Java ITs

- analyzers/src/SonarAnalyzer.CFG/SonarAnalyzer.CFG.csproj
- analyzers/src/SonarAnalyzer.CFG/packages.lock.json
- analyzers/src/SonarAnalyzer.CSharp/SonarAnalyzer.CSharp.csproj
- analyzers/src/SonarAnalyzer.CSharp/packages.lock.json
- analyzers/src/SonarAnalyzer.Common/SonarAnalyzer.Common.csproj
- analyzers/src/SonarAnalyzer.Common/packages.lock.json
- analyzers/src/SonarAnalyzer.RuleDescriptorGenerator/SonarAnalyzer.RuleDescriptorGenerator.csproj
- analyzers/src/SonarAnalyzer.RuleDescriptorGenerator/packages.lock.json
- analyzers/src/SonarAnalyzer.VisualBasic/SonarAnalyzer.VisualBasic.csproj
- analyzers/src/SonarAnalyzer.VisualBasic/packages.lock.json
- analyzers/tests/SonarAnalyzer.UnitTest/SonarAnalyzer.UnitTest.csproj
- analyzers/tests/SonarAnalyzer.UnitTest/packages.lock.json
> Remove useless package references

- azure-pipelines.yml
> Rename SC project

- analyzers/packaging/SonarAnalyzer.CSharp.nuspec
- analyzers/packaging/SonarAnalyzer.VisualBasic.nuspec
> Add clean code tag

- analyzers/src/SonarAnalyzer.CSharp/SonarAnalyzer.CSharp.csproj
- analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarAnalysisContext.cs
- analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarAnalysisContextBase.cs
- analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarCodeBlockAnalysisContext.cs
- analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarCodeBlockStartAnalysisContext.cs
- analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarCompilationAnalysisContext.cs
- analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarCompilationStartAnalysisContext.cs
- analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarParametrizedAnalysisContext.cs
- analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarReportingContextBase.cs
- analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarSymbolAnalysisContext.cs
- analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarSyntaxNodeAnalysisContext.cs
- analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarSyntaxTreeAnalysisContext.cs
- analyzers/src/SonarAnalyzer.Common/DiagnosticAnalyzer/SonarDiagnosticAnalyzer.cs
- analyzers/src/SonarAnalyzer.Common/SonarAnalyzer.Common.csproj
- analyzers/src/SonarAnalyzer.VisualBasic/SonarAnalyzer.VisualBasic.csproj
- analyzers/tests/SonarAnalyzer.UnitTest/AnalysisContext/SonarAnalysisContextBaseTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/AnalysisContext/SonarAnalysisContextTest.Register.cs
- analyzers/tests/SonarAnalyzer.UnitTest/AnalysisContext/SonarAnalysisContextTest.ShouldAnalyzeTree.cs
- analyzers/tests/SonarAnalyzer.UnitTest/AnalysisContext/SonarAnalysisContextTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/AnalysisContext/SyntaxTreeContextExtensionsTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Common/RuleTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/UtilityAnalyzerBaseTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/DiagnosticVerifier.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SnippetCompiler.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Tests/CodeFixProviderTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Tests/DummyAnalyzer.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Tests/DummyUtilityAnalyzer.cs
Part of #6532
Align namespace with directory name
> Refactor SonarAnalysisContext - Add AnalysisContext namespace

- analyzers/tests/SonarAnalyzer.UnitTest/SonarAnalyzer.UnitTest.csproj
- analyzers/tests/SonarAnalyzer.UnitTest/packages.lock.json
We currently use a pre-release version of the Workspace packages. This PR updates the dependencies to the release versions
> Packages: Use release version of Microsoft.CodeAnalysis.CSharp.Workspaces 4.4

- .editorconfig
- analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarAnalysisContext.cs
- analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarAnalysisContextBase.cs
- analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarCompilationAnalysisContext.cs
- analyzers/src/SonarAnalyzer.Common/Rules/EmptyMethodBase.cs
- analyzers/src/SonarAnalyzer.Common/Rules/PropertiesAccessCorrectFieldBase.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Rules/EmptyMethod.cs
- analyzers/tests/SonarAnalyzer.UnitTest/AnalysisContext/SonarAnalysisContextTest.Register.cs
> Refactor SonarAnalysisContext - Fix CodeSmells

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SqlKeywordsDelimitedBySpace.CSharp10.cs
> S2857: Add FP repro for #6633

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/AssertionArgsShouldBePassedInCorrectOrder.MsTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/AssertionArgsShouldBePassedInCorrectOrder.NUnit.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/AssertionArgsShouldBePassedInCorrectOrder.Xunit.cs
> S3415: Add FN repro for #6547

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/AssertionArgsShouldBePassedInCorrectOrder.MsTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/AssertionArgsShouldBePassedInCorrectOrder.NUnit.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/AssertionArgsShouldBePassedInCorrectOrder.Xunit.cs
> S3415: Add FN/FP repro for #6630

- scripts/rspec/rspec-templates/Rule.Base.cs
- scripts/rspec/rspec-templates/Rule.CS.cs
- scripts/rspec/rspec-templates/Rule.VB.cs
> Fix rspec scaffolding script after the SonarAnalysisContext refactoring

- analyzers/src/SonarAnalyzer.CFG/ShimLayer/SyntaxKindEx.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/InfiniteRecursion.RoslynCfg.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/InfiniteRecursionTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/InfiniteRecursion.RoslynCfg.CSharp9.cs
> Fix FN S2190: No issues raised if recursion is inside an init accessor of a property

- analyzers/rspec/cs/S2930_c#.html
- analyzers/src/SonarAnalyzer.CSharp/Rules/DisposableNotDisposed.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/DisposableNotDisposedTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DisposableNotDisposed.CSharp8.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DisposableNotDisposed.CSharp9.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DisposableNotDisposed.cs
> Fix FP S2930: IAsyncDisposable objects should not be flagged if disposed properly

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Sonar/EmptyNullableValueAccess.CSharp9.cs
> S3655: Add FP repro for #6682

- analyzers/src/SonarAnalyzer.Common/Rules/ImplementSerializationMethodsCorrectlyBase.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/ImplementSerializationMethodsCorrectlyTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ImplementSerializationMethodsCorrectly.CSharp11.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ImplementSerializationMethodsCorrectly.CSharp8.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ImplementSerializationMethodsCorrectly.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ImplementSerializationMethodsCorrectly.vb
Fixes #6331 
~~Made into a draft because it should be merged after the release.~~
> Improve S3927: Interfaces should be excluded

- analyzers/src/SonarAnalyzer.RuleDescriptorGenerator/SonarAnalyzer.RuleDescriptorGenerator.csproj
- azure-pipelines.yml
- sonar-csharp-plugin/pom.xml
- sonar-vbnet-plugin/pom.xml
> Fix RuleDescriptorGenerator and SonarAnalyzer.Common dependency issue

- analyzers/src/SonarAnalyzer.CSharp/Helpers/CSharpSymbolUsageCollector.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnusedPrivateMember.CSharp8.cs
> Fix S4487 FP: ??= operator reads value

- its/src/test/java/com/sonar/it/csharp/IncrementalAnalysisTest.java
- its/src/test/java/com/sonar/it/vbnet/WebConfigTest.java
> Re-introduce incremental PR integration tests

- its/src/test/java/com/sonar/it/shared/ScannerCliTest.java
> Revert mitigation for SQ regression on our ITs

- analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/ConditionEvaluatesToConstantTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/EmptyCollectionsShouldNotBeEnumeratedTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/HashesShouldHaveUnpredictableSaltTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/InitializationVectorShouldBeRandomTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/PublicMethodArgumentsShouldBeCheckedForNullTest.cs
> Rename verifier in SE rules - fix rebase

- analyzers/tests/SonarAnalyzer.UnitTest/MetadataReferences/AspNetCoreMetadataReference.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/Hotspots/DeliveringDebugFeaturesInProductionTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/DeliveringDebugFeaturesInProduction.Net7.cs
> Add reproducer for #6772 (S4507 FP: Error raised on .NET 7 although the debug feature is deactivated)

- .github/workflows/ToggleLockBranch.yml
Add [ToggleLockBranch](https://github.com/SonarSource/gh-action-lt-backlog/tree/master/ToggleLockBranch)
To review this, just make sure that the file is identical with AutoScan one (name, location, content)
https://github.com/SonarSource/sonar-dotnet-autoscan/blob/master/.github/workflows/ToggleLockBranch.yml
> GitHub workflow: Add ToggleLockBranch

- analyzers/src/SonarAnalyzer.Common/Rules/Utilities/AnalysisWarningAnalyzerBase.cs
Fix rebase conflict between #6576 and #6710
> AnalysisWarningAnalyzer: Fix rebase conflict

- docs/coding-style.md
See https://trello.com/c/GkCCaAHa/13-coding-style-common-code-at-the-bottom
> Coding Style: Put "leaf" methods at the bottom

- analyzers/src/SonarAnalyzer.ShimLayer.CodeGeneration/SonarAnalyzer.ShimLayer.CodeGeneration.csproj
- analyzers/src/SonarAnalyzer.ShimLayer.CodeGeneration/packages.lock.json
- analyzers/src/SonarAnalyzer.SourceGenerators/SonarAnalyzer.SourceGenerators.csproj
- analyzers/src/SonarAnalyzer.SourceGenerators/packages.lock.json
Aggregate PR for dependa-bot PRs:
#6730
#6733
#6790
> Bump Roslyn and NuGet dependencies

- analyzers/tests/SonarAnalyzer.UnitTest/SonarAnalyzer.UnitTest.csproj
- analyzers/tests/SonarAnalyzer.UnitTest/packages.lock.json
> Bump MsTest to 3.0.2 and Test SDK to 17.5.0

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundantInheritanceList.Fixed.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundantInheritanceList.cs
> Add reproducer for #6823 

- analyzers/src/SonarAnalyzer.Common/Helpers/WildcardPatternMatcher.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Helpers/WildcardPatternMatcherTest.cs
> Add support for wildcard to regex mapping

- analyzers/src/SonarAnalyzer.CSharp/Rules/PrivateStaticMethodUsedOnlyByNestedClass.cs
> Fix S3398: Replace SyntaxWalker with SafeSyntaxWalker

- analyzers/src/SonarAnalyzer.Common/Helpers/PropertiesHelper.cs
- analyzers/src/SonarAnalyzer.Common/Rules/Utilities/UtilityAnalyzerBase.cs
> Use SonarLint data class to retrieve user configuration about header comments analysis

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/References.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.LearnConstraint.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Nullable.cs
Part of #6812
```
if(arg.HasValue)
// We know arg is NotNull
else
// We know arg is Null
```
> SE - Nullable: Learn `ObjectConstraint` from branching on `nullable.HasValue`

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SymbolicValue.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Nullable.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.PatternMatching.cs
> SE - NonNullableValueTypes: SymbolicValue "True/False" also means "NotNull"

- analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/EmptyNullableValueAccess.cs
Task 3 of https://github.com/SonarSource/sonar-dotnet/issues/6794
Previous task: https://github.com/SonarSource/sonar-dotnet/pull/6876
> S3655: Implement ShouldExecute

- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
> SE - Non-nullable value types: Indexer and Range support

- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
Part of #6105 
Superceeds outdated #6871
> SE - Non-nullable value types: Add SizeOf tests

- analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarAnalysisContext.cs
- analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarAnalysisContextBase.cs
- analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarCodeBlockStartAnalysisContext.cs
- analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarCompilationReportingContext.cs
- analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarCompilationStartAnalysisContext.cs
- analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarReportingContextBase.cs
- analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarSymbolReportingContext.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/ReportingContext.cs
- analyzers/tests/SonarAnalyzer.UnitTest/AnalysisContext/SonarCodeBlockStartAnalysisContextTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/AnalysisContext/SonarCompilationReportingContextTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/AnalysisContext/SonarCompilationStartAnalysisContextTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/AnalysisContext/SonarSymbolReportingContextTest.cs
> Move Tree from `SonarReportingContextBase` to `SonarTreeReportingContextBase`

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/NullPointerDereferenceBase.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.cs
> Fix S2259 FP/FN: Do not raise on Nullable members

- analyzers/its/expected/Ember-MM/Ember Media Manager-{9B57D3AB-AF12-4012-B945-284C2448DC81}-S2259.json
- analyzers/its/expected/Ember-MM/EmberAPI-{208AA35E-C6AE-4D2D-A9DD-B6EFD19A4279}-S2259.json
- analyzers/its/expected/Ember-MM/generic.EmberCore.NMT-{84B2143A-D04F-4262-923D-21AEDF86E2B7}-S2259.json
- analyzers/its/expected/Ember-MM/scraper.EmberCore-{EF6A550E-DD76-4F4D-8250-8598140F828B}-S2259.json
- analyzers/its/expected/Ember-MM/scraper.EmberCore.XML-{E567C031-1F7B-4637-9B3A-806988DE50CF}-S2259.json
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Extensions/IOperationExtensions.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/NullPointerDereferenceBase.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.CSharp8.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.CSharp9.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.vb
> Fix S2259 FN: Raise on fields and events

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ReturnEmptyCollectionInsteadOfNull.CSharp8.cs
> S1168 : Add FP reproducer for #6878

- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SymbolicExecution/SETestContext.cs
> SE - Property reference: Test case for auto properties are not learning constraints

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Binary.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.LearnConstraint.cs
Review per commit should make it easier - I had to split 2 UTs as more constraints were present.
We'll eventually need to do this migration on more places. While gently avoiding conflicts on engine work.
> SE: Migrate to new assertions - RoslynSymbolicExecutionTest.Branching.LearnConstraint.cs

- analyzers/src/SonarAnalyzer.Common/Helpers/TypeHelper.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Helpers/TypeHelperTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
> SE - Non-nullable value types: Remove Enum constraint from IsStruct()

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IsPattern.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.LearnConstraint.cs
Part of #6812
```
if(arg is {} )
// we know NotNull here
```
> SE - Nullable: Learn NotNull from recursive pattern

- analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/EmptyNullableValueAccess.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyNullableValueAccess.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Sonar/EmptyNullableValueAccess.cs
Task 5 of https://github.com/SonarSource/sonar-dotnet/issues/6794
Previous task: https://github.com/SonarSource/sonar-dotnet/pull/6914
> S3655: Extend tests, fix ShouldExecute and FP on non-nullable value types

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SymbolicValue.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ExplodedNodeTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ProgramStateTest.OperationValue.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ProgramStateTest.SymbolValue.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ProgramStateTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Invocation.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/SymbolicContextTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Tests/SymbolicValueAssertionsTest.cs
> SE: Make SymbolicValue ctor private.

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/References.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SymbolicValue.cs
> SE: Maintenance: Remove SymbolicValue.This

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SymbolicCheckList.cs
> SE: Maintenance: Unroll SymbolicCheckList.InvokeChecks

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ArrayPassedAsParams.cs
> S3878: Add FP reproducers for #6893 and #6894

- analyzers/its/expected/Nancy/Nancy--net452-S2259.json
- analyzers/its/expected/Nancy/Nancy--netstandard2.0-S2259.json
- analyzers/its/expected/akka.net/Akka.Cluster.Sharding--netstandard2.0-S2259.json
- analyzers/its/expected/akka.net/Akka.Remote--netstandard2.0-S2259.json
- analyzers/its/expected/akka.net/Akka.Streams--netstandard2.0-S2259.json
- analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/NullPointerDereference.cs
- analyzers/src/SonarAnalyzer.VisualBasic/SymbolicExecution/Roslyn/NullPointerDereference.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.CSharp6.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.CSharp7.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.CSharp8.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.cs
Fixes #4250
Remove suppresion from #6117 after #6812  was implemented.
> S2259: Support coalescing and conditional access

- analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/EmptyNullableValueAccessTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyNullableValueAccess.Nullable.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyNullableValueAccess.NullableContext.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyNullableValueAccess.cs
Part 1 of task 6 of https://github.com/SonarSource/sonar-dotnet/issues/6794
Previous task: https://github.com/SonarSource/sonar-dotnet/pull/6918
> S3655: Deconstruction and null forgiving operator

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/EmptyNullableValueAccessBase.cs
Part 4 of task 6 of https://github.com/SonarSource/sonar-dotnet/issues/6794
Previous task: https://github.com/SonarSource/sonar-dotnet/pull/6962
> S3655: Use IsNonNullableValueType

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Checks/NonNullableValueTypeCheck.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.LearnConstraint.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Constants.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.InvocationAttribute.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Nullable.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.cs
> SE - Non-nullable value types: Set NotNull Constraint for tracked Symbols in NonNullableValueTypeCheck

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ArrayPassedAsParams.cs
> S3878: Add FN repro for #6977

- analyzers/src/SonarAnalyzer.Common/Helpers/HashCode.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Helpers/HashCodeTest.cs
> SE: Maintenance: Allocation free hash code implementation for immutable dict

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CheckArgumentException.cs
See https://community.sonarsource.com/t/s3928-with-local-function-false-positive-or-expected-behavior/56003
> Rule S3928: update case to be a false positive

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Extensions/IOperationExtensions.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Extensions/VisualBasic/ISymbolExtensionsTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/IOperationExtensionsTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Binary.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Invocation.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SymbolicExecution/SETestContext.cs
> Fix S2259 FN: Auto-Properties don't learn ObjectConstraint

- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.LearnConstraint.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/PublicMethodArgumentsShouldBeCheckedForNull.cs
Part of #6997
This is still a draft because it documents the FP without fixing it.
> S3900: Add FP repro for captured parameters

- analyzers/its/expected/Ember-MM/Ember Media Manager-{9B57D3AB-AF12-4012-B945-284C2448DC81}-S3900.json
- analyzers/its/expected/Ember-MM/EmberAPI-{208AA35E-C6AE-4D2D-A9DD-B6EFD19A4279}-S3900.json
- analyzers/its/expected/Ember-MM/generic.EmberCore.BulkRename-{EAAB0601-6478-44D2-A39C-89B0850D7833}-S3900.json
- analyzers/its/expected/Ember-MM/generic.EmberCore.Extractor-{B413DEAF-4FDC-416A-B3E0-968C1C8F3F83}-S3900.json
- analyzers/its/expected/Ember-MM/generic.EmberCore.MediaFileManager-{F6CACA89-E8E4-45D9-B942-97FBD4ADD106}-S3900.json
- analyzers/its/expected/Ember-MM/generic.EmberCore.MovieExporter-{B0BDF9C2-EB9C-4090-B9A9-B703DF00CCEF}-S3900.json
- analyzers/its/expected/Ember-MM/generic.EmberCore.NMT-{84B2143A-D04F-4262-923D-21AEDF86E2B7}-S3900.json
- analyzers/its/expected/Ember-MM/generic.EmberCore.Notifications-{2A08A524-88DA-432F-92E6-8DC63C5376DA}-S3900.json
- analyzers/its/expected/Ember-MM/generic.EmberCore.WebServer-{64D6F035-F186-4193-AF35-D20126B8DA64}-S3900.json
- analyzers/its/expected/Ember-MM/generic.EmberCore.XBMC-{6FE33C61-E2C2-4982-9536-63AEF0A98AAA}-S3900.json
- analyzers/its/expected/Ember-MM/multi.Compatibility-{859C1085-518B-49D2-9C84-D91C4094097F}-S3900.json
- analyzers/its/expected/Ember-MM/scraper.EmberCore-{EF6A550E-DD76-4F4D-8250-8598140F828B}-S3900.json
- analyzers/its/expected/Ember-MM/scraper.EmberCore.XML-{E567C031-1F7B-4637-9B3A-806988DE50CF}-S3900.json
- analyzers/rspec/vbnet/S3900_vb.net.html
- analyzers/rspec/vbnet/S3900_vb.net.json
- analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/LocksReleasedAllPaths.cs
- analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/NullPointerDereference.cs
- analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/PublicMethodArgumentsShouldBeCheckedForNull.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/PublicMethodArgumentsShouldBeCheckedForNullBase.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Rules/SymbolicExecution/SymbolicExecutionRunner.cs
- analyzers/src/SonarAnalyzer.VisualBasic/SymbolicExecution/Roslyn/LocksReleasedAllPaths.cs
- analyzers/src/SonarAnalyzer.VisualBasic/SymbolicExecution/Roslyn/NullPointerDereference.cs
- analyzers/src/SonarAnalyzer.VisualBasic/SymbolicExecution/Roslyn/PublicMethodArgumentsShouldBeCheckedForNull.cs
- analyzers/tests/SonarAnalyzer.UnitTest/PackagingTests/RuleTypeMappingVB.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/PublicMethodArgumentsShouldBeCheckedForNullTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/PublicMethodArgumentsShouldBeCheckedForNull.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/PublicMethodArgumentsShouldBeCheckedForNull.vb
> New Rule S3900 for VB.NET: Arguments of public methods should be validated against Nothing

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CallToAsyncMethodShouldNotBeBlocking.cs
> FP S4462: Re-producer for #7053 (Result is accessed after Task.WhenAll)

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Sonar/ConditionEvaluatesToConstant.CSharp8.cs
> Add reproducer for #7088

- analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/SymbolicExecutionRunner.cs
- analyzers/src/SonarAnalyzer.Common/Rules/SymbolicExecutionRunnerBase.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Rules/SymbolicExecution/SymbolicExecutionRunner.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/SymbolicExecutionRunnerTest.cs
Fixes #4824
Review it per commit, as I converted files to file scoped namespaces and that's noisy on GitHub UI
> SE: Update rule activation to be compatible with .editorconfig

- analyzers/packaging/SonarAnalyzer.CSharp.nuspec
- analyzers/packaging/SonarAnalyzer.VisualBasic.nuspec
- analyzers/src/AssemblyInfo.Shared.cs
- analyzers/src/SonarAnalyzer.CFG/SonarAnalyzer.CFG.cs.nuspec
- its/pom.xml
- pom.xml
- scripts/version/Version.props
- sonar-csharp-plugin/pom.xml
- sonar-dotnet-shared-library/pom.xml
- sonar-vbnet-plugin/pom.xml
Version 9.0 is a major version bump due to break of backward compatibility.
See #6028
> Bump version to 9.0.0

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/LockedFieldShouldBeReadonly.cs
> Add FP repro for #7058

- analyzers/packaging/SonarAnalyzer.CSharp.nuspec
- analyzers/packaging/SonarAnalyzer.VisualBasic.nuspec
> NuGet: Replace broken projectUrl link

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Constraints/BoolConstraint.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Constraints/LockConstraint.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Constraints/ObjectConstraint.cs
Code cleanup, extracted to avoid too many changes on the next one
> SE: Use file-scoped namespaces for constraints

- analyzers/src/SonarAnalyzer.VisualBasic/sonarpedia.json
Fix for step 1 of https://github.com/SonarSource/sonar-dotnet/issues/7150
> Add no-language-in-filenames option to VB.NET sonarpedia.json

- analyzers/NuGet.Config
> Remove Repox Artifactory (releases) from nuget.config

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Constraints/NumberConstraint.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Constraints/NumberConstraintTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/SymbolicConstraintTest.cs
Prerequisite for #7140 
This will be needed by caching and UT assertions
> SE: Add Equals and GetHashCode to NumberConstraint

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IncrementOrDecrement.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.IncrementOrDecrement.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Loops.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Monitor.Loops.cs
> SE: Add IncrementOrDecrementOperation support for numeric values

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Constraints/NumberConstraint.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Binary.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Constraints/NumberConstraintTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Binary.cs
> SE: Add MultiplicationOperation

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Binary.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Binary.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.LearnConstraint.cs
> SE: Learn NumberConstraint from combined Equals and NotEquals

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Binary.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.LearnConstraint.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Loops.cs
Part of #7143
Commits `Squash LearnNumberCombined`  does not need a review
Coverage will be fixed by a rebase, a commit was already pushed to #7198 
Review per commit will be easier than the full batch
> SE: Learn NumberConstraint from existing constraint

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.cs
> S2259: Add FP repro from Peach

- analyzers/its/expected/Ember-MM/scraper.EmberCore-{EF6A550E-DD76-4F4D-8250-8598140F828B}-S3900.json
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Extensions/IOperationExtensions.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/IOperationExtensionsTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.cs
> SE: Enum members are not tracked symbols

- analyzers/src/SonarAnalyzer.CSharp/Rules/ClassAndMethodName.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/ClassAndMethodNameTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ClassAndMethodName.cs
> Repo S101 FP: Lower case character after number

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationDispatcher.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/CompoundAssignment.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Binary.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.CompoundAssignment.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Loops.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.ParameterReassignedConstraint.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Monitor.Conditions.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/PublicMethodArgumentsShouldBeCheckedForNull.vb
> SE: Reset values on compound assignments

- sonar-csharp-plugin/pom.xml
Updating expectations after feature branch rebase and #7248
> Update expected plugin size

- analyzers/its/expected/Net7/Net7--net7.0-S3949.json
- analyzers/its/expected/akka.net/Akka--netstandard2.0-S3949.json
- analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/CalculationsShouldNotOverflow.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Extensions/IOperationExtensions.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/CalculationsShouldNotOverflowBase.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/CalculationsShouldNotOverflow.CSharp10.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/CalculationsShouldNotOverflow.cs
> Implement S3949 logic

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Constraints/NumberConstraint.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Binary.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/BranchingProcessor.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IsNull.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IsPattern.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IsType.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/References.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.LearnConstraint.cs
> SE: Learn NumberConstraint from range comparisons

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/CalculationsShouldNotOverflowBase.cs
Refactoring to bump coverage, inpired by idea mentioned here: 
https://github.com/SonarSource/sonar-dotnet/pull/7252#pullrequestreview-1441333546
It's fine to call `From` many times, because the instances will get cached in #7256
> S3949: Refactor to bump coverage

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/CompoundAssignment.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Binary.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.ParameterReassignedConstraint.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/PublicMethodArgumentsShouldBeCheckedForNull.CSharp9.cs
Part of #7144 
Related to #7111
> SE: CompoundAssignment learns NotNull

- analyzers/rspec/cs/S6424.html
- analyzers/rspec/cs/S6608.html
- analyzers/rspec/vbnet/S6608.html
- analyzers/src/SonarAnalyzer.CSharp/sonarpedia.json
- analyzers/src/SonarAnalyzer.VisualBasic/sonarpedia.json
> Update RSPEC before 9.1 release

- analyzers/its/expected/Automapper/AutoMapper--net461-S3237.json
- analyzers/its/expected/Automapper/AutoMapper--netstandard2.0-S3237.json
- analyzers/its/expected/Net5/Net5--net5.0-S3237.json
- analyzers/src/SonarAnalyzer.CSharp/Rules/UseValueParameter.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UseValueParameter.CSharp9.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UseValueParameter.cs
> Modify S3237 message to be more accurate

- analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/SymbolicExecutionRunner.cs
- analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/CSharpSyntaxClassifier.cs
- analyzers/src/SonarAnalyzer.Common/Rules/SymbolicExecutionRunnerBase.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Binary.Arithmetic.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Binary.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/BranchingProcessor.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IsNull.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IsPattern.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IsType.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/References.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SymbolicContext.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SyntaxClassifierBase.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Rules/SymbolicExecution/SymbolicExecutionRunner.cs
- analyzers/src/SonarAnalyzer.VisualBasic/SymbolicExecution/Roslyn/VisualBasicSyntaxClassifier.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Loops.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/SymbolicCheckListTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/SymbolicContextTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/SyntaxClassifierTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SymbolicExecution/SETestContext.cs
> Fix SE FPs: Improve fixed-count loops

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/CalculationsShouldNotOverflowBase.cs
- analyzers/src/SonarAnalyzer.VisualBasic/SymbolicExecution/Roslyn/CalculationsShouldNotOverflow.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/CalculationsShouldNotOverflow.vb
> S3949: Implement ShouldExecute for VB.NET

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Binary.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.LearnConstraint.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Loops.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Monitor.Loops.vb
Improvement to #7203
This is just a proof of concept without any polish.
> SE: Improve NumberConstraint learning from existing constraint

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Binary.Arithmetic.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Binary.cs
Part of https://github.com/SonarSource/sonar-dotnet/issues/7267
> SE: Add DivisionOperation

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Binary.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IsPattern.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Binary.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.PatternMatching.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.cs
> Fix S2259 FP: Conditional access checked for bool

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Binary.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Binary.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Invocation.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.cs
Fixes #7111
UTs fails due to red master, rebase will be needed
> SE: Concatenate string expression returns non-null string

- analyzers/tests/SonarAnalyzer.UnitTest/Rules/InsteadOfAnyTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/InsteadOfAny.EntityFramework.cs
> S6605: Add FP repro for #7286

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Binary.Arithmetic.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Binary.cs
> SE: Improve XOROperation

- analyzers/src/SonarAnalyzer.CSharp/Rules/InvalidCastToInterface.cs
- analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/InvalidCastToInterface.cs
- analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Sonar/Analyzers/InvalidCastToInterfaceSymbolicExecution.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/InvalidCastToInterfaceBase.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/InvalidCastToInterfaceTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/InvalidCastToInterface.CSharp10.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/InvalidCastToInterface.CSharp8.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/InvalidCastToInterface.CSharp9.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/InvalidCastToInterface.cs
> Migrate S1944: Scaffold the rule for the new SE

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Checks/ConstantCheck.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/CompoundAssignment.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Conversion.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Invocation.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/ObjectCreation.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/References.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SymbolicContext.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/SymbolicContextTest.cs
> SE: Add SymbolicContext.SetOperationValue

- analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/ObjectsShouldNotBeDisposedMoreThanOnce.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/ObjectsShouldNotBeDisposedMoreThanOnceBase.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ObjectsShouldNotBeDisposedMoreThanOnce.CSharp9.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ObjectsShouldNotBeDisposedMoreThanOnce.cs
> Migrate S3966: Implement ShouldExecute

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Extensions/IOperationExtensions.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/EmptyCollectionsShouldNotBeEnumeratedBase.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.cs
> Migrate S4158: Support Array Creation

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnusedReturnValue.cs
> S3241: Add FP repro for #7429 

- analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/ObjectsShouldNotBeDisposedMoreThanOnce.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/KnownMethods.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/ObjectsShouldNotBeDisposedMoreThanOnceBase.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ObjectsShouldNotBeDisposedMoreThanOnce.cs
```
public static void DisposeMultipleTimes(MyClass myclass)
{
Dispose(myclass); // AD0001 when trying to get the invocation.Instance
Dispose(myclass); 
}
```
> Fix S3966: AD0001 when inspecting Dispose that is not invoked from an instance.

- analyzers/its/expected/Nancy/Nancy--net452-S4158.json
- analyzers/its/expected/Nancy/Nancy--netstandard2.0-S4158.json
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/EmptyCollectionsShouldNotBeEnumeratedBase.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.CSharp8.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.cs
>  Migrate S4158: Support Object Initializers

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Extensions/IOperationExtensions.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Argument.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/EmptyCollectionsShouldNotBeEnumeratedBase.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.cs
> S4158 FP: Collection filled using delegates

- analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.vb
> Migrate S4158: Implement ShouldExecute

- analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarAnalysisContext.cs
- analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarAnalysisContextBase.cs
- analyzers/tests/SonarAnalyzer.UnitTest/AnalysisContext/SonarAnalysisContextBaseTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/AnalysisContext/SonarAnalysisContextTest.Register.cs
- analyzers/tests/SonarAnalyzer.UnitTest/AnalysisContext/SonarAnalysisContextTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/AnalysisScaffolding.cs
> HasMatchingScope should not allocate a new delegate on every call

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/EmptyCollectionsShouldNotBeEnumeratedBase.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.cs
Fix FP introduced in #7427 
Rebase will be needed
> Migrate S4158: Do not report on method references

- analyzers/its/sources/ManuallyAddedNoncompliantIssues.CS/IntentionalFindings/S4635.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/StringOffsetMethods.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/StringOffsetMethods.CSharp11.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/StringOffsetMethods.cs
Update message after the rule title update https://github.com/SonarSource/rspec/pull/2197
> Update message of S4635

- analyzers/rspec/cs/S122.html
- analyzers/rspec/cs/S2198.html
- analyzers/rspec/cs/S2198.json
- analyzers/rspec/cs/S2583.json
- analyzers/rspec/cs/S2681.html
- analyzers/rspec/cs/S2761.html
- analyzers/rspec/cs/S3451.html
- analyzers/rspec/cs/S3776.html
- analyzers/rspec/cs/S3776.json
- analyzers/rspec/cs/S3966.html
- analyzers/rspec/cs/S4487.html
- analyzers/rspec/cs/S4586.html
- analyzers/rspec/cs/S4586.json
- analyzers/rspec/cs/S4635.json
- analyzers/rspec/vbnet/S122.html
- analyzers/rspec/vbnet/S2761.html
- analyzers/rspec/vbnet/S3776.html
- analyzers/rspec/vbnet/S3776.json
- analyzers/rspec/vbnet/S3966.html
- analyzers/rspec/vbnet/S4158.html
- analyzers/rspec/vbnet/S4277.html
- analyzers/rspec/vbnet/S4586.html
- analyzers/rspec/vbnet/S4586.json
- analyzers/src/SonarAnalyzer.CSharp/sonarpedia.json
- analyzers/src/SonarAnalyzer.VisualBasic/sonarpedia.json
> Update RSPEC before 9.4 release

- pom.xml
- sonar-csharp-plugin/pom.xml
- sonar-dotnet-shared-library/pom.xml
- sonar-vbnet-plugin/pom.xml
Refactored version of #7441, #7442, #7443
> Bump guava from 31.1-jre to 32.0.0-jre

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/EmptyCollectionsShouldNotBeEnumeratedBase.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.cs
> Minor improvements for S4158

- analyzers/its/expected/akka.net/Akka.Remote--netstandard2.0-S2259.json
- analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/SymbolicExecutionRunner.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/SymbolicExecutionRunnerTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.CSharp8.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.CSharp9.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyNullableValueAccess.CSharp9.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyNullableValueAccess.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Monitor.Conditions.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.CSharp8.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.CSharp9.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ObjectsShouldNotBeDisposedMoreThanOnce.CSharp8.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ObjectsShouldNotBeDisposedMoreThanOnce.CSharp9.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Sonar/ConditionEvaluatesToConstant.CSharp8.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Sonar/EmptyCollectionsShouldNotBeEnumerated.CSharp8.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Sonar/EmptyCollectionsShouldNotBeEnumerated.CSharp9.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Sonar/EmptyNullableValueAccess.CSharp9.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Sonar/InitializationVectorShouldBeRandom.CSharp9.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Sonar/InvalidCastToInterface.CSharp9.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Sonar/InvalidCastToInterface.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Sonar/NullPointerDereference.CSharp8.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Sonar/NullPointerDereference.CSharp9.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Sonar/ObjectsShouldNotBeDisposedMoreThanOnce.CSharp9.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Sonar/ObjectsShouldNotBeDisposedMoreThanOnce.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Sonar/RestrictDeserializedTypes.CSharp9.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Sonar/RestrictDeserializedTypes.cs
Fixes #7469
Runs also for local functions in Top-level statements
> SE: Run for local functions

- analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/DoNotHardcodeCredentials.cs
- analyzers/src/SonarAnalyzer.CSharp/Trackers/CSharpInvocationTracker.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/DoNotHardcodeCredentialsBase.cs
- analyzers/src/SonarAnalyzer.Common/Trackers/InvocationTracker.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Rules/Hotspots/DoNotHardcodeCredentials.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Trackers/VisualBasicInvocationTracker.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/Hotspots/DoNotHardcodeCredentialsTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/DoNotHardcodeCredentials.SecureString.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/DoNotHardcodeCredentials.SecureString.vb
> Fix S2068 FN: add support for SecureString

- analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/UnsafeCodeBlocks.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/UnsafeCodeBlocks.cs
> Improve S6640: Support local functions

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Sonar/ConditionEvaluatesToConstant.cs
> S2589: Add FP repro for #7489

- analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/UnsafeCodeBlocks.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/UnsafeCodeBlocks.cs
> Improve S6640: Support fields, properties and delegates

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ObjectsShouldNotBeDisposedMoreThanOnce.cs
> S3966: Add FP repro for #7497

- analyzers/src/SonarAnalyzer.CSharp/Extensions/SyntaxNodeExtensions.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/SymbolicExecutionRunner.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/SymbolicExecutionRunnerTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/CalculationsShouldNotOverflow.CSharp9.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.CSharp9.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyNullableValueAccess.CSharp9.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.CSharp9.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ObjectsShouldNotBeDisposedMoreThanOnce.CSharp9.cs
> SE: Run for Top-Level statements

- analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/ClearTextProtocolsAreSensitive.cs
- analyzers/src/SonarAnalyzer.Common/Extensions/INamespaceSymbolExtensions.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Extensions/INamespaceSymbolExtensionsTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/Hotspots/ClearTextProtocolsAreSensitiveTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/ClearTextProtocolsAreSensitive.cs
> FP S5332: Improve detection of namespace uris

- analyzers/its/expected/akka.net/Akka--netstandard2.0-S6354.json
- analyzers/its/expected/akka.net/Akka.Persistence.Sql.Common--netstandard2.0-S6354.json
- analyzers/its/expected/akka.net/Akka.Remote--netstandard2.0-S6354.json
- analyzers/src/SonarAnalyzer.CFG/Helpers/CSharpSyntaxHelper.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/UseTestableTimeProvider.cs
- analyzers/src/SonarAnalyzer.Common/Rules/UseTestableTimeProviderBase.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Rules/UseTestableTimeProvider.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UseTestableTimeProvider.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UseTestableTimeProvider.vb
> Fix S6354 FP: Do not report on XML crefs and nameof

- sonar-csharp-plugin/pom.xml
> Bump plugin size (LAYC side effect)

- analyzers/src/SonarAnalyzer.CSharp/Rules/UseCharOverloadOfStringMethodsCodeFix.cs
- analyzers/src/SonarAnalyzer.Common/Rules/UseCharOverloadOfStringMethodsBase.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/UseCharOverloadOfStringMethodsTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UseCharOverloadOfStringMethods.Fixed.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UseCharOverloadOfStringMethods.ToFix.cs
> Rule S6610: implement CodeFix

- analyzers/its/expected/Ember-MM/EmberAPI-{208AA35E-C6AE-4D2D-A9DD-B6EFD19A4279}-S6563.json
- analyzers/its/expected/Ember-MM/generic.EmberCore.Extractor-{B413DEAF-4FDC-416A-B3E0-968C1C8F3F83}-S6563.json
- analyzers/its/expected/Ember-MM/scraper.EmberCore.XML-{E567C031-1F7B-4637-9B3A-806988DE50CF}-S6563.json
- analyzers/its/expected/Nancy/Nancy--net452-S6563.json
- analyzers/its/expected/Nancy/Nancy--netstandard2.0-S6563.json
- analyzers/its/expected/Nancy/Nancy.Authentication.Forms--net452-S6563.json
- analyzers/its/expected/Nancy/Nancy.Authentication.Forms--netstandard2.0-S6563.json
- analyzers/its/expected/Nancy/Nancy.ViewEngines.Spark--net452-S6563.json
- analyzers/its/expected/Net5/jsonserializerrecords-38409230-12D6-462B-BFAC-33B3491365B5-net5.0-S6563.json
- analyzers/its/expected/Net5/recordswithstatichelper-541512C1-D79D-48B4-AE0B-D9A643E16D1F-net5.0-S6563.json
- analyzers/its/expected/akka.net/Akka--netstandard2.0-S6563.json
- analyzers/its/expected/akka.net/Akka.Cluster.Sharding--netstandard2.0-S6563.json
- analyzers/its/expected/akka.net/Akka.Streams--netstandard2.0-S6563.json
- analyzers/its/expected/akka.net/PersistenceBenchmark--net471-S6563.json
- analyzers/rspec/cs/S6563.html
- analyzers/rspec/cs/S6563.json
- analyzers/rspec/vbnet/S6563.html
- analyzers/rspec/vbnet/S6563.json
- analyzers/src/SonarAnalyzer.CFG/ShimLayer/SyntaxKindEx.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/DoNotUseDateTimeNow.cs
- analyzers/src/SonarAnalyzer.Common/Rules/DoNotUseDateTimeNowBase.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Rules/DoNotUseDateTimeNow.cs
- analyzers/tests/SonarAnalyzer.UnitTest/PackagingTests/RuleTypeMappingCS.cs
- analyzers/tests/SonarAnalyzer.UnitTest/PackagingTests/RuleTypeMappingVB.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/DoNotUseDateTimeNowTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DoNotUseDateTimeNow.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DoNotUseDateTimeNow.vb
> New Rule S6563: Use UTC when recording instants

- README.md
Fix HasCorrectRuleCount_CS test is failing on master
> Bump C# rule count

- analyzers/src/SonarAnalyzer.CSharp/Rules/UseUnixEpochCodeFix.cs
- analyzers/src/SonarAnalyzer.Common/Rules/UseUnixEpochBase.cs
- analyzers/src/SonarAnalyzer.Common/Rules/UseUnixEpochCodeFixBase.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Rules/UseUnixEpochCodeFix.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/UseUnixEpochTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UseUnixEpoch.CSharp9.Fixed.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UseUnixEpoch.CSharp9.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UseUnixEpoch.Fixed.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UseUnixEpoch.Fixed.vb
> Adds quickfix for rule S6588

- analyzers/rspec/cs/S1048.html
- analyzers/rspec/cs/S1048.json
- analyzers/rspec/cs/S1848.html
- analyzers/rspec/cs/S1848.json
- analyzers/rspec/cs/S3984.html
- analyzers/rspec/cs/S3984.json
- analyzers/rspec/cs/S4260.html
- analyzers/rspec/cs/S6588.html
- analyzers/rspec/cs/S6588.json
- analyzers/rspec/cs/S6610.json
- analyzers/rspec/vbnet/S1048.html
- analyzers/rspec/vbnet/S1048.json
- analyzers/rspec/vbnet/S4260.html
- analyzers/rspec/vbnet/S6588.html
- analyzers/rspec/vbnet/S6588.json
- analyzers/src/SonarAnalyzer.CSharp/sonarpedia.json
- analyzers/src/SonarAnalyzer.VisualBasic/sonarpedia.json
> Update RSPECs as part of the LayC second migration (batch#4)

- analyzers/rspec/cs/S3363.html
- analyzers/rspec/cs/S6580.html
- analyzers/rspec/vbnet/S3363.html
- analyzers/rspec/vbnet/S6580.html
Updates for minor RSPEC changes in S3363 and S6580.
> Update RSPEC for datetime rules

- analyzers/rspec/cs/S2053.html
- analyzers/rspec/cs/S2123.html
- analyzers/rspec/cs/S2123.json
- analyzers/rspec/cs/S2259.html
- analyzers/rspec/cs/S2995.html
- analyzers/rspec/cs/S3453.html
- analyzers/rspec/cs/S3603.html
- analyzers/rspec/cs/S3887.html
- analyzers/rspec/cs/S3927.html
- analyzers/rspec/vbnet/S1048.html
- analyzers/rspec/vbnet/S2259.html
- analyzers/rspec/vbnet/S3453.html
- analyzers/rspec/vbnet/S3603.html
- analyzers/rspec/vbnet/S3927.html
- analyzers/src/SonarAnalyzer.CSharp/sonarpedia.json
- analyzers/src/SonarAnalyzer.VisualBasic/sonarpedia.json
> Update RSPECs as part of the LayC second migration (batch#6)

- analyzers/rspec/cs/S1751.html
- analyzers/rspec/cs/S1751.json
- analyzers/rspec/cs/S5445.html
- analyzers/rspec/vbnet/S1751.html
- analyzers/rspec/vbnet/S1751.json
- analyzers/rspec/vbnet/S5445.html
- analyzers/src/SonarAnalyzer.CSharp/sonarpedia.json
- analyzers/src/SonarAnalyzer.VisualBasic/sonarpedia.json
> Update RSPECs as part of the LayC second migration (batch#7)

- analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/HashesShouldHaveUnpredictableSalt.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/HashesShouldHaveUnpredictableSaltBase.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/HashesShouldHaveUnpredictableSaltTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/HashesShouldHaveUnpredictableSalt.CSharp10.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/HashesShouldHaveUnpredictableSalt.CSharp11.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/HashesShouldHaveUnpredictableSalt.CSharp8.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/HashesShouldHaveUnpredictableSalt.CSharp9.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/HashesShouldHaveUnpredictableSalt.cs
> Migrate S2053: Scaffold the rule for the new SE

- analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/RestrictDeserializedTypes.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/RestrictDeserializedTypesBase.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/RestrictDeserializedTypesTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/RestrictDeserializedTypes.CSharp8.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/RestrictDeserializedTypes.CSharp9.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/RestrictDeserializedTypes.JavaScriptSerializer.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/RestrictDeserializedTypes.LosFormatter.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/RestrictDeserializedTypes.cs
> Migrate S5773: Scaffold the rule for the new SE

- its/pom.xml
- pom.xml
- sonar-csharp-plugin/pom.xml
- sonar-dotnet-shared-library/pom.xml
- sonar-vbnet-plugin/pom.xml
Part of #4223
~~Rebase will be needed, commit `Squash greg/remove-bulk-delete` doesn't need a review~~
> Bump jUnit from 4.13.2 to 5.9.2

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.cs
> Reproducer for #7582 (S4158 FP)

- its/src/test/java/com/sonar/it/csharp/Tests.java
- its/src/test/java/com/sonar/it/shared/OrchestratorState.java
- its/src/test/java/com/sonar/it/shared/Tests.java
- its/src/test/java/com/sonar/it/vbnet/Tests.java
- its/src/test/resources/junit-platform.properties
Fixes #7557
There's cherrypicked commit `ITs: Fix race condition in MetricsIncludeHeaderCommentTest` that doesn't need a review.
> Java ITs: Run in parallel

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Constraints/ByteCollectionConstraint.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/SymbolicConstraintTest.cs
Cleanup for earlier ignored comment.
> Cleanup: remove Opposite implementation

- analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/HashesShouldHaveUnpredictableSalt.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/HashesShouldHaveUnpredictableSalt.CSharp9.cs
Fixes #7558 
A second attempt at [this PR](https://github.com/SonarSource/sonar-dotnet/pull/7579), after it was closed by Github.
> Migrate S2053: Implement ShouldExecute (C#)

- pom.xml
Recreation of #7602 that doesn't seem to get CI started due to a weird error
> Bump sonar.version from 9.17.0.587 to 10.0.0.695

- analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/InitializationVectorShouldBeRandom.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/InitializationVectorShouldBeRandomTest.cs
Fixes #7559
Do not review the commit `rebase-squash`.
> Migrate S3329: Implement ShouldExecute

- analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Extensions/IOperationExtensions.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/HashesShouldHaveUnpredictableSaltBase.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/HashesShouldHaveUnpredictableSaltTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/HashesShouldHaveUnpredictableSalt.CSharp8.NetCore.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/HashesShouldHaveUnpredictableSalt.CSharp8.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/HashesShouldHaveUnpredictableSalt.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/HashesShouldHaveUnpredictableSalt.vb
> Fix S2053 FN: Encoding.GetBytes

- analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/SymbolicExecutionRunner.cs
- analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/RestrictDeserializedTypes.cs
- analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Sonar/Analyzers/RestrictDeserializedTypes.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Constraints/SerializationConstraint.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Extensions/IOperationExtensions.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/RestrictDeserializedTypesBase.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SymbolicRuleCheck.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/RestrictDeserializedTypesTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Sonar/Constraints/SerializationConstraintTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/RestrictDeserializedTypes.CSharp8.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/RestrictDeserializedTypes.CSharp9.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/RestrictDeserializedTypes.JavaScriptSerializer.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/RestrictDeserializedTypes.LosFormatter.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/RestrictDeserializedTypes.cs
Step 2 of https://github.com/SonarSource/sonar-dotnet/issues/7564
> Migrate S5773: Implement the rule in the new SE

- analyzers/its/expected/Ember-MM/scraper.EmberCore-{EF6A550E-DD76-4F4D-8250-8598140F828B}-S5773.json
- analyzers/src/SonarAnalyzer.VisualBasic/SymbolicExecution/Roslyn/RestrictDeserializedTypes.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/RestrictDeserializedTypes.JavaScriptSerializer.vb
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/RestrictDeserializedTypes.LosFormatter.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/RestrictDeserializedTypes.LosFormatter.vb
Part of #7565 
Add VB test cases for LosFormatter and JavascriptSerializer.
> S5773: Additional VB test cases

- analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/RestrictDeserializedTypes.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/RestrictDeserializedTypesBase.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/RestrictDeserializedTypes.CSharp9.cs
> Improve S5773: Support secondary issue location for partial methods

- analyzers/rspec/cs/S104.html
- analyzers/rspec/cs/S1751.html
- analyzers/rspec/cs/S3329.json
- analyzers/rspec/cs/S4143.html
- analyzers/rspec/cs/S6563.json
- analyzers/rspec/vbnet/S104.html
- analyzers/rspec/vbnet/S3329.json
- analyzers/rspec/vbnet/S4143.html
- analyzers/rspec/vbnet/S6563.json
- analyzers/src/SonarAnalyzer.CSharp/sonarpedia.json
- analyzers/src/SonarAnalyzer.VisualBasic/sonarpedia.json
> Update RSPEC before 9.6 release

- analyzers/src/SonarAnalyzer.CSharp/Rules/UnusedStringBuilder.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnusedStringBuilder.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnusedStringBuilder.vb
> Fix S3063 FP: StringBuilder used in concatenation

- analyzers/tests/SonarAnalyzer.UnitTest/Rules/DisposableNotDisposedTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DisposableNotDisposed.ILogger.cs
> S2930: Add FN repro for #7635

- analyzers/src/SonarAnalyzer.CSharp/Rules/UnusedPrivateMember.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/UnusedPrivateMemberTest.Fields.cs
> Fix S1144 FP: Unused fields in class with StructLayout

- analyzers/src/SonarAnalyzer.CSharp/Rules/InsteadOfAny.cs
- analyzers/src/SonarAnalyzer.Common/Rules/InsteadOfAnyBase.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Rules/InsteadOfAny.cs
Left over from the change in #7671
> Remove unused members in S6605

- analyzers/tests/SonarAnalyzer.UnitTest/Rules/UnnecessaryUsingsTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnnecessaryUsings.InheritedPropertyBase.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnnecessaryUsings.InheritedPropertyChild.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnnecessaryUsings.InheritedPropertyUsage.cs
Add false negative repro for #7694
> S1128: Add FN repro for #7694

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.CSharp9.cs
Add repro for https://github.com/SonarSource/sonar-dotnet/issues/7665
> S2259: Add FP repro for #7665

- analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/SymbolicExecutionRunner.cs
- analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/ConditionEvaluatesToConstantBase.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SymbolicRuleCheck.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/ConditionEvaluatesToConstantTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp7.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp8.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp9.TopLevelStatements.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp9.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Tests/VerifierTest.cs
> Migrate S2583/S2589: Implement analyzer

- analyzers/its/expected/akka.net/Akka--netstandard2.0-S4023.json
- analyzers/its/expected/akka.net/Akka.Cluster--netstandard2.0-S4023.json
- analyzers/its/expected/akka.net/Akka.DistributedData--netstandard2.0-S4023.json
- analyzers/its/expected/akka.net/Akka.Persistence--netstandard2.0-S4023.json
- analyzers/its/expected/akka.net/Akka.Remote--netstandard2.0-S4023.json
- analyzers/its/expected/akka.net/Akka.Streams--netstandard2.0-S4023.json
- analyzers/src/SonarAnalyzer.CSharp/Rules/InterfacesShouldNotBeEmpty.cs
- analyzers/src/SonarAnalyzer.Common/Extensions/ITypeParameterSymbolExtensions.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/InterfacesShouldNotBeEmpty.cs
Fixes #7633
RSpec changes: https://github.com/SonarSource/rspec/pull/2691
Maerging should go along with the RSpec change.
> Fix S4023 FP: Interfaces that provide type parameters from base interface

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/ConditionEvaluatesToConstantBase.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SymbolicRuleCheck.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp7.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Tests/VerifierTest.cs
> SE: Migrate S2583/S2589 - Implement issue messages

- analyzers/rspec/cs/S100.json
- analyzers/rspec/cs/S1135.html
- analyzers/rspec/cs/S125.json
- analyzers/rspec/cs/S2190.html
- analyzers/rspec/cs/S2995.html
- analyzers/rspec/cs/S3456.html
- analyzers/rspec/cs/S3925.html
- analyzers/rspec/cs/S4023.html
- analyzers/rspec/cs/S6422.html
- analyzers/rspec/vbnet/S1135.html
- analyzers/src/SonarAnalyzer.CSharp/sonarpedia.json
- analyzers/src/SonarAnalyzer.VisualBasic/sonarpedia.json
> Update RSPEC before 9.7 release 

- analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp8.cs
> Migrate S2583/S2589: Implement ShouldExecute

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/LoopsAndLinq.CSharp11.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/LoopsAndLinq.cs
Add repro for https://github.com/SonarSource/sonar-dotnet/issues/7730
Add repro for https://github.com/SonarSource/sonar-dotnet/issues/7776 (extracted from 7730)
> S3267: Add FP repro for #7730 and FN repro for #7776

- analyzers/tests/SonarAnalyzer.UnitTest/SonarAnalyzer.UnitTest.csproj
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnusedPrivateMember.cshtml
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnusedPrivateMember.razor
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnusedPrivateMember.vbhtml
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/DiagnosticVerifier.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/ProjectBuilder.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Razor/EmptyProject/EmptyProject.csproj
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Razor/EmptyProject/_Imports.razor
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Tests/ProjectBuilderTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Tests/VerifierBuilderTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Tests/VerifierTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Verifier.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/VerifierBuilder.cs
- analyzers/tests/SonarAnalyzer.UnitTest/packages.lock.json
> Extend the test infrastructure to build and compile razor projects

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Dummy.cshtml
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Dummy.razor
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/DiagnosticVerifier.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/IssueLocationCollector.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Tests/DummyAnalyzerWithLocationMapping.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Tests/IssueLocationCollectorTest.GetExpectedIssueLocations.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Tests/IssueLocationCollectorTest.GetPreciseIssueLocations.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Tests/VerifierTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Verifier.cs
> Update the Verifier to read Noncompliant comments from .cshtml and .razor files

- analyzers/src/SonarAnalyzer.CSharp/Rules/Utilities/TokenTypeAnalyzer.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/TokenTypeAnalyzerTest.Classifier.cs
> UtilityAnalyzer: Wrong classifcation for nullable types

- analyzers/src/SonarAnalyzer.CSharp/Rules/Utilities/TokenTypeAnalyzer.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/TokenTypeAnalyzerTest.Classifier.cs
Part of #7808
Part https://github.com/SonarSource/sonar-dotnet/issues/7808#issuecomment-1682064614
> UtilityAnalyzer: Wrong classifcations for type parameter

- analyzers/src/SonarAnalyzer.CSharp/Rules/Utilities/TokenTypeAnalyzer.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/TokenTypeAnalyzerTest.Classifier.cs
Part of #7808
This part: https://github.com/SonarSource/sonar-dotnet/issues/7808#issuecomment-1682048135
> UtilityAnalyzer: Wrong classifcations for tuple elements

- analyzers/src/SonarAnalyzer.CSharp/Rules/Utilities/TokenTypeAnalyzer.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/TokenTypeAnalyzerTest.Classifier.cs
Part of #7808
Part https://github.com/SonarSource/sonar-dotnet/issues/7808#issuecomment-1682055394
> UtilityAnalyzer: Wrong classifications for AliasQualifiedNames 

- analyzers/src/SonarAnalyzer.CFG/ShimLayer/SyntaxKindEx.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/Utilities/TokenTypeAnalyzer.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/TokenTypeAnalyzerTest.Classifier.cs
> UtilityAnalyzer: Optimize hot-path of TokenType anaylzer

- analyzers/src/SonarAnalyzer.CSharp/Rules/Utilities/TokenTypeAnalyzer.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/TokenTypeAnalyzerTest.Classifier.cs
Part of https://github.com/SonarSource/sonar-dotnet/issues/7808
This part https://github.com/SonarSource/sonar-dotnet/issues/7808#issuecomment-1683433607
> UtilityAnalyzer: Wrong classifications: ref types

- analyzers/src/SonarAnalyzer.CSharp/Rules/Utilities/TokenTypeAnalyzer.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/TokenTypeAnalyzerTest.Classifier.cs
Part of #7808
This part https://github.com/SonarSource/sonar-dotnet/issues/7808#issuecomment-1683459816
> UtilityAnalyzer: Wrong classifications: value in MemberAccess

- analyzers/src/SonarAnalyzer.CSharp/Rules/Utilities/TokenTypeAnalyzer.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/TokenTypeAnalyzerTest.Classifier.cs
Part of #7808 
This part https://github.com/SonarSource/sonar-dotnet/issues/7808#issuecomment-1683448838
> UtilityAnalyzer: Wrong classifications: value in nameof

- analyzers/src/SonarAnalyzer.CSharp/Rules/Utilities/TokenTypeAnalyzer.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/TokenTypeAnalyzerTest.Classifier.cs
> Fix classification for global namespace parts in method invocation

- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Tests/IssueLocationCollectorTest.GetExpectedBuildErrors.cs
> Test infrastructure: Add UTs for ignored build errors

- analyzers/src/SonarAnalyzer.CSharp/Rules/ClassAndMethodName.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/NativeMethodsShouldBeWrapped.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/UnusedPrivateMember.cs
- analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarAnalysisContextBase.cs
- analyzers/src/SonarAnalyzer.Common/DiagnosticAnalyzer/SonarDiagnosticAnalyzer.cs
- analyzers/src/SonarAnalyzer.Common/Extensions/SyntaxTreeExtensions.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/GeneratedCodeRecognizer.cs
- analyzers/src/SonarAnalyzer.Common/Rules/Utilities/FileMetadataAnalyzerBase.cs
- analyzers/src/SonarAnalyzer.Common/Rules/Utilities/UtilityAnalyzerBase.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Helpers/GeneratedCodeRecognizerTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/EnvironmentVariableScope.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Tests/VerifierTest.cs
- azure-pipelines.yml
Fixes https://github.com/SonarSource/sonar-dotnet/issues/7818
> Make it possible to disable razor analysis with the help of an environment variable

- analyzers/src/SonarAnalyzer.VisualBasic/Rules/MethodsShouldNotHaveTooManyLines.cs
https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=sonaranalyzer-dotnet&open=AYon5_Ehmw8zdopbp6LF
> Fix S2583 raised in our code base

- docs/coding-style.md
Capture result of https://trello.com/c/UMlcuxKm/44-nullable-context-define-a-process-to-enable-it-in-our-code-base
> Coding style: nullable context

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Binary.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/BranchingProcessor.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IsNull.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IsPattern.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IsType.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/References.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SymbolicContext.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Loops.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/SymbolicCheckListTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/SymbolicContextTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp8.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Monitor.Loops.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Monitor.Loops.vb
Reverts #7797
There are severe issues with nested for-loops and do-while-loops. I have a fix planned, but revert is the quick solution for now.
> Revert "Fix S2589 FN: Infinite for-loop (#7797)"

- its/src/test/java/com/sonar/it/csharp/CasingAppTest.java
- its/src/test/java/com/sonar/it/vbnet/NoSonarTest.java
- the order of the issues does not matter
> Fix flaky integration tests

- analyzers/src/SonarAnalyzer.Common/Common/AnalyzerLanguage.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Common/AnalyzerLanguageTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/SymbolReferenceAnalyzerTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Utilities/SymbolReferenceAnalyzer/Razor.razor
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Utilities/SymbolReferenceAnalyzer/ToDo.cs
> Add .razor file unit test for SymbolReferenceAnalyzer

- analyzers/its/expected/Automapper/AutoMapper--net461-S112.json
- analyzers/its/expected/Automapper/AutoMapper--netstandard2.0-S112.json
- analyzers/its/expected/Net5/Net5--net5.0-S112.json
- analyzers/its/expected/akka.net/Akka.Benchmarks--netcoreapp3.1-S112.json
- analyzers/src/SonarAnalyzer.CSharp/Rules/ThrowReservedExceptions.cs
- analyzers/src/SonarAnalyzer.Common/Rules/ThrowReservedExceptionsBase.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Rules/ThrowReservedExceptions.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/ThrowReservedExceptionsTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ThrowReservedExceptions.CSharp8.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ThrowReservedExceptions.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ThrowReservedExceptions.vb
Fixes #7910
Review per commit should be easier due to the cleanup phase
> Fix S112 FN: When using null-coalesce operator

- analyzers/src/SonarAnalyzer.CFG/ShimLayer/SyntaxKindEx.cs
- analyzers/src/SonarAnalyzer.Common/Extensions/SyntaxTreeExtensions.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/SyntaxNodeExtensions.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Extensions/SyntaxNodeExtensionsTest.cs
> Retrieve file path from pragma checksum

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/EmptyCollectionsShouldNotBeEnumeratedBase.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.cs
```
var sb = new StringBuilder();
sb.Clear();
sb.Clear();    // Noncompliant FP
```
> SE: Do not learn CollectionConstraints for untracked collections

- its/src/test/java/com/sonar/it/csharp/UnitTestProjectTypeProbingTest.java
- the issues are not always imported in the same order
> Fix flaky unit test

- analyzers/src/SonarAnalyzer.CSharp/Metrics/CSharpExecutableLinesMetric.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/MetricsAnalyzerTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Utilities/MetricsAnalyzer/Component.razor
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Utilities/MetricsAnalyzer/Razor.razor
Part of #7893.
Fix component issues identified during peach validation.
> Add executable lines test coverage and solve peach validation issue

- analyzers/src/SonarAnalyzer.CSharp/Metrics/CSharpMetrics.cs
- analyzers/src/SonarAnalyzer.Common/Metrics/MetricsBase.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/MetricsAnalyzerTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Utilities/MetricsAnalyzer/Razor.razor
> .razor: class count, ignore generated classes

- analyzers/src/SonarAnalyzer.CSharp/Metrics/CSharpMetrics.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/MetricsAnalyzerTest.cs
> .razor: statement count, consider only mapped statements

- analyzers/src/SonarAnalyzer.CSharp/Metrics/CSharpMetrics.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/MetricsAnalyzerTest.cs
>  .razor: functions count, ignore generated function

- analyzers/src/SonarAnalyzer.Common/Helpers/SonarLintXmlReader.cs
- analyzers/tests/SonarAnalyzer.UnitTest/AnalysisContext/SonarAnalysisContextBaseTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Helpers/SonarLintXmlReaderTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Helpers/SonarLintXmlTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestResources/SonarLintXml/All_properties_cs/SonarLint.xml
- analyzers/tests/SonarAnalyzer.UnitTest/TestResources/SonarLintXml/PropertiesCSharpTrueVbnetFalse/SonarLint.xml
- sonar-csharp-plugin/src/main/java/org/sonar/plugins/csharp/CSharpLanguageConfiguration.java
- sonar-csharp-plugin/src/main/java/org/sonar/plugins/csharp/CSharpPropertyDefinitions.java
- sonar-csharp-plugin/src/test/java/org/sonar/plugins/csharp/CSharpLanguageConfigurationTest.java
- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/AbstractLanguageConfiguration.java
- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/AbstractPropertyDefinitions.java
> Add sonar.cs.analyzeRazorCode parameter

- sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/CoverageReportImportSensor.java
- sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/CoverageReportImportSensorTest.java
> Fix the coverage import for .razor files

- analyzers/src/SonarAnalyzer.CSharp/Rules/CollectionPropertiesShouldBeReadOnly.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/CollectionPropertiesShouldBeReadOnlyTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CollectionPropertiesShouldBeReadOnly.razor
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CollectionPropertiesShouldBeReadOnly.razor.cs
> Fix S4004 FP: The rule should not raise for properties with Parameter attribute

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnconditionalJumpStatement.cs
> Add FP repro for S1751

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/BooleanLiteralUnnecessary.Fixed.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/BooleanLiteralUnnecessary.cs
> Add quickfix error repro for S1125

- analyzers/src/SonarAnalyzer.CSharp/Rules/DoNotMarkEnumsWithFlags.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/DoNotMarkEnumsWithFlagsTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DoNotMarkEnumsWithFlags.cs
Repro for #7991 + cleanup (review it by commit)
> Add reproducer for #7991

- docs/coding-style.md
Implements https://trello.com/c/CayAtlNb/62-convention-helper-in-class-name
> Code conventions: improve "Naming conventions" section

- analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarAnalysisContextBase.cs
- analyzers/src/SonarAnalyzer.Common/Extensions/SyntaxTreeExtensions.cs
- analyzers/tests/SonarAnalyzer.UnitTest/AnalysisContext/SonarAnalysisContextBaseTest.ShouldAnalyzeTree.cs
> Skip .razor files if they are unchanged

- analyzers/its/expected/Net8/Net8--net8.0-S109.json
- analyzers/its/expected/Net8/Net8--net8.0-S1144.json
- analyzers/its/expected/Net8/Net8--net8.0-S1451.json
- analyzers/its/expected/Net8/Net8--net8.0-S1481.json
- analyzers/its/expected/Net8/Net8--net8.0-S2325.json
- analyzers/its/expected/Net8/Net8--net8.0-S3052.json
- analyzers/its/expected/Net8/Net8--net8.0-S3059.json
- analyzers/its/expected/Net8/Net8--net8.0-S3604.json
- analyzers/its/expected/Net8/Net8--net8.0-S3898.json
- analyzers/its/expected/Net8/Net8--net8.0-S3990.json
- analyzers/its/expected/Net8/Net8--net8.0-S3992.json
- analyzers/its/expected/Net8/Net8--net8.0-S4055.json
- analyzers/its/regression-test.ps1
- analyzers/its/sources/Net8/Net8.sln
- analyzers/its/sources/Net8/Net8/Net8.csproj
- analyzers/its/sources/Net8/Net8/Program.cs
- analyzers/its/sources/Net8/Net8/features/AliasAnyType.cs
- analyzers/its/sources/Net8/Net8/features/CollectionExpressions.cs
- analyzers/its/sources/Net8/Net8/features/DefaultLambdaParameters.cs
- analyzers/its/sources/Net8/Net8/features/InlineArrays.cs
- analyzers/its/sources/Net8/Net8/features/PrimaryConstructor.cs
- analyzers/its/sources/Net8/global.json
- analyzers/its/update-expected.ps1
> Add ITs with C# 12 features on .Net 8 runtime

- docs/coding-style.md
Implements https://trello.com/c/qWdOqXLK/53-convention-acceptable-use-of-is-var
> Code conventions: acceptable use of "is var o"

- analyzers/rspec/vbnet/S1301.html
- analyzers/src/SonarAnalyzer.CSharp/sonarpedia.json
- analyzers/src/SonarAnalyzer.VisualBasic/sonarpedia.json
> Update rspec before release

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
> S2583: Add reproducer for 8080

- docs/coding-style.md
Implements https://trello.com/c/liKnkZ8K/55-convention-indentation-of-lines-starting-with-logical-operators
> Code conventions: clarify indentation rules

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp8.cs
> S2589/S2583: Add reproducer for #8094

- analyzers/rspec/cs/S1854.json
- analyzers/rspec/cs/S3241.html
- analyzers/rspec/cs/S3776.html
- analyzers/rspec/cs/S5773.html
- analyzers/rspec/vbnet/S3776.html
- analyzers/rspec/vbnet/S5773.html
- analyzers/src/SonarAnalyzer.CSharp/sonarpedia.json
- analyzers/src/SonarAnalyzer.VisualBasic/sonarpedia.json
> Update RSPEC before 9.12 release

- sonar-csharp-plugin/pom.xml
- sonar-vbnet-plugin/pom.xml
While we wait for [this ticket](https://sonarsource.atlassian.net/browse/BUILD-3943) to be tackled, let's merge this, release, and revert it.
> [To be reverted] Manually override maven.deploy.skip

- analyzers/its/regression-test.ps1
It's slowing the CI and it's not used
> Remove perf report from .Net ITs

- analyzers/src/SonarAnalyzer.CSharp/Extensions/ArgumentSyntaxExtensions.cs
- analyzers/src/SonarAnalyzer.CSharp/Facade/CSharpSyntaxFacade.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/UriShouldNotBeHardcoded.cs
- analyzers/src/SonarAnalyzer.Common/Facade/SyntaxFacade.cs
- analyzers/src/SonarAnalyzer.Common/Rules/UriShouldNotBeHardcodedBase.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Extensions/ArgumentSyntaxExtensions.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Extensions/SyntaxNodeExtensions.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Facade/VisualBasicSyntaxFacade.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Rules/UriShouldNotBeHardcoded.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UriShouldNotBeHardcoded.CSharp11.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UriShouldNotBeHardcoded.CSharp12.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UriShouldNotBeHardcoded.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UriShouldNotBeHardcoded.vb
> Fix S1075 FN: default parameters

- analyzers/src/SonarAnalyzer.CFG/ShimLayer/Syntax.xml
- analyzers/src/SonarAnalyzer.CSharp/Rules/ArrayPassedAsParams.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/ArrayPassedAsParamsTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ArrayPassedAsParams.cs
> Fix S3878 FN: collection expressions

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp8.cs
> Add reproducer for #8149

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Checks/ConstantCheck.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Binary.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
> Fix S2583 FP: Issue is raised when there is comparison to a constant.

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CatchRethrow.Fixed.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CatchRethrow.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CatchRethrow.vb
> S2737: Add reproducer for #8199

- analyzers/src/SonarAnalyzer.CFG/ShimLayer/TypeDeclarationExtensions.cs
> Update ShimLayer: sync with Roslyn's Syntax.xml fix

- analyzers/its/regression-test.ps1
- it's not necessary; see: https://learn.microsoft.com/en-us/visualstudio/msbuild/customize-by-directory?view=vs-2022#search-scope
> Don't copy Directory.Build.targets in ITs

- analyzers/src/SonarAnalyzer.CSharp/Rules/SqlKeywordsDelimitedBySpace.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SqlKeywordsDelimitedBySpace.CSharp10.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SqlKeywordsDelimitedBySpace.cs
> Fix FP and FN for S2857

- analyzers/its/regression-test.ps1
- analyzers/its/sources/ManuallyAddedNoncompliantIssues.VB/IntentionalFindings/S5693.vb
- analyzers/its/sources/NetCore31/Controllers/S5693Controller.cs
- analyzers/rspec/cs/S5693.html
- analyzers/rspec/vbnet/S5693.html
- analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/RequestsWithExcessiveLengthBase.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/Hotspots/RequestsWithExcessiveLengthTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/RequestsWithExcessiveLength.CSharp10.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/RequestsWithExcessiveLength.CSharp11.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/RequestsWithExcessiveLength.CSharp9.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/RequestsWithExcessiveLength.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/RequestsWithExcessiveLength.vb
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/WebConfig/RequestsWithExcessiveLength/Values/ContentLength/Web.config
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/WebConfig/RequestsWithExcessiveLength/Values/ContentLength_Compliant/Web.config
Fixes #7867 
I also updated the RSPEC to match the new default value.
The PR: https://github.com/SonarSource/rspec/pull/3299
> Fix FP in S5693

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/ConditionEvaluatesToConstantBase.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/RestrictDeserializedTypesBase.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SymbolicRuleCheck.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/RestrictDeserializedTypes.CSharp8.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/RestrictDeserializedTypes.CSharp9.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/RestrictDeserializedTypes.JavaScriptSerializer.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/RestrictDeserializedTypes.JavaScriptSerializer.vb
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/RestrictDeserializedTypes.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/RestrictDeserializedTypes.vb
> S5773: Add message for secondary locations

- analyzers/src/SonarAnalyzer.CFG/ShimLayer/TypeDeclarationExtensions.cs
- analyzers/src/SonarAnalyzer.CSharp/Extensions/SyntaxNodeExtensions.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/RedundancyInConstructorDestructorDeclaration.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundancyInConstructorDestructorDeclaration.CSharp12.cs
> Fix S3253 FN: primary parameterless constructors

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/PrivateFieldUsedAsLocalVariable.cs
S1450. Repo for #8239 
There is a more general problem when ever a private method is passed as a delegate. I added another example for that.
> Repro FP S1450: Field is assigned value in event handler

- analyzers/src/SonarAnalyzer.CSharp/Extensions/SyntaxNodeExtensions.cs
- analyzers/src/SonarAnalyzer.CSharp/Extensions/TypeDeclarationSyntaxExtensions.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/UseParamsForVariableArguments.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/SymbolHelper.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Extensions/SyntaxNodeExtensionsTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Helpers/TypeDeclarationSyntaxExtensionsTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/UseParamsForVariableArgumentsTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UseParamsForVariableArguments.CSharp12.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UseParamsForVariableArguments.cs
> Fix S4061 FN: support constructors

- sonar-csharp-plugin/pom.xml
- sonar-vbnet-plugin/pom.xml
Fix #8234 
Reverts SonarSource/sonar-dotnet#8160
> Revert "Optimization: Enable on-demand plugin download"

- analyzers/src/SonarAnalyzer.Common/Rules/UriShouldNotBeHardcodedBase.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UriShouldNotBeHardcoded.CSharp12.cs
> Fix S1075 FN: Support collections and collection expressions

- analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/ClearTextProtocolsAreSensitive.cs
- analyzers/src/SonarAnalyzer.CSharp/Wrappers/ObjectCreationFactory.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/UnusedPrivateMemberTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/ClearTextProtocolsAreSensitive.CSharp12.cs
> Workaround for AD0001 in S1144

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SpecifyIFormatProviderOrCultureInfo.CSharp11.cs
> Repro for S4056

- docs/coding-style.md
From https://trello.com/c/T9adHFHl/48-convention-destructuring-of-de-facto-non-null-object
> Code convention: acceptable use of "o is { P: var p }"

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
> Repo for S2583 FP: Code wrongly considered unreachable

- analyzers/tests/SonarAnalyzer.UnitTest/Common/XUnitVersions.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/AssertionArgsShouldBePassedInCorrectOrderTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/DoNotUseLiteralBoolInAssertionsTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/TestMethodShouldContainAssertionTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Rules/TestsShouldNotUseThreadSleepTest.cs
[2.6.0 version](https://www.nuget.org/packages/xunit/2.6.0) cannot be loaded on .Net framework 4.6.2
> Fix XUnit version in tests

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/ArithmeticCalculator.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.ArithmeticCalculator.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
> Fix S2583 FP: Fix bug in calculation of maximum remainder

- scripts/rspec/CopyTestCasesFromRspec.ps1
- scripts/rspec/README.md
- scripts/rspec/rspec.ps1
- scripts/rspec/tests/CopyTestCasesFromRspec.Tests.ps1
As per the new rule specification process, this PR update `rspec.ps1` to copy all test cases from the given rule and branch.
> Update rspec.ps1 to copy test case from RSPEC

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
> Repro for S2589 FP: Simple switch block leads to multiple FPs

- analyzers/tests/SonarAnalyzer.UnitTest/Extensions/ISymbolExtensionsTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SnippetCompiler.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/TestHelper.cs
> Add tests to cover ISymbolExtensions.IsPrimaryConstructor

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.cs
> Reproducer for #8324

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp8.cs
> S2589 FP: Add reproducer for #8326

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CheckArgumentException.CSharp12.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CheckArgumentException.CSharp9.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CheckArgumentException.cs
> Add reproducer for #8319

- analyzers/src/SonarAnalyzer.CFG/SonarAnalyzer.CFG.csproj
- analyzers/src/SonarAnalyzer.CSharp/SonarAnalyzer.CSharp.csproj
- analyzers/src/SonarAnalyzer.VisualBasic/SonarAnalyzer.VisualBasic.csproj
- azure-pipelines.yml
- sonar-csharp-plugin/pom.xml
- sonar-vbnet-plugin/pom.xml
Fixes: #8230
Signing has been disabled by #8229
smctl doc: https://docs.digicert.com/en/digicert-keylocker/tools/command-line-interface/smctl.html
> Add back signing

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnusedPrivateMember.Fixed.Batch.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnusedPrivateMember.Fixed.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnusedPrivateMember.cs
> S1144: Add repro for #8348

- sonar-csharp-plugin/pom.xml
- sonar-vbnet-plugin/pom.xml
> Re-enable on demand plugin download for c# and vb.net

- analyzers/src/SonarAnalyzer.CSharp/Rules/MethodParameterUnusedCodeFix.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/KnownMethods.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Helpers/SymbolHelperTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/MethodParameterUnused.RoslynCfg.Fixed.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/MethodParameterUnused.RoslynCfg.cs
> Fix S1172 FP: Unused parameter cannot be removed

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.vb
> S2589: FP reproducer for #8368

- analyzers/tests/SonarAnalyzer.UnitTest/Extensions/SyntaxNodeExtensionsTest.cs
Follow-up cleanup after https://github.com/SonarSource/sonar-dotnet/pull/8073
See relevant  conversation: https://github.com/SonarSource/sonar-dotnet/pull/8073#discussion_r1381591293
> Extract common code in SyntaxNodeExtensionsTest

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp8.cs
> S2583/S2589: Add FP repro for #8382

- analyzers/src/SonarAnalyzer.Common/Extensions/SyntaxTreeExtensions.cs
> Use single nested cache for GeneratedCodeCache in SyntaxTreeExtensions

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundantCast.CSharp8.cs
> S1905: Add repro for #8413

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DisposableNotDisposed.cs
> S2930: Add repro for #8365

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
> S2583: FP reproducer for #8378

- analyzers/src/SonarAnalyzer.CSharp/Rules/AvoidExcessiveInheritance.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/CryptographicKeyShouldNotBeTooShort.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/DatabasePasswordsShouldBeSecure.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/ClearTextProtocolsAreSensitive.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/StringFormatValidator.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/NamingHelper.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/VbcHelper.cs
- analyzers/src/SonarAnalyzer.Common/Rules/CheckFileLicenseBase.cs
- analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/CommandPathBase.cs
- analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/DoNotHardcodeCredentialsBase.cs
- analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/PubliclyWritableDirectoriesBase.cs
- analyzers/src/SonarAnalyzer.SourceGenerators/RuleCatalogGenerator.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Rules/CommentLineEnd.cs
> Add timeouts to all regular expressions

- analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/ClearTextProtocolsAreSensitive.cs
- analyzers/src/SonarAnalyzer.Common/Extensions/RegexExtensions.cs
- analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/DoNotHardcodeCredentialsBase.cs
- analyzers/tests/SonarAnalyzer.UnitTest/Extensions/RegexExtensionsTests.cs
Increase timeout for S5332 & S2068.
Catch Regex timeout exceptions and ignore issues in such cases.
> Fix AD0001 due to Regex timeout

- analyzers/src/SonarAnalyzer.CSharp/sonarpedia.json
- analyzers/src/SonarAnalyzer.VisualBasic/sonarpedia.json
> Update RSPEC before 9.15 release

- .github/workflows/dogfood.yml
Code taken from
[Java](https://github.com/SonarSource/sonar-java/blob/master/.github/workflows/dogfood.yml)
[Python](https://github.com/SonarSource/sonar-python/blob/9a7d8fdfed3cca92a413f181e86c707eb67c7173/.github/workflows/dogfood.yml)
> Add dogfood GH action

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/LoopsAndLinq.CSharp11.cs
> S3267: Add FP Repro for #8430

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundancyInConstructorDestructorDeclaration.CSharp9.Fixed.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundancyInConstructorDestructorDeclaration.CSharp9.cs
> S3253: Add FP Repro for #8436

- analyzers/rspec/cs/S3928.html
- analyzers/src/SonarAnalyzer.CSharp/sonarpedia.json
- analyzers/src/SonarAnalyzer.VisualBasic/sonarpedia.json
> Update RSPEC before 9.16 release

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Extensions/IOperationExtensions.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/ConditionEvaluatesToConstantBase.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp9.cs
> Fix S2589 FP: Discard pattern in switch statement

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Extensions/IOperationExtensions.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IsPattern.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.LearnConstraint.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.PatternMatching.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.cs
> Fix S2259 FP: Raising issue in unreachable code when using declaration pattern on unknown value

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IsPattern.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.PatternMatching.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.CSharp9.cs
> Fix S2259 FP: is not and short-circuit or

- analyzers/its/expected/Net5/Net5--net5.0-S2589.json
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Extensions/BinaryOperatorKindExtensions.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Extensions/IOperationExtensions.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Binary.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IsPattern.cs
- analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.PatternMatching.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp9.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.CSharp9.cs
Fixes #8493
Review per commit shows the evolution
> Fix S2583/S2589 FN and FP: Add support for relational pattern

- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
> S2583/S2589: Add FP repro for #8495

- .github/workflows/RequestReview.yml
- .github/workflows/SubmitReview.yml
https://docs.github.com/en/graphql/reference/enums#commentauthorassociation
Tested on external test organization repo
> GitHub workflow: Improve author_association

- analyzers/tests/SonarAnalyzer.UnitTest/Rules/ArrayPassedAsParamsTest.cs
- analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ArrayPassedAsParams.CSharp12.cs
> S3878: Add FP repro for #8510

- its/src/test/java/com/sonar/it/shared/TestUtils.java
Fixes https://sonarsource.slack.com/archives/CJ8L44WRF/p1704444673166759
> [TO BE REVERTED] Fix Maven IT Failures because of 'no plugins installed'

- analyzers/NuGet.Config
- azure-pipelines.yml
- docs/contributing-analyzer.md
Fixes #8404
This has been tested against a NuGet repository that requires authentication. (see 
BUILD-4368)
Until https://repox.jfrog.io/artifactory/api/nuget/nuget enforces authentication, it will work without authentication, issues may raise once authentication is enforced on this repository.
> Add NuGet authentication

- docs/contributing-analyzer.md
- docs/verifier-syntax.md
- scripts/build/build-utils.ps1
- scripts/rspec/rspec-templates/Test.CS.cs
- scripts/rspec/rspec-templates/Test.VB.cs
- scripts/rspec/rspec.ps1
> Rename UnitTest projects to Test in other files

- analyzers/tests/SonarAnalyzer.Test/TestCases/InvocationResolvesToOverrideWithParams.cs
> S3220: Add FP Repro for #8522

- its/src/test/java/com/sonar/it/shared/TestUtils.java
Reverts #8518
[Internal click](https://sonarsource.slack.com/archives/C012KBFFYD6/p1704790803247729) for more info
> Revert "[TO BE REVERTED] Fix Maven IT Failures because of 'no plugins installed'

- analyzers/its/sources/ManuallyAddedNoncompliantIssues.CS/ManuallyAddedNoncompliantIssues.CS.sln
- analyzers/its/sources/ManuallyAddedNoncompliantIssues.CS/Net5/Net5.csproj
- analyzers/its/sources/ManuallyAddedNoncompliantIssues.CS/Net5/S6618.cs
- analyzers/its/sources/ManuallyAddedNoncompliantIssues.CS/Net6/Net6.csproj
- analyzers/its/sources/ManuallyAddedNoncompliantIssues.CS/Net6/S6618.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/UseStringCreate.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/UseStringCreate.CSharp10.cs
> Fix S6618 FP: Runtimes lower than .NET 6.0

- analyzers/src/SonarAnalyzer.CSharp/Rules/UnusedPrivateMember.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/KnownMethods.cs
- analyzers/tests/SonarAnalyzer.Test/Helpers/KnownMethodsTests.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/UnusedPrivateMember.CSharp9.cs
> Fix S1144 FP: PrintMembers method for records

- analyzers/tests/SonarAnalyzer.Test/Metrics/VisualBasicExecutableLinesMetricTest.cs
> Add UT for #8523

- analyzers/src/SonarAnalyzer.CSharp/Trackers/CSharpAssignmentFinder.cs
- analyzers/tests/SonarAnalyzer.Test/Rules/UnnecessaryBitwiseOperationTest.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/Hotspots/DoNotHardcodeCredentials.DefaultValues.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/UnnecessaryBitwiseOperation.CSharp9.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/UnnecessaryBitwiseOperation.Fixed.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/UnnecessaryBitwiseOperation.cs
> Fix S2437 FP: None of the operands is 0

- analyzers/SonarAnalyzer.sln
- analyzers/src/SonarAnalyzer.Common/Properties/AssemblyInfo.cs
- analyzers/tests/SonarAnalyzer.Test/SonarAnalyzer.Test.csproj
- analyzers/tests/SonarAnalyzer.TestFramework.Test/SonarAnalyzer.TestFramework.Test.csproj
- analyzers/tests/SonarAnalyzer.TestFramework.Test/packages.lock.json
- analyzers/tests/SonarAnalyzer.TestFramework/SonarAnalyzer.TestFramework.csproj
- analyzers/tests/SonarAnalyzer.TestFramework/packages.lock.json
- azure-pipelines.yml
Part of #8542
This is extract from the next PR, to split the review load. All used elements will be needed.
> TestFramework: Create empty projects

- analyzers/src/SonarAnalyzer.CSharp/Rules/CollectionQuerySimplification.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- analyzers/tests/SonarAnalyzer.Test/Rules/CollectionQuerySimplificationTest.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/CollectionQuerySimplification.CSharp9.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/CollectionQuerySimplification.NetFx.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/CollectionQuerySimplification.cs
- analyzers/tests/SonarAnalyzer.TestFramework/MetadataReferences/FrameworkMetadataReference.cs
> Improve S2971 to suggest to use AsEnumerable in LINQ database query

- analyzers/tests/SonarAnalyzer.Test/Rules/SpecifyTimeoutOnRegexTest.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/Hotspots/SpecifyTimeoutOnRegex.DefaultMatchTimeout.cs
> Add UTs for S6444

- analyzers/its/expected/Ember-MM/Ember Media Manager-{9B57D3AB-AF12-4012-B945-284C2448DC81}-S2178.json
- analyzers/its/expected/Ember-MM/EmberAPI-{208AA35E-C6AE-4D2D-A9DD-B6EFD19A4279}-S2178.json
- analyzers/its/expected/Ember-MM/scraper.EmberCore-{EF6A550E-DD76-4F4D-8250-8598140F828B}-S2178.json
- analyzers/its/expected/Nancy/Nancy--net452-S2178.json
- analyzers/its/expected/Nancy/Nancy--netstandard2.0-S2178.json
- analyzers/its/expected/Net5/variouspatternsofpatterns-3EFB6389-ED5B-4E14-809C-B43AF38748D9-net5.0-S2178.json
- analyzers/src/SonarAnalyzer.CSharp/Rules/UseShortCircuitingOperator.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/UseShortCircuitingOperatorCodeFix.cs
- analyzers/src/SonarAnalyzer.Common/Rules/UseShortCircuitingOperatorBase.cs
- analyzers/src/SonarAnalyzer.Common/Rules/UseShortCircuitingOperatorCodeFixBase.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Rules/UseShortCircuitingOperator.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Rules/UseShortCircuitingOperatorCodeFix.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/UseShortCircuitingOperator.Fixed.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/UseShortCircuitingOperator.cs
> Fix S2178 Rule message: Mention extracting right operand if applicable

- analyzers/src/SonarAnalyzer.Common/Rules/Utilities/SymbolReferenceAnalyzerBase.cs
- analyzers/tests/SonarAnalyzer.Test/Rules/Utilities/SymbolReferenceAnalyzerTest.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/Utilities/SymbolReferenceAnalyzer/Field.EscapedNonKeyword.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/Utilities/SymbolReferenceAnalyzer/Field.EscapedNonKeyword.vb
- analyzers/tests/SonarAnalyzer.Test/TestCases/Utilities/SymbolReferenceAnalyzer/Field.EscapedSequences.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/Utilities/SymbolReferenceAnalyzer/Field.ReservedKeyword.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/Utilities/SymbolReferenceAnalyzer/Field.ReservedKeyword.vb
- analyzers/tests/SonarAnalyzer.Test/TestCases/Utilities/SymbolReferenceAnalyzer/NamedType.ReservedKeyword.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/Utilities/SymbolReferenceAnalyzer/NamedType.ReservedKeyword.vb
- analyzers/tests/SonarAnalyzer.Test/TestCases/Utilities/SymbolReferenceAnalyzer/Parameter.ReservedKeyword.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/Utilities/SymbolReferenceAnalyzer/Parameter.ReservedKeyword.vb
> Detect symbol references for @keyword identifiers

- analyzers/tests/SonarAnalyzer.Test/TestCases/MemberShouldNotHaveConflictingTransparencyAttributes_AssemblyLevel.cs
- analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/IssueValidation/CompilationIssuesTest.cs
- analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/IssueValidation/IssueLocationCollectorTest.GetExpectedBuildErrors.cs
- analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/IssueValidation/IssueLocationCollectorTest.GetExpectedIssueLocations.cs
- analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/IssueValidation/IssueLocationCollectorTest.GetIssueLocations.cs
- analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/IssueValidation/IssueLocationCollectorTest.GetPreciseIssueLocations.cs
- analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/IssueValidation/IssueLocationCollectorTest.MergeLocations.cs
- analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/IssueValidation/IssueLocationPairTest.cs
- analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/IssueValidation/IssueLocationTest.cs
- analyzers/tests/SonarAnalyzer.TestFramework/Extensions/StringAssertionsExtensions.cs
- analyzers/tests/SonarAnalyzer.TestFramework/Verification/DiagnosticVerifier.cs
- analyzers/tests/SonarAnalyzer.TestFramework/Verification/IssueValidation/CompilationIssues.cs
- analyzers/tests/SonarAnalyzer.TestFramework/Verification/IssueValidation/FileContent.cs
- analyzers/tests/SonarAnalyzer.TestFramework/Verification/IssueValidation/IssueLocation.cs
- analyzers/tests/SonarAnalyzer.TestFramework/Verification/IssueValidation/IssueLocationCollector.cs
- analyzers/tests/SonarAnalyzer.TestFramework/Verification/IssueValidation/IssueLocationPair.cs
Part of #8543 
Last prerequisite PR
> TestFramework: Update IssueLocation

- analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/EmptyNullableValueAccess.CSharp9.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Sonar/EmptyNullableValueAccess.CSharp9.cs
> Reproducer for Fix S3655 FP: [DoesNotReturn] is not respected #8633

- its/src/test/java/com/sonar/it/shared/TestUtils.java
> Java ITs: Fix CE task extraction

- analyzers/tests/SonarAnalyzer.Test/Rules/CheckFileLicenseTest.cs
- analyzers/tests/SonarAnalyzer.Test/Rules/MarkAssemblyWithAssemblyVersionAttributeTest.cs
- analyzers/tests/SonarAnalyzer.Test/Rules/MarkAssemblyWithClsCompliantAttributeTest.cs
- analyzers/tests/SonarAnalyzer.Test/Rules/MarkAssemblyWithComVisibleAttributeTest.cs
- analyzers/tests/SonarAnalyzer.Test/Rules/MarkAssemblyWithNeutralResourcesLanguageAttributeTest.cs
- analyzers/tests/SonarAnalyzer.Test/Rules/OptionExplicitOnTest.cs
- analyzers/tests/SonarAnalyzer.Test/Rules/OptionStrictOnTest.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/MarkAssemblyWithAssemblyVersionAttributeNoncompliant.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/MarkAssemblyWithAssemblyVersionAttributeNoncompliant.vb
- analyzers/tests/SonarAnalyzer.Test/TestCases/MarkAssemblyWithClsCompliantAttributeNoncompliant.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/MarkAssemblyWithClsCompliantAttributeNoncompliant.vb
- analyzers/tests/SonarAnalyzer.Test/TestCases/MarkAssemblyWithComVisibleAttributeNoncompliant.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/MarkAssemblyWithComVisibleAttributeNoncompliant.vb
- analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/DiagnosticVerifierTest.cs
- analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/IssueValidation/IssueLocationTest.cs
- analyzers/tests/SonarAnalyzer.TestFramework/Verification/DiagnosticVerifier.cs
- analyzers/tests/SonarAnalyzer.TestFramework/Verification/IssueValidation/IssueLocation.cs
- analyzers/tests/SonarAnalyzer.TestFramework/Verification/IssueValidation/IssueLocationPair.cs
> TestFramework: Support asserting project-level issues

- analyzers/Analyzers.targets
- analyzers/NuGet.Config
- analyzers/SonarAnalyzer.sln
- analyzers/its/regression-test.ps1
- analyzers/src/ITs.JsonParser/CommandLineOptions.cs
- analyzers/src/ITs.JsonParser/ITs.JsonParser.csproj
- analyzers/src/ITs.JsonParser/Program.cs
- analyzers/src/ITs.JsonParser/packages.lock.json
- analyzers/src/SonarAnalyzer.CFG/SonarAnalyzer.CFG.csproj
- analyzers/src/SonarAnalyzer.CSharp/SonarAnalyzer.CSharp.csproj
- analyzers/src/SonarAnalyzer.Common/SonarAnalyzer.Common.csproj
- analyzers/src/SonarAnalyzer.RuleDescriptorGenerator/SonarAnalyzer.RuleDescriptorGenerator.csproj
- analyzers/src/SonarAnalyzer.ShimLayer.CodeGeneration/SonarAnalyzer.ShimLayer.CodeGeneration.csproj
- analyzers/src/SonarAnalyzer.SourceGenerators/SonarAnalyzer.SourceGenerators.csproj
- analyzers/src/SonarAnalyzer.VisualBasic/SonarAnalyzer.VisualBasic.csproj
- analyzers/tests/ITs.JsonParser.Test/ITs.JsonParser.Test.csproj
- analyzers/tests/ITs.JsonParser.Test/JsonParsingTest.cs
- analyzers/tests/ITs.JsonParser.Test/packages.lock.json
- analyzers/tests/SonarAnalyzer.Net8.Test/SonarAnalyzer.Net8.Test.csproj
- analyzers/tests/SonarAnalyzer.Test/SonarAnalyzer.Test.csproj
- analyzers/tests/SonarAnalyzer.TestFramework.Test/SonarAnalyzer.TestFramework.Test.csproj
- analyzers/tests/SonarAnalyzer.TestFramework/SonarAnalyzer.TestFramework.csproj
- azure-pipelines.yml
> ITs: Scaffold JSON Parser for ITs

- analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/DiagnosticVerifierTest.cs
- analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/IssueValidation/IssueLocationPairTest.cs
- analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/IssueValidation/IssueLocationTest.cs
- analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/VerifierTest.cs
- analyzers/tests/SonarAnalyzer.TestFramework/Verification/DiagnosticVerifier.cs
- analyzers/tests/SonarAnalyzer.TestFramework/Verification/IssueValidation/CompilationIssues.cs
- analyzers/tests/SonarAnalyzer.TestFramework/Verification/IssueValidation/IssueLocation.cs
- analyzers/tests/SonarAnalyzer.TestFramework/Verification/IssueValidation/IssueLocationPair.cs
> TestFramework: Support issue ID assertion

- analyzers/tests/SonarAnalyzer.Test/Common/FixAllProviders/DocumentBasedFixAllProviderTest.cs
- analyzers/tests/SonarAnalyzer.Test/Common/RuleTest.cs
- analyzers/tests/SonarAnalyzer.Test/Rules/SymbolicExecution/SymbolicExecutionRunnerTest.cs
- analyzers/tests/SonarAnalyzer.TestFramework/Verification/CodeFixVerifier.cs
- analyzers/tests/SonarAnalyzer.TestFramework/Verification/DiagnosticVerifier.cs
Part of #8601 
Next step: Cleanup, remove VerifyBuildErrors
> TestFramework: Refactor DiagnosticVerifier.AnalyzerDiagnostics

- docs/verifier-syntax.md
> TestFramework: Update Verifier syntax docs

- analyzers/rspec/cs/S2386.html
- analyzers/rspec/cs/S3887.html
- analyzers/src/SonarAnalyzer.CSharp/Rules/MutableFieldsShouldNotBe.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- analyzers/tests/SonarAnalyzer.Net8.Test/Rules/MutableFieldsShouldNotBePublicReadonlyTest.cs
- analyzers/tests/SonarAnalyzer.Net8.Test/Rules/MutableFieldsShouldNotBePublicStaticTest.cs
- analyzers/tests/SonarAnalyzer.Net8.Test/TestCases/MutableFieldsShouldNotBePublicReadonly.cs
- analyzers/tests/SonarAnalyzer.Net8.Test/TestCases/MutableFieldsShouldNotBePublicStatic.cs
Fixes #8638
RSpec changes: https://github.com/SonarSource/rspec/pull/3594
ToDo:
> Fix S2386 & S3887 FP: should not be raised for FrozenDictionary and FrozenSet

- analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
> S2583: Add FP Repro for #8678

- analyzers/tests/SonarAnalyzer.Test/TestCases/DoNotDecreaseMemberVisibility.cs
> S4105 FP: Add reproducer for #8666

- analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
Updates the reproducer on #8368
For context [see this](https://github.com/SonarSource/sonar-dotnet/issues/8368#issuecomment-1927750636).
> S2589: Update reproducer

- analyzers/src/SonarAnalyzer.Common/Helpers/KnownMethods.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/ObjectsShouldNotBeDisposedMoreThanOnce.CSharp8.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/ObjectsShouldNotBeDisposedMoreThanOnce.CSharp9.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/ObjectsShouldNotBeDisposedMoreThanOnce.vb
> Fix S3966: AD0001 for static Dispose() invocations

- analyzers/its/expected/akka.net/Akka--netstandard2.0-S2589.json
- analyzers/its/expected/akka.net/Akka.Persistence.Sql.Common--netstandard2.0-S2589.json
- analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/ConditionEvaluatesToConstantBase.cs
- analyzers/src/SonarAnalyzer.VisualBasic/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.vb
> Improve S2589: Update warning message for null check

- analyzers/tests/SonarAnalyzer.Test/Rules/DatabasePasswordsShouldBeSecureTest.cs
- analyzers/tests/SonarAnalyzer.Test/Rules/Hotspots/DisablingRequestValidationTest.cs
- analyzers/tests/SonarAnalyzer.Test/Rules/Hotspots/DoNotHardcodeCredentialsTest.cs
- analyzers/tests/SonarAnalyzer.Test/Rules/Hotspots/RequestsWithExcessiveLengthTest.cs
- analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/IssueValidation/CompilationIssuesTest.cs
- analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/IssueValidation/IssueLocationCollectorTest.MergeLocations.cs
- analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/IssueValidation/IssueLocationPairTest.cs
- analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/IssueValidation/IssueLocationTest.cs
- analyzers/tests/SonarAnalyzer.TestFramework/Verification/DiagnosticVerifier.cs
- analyzers/tests/SonarAnalyzer.TestFramework/Verification/IssueValidation/IssueLocation.cs
- analyzers/tests/SonarAnalyzer.TestFramework/Verification/IssueValidation/IssueLocationCollector.cs
Follow up of #8601 
Commit history shows the changes in isolation
> TestFramework: Refactoring and cleanup

- analyzers/tests/SonarAnalyzer.Test/AnalysisContext/SonarAnalysisContextBaseTest.ShouldAnalyzeTree.cs
- analyzers/tests/SonarAnalyzer.Test/Rules/DatabasePasswordsShouldBeSecureTest.cs
- analyzers/tests/SonarAnalyzer.Test/Rules/Hotspots/DisablingRequestValidationTest.cs
- analyzers/tests/SonarAnalyzer.Test/Rules/Hotspots/DoNotHardcodeCredentialsTest.cs
- analyzers/tests/SonarAnalyzer.Test/Rules/Hotspots/RequestsWithExcessiveLengthTest.cs
- analyzers/tests/SonarAnalyzer.Test/Rules/MethodsShouldUseBaseTypesTest.cs
- analyzers/tests/SonarAnalyzer.Test/Rules/OptionExplicitOnTest.cs
- analyzers/tests/SonarAnalyzer.Test/Rules/OptionStrictOnTest.cs
- analyzers/tests/SonarAnalyzer.Test/Rules/TaskConfigureAwaitTest.cs
- analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/DiagnosticVerifierTest.cs
- analyzers/tests/SonarAnalyzer.TestFramework/Verification/DiagnosticVerifier.cs
- analyzers/tests/SonarAnalyzer.TestFramework/Verification/Verifier.cs
- analyzers/tests/SonarAnalyzer.TestFramework/Verification/VerifierBuilder.cs
> TestFramework: Deprecate CompilationErrorBehavior

- analyzers/tests/SonarAnalyzer.TestFramework.Test/Common/LogTesterTest.cs
- analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/DiagnosticVerifierTest.cs
- analyzers/tests/SonarAnalyzer.TestFramework/SonarAnalyzer.TestFramework.csproj
- analyzers/tests/SonarAnalyzer.TestFramework/Verification/IssueValidation/CompilationIssues.cs
- analyzers/tests/SonarAnalyzer.TestFramework/Verification/SuppressionHandler.cs
Related to #8621
I can't get the coverage better due to bug in our coverage import logic: #8696
> TestFramework: Bump coverage

- analyzers/src/ITs.JsonParser/IssueParser.cs
- analyzers/src/ITs.JsonParser/Json/RuleIssues.cs
- analyzers/src/ITs.JsonParser/Json/SarifReport.cs
- analyzers/tests/ITs.JsonParser.Test/IssueParserTest.cs
> ITs: Simplify location information in JSON output

- analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
> S2583: Add FP Repro for #8719

- analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/DiagnosticVerifierExceptionTest.cs
- analyzers/tests/SonarAnalyzer.TestFramework/Verification/DiagnosticVerifierException.cs
- analyzers/tests/SonarAnalyzer.TestFramework/Verification/IssueValidation/VerificationMessage.cs
Follow up of #8546 for Rider users
> TestFramework: Make failed assertions clickable in Rider

- analyzers/its/Directory.Build.targets
- analyzers/its/regression-test.ps1
- analyzers/src/ITs.JsonParser/IssueParser.cs
- analyzers/src/ITs.JsonParser/Program.cs
- analyzers/src/ITs.JsonParser/Reports/InputReport.cs
- analyzers/tests/ITs.JsonParser.Test/IssueParserTest.cs
- analyzers/tests/ITs.JsonParser.Test/Sarif.cs
clone of https://github.com/SonarSource/sonar-dotnet/pull/8717 as it cannot be reopened because the feature branch it was targeting is closed.
> ITs: Write Sarif in different directory

- analyzers/its/expected/akka.net/S4049-Akka-netstandard2.0.json
- analyzers/its/expected/akka.net/S4049-Akka.Persistence.Query-netstandard2.0.json
- analyzers/its/expected/akka.net/S4049-Akka.Streams-netstandard2.0.json
- analyzers/src/SonarAnalyzer.CSharp/Rules/PropertiesShouldBePreferred.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/PropertiesShouldBePreferred.cs
> Fix S4049 FP: Do not raise on methods with generic parameters

- analyzers/its/expected/Ember-MM/generic.EmberCore.XBMC-{6FE33C61-E2C2-4982-9536-63AEF0A98AAA}-S2583.json
- analyzers/its/expected/Ember-MM/generic.EmberCore.XBMC-{6FE33C61-E2C2-4982-9536-63AEF0A98AAA}-S2589.json
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/ArithmeticCalculator.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Binary.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/BranchingProcessor.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/CompoundAssignment.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IncrementOrDecrement.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IsNull.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IsPattern.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IsType.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/References.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SymbolicContext.cs
- analyzers/tests/SonarAnalyzer.Test/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Loops.cs
- analyzers/tests/SonarAnalyzer.Test/SymbolicExecution/Roslyn/SymbolicCheckListTest.cs
- analyzers/tests/SonarAnalyzer.Test/SymbolicExecution/Roslyn/SymbolicContextTest.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/CalculationsShouldNotOverflow.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/CalculationsShouldNotOverflow.vb
- analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp12.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
Fixes #8474 
Fixes #8028
Fixes #8428
Fixes #8449
> Rework loop fuzzy logic for NumberConstraints

- analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
> S2583: Add FP Repro for #8707

- analyzers/its/expected/Net5/S2589-Net5-net5.0.json
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationDispatcher.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Argument.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/ArrayCreation.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/CollectionTracker.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Invocation.Enumerable.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Invocation.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/MethodReference.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/ObjectCreation.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/References.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/EmptyCollectionsShouldNotBeEnumeratedBase.cs
- analyzers/tests/SonarAnalyzer.Test/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Binary.cs
- analyzers/tests/SonarAnalyzer.Test/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Invocation.cs
- analyzers/tests/SonarAnalyzer.Test/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.vb
Fixes https://github.com/SonarSource/sonar-dotnet/issues/7866
> [DO NOT SQUASH] Move CollectionConstraint from S4158 to the engine 

- analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
> S2589: Add FP Repro for #8570

- docs/coding-style.md
https://trello.com/c/iKClG1Zo/90-coding-style-improve-directives
> Coding style: Remove compiler directives

- analyzers/src/SonarAnalyzer.CFG/Extensions/BasicBlockExtensions.cs
- analyzers/src/SonarAnalyzer.CFG/Extensions/ControlFlowRegionExtensions.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/LoopDetector.cs
- analyzers/tests/SonarAnalyzer.Test/Extensions/BasicBlockExtensionsTests.cs
- analyzers/tests/SonarAnalyzer.Test/SymbolicExecution/Roslyn/LoopDetectorTest.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
```
int count = 3;
while (count > 0)   // Noncompliant FP
{
try
{
Console.WriteLine();
}
finally
{
count--;
}
}
```
> Fix S2583/S2589 FP: try-finally in loop

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Extensions/BinaryOperatorKindExtensions.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/BinaryBase.cs
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IsPattern.cs
- analyzers/tests/SonarAnalyzer.Test/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.PatternMatching.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/CalculationsShouldNotOverflow.CSharp9.cs
> SE: Learn number constraints from relational pattern

- analyzers/src/SonarAnalyzer.Common/Helpers/MessageTemplates.cs
- analyzers/tests/SonarAnalyzer.Test/Helpers/MessageTemplatesTest.cs
> Implement a common mechanism for parsing strings with parameters

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IsPattern.cs
- analyzers/tests/SonarAnalyzer.Test/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.PatternMatching.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/CalculationsShouldNotOverflow.CSharp9.cs
> error AD0001: SonarAnalyzer.Rules.CSharp.SymbolicExecutionRunner showed up with SonarAnalyzer.Csharp 9.20.0.85982

- analyzers/rspec/cs/S2328.html
- analyzers/src/SonarAnalyzer.CSharp/Rules/GetHashCodeMutable.cs
- analyzers/tests/SonarAnalyzer.Test/Rules/GetHashCodeMutableTest.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/GetHashCodeMutable.CSharp10.cs
> Fix S2328 FP: GetHashCode on mutable struct is safe

- analyzers/its/expected/Ember-MM/S6667-Ember.Plugins.json
- analyzers/src/SonarAnalyzer.CSharp/Rules/ExceptionsShouldBeLogged.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- analyzers/tests/SonarAnalyzer.Test/Rules/ExceptionsShouldBeLoggedTest.cs
- analyzers/tests/SonarAnalyzer.TestFramework/MetadataReferences/NuGetMetadataReference.cs
> Rule s6667: Add support for additional frameworks

- analyzers/src/SonarAnalyzer.CSharp/Rules/ExceptionsShouldBeLogged.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- analyzers/tests/SonarAnalyzer.Test/Rules/ExceptionsShouldBeLoggedTest.cs
> Rule S6667: Add support for derived loggers

- analyzers/tests/SonarAnalyzer.Test/TestCases/Hotspots/CreatingHashAlgorithms.CSharp11.cs
>  S4790 FN: Add repro

- analyzers/tests/SonarAnalyzer.Test/TestCases/UnusedStringBuilder.vb
> Repro for S3063 FN

- analyzers/src/SonarAnalyzer.CSharp/Rules/MessageTemplates/UsePascalCaseForNamedPlaceHolders.cs
- analyzers/tests/SonarAnalyzer.Test/Rules/UsePascalCaseForNamedPlaceHoldersTest.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/UsePascalCaseForNamedPlaceHolders.cs
> Improve S6678: Introduce secondary locations

- analyzers/tests/SonarAnalyzer.Test/TestCases/CommentedOutCode.MultiLine.Fixed.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/CommentedOutCode.MultiLine.ToFix.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/CommentedOutCode.SingleLine.Fixed.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/CommentedOutCode.SingleLine.ToFix.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/CommentedOutCode.cs
Repro for https://github.com/SonarSource/sonar-dotnet/issues/8819
> S125: Add FP Repro for #8819

- analyzers/rspec/cs/S2551.html
- analyzers/rspec/cs/S3923.html
- analyzers/rspec/cs/S4426.html
- analyzers/rspec/cs/S4428.html
- analyzers/rspec/cs/S6668.html
- analyzers/rspec/cs/S6674.html
- analyzers/rspec/cs/S6674.json
- analyzers/rspec/cs/S6677.json
- analyzers/rspec/vbnet/S2551.html
- analyzers/rspec/vbnet/S4428.html
- analyzers/src/SonarAnalyzer.CSharp/sonarpedia.json
- analyzers/src/SonarAnalyzer.VisualBasic/sonarpedia.json
> Update RSPEC for 9.21 Release

- analyzers/its/expected/Ember-MM/S2259-Ember Media Manager.json
- analyzers/its/expected/Ember-MM/S2259-generic.EmberCore.NMT.json
- analyzers/its/expected/Ember-MM/S2583-EmberAPI.json
- analyzers/its/expected/Ember-MM/S2583-scraper.EmberCore.XML.json
- analyzers/its/expected/Ember-MM/S2589-EmberAPI.json
- analyzers/its/expected/Ember-MM/S2589-generic.EmberCore.Extractor.json
- analyzers/its/expected/Ember-MM/S3900-scraper.EmberCore.json
- analyzers/its/expected/Nancy/S2583-Nancy-net452.json
- analyzers/its/expected/Nancy/S2583-Nancy-netstandard2.0.json
- analyzers/its/expected/Nancy/S2589-Nancy-net452.json
- analyzers/its/expected/Nancy/S2589-Nancy-netstandard2.0.json
- analyzers/its/expected/akka.net/S2589-Akka-netstandard2.0.json
- analyzers/its/expected/akka.net/S2589-Akka.Cluster-netstandard2.0.json
- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
- analyzers/tests/SonarAnalyzer.Test/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Loops.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp8.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.vb
The old numbers are guesswork. So are these new numbers. Let's merge this and see how it performs for some easy experimentation.
A sprint dedicated to fine-tuning the SE engine's parameters will follow later.
> SE: Increase loop iteration limit to 3 and step count limit to 4000

- analyzers/src/SonarAnalyzer.CSharp/Rules/MessageTemplates/MessageTemplatesShouldBeCorrect.cs
- analyzers/src/SonarAnalyzer.Common/Extensions/CompilationExtensions.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/KnownAssembly.Predicates.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/KnownAssembly.cs
- analyzers/tests/SonarAnalyzer.Test/Extensions/CompilationExtensionsTest.cs
- analyzers/tests/SonarAnalyzer.Test/Helpers/KnownAssemblyTest.cs
- analyzers/tests/SonarAnalyzer.TestFramework/MetadataReferences/NuGetMetadataReference.cs
> Improve Logging Rules: Check for Library References Before Registering Analyzers

- analyzers/src/SonarAnalyzer.CSharp/Rules/LoggerMembersNamesShouldComply.cs
- analyzers/tests/SonarAnalyzer.Test/Rules/LoggerMembersNamesShouldComplyTest.cs
See [example](https://peach.aws-prd.sonarsource.com/issues?resolved=false&rules=csharpsquid%3AS6669&open=AY4bne4G4i6Mzpcf2Hho)
> S6669: Include 'Instance' in default allowed logger names

- analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.cs
> S2259: Add Repro for #8907 and #8908

- README.md
- analyzers/its/expected/AnalyzeGenerated.CS/S1128-AnalyzeGeneratedFiles.json
- analyzers/its/expected/AnalyzeGenerated.CS/S1451-AnalyzeGeneratedFiles.json
- analyzers/its/expected/AnalyzeGenerated.VB/S1451-AnalyzeGeneratedVb.json
- analyzers/its/expected/AnalyzeGenerated.VB/S6145-AnalyzeGeneratedVb.json
- analyzers/its/sources/AnalyzeGenerated.CS/AnalyzeGenerated.CS.csproj
- analyzers/its/sources/AnalyzeGenerated.VB/AnalyzeGenerated.VB.vbproj
- analyzers/its/sources/SkipGenerated.CS/SkipGenerated.CS.csproj
- analyzers/its/sources/SkipGenerated.VB/SkipGenerated.VB.vbproj
- analyzers/its/update-expected.ps1
- docs/contributing-analyzer.md
> ITs: Remove the need to install old .NET Frameworks

- README.md
- analyzers/its/expected/BlazorSample/S1312-BlazorSample-net7.0.json
- analyzers/its/expected/CSharpLatest/S1312-NetCore31.MVC.ConfigurableRules-netcoreapp3.1.json
- analyzers/its/expected/ManuallyAddedNoncompliantIssues.CS/S1312-IntentionalFindings-net8.0.json
- analyzers/its/expected/RazorSample/S1312-RazorSample-net7.0.json
- analyzers/its/expected/akka.net/S1312-Akka.Remote.TestKit-netstandard2.0.json
- analyzers/rspec/cs/S1312.html
- analyzers/rspec/cs/S1312.json
- analyzers/src/SonarAnalyzer.CSharp/Rules/LoggerFieldsShouldBePrivateStaticReadonly.cs
- analyzers/tests/SonarAnalyzer.Test/PackagingTests/RuleTypeMappingCS.cs
- analyzers/tests/SonarAnalyzer.Test/Rules/LoggerFieldsShouldBePrivateStaticReadonlyTest.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/LoggerFieldsShouldBePrivateStaticReadonly.cs
> New rule S1312: Logger fields should be 'private static readonly'

- analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.cs
> S2259: Add Repro for #8905

- analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- analyzers/src/SonarAnalyzer.Common/Rules/BackslashShouldBeAvoidedInAspNetRoutesBase.cs
- analyzers/tests/SonarAnalyzer.Test/Rules/BackslashShouldBeAvoidedInAspNetRoutesTest.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/BackslashShouldBeAvoidedInAspNetRoutes.AspNetCore2x.CSharp11.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/BackslashShouldBeAvoidedInAspNetRoutes.AspNetCore2x.CSharp8.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/BackslashShouldBeAvoidedInAspNetRoutes.AspNetCore2x.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/BackslashShouldBeAvoidedInAspNetRoutes.AspNetCore2x.vb
> S6930: Support for ASP.NET Core 2.x

- analyzers/src/SonarAnalyzer.CSharp/Rules/UseConstantLoggingTemplate.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/UseConstantLoggingTemplate.cs
> Fix S2629 FP - constant string concatenation

- analyzers/src/SonarAnalyzer.CSharp/Rules/MessageTemplates/LoggingTemplatePlaceHoldersShouldBeInOrder.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/LoggingTemplatePlaceHoldersShouldBeInOrder.cs
> Fix S6673 FP: Name matching of placeholder names

- analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.cs
> S2259: Add Repro for #8910

- analyzers/src/SonarAnalyzer.CSharp/Rules/LoggersShouldBeNamedForEnclosingType.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/LoggersShouldBeNamedForEnclosingType.cs
> Rule S3416: include constructors and reduce FPs

- analyzers/rspec/cs/S2551.html
- analyzers/rspec/cs/S3927.html
- analyzers/rspec/cs/S5542.html
- analyzers/rspec/vbnet/S117.html
- analyzers/rspec/vbnet/S2551.html
- analyzers/rspec/vbnet/S3927.html
- analyzers/rspec/vbnet/S5542.html
- analyzers/src/SonarAnalyzer.CSharp/sonarpedia.json
- analyzers/src/SonarAnalyzer.VisualBasic/sonarpedia.json
> Update RSPEC for 9.22 (again)

- analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/ObjectsShouldNotBeDisposedMoreThanOnce.cs
Repro for #8946
PS: branch name is wrong.
> S3966 FP Repro

- analyzers/tests/SonarAnalyzer.Test/Rules/UriShouldNotBeHardcodedTest.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/UriShouldNotBeHardcoded.Exceptions.cs
> S1075: Add FP repro for #8967

- analyzers/src/SonarAnalyzer.CSharp/Rules/SpecifyRouteAttribute.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/SpecifyRouteAttribute.CSharp12.cs
> Fix S6934 FP + FN: Inherited Route and HttpMethod attributes are not considered at the controller or action level

- analyzers/tests/SonarAnalyzer.Test/TestCases/SpecifyRouteAttribute.CSharp12.cs
> S6934: Add FP repro for #8985

- analyzers/src/SonarAnalyzer.CSharp/sonarpedia.json
- analyzers/src/SonarAnalyzer.VisualBasic/sonarpedia.json
> Update RSPEC before 9.23.1 release 

- analyzers/tests/SonarAnalyzer.Test/TestCases/BooleanLiteralUnnecessary.Fixed.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/BooleanLiteralUnnecessary.cs
> Repro for #8995

- analyzers/tests/SonarAnalyzer.Test/Rules/ClassShouldNotBeEmptyTest.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/ClassShouldNotBeEmpty.CSharp12.cs
> Add reproducer for #9011

- analyzers/tests/SonarAnalyzer.Test/AnalysisContext/SonarAnalysisContextBaseTest.ShouldAnalyzeTree.cs
- analyzers/tests/SonarAnalyzer.TestFramework.Test/Build/ProjectBuilderTest.cs
- analyzers/tests/SonarAnalyzer.TestFramework/Build/ProjectBuilder.cs
- analyzers/tests/SonarAnalyzer.TestFramework/Verification/Verifier.cs
> Add *.razor and *.cshtml additional files to the compilation

- analyzers/tests/SonarAnalyzer.Test/AnalysisContext/SonarAnalysisContextBaseTest.ShouldAnalyzeTree.cs
- analyzers/tests/SonarAnalyzer.TestFramework.Test/Build/ProjectBuilderTest.cs
- analyzers/tests/SonarAnalyzer.TestFramework/Build/ProjectBuilder.cs
- analyzers/tests/SonarAnalyzer.TestFramework/Verification/Verifier.cs
> Add custom .editorconfig file to the compilation

- analyzers/tests/SonarAnalyzer.Test/Rules/Hotspots/ClearTextProtocolsAreSensitiveTest.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/Hotspots/ClearTextProtocolsAreSensitive.NetFramework.cs
- analyzers/tests/SonarAnalyzer.TestFramework/MetadataReferences/FrameworkMetadataReference.cs
> Add reproducer for #9017

- analyzers/tests/SonarAnalyzer.Test/TestCases/DisposableNotDisposed.cs
> S2930: Add FP repro for #8336

- analyzers/src/SonarAnalyzer.CSharp.Styling/SonarAnalyzer.CSharp.Styling.csproj
- analyzers/src/SonarAnalyzer.CSharp.Styling/packages.lock.json
- analyzers/tests/SonarAnalyzer.CSharp.Styling.Test/packages.lock.json
> Use Latest Roslyn for Styling rules

- analyzers/src/SonarAnalyzer.CSharp.Styling/Rules/FileScopeNamespace.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/AbstractTypesShouldNotHaveConstructors.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/AllBranchesShouldNotHaveSameImplementation.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/AlwaysSetDateTimeKind.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/AnonymousDelegateEventUnsubscribe.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/ArgumentSpecifiedForCallerInfoParameter.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/ArrayCovariance.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/AssertionArgsShouldBePassedInCorrectOrder.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/AssertionsShouldBeComplete.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/AssignmentInsideSubExpression.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/AsyncAwaitIdentifier.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/AsyncVoidMethod.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/AvoidExcessiveClassCoupling.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/AvoidExcessiveInheritance.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/AvoidLambdaExpressionInLoopsInBlazor.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/BooleanLiteralUnnecessary.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/BreakOutsideSwitch.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/CallToAsyncMethodShouldNotBeBlocking.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/CallerInformationParametersShouldBeLast.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/CastConcreteTypeToInterface.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/CatchEmpty.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/ClassAndMethodName.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/ClassWithEqualityShouldImplementIEquatable.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/CloudNative/AzureFunctionsCatchExceptions.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/CloudNative/AzureFunctionsReuseClients.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/CloudNative/AzureFunctionsStateless.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/CloudNative/DurableEntityInterfaceRestrictions.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/CollectionPropertiesShouldBeReadOnly.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/CollectionQuerySimplification.cs
- analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarReportingContextBase.cs
Add first overloads, and use it on a few places to start CaYC.
> Add ReportIssue overload without Diagnostic

- analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp9.cs
> S2589: Add FP repro for #9051

- analyzers/packaging/SonarAnalyzer.CSharp.nuspec
- analyzers/packaging/SonarAnalyzer.VisualBasic.nuspec
- analyzers/src/AssemblyInfo.Shared.cs
- analyzers/src/SonarAnalyzer.CFG/SonarAnalyzer.CFG.cs.nuspec
- its/pom.xml
- pom.xml
- scripts/version/Version.props
- sonar-csharp-plugin/pom.xml
- sonar-dotnet-shared-library/pom.xml
- sonar-vbnet-plugin/pom.xml
> Update version to 9.23.2

- analyzers/src/RuleDescriptorGenerator/packages.lock.json
- analyzers/src/SonarAnalyzer.CFG/ShimLayer/AnalysisContext/SymbolStartAnalysisContextWrapper.cs
- analyzers/src/SonarAnalyzer.CFG/SonarAnalyzer.CFG.csproj
- analyzers/src/SonarAnalyzer.CFG/packages.lock.json
- analyzers/src/SonarAnalyzer.CSharp.Styling/packages.lock.json
- analyzers/src/SonarAnalyzer.CSharp/packages.lock.json
- analyzers/src/SonarAnalyzer.Common/packages.lock.json
- analyzers/src/SonarAnalyzer.VisualBasic/packages.lock.json
- analyzers/tests/ITs.JsonParser.Test/packages.lock.json
- analyzers/tests/SonarAnalyzer.CSharp.Styling.Test/packages.lock.json
- analyzers/tests/SonarAnalyzer.Net8.Test/packages.lock.json
- analyzers/tests/SonarAnalyzer.Test/TestCases/RouteTemplateShouldNotStartWithSlash.AspNet4x.vb
- analyzers/tests/SonarAnalyzer.Test/TestCases/RouteTemplateShouldNotStartWithSlash.AspNetCore.vb
- analyzers/tests/SonarAnalyzer.Test/Wrappers/RegisterSymbolStartActionWrapperTest.cs
- analyzers/tests/SonarAnalyzer.Test/packages.lock.json
- analyzers/tests/SonarAnalyzer.TestFramework.Test/packages.lock.json
- analyzers/tests/SonarAnalyzer.TestFramework/packages.lock.json
> Remove vb reference from SonarAnalyzer.CFG

- analyzers/src/SonarAnalyzer.CSharp.Styling/Rules/ArrowLocation.cs
- analyzers/tests/SonarAnalyzer.CSharp.Styling.Test/Rules/ArrowLocationTest.cs
- analyzers/tests/SonarAnalyzer.CSharp.Styling.Test/TestCases/ArrowLocation.cs
> New Rule T0002: Place => correctly

- analyzers/src/SonarAnalyzer.CSharp.Styling/Rules/AvoidValueTuple.cs
- analyzers/tests/SonarAnalyzer.CSharp.Styling.Test/Rules/AvoidValueTupleTest.cs
- analyzers/tests/SonarAnalyzer.CSharp.Styling.Test/TestCases/AvoidValueTuple.cs
Fixes #9039
GH had some issues yesterday. The pipeline is fully green on Azure DevOps
> New Rule T0003: Don't use ValueTuple in production code

- analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.CSharp8.cs
> S2259: Add FP repro for #9078

- analyzers/src/SonarAnalyzer.CSharp.Styling/Rules/LambdaParameterName.cs
- analyzers/tests/SonarAnalyzer.CSharp.Styling.Test/Common/StylingVerifierBuilder.cs
- analyzers/tests/SonarAnalyzer.CSharp.Styling.Test/Rules/LambdaParameterNameTest.cs
- analyzers/tests/SonarAnalyzer.CSharp.Styling.Test/SonarAnalyzer.CSharp.Styling.Test.csproj
- analyzers/tests/SonarAnalyzer.CSharp.Styling.Test/TestCases/LambdaParameterName.cs
> New Rule T0010: Use x as a lambda parameter name

- analyzers/src/SonarAnalyzer.Common/Rules/ClassShouldNotBeEmptyBase.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/ClassShouldNotBeEmpty.cs
> Fix S2094 FP: Documentation using the DefaultDocumentation package

- analyzers/src/SonarAnalyzer.CSharp.Styling/Rules/NullPatternMatching.cs
- analyzers/tests/SonarAnalyzer.CSharp.Styling.Test/Rules/NullPatternMatchingTest.cs
- analyzers/tests/SonarAnalyzer.CSharp.Styling.Test/TestCases/NullPatternMatching.cs
> New Rule T0007: Use "is (not) null" for null checks

- .gitignore
- analyzers/SonarAnalyzer.sln
- analyzers/packaging/SonarAnalyzer.CSharp.Styling.nuspec
- analyzers/src/Directory.Build.targets
- analyzers/src/SonarAnalyzer.CSharp.Styling/SonarAnalyzer.CSharp.Styling.csproj
- analyzers/tests/SonarAnalyzer.CSharp.Styling.Test/packages.lock.json
- scripts/version/ChangeVersion.proj
> Build SonarAnalyzer.CSharp.Styling NuGet package

- analyzers/src/SonarAnalyzer.CSharp.Styling/Rules/AvoidListForEach.cs
- analyzers/src/SonarAnalyzer.Common/Extensions/MethodSymbolExtensions.cs
- analyzers/tests/SonarAnalyzer.CSharp.Styling.Test/Rules/AvoidListForEachTest.cs
- analyzers/tests/SonarAnalyzer.CSharp.Styling.Test/Rules/AvoidValueTupleTest.cs
- analyzers/tests/SonarAnalyzer.CSharp.Styling.Test/TestCases/AvoidListForEach.cs
> New Rule T0011: Don't use List.ForEach

- analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
- analyzers/tests/SonarAnalyzer.Test/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Throw.cs
> AD0001: ArgumentNullException in SymbolicExecutionRunner

- analyzers/src/SonarAnalyzer.CSharp.Styling/Rules/HelperInTypeName.cs
- analyzers/src/SonarAnalyzer.CSharp/Extensions/SyntaxNodeExtensions.cs
- analyzers/src/SonarAnalyzer.Shared/Extensions/SyntaxNodeExtensions.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Extensions/SyntaxNodeExtensions.cs
- analyzers/tests/SonarAnalyzer.CSharp.Styling.Test/Rules/HelperInTypeName.cs
- analyzers/tests/SonarAnalyzer.CSharp.Styling.Test/TestCases/HelperInTypeName.cs
> New Rule T0006: Avoid Helper in a type name

- its/projects/Styling/File.cs
- its/projects/Styling/NuGet.config
- its/projects/Styling/Styling.csproj
- its/projects/Styling/Styling.sln
- its/src/test/java/com/sonar/it/shared/StylingTest.java
Fixes #9056 
UTs are failing due to an issue with base PR. The functionality of this PR works so it can be reviewed.
> ITs: Add StylingTest

- analyzers/src/SonarAnalyzer.CSharp.Styling/Common/IsExternalInit.cs
- analyzers/src/SonarAnalyzer.CSharp.Styling/Rules/TypeMemberOrdering.cs
- analyzers/src/SonarAnalyzer.Common/Properties/AssemblyInfo.cs
- analyzers/tests/SonarAnalyzer.CSharp.Styling.Test/Rules/TypeMemberOrderingTest.cs
- analyzers/tests/SonarAnalyzer.CSharp.Styling.Test/TestCases/TypeMemberOrdering.cs
- docs/coding-style.md
> New Rule T0008: Respect type member ordering

- analyzers/tests/SonarAnalyzer.CSharp.Styling.Test/Common/StylingRuleTest.cs
> Styling analyzers: Add rules safety net

- analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarAnalysisContextBase.cs
- analyzers/tests/SonarAnalyzer.CSharp.Styling.Test/Rules/FileScopeNamespaceTest.cs
- analyzers/tests/SonarAnalyzer.Test/AnalysisContext/SonarAnalysisContextBaseTest.cs
> Styling analyzers: Respect scope as configured

- analyzers/rspec/cs/S1104.html
- analyzers/rspec/cs/S2094.html
- analyzers/rspec/vbnet/S2094.html
- analyzers/src/SonarAnalyzer.CSharp/sonarpedia.json
- analyzers/src/SonarAnalyzer.VisualBasic/sonarpedia.json
> Update RSPEC before 9.24 release

- analyzers/src/SonarAnalyzer.CSharp.Styling/Rules/AvoidNullable.cs
- analyzers/tests/SonarAnalyzer.CSharp.Styling.Test/Rules/AvoidNullableTest.cs
- analyzers/tests/SonarAnalyzer.CSharp.Styling.Test/TestCases/AvoidNullable.cs
> New Rule T0036: Do not activate a nullable context

- analyzers/src/SonarAnalyzer.CSharp.Styling/Rules/MemberVisibilityOrdering.cs
- analyzers/tests/SonarAnalyzer.CSharp.Styling.Test/Common/StylingRuleTest.cs
- analyzers/tests/SonarAnalyzer.Net8.Test/packages.lock.json
#9136 had a copy/paste issue with Rule ID
> T0009: Fix rule ID

- analyzers/tests/SonarAnalyzer.Test/TestCases/SqlKeywordsDelimitedBySpace.CSharp10.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/SqlKeywordsDelimitedBySpace.CSharp11.cs
> Repro for Fix S2857 FP: Multiple FP on String Interpolation with Verbatim Literal

- analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
> Repro for S2589 FP: Unsigned number doubling by adding with itself inside while loop

- analyzers/src/SonarAnalyzer.CSharp.Styling/Rules/PropertyOrdering.cs
- analyzers/tests/SonarAnalyzer.CSharp.Styling.Test/Rules/PropertyOrderingTest.cs
- analyzers/tests/SonarAnalyzer.CSharp.Styling.Test/TestCases/PropertyOrdering.cs
> New Rule T0014: Move static properties before instance ones

- analyzers/src/SonarAnalyzer.CSharp/Rules/AspNet/ApiControllersShouldNotDeriveDirectlyFromController.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/AspNet/ApiControllersShouldNotDeriveDirectlyFromControllerCodeFix.cs
- analyzers/tests/SonarAnalyzer.Test/Rules/AspNet/ApiControllersShouldNotDeriveDirectlyFromControllerTest.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/AspNet/ApiControllersShouldNotDeriveDirectlyFromController.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/AspNet/ApiControllersShouldNotDeriveDirectlyFromControllerCodeFix.Fixed.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/AspNet/ApiControllersShouldNotDeriveDirectlyFromControllerCodeFix.cs
- analyzers/tests/SonarAnalyzer.TestFramework/Verification/Verifier.cs
> Rule S6961: Implement CodeFix

- analyzers/src/SonarAnalyzer.CSharp/Rules/AspNet/BackslashShouldBeAvoidedInAspNetRoutes.cs
- analyzers/src/SonarAnalyzer.Common/Rules/AspNet/BackslashShouldBeAvoidedInAspNetRoutesBase.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Rules/AspNet/BackslashShouldBeAvoidedInAspNetRoutes.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/AspNet/BackslashShouldBeAvoidedInAspNetRoutes.AspNet4x.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/AspNet/BackslashShouldBeAvoidedInAspNetRoutes.AspNet4x.vb
> Fix AD0001: Named Attribute Arguments in S6930

- analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp8.cs
> Repro for FN 2589: Support redundant recursive pattern null check

- analyzers/src/SonarAnalyzer.CSharp/Rules/AspNet/AvoidUnderPosting.cs
- analyzers/tests/SonarAnalyzer.Test/Rules/AspNet/AvoidUnderPostingTest.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/AspNet/AvoidUnderPosting.cs
> Improve S6964: Include array types and nested collection types

- analyzers/tests/SonarAnalyzer.Test/TestCases/UseConstantLoggingTemplate.cs
> S2629: Add Repro for #9247

- analyzers/src/SonarAnalyzer.CSharp/Rules/AspNet/SpecifyRouteAttribute.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/AspNet/SpecifyRouteAttribute.CSharp12.cs
> Fix S6934 FP: Abstract Controller base class

- .sonarlint/SonarAnalyzer.json
This will simplify binding SL to SC for every new user that didn't have the binding set up.
See MMF-3311
ToDo: 
* Install SL VS, do not setup connected mode
* Open this branch
* Open Team Explorer / SonarQube
* Golden bar should appear to suggest connected mode to the correct project
* Follow the golden bar to setup connected mode
> SonarLint: Use shared connected mode

- scripts/rspec/rspec-templates/Rule.CS.cs
- scripts/rspec/rspec-templates/Rule.VB.cs
- the previous version used a deprecated call
> Update the generated code

- analyzers/src/SonarAnalyzer.Common/Common/AnalyzerLanguage.cs
- analyzers/tests/SonarAnalyzer.Test/Common/AnalyzerLanguageTest.cs
> Styling rules: Do not show RSPEC URL

- analyzers/tests/SonarAnalyzer.Test/TestCases/AspNet/AvoidUnderPosting.CSharp12.cs
> S6964: Add FP repro for #9285

- analyzers/tests/SonarAnalyzer.Test/Rules/Utilities/MetricsAnalyzerTest.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/Utilities/MetricsAnalyzer/_Imports.razor
> Create reproducer for #9288

- analyzers/src/SonarAnalyzer.CSharp/Rules/AspNet/AvoidUnderPosting.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/AspNet/AvoidUnderPosting.CSharp12.cs
> Fix S6964 FP: Property marked with JsonRequired attribute

- analyzers/src/SonarAnalyzer.CFG/ShimLayer/SyntaxKindEx.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/AspNet/AvoidUnderPosting.cs
- analyzers/src/SonarAnalyzer.Common/Extensions/ISymbolExtensions.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/AspNet/AvoidUnderPosting.CSharp12.cs
> Fix S6964 FP: Do not raise in properties with required modifier

- analyzers/src/SonarAnalyzer.CSharp/Rules/AspNet/AnnotateApiActionsWithHttpVerb.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/AspNet/ApiControllersShouldNotDeriveDirectlyFromController.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/AspNet/AvoidUnderPosting.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/AspNet/CallModelStateIsValid.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/AspNet/ControllersHaveMixedResponsibilities.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/AspNet/ControllersReuseClient.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/AspNetMvcHelper.cs
- analyzers/src/SonarAnalyzer.Common/Rules/AspNet/BackslashShouldBeAvoidedInAspNetRoutesBase.cs
- analyzers/src/SonarAnalyzer.Common/Rules/AspNet/RouteTemplateShouldNotStartWithSlashBase.cs
> Split ReferencesControllers method to NetCore and NetFramework variants

- analyzers/tests/SonarAnalyzer.Test/Rules/UseAwaitableMethodTest.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/UseAwaitableMethod_EF.cs
Reproducer for #9269
It also adds some more True Positive examples for [DbContext](https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontext.addrange?view=efcore-8.0) and [DatabaseFacade](https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.infrastructure.databasefacade?view=efcore-8.0).
> S6966: Add FP repro for #9269

- analyzers/tests/SonarAnalyzer.Test/TestCases/AspNet/CallModelStateIsValid.cs
> S6967: Add FP repro for  #9325

- analyzers/its/expected/ManuallyAddedNoncompliantIssues.CS/S6964-IntentionalFindings-net8.0.json
- analyzers/src/SonarAnalyzer.CSharp/Rules/AspNet/AvoidUnderPosting.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/AspNet/AvoidUnderPosting.CSharp12.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/AspNet/AvoidUnderPosting.cs
> S6964: Issue is reported on the attribute instead of the property

- analyzers/src/SonarAnalyzer.CSharp/Rules/UseAwaitableMethod.cs
- analyzers/src/SonarAnalyzer.Common/Extensions/CompilationExtensions.cs
- analyzers/src/SonarAnalyzer.Common/Extensions/MethodSymbolExtensions.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.Implementation.cs
- analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
- analyzers/tests/SonarAnalyzer.Test/Rules/UseAwaitableMethodTest.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/UseAwaitableMethod_FluentValidation.cs
> Fix S6966 FP: FluentValidation ValidateAsync should not be proposed

- analyzers/src/SonarAnalyzer.CSharp/Rules/AspNet/ControllersHaveMixedResponsibilities.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/ParameterTypeShouldMatchRouteTypeConstraint.cs
- analyzers/src/SonarAnalyzer.Common/Common/SecondaryLocation.cs
Follow up of #9343 to remove the last usage
> ReportIssue: Remove SecondaryLocationExtensions

- analyzers/src/SonarAnalyzer.CSharp/Rules/AspNet/UseAspNetModelBinding.cs
- analyzers/tests/SonarAnalyzer.Test/Rules/AspNet/UseAspNetModelBindingTest.cs
> Fix S6932 FP: IFormCollection.Files access should be compliant

- analyzers/src/SonarAnalyzer.CSharp/Extensions/SonarAnalysisContextExtensions.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/ConditionalSimplification.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/GetTypeWithIsAssignableFrom.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/MethodParameterUnused.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/RedundantDeclaration.cs
- analyzers/src/SonarAnalyzer.CSharp/Rules/RedundantInheritanceList.cs
- analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarReportingContextBase.cs
- analyzers/src/SonarAnalyzer.Common/Rules/CheckFileLicenseBase.cs
- analyzers/src/SonarAnalyzer.Common/Rules/UnnecessaryBitwiseOperationBase.cs
Follow up of #9298 effort to add the last missing overload of `ReportIssue`
This PR replaces all usages that use the properties
> ReportIssue: Replace overloads that use properties

- analyzers/src/SonarAnalyzer.CSharp.Styling/Rules/MemberVisibilityOrdering.cs
- analyzers/tests/SonarAnalyzer.CSharp.Styling.Test/TestCases/MemberVisibilityOrdering.cs
> T0009: Add Secondary locations

- docs/coding-style.md
Defines the conventions to follow when defining test scenarios files for C# rules.
Result of the circle around the ["Merge test cases depending on language version" initiative](https://trello.com/c/5uqnuqTM/76-merge-test-cases-depending-on-language-version).
> Conventions on test scenarios files

- analyzers/src/SonarAnalyzer.CSharp/Rules/UseConstantLoggingTemplate.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/UseConstantLoggingTemplate.cs
> Fix S2629 FP: Constant fields in interpolated string

- analyzers/src/SonarAnalyzer.Common/Rules/ClassShouldNotBeEmptyBase.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/ClassShouldNotBeEmpty.cs
> Fix S2094 FP: Allow empty queries

- analyzers/its/regression-test.ps1
Fixes #9393
Review per commit will make it easier to see
> ITs: Regression script does not find differences when ruleId is used

- analyzers/tests/SonarAnalyzer.Test/TestCases/AspNet/AvoidUnderPosting.CSharp9.cs
> S6964: Add FP repro for #9363

- analyzers/src/SonarAnalyzer.CSharp.Styling/Rules/TypeMemberOrdering.cs
- analyzers/tests/SonarAnalyzer.CSharp.Styling.Test/TestCases/TypeMemberOrdering.cs
> T0008: Add Secondary locations

- analyzers/rspec/cs/S1312.html
- analyzers/rspec/cs/S2629.html
- analyzers/rspec/cs/S6668.html
- analyzers/rspec/cs/S6669.html
- analyzers/rspec/cs/S6670.html
- analyzers/rspec/cs/S6672.html
- analyzers/rspec/cs/S6674.html
- analyzers/rspec/cs/S6677.html
- analyzers/src/SonarAnalyzer.CSharp/sonarpedia.json
> Doc: add how to fix section for S1312, S2629, S6668, S6669, S6670, S6672, S6674 and S6677

- analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/InvalidCastToInterface.cs
> S1944 FP: Add reproducer

- analyzers/src/SonarAnalyzer.CSharp/Rules/ExceptionShouldNotBeThrownFromUnexpectedMethods.cs
- analyzers/tests/SonarAnalyzer.Test/Rules/ExceptionShouldNotBeThrownFromUnexpectedMethodsTest.cs
This was supposed to fix #3754, which didn't need any changes. So I just kept the cleanup that I started with
> S3877: Cleanup

- analyzers/tests/SonarAnalyzer.Test/TestCases/UnusedPrivateMember.Fixed.Batch.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/UnusedPrivateMember.Fixed.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/UnusedPrivateMember.cs
> Revert S1144 FN: Unused private methods with attributes is not an FN

- analyzers/src/SonarAnalyzer.CSharp/Rules/RedundancyInConstructorDestructorDeclaration.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/RedundancyInConstructorDestructorDeclaration.CSharp12.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/RedundancyInConstructorDestructorDeclaration.CSharp9.Fixed.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/RedundancyInConstructorDestructorDeclaration.CSharp9.cs
> Fix S3253 FP:  Don't raise for primary constructor in type declarations without parameters when they inherit from types with parameters

- analyzers/rspec/cs/S6608.html
> Rule S6608: update benchmark sample code and report

- analyzers/tests/SonarAnalyzer.Test/Rules/UnusedPrivateMemberTest.cs
- analyzers/tests/SonarAnalyzer.TestFramework/MetadataReferences/NuGetMetadataFactory.cs
> S1144: Add FP repro for #9416

- analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.cs
> S4158/S2583: Add FP repro for #9425

- analyzers/src/SonarAnalyzer.CSharp/Rules/ConditionalStructureSameImplementation.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/ConditionalStructureSameImplementation_If.cs
FN after fixing #1255
Lost issues:
- https://peach.aws-prd.sonarsource.com/code?id=dnspy&selected=dnspy:dnSpy/Roslyn/Roslyn.ExpressionCompiler/Core/ExpressionCompiler/CommonGeneratedNames.cs&line=348
- https://peach.aws-prd.sonarsource.com/code?id=jellyfin&selected=jellyfin:Jellyfin.Networking/Manager/NetworkManager.cs&line=1184
> Fix S1871 FN: Chained else if without else

- analyzers/src/SonarAnalyzer.CFG/LiveVariableAnalysis/RoslynLiveVariableAnalysis.cs
- analyzers/tests/SonarAnalyzer.Test/LiveVariableAnalysis/RoslynLiveVariableAnalysisTest.TryCatchFinally.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/DeadStores.RoslynCfg.cs
> Fix S1854 FP: Value used in finally should LiveIn after throw

- analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.cs
> S4158: Add repro for #9444

- analyzers/src/SonarAnalyzer.CFG/LiveVariableAnalysis/RoslynLiveVariableAnalysis.cs
- analyzers/tests/SonarAnalyzer.Test/LiveVariableAnalysis/RoslynLiveVariableAnalysisTest.TryCatchFinally.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/DeadStores.RoslynCfg.cs
> Fix S1854 FP: Value used in finally should LiveIn for all try blocks

- analyzers/tests/SonarAnalyzer.Test/TestCases/MethodsShouldNotHaveIdenticalImplementations.cs
Add a test case for an tricky TN found while [peach validation](https://github.com/SonarSource/sonar-dotnet/pull/9398#issuecomment-2186769972) of #9398
This makes sure, we do not introduce a regression here in the future.
> S4144: Add test case "InheritedConstraints"

- analyzers/its/expected/Nancy/S3247-Nancy-net452.json
- analyzers/its/expected/Nancy/S3247-Nancy-netstandard2.0.json
- analyzers/its/expected/Nancy/S3247-Nancy.ViewEngines.Razor-net452.json
- analyzers/its/expected/akka.net/S3247-Akka-netstandard2.0.json
- analyzers/its/expected/akka.net/S3247-Akka.DistributedData-netstandard2.0.json
- analyzers/its/expected/akka.net/S3247-Akka.Streams-netstandard2.0.json
- analyzers/its/expected/akka.net/S3247-Akka.Tests.Performance-netcoreapp3.1.json
- analyzers/its/expected/akka.net/S3247-Akka.Tests.Shared.Internals-netstandard2.0.json
- analyzers/src/SonarAnalyzer.CSharp/Rules/CastShouldNotBeDuplicated.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/CastShouldNotBeDuplicated.CSharp11.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/CastShouldNotBeDuplicated.CSharp12.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/CastShouldNotBeDuplicated.CSharp9.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/CastShouldNotBeDuplicated.cs
> Fix S3247 FN: Support structs

- analyzers/its/expected/Nancy/S3247-Nancy-net452.json
- analyzers/its/expected/Nancy/S3247-Nancy-netstandard2.0.json
- analyzers/its/expected/akka.net/S3247-Akka-netstandard2.0.json
- analyzers/its/expected/akka.net/S3247-Akka.Cluster-netstandard2.0.json
- analyzers/its/expected/akka.net/S3247-Akka.Persistence-netstandard2.0.json
- analyzers/its/expected/akka.net/S3247-Akka.Remote-netstandard2.0.json
- analyzers/its/expected/akka.net/S3247-Akka.Streams-netstandard2.0.json
- analyzers/src/SonarAnalyzer.CSharp/Rules/CastShouldNotBeDuplicated.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/CastShouldNotBeDuplicated.cs
> Fix S3247 FN: Detect is-as and is-is combinations

- analyzers/src/SonarAnalyzer.CSharp/Rules/GetTypeWithIsAssignableFrom.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/GetTypeWithIsAssignableFrom.Fixed.Batch.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/GetTypeWithIsAssignableFrom.Fixed.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/GetTypeWithIsAssignableFrom.cs
> S2219 FP: Is operator used for pattern matching

- analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/PublicMethodArgumentsShouldBeCheckedForNull.cs
> S3900: Add Repro for #9500

- analyzers/tests/SonarAnalyzer.Test/TestCases/GenericTypeParameterEmptinessChecking.CSharp9.cs
> Reproducer for S2955 FP: Comparing nullable type with null

- analyzers/tests/SonarAnalyzer.Test/TestCases/AbstractClassToInterface.cs
> Reproducer for S1694 FP: Abstract class with field or constructor

- analyzers/rspec/cs/S1144.html
- analyzers/rspec/cs/S2699.html
- analyzers/rspec/cs/S3247.html
- analyzers/src/SonarAnalyzer.CSharp/sonarpedia.json
- analyzers/src/SonarAnalyzer.VisualBasic/sonarpedia.json
> Update RSPEC before 9.29 release

- analyzers/src/SonarAnalyzer.CFG/LiveVariableAnalysis/RoslynLiveVariableAnalysis.cs
- analyzers/tests/SonarAnalyzer.Test/LiveVariableAnalysis/RoslynLiveVariableAnalysisTest.FlowCaptureOperation.cs
- analyzers/tests/SonarAnalyzer.Test/LiveVariableAnalysis/RoslynLiveVariableAnalysisTest.LocalFunction.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/DeadStores.RoslynCfg.cs
> LVA: Resolve FlowCapture and FlowCaptureReference operations to symbols instead of operations

- analyzers/tests/SonarAnalyzer.Test/Rules/UseConstantLoggingTemplateTest.cs
> Repro for S2629 on log4net.Error(Exception)

- analyzers/tests/SonarAnalyzer.Test/TestCases/UseReturnStatement.vb
> Repro for #9553: Fix S5944 FP: AddressOf(MethodName) in Return statement

- analyzers/its/expected/CSharpLatest/S1854-CSharpLatest-net8.0.json
- analyzers/src/SonarAnalyzer.CFG/LiveVariableAnalysis/RoslynLiveVariableAnalysis.cs
- analyzers/tests/SonarAnalyzer.Test/LiveVariableAnalysis/RoslynLiveVariableAnalysisTest.FlowCaptureOperation.cs
- analyzers/tests/SonarAnalyzer.Test/LiveVariableAnalysis/RoslynLiveVariableAnalysisTest.LocalFunction.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/DeadStores.RoslynCfg.cs
This reverts commit 2c9c49a326b620ed7c8397e61a3fd59fcad89697.
This commit revealed some FPs, some of which are tricky. 
Since we want to release on Monday the idea is to revert this commit for now, we release and we will emerge + fix after so that the we don't risk delaying due to validation.
> Revert "Fix S1854 FN: Support &&, ||, ?? and ??= (#9536)"

- sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/UnitTestResultsProvider.java
- sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/UnitTestResultsProviderTest.java
> SQ Plugin: Add xUnit report path to the UI

- analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
> Repro for S2583 FP: Custom indexer and removal method

- analyzers/src/SonarAnalyzer.ShimLayer.CodeGeneration/OperationLightupGenerator.cs
- analyzers/src/SonarAnalyzer.ShimLayer/OperationInterfaces.xml
> ShimLayer: Add support for OperationInterfaces

- analyzers/src/SonarAnalyzer.ShimLayer.CodeGeneration/OperationLightupGenerator.cs
Contributes to #9599 
Synchronized with the latest master: https://github.com/DotNetAnalyzers/StyleCopAnalyzers/commit/ff5c432467adee16db82b657f0d53c35a8d9eb71
> ShimLayer: Synchonize OperationLightupGenerator with StyleCop

- analyzers/src/SonarAnalyzer.CSharp/Rules/ExpectedExceptionAttributeShouldNotBeUsed.cs
- analyzers/src/SonarAnalyzer.Common/Rules/ExpectedExceptionAttributeShouldNotBeUsedBase.cs
- analyzers/src/SonarAnalyzer.VisualBasic/Rules/ExpectedExceptionAttributeShouldNotBeUsed.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/ExpectedExceptionAttributeShouldNotBeUsed.MsTest.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/ExpectedExceptionAttributeShouldNotBeUsed.MsTest.vb
> S3431: Optimize rule

- analyzers/tests/SonarAnalyzer.Test/Rules/Hotspots/ExecutingSqlQueriesTest.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/Hotspots/ExecutingSqlQueries.Dapper.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/Hotspots/ExecutingSqlQueries.EntityFrameworkCore2.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/Hotspots/ExecutingSqlQueries.EntityFrameworkCore2.vb
- analyzers/tests/SonarAnalyzer.Test/TestCases/Hotspots/ExecutingSqlQueries.EntityFrameworkCoreLatest.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/Hotspots/ExecutingSqlQueries.EntityFrameworkCoreLatest.vb
- analyzers/tests/SonarAnalyzer.Test/TestCases/Hotspots/ExecutingSqlQueries.MySqlData.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/Hotspots/ExecutingSqlQueries.NHibernate.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/Hotspots/ExecutingSqlQueries.Net46.cs
- analyzers/tests/SonarAnalyzer.Test/TestCases/Hotspots/ExecutingSqlQueries.Net46.vb
> Repro for S2077: Ternary in formatted string

- analyzers/rspec/cs/S2325.html
- analyzers/rspec/cs/S2674.html
- analyzers/src/SonarAnalyzer.CSharp/sonarpedia.json
- analyzers/src/SonarAnalyzer.VisualBasic/sonarpedia.json
> Update RSPEC before 9.32 release
