SonarSource/sonar-dotnet

analyzers/src/SonarAnalyzer.CSharp/Rules/DisposableNotDisposed.cs

Rename variables to improve readability in `DisposableNotDisposed ` (S2930).
Original issue: #5879 ([comment](https://github.com/SonarSource/sonar-dotnet/pull/6660#discussion_r1086712611))

Improve S2930: Rename variables

---

.github/dependabot.yml

I've noticed that we're not getting NuGet updates on this repo. 
This changes directory to the one with SLN file.

Dependabot: Use Analyzers directory for NuGet

---

its/src/test/java/com/sonar/it/csharp/AnalysisWarningsTest.java

All C# ITs references and starts `com.sonar.it.csharp.Tests.ORCHESTRATOR`. And are executed in `Tests: Java ITs CSharp` CI step.
`AnalysisWarningsTest` was referencing `com.sonar.it.shared.Tests.ORCHESTRATOR`, a separate orchestrator instance that started a 2nd instance of SQ of the same CI step.
`com.sonar.it.shared.Tests.ORCHESTRATOR` should be used only by `shared` integration tests that are executed in `Tests: Java ITs Others` step.

Java ITs CSharp: Start orchestrator only once

---

analyzers/src/SonarAnalyzer.CSharp/Rules/SillyMathematicalComparison.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SillyMathematicalComparison.cs

[Example FP](https://peach.sonarsource.com/project/issues?languages=cs&resolved=false&rules=csharpsquid%3AS2198&id=_NET_Team&open=AYY-IcRInuGymX21wEA8)
Generally looks like:
```csharp
const float i = float.PositiveInfinity;
float x = 42;
_ = 42 >= i; // Should NOT raise
```

Fix S2198 FP: Exclude Infinity checks 

---

analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/ConditionEvaluatesToConstantTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/EmptyCollectionsShouldNotBeEnumeratedTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/EmptyNullableValueAccessTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/HashesShouldHaveUnpredictableSaltTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/InitializationVectorShouldBeRandomTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/InvalidCastToInterfaceTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/NullPointerDereferenceTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/ObjectsShouldNotBeDisposedMoreThanOnceTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/PublicMethodArgumentsShouldBeCheckedForNullTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/RestrictDeserializedTypesTest.cs

The commit messages contains two changes:
* Align naming in NRE rule - this is the main change
* Align all other affected rules to prepare them for Roslyn migration - this is just mechanical follow up to prepare other rules

Rename verifiers in SE rules

---

analyzers/src/SonarAnalyzer.CSharp/Rules/SqlKeywordsDelimitedBySpace.cs
analyzers/tests/SonarAnalyzer.UnitTest/MetadataReferences/NuGetMetadataReference.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/SqlKeywordsDelimitedBySpaceTest.cs

Support `Microsoft.Data.SqlClient` in S2857.

---

analyzers/its/expected/Roslyn.1.3.1/Roslyn.1.3.1--net452-S1450.json
analyzers/its/expected/Roslyn.1.3.1/Roslyn.1.3.1--net452-S2221.json
analyzers/its/expected/Roslyn.1.3.1/Roslyn.1.3.1--net452-S2259.json
analyzers/its/expected/Roslyn.1.3.1/Roslyn.1.3.1--net452-S2325.json
analyzers/its/expected/Roslyn.1.3.1/Roslyn.1.3.1--net452-S3353.json
analyzers/its/expected/Roslyn.1.3.1/Roslyn.1.3.1--net452-S3900.json
analyzers/its/sources/Roslyn.1.3.1/OldRoslyn.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/Utilities/AnalysisWarningAnalyzer.cs
analyzers/src/SonarAnalyzer.Common/Rules/Utilities/AnalysisWarningAnalyzerBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/Utilities/AnalysisWarningAnalyzer.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/AnalysisWarningAnalyzerTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/CopyPasteTokenAnalyzerTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/LogAnalyzerTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/SymbolReferenceAnalyzerTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/TokenTypeAnalyzerTest.cs
its/projects/Roslyn.1.3.1/OldRoslyn.cs
its/projects/Roslyn.1.3.1/Roslyn.1.3.1.csproj
its/projects/Roslyn.1.3.1/Roslyn.1.3.1.sln
its/projects/Roslyn.1.3.1/packages.lock.json
its/src/test/java/com/sonar/it/csharp/AnalysisWarningsTest.java

Fixes #6678
MsBuild 14 is bound with Roslyn 1.x
MsBuild 15 is bound with Roslyn 2.x
We're fine with MsBuild 16+ and Roslyn 3.x+
https://learn.microsoft.com/en-us/visualstudio/extensibility/roslyn-version-support?view=vs-2022
While it is possible to have MsBuild 16+ and use Roslyn 1.x with it (see the trick in ITs), it's a corner case that we'll ignore as we can't detect MsBuild version from within Roslyn without help of Scanner for .NET.
The analyzer complains when old Roslyn is used and that's also correct behavior. As bumping Roslyn dependency will make it stop working on that Roslyn, no matter what MsBuild is used.
---
SQ plugin (the java part) already has a [mechanism](https://github.com/SonarSource/sonar-dotnet/blob/master/sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotn …

Report deprecation analysis warning for MsBuild 14/15

---

analyzers/src/SonarAnalyzer.CSharp/Rules/Utilities/TokenTypeAnalyzer.cs
analyzers/src/SonarAnalyzer.Common/Rules/Utilities/TokenTypeAnalyzerBase.cs
analyzers/src/SonarAnalyzer.Common/Rules/Utilities/UtilityAnalyzerBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/Utilities/TokenTypeAnalyzer.cs

The current implementation of the `TokenTypeAnalyzerBase` has the following problems:
* It allocates a new TokenClassifierBase per Token
* It does an "OrderBy" after all classification is collected
* It does a span-based text lookup in the tree for each classification
This PR changes how the TokenClassifierBase operates.
Instead of one new TokenClassifierBase per Token, the TokenClassifierBase is now created once per document. The token is passed to `ClassifyToken`.  `ClassifyToken` was changed
* from adding `TokenInfo` into the collecting list
* to returning the `TokenInfo` to the caller
The trivia handling was extracted into `TriviaClassifierBase` to allow `TokenClassifierBase.ClassifyToken()` to return a single `TokenInfo` instead of a list. The trivia is now processed before …

Performance: Token Type Utility Analyzer: Avoid allocations

---

analyzers/tests/SonarAnalyzer.UnitTest/CFG/Roslyn/BasicBlockTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/CFG/Roslyn/CaptureIdTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/CFG/Sonar/SonarControlFlowGraphTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Common/BidirectionalDictionaryTests.cs
analyzers/tests/SonarAnalyzer.UnitTest/Common/DistrubtionTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Common/MetricsTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Helpers/DiagnosticDescriptorFactoryTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Helpers/MethodParameterLookupTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Helpers/OperationExecutionOrderTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Helpers/SymbolHelperTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Json/JsonWalkerTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/SymbolReferenceAnalyzerTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/SonarAnalyzer.UnitTest.csproj
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ExplodedNodeTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Invocation.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Sonar/SonarExplodedGraphTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Sonar/SymbolicValues/NullableSymbolicValue_TrySetConstraint.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Sonar/SymbolicValues/NullableSymbolicValue_TrySetOppositeConstraint.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Sonar/SymbolicValues/SymbolicValue_TrySetConstraint.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/FluentTestHelper.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SymbolicExecution/ValidatorTestCheck.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Tests/IssueLocationCollectorTest.GetExpectedIssueLocations.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Tests/IssueLocationCollectorTest.GetIssueLocations.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Tests/ParseOptionsHelperTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Tests/VerifierBuilderTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestSuiteInitialization.cs
analyzers/tests/SonarAnalyzer.UnitTest/packages.lock.json

See also https://fluentassertions.com/upgradingtov6
The main changes made are with respect to collections.
* The custom `OnlyContainInOrder` and `OnlyContain` are replaced
* `OnlyContainInOrder` -> `Equal`
* `OnlyContain` -> `BeEquivalentTo`
* `BeEquivalentTo` -> needs an array to be passed in now.
* Support for non-generic collections was dropped in V6 which results in some `.Cast<object>()` intermediate steps.
* Equivalence checks changed in some edge cases.

Packages: Upgrade FluentAssertions

---

analyzers/src/SonarAnalyzer.CSharp/Rules/PrivateStaticMethodUsedOnlyByNestedClass.cs

Fixes #6706 
[RSPEC PR](https://github.com/SonarSource/rspec/pull/1572)

Improve S3398: Fix code smells

---

analyzers/src/SonarAnalyzer.CSharp/Facade/CSharpSyntaxFacade.cs
analyzers/src/SonarAnalyzer.Common/Facade/SyntaxFacade.cs
analyzers/src/SonarAnalyzer.Common/Rules/DebuggerDisplayUsesExistingMembersBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Facade/VisualBasicSyntaxFacade.cs

Relates to https://github.com/SonarSource/sonar-dotnet/pull/6760
https://github.com/SonarSource/sonar-dotnet/pull/6760 has introduced a new method `IsKnownAttribute` in `SyntaxFacade` for the needs of https://github.com/SonarSource/sonar-dotnet/issues/6703.
This PR does cleanup of https://github.com/SonarSource/sonar-dotnet/pull/6760, fixing the order of parameters of the new API, to conform to code conventions.

SyntaxFacade: fix the order of parameters in IsKnownAttributeType

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/References.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Nullable.cs

Part of #6812
Copy known constraints from nullable symbol to `.Value` property.
```C#
bool? nullable = true;          // nullable symbol is known to have True constraint after this
var result = nullable.Value;  // True constraint from symbol nullable should get propagated to its Value property so it can be assigned to the result symbol later
```

SE - Nullable: Copy constraints to `Value` property

---

analyzers/rspec/cs/S4433_c#.html
analyzers/rspec/cs/S4545_c#.html
analyzers/rspec/vbnet/S4545_vb.net.html
analyzers/src/SonarAnalyzer.CSharp/sonarpedia.json
analyzers/src/SonarAnalyzer.VisualBasic/sonarpedia.json

Update RSPEC for 8.54 release

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/References.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Nullable.cs

Part of #6812
Set `BoolConstraint` on `.HasValue` from known `ObjectConstraint`, if present.
Do not set `NotNull` for the symbol itself, as `something.HasValue` doesn't mean it cannot be null in this case.

SE - Nullable: Infer constraints for `HasValue` property

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationDispatcher.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/ObjectCreation.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Invocation.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Nullable.cs

Part of #6812 
`new Nullable<int>()` should have `Null` constraint

SE - Nullable: Add `Null` constraint for empty nullable constructor

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyNullableValueAccess.CSharp10.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyNullableValueAccess.CSharp11.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyNullableValueAccess.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyNullableValueAccess.cs

S3655: Prepare TestCases

---

analyzers/src/SonarAnalyzer.CSharp/Facade/CSharpFacade.cs
analyzers/src/SonarAnalyzer.CSharp/Helpers/CSharpMethodParameterLookup.cs
analyzers/src/SonarAnalyzer.CSharp/Helpers/CSharpSyntaxHelper.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/AssertionArgsShouldBePassedInCorrectOrder.cs
analyzers/src/SonarAnalyzer.CSharp/Trackers/CSharpObjectCreationTracker.cs
analyzers/src/SonarAnalyzer.CSharp/Wrappers/ObjectCreationFactory.cs
analyzers/src/SonarAnalyzer.Common/Facade/ILanguageFacade.cs
analyzers/src/SonarAnalyzer.Common/Helpers/MethodParameterLookupBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Facade/VisualBasicFacade.cs
analyzers/src/SonarAnalyzer.VisualBasic/Helpers/VisualBasicMethodParameterLookup.cs
analyzers/src/SonarAnalyzer.VisualBasic/Helpers/VisualBasicSyntaxHelper.cs
analyzers/src/SonarAnalyzer.VisualBasic/Trackers/VisualBasicObjectCreationTracker.cs
analyzers/tests/SonarAnalyzer.UnitTest/Facade/CSharpFacadeTests.cs
analyzers/tests/SonarAnalyzer.UnitTest/Facade/VisualBasicFacadeTests.cs
analyzers/tests/SonarAnalyzer.UnitTest/Helpers/MethodParameterLookupTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/AssertionArgsShouldBePassedInCorrectOrderTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/AssertionArgsShouldBePassedInCorrectOrder.MsTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/AssertionArgsShouldBePassedInCorrectOrder.NUnit.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/AssertionArgsShouldBePassedInCorrectOrder.Xunit.cs

Fix S3415 FP/FN: Support named arguments

---

analyzers/src/SonarAnalyzer.CFG/CfgSerializer/CfgSerializer.RoslynCfgWalker.cs
analyzers/src/SonarAnalyzer.CFG/Extensions/IOperationExtensions.cs
analyzers/src/SonarAnalyzer.CFG/ShimLayer/CaptureId.cs
analyzers/tests/SonarAnalyzer.UnitTest/CFG/Roslyn/RoslynCfgSerializerTest.cs

There are a lot of #numbers in the CFG serialization that make it unclear that #0, #1, #2 and so on sometimes mean a capture reference. This change will make it clear.
Old serialization:
```
1# FlowCaptureReferenceOperation: #0 / IdentifierNameSyntax: arg
```
New serialization:
```
1# FlowCaptureReferenceOperation: #Capture-0 / IdentifierNameSyntax: arg
```

SE: Serialize Captures with prefix

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/ObjectCreation.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SymbolicValue.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Nullable.cs

Part of #6812 
Set argument constraints for `new Nullable<int>(value)` or `new Nullable<int>(42)`
This is a draft, the 1st `Squash 03-NewArg` commit doesn't need a review as it is in #6853

SE - Nullable: Propagate constraints via nullable constructor

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Conversion.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Nullable.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs

Part of #6812
Add UTs for implicit and explicit conversions to be sure they work as expected.

SE - Nullable: Add UT for conversions

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationDispatcher.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Assignment.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Binary.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/BranchingProcessor.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IsNull.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IsPattern.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IsType.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/References.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/ProgramState.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ProgramStateTest.OperationValue.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Nullable.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs

Part of #6812
`PropertyReference` will need to be a branching processor. This changes its base class. The actual branching implementation will be done later.
There's one slight change in the conditions. From `nullable.Value`, we now learn that `nullable` cannot be null. Because it would throw otherwise.
This is a draft, rebase will be needed. Commits `Squash 04-NewArg` and `Squash 05-Conversions` do not need a review.

SE - Nullable: Change `PropertyReference` to branching processor

---

analyzers/src/SonarAnalyzer.CSharp/Rules/RedundantCast.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/RedundantCastTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundantCast.CSharp8.cs

Fix S1905 FP: Nullability context and array of anonymous types

---

analyzers/src/SonarAnalyzer.CSharp/Rules/TestMethodShouldContainAssertion.cs
analyzers/src/SonarAnalyzer.Common/Extensions/AttributeDataExtensions.cs
analyzers/src/SonarAnalyzer.Common/Helpers/SymbolHelper.cs
analyzers/tests/SonarAnalyzer.UnitTest/Extensions/AttributeDataExtensionsTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Helpers/SymbolHelperTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/TestMethodShouldContainAssertion.Custom.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SnippetCompiler.cs

Fix S2699 FP: Support overridden methods annotated with AssertionMethodAttribute

---

docs/contributing-plugin.md
scripts/build/dev-build.ps1

the `local-analyzer` maven profile had been deleted in  #5839

Remove inexistent mvn profile from build script

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Checks/ConstantCheck.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.LearnConstraint.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.cs

Part of #8612
Fixes #6241
Same functionality as we had for reference types, but for nullable types.
```
if(arg == null)
// We know arg is Null
else
// We know arg is NotNull
```
The problem here was, that `if(arg == null)`, the `null` literal doesn't have any `Type` in the CFG. So we were missing the `Null` constraint on it.

SE - Nullable: Learn object constraint from equals

---

analyzers/src/SonarAnalyzer.Common/Helpers/HashCode.cs
analyzers/tests/SonarAnalyzer.UnitTest/Helpers/DictionaryExtensionsTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Helpers/HashCodeTest.cs

Dictionaries don't maintain a order so these both dictionaries should be identical
* `["A" = 1, "B" = 2]`
* `["B" = 2, "A" = 1]`
`Hashcode.DictionaryContentHash` returns different hashcodes for both dictionaries.
See the failing test cases here https://dev.azure.com/sonarsource/DotNetTeam%20Project/_build/results?buildId=64968&view=ms.vss-test-web.build-test-results-tab

Fix SE: DictionaryContentHash is not stable to ordering

---

analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarAnalysisContextBase.cs
analyzers/src/SonarAnalyzer.Common/DiagnosticAnalyzer/ParametrizedDiagnosticAnalyzer.cs
analyzers/src/SonarAnalyzer.Common/Helpers/SonarLintXmlReader.cs
analyzers/src/SonarAnalyzer.Common/Rules/Utilities/UtilityAnalyzerBase.cs
analyzers/tests/SonarAnalyzer.UnitTest/AnalysisContext/SonarAnalysisContextBaseTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Helpers/ParameterLoaderTest.cs

Addresses comments from #6870
Review each commit separately.

SonarAnalysisContextBase refactoring

---

analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarAnalysisContextBase.cs
analyzers/src/SonarAnalyzer.Common/Helpers/WildcardPatternMatcher.cs
analyzers/tests/SonarAnalyzer.UnitTest/Helpers/WildcardPatternMatcherTest.cs

This PR aims to address the comments on the WildcardPatternMatcher, see [feature branch PR](https://github.com/SonarSource/sonar-dotnet/pull/6870).

Wildcard pattern matcher improvement

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Binary.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.LearnConstraint.cs

Part of #6812
```
if(arg == 42)
// We know arg is NotNull
else
// We don't know anything. It could be another NotNull, or it could be Null
```
Rebase will be needed once #6923 is merged

SE - Nullable: Learn object constraint from value comparison

---

analyzers/src/SonarAnalyzer.Common/Helpers/TypeHelper.cs
analyzers/tests/SonarAnalyzer.UnitTest/Helpers/TypeHelperTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.LearnConstraint.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs

Part of #6105
This PR adds support for T in `<T> where T: struct` being recognized as non-nullable value type. 
Next PR: Tests for such constraints when used e.g. so `M(T? t)` will ensure that this is recognized as a nullable value type.

SE - Non-nullable value types: Add support for constrained generics

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Invocation.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/ProgramState.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Nullable.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SymbolicExecution/PreserveTestCheck.cs

Part of #6812
```
value = nullable.GetValueOrDefault();
```
Depending on the `nullable`, we can learn
* `Null` => `NotNull`, and in case of `bool` also `False`.
* `NotNull` => propagate constraints like with `nullable.Value`
* no symbolic value => do nothing, `NonNullableValueTypeCheck` will give us `NotNull` for the value type

SE - Nullable: Add support for `nullable.GetValueOrDefault()`

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/ProgramState.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SymbolicValue.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/SymbolicValueTest.cs

Part of #6964
See also #6105
Implementation of sub-task:
The idea is to have a fast cache for SymbolValues that can be accessed allocation free. If a SymbolValue is manipulated via `WithConstraint` or `WithoutConstraint` the result of the newly constructed SymbolValue is taken from the cache (or added during first use). The current implementation is using a single constraint cache, meaning: Only SymbolValues with a single constraint are cached. The current cache implementation supports the following SymbolValue operations:
* A new constraint added to SymbolValue.Empty (here still SymbolValue.Constraintless)
* Exchange of a constraint of the same type for a SymbolValue with only a single Constraint
* Constraint removed from a single constraint SymbolValue (produced  SymbolValue.Empty)
* …

SE - Add cache for SymbolicValues

---

analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarAnalysisContextBase.cs
analyzers/src/SonarAnalyzer.Common/Helpers/SonarLintXml.cs
analyzers/src/SonarAnalyzer.Common/Helpers/SonarLintXmlReader.cs
analyzers/tests/SonarAnalyzer.UnitTest/Helpers/SonarLintXmlReaderTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/ResourceTests/SonarLintXml/Duplicated_Properties/SonarLint.xml

SonarLintXmlReader refactoring

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Invocation.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Invocation.cs

Fixes #6812 
Support for `object.Equals(left, right)` has some (limited) capabilities. This PR introduces the same functionality for `nullable.Equals(arg)`

SE - Nullable: Add support for nullable.Equals(arg)

---

analyzers/src/SonarAnalyzer.CSharp/Rules/ObsoleteAttributes.cs
analyzers/src/SonarAnalyzer.Common/Rules/ObsoleteAttributesBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/ObsoleteAttributes.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/ObsoleteAttributesTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ObsoleteAttributesNeedExplanation.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ObsoleteAttributesNeedExplanation.VB14.vb
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ObsoleteAttributesNeedExplanation.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ObsoleteAttributesNeedExplanation.vb

As mentioned by @martin-strecker-sonarsource reading the arguments should be improved. Result of a remark in #6593 .

Fix S1123 FN: The explanation should not be null or whitespace

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Invocation.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Invocation.cs

Part of #6812
Add UTs to make sure we learn from `Debug.Assert`

SE - Nullable: Add UTs for Debug.Assert

---

analyzers/src/SonarAnalyzer.Common/Helpers/HashCode.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/ProgramState.cs
analyzers/tests/SonarAnalyzer.UnitTest/Helpers/HashCodeTest.cs

SE: Enumerable ContentHash for ordered and unordered sets

---

analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/PublicMethodArgumentsShouldBeCheckedForNull.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Extensions/IOperationExtensions.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/PublicMethodArgumentsShouldBeCheckedForNull.CSharp11.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/PublicMethodArgumentsShouldBeCheckedForNull.CSharp8.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/PublicMethodArgumentsShouldBeCheckedForNull.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/PublicMethodArgumentsShouldBeCheckedForNull.cs

Part of https://github.com/SonarSource/sonar-dotnet/issues/6793
Task 4
This PR works without [the implementation of ShouldExecute()](https://github.com/SonarSource/sonar-dotnet/pull/6942), so some of test cases have FPs, due to the visibility of the method not being checked.
[Re-assignment of the method parameters](https://github.com/SonarSource/sonar-dotnet/issues/6972) will be taken care of in a separate PR, as well as the re-organization/cleanup of the test cases.

S3900: Basic rule implementation

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SymbolicValue.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/SymbolicValueTest.cs

SE: Caching: Cache "GetHashCode" for SymbolicValue

---

analyzers/src/SonarAnalyzer.CFG/ShimLayer/LightupHelpers.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/ReturnEmptyCollectionInsteadOfNull.cs
analyzers/src/SonarAnalyzer.Common/Helpers/TypeHelper.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ReturnEmptyCollectionInsteadOfNull.CSharp8.cs

Fixes #6878
Fixes #6825
Add a check on the return type to check nullability.

Fix S1168 FP: Does not respect nullable annotations

---

analyzers/src/SonarAnalyzer.VisualBasic/SymbolicExecution/Roslyn/EmptyNullableValueAccess.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyNullableValueAccess.vb

Fix S3655 FN: VB implicit conversions

---

analyzers/src/SonarAnalyzer.Common/Helpers/SonarLintXmlReader.cs

Line
```
public static readonly SonarLintXmlReader Empty = new(null);
```
sends `null` into constructor, that was propagated into `ParseContent` where it threw `NullReferenceException` due to `.ToString()`, that was caught by `catch` and `.Empty` was returned.

SonarLintXmlReader: Do not depend on exception logic

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyNullableValueAccess.cs

Part 3 of task 6 of https://github.com/SonarSource/sonar-dotnet/issues/6794
Previous task: https://github.com/SonarSource/sonar-dotnet/pull/6967

S3655: Fields with methods, local functions, yield and async

---

analyzers/its/expected/akka.net/Akka.Streams--netstandard2.0-S2259.json
analyzers/its/expected/akka.net/Akka.Streams--netstandard2.0-S3900.json
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Extensions/IOperationExtensions.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/IOperationExtensionsTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.IsNull.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.CSharp8.cs

Fix S2259 FP: Do not track symbol via TryCast

---

analyzers/its/expected/Automapper/AutoMapper--net461-S3900.json
analyzers/its/expected/Automapper/AutoMapper--netstandard2.0-S3900.json
analyzers/its/expected/Nancy/Nancy--net452-S3900.json
analyzers/its/expected/Nancy/Nancy--netstandard2.0-S3900.json
analyzers/its/expected/Nancy/Nancy.Hosting.Aspnet--net452-S3900.json
analyzers/its/expected/Nancy/Nancy.Testing--net452-S3900.json
analyzers/its/expected/Nancy/Nancy.Testing--netstandard2.0-S3900.json
analyzers/its/expected/Nancy/Nancy.Validation.DataAnnotations--net452-S3900.json
analyzers/its/expected/Nancy/Nancy.Validation.FluentValidation--net452-S3900.json
analyzers/its/expected/Nancy/Nancy.Validation.FluentValidation--netstandard2.0-S3900.json
analyzers/its/expected/Net5/Net5--net5.0-S3900.json
analyzers/its/expected/Net6/NullableReferenceTypesExample--net6.0-S3900.json
analyzers/its/expected/akka.net/Akka--netstandard2.0-S3900.json
analyzers/its/expected/akka.net/Akka.Cluster--netstandard2.0-S3900.json
analyzers/its/expected/akka.net/Akka.MultiNodeTestRunner.Shared--netstandard2.0-S3900.json
analyzers/its/expected/akka.net/Akka.Persistence--netstandard2.0-S3900.json
analyzers/its/expected/akka.net/Akka.Persistence.Sql.Common--netstandard2.0-S3900.json
analyzers/its/expected/akka.net/Akka.Persistence.TestKit--netstandard2.0-S3900.json
analyzers/its/expected/akka.net/Akka.Remote.TestKit--netstandard2.0-S3900.json
analyzers/its/expected/akka.net/Akka.Streams.TestKit--netstandard2.0-S3900.json
analyzers/its/expected/akka.net/Akka.Tests.Shared.Internals--netstandard2.0-S3900.json
analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/PublicMethodArgumentsShouldBeCheckedForNull.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/PublicMethodArgumentsShouldBeCheckedForNull.cs

Part of https://github.com/SonarSource/sonar-dotnet/issues/6997
Task 1 and 9

Fix S3900 FN: Conversion operations

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyNullableValueAccess.cs

Part 5 of task 6 of https://github.com/SonarSource/sonar-dotnet/issues/6794
Previous task: https://github.com/SonarSource/sonar-dotnet/pull/6989

S3655: Boxing

---

its/src/test/java/com/sonar/it/csharp/Tests.java

The security plugin version 7.3.0.1282 was added to Java ITs with #1930 for the UCFGDeserializationTest class. 
We don't have this test anymore since the security-frontend was moved outside of this repo.

Removing unused security plugin from Java ITs

---

analyzers/its/expected/Automapper/AutoMapper--net461-S3900.json
analyzers/its/expected/Automapper/AutoMapper--netstandard2.0-S3900.json
analyzers/its/expected/Nancy/Nancy--net452-S3900.json
analyzers/its/expected/Nancy/Nancy--netstandard2.0-S3900.json
analyzers/its/expected/Nancy/Nancy.Validation.DataAnnotations--net452-S3900.json
analyzers/its/expected/akka.net/Akka.Cluster.Sharding--netstandard2.0-S3900.json
analyzers/its/expected/akka.net/Akka.Streams--netstandard2.0-S3900.json
analyzers/its/expected/akka.net/Akka.TestKit--netstandard2.0-S3900.json
analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/PublicMethodArgumentsShouldBeCheckedForNull.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Extensions/IOperationExtensions.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/NullPointerDereferenceBase.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/PublicMethodArgumentsShouldBeCheckedForNull.cs

Part of #6997
There will be a rebase conflict with #7004 refactoring.

Fix S3900 and S2259 FN: Support method dereference

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/EmptyNullableValueAccessBase.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyNullableValueAccess.cs

Part 6 of task 6 of https://github.com/SonarSource/sonar-dotnet/issues/6794
Previous task: https://github.com/SonarSource/sonar-dotnet/pull/6996
Fixes https://github.com/SonarSource/sonar-dotnet/issues/6794
Fixes  `NullReferenceException` issues encountered on peach, such as:
```
CSC : error AD0001: Analyzer 'SonarAnalyzer.Rules.CSharp.SymbolicExecutionRunner' threw an exception of type 'SonarAnalyzer.SymbolicExecution.SymbolicExecutionException' with message '
Error processing method: .ctor ## Method file: C:\Project\src\System.Private.ServiceModel\src\Internals\System\Runtime\IOThreadTimer.cs ## 
Method line: 55,8 ## Inner exception: System.NullReferenceException: Object reference not set to an instance of an object. ##    
at SonarAnalyzer.SymbolicExecution.Roslyn.RuleChecks.EmptyNullab …
```

S3655: Static properties and fields called Value

---

analyzers/its/expected/Nancy/Nancy--net452-S3900.json
analyzers/its/expected/Nancy/Nancy--netstandard2.0-S3900.json
analyzers/its/expected/Nancy/Nancy.ViewEngines.Markdown--net452-S3900.json
analyzers/its/expected/Nancy/Nancy.ViewEngines.Markdown--netstandard2.0-S3900.json
analyzers/its/expected/akka.net/Akka.Tests.Shared.Internals--netstandard2.0-S3900.json
analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/PublicMethodArgumentsShouldBeCheckedForNull.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/PublicMethodArgumentsShouldBeCheckedForNull.cs

Minor update for S3900.
Switching from bottom-up search to top-down approach when dealing with operations.
This changed resolved a couple of FPs.

S3900: Change parameter dereference check to top-down

---

its/src/test/java/com/sonar/it/csharp/Tests.java
its/src/test/java/com/sonar/it/shared/TestUtils.java
its/src/test/java/com/sonar/it/shared/Tests.java
its/src/test/java/com/sonar/it/vbnet/Tests.java

Deduplicate version configuration and orchestrator scaffolding to a single place.

ITs: Deduplicate orchestrator initialization

---

analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/EmptyNullableValueAccessTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyNullableValueAccess.NullableContext.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyNullableValueAccess.cs

Part 7 of task 6 of https://github.com/SonarSource/sonar-dotnet/issues/6794
Previous task: https://github.com/SonarSource/sonar-dotnet/pull/7000
Addresses:
- comments received on https://github.com/SonarSource/sonar-dotnet/pull/6996 on commits already merged into `feature/SE`, reviewed twice due to a change of base branch as explained [here](https://github.com/SonarSource/sonar-dotnet/pull/6996#discussion_r1151472642);
- comment received offline on https://github.com/SonarSource/sonar-dotnet/pull/6962#discussion_r1149128723: `The idea was to assert all (again) is to be sure that the pairing (left vs. right) doesn't go out of sync. That would ensure that it works, and that it works for a good reason. In theory, the pairing could go out of sync somewhere and it could end up as a green test …

S3655: "In" method params

---

analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Sonar/ExplodedGraphNode.cs
analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Sonar/ProgramPoint.cs
analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Sonar/ProgramState.cs

This PR touches the old SE engine in a low-effort, low-risk manner. It saves a lot of small object allocations:
`Lazy<int>`, `LazyHelper`, and `Func<int>` allocations are eliminated. This results in a total reduction of the allocated objects by 55.000 (total 700.000 ~8%).
The total bytes allocated are down to 37.537.986 from 39.939.178 (~6%).

SE: Use Nullable<int> instead of Lazy<int> for HashCode caching in old SE

---

analyzers/its/sources/ManuallyAddedNoncompliantIssues.CS/IntentionalFindings/S3655.cs

S3655 is never triggered in any integration test.
This PR introduces a non-compliance into the `IntentionalFindings` project of `analyzers\its\sources\ManuallyAddedNoncompliantIssues.CS`, to ensure that the rule is triggered when executing integration tests.

S3655: Add non-compliance to ITs in intentional findings

---

its/pom.xml
its/src/test/java/com/sonar/it/shared/TestUtils.java

Update S4NET to [latest (5.13.0)](https://github.com/SonarSource/sonar-scanner-msbuild/releases/tag/5.13.0.66756)

Bump s4net to 5.13.0.66756

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyNullableValueAccess.cs

Documents scenarios found in peach validation for https://github.com/SonarSource/sonar-dotnet/issues/6794, such as
```cs
if (discountTypeId > 0)
{
return result[discountTypeId.Value];
}
```
source: `smartstore:Libraries/SmartStore.Services/Discounts/DiscountService.cs`.
Actual support for lifted comparison operators on nullable will come with https://github.com/SonarSource/sonar-dotnet/pull/7034.

S3655: Document comparisons

---

analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.IsNull.cs

Fixes misleading test case found here https://github.com/SonarSource/sonar-dotnet/pull/7023#discussion_r1158442446
The root cause was that `notNullValue` was not kept because `PreserveTestCheck` was missing.

SE: Fix test case IsNull_CoalesceAssignment_UnknownToNotNull

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/ExplodedNode.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/ProgramState.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.LearnConstraint.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SymbolicExecution/SETestContext.cs
azure-pipelines.yml

Part of #6105
Based on #7019
Fixes missing "NotNull" caused by  RoslynSymbolicExecution.SetBranchingConstraints

SE: Precision: Fix missing NotNull constraint in RoslynSymbolicExecution.SetBranchingConstraints

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyNullableValueAccess.cs

Documents scenarios found in peach validation for https://github.com/SonarSource/sonar-dotnet/issues/6794, such as
```cs
if ((Validation?.Invoke(options)).Value) 
if ((Validation?.Invoke(options, Dependency1, Dependency2)).Value)
...
```
source: `dotnet-runtime:src/libraries/Microsoft.Extensions.Options/src/ValidateOptions.cs`.
And also:
```cs
public async ValueTask HandleAsync(Server server, Player player)
{
var block = await player.World.GetBlockAsync((int)player.Position.X, (int)player.HeadY, (int)player.Position.Z);
switch (Action)
{
// ...
case EAction.StartSprinting:
if ((bool)(block?.IsFluid))
player.Swimming = true;
player.Sprinting = true;
break;
// ...
}
// ...
}
```
source: …

S3655: Null conditional operator, null coalescing assignment, value tuples

---

analyzers/src/SonarAnalyzer.CFG/Extensions/IOperationExtensions.cs
analyzers/tests/SonarAnalyzer.UnitTest/CFG/Roslyn/RoslynCfgSerializerTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ExplodedNodeTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ProgramStateTest.cs

The syntax type makes the CFG harder to read and doesn't bring practical value.

RoslynCfgSerializer: Do not render syntax type

---

analyzers/rspec/cs/S3655_c#.html
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyNullableValueAccess.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyNullableValueAccess.vb

- RSPEC update, incorporating changes in https://github.com/SonarSource/rspec/pull/1620
- Fix squiggle detection in VB tests
- Improvement mentioned in https://github.com/SonarSource/sonar-dotnet/pull/7006 but forgotten in its implementation: `comment received offline on https://github.com/SonarSource/sonar-dotnet/pull/6962#discussion_r1149128723: The idea was to assert all (again) is to be sure that the pairing (left vs. right) doesn't go out of sync. That would ensure that it works, and that it works for a good reason. In theory, the pairing could go out of sync somewhere and it could end up as a green test by coincidence.`

S3655: RSPEC update and test fixes

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/EmptyNullableValueAccessBase.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyNullableValueAccess.NullableContext.cs

Follows discussion had [here](https://github.com/SonarSource/sonar-dotnet/pull/6996#discussion_r1152789753).
When the user specifies the null forgiving operator on a value access of a `Nullable<T>` (e.g. `nullable!.Value`), no issue is raised by S3655, even when a path is found, in which `nullable` is `null`.
It also removes false positives encountered during peach validation for https://github.com/SonarSource/sonar-dotnet/issues/6794, such as
```cs
Label? after = null;
if (info.Is64BitSwitch)
{
after = _ilg.DefineLabel();
// ...
}
// ...
if (info.Is64BitSwitch)
{
_ilg.MarkLabel(after!.Value); // <- This should be compliant
}
``` 
source: `dotnet-runtime:src/libraries/System.Linq.Expressions/src/System/Linq/Expressions/Compil …

S3655: Honor null forgiving operator

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Binary.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Binary.cs

Related to https://github.com/SonarSource/sonar-dotnet/pull/7034: improve learning in branching on relational operators.
Extend the SE to learn `ObjectConstraint.NotNull`:
- on the true branch only
- when a relational operator (>=, >, <=, <) is used between an operand with a defined `ObjectConstraint` (which has to be `ObjectConstraint.NotNull`, otherwise the branching would have not happened at all, due to https://github.com/SonarSource/sonar-dotnet/pull/7054) and a symbol of a nullable value type.
~Draft because it targets https://github.com/SonarSource/sonar-dotnet/pull/7054, and has to be merged after that PR.~

SE: Learn NotNull on relational operator on nullable value types

---

analyzers/src/SonarAnalyzer.CFG/CfgSerializer/CfgSerializer.RoslynCfgWalker.cs
analyzers/tests/SonarAnalyzer.UnitTest/CFG/Roslyn/RoslynCfgSerializerTest.cs

**Before:**
```
0# SimpleAssignmentOperation
1# LocalReferenceOperation
1#  FlowCaptureReferenceOperation
```
While it is visible, that the assignments contains children LocalReference and FlowCaptureReference, it is not clear what assignment properties they refer to and how to access them.
**After:**
```
0# SimpleAssignmentOperation
1# 0#.Target: LocalReferenceOperation
1# 0#.Value: FlowCaptureReferenceOperation
```
It is no visible, that `assignment.Target` is the local reference and that `assignment.Value` is the flow capture reference.

RoslynCfgSerializer: Render property name

---

pom.xml

Burgr releasability check mandates the change: https://burgr.sonarsource.com/projects/SonarSource/sonar-dotnet/main

Update parent POM to 66.0.234

---

analyzers/its/expected/Net5/Net5--net5.0-S2094.json
analyzers/src/SonarAnalyzer.CSharp/Rules/ClassShouldNotBeEmpty.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ClassShouldNotBeEmpty.CSharp10.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ClassShouldNotBeEmpty.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ClassShouldNotBeEmpty.Inheritance.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ClassShouldNotBeEmpty.Inheritance.vb
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ClassShouldNotBeEmpty.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ClassShouldNotBeEmpty.vb

Fix S2094 FP: Allow to have empty class with non-empty ctor for base class

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/ProgramState.cs

As the print is going to be closed, we need to turn off the consistency check for the time being. Once we start working on #7025 again, we can re-enable it.

SE: Turn off State.CheckConsistency

---

analyzers/src/SonarAnalyzer.CSharp/Rules/MethodsShouldNotHaveTooManyLines.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/MethodsShouldNotHaveTooManyLinesTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/MethodsShouldNotHaveTooManyLines.LocalFunctions.CSharp9.cs

Fix AD0001 in S138: NullReferenceException

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Constraints/ConstraintKind.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Constraints/NumberConstraint.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/SymbolicConstraintTest.cs

SE: Add NumberConstraint

---

analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Binary.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.LearnConstraint.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.ExceptionCandidate.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.ExceptionType.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Invocation.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.IsNull.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Loops.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Nullable.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.ParameterReassignedConstraint.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.PatternMatching.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Throw.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SymbolicExecution/SETestContext.cs

Remove the need to pass ", " explicitly for `additionalParameters`.
This was a bad idea and it's time to fix it, before we add even more UTs.
There's file-scope ns change in one of the commits for SETestContext

UTs: Automatic parameter comma in SETestContext

---

analyzers/src/SonarAnalyzer.CSharp/Extensions/InvocationExpressionSyntaxExtensions.cs
analyzers/src/SonarAnalyzer.VisualBasic/Extensions/InvocationExpressionSyntaxExtensions.cs
analyzers/src/SonarAnalyzer.VisualBasic/Extensions/SyntaxNodeExtensions.cs
analyzers/tests/SonarAnalyzer.UnitTest/Extensions/InvocationExpressionSyntaxExtensionsTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Extensions/SyntaxNodeExtensionsTest.cs

Add extention method `TryGetOperands` for `InvocationExpressionSyntax` in order to help the implementation of the following rules:
- S6602 (#7121) 
- S6603 (#7122)
- S6605 (#7123)
- S6608 (#7125)
- S6609 (#7126)
- S6610 (#7127)
- S6613 (#7129)
- S6617 (#7131)

Add TryGetOperands helper method

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/TestMethodShouldContainAssertion.MsTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/TestMethodShouldContainAssertion.NUnit.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/TestMethodShouldContainAssertion.Xunit.Legacy.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/TestMethodShouldContainAssertion.Xunit.cs

Fix breaking UTs by updating NFluent "IsPositive" calls

---

sonar-vbnet-plugin/pom.xml

Due to the  update of the [protobuf dependency ](https://github.com/SonarSource/sonar-dotnet/pull/7188) the vb.net plugin size is larger.

Update the expected vbnet plugin file size range

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Constraints/NumberConstraint.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Binary.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/ProgramState.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Constraints/NumberConstraintTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Binary.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Monitor.Loops.vb

SE: Add Plus- and MinusOperation for literals

---

analyzers/its/expected/Ember-MM/EmberAPI-{208AA35E-C6AE-4D2D-A9DD-B6EFD19A4279}-S2302.json
analyzers/src/SonarAnalyzer.CSharp/Rules/NameOfShouldBeUsed.cs
analyzers/src/SonarAnalyzer.Common/Rules/NameOfShouldBeUsedBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/NameOfShouldBeUsed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/NameOfShouldBeUsed.vb

Improve S2302 Message: Use NameOf for VB.NET

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Constraints/NumberConstraint.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Binary.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Constraints/NumberConstraintTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.LearnConstraint.cs

Follow up of #7142 
Fixes #7143 
`Squash LearnNumberCombined` doesn't need a review, it's in #7198 
`Squash LearnNumberCombined_Existing` doesn't need a review, it's in #7203

SE: ComputeBoolConstraint for ranges of == and !=

---

analyzers/src/SonarAnalyzer.Common/Rules/Utilities/AnalysisWarningAnalyzerBase.cs
analyzers/src/SonarAnalyzer.Common/Rules/Utilities/CopyPasteTokenAnalyzerBase.cs
analyzers/src/SonarAnalyzer.Common/Rules/Utilities/FileMetadataAnalyzerBase.cs
analyzers/src/SonarAnalyzer.Common/Rules/Utilities/LogAnalyzerBase.cs
analyzers/src/SonarAnalyzer.Common/Rules/Utilities/MetricsAnalyzerBase.cs
analyzers/src/SonarAnalyzer.Common/Rules/Utilities/SymbolReferenceAnalyzerBase.cs
analyzers/src/SonarAnalyzer.Common/Rules/Utilities/TokenTypeAnalyzerBase.cs
analyzers/src/SonarAnalyzer.Common/Rules/Utilities/UtilityAnalyzerBase.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/AnalysisWarningAnalyzerTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/CopyPasteTokenAnalyzerTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/FileMetadataAnalyzerTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/LogAnalyzerTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/MetricsAnalyzerTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/SymbolReferenceAnalyzerTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/TokenTypeAnalyzerTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/UtilityAnalyzerBaseTest.cs

Pre-condition for https://github.com/SonarSource/sonar-dotnet/issues/6674
Analyzer should be stateless. This PR removes the properties from UtilityAnalyzerBase and captures them in `RegisterCompilationStartAction` per compilation.
After this change, `EnableConcurrentExecution` can be set to true (and also `var treeMessages = new List<TMessage>();` needs to be changed to `var treeMessages = new ConcurrentStack<TMessage>();` of course).

Make UtilityAnalyzerBase stateless by removing properties

---

analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Binary.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.LearnConstraint.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Constants.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.IncrementOrDecrement.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Invocation.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.InvocationAttribute.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.IsNull.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Loops.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Nullable.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.ParameterReassignedConstraint.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.PatternMatching.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SymbolicExecution/ValidatorTestCheck.cs

`ValidatorTestCheck.ValidateTag` is now obsolete, because we can fluently assert symbolic value constraints.
Using `TagValue("Name")` also gives better error message when assertion fails, because we can see what tagname failed in the message.
Before:
```
validator.ValidateTag("If", x => x.Should().HaveOnlyConstraint(ObjectConstraint.Null));
```
After:
```
validator.TagValue("If").Should().HaveOnlyConstraint(ObjectConstraint.Null);
```
All usages were replaced using regex:
Find: `ValidateTag\((?<Name>"[^"]+"), x => x.Should\(\)\.(?<Action>.*)\);`
Replace: `TagValue(${Name}).Should().${Action};`

SE UTs: Replace ValidateTag with TagValue

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/CalculationsShouldNotOverflow.cs

`Max` is not coverable, because it would require `Min` to return value that doesn't have max defined.
Coverage is currently incorrectly computed, because `&& Max(operation.Type) is { } typeMax` cannot produce `false` answer by-design now.

S3949: Bump coverage

---

analyzers/src/SonarAnalyzer.CSharp/Rules/EmptyMethodCodeFix.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/EmptyMethodTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/EmptyMethod.CSharp9.Comment.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/EmptyMethod.CSharp9.Throw.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/EmptyMethod.WithoutClosingBracket.Comment.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/EmptyMethod.WithoutClosingBracket.cs

Fix AD0001 on S1186: NullReferenceException for LocalFunctionStatements

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Constraints/NumberConstraint.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Constraints/NumberConstraintTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Binary.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs

Fixes #7156
Uses similar trick as cache of `SymbolicConstraint`
Stats of existing NumberConstraints from build of 3 projects:
[NumberConstraint_Akka.txt](https://github.com/SonarSource/sonar-dotnet/files/11544644/NumberConstraint_Akka.txt)
[NumberConstraint_Runtime.txt](https://github.com/SonarSource/sonar-dotnet/files/11544645/NumberConstraint_Runtime.txt)
[NumberConstraint_WCF.txt](https://github.com/SonarSource/sonar-dotnet/files/11544646/NumberConstraint_WCF.txt)

SE: Cache NumberConstraint

---

analyzers/src/SonarAnalyzer.Common/Rules/Utilities/AnalysisWarningAnalyzerBase.cs
analyzers/src/SonarAnalyzer.Common/Rules/Utilities/UtilityAnalyzerBase.cs

Fixes #7240
This locking is not needed as each of the analyzers is writing to its own file. And the action is executed only once. So there are now two threads accessing the file at the same time.

Remove locking from utility analyzers when writing protobuf files

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Checks/ConstantCheck.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Conversion.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Loops.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Nullable.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Monitor.Conditions.vb

In VB, compiler initializes value to 0, instead of dev needing to please the compiler
```
Dim Value As Integer
```
So we need to build the constraint for locally scoped variables, same as we already do for boolean.

SE: Init integral variables to zero

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/CalculationsShouldNotOverflowBase.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/CalculationsShouldNotOverflow.vb

Address https://github.com/SonarSource/sonar-dotnet/pull/7270#discussion_r1206472030
Power operator was not supported, so FP was not raised as the new value was not calculated yet.
Draft: I plan to rebase and merge this after the feature branch is merged to master.

S3949: Remove Power operator

---

analyzers/src/SonarAnalyzer.CSharp/Rules/LinkedListPropertiesInsteadOfMethodsCodeFix.cs
analyzers/src/SonarAnalyzer.Common/Rules/LinkedListPropertiesInsteadOfMethodsBase.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/LinkedListPropertiesInsteadOfMethodsTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/LinkedListPropertiesInsteadOfMethods.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/LinkedListPropertiesInsteadOfMethods.cs

Fixes #7239
RSPEC PR: https://github.com/SonarSource/rspec/pull/1953

Rule S6613: implement CodeFix

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Binary.Arithmetic.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Binary.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/CalculationsShouldNotOverflow.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/CalculationsShouldNotOverflow.vb

Part of https://github.com/SonarSource/sonar-dotnet/issues/7267

SE: Add RemainderOperation

---

analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
analyzers/src/SonarAnalyzer.Common/Rules/InsteadOfAnyBase.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/InsteadOfAny.EntityFramework.Core.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/InsteadOfAny.EntityFramework.Core.vb
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/InsteadOfAny.EntityFramework.Framework.cs

Fix S6605 and S6617 FP: Replace DbSet check with IQueryable<T> check

---

analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Sonar/Analyzers/InvalidCastToInterfaceSymbolicExecution.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Sonar/HashesShouldHaveUnpredictableSalt.cs

Fix AD0001 Bug: Old SE run without S1944 throws NullReferenceException

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationDispatcher.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/FlowCapture.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/ProgramState.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ProgramStateTest.OperationValue.cs

Part of #7339 
This will eventually be a prerequisite to fix the #7339 problem, after we improve LVA (not in this sprint).
For now, it's just an engine improvement to remove the counter-intuitive flow capture reference from under the hood into a normal flow.

SE: Refactor FlowCaptureReference to operation processor

---

analyzers/src/SonarAnalyzer.CSharp/Rules/UnnecessaryMathematicalComparison.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/UnnecessaryMathematicalComparison.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/NameOfShouldBeUsed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnnecessaryMathematicalComparison.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnnecessaryMathematicalComparison.cs

RSpec: https://github.com/SonarSource/rspec/pull/2156
Updates from the changes of the RSpec are going to be run by @csaba-sagi-sonarsource for all rules being modified in the rspec repository in the LaYC sprint.

Improve S2198: message - replace silly with unnecessary

---

analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Sonar/Analyzers/EmptyCollectionsShouldNotBeEnumerated.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Constraints/CollectionConstraint.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/EmptyCollectionsShouldNotBeEnumeratedBase.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.CSharp8.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.cs

Fixes #6179
This has two parts.
For `var arr = new int[5]` we need to learn explicitly CollectionNotEmpty, so when the `for` condition of `i<arr.Length` arrives, we're sure we go inside and do not skip the loop

S4158 FP: Collection filled in a for loop reported to be empty

---

analyzers/src/SonarAnalyzer.VisualBasic/Extensions/InvocationExpressionSyntaxExtensions.cs
analyzers/src/SonarAnalyzer.VisualBasic/SymbolicExecution/Roslyn/ObjectsShouldNotBeDisposedMoreThanOnce.cs

In VB.NET a method can be called by invocation, for example,  `d.Dispose()`, but it can be called also without the parentheses via member access `d.Dispose`.
So having an argument list with 0 arguments and having no argument list at all is the same thing in VB.NET context.

VB.NET HasExactlyNArguments method considers null argument list and 0 arguments the same.

---

pom.xml
sonar-csharp-plugin/pom.xml
sonar-dotnet-shared-library/pom.xml
sonar-vbnet-plugin/pom.xml

`guava` is refactored in #7464
`gson` and `commons-io` is not shared with other POMs

Deduplicate Java dependency versioning

---

analyzers/its/expected/Net5/Net5--net5.0-S6640.json
analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/UnsafeCodeBlocks.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Hotspots/UnsafeCodeBlocksTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/UnsafeCodeBlocks.cs

Improve S6640: Support type declarations

---

analyzers/rspec/cs/S6580.html
analyzers/rspec/vbnet/S6580.html

A simple RSPEC update, moving text from the Description part of the spec to the Why portion.

Modify S6580: Update RSPEC

---

analyzers/src/SonarAnalyzer.Common/Rules/UseUnixEpochBase.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UseUnixEpoch.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UseUnixEpoch.Fixed.vb
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UseUnixEpoch.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UseUnixEpoch.vb

Fix S6588 FN: Rule should cover case with epoch ticks

---

analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/InitializationVectorShouldBeRandom.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/InitializationVectorShouldBeRandomBase.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/InitializationVectorShouldBeRandomTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/InitializationVectorShouldBeRandom.CSharp10.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/InitializationVectorShouldBeRandom.CSharp11.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/InitializationVectorShouldBeRandom.CSharp8.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/InitializationVectorShouldBeRandom.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/InitializationVectorShouldBeRandom.cs

Migrate S3329: Scaffold the rule for the new SE 

---

its/src/test/java/com/sonar/it/csharp/MetricsIncludeHeaderCommentTest.java

Part of #7557 
`MetricsTest.java` and `MetricsIncludeHeaderCommentTest.java` use the same project to do assertions.
I decoupled them by using a different `projectKey` in orchestrator for the second one.

ITs: Fix race condition in MetricsIncludeHeaderCommentTest

---

azure-pipelines.yml
its/pom.xml
its/src/test/java/com/sonar/it/csharp/Tests.java
its/src/test/java/com/sonar/it/shared/Tests.java
its/src/test/java/com/sonar/it/vbnet/Tests.java

Fixes #4223
This removes suites and executes all UTs based on pattern in CI.
This still creates an orchestrator for every single test class.
To properly review it, please check AzureDev Ops build and make sure that CSharp executes only CSharp UTs (and all of them), and the "Others" run executes vbnet+shared

Java ITs: Migrate to jUnit 5 - Remove suites

---

its/pom.xml
its/src/test/java/com/sonar/it/csharp/IncrementalAnalysisTest.java
its/src/test/java/com/sonar/it/shared/TestUtils.java

Fixes #7274 
Just bumping the reference. We won't use the new jUnit5 capabilities, because it doesn't suite our use case.
I'm ignoring the failed IT, it will get resolved by a rebase

Bump sonar-orchestrator from 3.42.0.312 to 4.0.0.404

---

analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/RestrictDeserializedTypes.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/RestrictDeserializedTypesBase.cs

Migrate S5773: Implement ShouldExecute

---

.github/workflows/LabelIssue.yml

Re-add CreateCardForIssueFromLabel for E2E testing.
https://github.com/SonarSource/gh-action-lt-backlog/issues/54

GitHub workflow: Add CreateCardForIssueFromLabel from dev

---

analyzers/src/SonarAnalyzer.Common/Extensions/AnalyzerOptionsExtensions.cs

Fixes #7440
Tested with Akka.Net in a `dotnet build` context in a SQ EE SonaryWay run.
This change safes
* 5GB of string allocations caused by calls to `Path.GetFileName`
* 3GB of delegate allocations for the FirstOrDefault lambda argument
* 1,1 GB for the capture class for the filename parameter.
The total memory allocations are down to 32,5 GB from 41,7GB = 9,2 GB savings (22%)
The number of issues reported stayed the same (3514 warnings).
Before
After

Allocations: Unroll AdditionalFile extension method

---

analyzers/src/SonarAnalyzer.CSharp/Extensions/SyntaxNodeExtensions.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/Utilities/TokenTypeAnalyzer.cs

Moving some `SyntaxKind[]` arrays created by `IsAnyKind` to a static readonly field saves 350MB:
That array was the 15th most allocated type.
Before
After

Allocations: Move stringliteral tokens array to static field

---

analyzers/src/SonarAnalyzer.Common/Extensions/SyntaxTreeExtensions.cs

Small risk change that saves 291 MB of allocations (out of 41,6 GB). IsGenerated is the 7th most allocating method:
Before:
After
Before
After

Allocations: Remove delegate allocation from IsGenerated

---

analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarAnalysisContextBase.cs

IsUnchanged allocates a delegate on each call to GetOrAdd. This can be avoided by doing a TryGet before the GetOrAdd for the common case of a cache hit. This change saves 257 MB of allocations.
Before
After
Before
After

Allocations: Make IsUnchanged allocation free in the common case

---

analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarAnalysisContextBase.cs

Small risk change that saves 165 MB of allocations (out of 41,6 GB). IsExcluded is the 20th most allocating method:
Before
After
Before
After

Allocations: Remove delegate allocation from IsExcluded

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SymbolicRuleCheck.cs

Adding a report issue overload that accepts the DiagnosticDescriptor as a parameter.
We need this because S2589 and S2583 are reporting from the same class (issue #7646).

Add ReportIssue overload to SymbolicRuleCheck

---

analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/ConditionEvaluatesToConstantBase.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/ConditionEvaluatesToConstantBased.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/ConditionEvaluatesToConstantTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp10.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp11.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp7.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp8.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp9.TopLevelStatements.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs

Migrate S2583/S2589: Scaffold the rule for the new SE

---

analyzers/rspec/cs/S1186.html

Fixes a (likely) `NotSupportedException` copy paste mistake on S1186's html documentation

Fix copy paste in S1186 docs

---

analyzers/its/expected/Ember-MM/scraper.EmberCore.XML-{E567C031-1F7B-4637-9B3A-806988DE50CF}-S1643.json
analyzers/src/SonarAnalyzer.CSharp/Facade/CSharpSyntaxFacade.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/StringConcatenationInLoop.cs
analyzers/src/SonarAnalyzer.Common/Facade/SyntaxFacade.cs
analyzers/src/SonarAnalyzer.Common/Rules/StringConcatenationInLoopBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Facade/VisualBasicSyntaxFacade.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/StringConcatenationInLoop.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/StringConcatenationInLoopTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/StringConcatenationInLoop.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/StringConcatenationInLoop.vb

Fixex #5521 + structure refactoring.

Fix S1643 FP: should not apply when strings are not aggregated

---

analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Binary.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.LearnConstraint.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Invocation.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.InvocationAttribute.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Loops.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Nullable.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.PatternMatching.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.TryCatchFinally.cs

Notes. Search and replace
Regex used:
https://regex101.com/r/5boD7y/3
Find:
`(?<before>.*)(?<validateTag>ValidateTag)\((?<tagName>".*"), (?<paramName>.*) => (\k<paramName>)\.HasConstraint\((?<constraint>[^\)]*)\)\.Should\(\)\.BeTrue\(\)\)`
Replace:
`${before}TagValue("${tagName}").Should().HaveOnlyConstraint(${constraint})`

Deprecation: Replace ValidateTag with TagValue (BeTrue part)

---

analyzers/src/SonarAnalyzer.Common/Rules/StringConcatenationInLoopBase.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/StringConcatenationInLoop.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/StringConcatenationInLoop.vb

Fix S1643 FN: consider simple assignments with variable not on the innermost add expression

---

analyzers/its/expected/Ember-MM/Ember Media Manager-{9B57D3AB-AF12-4012-B945-284C2448DC81}-S1125.json
analyzers/its/expected/Ember-MM/EmberAPI-{208AA35E-C6AE-4D2D-A9DD-B6EFD19A4279}-S1125.json
analyzers/its/expected/Nancy/Nancy--net452-S1125.json
analyzers/its/expected/Nancy/Nancy--netstandard2.0-S1125.json
analyzers/its/expected/akka.net/Akka--netstandard2.0-S1125.json
analyzers/its/expected/akka.net/Akka.Cluster--netstandard2.0-S1125.json
analyzers/its/expected/akka.net/Akka.MultiNodeTestRunner.Shared--netstandard2.0-S1125.json
analyzers/its/expected/akka.net/Akka.Remote.TestKit--netstandard2.0-S1125.json
analyzers/its/expected/akka.net/Akka.TestKit--netstandard2.0-S1125.json
analyzers/src/SonarAnalyzer.CSharp/Extensions/SyntaxNodeExtensions.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/BooleanLiteralUnnecessary.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/BooleanLiteralUnnecessaryCodeFix.cs
analyzers/src/SonarAnalyzer.Common/Rules/BooleanLiteralUnnecessaryBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Extensions/SyntaxNodeExtensions.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/BooleanLiteralUnnecessary.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/BooleanLiteralUnnecessary.CSharp9.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/BooleanLiteralUnnecessary.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/BooleanLiteralUnnecessary.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/BooleanLiteralUnnecessary.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/BooleanLiteralUnnecessary.vb

Fix S1125 FN: recognize "is" and "is not" keyword with constant pattern

---

analyzers/src/SonarAnalyzer.CSharp/Rules/BooleanLiteralUnnecessaryCodeFix.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/BooleanLiteralUnnecessary.CSharp9.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/BooleanLiteralUnnecessary.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/BooleanLiteralUnnecessary.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/BooleanLiteralUnnecessary.cs

S1125: Faulty code fix on C# pattern matching in conditional operator

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs

Migrate S2589: Fix rethrow FP

---

analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Binary.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Invocation.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.PatternMatching.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SymbolicExecution/ValidatorTestCheck.cs

Follow up to #7705
[6395edd](https://github.com/SonarSource/sonar-dotnet/pull/7741/commits/6395edd7ebd387539728c61b74afc57102060747) removes `ValidateTag`!

Deprecation: Replace ValidateTag with TagValue (Part 2)

---

analyzers/src/SonarAnalyzer.CFG/CfgSerializer/DotWriter.cs

Allows deleting [the class](https://github.com/SonarSource/sonar-security/blob/ce89c9d45c371c52186c6faa373262d7ca031d9f/frontend/csharp/src/SonarAnalyzer.Security/Helpers/DotWriter.cs#L11) from the security Frontend

Change DotWriter Visibility to public

---

azure-pipelines.yml

To avoid the false positives we intentionally introduce in the unit tests.

Exclude test cases from code analysis

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.cs

FP reported here: https://community.sonarsource.com/t/c-s4158-false-positive/97192
This FP is present in the latest release 9.7.0.75501 but seems to be fixed now on master as it does not raise anymore probably fixed by this [PR](https://github.com/SonarSource/sonar-dotnet/pull/7641).

S4158: Add FP repro

---

analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/ConditionEvaluatesToConstantBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp8.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.vb
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Sonar/ConditionEvaluatesToConstant.CSharp8.cs

In a multithreading context, it makes sense to check conditions twice (before and after the lock).
That's why we are ignoring what is in the lock statement body to not create a lot of noise with false positive issues.
Related to #3353

Fix S2583/S2589 FP: Do not raise when condition is in the body of a lock statement.

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp7.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp8.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Sonar/ConditionEvaluatesToConstant.CSharp7.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Sonar/ConditionEvaluatesToConstant.CSharp8.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Sonar/ConditionEvaluatesToConstant.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Sonar/ConditionEvaluatesToConstant.cs

Add repros for #5002, #5601, #739, #2411
Update UTs and UT annotations.

Add reproducers for S2583/S2589 issues

---

analyzers/src/SonarAnalyzer.CFG/SonarAnalyzer.CFG.csproj
analyzers/src/SonarAnalyzer.CFG/packages.lock.json
analyzers/src/SonarAnalyzer.CSharp/SonarAnalyzer.CSharp.csproj
analyzers/src/SonarAnalyzer.CSharp/packages.lock.json
analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarAnalysisContextBase.cs
analyzers/src/SonarAnalyzer.Common/Extensions/AnalyzerOptionsExtensions.cs
analyzers/src/SonarAnalyzer.Common/Extensions/SyntaxTreeExtensions.cs
analyzers/src/SonarAnalyzer.Common/Helpers/HashCode.cs
analyzers/src/SonarAnalyzer.Common/SonarAnalyzer.Common.csproj
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SymbolicCheckList.cs
analyzers/src/SonarAnalyzer.Common/packages.lock.json
analyzers/src/SonarAnalyzer.VisualBasic/SonarAnalyzer.VisualBasic.csproj
analyzers/src/SonarAnalyzer.VisualBasic/packages.lock.json

Fixes #7690
From what I can tell, the rules are only activated if the `PerformanceSensitive` attribute is applied (I took a brief look at the implementation and it [seems to be the case](
https://github.com/dotnet/roslyn-analyzers/blob/633ade7a83c2b6918c10035247d93fbe1520463d/src/PerformanceSensitiveAnalyzers/Core/AbstractAllocationAnalyzer.cs#L49)).
The attribute is included via the `Microsoft.CodeAnalysis.PerformanceSensitiveAnalyzers.targets` targets file in [the nuget package](https://nuget.info/packages/Microsoft.CodeAnalysis.PerformanceSensitiveAnalyzers/3.3.1)
```xml
<PropertyGroup>
<GeneratePerformanceSensitiveAttribute Condition="'$(GeneratePerformanceSensitiveAttribute)' == ''">true</GeneratePerformanceSensitiveAttribute>
<PerformanceSensitiveAttributePath …
```

Performance: Add Microsoft.CodeAnalysis.PerformanceSensitiveAnalyzers to our code base

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UriShouldNotBeHardcoded.cs

S1075: Add FN repro

---

analyzers/src/SonarAnalyzer.CSharp/Rules/Utilities/TokenTypeAnalyzer.cs
analyzers/src/SonarAnalyzer.CSharp/SonarAnalyzer.CSharp.csproj

The code smells are due to this bug:
https://github.com/dotnet/roslyn-analyzers/issues/6851

UtilityAnalyzer: Annotate with performance sensitive

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Loops.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp8.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.vb
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.cs

Fixing this FP:
```
var b = false;
for (var i = 0; i < 10; i++)
{
if (i > 5)
b = arg;
}
if (b) // FP
{
Console.WriteLine();
}
```
The loop is explored twice. The second iteration can learn interesting constraints because `i` has `NumberConstraint.From(1, 9)`. Only visiting the loop condition twice would mean losing that information. If we visit it one more time, we can bring the information out of the loop.
There is a follow-up PR which will simplify a lot of the branching: #7797
Also:
Fixes #5601

SE: Increase VisitCount for loop conditions to 3

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Binary.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/BranchingProcessor.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IsNull.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IsPattern.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IsType.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/References.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SymbolicContext.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Loops.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/SymbolicCheckListTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/SymbolicContextTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs

Follow-up to #7797
By applying the special treatment for binary number operations to not just loop conditions but also operations inside a loop, we simplify the code and fix some arcane FPs.

SE: Learn NumberConstraint ranges for 2nd visits of conditions

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Binary.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/BranchingProcessor.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IsNull.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IsPattern.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IsType.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/References.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SymbolicContext.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Loops.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/SymbolicCheckListTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/SymbolicContextTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp8.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Monitor.Loops.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Monitor.Loops.vb

Follow-up to #7795 
Now that we visit loop conditions up to three times, one branch usually leaves the loop on the latest visit. This makes the arbitrary branching we have done before unnecessary. Removing it allows us to find infinite for-loops:
```
public void InfiniteForLoop(string arg)
{
for (var i = 0; i < 10; i--)    // FN
{
}
}
```

Fix S2589 FN: Infinite for-loop

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
its/src/test/java/com/sonar/it/csharp/SharedFilesTest.java

Issues are not always in the same order and this breaks the pipeline.
Access modifiers were also removed to increase readability - the public modifier is not needed with junit5- default one is enough.

Java ITs: Update test to not take order of issues into consideration

---

analyzers/tests/SonarAnalyzer.UnitTest/Rules/Hotspots/RequestsWithExcessiveLengthTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/WebConfig/RequestsWithExcessiveLength/Values/ContentLength_Compliant/Web.config

Fix S5693 FP: custom fileUploadSizeLimit parameter ignored when parsing Web.config files

---

analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Verifier.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/VerifierBuilder.cs

Part of #7893
This way we can write UTs adding snippets of code instead of in-memory files only.
`<VerifierBuilder>.AddSnippet("""<p>Hi there!</p>""", "Test.razor").Verify();`

Add .AddSnippet() support for .razor and .cshtml snippets

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Invocation.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Invocation.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.vb

SE: Learn bool constraints from Equals with bool parameters.

---

analyzers/its/expected/Net5/Net5--net5.0-S2583.json
analyzers/its/expected/Net5/Net5--net5.0-S2589.json
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Constraints/NumberConstraint.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IsPattern.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Constraints/NumberConstraintTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.PatternMatching.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp8.cs

Fix S2589 FN: No BoolConstraint from numerical constant patterns

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/EmptyCollectionsShouldNotBeEnumeratedBase.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.vb

Part of #7457 
We do not learn `CollectionEmpty` from `list.Clear()`.
```
var list = new List<int> { 1 };
list.Clear();   // Compliant
list.Clear();   // FN
```

Fix S4158 FN: Learn Empty on Clear

---

its/src/test/java/com/sonar/it/csharp/Tests.java
sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/SarifParserCallbackImpl.java
sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/sarif/SarifParserCallbackImplTest.java

Do not rethrow the exception in SarifParserCallbackImpl for invalid location for .razor/.cshtml files

---

analyzers/src/SonarAnalyzer.CSharp/Rules/UnusedPrivateMember.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnusedPrivateMember.CSharp7.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnusedPrivateMember.CSharp9.cs

Add reproducers for:
- #6699
- #6724
- #7904

Add reproducers for S1144 FN/FP

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/EmptyCollectionsShouldNotBeEnumeratedBase.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.cs

```
IList<int> iList = new List<int>();
iList.Add(5);
iList.Clear();                                      // Noncompliant FP
```

SE: Fix S4158 FP: Interfaces are only half tracked

---

analyzers/tests/SonarAnalyzer.UnitTest/CFG/Sonar/SonarControlFlowGraphTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/SonarAnalyzer.UnitTest.csproj
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Sonar/SonarExplodedGraphTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/NonDerivedPrivateClassesShouldBeSealed.CSharp11.cs
analyzers/tests/SonarAnalyzer.UnitTest/packages.lock.json
azure-pipelines.yml

Replaces #7856, #7872, #7613, #7571
Latest SDK fails due to altcover clash: https://github.com/microsoft/vstest/issues/4106

Bump test dependencies

---

analyzers/src/SonarAnalyzer.CSharp/Metrics/CSharpExecutableLinesMetric.cs
analyzers/src/SonarAnalyzer.Common/Extensions/SyntaxTreeExtensions.cs
analyzers/src/SonarAnalyzer.Common/Helpers/GeneratedCodeRecognizer.cs
analyzers/src/SonarAnalyzer.Common/Rules/Utilities/UtilityAnalyzerBase.cs
analyzers/tests/SonarAnalyzer.UnitTest/Metrics/CSharpExecutableLinesMetricTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/MetricsAnalyzerTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/SymbolReferenceAnalyzerTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Utilities/MetricsAnalyzer/Razor.cshtml
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Utilities/SymbolReferenceAnalyzer/Razor.cshtml

Ensure that utility analyzers are invoked only for .razor generated files

---

analyzers/src/SonarAnalyzer.Common/Common/AnalyzerLanguage.cs
analyzers/src/SonarAnalyzer.Common/Rules/Utilities/TokenTypeAnalyzerBase.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/TokenTypeAnalyzerTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Utilities/TokenTypeAnalyzer/Razor.cshtml
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Utilities/TokenTypeAnalyzer/Razor.razor

Update TokenTypeAnalyzer to ignore .cshtml and .razor files

---

analyzers/src/SonarAnalyzer.Common/Rules/Utilities/CopyPasteTokenAnalyzerBase.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/CopyPasteTokenAnalyzerTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Utilities/CopyPasteTokenAnalyzer/Razor.cshtml
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Utilities/CopyPasteTokenAnalyzer/Razor.razor

Update CopyPasteTokenAnalyzer to ignore .cshtml and .razor files

---

analyzers/src/SonarAnalyzer.Common/Rules/Utilities/CopyPasteTokenAnalyzerBase.cs
analyzers/src/SonarAnalyzer.Common/Rules/Utilities/FileMetadataAnalyzerBase.cs
analyzers/src/SonarAnalyzer.Common/Rules/Utilities/LogAnalyzerBase.cs
analyzers/src/SonarAnalyzer.Common/Rules/Utilities/MetricsAnalyzerBase.cs
analyzers/src/SonarAnalyzer.Common/Rules/Utilities/SymbolReferenceAnalyzerBase.cs
analyzers/src/SonarAnalyzer.Common/Rules/Utilities/TokenTypeAnalyzerBase.cs
analyzers/src/SonarAnalyzer.Common/Rules/Utilities/UtilityAnalyzerBase.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/FileMetadataAnalyzerTest.cs

Parameters modified:
- syntaxTree -> tree
- semanticModel -> model
Scope: utility analyzers

Rename parameter names to match our convention

---

.editorconfig

CS7035 expects the build number to fit in 16 bits, our build numbers are bigger
https://github.com/dotnet/roslyn/issues/17024#issuecomment-1669503201
This breaks QG when it is strict:
https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&id=sonaranalyzer-dotnet&open=AYqDXHV-DfNc-n4YKz3z

Ignore CS7035

---

analyzers/tests/SonarAnalyzer.UnitTest/PackagingTests/RuleTypeTest.cs

Should be merged after https://github.com/SonarSource/sonar-dotnet/pull/7942.
This HashSet does not seem to serve as a safety net since if we delete a rule and forget to add it there it still does not fail.
Also, the comments are not particularly useful in that place.
Currently, I'm in contact with SQ, SC, and SL to understand what kind of information they need and through what channel once we delete a rule. I'll add this knowledge to an xtranet page (called "How to delete a rule in sonar-dotnet") and maybe in the read me here.
Review only [delete hashet](https://github.com/SonarSource/sonar-dotnet/pull/7948/commits/83821db43e93ad785b1af99259945bdb134ac499) commit.

UTs: Delete HashSet with deleted rule IDs

---

analyzers/src/SonarAnalyzer.Common/Helpers/DiagnosticReportHelper.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/ConditionalStructureSameConditionTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/ConditionalStructureSameImplementationTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/ConditionalsWithSameConditionTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/DoNotShiftByZeroOrIntSizeTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/IndentSingleLineFollowingConditionalTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/TryStatementsWithIdenticalCatchShouldBeMergedTest.cs

Fix rules that rely on `DiagnosticReportHelper.GetLineNumberToReport` for razor

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/PublicMethodArgumentsShouldBeCheckedForNullBase.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/PublicMethodArgumentsShouldBeCheckedForNullTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/PublicMethodArgumentsShouldBeCheckedForNull.razor
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/PublicMethodArgumentsShouldBeCheckedForNull_component.razor

Fix S3900 FP: should not consider .razor generated file parameters

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp9.cs

- Repro for #8008
- Repro for #8011

S2589: Add repros

---

analyzers/src/SonarAnalyzer.CSharp/Rules/UnnecessaryUsings.cs

This avoids creating new strings that are needed just for comparison.

Use HashSet with string comparer instead of using ToUpperInvariant

---

analyzers/src/SonarAnalyzer.CFG/ShimLayer/SyntaxKindEx.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/Utilities/TokenTypeAnalyzer.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/TokenTypeAnalyzerTest.Classifier.cs

Follow up to https://github.com/SonarSource/sonar-dotnet/issues/7369

TokenType: Tests and support for scoped type declarations

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SqlKeywordsDelimitedBySpace.CSharp10.cs

Add test cases for non-const string interpolation, see #8102.

Add test cases for S2857 FP: Rule is not checking SQL keywords in interepolated string

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ParameterValidationInYieldShouldBeWrapped.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ParametersCorrectOrder.CSharp11.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ParametersCorrectOrder.CSharp12.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ParametersCorrectOrder.cs

Due to a glitch in the review process described [here](https://github.com/SonarSource/sonar-dotnet/pull/8093#issuecomment-1742706072) and [here](https://trello.com/c/AD7ixuIb/22-p-second-pass), we need a second pass, to address the following new comments on rules starting with P:
- https://github.com/SonarSource/sonar-dotnet/pull/8093#discussion_r1342429179
- https://github.com/SonarSource/sonar-dotnet/pull/8093#discussion_r1342434664
- https://github.com/SonarSource/sonar-dotnet/pull/8093#discussion_r1342435227
- https://github.com/SonarSource/sonar-dotnet/pull/8093#discussion_r1342439023
- https://github.com/SonarSource/sonar-dotnet/pull/8093#discussion_r1342442665
- https://github.com/SonarSource/sonar-dotnet/pull/8093#discussion_r1342448835

 .NET 8 and C# 12: fix repros and UTs for rules starting with P in SonarWay

---

sonar-csharp-plugin/pom.xml
sonar-vbnet-plugin/pom.xml

Optimization: Enable on-demand plugin download

---

analyzers/src/SonarAnalyzer.CFG/ShimLayer/Syntax.xml

Part of #8176.
This PR adds support for the new C#12 syntax introduced by [Collection Expressions](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-12.0/collection-expressions) feature:
- `CollectionExpressionSyntax`
- `CollectionElementSyntax`
- `ExpressionElementSyntax`
- `SpreadElementSyntax`

Add Collection Expression syntax to the ShimLayer

---

analyzers/src/SonarAnalyzer.CFG/ShimLayer/Syntax.xml

Part of #8176.
This PR adds support for the new C#12 syntax introduced by [Alias any Type](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-12.0/using-alias-types) feature:
- `UsingDirectiveSyntax`, `StaticKeyword` field
- `UsingDirectiveSyntax`, optional sequence of `UnsafeKeywords` of type `SyntaxToken`

Add Alias any Type syntax to the ShimLayer

---

analyzers/src/SonarAnalyzer.CFG/ShimLayer/Syntax.xml

Part of #8176.
This PR adds support for the new C#12 syntax introduced by [Primary Constructor](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-12.0/primary-constructors) feature:
- `ParameterList` field to `TypeDeclarationSyntax
`
- `ParameterList`, `OpenBraceToken` and `CloseBraceToken` fields to `ClassDeclarationSyntax`
- `ParameterList`, `OpenBraceToken` and `CloseBraceToken` fields to `StructDeclarationSyntax`
- `ParameterList`, `OpenBraceToken` and `CloseBraceToken` fields to `InterfaceDeclarationSyntax`
- optional `OpenBraceToken` and `CloseBraceToken` fields to `EnumDeclarationSyntax`
For now, we miss the `Override="true"` attribute on `ParameterList` of `RecordDeclarationSyntax` since this introduces a breaking change and requires a …

Add Primary Constructor syntax to the ShimLayer

---

analyzers/its/regression-test.ps1

Internal projects are verified differently and we don't need to wait for the other projects to run to validate them.

Update .Net ITs order to run the internal projects first

---

analyzers/src/SonarAnalyzer.CSharp/Extensions/ISymbolExtensions.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/PublicMethodWithMultidimensionalArray.cs
analyzers/src/SonarAnalyzer.Common/Rules/PublicMethodWithMultidimensionalArrayBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/PublicMethodWithMultidimensionalArray.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/PublicMethodWithMultidimensionalArrayTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/PublicMethodWithMultidimensionalArray.CSharp12.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/PublicMethodWithMultidimensionalArray.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/PublicMethodWithMultidimensionalArray.vb

Fixes #7329
And handles ordinary constructor support from #8083

Fix S2368 FP/FN: Don't raise for extension methods and raise for constructors

---

analyzers/src/SonarAnalyzer.CFG/ShimLayer/LightupHelpers.cs

Avoid allocations in LightupHelpers.CanWrap... methods

---

analyzers/src/SonarAnalyzer.CSharp/Rules/DoNotMarkEnumsWithFlags.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DoNotMarkEnumsWithFlags.cs

if their absolute value is a power of two.
Fixes #7991

Update S4070 to accept negative numbers

---

analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/CalculationsShouldNotOverflow.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/CalculationsShouldNotOverflowSyntaxKindWalkerTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/CalculationsShouldNotOverflowSyntaxWalkerTest.cs

CalculationsShouldNotOverflow.SyntaxKindWalker reduce allocations and evaluations in the hot path

---

analyzers/src/SonarAnalyzer.CFG/Helpers/OperationExecutionOrder.cs
analyzers/src/SonarAnalyzer.CFG/ShimLayer/IOperationWrapperSonar.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/InfiniteRecursion.RoslynCfg.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/ExplodedNode.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/ProgramState.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
analyzers/tests/SonarAnalyzer.UnitTest/Helpers/OperationExecutionOrderTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ExplodedNodeTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ProgramStateTest.OperationValue.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/SymbolicCheckListTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/SymbolicContextTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/TestHelper.cs

The IOperationWrapperSonar does not follow the pattern used for the other wrappers. This PR rewrites the wrapper to
* Use compiled expressions instead of cached reflection
* Use a readonly struct instead of a class
Before
After

IOperationsWrapperSonar: Use compiled expressions

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Binary.Collections.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/EmptyCollectionsShouldNotBeEnumeratedBase.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/CollectionConstraintTests.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.cs

Fixes and issue introduced in #7877 
```
class NotACollection
{
List<int> items;
int Count => items.Count;
void Remove(int i) => items.Remove(i);
void Foo(NotACollection notACollection)
{
if (notACollection.Count > 0)
{
notACollection.Remove(5);
if (notACollection.Count > 0)   // Noncompliant FP
{
Console.WriteLine();
}
}
}
}
```

Fix S2583/S2589 FP: Not tracked collection types can learn `CollectionConstraint` from `BinaryOperation`

---

analyzers/src/SonarAnalyzer.CSharp/Extensions/ISymbolExtensions.cs
analyzers/src/SonarAnalyzer.CSharp/Extensions/SyntaxNodeExtensions.cs
analyzers/src/SonarAnalyzer.CSharp/Facade/CSharpSyntaxFacade.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/TypeNamesShouldNotMatchNamespaces.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/UseStringCreate.cs
analyzers/tests/SonarAnalyzer.UnitTest/Extensions/SyntaxNodeExtensionsTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Tests/DummyAnalyzerWithLocation.cs

SyntaxNodeExtensions.GetIdentifier and ISymbolExtensions.NodeIdentifier are duplicates

---

analyzers/src/SonarAnalyzer.CSharp/Extensions/SyntaxNodeExtensions.cs
analyzers/src/SonarAnalyzer.CSharp/Facade/CSharpFacade.cs
analyzers/src/SonarAnalyzer.CSharp/Facade/CSharpSyntaxFacade.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/AssertionArgsShouldBePassedInCorrectOrder.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/ParametersCorrectOrder.cs
analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarSyntaxNodeReportingContext.cs
analyzers/src/SonarAnalyzer.Common/Facade/SyntaxFacade.cs
analyzers/src/SonarAnalyzer.Common/Helpers/MethodParameterLookupBase.cs
analyzers/src/SonarAnalyzer.Common/Rules/ParametersCorrectOrderBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Extensions/SyntaxNodeExtensions.cs
analyzers/src/SonarAnalyzer.VisualBasic/Facade/VisualBasicFacade.cs
analyzers/src/SonarAnalyzer.VisualBasic/Facade/VisualBasicSyntaxFacade.cs
analyzers/src/SonarAnalyzer.VisualBasic/Helpers/VisualBasicSyntaxHelper.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/ParametersCorrectOrder.cs
analyzers/tests/SonarAnalyzer.UnitTest/Extensions/SyntaxNodeExtensionsTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Facade/CSharpFacadeTests.cs
analyzers/tests/SonarAnalyzer.UnitTest/Facade/SyntaxFacadeTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Facade/VisualBasicFacadeTests.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/ParametersCorrectOrderTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ParametersCorrectOrder.CSharp12.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ParametersCorrectOrder.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ParametersCorrectOrder.vb

Fixes #8070
Fixes #8071
The original implementation was rewritten from scratch. The reasons are
* The implementation didn't follow our principals
* The analyzer wasn't derived from `SonarDiagnosticAnalyzer<TSyntaxKind>`
* The registration happened in the derived classes instead of the base class
* `LanguageFacade` wasn't used
* There was a mixture of `abstract` methods (e.g., `GetArgumentTypeSymbolInfo`) and passed delegates (e.g., `getLocationToReport` parameter in `ReportIncorrectlyOrderedParameters`) which are both used as language-specific holes for the language-neutral implementation
* The `ArgumentIdentifier` private class and derived classes are not needed
* The logic was complex to follow
The current implementation follows our standards more closely and moves a lot of logic to the …

Fix S2234 FN: primary constructors for records, classes and structs

---

analyzers/SonarAnalyzer.sln
analyzers/tests/SonarAnalyzer.Net8.UnitTest/ReadMe.md
analyzers/tests/SonarAnalyzer.Net8.UnitTest/Rules/SelfAssignmentTest.cs
analyzers/tests/SonarAnalyzer.Net8.UnitTest/SonarAnalyzer.Net8.UnitTest.csproj
analyzers/tests/SonarAnalyzer.Net8.UnitTest/TestCases/SelfAssignment.cs
analyzers/tests/SonarAnalyzer.Net8.UnitTest/packages.lock.json
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/ParseOptionsHelper.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Verifier.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/VerifierBuilder.cs
azure-pipelines.yml

Fixes #8171 
I've tested the coverage import with a separate PR that I had to remove. Here is how it looks on sonarcloud:
and this is the build: https://dev.azure.com/sonarsource/DotNetTeam%20Project/_build/results?buildId=79428

Add project with .Net 8 unit tests

---

analyzers/its/expected/Nancy/Nancy--net452-S3254.json
analyzers/its/expected/Nancy/Nancy--netstandard2.0-S3254.json
analyzers/its/expected/akka.net/Akka--netstandard2.0-S3254.json
analyzers/its/expected/akka.net/Akka.Cluster--netstandard2.0-S3254.json
analyzers/its/expected/akka.net/Akka.Cluster.Metrics--netstandard2.0-S3254.json
analyzers/its/expected/akka.net/Akka.Cluster.Sharding--netstandard2.0-S3254.json
analyzers/its/expected/akka.net/Akka.DistributedData--netstandard2.0-S3254.json
analyzers/its/expected/akka.net/Akka.Persistence--netstandard2.0-S3254.json
analyzers/its/expected/akka.net/Akka.Persistence.Sql.Common--netstandard2.0-S3254.json
analyzers/its/expected/akka.net/Akka.Persistence.Sql.TestKit--netstandard2.0-S3254.json
analyzers/its/expected/akka.net/Akka.Persistence.TCK--netstandard2.0-S3254.json
analyzers/its/expected/akka.net/Akka.Remote--netstandard2.0-S3254.json
analyzers/its/expected/akka.net/Akka.Streams--netstandard2.0-S3254.json
analyzers/its/expected/akka.net/Akka.TestKit--netstandard2.0-S3254.json
analyzers/src/SonarAnalyzer.CSharp/Rules/RedundantArgument.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundantArgument.CSharp12.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundantArgument.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundantArgument.Named.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundantArgument.NoNamed.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundantArgument.cs

Fixes #8096
Also reverts #4620
~Blocked by #8238~

Fix S3254 FN: primary constructors

---

analyzers/src/SonarAnalyzer.CSharp/Extensions/ISymbolExtensions.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/VariableShadowsField.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/VariableShadowsFieldTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/VariableShadowsField.CSharp12.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/VariableShadowsField_PartialClass1.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/VariableShadowsField_PartialClass2.cs

Fix S1117 FN: support primary constructors

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CastShouldNotBeDuplicated.CSharp12.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CastShouldNotBeDuplicated.cs

Adds repro for https://github.com/SonarSource/sonar-dotnet/issues/223
Created after [this discussion](https://github.com/SonarSource/sonar-dotnet/issues/8121#issuecomment-1767818794).

S3247: Add repro for #223

---

pom.xml
sonar-csharp-plugin/pom.xml
sonar-vbnet-plugin/pom.xml

It was introduced in https://github.com/SonarSource/sonar-dotnet/pull/8164/files and it's not needed.

Revert SQ min version change

---

analyzers/its/expected/Nancy/Nancy--net452-S2930.json
analyzers/its/expected/Nancy/Nancy--netstandard2.0-S2930.json
analyzers/its/expected/akka.net/Akka--netstandard2.0-S2930.json
analyzers/its/expected/akka.net/Akka.Cluster.Tests.Performance--netcoreapp3.1-S2930.json
analyzers/its/expected/akka.net/Akka.Persistence.Sql.Common--netstandard2.0-S2930.json
analyzers/its/expected/akka.net/Akka.Remote.Tests.Performance--netcoreapp3.1-S2930.json
analyzers/its/expected/akka.net/Akka.Streams--netstandard2.0-S2930.json
analyzers/its/expected/akka.net/Akka.Tests.Performance--netcoreapp3.1-S2930.json
analyzers/its/expected/akka.net/RemotePingPong--net471-S2930.json
analyzers/its/expected/akka.net/RemotePingPong--net5.0-S2930.json
analyzers/its/expected/akka.net/RemotePingPong--netcoreapp3.1-S2930.json
analyzers/its/expected/akka.net/Samples.Akka.AspNetCore--netcoreapp3.1-S2930.json
analyzers/src/SonarAnalyzer.CSharp/Rules/DisposableNotDisposed.cs
analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DisposableNotDisposed.cs

Fix S2930 FN: Track System.Threading.CancellationTokenSource

---

analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/ClearTextProtocolsAreSensitive.cs

The 5 compiled regex used in  ClearTextProtocolsAreSensitive are not cached between instances and are adding a significant JIT compilation overhead. This PR fixes this:
akka.net project
Before: 
After:
Before: 18th most expensive operation with 14,5 seconds
After: 55 ms

ClearTextProtocolsAreSensitive: Reuse compiled regex

---

analyzers/tests/SonarAnalyzer.UnitTest/AnalysisContext/SonarSyntaxNodeReportingContextTest.cs

`IsRedundantPrimaryConstructorBaseTypeContext` wasn't under test properly. Now that https://github.com/dotnet/roslyn/pull/70655 has fixed the double invocation, we need to make sure that `IsRedundantPrimaryConstructorBaseTypeContext` returns `true` on the invocation that will be suppressed in the future. The test will fail once https://github.com/dotnet/roslyn/pull/70655 is released, and therefore, a compiler version check was already included and only needs to be updated once we know the correct version number.

IsRedundantPrimaryConstructorBaseTypeContext: Add tests

---

analyzers/src/SonarAnalyzer.CSharp/Rules/SerializationConstructorsShouldBeSecured.cs

Fixes #8228
Added also in the list of obsolete rules: https://docs.google.com/spreadsheets/d/1-30aNgv2Ust0RjiCi-gtAmyRDPrB9IhwA2Mor5LBYlE/edit#gid=0
In previously deleted rules none (from the ones I deleted), except one, was annotated as obsolete ([example](https://github.com/SonarSource/sonar-dotnet/pull/8049/files) ) but I think it's good to do so.

Annotate S4212 as obsolete

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/ExceptionCandidate.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Extensions/IOperationExtensions.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.CSharp6.cs

Make TrackedSymbol capable of resolving FlowCaptures and Conversions in Field/PropertyReference.Instance
Fixes:
```
class Sample
{
private object _foo1;
void ConditionalThisFieldAccess()
{
this._foo1 = null;
this?._foo1.ToString(); // FN
}
}
```

Fix S2259 FN: FlowCaptures in Field/PropertyReference.Instance

---

analyzers/src/SonarAnalyzer.CFG/Roslyn/ControlFlowGraphCache.cs
analyzers/src/SonarAnalyzer.CFG/Sonar/CSharpControlFlowGraph.cs
analyzers/src/SonarAnalyzer.CSharp/Extensions/SyntaxNodeExtensions.cs
analyzers/src/SonarAnalyzer.CSharp/LiveVariableAnalysis/SonarCSharpLiveVariableAnalysis.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/DeadStores.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/InfiniteRecursion.SonarCfg.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/InfiniteRecursion.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/MemberInitializerRedundant.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/MethodParameterUnused.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/RedundantJumpStatement.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/SymbolicExecutionRunner.cs
analyzers/src/SonarAnalyzer.Common/Rules/SymbolicExecutionRunnerBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/SymbolicExecution/SymbolicExecutionRunner.cs
analyzers/tests/SonarAnalyzer.UnitTest/CFG/Sonar/SonarControlFlowGraphTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Common/RuleTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Extensions/SyntaxNodeExtensionsTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/LiveVariableAnalysis/RoslynLiveVariableAnalysisTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/SymbolicExecutionRunnerTest.cs

Better review commit by commit.

SE: Refactor CreateCfg method to get the SyntaxNode as input as is without having to retrieve its body.

---

analyzers/src/SonarAnalyzer.Common/Json/Parsing/LexicalAnalyzer.cs

Fixes issue introduced [here](https://github.com/SonarSource/sonar-dotnet/pull/8312#discussion_r1388294151).
To reproduce the issue you need to switch to a Windows locale that uses a decimal separator different than `.`: for example french.

JSON Lexical Analyzer: Fix locale on decimal parsing

---

analyzers/src/SonarAnalyzer.CSharp/Rules/StaticFieldInGenericClass.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/StaticFieldInGenericClass.cs

Fix S2743 FP: Arrow properties do not have static fields

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnusedPrivateMember.CSharp7.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnusedPrivateMember.CSharp8.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnusedPrivateMember.Fixed.Batch.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnusedPrivateMember.Fixed.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnusedPrivateMember.cs

S1144: Add repro for #8342

---

analyzers/rspec/cs/S4790.json
analyzers/rspec/vbnet/S4790.json
analyzers/src/SonarAnalyzer.CSharp/sonarpedia.json
analyzers/src/SonarAnalyzer.VisualBasic/sonarpedia.json

Fixes #8290
Remark: the only RSPEC that has been changed outside of the scope of the .NET Squad is the change in S4790. 
It was done by @hendrik-buchwald-sonarsource in [this PR](https://github.com/SonarSource/rspec/pull/3450). 
It removes `spring` from the tags, which is correct.

Update RSPEC before 9.14 release

---

analyzers/src/SonarAnalyzer.Common/Rules/Utilities/FileMetadataAnalyzerBase.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/FileMetadataAnalyzerTest.cs

Fixes #7858
Fairly simple change to use the cached value for `IsGenerated`. This seemed to be the only remaining code that didn't use the extension method.
According to the issue, `UtilityAnalyzerBase` was also affected but it seemed it was fixed in the meantime already.

FileMetadataAnalyzer: Use tree.IsGenerated extension method

---

analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/NullPointerDereference.cs
analyzers/src/SonarAnalyzer.VisualBasic/SymbolicExecution/Roslyn/NullPointerDereference.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/NullPointerDereferenceSyntaxKindWalkerTests.cs

See also #8103
This PR fixes the params array allocation caused by IsAnyKind and reactors the SyntaxWalker to do the SyntaxKind checks in the dedicated Visit... methods. That way the number of comparisons is reduced.

NullPointerDereference.SyntaxKindWalker reduce allocations and evaluations in the hot path

---

analyzers/src/SonarAnalyzer.CSharp/Rules/Utilities/TokenTypeAnalyzer.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/TokenTypeAnalyzerTest.Classifier.cs

SemanticModel queries caused by `ClassifyMemberAccess` are the main contributor to the TokenTypeAnalyzer performance by far:
We can not fully guarantee the correctness of the classification without querying the semantic model:
```cs
_ = A.B.C;
```
Here we already know that `C` can not be a type, but for `A` and `B` it is not decidable. The following definitions of `A` and `B` could be valid:
```cs
// All Properties:
class A { B B { get; } } // the above would be interpreted like this.A.B.C;
class A { static B B { get; } } // B is a static member and `A` refers to a type
class A { class B { static C C { get; } } // B is a nested class in A and C is a static property of B
```
We can use one heuristic to minimize the number of queries: Such accesses often start with locals, or parameters, …

TokenTypeAnalyzer: Use heuristic for lowercase identifier

---

analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/PubliclyWritableDirectoriesBase.cs

see also #8181
Strips of another 4,5 seconds (or 0,08%) by caching the JITed regex in `IsSensitiveDirectoryUsage`:
Before:
After:
Before
After

Improve S5443 performance: Reuse compiled Regex

---

analyzers/src/SonarAnalyzer.CSharp/Rules/InfiniteRecursion.RoslynCfg.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/InfiniteRecursion.SonarCfg.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/InfiniteRecursion.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/SymbolicExecutionRunner.cs

Legacy Sonar CFG creating used to depend on `CSharpSyntaxNode`. This was removed quite some time ago, while working on Roslyn-based CFG and SE.
This PR removes the last leftovers from that process.

Remove unneeded CSharpSyntaxNode casts

---

analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/DoNotHardcodeCredentialsBase.cs

see also #8181 and #8183
Before:
After:

Improve S2068 performance: Reuse compiled Regex

---

analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/ClearTextProtocolsAreSensitive.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/DisablingCsrfProtection.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/PermissiveCors.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/JSInvokableMethodsShouldBePublic.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/UseStringCreate.cs
analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarAnalysisContext.cs
analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarCompilationStartAnalysisContext.cs
analyzers/src/SonarAnalyzer.Common/Rules/DateAndTimeShouldNotBeUsedasTypeForPrimaryKeyBase.cs
analyzers/src/SonarAnalyzer.Common/Rules/DoNotCallMethodsBase.cs
analyzers/src/SonarAnalyzer.Common/Rules/UseUnixEpochBase.cs
analyzers/tests/SonarAnalyzer.UnitTest/AnalysisContext/SonarAnalysisContextTest.Register.cs

Fix #8399
Before the changes (for oqtane.framework):
After the changes:

Remove HasMatchingScope from Execute for SyntaxNode

---

analyzers/tests/SonarAnalyzer.UnitTest/AnalysisContext/SonarAnalysisContextTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/AssertionArgsShouldBePassedInCorrectOrderTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/DoNotUseLiteralBoolInAssertionsTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/TestClassShouldHaveTestMethodTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/TestMethodShouldContainAssertionTest.cs

NUnit 4.0 release had breaking changes. Some tests with `Constants.NuGetLatestVersion` are failing due to that. To make the test pass `NuGetLatestVersion` is replaced by the fixed version `3.14.0`. 
#8409 was created to follow up on the breaking change, as the assertion methods are moved to another type and namespace and we need to adopt a couple of rules to reflect that.

S3415, S2701, S2699, S2187: Fix failing tests for NUnit 4.0 release

---

analyzers/src/SonarAnalyzer.CFG/ShimLayer/ISymbolNullableExtensions.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/RedundantCast.cs
analyzers/src/SonarAnalyzer.Common/Helpers/TypeHelper.cs
analyzers/tests/SonarAnalyzer.UnitTest/Wrappers/ISymbolNullableExtensionsTest.cs

Part of #6825
This PR lights up NullableAnnotation() for all symbols that support this property. It also adds the missing usage in RedundantCast that motivated #6825.
The PR was started by working on #5217 which was postponed until later.

S1905: Use NullableAnnotation() to find differences in type annotations

---

analyzers/src/SonarAnalyzer.CFG/ShimLayer/SyntaxKindEx.cs

We've missed this one:
https://github.com/dotnet/roslyn/blob/b3e63468749b56e9b30334bbd5312a723b5cc3ab/src/Compilers/CSharp/Portable/Syntax/SyntaxKind.cs#L886

ShimLayer: Add SyntaxKindEx.FunctionPointerCallingConvention

---

analyzers/src/SonarAnalyzer.Common/Rules/Utilities/CopyPasteTokenAnalyzerBase.cs
analyzers/src/SonarAnalyzer.Common/Rules/Utilities/FileMetadataAnalyzerBase.cs
analyzers/src/SonarAnalyzer.Common/Rules/Utilities/LogAnalyzerBase.cs
analyzers/src/SonarAnalyzer.Common/Rules/Utilities/MetricsAnalyzerBase.cs
analyzers/src/SonarAnalyzer.Common/Rules/Utilities/UtilityAnalyzerBase.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/AnalysisWarningAnalyzerTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/CopyPasteTokenAnalyzerTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/FileMetadataAnalyzerTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/LogAnalyzerTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/MetricsAnalyzerTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/SymbolReferenceAnalyzerTest.cs
analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/TokenTypeAnalyzerTest.cs

Fixes #6558
Fixes #7368
See https://github.com/SonarSource/sonar-dotnet/issues/7368#issuecomment-1618104968 for the acceptance criteria.

Performance: UtilityAnalyzerBase calls GetSemanticModel for each SyntaxTree

---

analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarCompilationStartAnalysisContext.cs

Fixes #8406
Cache the result of ShouldAnalyzeTree and other checks per SyntaxTree in a dictionary.
Before:
After:
Allocation is going down from 13'633 MB to 11'838 MB overall.
Most of it is saved in `RegisterNodeAction`:
Before:
After:

Cache RegisterNodeAction checks result per SyntaxTree

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/ExceptionCandidate.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Extensions/IOperationExtensions.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/TypeCatalog.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.ExceptionCandidate.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs

Fix S2583 FP: Variable Set in Catch Block

---

analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs

S2589: Add FP repro for #8449

---

its/pom.xml
its/src/test/java/com/sonar/it/shared/TestUtils.java

Bump S4NET to [latest (6.0.0.81631)](https://github.com/SonarSource/sonar-scanner-msbuild/releases/tag/6.0.0.81631)
The 6.0.0.81631 release of the S4NET is a major version release, introducing several breaking changes that need to be tested with `sonar-dotnet` ITs.
The PR stays in draft for the time being, since we may not need this if we successfully run on the latest S4NET.
The work to run on the latest S4NET, instead of a fixed version, will be done in the context of https://github.com/SonarSource/sonar-scanner-msbuild/issues/1774

Bump Scanner for .NET to 6.0.0.81631 for ITs

---

.github/workflows/CreateMilestone.yml

When we create a new milestone, a new issue is created like this: #8443
It CC's PM to see if rules needs update after our release. The CC makes you get email notifications from the card.
This updates it from Tom to Denis.

GitHub workflow: cc Denis from new milestone

---

azure-pipelines.yml

Temporary revert until the assembly signing is fixed.
```
smctl sync:
smctl : The term 'smctl' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

Revert BUILD-3696 Use agent pool on AWS

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/CompoundAssignment.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp8.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs

Fix S2583 FP: Delegate unsubscription

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Extensions/IOperationExtensions.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationDispatcher.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/DeconstructionAssignment.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/ProgramState.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ProgramStateTest.OperationAndSymbolValue.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp10.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp7.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp8.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp9.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.CSharp10.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyNullableValueAccess.CSharp10.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyNullableValueAccess.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/HashesShouldHaveUnpredictableSalt.CSharp10.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/InitializationVectorShouldBeRandom.CSharp10.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.CSharp10.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ObjectsShouldNotBeDisposedMoreThanOnce.cs

Fixes #7057 
The PR aims to fix FPs related to deconstruction assignments.
It doesn't handle:
- pattern matching involving tuples
- TupleBinaryOperation (e.g. `if ((first, second) == ("abc", "xyz"))`)
These scenarios need to be handled in separate PRs.

Fix S2583/S2589 FP: Tuple deconstruction assignment

---

analyzers/src/SonarAnalyzer.Common/Helpers/TypeHelper.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Binary.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Binary.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs

Fix S2583 FP: Should not raise on double condition

---

analyzers/src/SonarAnalyzer.VisualBasic/Rules/MethodParameterUnused.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/MethodParameterUnused.vb

Fix S1172 FP: VB names should not be case sensitive

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Throw.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.TryCatchFinally.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Monitor.TryCatch.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Monitor.TryCatch.vb

Fix S2583 FP: nested try catch blocks

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Invocation.cs
analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Invocation.cs
analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp8.cs

Fix S2589 FP: Custom Equals(null) is wrongly assumed to always return false

---

.github/workflows/RequestReview.yml
.github/workflows/SubmitReview.yml

#8505 didn't work as expected, as COLLABORATOR gets promoted to CONTRIBUTOR and cannot distinguish internal/external

GitHub workflow: Improve author_association to NONE only

---

analyzers/tests/SonarAnalyzer.Test/TestCases/UnusedPrivateMember.Fixed.Batch.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/UnusedPrivateMember.Fixed.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/UnusedPrivateMember.cs

S1144: Add FP/FN Repro for #8532

---

analyzers/tests/SonarAnalyzer.Test/Rules/ExcludeFromCodeCoverageAttributesNeedJustificationTest.cs

The lowercase directive was not recognized and UT was not run. IT appeared in UT issues on SC during the rename

UTs: Fix ExcludeFromCodeCoverageAttributesNeedJustificationTest

---

analyzers/its/expected/Automapper/AutoMapper--net461-S4027.json
analyzers/its/expected/Automapper/AutoMapper--netstandard2.0-S4027.json
analyzers/its/expected/Nancy/Nancy--net452-S4027.json
analyzers/its/expected/Nancy/Nancy--netstandard2.0-S4027.json
analyzers/src/SonarAnalyzer.CSharp/Rules/ExceptionsNeedStandardConstructors.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/ExceptionsNeedStandardConstructors.cs

Fix S4027 FP: BinaryFormatter. Serialization constructors are obsolete and should not be required

---

README.md

Follow-up of #8516
Resolving [this comment](https://github.com/SonarSource/sonar-dotnet/pull/8516#discussion_r1442655426)
About re-ci-infrastructure, according to Mate:
_You are absolutely right. 
re-ci-infrastructure was used to provision the GCP infrastructure, but it's now deprecated following the switch to AWS. I'll take care of archiving the code at the end of January. 
Thanks for updating the README. Please let me know if clarification is needed in the documentation of dotnet-infra or re-ci-images._

Documentation: Remove re-ci-infrastructure links to dead documentation/code

---

analyzers/src/SonarAnalyzer.CSharp/Rules/MethodShouldBeNamedAccordingToSynchronicity.cs

May fix https://community.sonarsource.com/t/false-negative-async-suffix-reported-when-the-character-a-or-a-is-in-front-of-the-async-suffix/107390
The issue is not reproducible on my side but the pattern used is not recommended by Microsoft:
> The [ToUpper](https://learn.microsoft.com/en-us/dotnet/api/system.string.toupper?view=net-8.0) method is often used to convert a string to uppercase so that it can be used in a case-insensitive comparison. A better method to perform case-insensitive comparison is to call a string comparison method that has a [StringComparison](https://learn.microsoft.com/en-us/dotnet/api/system.stringcomparison?view=net-8.0) parameter whose value you set to [StringComparison.CurrentCultureIgnoreCase](https://learn.microsoft.com/en-us/dotnet/api/system.stringcomparison …

S4261: Simplify name comparrission

---

analyzers/src/SonarAnalyzer.CSharp/Rules/BooleanLiteralUnnecessary.cs
analyzers/src/SonarAnalyzer.Common/Rules/BooleanLiteralUnnecessaryBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/BooleanLiteralUnnecessary.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/BooleanLiteralUnnecessary.CSharp8.Fixed.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/BooleanLiteralUnnecessary.CSharp8.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/BooleanLiteralUnnecessary.Fixed.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/BooleanLiteralUnnecessary.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/BooleanLiteralUnnecessary.vb

Fix S1125 FP: Type check for objects and dynamic types

---

analyzers/src/SonarAnalyzer.Common/Rules/SecurityPInvokeMethodShouldNotBeCalledBase.cs

Fixes #7960 
RSPEC update has already been done in #8018, so it is basically only adding the `[Obsolete]` attribute.
Internal documentation about [deprecation](https://xtranet-sonarsource.atlassian.net/wiki/spaces/LANG/pages/2907832321/How+to+deprecate+then+delete+a+rule+in+sonar-dotnet.).

Deprecate rule S3884

---

analyzers/its/regression-test.ps1
scripts/build/build-utils.ps1
scripts/build/dev-build.ps1

As part of [MMF-3594](https://sonarsource.atlassian.net/browse/MMF-3594), we are dropping support for MSBuild 14.
The goal of this PR is to remove all the MSBuild 14 test infrastructure from the analyzer.
[MMF-3594]: https://sonarsource.atlassian.net/browse/MMF-3594?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove MSBuild 14 related logic

---

azure-pipelines.yml

Part of #8542 
Only the last commit `TestFramework: Fix coverage` needs a review. The rest is here to prove that covered is not 0% anymore

TestFramework: Fix coverage

---

its/pom.xml

Similar to [this scanner PR](https://github.com/SonarSource/sonar-scanner-msbuild/pull/1845), we want to fail if for some reason no tests are discovered.

Add 'failIfNoTests' in the Maven ITs

---

its/src/test/java/com/sonar/it/shared/TestUtils.java

This should be reverted as soon as SQ is stable again.

Java ITs: Use LATEST_RELEASE SQ version

---

azure-pipelines.yml

This is a quick quick-fix for coverage issue. A proper fix will coverage
We have problem with agent working directories again. File was imported like this - note `1` in the path
```
"C:\\sonar-ci\\_work\\1\\s\\analyzers\\tests\\SonarAnalyzer.TestFramework\\Analyzers\\DummyAnalyzerWithLocation.cs",\
```
and coverage was computed on an agent with a different working directory, note `2` in the path.
```
16:17:30.748 DEBUG: Did not find deterministic source path in 'C:\sonar-ci\_work\2\s\analyzers\tests\SonarAnalyzer.TestFramework\Analyzers\DummyAnalyzerWithLocation.cs'. Will skip this coverage entry. Verify sonar.sources in .sonarqube\out\sonar-project.properties.
16:17:30.748 DEBUG: CoveredFile created: (ID '968', path 'C:\sonar-ci\_work\2\s\analyzers\tests\SonarAnalyzer.TestFramework\Analyz …
```

Coverage: Quick fix pattern after migration to AWS

---

analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/DiagnosticsComparerTest.cs
analyzers/tests/SonarAnalyzer.TestFramework/Verification/DiagnosticVerifier.cs
analyzers/tests/SonarAnalyzer.TestFramework/Verification/DiagnosticsComparer.cs
analyzers/tests/SonarAnalyzer.TestFramework/Verification/IssueLocationCollector.cs
analyzers/tests/SonarAnalyzer.TestFramework/Verification/IssueValidation/CompilationIssues.cs

Part of #8543 
This PR:
* Creates `CompilationIssues` class that holds issues from all files from a compilation. It will be heavily used later for way more logic.
* Comments out unused `DiagnosticComparer` for now. That will be reworked/partially reused later.

TestFramework: Create CompilationIssues class

---

analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/IssueValidation/CompilationIssuesTest.cs
analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/IssueValidation/IssueLocationTest.cs
analyzers/tests/SonarAnalyzer.TestFramework/Common/LogTester.cs
analyzers/tests/SonarAnalyzer.TestFramework/Extensions/StringAssertionsExtensions.cs
analyzers/tests/SonarAnalyzer.TestFramework/Verification/IssueValidation/CompilationIssues.cs
analyzers/tests/SonarAnalyzer.TestFramework/Verification/IssueValidation/IssueLocation.cs

Part of #8543 
This is a prerequisite needed to properly implement issue matching. 
The algorithm will be roughly like:
```
For Each Key In Actual.UniqueKeys
BuildPairs(Actual.Remove(Key), Expected.Remove(Key))
Next
```
where `Remove` will give us what was removed for the key and considered "done done".
`BuildPairs` will find best matches between these two groups.

TestFramework: Implement CompilationIssues class

---

analyzers/NuGet.Config
azure-pipelines.yml

In order to avoid problems with repox integration (server errors, HTTP response code 500) we have to specify an URL that contains the protocol version and also to specify the protocol version in the NuGet.config file.

Use correct NuGet api and specify protocol version

---

analyzers/src/SonarAnalyzer.CSharp/Extensions/SyntaxNodeExtensions.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/AbstractTypesShouldNotHaveConstructors.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/EmptyMethod.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/EmptyMethodCodeFix.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/ReturnEmptyCollectionInsteadOfNull.cs
analyzers/tests/SonarAnalyzer.Test/Rules/EmptyMethodTest.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/EmptyMethod.CSharp11.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/EmptyMethod.CSharp9.Comment.Fixed.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/EmptyMethod.CSharp9.Throw.Fixed.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/EmptyMethod.CSharp9.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/EmptyMethod.Comment.Fixed.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/EmptyMethod.Throw.Fixed.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/EmptyMethod.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/ReturnEmptyCollectionInsteadOfNull.cs

S1186: also inspect empty set and init and empty local functions

---

analyzers/tests/SonarAnalyzer.Test/AnalysisContext/SonarAnalysisContextBaseTest.ShouldAnalyzeTree.cs
analyzers/tests/SonarAnalyzer.Test/Metrics/CSharpExecutableLinesMetricTest.cs
analyzers/tests/SonarAnalyzer.Test/Rules/Hotspots/DisablingRequestValidationTest.cs
analyzers/tests/SonarAnalyzer.Test/Rules/MethodParameterUnusedTest.cs
analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/VerifierBuilderTest.cs
analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/VerifierTest.cs
analyzers/tests/SonarAnalyzer.TestFramework/Verification/DiagnosticVerifier.cs
analyzers/tests/SonarAnalyzer.TestFramework/Verification/Verifier.cs
analyzers/tests/SonarAnalyzer.TestFramework/Verification/VerifierBuilder.cs

Part of #8543 
The previous Razor validation in `Verifier` class is unfortunate, as it compiles files from temp directory, but uses files from TestCases directory to compute expected issues. Those files do not match on their paths, causing issues not being paired properly.

TestFramework: Rework Razor verification

---

analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/VerifierTest.cs

To be reverted after 9.19 release
For context (internal link): https://sonarsource.slack.com/archives/C012KBFFYD6/p1706698914234329

Ignore Verify_Razor_WithFramework test

---

analyzers/tests/SonarAnalyzer.TestFramework/Verification/Verifier.cs

This fixes `Verify_Razor_WithFramework` test that fails due to missing dependencies.

Restore dependencies before compilation

---

analyzers/src/SonarAnalyzer.RuleDescriptorGenerator/packages.lock.json
analyzers/tests/SonarAnalyzer.Net8.Test/packages.lock.json

- to avoid `error NU1403: Package content hash validation failed for runtime.rhel.7-x64.runtime.native.System.Security.Cryptography.OpenSsl.4.3.0. The package is different than the last restore.`

Recompute nuget lock files

---

analyzers/tests/SonarAnalyzer.Test/Rules/CheckFileLicenseTest.cs
analyzers/tests/SonarAnalyzer.Test/Rules/MethodsShouldNotHaveTooManyLinesTest.cs
analyzers/tests/SonarAnalyzer.Test/Rules/SymbolicExecution/SymbolicExecutionRunnerTest.cs
analyzers/tests/SonarAnalyzer.TestFramework/Verification/DiagnosticVerifier.cs

Part of #8601
Next step: Rename `GetDiagnosticsNoExceptions` to `AnalyzerDiagnostics`

TestFramework: Refactor DiagnosticVerifier.AnalyzerExceptions

---

analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/IssueValidation/CompilationIssuesTest.cs
analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/IssueValidation/IssueLocationCollectorTest.ExpectedBuildErrors.cs
analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/IssueValidation/IssueLocationCollectorTest.ExpectedIssueLocations.cs
analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/IssueValidation/IssueLocationCollectorTest.FindIssueLocations.cs
analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/IssueValidation/IssueLocationCollectorTest.FindPreciseIssueLocations.cs
analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/IssueValidation/IssueLocationCollectorTest.MergeLocations.cs
analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/IssueValidation/IssueLocationCollectorTest.cs
analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/IssueValidation/IssueLocationPairTest.cs
analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/IssueValidation/IssueLocationTest.cs
analyzers/tests/SonarAnalyzer.TestFramework/Verification/DiagnosticVerifier.cs
analyzers/tests/SonarAnalyzer.TestFramework/Verification/IssueValidation/IssueLocation.cs
analyzers/tests/SonarAnalyzer.TestFramework/Verification/IssueValidation/IssueLocationCollector.cs
analyzers/tests/SonarAnalyzer.TestFramework/Verification/IssueValidation/IssueLocationPair.cs

Part of #8601 
We will need 3 types of issues: `Primary`, `Secondary`, `Error` instead of the current `IsPrimary` flag
This doesn't do any functional changes.

TestFramework: Change IssueLocation.IsPrimary to IssueType

---

.editorconfig

This asks to replace
```
var filePath = Location.Uri.Substring(Location.Uri.IndexOf("analyzers/its"));
```
with fairly unreadable
```
var filepath = Location.Uri[Location.Uri.IndexOf("analyzers/its")..];
```

Disable IDE0057

---

analyzers/src/SonarAnalyzer.Common/Rules/PropertyGetterWithThrowBase.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/PropertyGetterWithThrow.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/PropertyGetterWithThrow.vb

Fixes #8611
…to ignore the issue, if the returned exception type is derived from one of the AllowedExceptionBaseTypes.
New test cases failed before and worked after fix.

Fix S2372 FP: Add support for method invocations

---

analyzers/tests/SonarAnalyzer.Test/Metrics/CSharpExecutableLinesMetricTest.cs
analyzers/tests/SonarAnalyzer.Test/Rules/CallerInformationParametersShouldBeLastTest.cs
analyzers/tests/SonarAnalyzer.Test/Rules/DeclareTypesInNamespacesTest.cs
analyzers/tests/SonarAnalyzer.Test/Rules/NativeMethodsShouldBeWrappedTest.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/DeclareTypesInNamespaces.BeforeCSharp8.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/DeclareTypesInNamespaces.CSharp7.cs
analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/VerifierTest.cs

Fix broken master after #8621. All of the changes are related to that.
UTs on `master` run for all language version. This causes some UTs to fail due to different error number on different language versions, like
```
// Error [CS8026] Feature 'default interface implementation' is not available in C# 5. Please use language version 8.0 or greater.
// Error [CS8059] Feature 'default interface implementation' is not available in C# 6. Please use language version 8.0 or greater.
// Error [CS8107] Feature 'default interface implementation' is not available in C# 7.0. Please use language version 8.0 or greater.
```
We don't really need to test the invalid syntax scenarios on multiple versions.

UTs: Fix language versions

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Binary.Collections.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/CollectionTracker.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/ObjectCreation.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/EmptyCollectionsShouldNotBeEnumeratedBase.cs
analyzers/tests/SonarAnalyzer.Test/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs

Part of #7866
Moves the following logic from the rule to the `ObjectCreation` processor:
```csharp
void Foo(List<int> one)
{
var two= new List<int>(one); // apply one's "CollectionConstraint"  to two
}
```

SE: Move CollectionConstraint from S4158 to the engine (part 1)

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Argument.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/EmptyCollectionsShouldNotBeEnumeratedBase.cs
analyzers/tests/SonarAnalyzer.Test/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Binary.cs
analyzers/tests/SonarAnalyzer.Test/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
analyzers/tests/SonarAnalyzer.Test/TestFramework/SymbolicExecution/ValidatorTestCheck.cs

Part of https://github.com/SonarSource/sonar-dotnet/issues/7866
Moves out of the rule the `ArgumentOperation` part.
Applies to this code:
```csharp
var x = new List<int>(); // CollectionConstraint set to "Empty"
// x is used as an argument, CollectionConstraint is removed. 
// Because we have no idea what the method does.
AddStuff(x); 
x.Clear(); // We do not raise, because there is no constraint here. (intended)

SE: Move CollectionConstraint from S4158 to the engine (part 3)

---

analyzers/src/SonarAnalyzer.Common/Rules/UriShouldNotBeHardcodedBase.cs

We had an AD0001 on this rule on cirrus https://cirrus-ci.com/task/6479785799450624 see also our [internal slack conversation](https://sonarsource.slack.com/archives/C012KBFFYD6/p1707387101212299?thread_ts=1707294010.300419&cid=C012KBFFYD6).
```
CSC : error AD0001: Analyzer 'SonarAnalyzer.Rules.CSharp.UriShouldNotBeHardcoded' threw an exception of type 'System.Text.RegularExpressions.RegexMatchTimeoutException' with message 'The RegEx engine has timed out while trying to match a pattern to an input string. This can occur for many reasons, including very large inputs or excessive backtracking caused by nested quantifiers, back-references and other factors.'. [C:\sonar-ci\Project\src\dotnet-svcutil\lib\src\dotnet-svcutil-lib.csproj]
```
This PR increases the timeout from the default 100ms …

Increase Regex timeout for S1075

---

analyzers/tests/SonarAnalyzer.Test/Rules/CheckFileLicenseTest.cs
analyzers/tests/SonarAnalyzer.TestFramework.Test/TestCases/DiagnosticVerifierException.Concurrent.cs
analyzers/tests/SonarAnalyzer.TestFramework.Test/TestCases/DiagnosticVerifierException.File1.cs
analyzers/tests/SonarAnalyzer.TestFramework.Test/TestCases/DiagnosticVerifierException.File2.cs
analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/DiagnosticVerifierExceptionTest.cs
analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/DiagnosticVerifierTest.cs
analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/IssueValidation/IssueLocationPairTest.cs
analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/VerifierTest.cs
analyzers/tests/SonarAnalyzer.TestFramework/Common/Paths.cs
analyzers/tests/SonarAnalyzer.TestFramework/Verification/DiagnosticVerifier.cs
analyzers/tests/SonarAnalyzer.TestFramework/Verification/DiagnosticVerifierException.cs
analyzers/tests/SonarAnalyzer.TestFramework/Verification/IssueValidation/IssueLocationPair.cs
analyzers/tests/SonarAnalyzer.TestFramework/Verification/IssueValidation/VerificationMessage.cs

Fixes #8546 
The exact stack trace will change a bit to make it work in Rider too in #8725

TestFramework: Make failed assertions clickable

---

analyzers/its/regression-test.ps1

Unify all output from a project build under `output/<PROJECT>` folder.
Also add same logging for MsBuild projects as there was for dotnet projects.

ITs: Store build log in output\Project folder

---

analyzers/tests/ITs.JsonParser.Test/ITs.JsonParser.Test.csproj
analyzers/tests/ITs.JsonParser.Test/TestFramework/PathsTest.cs
analyzers/tests/SonarAnalyzer.TestFramework.Test/Build/ProjectBuilderTest.cs
analyzers/tests/SonarAnalyzer.TestFramework.Test/Build/SnippetCompilerTest.cs
analyzers/tests/SonarAnalyzer.TestFramework.Test/Common/EnvironmentVariableScopeTest.cs
analyzers/tests/SonarAnalyzer.TestFramework.Test/Common/TestHelperTest.cs
analyzers/tests/SonarAnalyzer.TestFramework.Test/Extensions/CompilationExtensionsTest.cs
analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/VerifierTest.cs
analyzers/tests/SonarAnalyzer.TestFramework/Build/ProjectBuilder.cs
analyzers/tests/SonarAnalyzer.TestFramework/Build/SnippetCompiler.cs
analyzers/tests/SonarAnalyzer.TestFramework/Common/AssertIgnoreScope.cs
analyzers/tests/SonarAnalyzer.TestFramework/Common/TestHelper.cs
analyzers/tests/SonarAnalyzer.TestFramework/Extensions/CompilationExtensions.cs
analyzers/tests/SonarAnalyzer.TestFramework/Verification/CodeFixVerifier.cs
analyzers/tests/SonarAnalyzer.TestFramework/Verification/Verifier.cs

Follow up of #8542 
The coverage of this PR itself is laying in a big picture, as it shows the number isolated to this PR, not to the whole changes of Test Framework.
CompilationExtensions.cs: There was an uncovered condition on line 29 and uncovered line 33. That changed to uncovered condition on line 33 as planned. 
ProjectBuilder.cs: It shows 3/4 on a condition that should be 2/2: Tooling issue with #8696

TestFramework: Bump coverage

---

analyzers/its/sources/NetCore31/global.json
analyzers/its/sources/NetCore31WithConfigurableRules/global.json

When compiling the `NetCore31WithConfigurableRules` and `NetCore31` projects with dotnet SDK  `3.1.201`,  the autogenerated files are dropped in a generated path in the `%Temp%` folder instead of the expected `analyzers/its`.
This creates confusion when we compute the expected vs. actual since we keep the file location as info in the JSON.
I set the version to be the current one we use in the CI, which seems to work as expected locally and on the CI.

ITs: Update minimum dotnet sdk version for .NET 3.1 projects

---

.editorconfig

Fixes https://sonarsource.slack.com/archives/C01H2B58DE1/p1707746528445389 😆
This prevents hints that we don't blidnly follow

Disable IDE0290

---

analyzers/SonarAnalyzer.sln

Fixes #8752
Add build order solution dependency to prevent running the Clear target twice.
https://github.com/SonarSource/sonar-dotnet/blob/8e491ee2944b481970c80991716920ba614e655a/analyzers/src/Directory.Build.targets#L10-L12

ITs: Fix ITs.JsonParser.exe build under Visual Studio

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/ArithmeticCalculator.cs
analyzers/tests/SonarAnalyzer.Test/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.ArithmeticCalculator.cs
analyzers/tests/SonarAnalyzer.Test/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Loops.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/CalculationsShouldNotOverflow.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/CalculationsShouldNotOverflow.vb
analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs

SE Loops: Addition for same sign operands

---

docs/coding-style.md

`ValueTuples` are not available for users with MsBuild 14. While MsBuild 14 is not officially supported anymore, we still want to avoid breaking it, if possible.
Since we do not have tests for MsBuild 14 anymore, pipelines will not turn red, when using `ValueTuples`. Thus it needs to be added to our coding style (and eventually checked via Analyzer).

Coding Style update: Do not use `ValueTuples`

---

analyzers/its/regression-test.ps1
analyzers/src/ITs.JsonParser/Program.cs

When differences are found between `actual` and `expected`, report the differences and directly update `expected`.
This will allow to review the changes also in the local git changes, and directly commit them when needed.
https://trello.com/c/oU5j9gig/100-its-always-move-actual-to-expected

ITs: Update expected issues when differences are found

---

analyzers/src/SonarAnalyzer.CSharp/Rules/ExceptionsShouldBeLogged.cs
analyzers/src/SonarAnalyzer.Shared/LoggingFrameworkIdentifier.cs

Contains the method names used by the logging frameworks so they can be reused by all logging rules.

Extract LoggingFrameworkIdentifier

---

analyzers/its/expected/Ember-MM/S6667-Ember.Plugins.json
analyzers/rspec/cs/S6667.html
analyzers/rspec/cs/S6667.json
analyzers/src/SonarAnalyzer.CSharp/Extensions/ArgumentSyntaxExtensions.cs
analyzers/src/SonarAnalyzer.CSharp/Extensions/InvocationExpressionSyntaxExtensions.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/ExceptionsShouldBeLogged.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/MessageTemplates/MessageTemplateAnalyzer.cs
analyzers/src/SonarAnalyzer.Shared/LoggingFrameworkMethods.cs
analyzers/tests/SonarAnalyzer.Test/Rules/ExceptionsShouldBeLoggedTest.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/ExceptionsShouldBeLogged.cs

- update rule title
- avoid FPs when the `InnerException` is logged
- add support for NLog logging extension methods

Rule S6667: Update after peach validation

---

analyzers/src/SonarAnalyzer.CSharp/Rules/MessageTemplates/MessageTemplateAnalyzer.cs
analyzers/tests/SonarAnalyzer.Test/Rules/NamedPlaceholdersShouldBeUniqueTest.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/NamedPlaceholdersShouldBeUnique.cs

Fixes two issues:
- Deriving from serilog should raise.
- Using interpolated strings should not raise.

Template rules update after peach validation

---

analyzers/src/SonarAnalyzer.CSharp/Rules/MessageTemplates/MessageTemplateAnalyzer.cs
analyzers/tests/SonarAnalyzer.Test/Helpers/MessageTemplatesTest.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/NamedPlaceholdersShouldBeUnique.cs

Supports expressions containing `AddExpression`, like `"string1" + "string2"`.

Template rules update after peach validation part#2

---

analyzers/src/SonarAnalyzer.CSharp/Rules/DoNotUseLiteralBoolInAssertions.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/DoNotUseLiteralBoolInAssertions.Xunit.cs

S2701 is not raising for `Assert.True` in xUnit because `Assert.Fail` was introduced in 2020 version `2.4.2` and `Assert.True(false, message)` was a way to simulate it. Now that we are promoting this rule to SonarWay we want to play it safe and avoid raising also for `Assert.False` for the same reason `Assert.False(true, message)`.

Fix S2701 FP: avoid raising for xUnit Assert.True()

---

analyzers/src/SonarAnalyzer.CSharp/Rules/LoggingArgumentsShouldBePassedCorrectly.cs
analyzers/tests/SonarAnalyzer.Test/Rules/LoggingArgumentsShouldBePassedCorrectlyTest.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/LoggingArgumentsShouldBePassedCorrectly.cs

Rule S6668 has an exception in the specification that I did not implement in the first version of the rule:
> This rule will not raise an issue if one of the parameters mentioned above is passed twice, once as a separate argument to the invocation and once as an argument to the message format.
```csharp
try { }
catch (Exception ex)
{
logger.LogDebug(ex, "An exception occured {Exception}.", ex); // Compliant
}
```

Rule S6668: Handle the rule exceptions

---

analyzers/.runsettings

This reduces UTs runtime from 7 to 3 minutes. It could have been down to 2 minutes if we solve the Razor problem.
This will instruct test adapter to run all test DLLs in parallel when running UTs via Test Explorer.
Because SonarAnalyzer.Test (net48) and SonarAnalyzer.Test (net7.0) have bot roughly 7000+ UTs, the whole UT run is as short as the longer of those.
The key follow up problem to solve is extremely slow Razor UTs.

UTs: Add .runsettings to run UTs in parallel

---

analyzers/src/SonarAnalyzer.CSharp/Rules/DontUseTraceWrite.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/DontUseTraceWrite.cs

Improves #8841 
Adds an exception to the rule for cases like this:
```cs
Trace.Write(message: "Login failed!", category: "Security"); // uses it's own custom category
```

Improve S6670: Ignore when Trace.Write() called with category parameter

---

analyzers/its/sources/ManuallyAddedNoncompliantIssues.CS/NetFramework35/NetFramework35.csproj
analyzers/its/sources/ManuallyAddedNoncompliantIssues.CS/NetFramework35/packages.config
analyzers/its/sources/ManuallyAddedNoncompliantIssues.CS/NetFramework4/NetFramework4.csproj
analyzers/its/sources/ManuallyAddedNoncompliantIssues.CS/NetFramework4/packages.config
analyzers/its/sources/ManuallyAddedNoncompliantIssues.CS/NetFramework45/NetFramework45.csproj
analyzers/its/sources/ManuallyAddedNoncompliantIssues.CS/NetFramework45/packages.config
analyzers/its/sources/ManuallyAddedNoncompliantIssues.CS/NetFramework452/NetFramework452.csproj
analyzers/its/sources/ManuallyAddedNoncompliantIssues.CS/NetFramework452/packages.config

Part of #8883
The `Microsoft.NETFramework.ReferenceAssemblies` package is a wrapper around all versions of .NET Framework reference assemblies packages, like 
```
Microsoft.NETFramework.ReferenceAssemblies.net35
Microsoft.NETFramework.ReferenceAssemblies.net40
Microsoft.NETFramework.ReferenceAssemblies.net45
Microsoft.NETFramework.ReferenceAssemblies.net452
...
```
These packages contain rather empty .NET Framework DLLs with references only. Their purpose is to be able to build a project targeting specific old .NET Framework versions on a build machine, that doesn't have it installed.
I don't have any of those installed at my current PC and I'm able to build the project. I cannot open it in VS and work with it, but that's fine.

ITs: Use Microsoft.NETFramework.ReferenceAssemblies

---

analyzers/src/SonarAnalyzer.CSharp/Rules/BooleanLiteralUnnecessaryCodeFix.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/BooleanLiteralUnnecessary.Fixed.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/BooleanLiteralUnnecessary.cs

Bug: S1125 code fix does not add ! when transforming x == false.

---

analyzers/its/expected/Nancy/S6602-Nancy-net452.json
analyzers/its/expected/Nancy/S6602-Nancy-netstandard2.0.json
analyzers/its/expected/akka.net/S6602-Akka-netstandard2.0.json
analyzers/its/expected/akka.net/S6602-Akka.MultiNodeTestRunner-net471.json
analyzers/its/expected/akka.net/S6602-Akka.MultiNodeTestRunner-net5.0.json
analyzers/its/expected/akka.net/S6602-Akka.MultiNodeTestRunner-netcoreapp3.1.json
analyzers/its/expected/akka.net/S6602-Akka.Serialization.Hyperion-netstandard2.0.json
analyzers/its/expected/akka.net/S6602-Akka.Streams-netstandard2.0.json
analyzers/src/SonarAnalyzer.Common/Rules/FindInsteadOfFirstOrDefaultBase.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/FindInsteadOfFirstOrDefault.Array.cs

Rule S6602: Update the message for arrays

---

analyzers/its/expected/CSharpLatest/S2094-CSharpLatest-net8.0.json
analyzers/src/SonarAnalyzer.CSharp/Rules/ClassShouldNotBeEmpty.cs
analyzers/src/SonarAnalyzer.Common/Rules/ClassShouldNotBeEmptyBase.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/ClassShouldNotBeEmpty.CSharp9.cs

Fix S2094 FP: Marker interfaces for record types

---

analyzers/its/expected/Nancy/S1117-Nancy-net452.json
analyzers/its/expected/Nancy/S1117-Nancy-netstandard2.0.json
analyzers/src/SonarAnalyzer.CSharp/Rules/VariableShadowsField.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/VariableShadowsField.CSharp12.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/VariableShadowsField.cs

Fix S1117 FP: Local variables declared in static context

---

analyzers/src/SonarAnalyzer.CSharp/Rules/RequireAttributeUsageAttribute.cs
analyzers/tests/SonarAnalyzer.Test/Rules/MarkAssemblyWithAttributeUsageAttributeTest.cs
analyzers/tests/SonarAnalyzer.Test/Rules/RequireAttributeUsageAttributeTest.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/RequireAttributeUsageAttribute.cs

As reported at [Sonar Community](https://community.sonarsource.com/t/fp-s3993-requires-abstract-attributes-to-be-decorated-with-attributeusage/110870), Abstract attributes should not report S3993.
Not that due to the latest changes, I can not build Sonar locally, as I have no JFrog account, and I could not find how to set this up in the documentation.

Fix S3993 FP: Allow abstract attributes not to decorate Attribute usage

---

analyzers/src/SonarAnalyzer.CSharp/Extensions/SyntaxNodeExtensions.cs

It is redundant and covered by the SimpleNameSyntax already.

Remove IdentifierNameSyntax from GetIdentifier

---

analyzers/tests/ITs.JsonParser.Test/ITs.JsonParser.Test.csproj
analyzers/tests/ITs.JsonParser.Test/packages.lock.json
analyzers/tests/SonarAnalyzer.Net8.Test/SonarAnalyzer.Net8.Test.csproj
analyzers/tests/SonarAnalyzer.Net8.Test/packages.lock.json
analyzers/tests/SonarAnalyzer.Test/SonarAnalyzer.Test.csproj
analyzers/tests/SonarAnalyzer.Test/packages.lock.json
analyzers/tests/SonarAnalyzer.TestFramework.Test/SonarAnalyzer.TestFramework.Test.csproj
analyzers/tests/SonarAnalyzer.TestFramework.Test/packages.lock.json
azure-pipelines.yml

Bump Microsoft.NET.Test.Sdk to 17.9.0

---

analyzers/src/SonarAnalyzer.CFG/ShimLayer/SyntaxKindEx.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/ArrayPassedAsParams.cs
analyzers/src/SonarAnalyzer.Common/Rules/ArrayPassedAsParamsBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/ArrayPassedAsParams.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/ArrayPassedAsParams.CSharp12.cs

Fix S3878 FP: When input array is collection expression with spread operator

---

analyzers/src/SonarAnalyzer.CSharp/Rules/SqlKeywordsDelimitedBySpace.cs
analyzers/tests/SonarAnalyzer.Test/Rules/SqlKeywordsDelimitedBySpaceTest.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/SqlKeywordsDelimitedBySpace.CSharp10.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/SqlKeywordsDelimitedBySpace.cs

Fix S2857 FP: Rule is not checking SQL keywords in const interepolated string

---

analyzers/src/SonarAnalyzer.CSharp/Rules/CastShouldNotBeDuplicated.cs
analyzers/tests/SonarAnalyzer.Test/Rules/CastShouldNotBeDuplicatedTest.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/CastShouldNotBeDuplicated.cshtml
analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/VerifierTest.cs
analyzers/tests/SonarAnalyzer.TestFramework/Verification/Verifier.cs

Fix S3247 FP: Rule should not trigger when variable is used for data binding on Razor/MVC views

---

analyzers/rspec/cs/S1192.html
analyzers/rspec/cs/S1481.html
analyzers/rspec/cs/S2955.html
analyzers/rspec/cs/S6934.html
analyzers/rspec/vbnet/S1192.html
analyzers/rspec/vbnet/S1481.html
analyzers/src/SonarAnalyzer.CSharp/sonarpedia.json
analyzers/src/SonarAnalyzer.VisualBasic/sonarpedia.json

Update RSPEC before 9.23 release

---

analyzers/src/SonarAnalyzer.CFG/ShimLayer/AnalysisContext/SymbolStartAnalysisContextWrapper.cs

Fixes AD0001
See https://cirrus-ci.com/task/5657719948967936?logs=build#L1542
```
CSC : error AD0001: Analyzer 
'SonarAnalyzer.Rules.CSharp.RouteTemplateShouldNotStartWithSlash' threw an exception of type 
'System.TypeInitializationException' with message 'The type initializer for 
'SonarAnalyzer.ShimLayer.AnalysisContext.SymbolStartAnalysisContextWrapper' 
threw an exception.'.
```
I had a UT for the fix, but it broke all the other tests because the type initializer is called only once per assembly load. I tried with AppDomains, but that didn't work. The only solution would be to isolate the test in a dedicated UT assembly, which does seem to be overkill.

Fix TypeInitializationException in SymbolStartAnalysisContextWrapper

---

analyzers/tests/SonarAnalyzer.Test/Rules/MethodParameterUnusedTest.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/MethodParameterUnused.CSharp11.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/MethodParameterUnused.RoslynCfg.Fixed.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/MethodParameterUnused.RoslynCfg.cs

Reproducer for #8988 S1172 FP: Don't report on partial method parameters

---

analyzers/its/expected/ManuallyAddedNoncompliantIssues.CS/S4487-NetFramework48.json
analyzers/rspec/cs/S1144.html
analyzers/src/SonarAnalyzer.CSharp/Rules/UnusedPrivateMember.cs
analyzers/src/SonarAnalyzer.Common/Helpers/SymbolHelper.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/UnusedPrivateMember.Fixed.Batch.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/UnusedPrivateMember.Fixed.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/UnusedPrivateMember.cs

Fix S1144 FP: Ignore Serializable members

---

analyzers/src/SonarAnalyzer.CSharp/Rules/ClassShouldNotBeEmpty.cs
analyzers/tests/SonarAnalyzer.Test/Rules/ClassShouldNotBeEmptyTest.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/ClassShouldNotBeEmpty.CSharp12.cs

Consider the following piece of code:
``` C#
class ChildClass() : BaseClass(42){ }
class BaseClass(int value) { }
```
Than `ChildClass` should not be considered an empty class, and hence should not raise [S2094](https://rules.sonarsource.com/csharp/RSPEC-2094),
I'm in doubt if S2094 should raise on `BaseClass`, but you could argue that there should be a different rule, that checks if the parameters of a primary constructor (on classes only) is actually used.

Fix S2094 FP: Primary constructors for classes should be handled equal to records

---

analyzers/SonarAnalyzer.sln
analyzers/src/SonarAnalyzer.CSharp.Styling/Common/DescriptorFactory.cs
analyzers/src/SonarAnalyzer.CSharp.Styling/Rules/FileScopeNamespace.cs
analyzers/src/SonarAnalyzer.CSharp.Styling/SonarAnalyzer.CSharp.Styling.csproj
analyzers/src/SonarAnalyzer.CSharp.Styling/packages.lock.json
analyzers/tests/SonarAnalyzer.CSharp.Styling.Test/Rules/FileScopeNamespaceTest.cs
analyzers/tests/SonarAnalyzer.CSharp.Styling.Test/SonarAnalyzer.CSharp.Styling.Test.csproj
analyzers/tests/SonarAnalyzer.CSharp.Styling.Test/TestCases/FileScopeNamespace.cs
analyzers/tests/SonarAnalyzer.CSharp.Styling.Test/packages.lock.json
azure-pipelines.yml

Create SonarAnalyzer.CSharp.Styling project

---

analyzers/src/SonarAnalyzer.CSharp/Extensions/SonarAnalysisContextExtensions.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/GetHashCodeEqualsOverride.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/GuardConditionOnEqualsOverride.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/StaticFieldWrittenFrom.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/ThisShouldNotBeExposedFromConstructors.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/VariableUnused.cs
analyzers/src/SonarAnalyzer.VisualBasic/Extensions/SonarAnalysisContextExtensions.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/VariableUnused.cs

These `SonarAnalysisContextExtensions.cs` are specific to a language (CSharp vs. VisualBasic) therefore their `TSyntaxKind` is already given by the project they reside in.
Generic argument is needed only in the layer below these files.

Simplify registration extensions

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/References.cs
analyzers/tests/SonarAnalyzer.Test/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.vb

Fix S2259 FP: `PropertyReference` does not learn from underlying symbol

---

analyzers/src/SonarAnalyzer.CSharp.Styling/Common/StylingAnalyzer.cs
analyzers/src/SonarAnalyzer.CSharp.Styling/Rules/FileScopeNamespace.cs
analyzers/src/SonarAnalyzer.CSharp.Styling/SonarAnalyzer.CSharp.Styling.csproj
analyzers/src/SonarAnalyzer.CSharp.Styling/packages.lock.json
analyzers/tests/SonarAnalyzer.CSharp.Styling.Test/Rules/FileScopeNamespaceTest.cs
analyzers/tests/SonarAnalyzer.CSharp.Styling.Test/TestCases/FileScopeNamespace.Compliant.cs
analyzers/tests/SonarAnalyzer.CSharp.Styling.Test/TestCases/FileScopeNamespace.cs
analyzers/tests/SonarAnalyzer.CSharp.Styling.Test/packages.lock.json

Fixes #9035
~~This is based on #9048 and #9049. These commits do not need review:~~
* ~~Simplify registration extensions~~
* ~~Create SonarAnalyzer.CSharp.Styling project~~
* ~~Update locks~~

New rule T0001: Use FileScoped namespaces

---

.editorconfig
analyzers/tests/SonarAnalyzer.Test/AnalysisContext/SonarAnalysisContextTest.Register.cs
analyzers/tests/SonarAnalyzer.Test/AnalysisContext/SonarSyntaxNodeReportingContextTest.cs

I don't know why it doesn't raise on Common, CSharp and VisualBasic projects.
We intentionally use a lot of symbols that are prohibited by the rule, see https://github.com/dotnet/roslyn-analyzers/blob/89c1a9dd4775efb2c55af106c23d5415d8177d5e/src/Microsoft.CodeAnalysis.Analyzers/Core/AnalyzerBannedSymbols.txt

Disable RS1036

---

analyzers/tests/SonarAnalyzer.CSharp.Styling.Test/SonarAnalyzer.CSharp.Styling.Test.csproj
analyzers/tests/SonarAnalyzer.TestFramework/SonarAnalyzer.TestFramework.csproj
analyzers/tests/SonarAnalyzer.TestFramework/packages.lock.json

While some projects already had 0.31.0, this one was few versions being. It was causing CS8036 error about not begin able to load types.
GH had some issues yesterday, the pipeline is fully green on Azure DevOps

Bump FluentAssertions.Analyzers to 0.31.0

---

analyzers/its/expected/akka.net/S2094-Akka-netstandard2.0.json
analyzers/src/SonarAnalyzer.Common/Rules/ClassShouldNotBeEmptyBase.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/ClassShouldNotBeEmpty.cs

Fix S2094 FP: Should not raise for messages

---

analyzers/src/SonarAnalyzer.Common/Rules/ClassShouldNotBeEmptyBase.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/ClassShouldNotBeEmpty.CSharp9.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/ClassShouldNotBeEmpty.cs

Fix S2094 FP: Implicit parameterless constructor widens the scope of the base class constructor 

---

analyzers/src/SonarAnalyzer.Common/Rules/ArrayPassedAsParamsBase.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/ArrayPassedAsParams.CSharp12.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/ArrayPassedAsParams.cs

Fix S3878 FP: Jagged arrays

---

analyzers/tests/SonarAnalyzer.Test/TestCases/NotAssignedPrivateMember.cs

S3459: add reproducer for #9106

---

analyzers/its/expected/CSharpLatest/S1144-CSharpLatest-net8.0.json
analyzers/its/expected/akka.net/S1144-Akka-netstandard2.0.json
analyzers/its/expected/akka.net/S1144-Akka.Benchmarks-netcoreapp3.1.json
analyzers/its/expected/akka.net/S1144-Akka.DI.TestKit-netstandard2.0.json
analyzers/src/SonarAnalyzer.CSharp/Rules/UnusedPrivateMember.cs
analyzers/tests/SonarAnalyzer.Test/Rules/UnusedPrivateMemberTest.Constructors.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/UnusedPrivateMember.Fixed.Batch.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/UnusedPrivateMember.Fixed.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/UnusedPrivateMember.cs

Fix S1144: Nested type constructor accessibility is wrong in the rule message

---

analyzers/src/SonarAnalyzer.Common/Helpers/AnalysisConfig.cs
analyzers/src/SonarAnalyzer.Common/Helpers/AnalysisConfigReader.cs
analyzers/src/SonarAnalyzer.Common/Helpers/ConfigSetting.cs
analyzers/tests/SonarAnalyzer.Test/Helpers/AnalysisConfigReaderTest.cs

Prerequisite for https://github.com/SonarSource/sonar-dotnet/issues/9061
We need to ILMerge styling analyzer, because it would collide with SonarAnalyzer otherwise.
We will eventually need to ILMerge CSharp analyzer too.
Inside ILMerged assembly, all merged types are internal and that breaks XmlSerializer.
XmlSerializer is evil anyway, so it's good to get rid of it.
We can't use DataContractSerializer here, because it does not support Xml attributes.

Replace XmlSerializer in AnalysisConfigReader

---

analyzers/src/SonarAnalyzer.Common/Helpers/ProjectConfig.cs
analyzers/src/SonarAnalyzer.Common/Helpers/ProjectConfigReader.cs

Prerequisite for #9061
We need to ILMerge styling analyzer, because it would collide with SonarAnalyzer otherwise.
We will eventually need to ILMerge CSharp analyzer too.
Inside ILMerged assembly, all merged types are internal and that breaks XmlSerializer.
XmlSerializer is evil anyway, so it's good to get rid of it.
We don't want to use use DataContractSerializer to be consistent with #9117, and because it puts too many constraints about element order in place.

Replace XmlSerializer in ProjectConfigReader

---

analyzers/NuGet.Config
analyzers/packaging/SonarAnalyzer.CSharp.Styling.nuspec
analyzers/src/Directory.Build.targets
analyzers/src/SonarAnalyzer.CSharp.Styling/SonarAnalyzer.CSharp.Styling.csproj
analyzers/src/SonarAnalyzer.CSharp.Styling/packages.lock.json
analyzers/tests/SonarAnalyzer.TestFramework/Verification/SuppressionHandler.cs

Fixes #9061
Rebase will be needed, these two commits do not need a review as they are in other PRs:
* Replace XmlSerializer in AnalysisConfigReader #9117 
* Replace XmlSerializer in ProjectConfigReader #9116

ILMerge SonarAnalyzer.CSharp.Styling into a single DLL

---

analyzers/src/SonarAnalyzer.Common/Rules/ClassShouldNotBeEmptyBase.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/ClassShouldNotBeEmpty.cs

Fixes #7591
Follow-up to #9081

Fix S2094 FP: Implicit parameterless constructor widens the scope of the base class constructor

---

analyzers/src/Directory.Build.targets
analyzers/src/SonarAnalyzer.CSharp.Styling/SonarAnalyzer.CSharp.Styling.csproj

`CleanBinaries` is responsible for deleting the `packaging/binaries` folder on `clean` or `rebuild`. It is potentially executed multiple times, which can cause problems if projects are not built in the same step (e.g., because of dependencies).
This PR adds a condition to the target to prevent it from being executed multiple times.
The idea for the solution comes from this [StackOverflow post](https://stackoverflow.com/a/46679661).

Execute `CleanBinaries` target only once

---

analyzers/src/SonarAnalyzer.CSharp.Styling/Rules/MemberVisibilityOrdering.cs
analyzers/tests/SonarAnalyzer.CSharp.Styling.Test/Rules/MemberVisibilityOrderingTest.cs
analyzers/tests/SonarAnalyzer.CSharp.Styling.Test/TestCases/MemberVisibilityOrdering.cs

New Rule T0009: Order the same member kind by its accessibility

---

analyzers/src/SonarAnalyzer.CSharp.Styling/Rules/UseNullInsteadOfDefault.cs
analyzers/src/SonarAnalyzer.CSharp/Helpers/CSharpSyntaxHelper.cs
analyzers/src/SonarAnalyzer.Common/Helpers/TypeHelper.cs
analyzers/tests/SonarAnalyzer.CSharp.Styling.Test/Rules/UseNullInsteadOfDefaultTest.cs
analyzers/tests/SonarAnalyzer.CSharp.Styling.Test/TestCases/UseNullInsteadOfDefault.cs

New Rule T0012: Use null instead of default for reference types

---

analyzers/src/SonarAnalyzer.CSharp.Styling/Rules/UseRegexSafeIsMatch.cs
analyzers/src/SonarAnalyzer.CSharp/Helpers/CSharpSyntaxHelper.cs
analyzers/src/SonarAnalyzer.Common/Helpers/TypeHelper.cs
analyzers/tests/SonarAnalyzer.CSharp.Styling.Test/Rules/UseRegexSafeIsMatchTest.cs
analyzers/tests/SonarAnalyzer.CSharp.Styling.Test/TestCases/UseRegexSafeIsMatch.cs

New Rule T0004: Use Regex.SafeIsMatch

---

analyzers/src/SonarAnalyzer.CSharp.Styling/Rules/ArrowLocation.cs
analyzers/src/SonarAnalyzer.CSharp.Styling/Rules/SeparateDeclarations.cs
analyzers/src/SonarAnalyzer.CSharp/Helpers/CSharpSyntaxHelper.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/CommentedOutCode.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/ConditionalsShouldStartOnNewLine.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/DeadStores.SonarCfg.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/LooseFilePermissions.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/IndentSingleLineFollowingConditional.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/RightCurlyBraceStartsLine.cs
analyzers/src/SonarAnalyzer.Common/Extensions/LocationExtensions.cs
analyzers/src/SonarAnalyzer.Common/Extensions/SyntaxTokenExtensions.cs
analyzers/src/SonarAnalyzer.Common/Rules/SingleStatementPerLineBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/CommentLineEnd.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/LooseFilePermissions.cs
analyzers/tests/SonarAnalyzer.CSharp.Styling.Test/Rules/SeparateDeclarationsTest.cs
analyzers/tests/SonarAnalyzer.CSharp.Styling.Test/TestCases/SeparateDeclarations.cs
analyzers/tests/SonarAnalyzer.Test/Helpers/LocationExtensionsTest.cs

New Rule T0016: Separate declarations by an empty line

---

.github/workflows/release.yml

This reverts commit 649688dd53550bf53e72ee4a5755b61fe07c0ee3.
v6 was unexpectedly deleted

Revert Bump SonarSource/gh-action_release from 5 to 6 (#8986)

---

analyzers/tests/SonarAnalyzer.Test/Rules/SymbolicExecution/ConditionEvaluatesToConstantTest.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
analyzers/tests/SonarAnalyzer.TestFramework/MetadataReferences/MetadataReferenceFacade.cs

Repro for #9204
Repro for https://github.com/SonarSource/sonar-dotnet/issues/8885

Repro for FP S2589: Assignment for captures are ignored

---

analyzers/src/SonarAnalyzer.CSharp/Rules/SwaggerActionReturnType.cs
analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/SwaggerActionReturnType.cs

Rule S6968: Add support for ProducesAttribute

---

analyzers/src/SonarAnalyzer.CSharp/ReuseClientBase.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/AspNet/AnnotateApiActionsWithHttpVerb.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/AspNet/ApiControllersShouldNotDeriveDirectlyFromControllerCodeFix.cs
analyzers/src/SonarAnalyzer.Common/Extensions/CompilationExtensions.cs
analyzers/src/SonarAnalyzer.Common/Helpers/AspNetMvcHelper.cs
analyzers/src/SonarAnalyzer.Common/Rules/AspNet/BackslashShouldBeAvoidedInAspNetRoutesBase.cs
analyzers/tests/SonarAnalyzer.Test/Common/DisjointSetsTest.cs
analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/VerifierTest.cs
analyzers/tests/SonarAnalyzer.TestFramework/MetadataReferences/MetadataReferenceFacade.cs
analyzers/tests/SonarAnalyzer.TestFramework/Verification/Verifier.cs

Fix styling issues on new code

---

analyzers/src/SonarAnalyzer.Common/Extensions/IParameterSymbolExtensions.cs
analyzers/src/SonarAnalyzer.Common/Extensions/ISymbolExtensions.cs
analyzers/src/SonarAnalyzer.Common/Extensions/ITypeSymbolExtensions.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Extensions/IOperationExtensions.cs
analyzers/tests/SonarAnalyzer.Test/CFG/Roslyn/RoslynControlFlowGraphTest.cs
analyzers/tests/SonarAnalyzer.Test/Extensions/IParameterSymbolExtensionsTest.cs
analyzers/tests/SonarAnalyzer.Test/Extensions/ISymbolExtensionsTest.cs
analyzers/tests/SonarAnalyzer.Test/Extensions/ITypeSymbolExtensionsTest.cs
analyzers/tests/SonarAnalyzer.Test/Helpers/KnownTypeTest.cs
analyzers/tests/SonarAnalyzer.Test/SonarAnalyzer.Test.csproj
analyzers/tests/SonarAnalyzer.Test/SymbolicExecution/Roslyn/IOperationExtensionsTest.cs

There are some file-scoped namespaces and file renames.  Review per commit should be easier

Rename TypeHelper to ITypeSymbolExtensions

---

analyzers/src/SonarAnalyzer.CSharp/Rules/AspNet/CallModelStateIsValid.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/AspNet/CallModelStateIsValid.cs

Improves #9095
The rule currently doesn't raise for classes decorated with the `[ApiController]` attribute, as it adds automatic request validation to the action methods.
This PR improves that by also checking whether any of the base classes of the Controller is decorated with that attribute.
This eliminates [FPs like this](https://peach.aws-prd.sonarsource.com/issues?projects=jellyfin&resolved=false&rules=csharpsquid%3AS6967&open=AY8vcfEsPfBcX2L0QXhf), where [the base class is marked with [ApiController]](https://github.com/jellyfin/jellyfin/blob/16b2483d848e9f66de48cb5eaa4ed40e14360617/Jellyfin.Api/BaseJellyfinApiController.cs#L12).

Improve S6967: Add check for base classes with ApiController attribute

---

analyzers/src/SonarAnalyzer.CSharp/Rules/AspNet/CallModelStateIsValid.cs
analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/AspNet/CallModelStateIsValid.cs

Improves #9095 
[Fixes FPs](https://peach.aws-prd.sonarsource.com/issues?projects=bitwarden-core&resolved=false&rules=csharpsquid%3AS6967&open=AY8vOYQHr4ooVA6A4nO1) where the controller action only has a [CancellationToken parameter](https://andrewlock.net/using-cancellationtokens-in-asp-net-core-mvc-controllers/).

Improve S6967: Filter out CancellationToken parameters

---

analyzers/src/SonarAnalyzer.CSharp/Rules/UnusedPrivateMember.cs
analyzers/tests/SonarAnalyzer.Test/Rules/UnusedPrivateMemberTest.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/UnusedPrivateMember.Fixed.Batch.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/UnusedPrivateMember.Fixed.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/UnusedPrivateMember.cs

Fixes #9219
Reviewing per-commit might be helpful.
Definitely check `ignore whitespace`, since file-scoped namespace destroys reviewability.
Commit 1: The actual change
Commit 2: UTs
Commit 3: CaYC

Fix S1144 FP: Getters/Setters of property with attribute are being flagged

---

analyzers/src/SonarAnalyzer.CSharp/Rules/AspNet/AvoidUnderPosting.cs
analyzers/tests/SonarAnalyzer.Test/Rules/AspNet/AvoidUnderPostingTest.cs

Improve S6964: Dont try to raise issue when Model and Controller are in different projects

---

analyzers/tests/SonarAnalyzer.Test/TestCases/ClassShouldNotBeEmpty.cs

S2094: Add Repro for #9241

---

analyzers/packaging/SonarAnalyzer.CSharp.nuspec
analyzers/packaging/SonarAnalyzer.VisualBasic.nuspec
analyzers/src/SonarAnalyzer.CSharp/SonarAnalyzer.CSharp.csproj
analyzers/src/SonarAnalyzer.VisualBasic/SonarAnalyzer.VisualBasic.csproj

The search "sonar dotnet" only reports the scanner, whereas "sonar" also returns the CSharp analyzer in the first position. 
Adding more tags would help discoverability on nuget.org.
See original ticket [here](https://trello.com/c/9TqRfMco/1306-improve-discoverability-of-sonar-analyzers-nuget-packages-on-vs-extensions-management).
Tested in https://int.nugettest.org/
Resources:
* https://learn.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-visual-studio?tabs=netcore-cli
* https://learn.microsoft.com/en-us/nuget/reference/nuspec?WT.mc_id=DT-MVP-5003978#tags

Improve discoverability of nuget packages

---

analyzers/src/SonarAnalyzer.CSharp.Styling/Rules/LambdaParameterName.cs
analyzers/tests/SonarAnalyzer.CSharp.Styling.Test/TestCases/LambdaParameterName.cs

` _ => 42` should be allowed, because `_` is more descriptive than `x` in this case and signals: "I do not care about the parameter." Rational: In `(_, _) => 42` `_` is a real discard, while in `_ => 42` it isn't only for back compatibility reasons.
See e.g. here:
https://sonarcloud.io/project/issues?resolved=false&pullRequest=8950&id=sonaranalyzer-dotnet&open=AY9NLK1CHaBGYjI6fPmk
`_` is a better name than `x` in such a case.

Fix T0010 FP: Allow "_" discard like parameter name

---

analyzers/src/SonarAnalyzer.CSharp.Styling/Rules/LambdaParameterName.cs
analyzers/tests/SonarAnalyzer.CSharp.Styling.Test/TestCases/LambdaParameterName.cs

Fixes
```cs
public delegate void SomeDelegate(int someParameterName);
public void Use(SomeDelegate action) { }
public void Test()
{
Use(x => { }); // Compliant
Use(someParameterName => { }); // FP
}
```

Fix T0010 FP: Allow delegate type parameter name

---

analyzers/tests/SonarAnalyzer.Test/Rules/IfCollapsibleTest.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/IfCollapsible.cs

S1066: Add reproducer for #9221

---

analyzers/src/SonarAnalyzer.CSharp/Extensions/SyntaxNodeExtensionsCSharp.cs
analyzers/src/SonarAnalyzer.CSharp/Facade/CSharpTrackerFacade.cs
analyzers/src/SonarAnalyzer.CSharp/Helpers/CSharpAttributeParameterLookup.cs
analyzers/src/SonarAnalyzer.CSharp/Helpers/CSharpMethodParameterLookup.cs
analyzers/src/SonarAnalyzer.CSharp/Trackers/CSharpArgumentTracker.cs
analyzers/src/SonarAnalyzer.Common/Facade/ITrackerFacade.cs
analyzers/src/SonarAnalyzer.Common/Helpers/ArgumentDescriptor.cs
analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
analyzers/src/SonarAnalyzer.Common/Helpers/MethodParameterLookupBase.cs
analyzers/src/SonarAnalyzer.Common/Helpers/RefKindEx.cs
analyzers/src/SonarAnalyzer.Common/Trackers/ArgumentContext.cs
analyzers/src/SonarAnalyzer.Common/Trackers/ArgumentTracker.cs
analyzers/src/SonarAnalyzer.Common/Trackers/TrackerBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Extensions/SyntaxNodeExtensionsVisualBasic.cs
analyzers/src/SonarAnalyzer.VisualBasic/Facade/VisualBasicFacade.cs
analyzers/src/SonarAnalyzer.VisualBasic/Facade/VisualBasicTrackerFacade.cs
analyzers/src/SonarAnalyzer.VisualBasic/Helpers/VisualBasicAttributeParameterLookup.cs
analyzers/src/SonarAnalyzer.VisualBasic/Helpers/VisualBasicMethodParameterLookup.cs
analyzers/src/SonarAnalyzer.VisualBasic/Trackers/VisualBasicArgumentTracker.cs
analyzers/tests/SonarAnalyzer.Test/Facade/VisualBasicFacadeTest.cs
analyzers/tests/SonarAnalyzer.Test/Trackers/ArgumentTrackerTest.cs

Adds an ArgumentDescriptor and logic to match an ArgumentSyntax against it.
Based on #8947

Add Argument tracker and tests

---

analyzers/tests/SonarAnalyzer.Test/Metrics/CSharpExecutableLinesMetricTest.cs
analyzers/tests/SonarAnalyzer.Test/Rules/Utilities/MetricsAnalyzerTest.cs
analyzers/tests/SonarAnalyzer.Test/Rules/Utilities/SymbolReferenceAnalyzerTest.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/Utilities/MetricsAnalyzer/Razor.razor
analyzers/tests/SonarAnalyzer.TestFramework.Test/Common/SourceGeneratorProviderTest.cs
analyzers/tests/SonarAnalyzer.TestFramework.Test/TestCases/Dummy.SecondaryLocation.razor
analyzers/tests/SonarAnalyzer.TestFramework.Test/TestCases/DummyExpressions.razor
analyzers/tests/SonarAnalyzer.TestFramework/Common/SourceGeneratorProvider.cs
azure-pipelines.yml

dotnet 8.0.5 introduced breaking changes when generating code for Razor files.
This PR updates our pipeline to:
- run UTs on 8.0.5
- describe the new behavior
Fixes: https://github.com/SonarSource/sonar-dotnet/issues/9291

UTs: run on dotnet 8.0.5

---

analyzers/src/SonarAnalyzer.Common/Metrics/MetricsBase.cs

 Razor mappings: Ensure we check if the mapped span is valid

---

analyzers/src/SonarAnalyzer.CSharp.Styling/Common/DescriptorFactory.cs
analyzers/src/SonarAnalyzer.CSharp.Styling/Common/StylingAnalyzer.cs
analyzers/src/SonarAnalyzer.CSharp/Common/DescriptorFactory.cs
analyzers/src/SonarAnalyzer.CSharp/SonarAnalyzer.CSharp.csproj
analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarAnalysisContextBase.cs
analyzers/src/SonarAnalyzer.Common/Analyzers/DiagnosticDescriptorFactory.cs
analyzers/src/SonarAnalyzer.Common/Analyzers/HotspotDiagnosticAnalyzer.cs
analyzers/src/SonarAnalyzer.Common/Analyzers/ParametrizedDiagnosticAnalyzer.cs
analyzers/src/SonarAnalyzer.Common/Analyzers/SonarDiagnosticAnalyzer.cs
analyzers/src/SonarAnalyzer.Common/Analyzers/TrackerHotspotDiagnosticAnalyzer.cs
analyzers/src/SonarAnalyzer.Common/SonarAnalyzer.Common.csproj
analyzers/src/SonarAnalyzer.VisualBasic/Common/DescriptorFactory.cs
analyzers/src/SonarAnalyzer.VisualBasic/SonarAnalyzer.VisualBasic.csproj
analyzers/tests/SonarAnalyzer.Test/Analyzers/DiagnosticDescriptorFactoryTest.cs
analyzers/tests/SonarAnalyzer.Test/SonarAnalyzer.Test.csproj
analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/CodeFixProviderTest.cs
analyzers/tests/SonarAnalyzer.TestFramework/SonarAnalyzer.TestFramework.csproj

The purpose of this is to move `DescriptorFactory` out of `SonarAnalyzer` namespace to a sub-namespace, as global using are finally available in C# and the type doesn't need to be in the root anymore.
On the way *DiagnosticAnalyzer were moved to `Analyzers` directory and namespace CaYC
Review per commit is suggested, as there's a file-scoped-namespace update on the way
ToDo: Send mail once done

Move DescriptorFactory and DiagnosticAnalyzers to namespaces

---

analyzers/src/SonarAnalyzer.CSharp/Rules/PasswordsShouldBeStoredCorrectly.cs
analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
analyzers/tests/SonarAnalyzer.Test/Rules/PasswordsShouldBeStoredCorrectlyTest.cs
analyzers/tests/SonarAnalyzer.TestFramework/MetadataReferences/NuGetMetadataReference.cs

Part of #8998
Whatever is checked, is implemented in this PR:

Create rule S5344: Passwords should not be stored in plain-text or with a fast hashing algorithm (Part 2)

---

analyzers/src/SonarAnalyzer.CSharp/Rules/AspNet/AvoidUnderPosting.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/AspNet/AvoidUnderPosting.CSharp8.cs

Fix S6964 FP: Should not raise for reference properties in nullable context

---

analyzers/tests/SonarAnalyzer.TestFramework.Test/Common/CombinatorialDataAttributeTest.cs
analyzers/tests/SonarAnalyzer.TestFramework/Common/CombinatorialDataAttribute.cs

Adds the CombinatorialDataAttribute for use in S6932

Add combinatorial data attribute

---

analyzers/src/SonarAnalyzer.CSharp/Rules/AspNet/SpecifyRouteAttribute.cs
analyzers/src/SonarAnalyzer.Common/Extensions/AttributeDataExtensions.cs
analyzers/src/SonarAnalyzer.Common/Helpers/AspNetMvcHelper.cs
analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
analyzers/src/SonarAnalyzer.Common/Rules/AspNet/RouteTemplateShouldNotStartWithSlashBase.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/AspNet/SpecifyRouteAttribute.CSharp12.cs

Fix S6934 FP: Route attributes derived from IRouteTemplateProvider

---

analyzers/src/SonarAnalyzer.CSharp/Rules/UseAwaitableMethod.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/UseAwaitableMethod_EF.cs

Fix S6966 FP: EntityFrameworks DbContext/DBSet Add/AddRange methods are preferred over their Async counterpart

---

analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/SecureRandomSeedsShouldNotBePredictable.cs
analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
analyzers/tests/SonarAnalyzer.Test/Rules/SecureRandomSeedsShouldNotBePredictableTest.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/SecureRandomSeedsShouldNotBePredictable.cs

Part of https://github.com/SonarSource/sonar-dotnet/issues/8992
Implementing Scenario 2
Also, added support for `Array.Initialize`, which re-sets an array to predictable.

Create rule S4347: 'SecureRandom' seeds should not be predictable (part 2)

---

analyzers/src/SonarAnalyzer.CSharp/Rules/AvoidExcessiveClassCoupling.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/AvoidExcessiveInheritance.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/ConditionalStructureSameCondition.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/ConditionalStructureSameImplementation.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/MultilineBlocksWithoutBrace.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/SwaggerActionReturnType.cs
analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarReportingContextBase.cs
analyzers/src/SonarAnalyzer.Common/Common/SecondaryLocation.cs
analyzers/src/SonarAnalyzer.Common/Extensions/CompilationExtensions.cs
analyzers/src/SonarAnalyzer.Common/Extensions/DiagnosticDescriptorExtensions.cs
analyzers/src/SonarAnalyzer.Common/Extensions/LocationExtensions.cs
analyzers/src/SonarAnalyzer.Common/Extensions/SyntaxTokenExtensions.cs
analyzers/src/SonarAnalyzer.Common/Helpers/SyntaxNodeExtensions.cs
analyzers/src/SonarAnalyzer.Common/Rules/CertificateValidationCheckBase.cs
analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/DoNotHardcodeCredentialsBase.cs
analyzers/src/SonarAnalyzer.Common/Rules/StringLiteralShouldNotBeDuplicatedBase.cs
analyzers/src/SonarAnalyzer.Common/Trackers/SyntaxTrackerBase.cs
analyzers/tests/SonarAnalyzer.Test/AnalysisContext/SonarSyntaxTreeReportingContextTest.cs
analyzers/tests/SonarAnalyzer.TestFramework/Verification/IssueValidation/CompilationIssues.cs

Prerequisite for #9174 
Review per commit shows the logical changes.
The purpose of this PR is to prepare everything that will be needed by all other rules. Migration of other rules (mainly monotounus removals of `DiagnosticDescriptorExtensions.CreateDiagnostic` will be in upcoming PRs)
The goals are:
* Make `ReportIssue` contract clear about `SecondaryLocation` boundary
* Hide the workaround with immutable dictionary of parameters
* Make reporting of secondary issues with messages super easy
* Fix bug where `ToProperties` does not respect `SecondaryLocation.Message`, but uses additional argument instead
I've changed `params object[]` to `params string[]` so we don't risk accidentally sending a collection of secondary locations (with a wrong type) to the params value.

SonarReportingContext: Add ReportIssue with SecondaryLocation

---

analyzers/src/SonarAnalyzer.CFG/ShimLayer/IPropertySymbolExtensions.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/AspNet/AvoidUnderPosting.cs
analyzers/tests/SonarAnalyzer.Test/Wrappers/IPropertySymbolExtensionTest.cs

Follow up to #9307
Fixes ToDo in  https://github.com/SonarSource/sonar-dotnet/blob/0876a571b93c5748ea8396b9f29ba53a6e54543f/analyzers/src/SonarAnalyzer.CSharp/Rules/AspNet/AvoidUnderPosting.cs#L84

Add IPropertySymbol.IsRequired() to ShimLayer

---

analyzers/src/SonarAnalyzer.CSharp/Rules/UseAwaitableMethod.cs
analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
analyzers/tests/SonarAnalyzer.Test/Rules/UseAwaitableMethodTest.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/UseAwaitableMethod_MongoDBDriver.cs

Fixes #9265
This implementation follows option 2 of https://github.com/SonarSource/sonar-dotnet/issues/9265#issuecomment-2126491852

Fix S6966 FP: Methods with different signatures should not trigger this rule.

---

analyzers/src/SonarAnalyzer.Common/Rules/ParametersCorrectOrderBase.cs
analyzers/tests/SonarAnalyzer.Test/Rules/ParametersCorrectOrderTest.cs

Fixes #8577
1st commit adds a reproducer, 2nd fixes it by using the new overloads from #9298

Fix S2234 Bug: AD0001 is thrown due to referencing a location outside of the current compilation

---

analyzers/its/expected/ManuallyAddedNoncompliantIssues.CS/S6964-IntentionalFindings-net8.0.json
analyzers/rspec/cs/S6964.html
analyzers/rspec/cs/S6964.json
analyzers/src/SonarAnalyzer.CSharp/Rules/AspNet/AvoidUnderPosting.cs
analyzers/src/SonarAnalyzer.Common/Extensions/ISymbolExtensions.cs
analyzers/tests/SonarAnalyzer.Test/Rules/AspNet/AvoidUnderPostingTest.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/AspNet/AvoidUnderPosting.CSharp8.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/AspNet/AvoidUnderPosting.CSharp9.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/AspNet/AvoidUnderPosting.cs

Fixes #9263
RSPEC PR: https://github.com/SonarSource/rspec/pull/3942

Fix S6964 FN: Rule should raise in case of value type property annotated with RequiredAttribute

---

analyzers/src/SonarAnalyzer.CSharp/Rules/DoNotTestThisWithIsOperator.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/ExceptionsShouldBeLoggedOrThrown.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/FunctionComplexity.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/GetHashCodeMutable.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/ImplementIDisposableCorrectly.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/ImplementISerializableCorrectly.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/XmlExternalEntityShouldNotBeParsed.cs
analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarReportingContextBase.cs
analyzers/src/SonarAnalyzer.Common/Common/SecondaryLocation.cs
analyzers/src/SonarAnalyzer.Common/Rules/CognitiveComplexityBase.cs
analyzers/src/SonarAnalyzer.Common/Rules/MethodOverloadsShouldBeGroupedBase.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/CalculationsShouldNotOverflowBase.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/ConditionEvaluatesToConstantBase.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/PublicMethodArgumentsShouldBeCheckedForNullBase.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/RestrictDeserializedTypesBase.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SymbolicRuleCheck.cs
analyzers/tests/SonarAnalyzer.Test/AnalysisContext/SonarSyntaxTreeReportingContextTest.cs

Follow up of #9323 to prevent AD0001s with secondary locations raised on a referenced projects.
This PR:
* Replaces old usages with secondary locations with the new, safe API*
* Updates SE `ReportIssue` to the same principle
*Except one that will follow in a later PR

ReportIssue: Use safe overloads for secondary locations

---

analyzers/src/SonarAnalyzer.CSharp/Rules/AspNet/AvoidUnderPosting.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/AspNet/AvoidUnderPosting.CSharp12.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/AspNet/AvoidUnderPosting.CSharp9.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/AspNet/AvoidUnderPosting.cs

Fix S6964 FP: Properties with default values

---

analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/SecureRandomSeedsShouldNotBePredictable.cs
analyzers/tests/SonarAnalyzer.Test/Rules/SecureRandomSeedsShouldNotBePredictableTest.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/SecureRandomSeedsShouldNotBePredictable.cs
analyzers/tests/SonarAnalyzer.TestFramework/MetadataReferences/NuGetMetadataReference.cs

Covers **Scenario 3**
Also fixed some minor issues.
Part of #8992

Create rule S4347: 'SecureRandom' seeds should not be predictable (part 3)

---

analyzers/src/SonarAnalyzer.CSharp/Rules/AspNet/SpecifyRouteAttribute.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/CastShouldNotBeDuplicated.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/ConsumeValueTaskCorrectly.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/DisposeNotImplementingDispose.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/ExceptionsShouldBeLogged.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/InheritedCollidingInterfaceMembers.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/LoggingArgumentsShouldBePassedCorrectly.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/MessageTemplates/LoggingTemplatePlaceHoldersShouldBeInOrder.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/MessageTemplates/NamedPlaceholdersShouldBeUnique.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/MessageTemplates/UsePascalCaseForNamedPlaceHolders.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/ReturnEmptyCollectionInsteadOfNull.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/SwaggerActionReturnType.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/TooManyLoggingCalls.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/XXE/XmlReaderSettingsValidator.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/XmlExternalEntityShouldNotBeParsed.cs
analyzers/src/SonarAnalyzer.Common/Helpers/EnumerableExtensions.cs
analyzers/src/SonarAnalyzer.Common/Rules/AspNet/RouteTemplateShouldNotStartWithSlashBase.cs
analyzers/src/SonarAnalyzer.Common/Rules/CertificateValidationCheckBase.cs
analyzers/src/SonarAnalyzer.Common/Rules/CommentsShouldNotBeEmptyBase.cs
analyzers/src/SonarAnalyzer.Common/Rules/StringLiteralShouldNotBeDuplicatedBase.cs
analyzers/src/SonarAnalyzer.Common/Rules/UseWhereBeforeOrderByBase.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/ConditionEvaluatesToConstantBase.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/RestrictDeserializedTypesBase.cs
analyzers/tests/SonarAnalyzer.TestFramework/Analyzers/DummyAnalyzerWithLocation.cs

Follow up of https://github.com/SonarSource/sonar-dotnet/pull/9298 to prevent AD0001s like in #9323 
This PR replaces usage of `Diagnostic.Create` overloads that
* Did not use the safe `DiagnosticDescriptorExtensions.CreateDiagnostic` (replaced in #9346)
* Used secondary locations parameter

ReportIssue: Replace Diagnostic.Create with secondary locations

---

analyzers/src/SonarAnalyzer.CSharp/Extensions/SonarAnalysisContextExtensions.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/AspNet/UseAspNetModelBinding.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/MarkAssemblyWithNeutralResourcesLanguageAttribute.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/UninvokedEventDeclaration.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/UnusedPrivateMember.cs
analyzers/src/SonarAnalyzer.VisualBasic/Extensions/SonarAnalysisContextExtensions.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/OptionExplicitOn.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/OptionStrictOn.cs

Follow up of #9298 effort
This PR: 
* Removes two obsolete `SonarAnalysisContextExtensions` extensions
* Deduplicates extensions to extend a base class, instead of duplicating extensions for `SonarCompilationReportingContext` and `SonarSymbolReportingContext` separately

ReportIssue: Remove obsolete overloads from SonarAnalysisContextExtensions

---

analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/SecureRandomSeedsShouldNotBePredictable.cs

Part of #8992
Do NOT merge until #9333 is merged.
Please leave as DRAFT.

S4347: Implement ShouldExecute

---

analyzers/src/SonarAnalyzer.CSharp/Rules/AspNet/AvoidUnderPosting.cs
analyzers/src/SonarAnalyzer.Common/Extensions/ISymbolExtensions.cs
analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
analyzers/tests/SonarAnalyzer.Test/Rules/AspNet/AvoidUnderPostingTest.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/AspNet/AvoidUnderPosting.cs
analyzers/tests/SonarAnalyzer.TestFramework/MetadataReferences/NuGetMetadataReference.cs

Fixes #9337 
With this PR I'm excluding properties annotated with:
-  `JsonProperty(Required = Required.Always)`
-  `JsonProperty(Required = Required.AllowNull)`
-  `Newtonsoft.Json.JsonIgnore`
- `Newtonsoft.Json.JsonRequired`
- `System.Text.Json.Serialization.JsonRequired`
- `System.Text.Json.Serialization.JsonIgnore`
- `Range`

Fix S6964 FP: Add more attributes to the exclusions

---

analyzers/src/SonarAnalyzer.CSharp/Rules/UseAwaitableMethod.cs
analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
analyzers/tests/SonarAnalyzer.Test/Rules/UseAwaitableMethodTest.cs

Fix S6966 FP: Don't raise on XmlReader and XmlWriter methods

---

analyzers/src/SonarAnalyzer.CFG/ShimLayer/OperationInterfaces.xml

Add wrappers for `ICollectionExpressionOperation` and `ISpreadOperation`.
Done by copying the [OperationInterfaces.xml from the Roslyn repo](https://github.com/dotnet/roslyn/blob/8595c8d30a4546cf662dba9ae475b4a2c50fb922/src/Compilers/Core/Portable/Operations/OperationInterfaces.xml#L1) and removing the nullable reference types with find/replace.
Most of the changes are formatting, the only real changes are at the bottom of the file (the two new interfaces).

Update Shim Layer: Add wrappers for C# 12 Operations

---

pom.xml

For [the releasability check](https://xtranet-sonarsource.atlassian.net/wiki/spaces/LANG/pages/666292/C+and+VB.NET+analyzers+release+process#Check-for-Releasability) for 9.26.

Update ParentPOM for 9.26 Release

---

analyzers/src/SonarAnalyzer.CSharp/Rules/CatchRethrow.cs
analyzers/src/SonarAnalyzer.Common/Rules/CatchRethrowBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/CatchRethrow.cs
analyzers/tests/SonarAnalyzer.Test/Rules/CatchRethrowTest.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/CatchRethrow.Fixed.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/CatchRethrow.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/CatchRethrow.vb

Fix S2737 FP: Raised when exception filter is used

---

analyzers/its/expected/CSharpLatest/S2325-CSharpLatest-net8.0.json
analyzers/src/SonarAnalyzer.CSharp/Facade/CSharpSyntaxFacade.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/MemberShouldBeStatic.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/MemberShouldBeStatic.cs

Fix S2325 FP: Partial method implementations

---

analyzers/src/SonarAnalyzer.CSharp/Rules/NotAssignedPrivateMember.cs
analyzers/tests/SonarAnalyzer.Test/Rules/NotAssignedPrivateMemberTest.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/NotAssignedPrivateMember.CSharp9.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/NotAssignedPrivateMember.cs

Fix S3459 FP: Backing field with ref property

---

analyzers/src/SonarAnalyzer.CSharp/Rules/InvocationResolvesToOverrideWithParams.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/InvocationResolvesToOverrideWithParams.cs

Fix S3220 FP: Rule does not take into account generics

---

analyzers/its/expected/akka.net/S2743-Akka.Streams-netstandard2.0.json
analyzers/src/SonarAnalyzer.CSharp/Rules/StaticFieldInGenericClass.cs
analyzers/tests/SonarAnalyzer.Test/Rules/StaticFieldInGenericClassTest.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/StaticFieldInGenericClass.cs

Fix S2743 FP: Should not raise when base type is generic

---

analyzers/src/SonarAnalyzer.Common/Rules/MarkAssemblyWithAssemblyVersionAttributeBase.cs
analyzers/src/SonarAnalyzer.Common/Rules/MarkAssemblyWithClsCompliantAttributeBase.cs
analyzers/src/SonarAnalyzer.Common/Rules/MarkAssemblyWithComVisibleAttributeBase.cs
its/src/test/java/com/sonar/it/csharp/ProjectLevelDuplicationTest.java
sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/SarifParserCallbackImpl.java
sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/sarif/SarifParserCallbackImplTest.java

Allow for multiple project-level issues

---

analyzers/its/expected/akka.net/S2743-Akka.Streams-netstandard2.0.json
analyzers/src/SonarAnalyzer.CSharp/Rules/StaticFieldInGenericClass.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/StaticFieldInGenericClass.cs

Fix S2743 FN: Static fields of nested class inside generic class

---

analyzers/src/SonarAnalyzer.CSharp/Rules/InfiniteRecursion.RoslynCfg.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/InfiniteRecursion.SonarCfg.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/InfiniteRecursion.cs
analyzers/src/SonarAnalyzer.RuleDescriptorGenerator/packages.lock.json
analyzers/tests/SonarAnalyzer.Net8.UnitTest/packages.lock.json
analyzers/tests/SonarAnalyzer.Test/TestCases/InfiniteRecursion.RoslynCfg.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/InfiniteRecursion.SonarCfg.cs
analyzers/tests/SonarAnalyzer.UnitTest/packages.lock.json

Fixes #6642 
Fixes #6643 
Fixes #6644

Fix S2190 FN: Support indexer, conversion operator and event declaration

---

analyzers/its/expected/Ember-MM/S1871-Ember Media Manager.json
analyzers/its/expected/Ember-MM/S1871-EmberAPI.json
analyzers/its/expected/Ember-MM/S1871-generic.EmberCore.Notifications.json
analyzers/its/expected/akka.net/S1871-Akka.Cluster.Sharding-netstandard2.0.json
analyzers/its/expected/akka.net/S1871-Akka.Remote.TestKit-netstandard2.0.json
analyzers/src/SonarAnalyzer.CSharp/Rules/ConditionalStructureSameImplementation.cs
analyzers/src/SonarAnalyzer.Common/Rules/ConditionalStructureSameImplementationBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/ConditionalStructureSameImplementation.cs
analyzers/tests/SonarAnalyzer.Test/Rules/ConditionalStructureSameImplementationTest.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/ConditionalStructureSameImplementation_If.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/ConditionalStructureSameImplementation_If.vb
analyzers/tests/SonarAnalyzer.Test/TestCases/ConditionalStructureSameImplementation_Switch.Latest.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/ConditionalStructureSameImplementation_Switch.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/ConditionalStructureSameImplementation_Switch.vb

Fix S1871 FN: Support single line conditional block

---

analyzers/rspec/cs/S1144.html
analyzers/src/SonarAnalyzer.CSharp/Helpers/CSharpSymbolUsageCollector.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/UnusedPrivateMember.cs
analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
analyzers/tests/SonarAnalyzer.Test/Rules/UnusedPrivateMemberTest.Constructors.cs
analyzers/tests/SonarAnalyzer.Test/Rules/UnusedPrivateMemberTest.Fields.cs
analyzers/tests/SonarAnalyzer.Test/Rules/UnusedPrivateMemberTest.Methods.cs
analyzers/tests/SonarAnalyzer.Test/Rules/UnusedPrivateMemberTest.Types.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/UnusedPrivateMember.CSharp9.cs

Fixes #9379
RSpec change: https://github.com/SonarSource/rspec/pull/3992

Fix S1144 FP: types used through reflection

---

analyzers/src/SonarAnalyzer.CSharp/Helpers/CSharpSymbolUsageCollector.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/UnusedPrivateMember.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/UnusedPrivateMember.CSharp8.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/UnusedPrivateMember.CSharp9.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/UnusedPrivateMember.Fixed.Batch.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/UnusedPrivateMember.Fixed.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/UnusedPrivateMember.cs

Fix S1144 FP: Private attributes

---

.github/workflows/SlackNotification.yml

The workflow needs to be on the master branch to be triggered.
See the [documentation](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#check_run):
```
Note: This event will only trigger a workflow run if the workflow file is on the default branch.
```
Until then, no tests can be done.
Based on https://github.com/SonarSource/sonar-scanner-msbuild/blob/master/.github/workflows/SlackNotification.yml

Add GH action slack notification

---

analyzers/src/SonarAnalyzer.CFG/LiveVariableAnalysis/LiveVariableAnalysisBase.cs
analyzers/src/SonarAnalyzer.CFG/LiveVariableAnalysis/RoslynLiveVariableAnalysis.cs
analyzers/src/SonarAnalyzer.CSharp/LiveVariableAnalysis/SonarCSharpLiveVariableAnalysis.cs
analyzers/tests/SonarAnalyzer.Test/AnalysisContext/SonarAnalysisContextBaseTest.ShouldAnalyzeTree.cs
analyzers/tests/SonarAnalyzer.Test/LiveVariableAnalysis/RoslynLiveVariableAnalysisTest.LocalFunction.cs
analyzers/tests/SonarAnalyzer.Test/LiveVariableAnalysis/RoslynLiveVariableAnalysisTest.TryCatchFinally.cs
analyzers/tests/SonarAnalyzer.Test/LiveVariableAnalysis/RoslynLiveVariableAnalysisTest.cs
analyzers/tests/SonarAnalyzer.Test/LiveVariableAnalysis/SonarLiveVariableAnalysisTest.cs

Just taking the dust - no functional changes or other improvements 🧹 🧹 🧹 🧹 🧹 🧹 
I'll make meaningful functional cleanup changes, if needed, during actual work.

LVA: Coding style cleanup

---

analyzers/tests/SonarAnalyzer.Test/AnalysisContext/SonarAnalysisContextTest.Register.cs
analyzers/tests/SonarAnalyzer.Test/AnalysisContext/SonarSemanticModelReportingContextTest.cs
analyzers/tests/SonarAnalyzer.Test/AnalysisContext/SonarSyntaxNodeReportingContextTest.cs
analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/CodeFixProviderTest.cs
analyzers/tests/SonarAnalyzer.TestFramework/Analyzers/DummyAnalyzer.cs

Follow up on #9377
After this PR, there are still 12 `ReportIssue(diagnostic)` calls left. These require a bit more work to resolve, as they use a "collect and report later" approach.

Replace deprecated ReportIssue calls in UTs

---

analyzers/src/SonarAnalyzer.CSharp/Rules/CollectionsShouldImplementGenericInterface.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/DoNotDecreaseMemberVisibility.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/DoNotHideBaseClassMethods.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/DoNotShiftByZeroOrIntSize.cs

Follow up on #9422
Replaces 5 of the remaining 12 calls.

Replace deprecated ReportIssue in more locations

---

analyzers/src/SonarAnalyzer.CFG/ShimLayer/INamedTypeSymbolExtensions.Sonar.cs
analyzers/src/SonarAnalyzer.CFG/ShimLayer/INamedTypeSymbolExtensions.cs
analyzers/tests/SonarAnalyzer.Test/Wrappers/INamedTypeSymbolExtensionsTests.cs

Precondition for #8413
Exposes [INamedTypeSymbol.TypeArgumentNullableAnnotations](https://learn.microsoft.com/zh-tw/dotnet/api/microsoft.codeanalysis.inamedtypesymbol.typeargumentnullableannotations?view=roslyn-dotnet-4.7.0) (but not [IMethodSymbol.TypeArgumentNullableAnnotations](https://learn.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.imethodsymbol.typeargumentnullableannotations?view=roslyn-dotnet-4.7.0))

Shimlayer: Light up TypeArgumentNullableAnnotations

---

analyzers/src/SonarAnalyzer.CSharp/Rules/MethodsShouldNotHaveIdenticalImplementations.cs
analyzers/src/SonarAnalyzer.Common/Rules/MethodsShouldNotHaveIdenticalImplementationsBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/MethodsShouldNotHaveIdenticalImplementations.cs
analyzers/tests/SonarAnalyzer.Test/Rules/AspNet/UseAspNetModelBindingTest.cs
analyzers/tests/SonarAnalyzer.Test/Rules/MethodsShouldNotHaveIdenticalImplementationsTest.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/MethodsShouldNotHaveIdenticalImplementations.CSharp9.cs
analyzers/tests/SonarAnalyzer.TestFramework.Test/Common/CombinatorialDataTestMethodAttributeTest.cs
analyzers/tests/SonarAnalyzer.TestFramework/Common/CombinatorialDataAttribute.cs
analyzers/tests/SonarAnalyzer.TestFramework/Common/CombinatorialDataTestMethodAttribute.cs

Fix S4144 FP: when type constraints are used

---

analyzers/its/expected/Ember-MM/S2259-EmberAPI.json
analyzers/src/SonarAnalyzer.CFG/LiveVariableAnalysis/RoslynLiveVariableAnalysis.cs
analyzers/tests/SonarAnalyzer.Test/LiveVariableAnalysis/RoslynLiveVariableAnalysisTest.TryCatchFinally.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/DeadStores.RoslynCfg.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs

Fixes #9447
Fixes #8719
The FP is not visible in this PR, because it's muted by the rule, see #4940

Fix S1854 FP: Value used in `catch` or `when` should LiveIn for all try blocks

---

analyzers/its/expected/akka.net/S1144-Akka-netstandard2.0.json
analyzers/src/SonarAnalyzer.CSharp/Rules/UnusedPrivateMember.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/UnusedPrivateMember.Fixed.Batch.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/UnusedPrivateMember.Fixed.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/UnusedPrivateMember.cs

Fix S1144 FP: Nested types decorated with StructLayout attribute

---

analyzers/src/SonarAnalyzer.CSharp/Common/Walkers/MutedSyntaxWalker.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/DeadStores.RoslynCfg.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/DeadStores.SonarCfg.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Sonar/ConditionEvaluatesToConstant.CSharp7.cs

Fixes #4940
This is possible now, because #9448 and #9449 fixed the root cause of the FPs
Review per commit should be easier due to file-scoped namespace change

Fix S1854 FN: Proper support of try/catch statements

---

analyzers/rspec/cs/S1694.html
analyzers/rspec/cs/S1871.html
analyzers/rspec/cs/S4201.json
analyzers/rspec/vbnet/S1871.html
analyzers/rspec/vbnet/S4201.json
analyzers/src/SonarAnalyzer.CSharp/sonarpedia.json
analyzers/src/SonarAnalyzer.VisualBasic/sonarpedia.json

Update RSPEC before 9.28 release

---

analyzers/src/SonarAnalyzer.VisualBasic/Rules/ArrayPassedAsParams.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/ArrayPassedAsParams.vb

Fixes (https://cirrus-ci.com/task/4645507522363392?logs=build#L3923)

Fix S3878 AD0001: Cover the case of CollectionInitializerSyntax for VB.NET

---

analyzers/its/expected/CSharpLatest/S6966-NetCore31.MVC.ConfigurableRules-netcoreapp3.1.Views.json
analyzers/its/expected/Ember-MM/S2259-scraper.EmberCore.json
analyzers/its/expected/Nancy/S3900-Nancy-net452.json
analyzers/its/expected/Nancy/S3900-Nancy-netstandard2.0.json
analyzers/its/expected/Nancy/S3900-Nancy.Testing-net452.json
analyzers/its/expected/Nancy/S3900-Nancy.Testing-netstandard2.0.json
analyzers/its/expected/akka.net/S3900-Akka-netstandard2.0.json
analyzers/its/expected/akka.net/S3900-Akka.Cluster.TestKit-netstandard2.0.json
analyzers/its/expected/akka.net/S3900-Akka.Remote.TestKit-netstandard2.0.json
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Invocation.cs
analyzers/tests/SonarAnalyzer.Test/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Invocation.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.cs

Fixes #8907
For this PR, I had to build two lists of methods: 
* one that does early null-checking
* and one that doesn't, or does lazily when the enumerable is used somehow.
These lists may have changed over time, in different versions of .NET Framework and Core.
So I decided to be conservative and only include the (public) LINQ methods that do null-checking as precondition, i.e. right at the beginning of the call, and typically with code like `if (source == null) throw Error.ArgumentNull("source")`. The assumption is that null-checks are most likely going to be added, not removed.
I used `Enumerable.cs` from .NET Framework 4.0 for that, went through the merged class, and checked if the precondition is asserted right after the signature. That means that my list was not complete, and …

Fix S2259 FP: Engine does not learn `NotNull` from LINQ methods

---

analyzers/tests/SonarAnalyzer.Test/TestCases/DeadStores.RoslynCfg.cs

Reproduces  #9466, #9467, #9468

S1854: Add FP repro for #9466, #9467, #9468

---

analyzers/tests/SonarAnalyzer.Test/TestCases/DeadStores.RoslynCfg.cs

Related to #9471, #9472, #9473

S1854: Add FP repro for #9471, #9472, #9473

---

analyzers/src/SonarAnalyzer.CSharp/Rules/CastShouldNotBeDuplicated.cs
analyzers/tests/SonarAnalyzer.Test/Rules/CastShouldNotBeDuplicatedTest.cs

Preparation for #223
Review per commit will be easier due to file-scoped namespaces
Those uncovered cases are not coverable. Roslyn is introducing fake intermediate nodes into the tree for the switch labels and arms to work.

S3247 cleanup

---

analyzers/src/SonarAnalyzer.CSharp/Rules/UnusedPrivateMember.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/UnusedPrivateMember.CSharp7.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/UnusedPrivateMember.CSharp8.cs

Fixes #3842
To merge after #9459
S1144 will now ignore unused `Deconstruct` methods.
It ignores methods named `Deconstruct` with at least 1 parameter and when all parameters have the `out` reference keyword.

Fix S1144 FP: Ignore unused `Deconstruct` methods

---

analyzers/its/expected/akka.net/S3247-Akka-netstandard2.0.json
analyzers/src/SonarAnalyzer.CSharp/Rules/CastShouldNotBeDuplicated.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/CastShouldNotBeDuplicated.cs

Fix S3247 FP: Should not report on member access objects

---

analyzers/its/expected/Ember-MM/S3247-Ember.Plugins.json
analyzers/its/expected/Nancy/S3247-Nancy-net452.json
analyzers/its/expected/Nancy/S3247-Nancy-netstandard2.0.json
analyzers/its/expected/Nancy/S3247-Nancy.Validation.DataAnnotations-net452.json
analyzers/its/expected/Nancy/S3247-Nancy.ViewEngines.Razor-net452.json
analyzers/its/expected/akka.net/S3247-Akka-netstandard2.0.json
analyzers/its/expected/akka.net/S3247-Akka.Cluster-netstandard2.0.json
analyzers/its/expected/akka.net/S3247-Akka.DistributedData-netstandard2.0.json
analyzers/its/expected/akka.net/S3247-Akka.Persistence-netstandard2.0.json
analyzers/its/expected/akka.net/S3247-Akka.Persistence.Sql.Common-netstandard2.0.json
analyzers/its/expected/akka.net/S3247-Akka.Persistence.TCK-netstandard2.0.json
analyzers/its/expected/akka.net/S3247-Akka.Remote-netstandard2.0.json
analyzers/its/expected/akka.net/S3247-Akka.Remote.TestKit-netstandard2.0.json
analyzers/its/expected/akka.net/S3247-Akka.Streams-netstandard2.0.json
analyzers/its/expected/akka.net/S3247-Akka.TestKit-netstandard2.0.json
analyzers/its/expected/akka.net/S3247-Akka.Tests.Performance-netcoreapp3.1.json
analyzers/its/expected/akka.net/S3247-Akka.Tests.Shared.Internals-netstandard2.0.json
analyzers/src/SonarAnalyzer.CSharp/Rules/CastShouldNotBeDuplicated.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/CastShouldNotBeDuplicated.cs

Fixes #2120 
RSPEC update: https://github.com/SonarSource/rspec/pull/4019

Improve S3247: Rule should recommend pattern matching for new C# instead of as

---

analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Extensions/IInvocationOperationExtensions.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Invocation.Enumerable.cs
analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Invocation.cs
analyzers/tests/SonarAnalyzer.Test/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Invocation.cs

SE: Learn from bool collection methods

---

analyzers/src/SonarAnalyzer.CSharp/Rules/CastShouldNotBeDuplicated.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/CastShouldNotBeDuplicated.cs

Fix S3247 FN: When cast expression contains parentheses

---

analyzers/its/expected/akka.net/S1694-Akka-netstandard2.0.json
analyzers/its/expected/akka.net/S1694-Akka.Remote-netstandard2.0.json
analyzers/src/SonarAnalyzer.CSharp/Rules/AbstractClassToInterface.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/AbstractClassToInterface.CSharp11.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/AbstractClassToInterface.CSharp9.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/AbstractClassToInterface.cs

Fix S1694 FP: Cconstructors and fields

---

.github/workflows/LabelIssue.yml
.github/workflows/ToggleLockBranch.yml

Recreation of #9431 based on https://github.com/sonarsource/vault-action-wrapper?tab=readme-ov-file#vault-action-wrapper
Also related to https://github.com/SonarSource/gh-action-lt-backlog/pull/76 in the samples of the original actions

Bump vault-action-wrapper to v3

---

analyzers/its/Directory.Build.targets
analyzers/its/regression-test.ps1
analyzers/packaging/SonarAnalyzer.CSharp.Styling.nuspec
analyzers/packaging/SonarAnalyzer.CSharp.nuspec
analyzers/packaging/SonarAnalyzer.VisualBasic.nuspec
analyzers/src/Directory.Build.targets
analyzers/src/ITs.JsonParser/ITs.JsonParser.csproj
analyzers/src/RuleDescriptorGenerator/RuleDescriptorGenerator.csproj
analyzers/src/SonarAnalyzer.CSharp.Styling/SonarAnalyzer.CSharp.Styling.csproj
docs/contributing-analyzer.md
its/src/test/java/com/sonar/it/shared/StylingTest.java
sonar-csharp-plugin/pom.xml
sonar-vbnet-plugin/pom.xml

Change the structure of `analyzers/packaging/binaries` to have one folder per project.
This simplifies the clean-up process.
[Background Task](https://trello.com/c/0QOHiwL1/1360-future-proof-cleanbinaries-target)

Streamline packaging/binaries folder

---

analyzers/src/SonarAnalyzer.CSharp/Rules/FieldsShouldBeEncapsulatedInProperties.cs
analyzers/tests/SonarAnalyzer.Test/Rules/FieldsShouldBeEncapsulatedInPropertiesTest.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/FieldsShouldBeEncapsulatedInProperties.Unity3D.cs

Fixes #7522 
Ignore fields in the following Unity classes:
- [ScriptableObject](https://docs.unity3d.com/ScriptReference/ScriptableObject.html)
- [MonoBehaviour](https://docs.unity3d.com/ScriptReference/MonoBehaviour.html)

Fix S1104 FP: Do not report in Unity serializable classes

---

analyzers/src/SonarAnalyzer.CSharp/Rules/TestMethodShouldContainAssertion.cs
analyzers/tests/SonarAnalyzer.Test/Rules/TestMethodShouldContainAssertionTest.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/TestMethodShouldContainAssertion.Moq.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/TestMethodShouldContainAssertion.MsTest.cs

Fixes #7961 
I was not able to reproduce the FP.
Since the rule checks for method invocations that include the `Verify` word, we already support `Moq.` (see [UnitTestHelper.cs](https://github.com/SonarSource/sonar-dotnet/blob/master/analyzers/src/SonarAnalyzer.Common/Helpers/UnitTestHelper.cs#L57-L64))
I made an update in rspec to mention it: https://github.com/SonarSource/rspec/pull/4052
I only added test cases with Moq usage.

S2699: Add UTs for Moq

---

analyzers/src/SonarAnalyzer.CSharp/Rules/PrivateFieldUsedAsLocalVariable.cs
analyzers/tests/SonarAnalyzer.Test/Rules/PrivateFieldUsedAsLocalVariableTest.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/PrivateFieldUsedAsLocalVariable.cs

Fixes #8239
These changes treat method groups as invocation.

Fix S1450 FP when field is assigned value in event handler

---

analyzers/tests/SonarAnalyzer.Test/TestCases/RedundantCast.Fixed.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/RedundantCast.cs

Reproducer for S1905 FP: Floating point arithmetic

---

analyzers/src/SonarAnalyzer.CFG/LiveVariableAnalysis/RoslynLiveVariableAnalysis.cs
analyzers/tests/SonarAnalyzer.Test/LiveVariableAnalysis/RoslynLiveVariableAnalysisTest.TryCatchFinally.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/DeadStores.RoslynCfg.cs

Fix S1854 FP: Throw should connect to outer catch

---

analyzers/src/SonarAnalyzer.CFG/CfgSerializer/CfgSerializer.RoslynCfgWalker.cs
analyzers/src/SonarAnalyzer.CFG/CfgSerializer/CfgSerializer.RoslynLvaWalker.cs
analyzers/src/SonarAnalyzer.CFG/CfgSerializer/CfgSerializer.SonarCfgWalker.cs
analyzers/src/SonarAnalyzer.CFG/CfgSerializer/CfgSerializer.cs
analyzers/src/SonarAnalyzer.CFG/CfgSerializer/DotWriter.cs
analyzers/src/SonarAnalyzer.CFG/LiveVariableAnalysis/RoslynLiveVariableAnalysis.cs
analyzers/tests/SonarAnalyzer.Test/CFG/Roslyn/RoslynCfgSerializerTest.cs
analyzers/tests/SonarAnalyzer.Test/CFG/Roslyn/RoslynLvaSerializerTest.cs
analyzers/tests/SonarAnalyzer.Test/CFG/Sonar/SonarCfgSerializerTest.cs
analyzers/tests/SonarAnalyzer.Test/LiveVariableAnalysis/RoslynLiveVariableAnalysisTest.cs
analyzers/tests/SonarAnalyzer.TestFramework/Extensions/StringAssertionsExtensions.cs

The first commit is only CaYC.
I went a bit wild on cleaning...

LVA: Add CfgSerializer.RoslynLvaWalker

---

analyzers/its/expected/CSharpLatest/S1854-CSharpLatest-net8.0.json
analyzers/its/expected/akka.net/S1854-Akka-netstandard2.0.json
analyzers/src/SonarAnalyzer.CFG/LiveVariableAnalysis/RoslynLiveVariableAnalysis.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/DeadStores.RoslynCfg.cs
analyzers/src/SonarAnalyzer.CSharp/Rules/DeadStores.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/DeadStores.RoslynCfg.cs

Detect assignments to FlowCaptureReference operations

---

analyzers/src/SonarAnalyzer.CFG/CfgSerializer/CfgSerializer.RoslynLvaWalker.cs
analyzers/src/SonarAnalyzer.CFG/LiveVariableAnalysis/RoslynLiveVariableAnalysis.cs
analyzers/tests/SonarAnalyzer.Test/CFG/Roslyn/RoslynLvaSerializerTest.cs
analyzers/tests/SonarAnalyzer.Test/LiveVariableAnalysis/RoslynLiveVariableAnalysisTest.TryCatchFinally.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/DeadStores.RoslynCfg.cs

Fix S1854 FP: Throw should visit finally

---

analyzers/rspec/cs/S2971.json
analyzers/rspec/vbnet/S2358.json
analyzers/src/SonarAnalyzer.CSharp/sonarpedia.json
analyzers/src/SonarAnalyzer.VisualBasic/sonarpedia.json

Update RSPEC before 9.30 release

---

pom.xml
sonar-csharp-plugin/pom.xml
sonar-csharp-plugin/src/test/java/org/sonar/plugins/csharp/CSharpPluginTest.java
sonar-csharp-plugin/src/test/java/org/sonar/plugins/csharp/CSharpSonarWayProfileTest.java
sonar-dotnet-shared-library/pom.xml
sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/PropertyUtils.java
sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/CoverageReportImportSensorTest.java
sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/CoverageTest.java
sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/WildcardPatternFileProviderTest.java
sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/CodeCoverageProviderTest.java
sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/RoslynProfileExporterTest.java
sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/UnitTestResultsProviderTest.java
sonar-vbnet-plugin/pom.xml
sonar-vbnet-plugin/src/test/java/org/sonar/plugins/vbnet/VbNetPluginTest.java

Remove dependency on Google Guava library

---

analyzers/tests/SonarAnalyzer.Test/Rules/UsePascalCaseForNamedPlaceHoldersTest.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/UsePascalCaseForNamedPlaceHolders.Latest.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/UsePascalCaseForNamedPlaceHolders.cs

Add repro for S6678

---

its/pom.xml
its/src/test/java/com/sonar/it/shared/ScannerCliTest.java

SQ Plugin: Bump orchestrator to 5.0.0.2065

---

sonar-csharp-plugin/src/main/java/org/sonar/plugins/csharp/CSharpFileCacheSensor.java
sonar-csharp-plugin/src/main/java/org/sonar/plugins/csharp/CSharpPlugin.java
sonar-csharp-plugin/src/main/java/org/sonar/plugins/csharp/CSharpPropertyDefinitions.java
sonar-csharp-plugin/src/test/java/org/sonar/plugins/csharp/CSharpFileCacheSensorTest.java
sonar-csharp-plugin/src/test/java/org/sonar/plugins/csharp/CSharpPluginTest.java
sonar-csharp-plugin/src/test/java/org/sonar/plugins/csharp/CSharpSonarRulesDefinitionTest.java
sonar-csharp-plugin/src/test/java/org/sonar/plugins/csharp/CSharpTest.java
sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/AbstractFileCacheSensor.java
sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/AbstractPropertyDefinitions.java
sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/RoslynDataImporter.java
sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/AbstractFileCacheSensorTest.java
sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/AbstractRulesDefinitionTest.java
sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/GeneratedFileFilterTest.java
sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/RoslynDataImporterTest.java
sonar-vbnet-plugin/src/main/java/org/sonar/plugins/vbnet/VbNetFileCacheSensor.java
sonar-vbnet-plugin/src/main/java/org/sonar/plugins/vbnet/VbNetPlugin.java
sonar-vbnet-plugin/src/main/java/org/sonar/plugins/vbnet/VbNetPropertyDefinitions.java
sonar-vbnet-plugin/src/test/java/org/sonar/plugins/vbnet/VbNetFileCacheSensorTest.java
sonar-vbnet-plugin/src/test/java/org/sonar/plugins/vbnet/VbNetPluginTest.java
sonar-vbnet-plugin/src/test/java/org/sonar/plugins/vbnet/VbNetTest.java

SQ Plugin: Remove old runtime version checks

---

sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/CoverageReportImportSensor.java
sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/CodeCoverageProvider.java
sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/CoverageAggregatorTest.java
sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/CoverageReportImportSensorTest.java
sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/CodeCoverageProviderTest.java
sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/UnitTestResultsProviderTest.java

SQ Plugin: Remove deprecated import of integration test coverage from plugins

---

analyzers/its/expected/CSharpLatest/S1854-CSharpLatest-net8.0.json
analyzers/src/SonarAnalyzer.CFG/LiveVariableAnalysis/RoslynLiveVariableAnalysis.cs
analyzers/tests/SonarAnalyzer.Test/LiveVariableAnalysis/RoslynLiveVariableAnalysisTest.FlowCaptureOperation.cs
analyzers/tests/SonarAnalyzer.Test/LiveVariableAnalysis/RoslynLiveVariableAnalysisTest.LocalFunction.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/DeadStores.RoslynCfg.cs

Fix S1854 FN: Support &&, ||, ?? and ??=

---

analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs

Reproduce S2583 FP: indexer does not throw exception

---

pom.xml
sonar-csharp-plugin/src/test/java/org/sonar/plugins/csharp/CSharpSonarRulesDefinitionTest.java
sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/AbstractRulesDefinitionTest.java
sonar-dotnet-shared-library/src/test/resources/AbstractRulesDefinitionTest/Rules.json
sonar-dotnet-shared-library/src/test/resources/AbstractRulesDefinitionTest/S1117.html
sonar-dotnet-shared-library/src/test/resources/AbstractRulesDefinitionTest/S1117.json

Add support for STIG standard

---

sonar-csharp-plugin/src/main/java/org/sonar/plugins/csharp/CSharpFileCacheSensor.java
sonar-csharp-plugin/src/test/java/org/sonar/plugins/csharp/CSharpFileCacheSensorTest.java
sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/AbstractFileCacheSensor.java

SQ Plugin: Include cshtml files in caching

---

sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/CoverageParser.java
sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/DotCoverReportParser.java
sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/NCover3ReportParser.java
sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/OpenCoverReportParser.java
sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/ScannerFileService.java
sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/DotCoverReportParserTest.java
sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/NCover3ReportParserTest.java
sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/OpenCoverReportParserTest.java
sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/ScannerFileServiceTest.java

SQ Plugin: Should align logging for not indexed files

---

analyzers/tests/SonarAnalyzer.Test/TestCases/DeadStores.RoslynCfg.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/MethodParameterUnused.RoslynCfg.Fixed.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/MethodParameterUnused.RoslynCfg.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.cs

LVA: Add UTs after validation

---

analyzers/src/SonarAnalyzer.CSharp/Rules/UseAwaitableMethod.cs
analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/UseAwaitableMethod_EF.cs

Fix S6966 FP: EntityFrameworks IDbContextFactory CreateDbContext method is preferred over its Async counterpart

---

analyzers/src/SonarAnalyzer.CSharp/Rules/StreamReadStatement.cs

RSPEC PR: https://github.com/SonarSource/rspec/pull/4120

S2674 Cleanup for SonarWay promotion

---

analyzers/src/SonarAnalyzer.ShimLayer/README.md

Update the README file

---

analyzers/src/SonarAnalyzer.ShimLayer/Syntax.xml

Part of the fix for #9600
Roslyn [Syntax.xml](https://github.com/dotnet/roslyn/blob/release/dev17.12/src/Compilers/CSharp/Portable/Syntax/Syntax.xml)

Update Syntax.xml from Roslyn release/dev17.12 branch

---

analyzers/src/SonarAnalyzer.ShimLayer/Sonar/TypeDeclarationSyntaxExtensions.cs
analyzers/src/SonarAnalyzer.ShimLayer/TypeDeclarationSyntaxExtensions.cs

Fix Shimlayer after peach validation
dotnet runtime
`C:\nuget\microsoft.net.compilers.toolset\4.0.0-4.21427.11\tasks\netcoreapp3.1\Microsoft.CSharp.Core.targets(75,5): error :    at StyleCop.Analyzers.Lightup.RecordDeclarationSyntaxWrapper.get_ParameterList() [C:\sonar-ci\Project\src\tasks\WorkloadBuildTasks\WorkloadBuildTasks.csproj]`
lethetus-ide
`C:\Program Files\dotnet\sdk\7.0.410\Roslyn\Microsoft.CSharp.Core.targets(80,5): error :    at StyleCop.Analyzers.Lightup.TypeDeclarationSyntaxExtensions.ParameterList(Microsoft.CodeAnalysis.CSharp.Syntax.TypeDeclarationSyntax) [C:\sonar-ci\Project\Luthetus.Common\Source\Lib\Luthetus.Common.RazorLib\Luthetus.Common.RazorLib.csproj]`

Shimlayer: Fix TypeDeclarationSyntax ParameterList for RecordDeclarationSyntax

---

analyzers/src/SonarAnalyzer.CSharp/Rules/ExpectedExceptionAttributeShouldNotBeUsed.cs
analyzers/src/SonarAnalyzer.Common/Rules/ExpectedExceptionAttributeShouldNotBeUsedBase.cs
analyzers/src/SonarAnalyzer.VisualBasic/Rules/ExpectedExceptionAttributeShouldNotBeUsed.cs
analyzers/tests/SonarAnalyzer.Test/Rules/ExpectedExceptionAttributeShouldNotBeUsedTest.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/ExpectedExceptionAttributeShouldNotBeUsed.MsTest.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/ExpectedExceptionAttributeShouldNotBeUsed.MsTest.vb
analyzers/tests/SonarAnalyzer.Test/TestCases/ExpectedExceptionAttributeShouldNotBeUsed.NUnit.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/ExpectedExceptionAttributeShouldNotBeUsed.NUnit.vb

Fixes #8300 
RSPEC PR: https://github.com/SonarSource/rspec/pull/4127

Fix S3431 FP: Don't raise if assertions are done in catch or finally

---

analyzers/tests/SonarAnalyzer.Test/Extensions/SyntaxNodeExtensionsTest.cs

Increasing the threshold to 1,5s for a flaky UT (CreateCfg_Performance_UsesCache_CS)

Increase threshold of flaky UT

---

analyzers/src/SonarAnalyzer.CSharp/Rules/OperatorsShouldBeOverloadedConsistently.cs
analyzers/tests/SonarAnalyzer.Test/TestCases/OperatorsShouldBeOverloadedConsistently.cs

[RSPEC PR](https://github.com/SonarSource/rspec/pull/4135)

S4050: Promote to SonarWay
